### ISSUE TITLE
Нереалистичный перевод

### ISSUE THREAD

**Issue by SuperZombi** [ilyhalight/voice-over-translation#10]
Я когда-то давно скачивал яндекс браузер и мне прям очень зашла эта фишка с переводом, но ваш плагин, как мне кажется использует другой способ для перевода, либо яндекс скатились. Но переводит в стиле "аля гугл транслате". Мне не зашло(

**Comment by ilyhalight** [comment]
> Я когда-то давно скачивал яндекс браузер и мне прям очень зашла эта фишка с переводом, но ваш плагин, как мне кажется использует другой способ для перевода, либо яндекс скатились. Но переводит в стиле "аля гугл транслате". Мне не зашло(

Жаль, что не понравилось =(
Плагин использует тот же перевод, что и обычный Яндекс Браузер. На счёт самого перевода - не могу не согласится, что переводчик видео от Яндекса довольно плохо переводит специфичные слова/сокращения/ит-термины и т.п. (хотя порой и с обычными видео у него бывают проблемы).

**Comment by SuperZombi** [comment]
Я включил видосик про jpg vs png. И он png переводил вобще как другое слово))

**Comment by SuperZombi** [comment]
ЭЭэээээ. щас еще раз скачал для того чтобы найти тот момент. Ну png он по прежнему произносит как "Инь" какойто. Но теперь перевод стал лучше...? Чта? Лол
