### ISSUE TITLE
Видео не удалось извлечь. Возможная ошибка: null

### ISSUE THREAD

**Issue by SeekerLightOri** [ilyhalight/voice-over-translation#1004]
### Operating system / Операционная система

Windows 11 Pro 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.3

### Describe the bug / Опишите ошибку

При попытке перевести видео на сайте [artstation.com](https://www.artstation.com/learning) выдаёт ошибку:
![Screenshot_2](https://github.com/user-attachments/assets/89903486-e21d-4d9f-9bf8-9a0a773f4c7e)

**Comment by ilyhalight** [comment]
Проблемы с сетью на сервере, ожидайте, скоро само решится
