### ISSUE TITLE
Оверлей не скрывается

### ISSUE THREAD

**Issue by KoyomiNya** [ilyhalight/voice-over-translation#1005]
### Operating system / Операционная система

Android 11

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.3

### Describe the bug / Опишите ошибку

При воспроизведении видео оверлей не скрывается. В версии 1.8.1 не было этой проблемы. Проблему наблюдал в Яндекс диске.
Как было в версии 1.8.1: https://disk.yandex.ru/i/ddb6lvm4lXb_Xw
Проблема в версии 1.8.3: https://disk.yandex.ru/i/MD61Oqo2bqFuwQ

**Comment by ilyhalight** [comment]
Попробуйте [эту](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версию

**Comment by KoyomiNya** [comment]
> Попробуйте [эту](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версию

Спасибо, теперь всё работает :)
