### ISSUE TITLE
Не свайпается экран при воспроизведении видео

### ISSUE THREAD

**Issue by KoyomiNya** [ilyhalight/voice-over-translation#1006]
### Operating system / Операционная система

Android 11

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.3

### Describe the bug / Опишите ошибку

При воспроизведении видео невозможно свайпать в области отображения плеера. В версии 1.8.1 не было этой проблемы. Проблему наблюдал в Яндекс диске.
Как было в версии 1.8.1: https://disk.yandex.kz/i/ddb6lvm4lXb_Xw
Проблема в версии 1.8.3: https://disk.yandex.kz/i/MD61Oqo2bqFuwQ

**Comment by ilyhalight** [comment]
Попробуйте [эту](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версию
