### ISSUE TITLE
Почему пропала возможность переводить на другие языки кроме английского и казахского ?

### ISSUE THREAD

**Issue by Koaxz** [ilyhalight/voice-over-translation#1009]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.4

### Describe the bug / Опишите ошибку

До версии 1.5 была возможность выбрать практически любой язык

### Additional information / Дополнительная информация

![изображение](https://github.com/user-attachments/assets/9538a6c4-feef-41e8-aaeb-7dad8caefd9a)

**Comment by SashaXser** [comment]
04.11.2023 большинство языков, доступных для выбора в качестве озвучки, были отключены на стороне Яндекса. Я не знаю, будут ли они возвращены позже или нет. Из тех, что точно можно перевести, есть: Русский, Английский, Казахский.

**Comment by ilyhalight** [comment]
Ограничение API
