### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by JulyKapuza** [ilyhalight/voice-over-translation#102]
c 17.02 перевод работал, последнюю неделю выбивает ошибку 
 Uncaught Не удалось запросить перевод видео  
userscript.html?name=Voice%2520Over%2520Translations.user.js&id=8309a2e6-fbf7-496c-8243-1b6c39b6e824:1031

блокировки рекламы нет, использую расширение Tampermonkey, браузер Chrome.Что можно сделать?

**Comment by ten4dinosaur** [comment]
Лучше всего скинь лог запроса. Если не знаешь как, попробуй версию под клоудфлаер. Т.к сам метод не пофиксили и он работает, только что проверил

**Comment by ilyhalight** [comment]
> c 17.02 перевод работал, последнюю неделю выбивает ошибку
Uncaught Не удалось запросить перевод видео
userscript.html?name=Voice%2520Over%2520Translations.user.js&id=8309a2e6-fbf7-496c-8243-1b6c39b6e824:1031

> блокировки рекламы нет, использую расширение Tampermonkey, браузер Chrome.Что можно сделать?

Как сказали выше, нужен лог запроса, дабы понять, что именно идет не так при попытке сделать этот самый запрос
