### ISSUE TITLE
Не удается пройти установку npm install (vot-cli)

### ISSUE THREAD

**Issue by D4Vinci-CDM** [ilyhalight/voice-over-translation#103]
Подскажите, что нужно делать в таком случае ?
![Снимок экрана 2023-03-29 в 6 18 12](https://user-images.githubusercontent.com/65075208/228395316-13a3c382-688a-4d36-9706-8820997a05cf.png)

**Comment by ilyhalight** [comment]
> Подскажите, что нужно делать в таком случае ?

У вас всё правильно установилось. А данная надпись означает, что данные пакеты просят их поддержать материально (необязательно). Если возникает какая-то ошибка при запуске самой программы, то предоставьте ее.
