### ISSUE TITLE
Перевод Библейских цитат некачественный

### ISSUE THREAD

**Issue by arminianin** [ilyhalight/voice-over-translation#105]
Привожу пример с этого видео https://www.youtube.com/watch?v=jB7EZ5fgr4I Здесь на 20:05 Цитата из Библии Левит 17 глава 11 стих -- переводится как тысяча семьсот одиннадцать.... я не знаю к кому обратиться..... написал кстати в техподдержку Яндекса, обещали исправить.... И решил ещё здесь озвучить эту проблему

**Comment by ilyhalight** [comment]
> Привожу пример с этого видео https://www.youtube.com/watch?v=jB7EZ5fgr4I Здесь на 20:05 Цитата из Библии Левит 17 глава 11 стих -- переводится как тысяча семьсот одиннадцать.... я не знаю к кому обратиться..... написал кстати в техподдержку Яндекса, обещали исправить.... И решил ещё здесь озвучить эту проблему

А я, то, что могу с этим сделать? Не я же перевожу видео :)

P.S.; Ждите, пока ребята из Яндекса исправят

**Comment by arminianin** [comment]
Я как бы так и думал, ну мало ли, решил озвучить и узнать, а вдруг что-то можно решить......

**Comment by arminianin** [comment]
Я как бы так и думал, ну мало ли, решил озвучить и узнать, а вдруг что-то можно решить...... Спасибо огромное за возможность пользоваться данным приложением.... Именно благодаря ВАМ получил доступ ко многим видео материалам!!!!
