### ISSUE TITLE
Перевод длинных видео

### ISSUE THREAD

**Issue by 9dogs** [ilyhalight/voice-over-translation#106]
Привет и спасибо за отличное расширение!
Я пытаюсь понять, как лучше подступиться к переводу длинного видео (4 часа 20 минут). Как я понимаю, Яндексу нужна публичная ссылка, так что пока идея отпилить кусок видео, чтобы влезало в лимит, и залить как private на ютуб (и то не знаю, насколько велика опасность словить страйк за копирайт). Может еще какие-нибудь идеи подскажешь?

**Comment by ilyhalight** [comment]
> и то не знаю, насколько велика опасность словить страйк за копирайт

Ютуб, вроде бы, не дает автоматические страйки за контент (за исключением, некоторой музыки, из-за которой видео могут заблокировать в некоторых странах). Он максимум, ограничивает монетизацию для таких видео. Так же, можно залить видео с доступом по ссылке, или, вовсе, залить его на vimeo, где, как мне кажется, всё не так строго с авторскими правами.
