### ISSUE TITLE
Можно ли вернуть twitter?

### ISSUE THREAD

**Issue by texi7** [ilyhalight/voice-over-translation#108]
Почему то (из за блокировки?) разрабы убрали twitter и поэтому хотел спросить. Возможно ли его возвращение в этом расширении? Если он уже был официально то вроде как вернуть его не будет сложно надеюсь, верно? ( .   с    .)

**Comment by ilyhalight** [comment]
Можно вернуть, как доработаю визуальную часть добавлю
![изображение](https://user-images.githubusercontent.com/62353659/230691014-d8c60ba8-deed-4448-99a8-bb003de45adf.png)

**Comment by ilyhalight** [comment]
Добавил поддержку в обычную версию расширения, для cloudflare-версии появится немного позже с выходом обновления 1.1.0
