### ISSUE TITLE
Субтитры

### ISSUE THREAD

**Issue by HarwoodKinnav** [ilyhalight/voice-over-translation#11]
Планируется (или скорее возможно) ли в будущем прикрутить еще и субтитры? В ютубе они работают куда лучше, чем стандартные гугловские.
![image](https://user-images.githubusercontent.com/108170978/182418375-505fa504-b159-45c5-ad96-d366064fa0dd.png)

**Comment by DmitriyPekar** [comment]
#1 
![image](https://user-images.githubusercontent.com/14822106/182565080-a8e72ba7-ff4c-4a74-8d9f-2059bff804ae.png)
