### ISSUE TITLE
возможность перевода на coursehunter.net

### ISSUE THREAD

**Issue by edstarck** [ilyhalight/voice-over-translation#111]
Здравствуйте!
Можно ли добавить возможность перевода на видео с https://coursehunter.net/
Спасибо за Ваше расширение!!!

**Comment by ilyhalight** [comment]
К сожалению, не получится, ограничены, только, этим списком сайтов (и то, сейчас, не все эти сайты поддерживает расширение)
![изображение](https://user-images.githubusercontent.com/62353659/231311861-6fcf7721-d1b1-4323-b9d4-21a6b1a8c627.png)

**Comment by ilyhalight** [comment]
Добавлено еще в 1.5.0.4
