### ISSUE TITLE
Не работает на Apple Developer

### ISSUE THREAD

**Issue by EvgeniyKostin** [ilyhalight/voice-over-translation#112]
https://developer.apple.com/videos/ 

Добавьте пожалуйста возможность перевода для этого раздела. Заранее благодарю!

**Comment by ilyhalight** [comment]
К сожалению сам яндексовский переводчик видео имеет определённый список поддерживаемых сайтов в котором нету apple

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
