### ISSUE TITLE
Добавление поддержки 

### ISSUE THREAD

**Issue by BioXeon** [ilyhalight/voice-over-translation#113]
Прошу добавить поддержку на сайте nebula.tv Заранее очень признателен

**Comment by ilyhalight** [comment]
К сожалению сам яндексовский переводчик видео имеет определённый список поддерживаемых сайтов в котором нету этого сайта

**Comment by BioXeon** [comment]
А может подскажешь аналогичные Яндексу сервисы с VoT?

**Comment by ilyhalight** [comment]
К сожалению именно сервисов, которые так же автоматически переводят видео на том же Ютубе и не берут за это ни копейки не знаю. Можно сделать что-то очень близкое к Яндексу с помощью [этой](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs) утилиты, но там нужны субтитры + скорее всего потребуется заплатить за использование сторонних апи.
