### ISSUE TITLE
Перевод в смартфонной разметке

### ISSUE THREAD

**Issue by shaman1010** [ilyhalight/voice-over-translation#114]
Android 12 , firefox 111.11.1, в предыдущем было аналогично.
m.youtube 
В смартфонной разметке кнопка перевода появляется только если перезагрузить страницу, при первом открытии кнопки нет. Но это меньший глюк.
При обновлении страницы - кнопка появляется, на нажатия реагирует, пускает сделать настройки (громкость, автостарт и т.д.) ведет себя нормально, кроме одного - не переводит. Даже звук оригинальной дорожки приглушает, но переведенную дорожку не добавляет.
При этом, если переключиться в полный режим - все работает нормально (только навигация на смартфоне полным интерфейсом - сильно неудобная).

**Comment by ilyhalight** [comment]
Да, такая проблема есть, но как ее отследить, кроме как "методом тыка" - я не знаю. Для этого нужна консоль, а удаленная отладка у меня не запускается ¯\_(ツ)_/¯. Ничего не могу обещать на счёт исправления этого бага.

**Comment by Waffelson** [comment]
Проблема скорее не с Фаерфоксом а его юзер агентом, этот баг можно воспроизвести на настольных браузерах с помощью расширения для отделки браузера и ос, если хочешь использовать Фаерфокс, можешь скачать его бета версию, в ней можно установить больше аддонов и тот который поможет в решении проблемы

**Comment by ilyhalight** [comment]
Наверное, уже неактуально
