### ISSUE TITLE
Видео в твитере не переводятся

### ISSUE THREAD

**Issue by vocalir145** [ilyhalight/voice-over-translation#119]
При нажатии на кнопку "Перевести видео" выводится следущее сообщение:

Error: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.twimg.com https://recaptcha.net/recaptcha/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://client-api.arkoselabs.com/ https://www.google-analytics.com https://twitter.com https://app.link https://accounts.google.com/gsi/client https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js  'nonce-MTFiZWE2NzAtMGFmYy00MmIwLTllM2ItMmEzZmRlNDVhMzU5'".

Перевод в ленте не работает, это понятно. Но когда открываешь видео из ленты, кнопки перевода нет, приходится перезагрузать страницу чтобы она появилась, было бы хорошо и это пофиксить тоже

**Comment by ilyhalight** [comment]
После релиза 1.1.1 буду пытаться разобраться с твитером

**Comment by vocalir145** [comment]
Желаю всего хорошего

**Comment by ilyhalight** [comment]
Из-за CSP не работает. Попробуйте установить [это расширение](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related) и включить для нужного вам сайта (просто нажмите на значок расширения, чтобы он загорелся фиолетовым и перезагрузите страницу). Должно помочь. 

**Включайте только на сайтах, где не работает!**

**Comment by vocalir145** [comment]
> Из-за CSP не работает. Попробуйте установить [это расширение](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related) и включить для необходимого вам сайта (просто нажмите на значок расширения, он загорелся фиолетовым и перезагрузите страницу). Должно помочь.
> 
> **Включайте только на сайтах, где не работает!**

Теперь кнопка нажимается и просит подождать, как когда видео переводится впервые, но подождав выводится сообщение "Возникла ошибка, попробуйте позже"

**Comment by ilyhalight** [comment]
> Теперь кнопка нажимается и просит подождать, как когда видео переводится впервые, но подождав выводится сообщение "Возникла ошибка, попробуйте позже"

Это уже звучит как пррблема на стороне яндекса
