### ISSUE TITLE
Поддержка Piped

### ISSUE THREAD

**Issue by il2020** [ilyhalight/voice-over-translation#124]
Добавьте, пожалуйста, поддержку Piped.

https://github.com/TeamPiped/Piped
https://github.com/TeamPiped/Piped/wiki/Instances

**Comment by ilyhalight** [comment]
После выхода обновления 1.1.1. скорее всего добавлю

**Comment by ilyhalight** [comment]
Добавлено в 1.1.2. Протестировано, только, на piped.video
