### ISSUE TITLE
с русского на английский на YouTube

### ISSUE THREAD

**Issue by Patraskon** [ilyhalight/voice-over-translation#129]
Как ей воспользоваться ?

**Comment by ilyhalight** [comment]
> Сейчас, при нажатие на кнопку "перевести видео" должен автоматически определяться язык видео, и если язык видео русский, то будет запрашиваться перевод с русского на английский язык. Скорее всего в следующих обновлениях сделаю возможность самому указать с какого языка на какой необходимо переводить, ибо не всегда точно определяется.

Посмотреть, какой язык видео установился можно, пока что, только, в консоли:
![image](https://user-images.githubusercontent.com/62353659/234309583-31421c8b-492d-47d4-a9f6-c617a42a0503.png)

**Comment by barbaduk** [comment]
> > Сейчас, при нажатие на кнопку "перевести видео" должен автоматически определяться язык видео, и если язык видео русский, то будет запрашиваться перевод с русского на английский язык. Скорее всего в следующих обновлениях сделаю возможность самому указать с какого языка на какой необходимо переводить, ибо не всегда точно определяется.
> 
> Посмотреть, какой язык видео установился можно, пока что, только, в консоли: DetectedLanguage - Автоматически определенный язык видео ResponseLanguage - Язык на который будет перевод ![image](https://user-images.githubusercontent.com/62353659/234309583-31421c8b-492d-47d4-a9f6-c617a42a0503.png)

у меня некоторые видео детектятся, как en, хотя язык русский. Соответственно выдаётся ошибка "Не удалось перевести, на видео отсутствует речь для перевода". Как-то можно принудительно указать язык для распознавания?

**Comment by ilyhalight** [comment]
> Как-то можно принудительно указать язык для распознавания

Пока такой функции нету

**Comment by ilyhalight** [comment]
Добавлено в 1.2.0 / 1.2.1
