### ISSUE TITLE
Не работает в AdGuard

### ISSUE THREAD

**Issue by Pro100BooM** [ilyhalight/voice-over-translation#13]
Добавте поддержку работы в AdGuard user script

**Comment by ilyhalight** [comment]
Не знаю как можно было бы исправить запрос для этого расширения.

Используй [Tampermonkey ](https://www.tampermonkey.net/)/ [Violetmonkey ](https://violentmonkey.github.io/get-it/)/ [Userscripts (safari)](https://apps.apple.com/app/userscripts/id1463298887)

**Comment by Baltazar500** [comment]
Тоже интересует работа данного скрипта в рамках AdGuard и в частности на Android (там tampermonkey и прочие не прикрутишь). VOT - скрипт в AdGuard успешно воткнулся и даже панелька при просмотре видео появилась. Вот только при попытке перевода идётобломинго и панелька выкидывает "Не удалось запросить перевод видео". Вероятно не учтены какие-то нюансы AdGuard'овского user-js движка и нужен допил скрипта. Ну или AdGuard'овского user-js движок не поддерживает то, что используется в данном скрипте. Вопрос в том, что ? ...

**Comment by ram108** [comment]
Аналогичная история. Пробовал скрипт в AdGuard на Android и на Windows. Выскакивает ошибка о невозможности перевести видео.

**Comment by ask0rd** [comment]
Столкнулся с аналогичной проблемой в Safari на macOS. Отключил расширения в настройках AdGuard, отключил помощника AdGuard в настройках Safari, перезапустил браузер, нажал "установить скрипт" повторно. UserScript перехватил скрипт и добавил к себе, в обход AdGuard. Работает. Включил весь функционал AdGuard обратно - тоже работает.

**Comment by ask0rd** [comment]
Столкнулся с аналогичной проблемой в Safari на macOS. Отключил расширения в настройках AdGuard, отключил помощника AdGuard в настройках Safari, перезапустил браузер, нажал "установить скрипт" повторно. UserScript перехватил скрипт и добавил к себе, в обход AdGuard. Работает. Включил весь функционал AdGuard обратно - тоже работает.

**Comment by Baltazar500** [comment]
Посмотрел har-дамп самого AdGuard'а при отработке скрипта и ничего кроме запросов

>https://icongr.am/entypo/language.svg?size=18&color=ffffff
>https://icongr.am/entypo/dots-three-vertical.svg?size=14&color=ffffff
>https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/img/YAlice.svg

которые происходят при открытии панельки не увидел. Никаких xhr - запросов до api.browser.yandex.ru, да и в принципе xhr - запросов не было. Тут или чего-то не хватает в скрипте или в движке самого AdGuard'a.
