### ISSUE TITLE
Ошибка при открытии YouTube, Twitch и т.д...

### ISSUE THREAD

**Issue by Spuner** [ilyhalight/voice-over-translation#130]
После обновления скрипта, при открытии Twitch - выскакивает ошибка... До обновления на 1.1.1 - такого не было.

![2023-04-25 16_43_00-Twitch – Cent Browser](https://user-images.githubusercontent.com/30773815/234280501-e1f24c98-513f-4ac8-83e4-ea1ae65021d0.png)

**Comment by ilyhalight** [comment]
У вас скорее всего из-за ошибки #116 обновилось на обычную версию расширению. Установите vot-cloudflare

**Comment by Spuner** [comment]
Извините, а поподробнее можно?

**Comment by ilyhalight** [comment]
Удалите текущую версию скрипта и установите cloudflare версию по ссылке указанной на скриншоте
![image](https://user-images.githubusercontent.com/62353659/235329351-64befcba-67ac-427b-8ee3-cf294130023d.png)
