### ISSUE TITLE
Increase the distance between the slider and the download button

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#132]
Voice Over Translation v.1.1.1

---

Google Chrome – macOS

<img width="284" alt="Screen Shot 2023-04-26 at 19 27 10" src="https://user-images.githubusercontent.com/62497891/234651996-82675931-def1-4d32-9d23-d1a7ef1a867a.png">

---

Mozilla Firefox – macOS

<img width="1279" alt="Mozilla Firefox – macOS" src="https://user-images.githubusercontent.com/62497891/234678690-505a488b-1b2b-4766-9b0e-ff3eb26d9e0b.png">

---

Mozilla Firefox – linux Fedora 38

<img width="1243" alt="Mozilla Firefox – linux Fedora 38" src="https://user-images.githubusercontent.com/62497891/234678820-686b8a5f-b7ab-4515-a5eb-6115d54c3bce.png">

---

Google Chrome – linux Fedora 38

<img width="1324" alt="Google Chrome – linux Fedora 38" src="https://user-images.githubusercontent.com/62497891/234681449-cb63fcfc-638d-4c98-be46-87184e3be217.png">

---

Example:

<img width="284" alt="Screen Shot 2023-04-26 at 19 27 10 copy" src="https://user-images.githubusercontent.com/62497891/234653078-05b87b83-2278-4faa-adbe-32d7b8d8d72e.png">

**Comment by ilyhalight** [comment]
Will be added in the next update

**Comment by ilyhalight** [comment]
Fixed in 1.1.2
