### ISSUE TITLE
Не удалось запросить перевод видео(

### ISSUE THREAD

**Issue by Kriselov** [ilyhalight/voice-over-translation#133]
Хром. Показывает "Не удалось запросить перевод видео" Устанавливал по описанию.  Украина. Виндовс 10.  На MS Edge теж саме.  Что делать?
![2023-04-27_233304](https://user-images.githubusercontent.com/132014850/234985384-32e3b6e6-e5e7-4dc7-91b3-a7ac65f0b943.jpg)
![2023-04-27_233539](https://user-images.githubusercontent.com/132014850/234985418-a384cedc-f2f1-49e3-a0da-53310134fad1.jpg)

**Comment by Kriselov** [comment]
На MS Edge тоже самое

**Comment by ilyhalight** [comment]
Попробуйте использовать впн

**Comment by ilyhalight** [comment]
> Попробуйте использовать впн

или версию для cloudflare, дабы не использовать впн, там по идеи такой проблемы не должно быть

**Comment by Kriselov** [comment]
> Попробуйте использовать впн

Установил впн расширение - заработало) А где оно есть cloudflare и как ее установить? Спасибо

**Comment by ilyhalight** [comment]
> > Попробуйте использовать впн
> 
> Установил впн расширение - заработало) А где оно есть cloudflare и как ее установить? Спасибо

Чуть-чуть ниже эта версия.
![image](https://user-images.githubusercontent.com/62353659/235012358-1a253898-1dbd-4238-b11a-35167263bed1.png)

**Comment by Kriselov** [comment]
Не работает cloudflare. Не так не через впн.
![2023-04-28_132122](https://user-images.githubusercontent.com/132014850/235127673-f63c3957-ee7f-42b7-a4e2-8ef76e97143c.jpg)
![2023-04-28_132045](https://user-images.githubusercontent.com/132014850/235127711-c9d4be53-d979-445a-a066-9afd9a1a8168.jpg)
![2023-04-28_133727](https://user-images.githubusercontent.com/132014850/235127732-cee42671-dab7-4085-8a81-ad5eff390eae.jpg)
