### ISSUE TITLE
Траблы с переводом. 

### ISSUE THREAD

**Issue by Kriselov** [ilyhalight/voice-over-translation#134]
Хром. Украина. Виндовс 10. Ставил скрипт cloudflare. Не переводит с впн и без.  Обычный скрипт тоже перестает работать после того, как установлю cloudflare.  Нужно сносить темперманки и ставить наново чтобы снова заработал обычний с впн с заменой страны.
![2023-04-28_132122](https://user-images.githubusercontent.com/132014850/235135114-65444198-c994-4c33-be72-32321eb5d8d4.jpg)
![2023-04-28_133727](https://user-images.githubusercontent.com/132014850/235135124-934935db-6a84-444b-9e3d-cd7ec1b4985c.jpg)
![2023-04-28_132045](https://user-images.githubusercontent.com/132014850/235135136-8bf6e7b4-87eb-48fd-bc69-49035b47158d.jpg)

**Comment by ilyhalight** [comment]
Что значит перестает переводить? Судя по скриншоту всё работает

**Comment by Kriselov** [comment]
cloudflare нету звукового перевода хотя все настройки активны(

**Comment by ilyhalight** [comment]
> cloudflare нету звукового перевода хотя все настройки активны(

Попробуй в cloudflare версии нажать на кнопку загрузки и проверить загрузится страница с аудио или нет. 
![кнопка загрузки](https://user-images.githubusercontent.com/62353659/235244728-55e4833c-dd5b-417c-b8d5-7e568c2eacd2.png)

Не загрузится - значит не работает из-за Украинского айпишника
Загрузится - значит надо смотреть запросы браузера (консоль браузера -> сеть -> media), и там, как на скриншоте ищешь строчку, которая начинается с "vtrans". После смотришь на статус код загрузки, если он горит красным, значит не получается подгрузить само аудио, если горит зеленый (206), то тогда не знаю из-за чего у тебя может возникать подобная ошибка
![страница запросов](https://user-images.githubusercontent.com/62353659/235244298-11e0c8f1-1da1-4fd9-85df-47d1171b6c83.png)

**Comment by Kriselov** [comment]
Проверяю без впн. Не загружает! Скорее всево ип. Ладно. Спасибо за помощь. Буду пока сидеть на обычной версии через впн)
![2023-04-29_004614](https://user-images.githubusercontent.com/132014850/235260139-4b9493a6-3caa-42ab-9183-9ffddcce71a2.jpg)
![2023-04-29_004645](https://user-images.githubusercontent.com/132014850/235260145-d36336fa-c68f-4ca7-ac8e-bab3bbb2140f.jpg)
