### ISSUE TITLE
Переводит только на английский 

### ISSUE THREAD

**Issue by neitron10** [ilyhalight/voice-over-translation#136]
В последнем обновлении теперь переводит только на английский. И русское видео и английское.

**Comment by neitron10** [comment]
Решил проблему включив Ограничение перевода русскоязычных видео. Чтобы это не значило.

**Comment by ilyhalight** [comment]
> В последнем обновлении теперь переводит только на английский. И русское видео и английское.

Это зависит от наличия русских букв в описание видео, название видео и имени автора канала. В следующих версиях, как уже писал ранее, скорее всего будет добавлена возможность вручную задать язык видео, дабы не было таких ситуаций.
