### ISSUE TITLE
Не переводятся никакие видео (V1.1.2)

### ISSUE THREAD

**Issue by AvenCores** [ilyhalight/voice-over-translation#139]
![image](https://user-images.githubusercontent.com/64781822/235336479-3babc7c3-5b36-4cfd-a5fa-21db543e6bd2.png)

на всех видео данная ошибка

**Comment by AvenCores** [comment]
помогла установка другой версии
![image](https://user-images.githubusercontent.com/64781822/235336582-98fd4c7f-c5dd-4c0c-ac8a-3009561f5e84.png)

**Comment by ilyhalight** [comment]
> на всех видео данная ошибка

Пробовали только в edge? Пробовал в хроме и мозиле, и там, всё работает

**Comment by ilyhalight** [comment]
Похоже, это был всё таки не баг виртуалки

**Comment by ilyhalight** [comment]
Проблему нашёл. Сейчас залью новую версию

**Comment by ilyhalight** [comment]
Не досмотрел за изменениями в #137. Обновитесь до 1.1.2.1
