### ISSUE TITLE
Кнопка перевода работает только после перезапуска старницы

### ISSUE THREAD

**Issue by Spp595** [ilyhalight/voice-over-translation#140]
Почему то я могу нажать на кнопку перевода только после того как перезапущу страницу с видео. До этого момента кнопка будто не нажимается.
Видео: https://pingvin.sp595.ru/share/github-issues

**Comment by ilyhalight** [comment]
Обновитесь до 1.1.2.2

**Comment by Spp595** [comment]
теперь новая ошибка)
После включения перевода выключить нельзя
Видео: https://pingvin.sp595.ru/share/github2

**Comment by ilyhalight** [comment]
Вроде пофиксил
