### ISSUE TITLE
Проверка в Ограничить перевод русскоязычных видео работает некорректно

### ISSUE THREAD

**Issue by SashaXser** [ilyhalight/voice-over-translation#144]
Если зайти на англоязычное видео, а потом перейти на русское то перевод начнется.  И наоборот если зайти на русско язычное видео а потом на англоязычное то перевод не будет начинаться из-за ошибки "Вы отключили перевод русскоязычных видео"

Видео:[тык](https://www.veed.io/view/250d0dc7-0199-49c2-966a-df775db1d06f)

**Comment by ilyhalight** [comment]
Только что, проверил и у меня всё работает нормально. Но не исключаю, что рандомно могут появляться такие проблемы, но как их отследить - это уже другой вопрос

**Comment by SashaXser** [comment]
Проблема найден, не поверишь ассинхронный $translationBtn.click вызывает эту ошибку

**Comment by SashaXser** [comment]
Точнее моя попытка его склеить в один приводит к этому багу

**Comment by SashaXser** [comment]
Странно, но этот баг проявляется по разному хз даже как описать его причину

**Comment by SashaXser** [comment]
Попробуй переключаться между русским переводом и английским, типо с русского на англиканский а английского на русский. Заметил что-то странное?

**Comment by ilyhalight** [comment]
> Попробуй переключаться между русским переводом и английским, типо с русского на англиканский а английского на русский. Заметил что-то странное?

Да, сейчас, сработало. Определился английский язык, но пишет, что перевод русских видео ограничен

**Comment by ilyhalight** [comment]
Возможно, будет исправлено в обновление

**Comment by ilyhalight** [comment]
Пока поставлю статус решено, если на 1.2.0 снова всплывет открывайте заново ветку

**Comment by SashaXser** [comment]
Всё также, переходишь с русского видео на английское[
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/d88d58ca-c757-4e25-960c-d050779114b2)
](url)
