### ISSUE TITLE
Скрытие иконки Алисы и оптимизация строк интерфейса

### ISSUE THREAD

**Issue by dlt5** [ilyhalight/voice-over-translation#145]
Добавьте плз настройку скрытия иконки Алисы, чтобы уменьшить ширину кнопки (либо оставить кнопку без текста)
И предлагаю сделать текст лаконичнее (пример на скриншоте). 
И второй и пятый чекбоксы логичнее местами поменять.

![image](https://user-images.githubusercontent.com/29644162/236058017-6aa8c379-5902-4741-98a7-2a7c28d511bc.png)

**Comment by Oleg-Chashko** [comment]
Please, make the vertical size of the interface dynamically resizable so that there are no empty spaces.

![236058017-6aa8c379-5902-4741-98a7-2a7c28d511bc](https://user-images.githubusercontent.com/62497891/236551859-5aab350c-aced-4525-bdab-c52dff9b2b7f.png)

**Comment by ilyhalight** [comment]
> Добавьте плз настройку скрытия иконки Алисы

Куда эти кнопки еще-то добавлять, там менюшка и так уже еле-еле помещается в само видео

> либо оставить кнопку без текста
Может быть, в следующем обновление уберу

> И предлагаю сделать текст лаконичнее (пример на скриншоте).

Согласен, что это стоило бы поменять. Но в предложенном примере это выглядит крайне не информативно.
Вот, что может значить "переводить всегда" не зная, что это подразумевает "автоперевод видео"? Да, всё, что угодно. Да и к тому же, это название противоречит функции "не переводить с русского" (как можно переводить всегда, но при этом не переводить при каком-то условии?)) )
Подумаю, как можно было бы сократить названия кнопок и не сильно теряя передачу их смысла

> И второй и пятый чекбоксы логичнее местами поменять.

В следующем обновление поменяю

> Please, make the vertical size of the interface dynamically resizable so that there are no empty spaces.

Thought about it, maybe it will be done in the next update

**Comment by dlt5** [comment]
> Вот, что может значить "переводить всегда"

Так и «Автоматический перевод видео» непонятно. Сама по себе функция перевода видео и есть автоматический перевод. Можно тогда «Переводить без запроса».

А логотип Алисы я бы просто убрал, без опций. Он не нужен.

**Comment by Oleg-Chashko** [comment]
`Куда_ эти кнопки еще-то добавлять, там менюшка и так уже еле-еле помещается в само видео.`

В данный момент, меню уже не вписывается в вертикальный размер окна. (kitguru.net)

<img width="1093" alt="kitguru net_1" src="https://user-images.githubusercontent.com/62497891/236619817-6445a338-3a33-4f3c-aff8-e5f889380830.png">

<img width="1093" alt="kitguru net_2" src="https://user-images.githubusercontent.com/62497891/236619825-162a25ec-2686-4153-8f00-48e03158b860.png">

**Comment by dlt5** [comment]
Опция «Скрывать родную кнопку перевода в Яндекс-браузере» бы тоже не помешала. А то их две, они не связаны и орут хором, если обе включить)
А в настройках назвать это «Заменять кнопку в Яндекс-браузере»

**Comment by ilyhalight** [comment]
> kitguru.net

На сторонние сайты не обращаю внимания. Там, могут вставить видео любого размера, хоть 300х100, хоть 2560х1440.

> Опция «Скрывать родную кнопку перевода в Яндекс-браузере» бы тоже не помешала

Не думаю, что когда-нибудь появится

**Comment by ilyhalight** [comment]
> Please, make the vertical size of the interface dynamically resizable so that there are no empty spaces.

> (либо оставить кнопку без текста)
> И предлагаю сделать текст лаконичнее (пример на скриншоте).
> И второй и пятый чекбоксы логичнее местами поменять.

Добавлено в 1.2.0

**Comment by dlt5** [comment]
Сделал "Переводить при открытиЕ" )

**Comment by dlt5** [comment]
> И второй и пятый чекбоксы логичнее местами поменять.

Видимо забыл.

**Comment by ilyhalight** [comment]
> открытиЕ

> Видимо забыл.

Будет исправлено в следующей версии (завтра)
