### ISSUE TITLE
Поддержка Видео mail.ru

### ISSUE THREAD

**Issue by dlt5** [ilyhalight/voice-over-translation#151]
Возможна?

**Comment by ilyhalight** [comment]
Добавлено в 1.2.1

**Comment by dlt5** [comment]
Пишет не найден id видео (
И всегда сначала выбрана пара Русский -> Английский

![image](https://github.com/ilyhalight/voice-over-translation/assets/29644162/acdcde1a-b48a-4287-9ede-108994546888)

**Comment by ilyhalight** [comment]
> Пишет не найден id видео (

Можно ссылку на видео? Тестировал и нормально работало

> И всегда сначала выбрана пара Русский -> Английский

Так специально поставлено

**Comment by dlt5** [comment]
https://my.mail.ru/mail/d-light/video/_myvideo/2.html
https://my.mail.ru/mail/d-light/video/_myvideo/1.html
https://my.mail.ru/mail/d-light/video/_myvideo/3.html



> Так специально поставлено

Тогда настройки должны запоминаться. Каждый раз переключать язык не годится (я уже не спрашиваю, зачем вообще по дефолту переводить с русского)

**Comment by ilyhalight** [comment]
> я уже не спрашиваю, зачем вообще по дефолту переводить с русского

На видео mail.ru, ровно так же, как и на рутубе почти все видео на русском, поэтому так и сделано. Если не нравится бери и вырезай проверку, никто не запрещает.

> https://my.mail.ru/mail/d-light/video/_myvideo/3.html

Исправлю в 1.2.3

**Comment by ilyhalight** [comment]
> Если не нравится бери и вырезай проверку, никто не запрещает.

Может быть, чуть позже добавлю, чтобы по названию видео проверялось, т.е. есть русские буквы - перевод с русского на английский, русских букв нету - перевод с английского на русский

**Comment by dlt5** [comment]
> На видео mail.ru, ровно так же, как и на рутубе почти все видео на русском

А, это только для этих сервисов — тогда не критично.
А почему просто не запоминать настройки, как для других сайтов? Вроде оптимальный вариант и ожидаемое поведение.

**Comment by ilyhalight** [comment]
> А почему просто не запоминать настройки, как для других сайтов? Вроде оптимальный вариант и ожидаемое/предсказуемое поведение.

Я бы, всё же, отдавал приоритет автоопределению языка, как это сейчас сделано для ютуба, где от наличия кириллицы в название, описание и имени автора канала зависит язык перевода. 

Но это всё равно палка о двух концах, кому-то удобнее, чтобы оно само опредялось и тебе нужно было просто нажать на кнопку, а если определено неверно единожды поменять. А кому-то удобнее 1 раз самому задать с какого языка на какой переводить.

**Comment by dlt5** [comment]
А ты сделай как в переводчиках: первая строчка в списке языков — Автоопределение, которое выбрано по дефолту. И запоминание настроек. Если юзеру будет мешать авто, он выберет язык явным образом. И вернёт авто, когда понадобится.

**Comment by dlt5** [comment]
> Исправлю в 1.2.3

Правильно понимаю, что еще не исправлено?

**Comment by ilyhalight** [comment]
> И после выкл-вкл всегда пишет, что перевод займет около минуты.

Это уже зависит от того, какой ответ прийдёт от апи. Иногда сразу приходит аудио дорожка, а иногда перевод начинается заново.
