### ISSUE TITLE
Не удалось перевести, на видео отсутствует речь для перевода 

### ISSUE THREAD

**Issue by rollly00** [ilyhalight/voice-over-translation#154]
Safari, Chrome. Mac OS. AdBlock отключен. С VPN и без. 
Пример видео:
https://www.youtube.com/watch?v=4acXs-kNbVI
<img width="552" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/31448610/2025f717-2c0e-4a5b-88f6-7056e40cbe68">

**Comment by SashaXser** [comment]
> 

Апи не распознал голос на видео, проблема возможно на стороне яндекса

**Comment by ilyhalight** [comment]
Ответили выше
