### ISSUE TITLE
[Beta 1.2.0] Белый текст в белых дропдаунах

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#157]
Собственно сабж:
<img width="279" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/4968313/4e47e586-c409-422c-8fa5-eb17da0b8693">

**Comment by ilyhalight** [comment]
А что за сайт на котором проблема?

**Comment by Dragoy** [comment]
bilibili

**Comment by ilyhalight** [comment]
Сейчас с поддержкой mail.ru разберусь и залью фикс

**Comment by Dragoy** [comment]
на YT проверил все четко выглядит

**Comment by ilyhalight** [comment]
Исправил в 1.2.1
