### ISSUE TITLE
Не работает в Cent Browser

### ISSUE THREAD

**Issue by grokom** [ilyhalight/voice-over-translation#16]
Cent Browser (https://www.centbrowser.com/https://www.centbrowser.com/) - Версия 4.3.9.248 (Официальная сборка), (64 бит) (Portable) (Chromium 86.0.4240.198)

Ошибка: постоянно висит "Перевод займет около минуты"

![image](https://user-images.githubusercontent.com/111271399/184594766-8c0ee158-0e16-4748-bb0e-8951ea962a97.png)

**Comment by ilyhalight** [comment]
Как будет время постараюсь исправить

**Comment by ilyhalight** [comment]
Не удалось скачать портейбл версию из-за каких-то проблем на сайте (загрузка начинается, но скорость весит на 0 кб/с ), поэтому пробовал на обычной версии Cent Browser`a (Версия 4.3.9.248 (Официальная сборка), (32 бит) (Chromium 86.0.4240.198))

Ошибки нету.

![изображение](https://user-images.githubusercontent.com/62353659/185247180-234bbea8-4a55-4ea0-88af-d8e7c284de2e.png)

**Comment by Spuner** [comment]
К сожалению, в Cent Browser 5.0.1002.182 Beta - не работает. В CatsXP Browser 2.8.4 (104.0.5112.94) - работает.

**Comment by ilyhalight** [comment]
> Cent Browser 5.0.1002.182 (102.0.5005.167) Beta

Честно, без понятия почему так происходит, но мне не удаётся воспроизвести эту ошибку
![изображение](https://user-images.githubusercontent.com/62353659/186283566-83534d6b-95a4-4eff-a8aa-845415abcb08.png)

**Comment by Spuner** [comment]
Каким-то чудом заработало. Но в яндекс браузере помню, что оригинальная дорожка автоматический приглушалась при включении перевода. Тут же, приходится вручную понижать громкость видео.

**Comment by Jeff-xxx** [comment]
Привет. Cent  5.0.1002.182 (Официальная сборка), (64 бит) (Chromium 102.0.5005.167), также не заработало сначала, висело на "ожидании около минуты", либо кнопка "перевести" совсем не нажималась. Путём отключения всего и вся, выяснилось, что скрипт конфликтует с расширением Magic Actions for YouTube. От перебора настроек ничего не меняется, влияет факт самого включения расширения. Можно ли подружить скрипт с этим расширением?
