### ISSUE TITLE
[Beta 1.2.0] Не поддерживается перевод видосов с эпизодами на BiliBili 

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#160]
Если открыть видео которое разбито на эпизоды (аналог плейлиста), то переводиться только первый видос, остальные не учитываются:

Первый видос - https://www.bilibili.com/video/BV16e4y1o7vM?p=1&vd_source=31ca8612fe0b126579a245dddfcf3735
Пятый видос - https://www.bilibili.com/video/BV16e4y1o7vM/?p=5&vd_source=31ca8612fe0b126579a245dddfcf3735

**Comment by ilyhalight** [comment]
Добавленов в 1.2.2
