### ISSUE TITLE
XVideos не работает

### ISSUE THREAD

**Issue by HardTattoo** [ilyhalight/voice-over-translation#161]
Долго переводит, потом пишет что формат аудио не поддерживается

**Comment by ilyhalight** [comment]
Из-за CSP не работает. Попробуйте установить [это расширение](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related) и включить для нужного вам сайта (просто нажмите на значок расширения, чтобы он загорелся фиолетовым и перезагрузите страницу). Должно помочь. 

**Включайте только на сайтах, где не работает!**
