### ISSUE TITLE
[Вопрос] Язык озвучки

### ISSUE THREAD

**Issue by ilyhalight** [ilyhalight/voice-over-translation#164]
Нужно ли добавлять возможность выбрать Китайский, Французский, Итальянский и Испанский язык озвучки? Или это будет лишним и будет лишь захламлять меню выбора языка?

т.е. можно будет условно с русского перевести на китайский, с итальянского на испанский и т.д.
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/6edee2d5-209b-4344-96e1-93e444ecdfcb)

**Comment by SashaXser** [comment]
Пускай будет

**Comment by Oleg-Chashko** [comment]
If possible, add.

**Comment by Dragoy** [comment]
Удобно для ребят которые хотят смотреть знакомый контент на другом языке для изучения языков. Либо для зарубежных пользователей.

**Comment by Oleg-Chashko** [comment]
Please add German language.

**Comment by YuchkinUA** [comment]
Cool script!👍
but please add Ukrainian.
Alternatively, you can take the engine from "Neurodub" or Microsoft Edge Browser.

Thanks!)🤝

**Comment by ilyhalight** [comment]
> Alternatively, you can take the engine from "Neurodub" or Microsoft Edge Browser.

Yandex API does not support the Ukrainian language.

I didn't understand a bit what you mean by the engine from Microsoft Edge Browser?

**Comment by YuchkinUA** [comment]
@ilyhalight Well, something like this...) 

https://github.com/ilyhalight/voice-over-translation/assets/127149244/98ce0a45-001d-4ef5-8148-d7dee92f7662

**Comment by YuchkinUA** [comment]
Yey!🥳 Thanks @ilyhalight
 that added Ukrainian to the list of languages🙂🤝

**Comment by YuchkinUA** [comment]
Yey!🥳 Thanks @ilyhalight
that added Ukrainian to the list of languages🙂🤝

Now, English-language YouTube becomes even more accessible!
and what about YouTube...
I can watch TV series without waiting for dubbing.😊🔥
![image](https://github.com/ilyhalight/voice-over-translation/assets/127149244/e13747c7-9418-487c-b393-b01b77bce1b5)

**Comment by SashaXser** [comment]
> Yey!🥳 Thanks @ilyhalight that added Ukrainian to the list of languages🙂🤝
> 
> Now, English-language YouTube becomes even more accessible! and what about YouTube... I can watch TV series without waiting for dubbing.😊🔥

Он уже как месяц добвлен...

**Comment by YuchkinUA** [comment]
@SashaXser Yeah? I just saw it now)
