### ISSUE TITLE
Не появляется кнопка перевода в m.youtube.com

### ISSUE THREAD

**Issue by Michael1297** [ilyhalight/voice-over-translation#165]
После сегодняшнего обновления кнопка вообще не появляется

**Comment by ilyhalight** [comment]
Завтра выпущу фикс, чтобы появлялась

**Comment by Dragoy** [comment]
> Завтра выпущу фикс, чтобы появлялась

Докучи с m.vk.com такая же история

**Comment by ilyhalight** [comment]
Кнопку то добавил, но перевод там всё равно нормально не работает #114

**Comment by Michael1297** [comment]
@ilyhalight На телефоне кнопка все еще не хочет появляться.
В хроме через AdGuard она вообще не появилась.
В Kiwi Browser через tampermonkey она может появиться после нескольких перезагрузок страницы. (возможно https://github.com/ilyhalight/voice-over-translation/issues/114)

Кстати оказывается что в Kiwi Browser есть консоль 😮, я его поставил только для теста так как в нем можно использовать расширения для десктопного хрома.

**Comment by ilyhalight** [comment]
Чуть позже попробую пофиксить
