### ISSUE TITLE
Improving UI (with mockup screenshot)

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#166]
<img width="383" alt="Screen Shot 2023-05-23 at 20 01 18 copy" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/59669b2e-1314-441b-b832-ac634f19561c">

---

Example:

<img width="403" alt="Screen Shot 2023-05-23 at 20 01 18" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/9d4bf695-69c9-4b50-888c-27de8d39204e">

**Comment by ilyhalight** [comment]
50/50
It seems better that everything fits on one line, but there will be too much free space on other sites, it seems to me

**Comment by Oleg-Chashko** [comment]
The words after the checkbox are not centered in google chrome. Everything is fine in Firefox.

- Google
<img width="905" alt="Google copy" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/7e8f9abb-25b1-44d9-ab84-ab3a4e4a232b">

<img width="905" alt="Google" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/fe7a89f4-0257-4d14-ac95-49ddea3dadd6">

---

- Firefox
<img width="853" alt="Firefox copy" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/358fde90-17e9-4948-8da1-0f300c7225aa">

<img width="853" alt="Firefox" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/5ab5fa88-9055-424c-895b-932f5d051cd8">

**Comment by iav** [comment]
Нельзя ли прижать к верхнему краю экрана? 
Сейчас для регулировки громкости или выбора нижних кнопок приходится увеличивать видео на весь экран, хотя смотрю я в окне.
Собственно, на ваших скриншотах тоже низ окна перекрыт контролами ютуба и потому нефункционален.

**Comment by ilyhalight** [comment]
> Нельзя ли прижать к верхнему краю экрана?

В 1.3.1 кнопка станет располагаться немного выше

**Comment by ilyhalight** [comment]
> The words after the checkbox are not centered in Google Chrome. Everything is fine in Firefox.

В 1.3.1 вроде как должны стать получше.

Было:
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/30d9ea6b-1e57-427d-863f-d9fcb68e7e77)

Стало:
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/e3362db7-b831-4fe4-b789-77c0fefb8c70)

**Comment by Oleg-Chashko** [comment]
Please, increase the width of the window so that the text is a single line.
As well as the length of sliders and buttons as in the example above in the text.

![1](https://github.com/ilyhalight/voice-over-translation/assets/62497891/142c9435-7c7a-4a63-b659-f69e1370cb3c)

---

Try to make sure that no interface elements do not go into the virtual zone, that everything was semetric from all sides.

<img width="899" alt="Screen Shot 2023-06-30 at 7 53 15" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/45d3cbdf-1fda-4ae9-8f72-b69810bb4c0f">

**Comment by ilyhalight** [comment]
On which sites / browsers does this occur? I checked on YouTube and everything is fine there

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/1774d5e0-a8e0-4e64-9226-7d21fe15d5d3)

**Comment by Oleg-Chashko** [comment]
> On which sites / browsers does this occur? I checked on YouTube and everything is fine there
> 
> ![image](https://user-images.githubusercontent.com/62353659/250080779-1774d5e0-a8e0-4e64-9226-7d21fe15d5d3.png)

Google Chrome v114.0.5735.198

**Comment by Oleg-Chashko** [comment]
Same problem and artifacts on the sliders.
Safari v16.5.1 (17615.2.9.11.7, 17615)

<img width="591" alt="Screen Shot 2023-06-30 at 15 04 29" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/c268d8ea-f686-4d10-ba38-0b2436e4238b">

**Comment by ilyhalight** [comment]
maybe it's some mac os features... On Windows it looks the same as I sent the photo above

**Comment by Oleg-Chashko** [comment]
Fedora Linux. YouTube. Google Chrome v114.0.5735.198

<img width="827" alt="Screen Shot 2023-06-30 at 17 26 52" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/08d589fc-6cdf-4170-ad14-a658f10e9bc1">

**Comment by ilyhalight** [comment]
More irrelevant because of the new menu in #294.
