### ISSUE TITLE
[Beta 1.2.2] Нет кнопки перевода в m.vk.com + снова траблы с дропдаунами 

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#167]
Нет кнопки перевода в m.vk.com, приходится переключать на vk.com.

Опять же траблы с дропдаунами:

![AF192E89-A6B4-4EF3-B82B-2F86377892B1](https://github.com/ilyhalight/voice-over-translation/assets/4968313/36a69191-b12f-47b8-ad8d-d2ee335a7255)

**Comment by Dragoy** [comment]
Скриншот с Айпада

**Comment by ilyhalight** [comment]
> Опять же траблы с дропдаунами:

Исправлю. 

> Нет кнопки перевода в m.vk.com, приходится переключать на vk.com.

Проверил, да, проблема есть, но в ближайшее время вряд ли буду исправлять (может быть как-нибудь в будущем), ибо прийдётся очень дублировать/переделывать из-за необходимости взаимодействия с shadowroot

**Comment by ilyhalight** [comment]
> > Опять же траблы с дропдаунами:
> 
> Исправлю.
> 
> > Нет кнопки перевода в m.vk.com, приходится переключать на vk.com.
> 
> Проверил, да, проблема есть, но в ближайшее время вряд ли буду исправлять (может быть как-нибудь в будущем), ибо прийдётся слишком многое дублировать/переделывать из-за необходимости взаимодействия с shadowroot

**Comment by Dragoy** [comment]
Окей, спасиб, потерпим :>
