### ISSUE TITLE
Pop-up button picture in picture in edge browser is gone

### ISSUE THREAD

**Issue by HarDX** [ilyhalight/voice-over-translation#17]
Pop-up button picture in picture in edge browser is gone
For example when it present:
![image](https://user-images.githubusercontent.com/5231223/185064543-2559ced5-3fb0-4ff3-9467-16f7b7126aa0.png)

**Comment by ilyhalight** [comment]
I don't understand the point of the question. Is the button missing in picture-in-picture mode or when watching the video itself? If it's the latter, can you tell me the version of MS Edge?

**Comment by HarDX** [comment]
Edge 104.0.1293.54 (Официальная сборка) (64-разрядная версия)
No this pop-up button for open pip, after install and using this script
But pop-up button for yandex translate is present

**Comment by ilyhalight** [comment]
> Edge 104.0.1293.54 (Официальная сборка) (64-разрядная версия) No this pop-up button for open pip, after install and using this script But pop-up button for yandex translate is present

Now, I see what you mean. I may be wrong, but it's a problem with Tampermonkey itself. Try installing [Violetmonkey](https://violentmonkey.github.io/), there was no such problem

---
MS Edge: Версия 104.0.1293.54 (Официальная сборка) (64-разрядная версия)
Violentmonkey: v2.13.0

![изображение](https://user-images.githubusercontent.com/62353659/185365182-e9c413e1-d2a0-4a19-9690-3f554dc851bc.png)

**Comment by HarDX** [comment]
Thanks. problem with Tampermonkey. All is ok now
