### ISSUE TITLE
Для бета-версий нужна отдельная ветка обновлений.

### ISSUE THREAD

**Issue by Baltazar500** [ilyhalight/voice-over-translation#171]
Собственно сабж.

Для бета-версий нужна отдельная ветка обновлений т.к. когда satble-версия автоапдейтом (adguard/tamper monkey/etc) заменяется на нестабильную бету с кучей нововведений, а узнаешь ты об этом лишь случайно заглянув в свойства скрипта - такое себе удовольствие. Хотя у меня и стоит email-подписка касательно обновлений скрипта, особого значения уведомлениям не придал. Ну бета и бета. Выйдет satble, заменят бету и обновится скрипт. А оно эвона как вышло. Бэта попёрла сразу же заменив stable. 

Я VOT использую в AdGuard на ведре, где приходится маяться с постоянными апдейтами скриптов вручную т.к. ещё надо вписать свой worker. Через cgi-скрипт на htppd под локалхостом я это рутину автоматизировал и решил вопрос с worker'ом, но такой  подход к обновлениям свёл все мои старания на нет и вынудил вернуться к ручным обновленям. Было бы намного проще, если бы AdGuard позволял деактивировать обновления скриптов, но он увы не даёт такой возможности (хотя разрабы пообещали рассмотреть/запилить подобную фичу), так чт для бет нужна отдельная ветка :)

**Comment by SashaXser** [comment]
Форкни репозиторий и делай что хочешь

**Comment by ilyhalight** [comment]
Идея хорошая, но боюсь, тогда, чтобы узнать о каких-либо багах прийдётся ждать очень долго. Поскольку, сейчас, у всех стоит основная ветка + автоапдейт расширений, и они заходят в репу, только, для того, чтобы оставить обратную связь о каком-либо баге или новой идеи (и то, мне кажется, что большая часть просто на это забивает).

Отсюда и получится, что если будет отдельная ветка, то большинство багов будут доходить до основной ветки, и получится, что стейбл уже не будет стейблом, а станет и станет такой же бетой ¯\_(ツ)_/¯

> где приходится маяться с постоянными апдейтами скриптов вручную т.к. ещё надо вписать свой worker

Вообще, была идея попытаться добавить отдельное меню с настройками расширения (т.е. где можно будет прямо внутри расширения, не меняя как-либо код, задать свой воркер или выбрать один из списка), но пока это остается лишь на стадии идеи

**Comment by Baltazar500** [comment]
>Идея хорошая, но боюсь, тогда, чтобы узнать о каких-либо багах прийдётся ждать очень долго. Поскольку, сейчас, у всех стоит основная ветка + автоапдейт расширений, и они заходят в репу, только, для того, чтобы оставить обратную связь о каком-либо баге или новой идеи (и то, мне кажется, что большая часть просто на это забивает).

ОК. Если подход к вопросу такой, то это разумное решение, согласен. В таком случае могу как минимум предложить в скрипт вносить маркировку того что это "BETA" версия (например name), тогда это позволит чекать моим cgi-скриптом (после доработки естественно) релиз на предмет беты и скипать его в случае чего. Как максимум могу предложить вам сделать доп. ветку со stable - релизом и добавить в описание в теле скрипта. Если кто сильно захочет - руками заменит на stable.

**Comment by ilyhalight** [comment]
> > Идея хорошая, но боюсь, тогда, чтобы узнать о каких-либо багах прийдётся ждать очень долго. Поскольку, сейчас, у всех стоит основная ветка + автоапдейт расширений, и они заходят в репу, только, для того, чтобы оставить обратную связь о каком-либо баге или новой идеи (и то, мне кажется, что большая часть просто на это забивает).
> 
> ОК. Если подход к вопросу такой, то это разумное решение, согласен. В таком случае могу как минимум предложить в скрипт вносить маркировку того что это "BETA" версия (например name), тогда это позволит чекать моим cgi-скриптом (после доработки естественно) релиз на предмет беты и скипать его в случае чего. Как максимум могу предложить вам сделать доп. ветку со stable - релизом и добавить в описание в теле скрипта. Если кто сильно захочет - руками заменит на stable.

Для бета версий в конец версии (version) будет добавляться "-beta" (1.2.4-beta и т.п.), думаю будет вполне оптимально

**Comment by ilyhalight** [comment]
Сделал ветку [dev](https://github.com/ilyhalight/voice-over-translation/tree/dev) + бета версии, теперь, будут выходить как Pre-release т.е., в теории, скрипт не должен будет до них автоматически обновляться
