### ISSUE TITLE
Сама повышается громкость оригинала

### ISSUE THREAD

**Issue by DygDyg** [ilyhalight/voice-over-translation#172]
процентах на 90% видео громкость оригинальной дорожки повышается почти до максимума (использую галочку уменьшить громкость до 15%) при этом ползунок стоит на 15% но выгладить как на 90%
![image](https://github.com/ilyhalight/voice-over-translation/assets/33259562/9a715941-20a5-4a1e-821b-c415ce134993)
при попытке его передвинуть он сразу изменяется в этом месте на 95%
![image](https://github.com/ilyhalight/voice-over-translation/assets/33259562/7c512557-911f-45bb-b33f-cfe64ebc5f23)

**Comment by DygDyg** [comment]
@version 1.2.3

**Comment by petrsmir** [comment]
У меня тоже самое, я обычно громкость оригинала ставлю либо на 0 или же до 5-6 процентов и всё работало, а теперь постоянно показывается 90 процентов и если передвинуть на другие проценты, то спустя несколько секунд автоматически звук оригинала возвращается на 90 процентов, что бесит. Версия у меня данного расширения 1.0.9.9, будьте добры это исправить

**Comment by DygDyg** [comment]
По моим наблюдениям громкость повышается всегда ровно за 2 минуты до конца видео

**Comment by Harosatchi** [comment]
Еще "Уменьшать громкость видео до 15%" не включается, если открыть страницу видео, не запуская это видео, нажать Перевести, и потом уже запустить видео. Приходится сначала запускать видео, и только потом нажимать Перевести. Очень неудобно.

**Comment by iav** [comment]
У меня громкость оригинала повышается до оригинальной не за две минуты до конца, а секунд через 30. При этом цифра на слайдере громкости оригинала остаётся прежней, а шарик прыгает в конец. Можно снова сдвинуть движок, громкость уменьшится на следующие 30 секунд.

**Comment by narimangafurov** [comment]
Такая же проблема( Все версии последниие, компьютер Мак. Раньше со старой версией такого не было

**Comment by Jafa7** [comment]
Та же проблема. Версия 1.3.3. Кто-то нашел решение роблемы?

**Comment by sid350** [comment]
Громкость оригинала сама вырастает до 100% через минуту воспроизведения
