### ISSUE TITLE
[Beta 1.2.3] Не работает перевод в приватных окнах Firefox 113.0.2

### ISSUE THREAD

**Issue by Aborovskoy** [ilyhalight/voice-over-translation#173]
В приватном режиме падает на openDB("VOT"), получаем сообщение в консоль VOT: Ошибка инициализации Базы Данных: undefined.
Если комментируем/убираем содержимое функции async function initDB () { } , то естественно лишаемся доступа к настройкам, но перевод начинает работать.

**Comment by ilyhalight** [comment]
IndexedDB не работает в режиме инкогнито, отсюда и ошибка. Может быть, позже сделаю, чтобы в приватных окнах заместо нее использовался LocalStorage, но это явно не в приоритете

**Comment by Aborovskoy** [comment]
Достаточно было бы не инициализировать БД в приватных окнах. Настройки в этом режиме не нужны имхо.

**Comment by SashaXser** [comment]
Лично у меня всё работает

**Comment by ilyhalight** [comment]
> Лично у меня всё работает

Такое только в firefox

**Comment by SashaXser** [comment]
> 

У меня Firefox Nightly

**Comment by ilyhalight** [comment]
Исправлено в 1.3.0
