### ISSUE TITLE
In Google Chrome there is no “Не переводить с русского (youtube)"

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#175]
Beta v1.2.3
In Google Chrome there is no "Не переводить с русского (youtube). 

<img width="905" alt="Google" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/50495cc2-9d56-4105-aebe-9a61284efc33">

---

Everything is fine in Firefox.

<img width="853" alt="Firefox" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/d44ce2e7-8aaa-44a1-a69b-d9a20d2f869b">

**Comment by ilyhalight** [comment]
Try clicking on "Сбросить настройки" in Google Chrome

**Comment by Oleg-Chashko** [comment]
Thank you. The issue is closed.
