### ISSUE TITLE
Не работает перевод, и ошибки в консоли на piped.video

### ISSUE THREAD

**Issue by il2020** [ilyhalight/voice-over-translation#176]
На странице с видео часто нет кнопки для включения перевода, а когда она есть, то при нажатии на неё перевод не включается.
Пример видео: https://piped.video/watch?v=w7ZbqwnAM3k

![2023-05-30_15-56](https://github.com/ilyhalight/voice-over-translation/assets/77854832/e92b127f-ac24-4fad-bd51-80b8c0030c2a)

В этом же видео, но на https://invidious.kavin.rocks/watch?v=w7ZbqwnAM3k перевод включается.

![2023-05-30_15-58](https://github.com/ilyhalight/voice-over-translation/assets/77854832/1e6406a0-5321-4db3-b26e-1f385a4294f2)

Firefox 113.0.2

**Comment by ilyhalight** [comment]
Исправлено. Спасибо за репорт
