### ISSUE TITLE
Поддержка FireMonkey

### ISSUE THREAD

**Issue by MistakeTZ** [ilyhalight/voice-over-translation#18]
Пожалуйста добавьте поддержку FireMonkey (https://addons.mozilla.org/en-US/firefox/addon/firemonkey/)

**Comment by MjKey** [comment]
+
Или хотя бы просто поддержку FireFox :3

**Comment by MistakeTZ** [comment]
Я проверил, этот скрипт до сих пор не работает с FireMonkey

**Comment by ilyhalight** [comment]
Добавил. Почему-то сначала не загружались стили, но потом это как-то само по себе исправилось.

**Comment by ilyhalight** [comment]
Скачай версию для VM, FM, GM, AdGuard с главной страницы репозитория

**Comment by MistakeTZ** [comment]
Супер! Большое спасибо
