### ISSUE TITLE
Не переводит видео с домена player.vimeo.com

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#181]
Вот тут можно потестить: https://player.vimeo.com/video/797744941
После нажатия на перевод, пишет "Возникла ошибка, попробуйте позже"

**Comment by Dragoy** [comment]
Так же и тут: https://vimeo.com/807245860/4bb6b8c22a

**Comment by lux-futurum** [comment]
Только что проверил обе ваших ссылки в яндекс‐браузере, там тоже недоступен перевод. Пожалуйста, проверяйте проблемные ссылки в родном браузере перед публикацией.

**Comment by ilyhalight** [comment]
Позже исправлю

**Comment by ilyhalight** [comment]
1. В плеере ограничен CSP из-за этого не удается получить аудио файл. Единственное решение, которое знаю - скачать доп расширение для отключения CSP

2. Поддержку таких ссылок добавил в еще не вышедшей 1.3.1, но есть одно но - Яндекс всё равно не умеет их переводить. Теперь, нужно у них просить, чтобы добавили поддержку ¯\_(ツ)_/¯
