### ISSUE TITLE
Добавить немецкий язык

### ISSUE THREAD

**Issue by johnny-ivan** [ilyhalight/voice-over-translation#183]
В Яндекс Браузере немецкий доступен.
Можно пожалуйста добавить его сюда тоже?

Спасибо!

**Comment by ilyhalight** [comment]
Уже было, добавлю позже

**Comment by Oleg-Chashko** [comment]
Please tell me, when do you plan to add German language support?

**Comment by ilyhalight** [comment]
> Please tell me, when do you plan to add German language support?

in 1.2.5 (next update)
