### ISSUE TITLE
Добавить перевод для gaia.com 

### ISSUE THREAD

**Issue by johnny-ivan** [ilyhalight/voice-over-translation#184]
GAIA.com уникальный ресурс который на английском языке, у меня есть друзья кто бы хотел много чего там посмотреть но знания английского не хватает.
Было бы очень очень круто если бы как-то получилось наладить работу перевода с Gaia.com.

*Сервис подписной $11.99 в месяц или $99 в год.

**Comment by ilyhalight** [comment]
Не думаю, что яндекс его поддерживаю. Позже гляну

**Comment by leex-leex** [comment]
Уважаемый, **ilyhalight.**
К сожалению github.com убрал личные сообщения, **поэтому** пишу здесь.
Удалю как прочтете.  **Не реализуемо** надо писать слитно. Это прилагательное. 

Пишем прилагательные с частицей «не» раздельно, если в тексте предложения есть противопоставления с союзом «а» или слова, усиливающие отрицание. 
В остальных случаях пишем слитно.

**Comment by ilyhalight** [comment]
поправил написание
