### ISSUE TITLE
Invidious глюки

### ISSUE THREAD

**Issue by nIKsL** [ilyhalight/voice-over-translation#185]
\*://iv.melmac.space/\* - добавляю зеркало Invidious - не появляется кнопки перевода

на https://yewtu.be/ - "формат аудио не поддерживается" (громкость оригинального видео уменьшается)
нажимаю три точки (настройки) - кнопка скачать перевод - там перевод идёт. Как выход приходится фоном открывать этот перевод и запускать видео на странице :(

**Comment by ilyhalight** [comment]
> на https://yewtu.be/ - формат аудио не поддерживается

Такое только в хроме из-за CSP. Там нужно качать доп. расширение и отключать CSP на этой странице (об этом сказано в описание)

> *://iv.melmac.space/* - добавляю зеркало Invidious - не появляется кнопки перевода

Может быть создатель зеркала что-то менял в коде и поэтому не появляется. Или может быть вы забыли добавить в массив sitesInvidious
