### ISSUE TITLE
Firefox Nightly 

### ISSUE THREAD

**Issue by Waffelson** [ilyhalight/voice-over-translation#186]
Перестало работать в Firefox nightly в windows 10 и android

**Comment by ilyhalight** [comment]
Потом проверю

**Comment by ilyhalight** [comment]
Попробуйте обновить расширение. Только что, проверил в Firefox (114.0.2), Firefox Nightly (116.0a1 (2023-06-24)), Firefox Developer Edition (115.0b9) и везде работает (пк)

**Comment by Waffelson** [comment]
Похоже начало наботать, версия 1.2.3 и 1.2.4
Возможно баг был со стороны firefox и вероятно его пофиксили
