### ISSUE TITLE
Виновата ОС?

### ISSUE THREAD

**Issue by Askutreg** [ilyhalight/voice-over-translation#188]
Автору-энтузиасту - респект!
Есть два ПК. Первый на Win10x64, второй - на Win11. На обеих установлены Chrome и AdGuard последних версий. На первый ПК установил это расширение в AdGuard  и все работает хорошо. А вот на второй ПК ни из AdGuard, ни как расширение самого Chrome, работать не хочет. Кнопка "Перевести видео" появляется, при нажатии активируется (меняется на "Выключить"), но самого перевода нет. Оригинальный звук самого видео при запуске не затихает. Через минуту окошко меняется на "Формат аудио не поддерживается". Хотя на первом ПК эти самые ролики прекрасно переводились. В итоге, на втором ПК не удалось посмотреть с переводом ни одного видео на YouTube.
ПК глобально отличаются только опер.системами. Другими причинами объяснить не могу. 
Может есть соображения по этому поводу?
Спасибо.

**Comment by ilyhalight** [comment]
Сложно, так, с ходу сказать. Может быть у AdGuard что-то отличается в работе на win10 и win11, или может быть настройки какие-то стоят на win11, которые отключены на win10 и тем самым блокируют получение звуковой дорожки. Вариантов можно множество накидать, но без тестов это считай что тыкать пальцем в небо.

**Comment by Askutreg** [comment]
Спасибо за ответ.
Разобрался. Оказалось, что причина в провайдере, к которому подключен второй ПК. Этот провайдер блокирует часть российских ресурсов. Через VPN все заработало.
Для юзеров из Украины, надеюсь, мой опыт будет полезен.
