### ISSUE TITLE
[Bug] Не работает только на одном видео на Youtube

### ISSUE THREAD

**Issue by iG8R** [ilyhalight/voice-over-translation#189]
Приветствую.
Почему-то работает на всех видео, кроме следующего https://www.youtube.com/watch?v=VVCh-Ni7Wew
Проверялось в Firefox 114.0.1 и IE 114.0.1823.51 (Official build) (64-bit).

**Comment by SashaXser** [comment]
> Приветствую. Почему-то работает на всех видео, кроме следующего https://www.youtube.com/watch?v=VVCh-Ni7Wew Проверялось в Firefox 114.0.1 и IE 114.0.1823.51 (Official build) (64-bit).

Всё работает в Firefox 116

**Comment by iG8R** [comment]
> Всё работает в Firefox 116

Какой у Вас номер скрипта?
На 1.0.9.9 версии - работает на любом видео.
На 1.2.3 версии - не рабортает на том видео, что я указал выше, на всех остальных - работает.

**Comment by iG8R** [comment]
[Voice-Over-Translation-Video_2023-06-19_134307_FFB.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/cfef6591-1210-4490-ad80-75906b112026)

**Comment by ilyhalight** [comment]
> Voice-Over-Translation-Video_2023-06-19_134307_FFB.webm

В консоли есть какие-то ошибки?

**Comment by iG8R** [comment]
> В консоли есть какие-то ошибки?

![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/b2b18ed7-2db2-45f7-9bec-34c71e657c71)

**Comment by SashaXser** [comment]
> > В консоли есть какие-то ошибки?
> 
> ![image](https://user-images.githubusercontent.com/11407417/246834285-b2b18ed7-2db2-45f7-9bec-34c71e657c71.png)

Вы пробывали 1.2.3 cloudflare?

**Comment by iG8R** [comment]
Всё, нашел внизу инструкции. Сейчас попробую.

**Comment by iG8R** [comment]
С `1.2.3 cloudflare` такая же ситуация, как и с обычной `1.2.3` - всплывающее меню не появляется на вышеуказанном видео.

**Comment by iG8R** [comment]
> Пробывали сбросить базу данных настроек?

Возможно сбросить только настройки VOT или только все настройки разом сбрасываются? Если все вместе, то это будет крайне затруднительно сделать, т.к. слишком много после этого придется восстанавливать.
Плюс ко всему, изначально я устанавливал 1.2.3 версию на абсолютно чистый профайл браузеров, и когда она не заработала, тогда уже порывшись в закромах нашел 1.0.9.9 версию и сравнил их работу.

**Comment by iG8R** [comment]
Как можно еще выявисть причину такого поведения?
Какие еще можно посмотреть логи, кроме консольных, или может нужно настраивать какие-то другие логи?

**Comment by SashaXser** [comment]
> Как можно еще выявисть причину такого поведения? Какие еще можно посмотреть логи, кроме консольных, или может нужно настраивать какие-то другие логи?

Я еще раз посмотрел видео, вижу у тебя очень много скриптов, попробуй их вырубить и оставить только VOT на новой и старой версии. Мб конфликтуют

**Comment by iG8R** [comment]
Отключил все скрипты, ничего не поменялось.
Также проверил на 2-х других ноутбуках - ситуация та же, 1.0.9.9 работает, 1.2.3 - нет.

[Voice-Over-Translation-Video_2023-06-19_180432FFB.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/42178d6a-e5d5-41f3-96a5-d7898145e112)

**Comment by Oleg-Chashko** [comment]
I confirm the existence of this bug.
Google Chrome v114.0.5735.133

**Comment by SashaXser** [comment]
Проверьте мою версию, я попробывал в Edge запустить вроде работает. [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

**Comment by iG8R** [comment]
Спасибо!
PS. Правда, скрипт прибавил в весе аж на 50Кб.

**Comment by Oleg-Chashko** [comment]
> Проверьте мою версию, я попробывал в Edge запустить вроде работает. [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

It works, thank you.

**Comment by SashaXser** [comment]
> Спасибо! PS. Правда, скрипт прибавил в весе аж на 50Кб.

Разве увеличен из-за пакета на определения языка. Я использовал его для того чтобы смотреть все видео на ютубе, даже тогда когда нету субтитров. Если хочешь, то он сжимается до 117 кб. Если вырезать пакет на определения языка то все 51 кб
