### ISSUE TITLE
Вчерась была кнопка сегодня пропала.

### ISSUE THREAD

**Issue by IVJik** [ilyhalight/voice-over-translation#191]
Ну собственно я хз в чём дело.
Обновлений не было, дополнения не ставил кеш не чистил у браузера.
https://ibb.co/FW5QQLW
Что было сделано сегодня: чистка кеша удаление скрипта, установка скрипта заново, частично отключал другие дополнения.Не помогло.

**Comment by Oleg-Chashko** [comment]
I just checked, the button is in place and working.
Google Chrome v114.0.5735.133
VOT Cloudflare v.1.2.3

<img width="1019" alt="Screen Shot 2023-06-23 at 10 34 44" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/416253e9-e11d-42cc-b242-e58c58f62dcc">

**Comment by IVJik** [comment]
> I just checked, the button is in place and working. Google Chrome v114.0.5735.133 VOT Cloudflare v.1.2.3
> <img alt="Screen Shot 2023-06-23 at 10 34 44" width="1019" src="https://user-images.githubusercontent.com/62497891/248203374-416253e9-e11d-42cc-b242-e58c58f62dcc.png">
Sorry, problem not only in one video? buttonn disappeared on ANY videos on YT

**Comment by IVJik** [comment]
https://ibb.co/C0mJd41
Выключил все дополнения и сменил версию скрипта на Cloudflare.
Проверил в другом браузере "Firefox developer edition" там всё работает.

**Comment by IVJik** [comment]
В общем каким то макаром...
Но кнопку украли Multi-Account containers Firefox, и показывают её теперь только в контейнерах... и не возвращают её дефолтному аккаунту.
https://ibb.co/pPYS2Jk

**Comment by akela7292** [comment]
У меня тоже пропала кнопка. Что делать?

У вас установлена последняя версия Chrome.
Версия 114.0.5735.134 (Официальная сборка), (64 бит

**Comment by ivdos** [comment]
Так же пропала
Microsoft Edge
Версия 114.0.1823.51 (Официальная сборка) (64-разрядная версия)

**Comment by Oleg-Chashko** [comment]
I installed version 1.2.4, also works well. See if it helps you.
[VOT Cloudflare] - Voice Over Translation  v1.2.4 [https://github.com/SashaXser/voice-over-translation/tree/master/dist](url)

**Comment by SashaXser** [comment]
Попробуй поставить мою версию скрипта, возможно вам это поможет [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist) или вот прямая ссылка на CloudFlare версию [Тык](https://github.com/SashaXser/voice-over-translation/raw/master/dist/vot-cloudflare.user.js)

**Comment by damaskuss** [comment]
до сих пор в хроме не работает

**Comment by ivdos** [comment]
Похоже что-то поменяли на стороне ютуба. Фильтры к imagus тоже не работают.

**Comment by Oleg-Chashko** [comment]
If you clear cookies and cache, the button stops working.

<img width="546" alt="Screen Shot 2023-06-24 at 16 41 09" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/a803194a-99cf-42f0-a4ee-93688c5e858b">

**Comment by ilyhalight** [comment]
Попробуйте обновить скрипт. Только что, проверил всё работает

**Comment by Oleg-Chashko** [comment]
The new version 1.2.4 fixes this bug.

**Comment by IVJik** [comment]
> Попробуйте обновить скрипт. Только что, проверил всё работает

В скрипте нет проблем.
Это вопросс уже к разрабам лисы или мультиакк контейнеров.
Кнопка перевода только там работает.
я и удалял тамперманки, и скрипты из неё, а само дополнение оставлял.
Удалял контейнеры потом заного ставил, кнопка есть только в контенерах.
Лиса или дополнение контейнеров факапит что-то у себя и перевод работает только внутри любого контейнера но не без них.

**Comment by ilyhalight** [comment]
> кнопка есть только в контенерах

Странно конечно, попробовал сделать тоже самое. Поставил обычную лису и на нее накатил Multi-Account containers Firefox, и у меня и в контейнерах, и без них кнопка работает. Наверное, вам действительно попался какой-то баг, связанный с дополнением на контейнеры

**Comment by Protey** [comment]
Подтверждаю в контейнерах (Multi-Account containers Firefox) все работает, а вот без контейнеров нет (**нет кнопки**).
В Violetmonkey, Firemonkey, Greasemonkey скрипт вообще не работает.

Версия Firefox последняя (на момент написания поста) - 114.0.2 (64-разрядный)

**Comment by ivdos** [comment]
@Protey в контейнерах тоже не работает если зайти под своим аккаунтом. 
В общем и целом. Затестил на лисе, эдже. Если на ютубе залогиниться, то кнопка пропадает. Без активного логина. Кнопка перевода есть и перевод работает.

**Comment by IVJik** [comment]
> контейнерах тоже не работает если зайти под своим аккаунтом.

Тааак.А вот это уже интересно.
Проверил.
(У меня есть ещё пара аккуантов чисто для музыки и хобби) в них кнопка есть и перевод работает.
Также и без аккаунта ютуба.
Проверил.Пропажа кнопки связана с аккаунтом. Зашёл с основного в контейнере нет перевода.
Зашёл с музыкального без контейнера есть перевод.

**Comment by ivdos** [comment]
> Зашёл с музыкального без контейнера есть перевод.

Тогда вообще не понимаю что такого в наших аккаунтах, что кнопка при логине перестает показываться? А в других работает.

**Comment by akela7292** [comment]
Версия 1.2.4 так же не работает на youtube.com.  А вот vk работает. И инкогнито работает все. Как быть youtube.com?

**Comment by ilyhalight** [comment]
> Для теста установил контейнеры, И, подтверждаю, в контейнерах (Multi-Account containers Firefox) все работает, а вот без контейнеров нет (нет кнопки).
В Violetmonkey, Firemonkey, Greasemonkey скрипт вообще не работает.
>
>Кнопка есть в - [VK](https://vk.com/), [Vimeo](https://vimeo.com/), [Bilibili](https://bilibili.com/)...(может еще где-то).
Кнопки нет в - [YouTube](https://www.youtube.com/), [Twitch](https://www.twitch.tv/), [Twitter](https://twitter.com/)...(может еще где-то).
>
>Используется Firefox версия (на момент написания поста) - 114.0.2 (64-разрядный), и Tampermonkey версия (на момент написания поста) 4.18.1.

Для твича не работает, потому что в 1.2.4 допущена ошибка в условиях, при которых запускается скрипт для твича, и из-за этого они являются "недосягаемыми".  В след. обнове исправлю

Для VM, FM, GM своя версия скрипта, которая устанавливается ниже основной ссылки на установку.

> @Protey в контейнерах тоже не работает если зайти под своим аккаунтом.
В общем и целом. Затестил на лисе, эдже. Если на ютубе залогиниться, то кнопка пропадает. Без активного логина. Кнопка перевода есть и перевод работает.

> Тааак.А вот это уже интересно.
Проверил.
(У меня есть ещё пара аккуантов чисто для музыки и хобби) в них кнопка есть и перевод работает.
Также и без аккаунта ютуба.
Проверил.Пропажа кнопки связана с аккаунтом. Зашёл с основного в контейнере нет перевода.
Зашёл с музыкального без контейнера есть перевод.

С ютубом так и не получилось воспроизвести. Пробовал:
1) Разные контейнеры без аккаунта
2) Разные контейнеры с разными аккаунтами
3) Без контейнера без аккаунта
4) Без контейнера с разными аккаунтами
5) В инкогнито

**Comment by ivdos** [comment]
@ilyhalight на аккаунтах только по 1 каналу? У меня просто 1 аккаунт и 2 канала, при логине вторым каналом кнопки нет, я с него сижу обычно. При первом есть. Возможно в этом проблема. Нужно, чтобы @IVJik отписался как у него. 
![image](https://github.com/ilyhalight/voice-over-translation/assets/65247362/849efde1-e445-49c9-9ab3-1335fc9a627c)

**Comment by damaskuss** [comment]
@ivdos подтверждаю. если на акке несколько каналов ютуб, то при переключение между ними, кнопка будет появлятся только на одном из них. Что очень не удобно стало

**Comment by ilyhalight** [comment]
> @ilyhalight на аккаунтах только по 1 каналу? У меня просто 1 аккаунт и 2 канала, при логине вторым каналом кнопки нет, я с него сижу обычно. При первом есть. Возможно в этом проблема. Нужно, чтобы @IVJik отписался как у него. ![image](https://user-images.githubusercontent.com/65247362/249234843-849efde1-e445-49c9-9ab3-1335fc9a627c.png)

> @ivdos подтверждаю. если на акке несколько каналов ютуб, то при переключение между ними, кнопка будет появлятся только на одном из них. Что очень не удобно стало

Да, было по одному каналу. Попробовал создать еще один канал, но результата не дало. Возможно, на ютубе что-то тестируют и выборочно дают доступ ¯\_(ツ)_/¯

**Comment by IVJik** [comment]
> Нужно, чтобы @IVJik отписался как у него
Три аккаунта.В двух есть перевод и не важно под контейнерами или нет.
Перевода нет как раз с основного, там и канал к слову есть, но заливаю для своих по ссылке раз в год.



> Возможно, на ютубе что-то тестируют и выборочно дают доступ

Солидарен 💯 .Ничто так не мешает развивать свой софт разработчику одиночке, как постоянные обновления инфраструктуры для которой он писался.

**Comment by Protey** [comment]
Могу так же подтвердить, если на ютуб несколько авторизованных аккаунтов, при переключении на другие аккаунты появляется кнопка перевода

**Comment by 7biz** [comment]
Кнопка не видна потому что прозрачность 0, чтобы стала видна надо поставить 1 в стиле отредактировав скрипт  
95 ( бетте) ___CSS_LOADER_EXPORT___.push([module.id, .......найти opacity: 0;  и заменить на opacity: 1.

**Comment by akela7292** [comment]
@7biz у тебя заработал перевод? Поменял в 95 строке на opacity: 1. Кнопка появляться на пару секунд и после клика пропадает. В тоже время перевод так же не отрабатывает. 
Заметил что при смене акаунта  ютуб  все работает и также в режиме инкогнито.  @ilyhalight 


У вас установлена последняя версия Chrome.
Версия 114.0.5735.199 (Официальная сборка), (64 бит)

**Comment by ilyhalight** [comment]
> @7biz у тебя заработал перевод? Поменял в 95 строке на opacity: 1. Кнопка появляться на пару секунд и после клика пропадает. В тоже время перевод так же не отрабатывает. Заметил что при смене акаунта ютуб все работает и также в режиме инкогнито. @ilyhalight
> 
> У вас установлена последняя версия Chrome. Версия 114.0.5735.199 (Официальная сборка), (64 бит)

Пробовал и в Chrome, и в Firefox. Везде, не получается заставить кнопку пропасть. Похоже, это действительно как-то связано с самим аккаунтом гугла. Скорее всего, как говорил выше, на ютубе действительно что-то тестируют и выдают доступ выборочно.

В консоли так же пусто? Никаких ошибок от расширения нету?

**Comment by SashaXser** [comment]
Попробуй мою версию скрипта, возможно проблема была решена [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

**Comment by Protey** [comment]
> Попробуйте мою версию скрипта, возможно проблема была решена [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

Странные люди, предлагают то в чем сами не уверены "возможно проблема была решена"...
Зачем?

**Comment by SashaXser** [comment]
> > Попробуйте мою версию скрипта, возможно проблема была решена [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)
> 
> Странные люди, предлагают то в чем сами не уверены "возможно проблема была решена"... Зачем?

Вы издеваетесь? Вы не умеете решать проблемы, а только писать сюда. Вы лучше пишите по делу а не всякую ерунду!

**Comment by Protey** [comment]
> Вы издеваетесь? Вы не умеете решать проблемы, а только писать сюда. Вы лучше пишите по делу а не всякую ерунду!

По моему это вы издеваетесь предлагая решение в котором сами не уверены исходя из ваших слов "**возможно** проблема была решена"

**Comment by SashaXser** [comment]
> По моему это вы издеваетесь предлагая решение в котором сами не уверены исходя из ваших слов "**возможно** проблема была решена"

Я не издеваюсь, а пытаюсь помочь. Я предложил решение, которое работало у меня. Я не могу быть уверен, что оно подойдет всем, потому что я не знаю всех деталей ситуации и не могу полностью воспроизвести проблему. Если вы хотите получить более точный ответ, пожалуйста, сделайте исправление сами. Вы максимум можете только жаловаться на проблему, но КПД ваших действий в решении проблемы близок к 0%.

**Comment by Andreykakvasmnogo** [comment]
Доброй ночи! Получается так, что у меня приложение работает, если не входить в акаунт Google, а после входа тут же вылетает. В Хроме и в Опере проверял.

**Comment by ilyhalight** [comment]
> Доброй ночи! Получается так, что у меня приложение работает, если не входить в акаунт Google, а после входа тут же вылетает. В Хроме и в Опере проверял.

Как говорил тут, да и выше тоже, к сожалению, не получается воспроизвести ошибку
