### ISSUE TITLE
Медиаклавиши перестают работать

### ISSUE THREAD

**Issue by SKProCH** [ilyhalight/voice-over-translation#192]
Обычно, при запуске видео, например на ютубе, я могу начать FN + F7 для паузы/продолжения воспроизведения видео. После включения перевода эта возможность пропадает и при нажатии комбинации клавиш лишь появляется обводка текста в кнопке "Выключить".

![image](https://github.com/ilyhalight/voice-over-translation/assets/29896317/73c3ff30-c2cb-4eb7-8271-0c3d6da3ce0c)

**Comment by ilyhalight** [comment]
Какой браузер? В Firefox всё работает

**Comment by SKProCH** [comment]
> Какой браузер? В Firefox всё работает

Chrome 115.0.5790.40

**Comment by DygDyg** [comment]
В эдже так же не работают мультимедиа кнопки, когда включён перевод. Могу предположить, что кнопки начинают управлять не самим видео, аудиодорожкой перевода.

**Comment by KrevetkaOo** [comment]
именно когда включён перевод перестают работать клавиши мультимедиа, если отключить перевод, то кнопки снова начинают работать.

**Comment by ilyhalight** [comment]
Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, должно работать

**Comment by ilyhalight** [comment]
> Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, должно работать

Исправлено, но работает, только, если включен "Новый аудиоплеер"
