### ISSUE TITLE
Кнопка "перевести" не кликабельна

### ISSUE THREAD

**Issue by WhiteBite** [ilyhalight/voice-over-translation#193]
Почему-то кнопка  "перевести видео" не кликается. Самое странное, что она работает в режиме инкогнито

**Comment by ilyhalight** [comment]
Браузер? Что-то в консоли пишет?

**Comment by ilyhalight** [comment]
Попробуйте сбросить базу данных расширения по гайду на главной странице репозитория. Если проблема не была решена, то переоткройте
