### ISSUE TITLE
Не появляется кнопка

### ISSUE THREAD

**Issue by Aitix** [ilyhalight/voice-over-translation#195]
Ничего не удалял, не устанавливал. Еще на днях мог юзать — сейчас просто нет кнопки перевести. Последняя версия как браузера, так и этой утилиты.

**Comment by Shagy25** [comment]
Тоже самое. Кнопка просто исчезла. Стоит последняя версия Firefox, ничего не трогал. В TemperMonkey на ютубе в конце скрипта показывается такое сообщение: eslint: no-case-declarations - Unexpected lexical declaration in case block

**Comment by SashaXser** [comment]
> Ничего не удалял, не устанавливал. Еще на днях мог юзать — сейчас просто нет кнопки перевести. Последняя версия как браузера, так и этой утилиты.

Пожалуйста, подскажите, как воспроизвести проблему.

**Comment by ilyhalight** [comment]
> Ничего не удалял, не устанавливал. Еще на днях мог юзать — сейчас просто нет кнопки перевести. Последняя версия как браузера, так и этой утилиты.

Так же, как и для Firefox - не получается воспроизвести

**Comment by Shagy25** [comment]
Проблема как-то связана с аккаунтом в гугле. У меня есть основной и тот, куда заливаю видео. На основном кнопка не появляется, на втором - все работает.

**Comment by lesliefag** [comment]
Подтверждаю, воспроизводится только на ютубе под основным аккаунтом, перелогинился под новый - кнопка появилась.

**Comment by Mefisst** [comment]
у меня так и не появляется (((( приходиться использовать яндекс браузер

**Comment by ilyhalight** [comment]
> у меня основной акаунт в ютубе не переводит, создал дополнительный и там появилась кнопка, с чем связано?

я бы сам знал с чем это связано

**Comment by lizardjazz1** [comment]
В прошлый раз я подобное решил отключением остальных плагинов на файрфоксе, но сейчас они все выключены, а кнопка не появляется

**Comment by tommydii** [comment]
Не появляется кнопка 
// ==UserScript==
// @name [VOT Cloudflare] - Voice Over Translation
1.41 beta
браузер FireFox

**Comment by SashaXser** [comment]
> Не появляется кнопка // ==UserScript== // @name [VOT Cloudflare] - Voice Over Translation 1.41 beta браузер FireFox

Создай отдельный Issue

**Comment by ilyhalight** [comment]
Изначальная проблема еще актуальна?

**Comment by ilyhalight** [comment]
> Не появляется кнопка // ==UserScript== // @name [VOT Cloudflare] - Voice Over Translation 1.41 beta браузер FireFox

Попробуйте обновиться до релиза 1.4.1. Если не поможет, то сделайте отдельный Issue и приложите логи консоли

**Comment by ilyhalight** [comment]
Если проблема не решена откройте заново
