### ISSUE TITLE
Кнопка не появляется на YouTube

### ISSUE THREAD

**Issue by TEPA6ANT** [ilyhalight/voice-over-translation#196]
Браузер - Opera GX (99.0.4788.86)
Расширение - Tampermonkey v4.16.6160
(Другие установленные расширения: AdGuard, Youtube-shorts block, Return YouTube Dislike, Rememberry, Browsec VPN.
Но даже если их всех выключить, проблема остаётся)

Кнопка не появляется только на YouTube. В коде страницы она есть, но просто не появляется при наведении на видео. 
Конечно, можно её сделать видимой, отредактировав код страницы, но в таком случае не нажимается.

На других сайтах, вроде Твиттер, кнопка появляется.

**Comment by TEPA6ANT** [comment]
Кнопка есть, если сменить аккаунт на основной.

**Comment by GoGagoo** [comment]
> Кнопка есть, если сменить аккаунт на основной.
а возможно, что на второстепенном аккаунте в будущем заработает?

**Comment by curkan** [comment]
Браузер Safari, кнопка тоже не появляется. Проверял на Vimeo, там все есть. На YouTube не работает

**Comment by ilyhalight** [comment]
Еще актуально?

**Comment by TEPA6ANT** [comment]
> Еще актуально?

на данный момент, всё работает как должно быть.
