### ISSUE TITLE
Как в последней версии 1.2.4 уменьшить громкость перевода до 0%

### ISSUE THREAD

**Issue by AvenCores** [ilyhalight/voice-over-translation#197]
Т.к в последней версии код зашифрован я банально теперь не могу это сделать :(
![image](https://github.com/ilyhalight/voice-over-translation/assets/64781822/dae6aedc-9f9d-4650-90f4-a696739e35cc)

**Comment by ilyhalight** [comment]
До 1.3.0 обновись, там не минифицирован код
