### ISSUE TITLE
Перевод видео из ютуб на других сайтах

### ISSUE THREAD

**Issue by leex-leex** [ilyhalight/voice-over-translation#198]
Здравствуйте.
Можно ли попросить добавить закадровый перевод видео из ютуба, когда просматриваешь видео на других сайтах?

**Comment by ilyhalight** [comment]
> Можно ли простить добавить закадровый перевод видео из ютуба, когда просматриваешь видео на других сайтах?

Перевод из ютуба работает на всех сайтах, где встроен плеер ютуба

**Comment by SashaXser** [comment]
> > Можно ли простить добавить закадровый перевод видео из ютуба, когда просматриваешь видео на других сайтах?
> 
> Перевод из ютуба работает на всех сайтах, где встроен плеер ютуба

Нет, он работает только на сайтах Youtube, там банальная проверка на домены ютуба, которая не даст использовать тебе на других сайтах где встроен плеер ютуба. 
`` 
    if (regexes.youtubeRegex.test(window.location.hostname)) { ``

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/15142e3d-13d3-45ca-b160-316ccb0644e2)

**Comment by ilyhalight** [comment]
> Нет, он работает только на сайтах Youtube, там банальная проверка на домены ютуба, которая не даст использовать тебе на других сайтах где встроен плеер ютуба.

Я имею ввиду про встраивание через iframe. Если встраивать через iframe, то идет проверка на домен iframe, а не на домен основного сайта.

Но справедливости ради, ютуб через iframe действительно почему-то перестал работать (скорее всего из-за того, что не работает на youtube.com/embed/XXX)
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/2a2dd62c-bbc2-418f-a41a-368f4e690590)

**Comment by SashaXser** [comment]
> > Нет, он работает только на сайтах Youtube, там банальная проверка на домены ютуба, которая не даст использовать тебе на других сайтах где встроен плеер ютуба.
> 
> Я имею ввиду про встраивание через iframe. Если встраивать через iframe, то идет проверка на домен iframe, а не на домен основного сайта.
> 
> Но справедливости ради, ютуб через iframe действительно почему-то перестал работать (скорее всего из-за того, что не работает на youtube.com/embed/XXX) ![image](https://user-images.githubusercontent.com/62353659/249895645-2a2dd62c-bbc2-418f-a41a-368f4e690590.png)

Дополню, piped тоже сломался после перехода на shaka player

**Comment by ilyhalight** [comment]
> Дополню, piped тоже сломался после перехода на shaka player.

Чуть позже гляну и постараюсь исправить

**Comment by ilyhalight** [comment]
Исправил и piped и youtube embed
