### ISSUE TITLE
Установка на удаленном сервере.

### ISSUE THREAD

**Issue by OwnerLink** [ilyhalight/voice-over-translation#2]
Привет! Можно ли как-то адаптировать это дело под установку на удаленном сервере? Чтобы веб сервер и яндекс браузер запускались там, а на основной пк просто прилетал перевод? А если это и так можно сделать, то, если не сложно, распиши инструкцию.

**Comment by ilyhalight** [comment]
> Привет! Можно ли как-то адаптировать это дело под установку на удаленном сервере? Чтобы веб сервер и яндекс браузер запускались там, а на основной пк просто прилетал перевод? А если это и так можно сделать, то, если не сложно, распиши инструкцию.

Пытался сделать такое с vds на линуксе, но насколько я понял, там не работает функция перевода из-за того, что нет графического интерфейса. Если vds на виндовс, то делаешь так же, как и на своём пк:
1. Ставишь ЯБраузер на VDS
2. Ставишь веб-сервер на VDS
3. На своём ПК заходишь в расширение tampermonkey (или что ты там используешь)
4. Находишь данный скрипт  (voice-over-translation) в tampermonkey и меняешь все значения "127.0.0.1", на IP-адрес твоего VDS (Пример IP-Адреса: 10.123.11.0)
P.S.: Нужно поменять в `@connect 127.0.0.1` и в `url: "http://127.0.0.1:3000/video",`

Вроде бы, так.

**Comment by OwnerLink** [comment]
Понял, придется искать где за недорого арендовать vds на виндовс :) Просто имею vds-ку на линуксе с прокси, думал получится там завести. Ну в любом случае спасибо за помощь!

**Comment by OwnerLink** [comment]
Кстати только что пришла мысль попробовать накатить на сервак граф. оболочку. Короче буду пробовать, если че получится отпишусь.

**Comment by lp85d** [comment]
Нужен реальны веб сервер? Обращайтесь в телегу lp85d помогу
Простаивает без дела на процессоре i3 12 оперативы
Рассмотрю любые варианты сотрудничества
