### ISSUE TITLE
Firefox doesn't work

### ISSUE THREAD

**Issue by emma910** [ilyhalight/voice-over-translation#20]
VOT: Получены данные из Базы Данных:  undefined [voice-over-translation.user.js:338:17](moz-extension://55960eec-41b5-4e2b-930d-c4eb76f80220/userscripts/voice-over-translation.user.js?id=9130d0a7-18c1-46b7-a09a-6967b8cd2c6a)
Uncaught (in promise) TypeError: dbData is undefined
    tms_9130d0a7_18c1_46b7_a09a_6967b8cd2c6a$/< moz-extension://55960eec-41b5-4e2b-930d-c4eb76f80220/userscripts/voice-over-translation.user.js?id=9130d0a7-18c1-46b7-a09a-6967b8cd2c6a:365
    dispatch moz-extension://55960eec-41b5-4e2b-930d-c4eb76f80220/userscripts/voice-over-translation.user.js?id=9130d0a7-18c1-46b7-a09a-6967b8cd2c6a:3
    handle moz-extension://55960eec-41b5-4e2b-930d-c4eb76f80220/userscripts/voice-over-translation.user.js?id=9130d0a7-18c1-46b7-a09a-6967b8cd2c6a:3
    xb https://www.youtube.com/s/desktop/8d5d4899/jsbin/webcomponents-sd.vflset/webcomponents-sd.js:41
    dispatchEvent https://www.youtube.com/s/desktop/8d5d4899/jsbin/webcomponents-sd.vflset/webcomponents-sd.js:106
    fire https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:6090
    performDataUpdate https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:21642
    e https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:21637
    measurePaintTime https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:9829
    e https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:21637
    I https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:29
    O https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:38
    S https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:34
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    start https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:39
    O https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:38
    P https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:31
    requestIdleCallback handler*f.start https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:39
    O https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:38
    P https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:31
    requestIdleCallback handler*f.start https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:39
    O https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:38
    S https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:34
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    start https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:39
    J https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:26
    d https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:44
    setTimeout handler*ka https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:44
    addJob https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:1292
    addLowPriorityJob https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:1285
    Ek https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:1572
    Bk https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:1572
    ua https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:48
    next https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:50
    b https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:53
    promise callback*h https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:55
    promise callback*h https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:55
    uaa https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:56
    uaa https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:55
    r https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:56
    Bk https://www.youtube.com/s/desktop/8d5d4899/jsbin/desktop_polymer.vflset/desktop_polymer.js:1572
    I https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:29
    O https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:38
    S https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:34
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    requestAnimationFrame https://www.youtube.com/s/desktop/8d5d4899/jsbin/web-animations-next-lite.min.vflset/web-animations-next-lite.min.js:96
    start https://www.youtube.com/s/desktop/8d5d4899/jsbin/scheduler.vflset/scheduler.js:39

**Comment by ilyhalight** [comment]
Перезапусти страницу с ютубом. В теории - должно помочь, ибо база данных не инициализавалась. Если не поможет, то проверь разрешения у Tampermonkey

**Comment by emma910** [comment]
Перезапустить  - серьезно? Я даже комп перезагружал, не то, что страницу. Ну рили, что за отмазки, может поставишь и потетсируешь браузер? )

**Comment by emma910** [comment]
о каких разрешениях речь?

**Comment by ilyhalight** [comment]
> Ну рили, что за отмазки, может поставишь и потетсируешь браузер? )

Стоит Firefox как мейн браузер. Проблем с расширением не испытываю. Попросил перезагрузить страницу т.к при перезагрузке проверяется наличие базы данных, и если её нету, то создаётся бд для настроек расширения.

> о каких разрешениях речь?

![изображение](https://user-images.githubusercontent.com/62353659/186272478-a181d19a-c360-4b64-8cc8-8368421a27aa.png)

**Comment by ilyhalight** [comment]
> > Ну рили, что за отмазки, может поставишь и потетсируешь браузер? )
> 
> Стоит Firefox как мейн браузер. Проблем с расширением не испытываю. Попросил перезагрузить страницу т.к при перезагрузке проверяется наличие базы данных, и если её нету, то создаётся бд для настроек расширения.
> 
> > о каких разрешениях речь?
> 
> ![изображение](https://user-images.githubusercontent.com/62353659/186272478-a181d19a-c360-4b64-8cc8-8368421a27aa.png)

Если не собираешься постоянно переключать галочку "автоперевода", то можешь использовать прикрепленную ниже версию с вырезанной бд. Значение "Автоперевода" можно будет изменить, поменяв в коде расширения значение этой переменной (чекбокс в меню будет не рабочим):
`const isDBInited = true // true - Enable / false - Disable autotranslate`

[Скачать](https://drive.google.com/file/d/1tpIEEkfRSfyffphN9CAK9FNlMNsOyC1F/view?usp=sharing)

**Comment by emma910** [comment]
Разрешения такие же стоят. Как будем ловить баг?

**Comment by ilyhalight** [comment]
> Разрешения такие же стоят. Как будем ловить баг?

Хотелось бы узнать версию браузера, а так же, чтобы вы сделали тест на этом сайте: https://firefox-storage-test.glitch.me/ (предпоследняя колонка должна содержать working или что-то такое если все в порядке, Иначе нужно искать источник проблемы в настройках браузера)

**Comment by emma910** [comment]
LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

**Comment by DmitriyPekar** [comment]
у меня конечно не сам Firefox, а его форк, но и нам нём всё прекрасно работает

**Comment by emma910** [comment]
![image](https://user-images.githubusercontent.com/111916193/186421114-13b06422-720e-494e-93b0-f87215ae10dd.png)
![image](https://user-images.githubusercontent.com/111916193/186421185-89b69f24-6d4b-492c-9af8-aa2a736252cb.png)

**Comment by emma910** [comment]
Лог "новой версии"
![image](https://user-images.githubusercontent.com/111916193/186421751-f1eb33fd-cae8-4e40-b205-d958edb48e0a.png)

**Comment by ilyhalight** [comment]
> В сторадже по-прежнему нет ключа в разделе Settings, но заработало! Перевелось через минутку ожидания

Если не затруднит, попробуй вот [эту](https://drive.google.com/file/d/1ibKGwlU6Jmq2uGtT-luBN2vnFSwLUeVe/view?usp=sharing) версию. С ней бд должна будет обновится, и ключ в разделе Settings появится

**Comment by emma910** [comment]
Да, алертнулось, попросило обновить страницу. После чего ключ появился. Рад, что помог тебе сделать скрипт лучше.
