### ISSUE TITLE
Порт для mpv

### ISSUE THREAD

**Issue by ghost** [ilyhalight/voice-over-translation#201]
Было бы шикарно, если бы появился порт для проигрывателя mpv.

Спасибо за расширение!

**Comment by tyusha0** [comment]
> Было бы шикарно, если бы появился порт для проигрывателя mpv.
> 
> Спасибо за расширение!

Насколько я понял данные сериализованны в protobuf, но передаются post запросом.
protobuf для lua вроде есть, но знаний одного и второго нет...
Надо попробовать поиграться с postman

Но по моему, проще порт vot-cli на python

**Comment by Olejja** [comment]
Но в целом это осуществимо?

**Comment by tyusha0** [comment]
> Но в целом это осуществимо?

Наверно да. И оказывается mpv поддерживает скриптинг не только на lua https://github.com/mpv-player/mpv/wiki/Language-bindings  

Я пока пользую так:

#!/bin/bash
yt_video="$1"
vot_audio=$(node index.js "$yt_video" | cut -d " " -f 6 | tr -d $'\n')
mpv "$yt_video" \
--external-file="$vot_audio" \
--lavfi-complex='[aid1]volume=0.5[vol1];[aid2]volume=3dB[vol2];[vol1][vol2]amix[ao]'

**Comment by Olejja** [comment]
> Но по моему, проще порт vot-cli на python

Не смог найти его. Он существует?

**Comment by tyusha0** [comment]
> > Но по моему, проще порт vot-cli на python
> 
> Не смог найти его. Он существует?

Пока нет #125
Может я попробую если будет время
