### ISSUE TITLE
"Формат аудио не поддерживается" при таймауте / недоступность при заблокированном Яндексе

### ISSUE THREAD

**Issue by Metadorius** [ilyhalight/voice-over-translation#202]
Steps to reproduce:
1. Находиться в/на Украине и не пользоваться VPN-ом.
2. Попробовать поставить юзерскрипт и включить любое видео.

Ожидаемый результат: ошибка "Превышено время ожидания сервера".
Действительный результат: ошибка "Формат аудио не поддерживается", а в консоли браузера уже таймаут пишет.

Конечно, совсем классно было бы, если бы запросы проксировались чем-то для тех, у кого Яндекс блокируется, но это уже хотелки, и так здорово, что такой юзерскрипт существует :)

**Comment by SashaXser** [comment]
> Steps to reproduce:
> 
>     1. Находиться в/на Украине и не пользоваться VPN-ом.
> 
>     2. Попробовать поставить юзерскрипт и включить любое видео.
> 
> 
> Ожидаемый результат: ошибка "Превышено время ожидания сервера". Действительный результат: ошибка "Формат аудио не поддерживается", а в консоли браузера уже таймаут пишет.
> 
> Конечно, совсем классно было бы, если бы запросы проксировались чем-то для тех, у кого Яндекс блокируется, но это уже хотелки, и так здорово, что такой юзерскрипт существует :)

Для этого существует версия Cloudflare, она у всех работает

**Comment by Metadorius** [comment]
Ну во-первых, не у всех, потому что у меня как раз она стоит и она не работает. Во-вторых, спасибо, в курсе, чай не первый день живу здесь ;)

![image](https://github.com/ilyhalight/voice-over-translation/assets/17500545/bb459083-1c8a-4538-b1b7-ed3734be3d81)

**Comment by Metadorius** [comment]
Ну и да, чтоб уж совсем вопросов не было, все другие юзерскрипты и расширения, связанные с ютубом, отключал, не в них дело.

**Comment by SashaXser** [comment]
> Ну во-первых, не у всех, потому что у меня как раз она стоит и она не работает. Во-вторых, спасибо, в курсе, чай не первый день живу здесь ;)
> 
> ![image](https://user-images.githubusercontent.com/17500545/250277661-bb459083-1c8a-4538-b1b7-ed3734be3d81.png)

Если хотите чтобы все работало, надо прость Илью поменять на сервере вместо выдачи ссылки выдавать аудиофайл

**Comment by Metadorius** [comment]
Что есть WARP, какой-то VPN/прокси?

**Comment by Metadorius** [comment]
UPD: нашёл, это клоудфларевский DNS или что-то такое. Спасибо, погляжу, хотя я и так могу обойти. Было бы действително неплохо без обходов, чтоб работало.

**Comment by SashaXser** [comment]
> UPD: нашёл, это клоудфларевский DNS или что-то такое. Спасибо, погляжу, хотя я и так могу обойти. Было бы действително неплохо без обходов, чтоб работало.

Надо будет переделать сервер на cloudflare, и думаю проблема решится. Увы других идей нет, только передавать аудио напрямую заместо редиректа.

**Comment by ilyhalight** [comment]
Попробовал добавить, если будет время можешь проверить. В меню надо поставить галочку "Проксировать полученное аудио" (если галочки нету сбрось настройки расширения)
https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view?usp=sharing

**Comment by FiLinX** [comment]
а если проверить замену всех *.yandex.ru на *,yandex.com ? вдруг прокатит)  
ну, по крайней мере апи переводчика яндексового точно работает и на .com
хотя, трассировку то я и не смотрел)

**Comment by SashaXser** [comment]
> yandex.com

Я думаю, что реализация через CloudFlare куда надежнее и 100% будет работать у всех. В добавок, yandex.com также находится на русском IP-адресе, вполне возможно, что и он может в будущем перестать работать.

**Comment by Metadorius** [comment]
> Попробовал добавить, если будет время можешь проверить. В меню надо поставить галочку "Проксировать полученное аудио" (если галочки нету сбрось настройки расширения) https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view?usp=sharing

Попробовал. Что-то галки не нашёл, а сброс настроек вот такое показывает после сброса: 
![image](https://github.com/ilyhalight/voice-over-translation/assets/17500545/da91de39-f582-4e39-b8db-f982a3fce219)
Если рестартнуть браузер - всё возвращается на место, но галки до сих пор нету. Я на violentmonkey, если что. Пробовал и как новый юзерскрипт с другим именем грузить, и старый удалить, одно и то же.

**Comment by Metadorius** [comment]
> а если проверить замену всех *.yandex.ru на *,yandex.com ? вдруг прокатит) ну, по крайней мере апи переводчика яндексового точно работает и на .com хотя, трассроут то я и не смотрел)

Украинские провайдеры блокируют по IP, а не по DNS-имени. Запросы идут на yandex.net вообще.

**Comment by SashaXser** [comment]
> > Попробовал добавить, если будет время можешь проверить. В меню надо поставить галочку "Проксировать полученное аудио" (если галочки нету сбрось настройки расширения) https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view?usp=sharing
> 
> Попробовал. Что-то галки не нашёл, а сброс настроек вот такое показывает после сброса, а кнопка сама не работает: ![image](https://user-images.githubusercontent.com/17500545/250547651-da91de39-f582-4e39-b8db-f982a3fce219.png) Если рестартнуть браузер - всё возвращается на место, но галки до сих пор нету. Я на violentmonkey, если что. Пробовал и как новый юзерскрипт с другим именем грузить, и старый удалить, одно и то же. В консоли ошибок вроде не видно.

Попробуй в TamperMoney

**Comment by Metadorius** [comment]
> Попробуй в TamperMonkey

Та же петрушка, аналогичные проблемы.

**Comment by SashaXser** [comment]
> > Попробуй в TamperMonkey
> 
> Та же петрушка, аналогичные проблемы.

Понял в чём ошибка, в старом хроме (86) и FF всё работает, а в новом хроме скрипт создания базы не создает пункт с проксированием, и даже если создать его вручную то он просто не работает.

**Comment by ilyhalight** [comment]
Полноценно "Проксировать полученное аудио" было добавлено в релиз 1.3.2. Сбрасывать базу данных, теперь, тоже не нужно.

**Comment by Leshugan** [comment]
> Попробовал добавить, если будет время можешь проверить. В меню надо поставить галочку "Проксировать полученное аудио" (если галочки нету сбрось настройки расширения) https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view?usp=sharing

Спасибо это помогло исправить проблему "Формат аудио не поддерживается" для украины
