### ISSUE TITLE
Перевод интерфейса

### ISSUE THREAD

**Issue by rassie** [ilyhalight/voice-over-translation#203]
А как обстоят дела с переводом интерфейса хотя бы на английский? Есть какие-то правовые препятствия или просто руки не дошли / не было необходимости? Патчи можно слать?

**Comment by ilyhalight** [comment]
Никто ни разу и не просил перевод интерфейса, если есть желание, то конечно можете сделать - добавлю

**Comment by FiLinX** [comment]
хы, как только я узнал про включение яндыксом перевода видосов ru-en, то сразу всем своим забугорным контактам ссылку на VOT разослал..  правда все контакты русскоговорящие) 
но если англифицировать интерфейсу и README.md тут, и подкинуть мазу в ихние топовые фбуки-тики-твитусы, то думаю Илье стоит подумать о прикрутке какой-нить денюжко-кликовой вставочке))

**Comment by ilyhalight** [comment]
Поразмыслил немного, в целом, переводить не так уж и много. Если будет лишнее время, и если найду куда прикрутить менюшку со сменой языка, то может быть и сам сделаю

**Comment by SashaXser** [comment]
Я сделал перевод на 7 языков, чтобы им воспользоваться вам нужно выставить язык отображения страниц на интересующий (ru, en, zh, fr, it, es, de) #212. Осталось лишь перевести языки и перевод можно считать готовым. Пока переведен только интерфейс, возможно потом кто-то переведет языки.

**Comment by ilyhalight** [comment]
В 1.3.3 расширение было полностью переведено на 7 доступных языков. Язык на данный момент выбирается на основе языка браузера

**Comment by rassie** [comment]
Спасибо, ребята! Я даже не успел мяу сказать, как уже все сделали.
