### ISSUE TITLE
Асинхронность аудио дорожки с видео

### ISSUE THREAD

**Issue by Woukim** [ilyhalight/voice-over-translation#204]
После обновления перевод начинает озвучивать с самого начала видео, несмотря на перемотку, после паузы и воспроизведения так же начинает с самого начала озвучивать. Обновление страницы не помогает

**Comment by ilyhalight** [comment]
Это в каком браузере и сайте? Только что проверил в FF, там всё нормально

**Comment by Woukim** [comment]
В очередной раз обновил страницу и стало норм..но все равно такого никогда прежде не было) браузер Edge, youtube
