### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by DimDevOff** [ilyhalight/voice-over-translation#205]
### Я использую версию Edge 114.0.1823.67.
**И когда я нажимаю на кнопку "Перевести видео" то сначала ничего не происходит а потом пишет "Не удалось запросить перевод видео"**
В чем проблема?

**Comment by ilyhalight** [comment]
Попробуйте cloudflare-версию. Если с ней у вас будет ошибка "формат аудио не поддерживается", то включите "проксировать полученное аудио" в меню расширения. Если всё равно проблема не было решена, то заново откройте ветку и предоставьте скриншоты консоли. Пока помечаю как решено.

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/563c086d-276a-4973-9170-cf85155c1257)
