### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by LeonINFIZ** [ilyhalight/voice-over-translation#206]
Установил расширение и скрипт (раздел как собрать расширение не трогал), зашел на видео: 
https://www.youtube.com/watch?v=3n7HXbKRgb0

Вроде кнопка появилась, но при нажатии выдаёт "Не удалось запросить перевод видео"
 
 
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/4c67ba2e-aa54-4590-b34f-73c3acfbab17)

Использую Orepa GX.

![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/accf8f77-6fea-46ee-b74d-04c410c618e4)

**Comment by SashaXser** [comment]
Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)

**Comment by LeonINFIZ** [comment]
Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?

> Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)

**Comment by SashaXser** [comment]
> Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> 
> > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)

Консоли браузера, нет не в этом

**Comment by LeonINFIZ** [comment]
> > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> 
> Консоли браузера, нет не в этом

![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/c8ce3cee-4e66-47c7-b10b-a78964c9c38e)
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/12c0866a-9a96-475c-bb2d-8124a4762146)

**Comment by SashaXser** [comment]
> > > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> > 
> > 
> > Консоли браузера, нет не в этом
> 
> ![image](https://user-images.githubusercontent.com/63362730/250569100-c8ce3cee-4e66-47c7-b10b-a78964c9c38e.png) ![image](https://user-images.githubusercontent.com/63362730/250569186-12c0866a-9a96-475c-bb2d-8124a4762146.png)

Хм, зайдите во вкладку "Сеть" и в поиске напишите trans и скиньте скриншот. А также попробуй скрипт который я скинул выше

**Comment by LeonINFIZ** [comment]
> > > > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> > > 
> > > 
> > > Консоли браузера, нет не в этом
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/63362730/250569100-c8ce3cee-4e66-47c7-b10b-a78964c9c38e.png) ![image](https://user-images.githubusercontent.com/63362730/250569186-12c0866a-9a96-475c-bb2d-8124a4762146.png)
> 
> Хм, зайдите во вкладку "Сеть" и в поиске напишите trans и скиньте скриншот. А также попробуй скрипт который я скинул выше

Скрин из сетью от 1-го скрипта, остальный относительно твоего скрипта. К слову, используя твой скрипт кнопка не появляется.
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/414c2967-bf71-4982-899a-6c6ea4fd5392)
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/a46fb717-f511-4162-909b-43a5cbcda135)
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/99bd5474-2bcc-4c85-b460-c2550cacfec6)

**Comment by SashaXser** [comment]
> > > > > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > > > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> > > > 
> > > > 
> > > > Консоли браузера, нет не в этом
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/63362730/250569100-c8ce3cee-4e66-47c7-b10b-a78964c9c38e.png) ![image](https://user-images.githubusercontent.com/63362730/250569186-12c0866a-9a96-475c-bb2d-8124a4762146.png)
> > 
> > 
> > Хм, зайдите во вкладку "Сеть" и в поиске напишите trans и скиньте скриншот. А также попробуй скрипт который я скинул выше
> 
> Скрин из сетью от 1-го скрипта, остальный относительно твоего скрипта. К слову, используя твой скрипт кнопка не появляется. ![image](https://user-images.githubusercontent.com/63362730/250571142-414c2967-bf71-4982-899a-6c6ea4fd5392.png) ![image](https://user-images.githubusercontent.com/63362730/250571425-a46fb717-f511-4162-909b-43a5cbcda135.png) ![image](https://user-images.githubusercontent.com/63362730/250571480-99bd5474-2bcc-4c85-b460-c2550cacfec6.png)

Вы поначалу использовали версию без Cloudflare?

**Comment by LeonINFIZ** [comment]
> > > > > > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > > > > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> > > > > 
> > > > > 
> > > > > Консоли браузера, нет не в этом
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/63362730/250569100-c8ce3cee-4e66-47c7-b10b-a78964c9c38e.png) ![image](https://user-images.githubusercontent.com/63362730/250569186-12c0866a-9a96-475c-bb2d-8124a4762146.png)
> > > 
> > > 
> > > Хм, зайдите во вкладку "Сеть" и в поиске напишите trans и скиньте скриншот. А также попробуй скрипт который я скинул выше
> > 
> > 
> > Скрин из сетью от 1-го скрипта, остальный относительно твоего скрипта. К слову, используя твой скрипт кнопка не появляется. ![image](https://user-images.githubusercontent.com/63362730/250571142-414c2967-bf71-4982-899a-6c6ea4fd5392.png) ![image](https://user-images.githubusercontent.com/63362730/250571425-a46fb717-f511-4162-909b-43a5cbcda135.png) ![image](https://user-images.githubusercontent.com/63362730/250571480-99bd5474-2bcc-4c85-b460-c2550cacfec6.png)
> 
> Вы поначалу использовали версию без Cloudflare?

Да, так как ссылка на неё указана на репозитории.

**Comment by SashaXser** [comment]
> > > > > > > Я же сказал что не установил node.js, какой консоли?) Или проблема в том что как раз таки node.js не установлен?
> > > > > > > > Покажите скриншот консоли, также можете попробывать этот скрипт [Тык](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view)
> > > > > > 
> > > > > > 
> > > > > > Консоли браузера, нет не в этом
> > > > > 
> > > > > 
> > > > > ![image](https://user-images.githubusercontent.com/63362730/250569100-c8ce3cee-4e66-47c7-b10b-a78964c9c38e.png) ![image](https://user-images.githubusercontent.com/63362730/250569186-12c0866a-9a96-475c-bb2d-8124a4762146.png)
> > > > 
> > > > 
> > > > Хм, зайдите во вкладку "Сеть" и в поиске напишите trans и скиньте скриншот. А также попробуй скрипт который я скинул выше
> > > 
> > > 
> > > Скрин из сетью от 1-го скрипта, остальный относительно твоего скрипта. К слову, используя твой скрипт кнопка не появляется. ![image](https://user-images.githubusercontent.com/63362730/250571142-414c2967-bf71-4982-899a-6c6ea4fd5392.png) ![image](https://user-images.githubusercontent.com/63362730/250571425-a46fb717-f511-4162-909b-43a5cbcda135.png) ![image](https://user-images.githubusercontent.com/63362730/250571480-99bd5474-2bcc-4c85-b460-c2550cacfec6.png)
> > 
> > 
> > Вы поначалу использовали версию без Cloudflare?
> 
> Да, так как ссылка на неё указана на репозитории.

Теперь понятно, попробуйте использовать CloudFlare версию, либо которая находится в этом репозетории либо мою [Тык](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

**Comment by LeonINFIZ** [comment]
А, всё ясно. Нужно было VPN включить, я нахожусь в Украине, у нас .ru сайты не работают без него.
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/e22d7aee-2a9b-4033-8b2b-10125d1a2277)

**Comment by SashaXser** [comment]
> А, всё ясно. Нужно было VPN включить, я нахожусь в Украине, у нас .ru сайты не работают без него. ![image](https://user-images.githubusercontent.com/63362730/250574621-e22d7aee-2a9b-4033-8b2b-10125d1a2277.png)

Понятно, но при использовании [этого](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) у вас не появляется кнопка?

**Comment by LeonINFIZ** [comment]
Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.

**Comment by SashaXser** [comment]
> Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.

Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...

**Comment by LeonINFIZ** [comment]
> > Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.
> 
> Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...

Кнопка появилась, но там уже другая проблема
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/bfeccfc7-821a-49b4-852a-e0f4ddab5224)

**Comment by SashaXser** [comment]
> > > Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.
> > 
> > 
> > Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...
> 
> Кнопка появилась, но там уже другая проблема ![image](https://user-images.githubusercontent.com/63362730/250578637-bfeccfc7-821a-49b4-852a-e0f4ddab5224.png)

Вы поставили пункт в меню проксирование аудио?

**Comment by LeonINFIZ** [comment]
> > > > Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.
> > > 
> > > 
> > > Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...
> > 
> > 
> > Кнопка появилась, но там уже другая проблема ![image](https://user-images.githubusercontent.com/63362730/250578637-bfeccfc7-821a-49b4-852a-e0f4ddab5224.png)
> 
> Вы поставили пункт в меню проксирование аудио?

Было бы где
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/a80b6dda-f4ab-4cc9-a0f9-d74d36dcd693)

**Comment by SashaXser** [comment]
> > > > > Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.
> > > > 
> > > > 
> > > > Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...
> > > 
> > > 
> > > Кнопка появилась, но там уже другая проблема ![image](https://user-images.githubusercontent.com/63362730/250578637-bfeccfc7-821a-49b4-852a-e0f4ddab5224.png)
> > 
> > 
> > Вы поставили пункт в меню проксирование аудио?
> 
> Было бы где ![image](https://user-images.githubusercontent.com/63362730/250579638-a80b6dda-f4ab-4cc9-a0f9-d74d36dcd693.png)



> > > > > Используя [это](https://github.com/SashaXser/voice-over-translation/blob/master/dist/vot-cloudflare.user.js), кнопка появилась.
> > > > 
> > > > 
> > > > Понятно, значит IndexedDB действительно может блокировать появление кнопки. Насчет VPN то да, в Украине блокируются Российские IP адреса, как указано в #202. В этом [скрипте](https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view) был изменен алгоритм получения аудио, и поэтому он должен был был исправить вашу проблему. Но у вас, не работает кнопка в этом скрипте...
> > > 
> > > 
> > > Кнопка появилась, но там уже другая проблема ![image](https://user-images.githubusercontent.com/63362730/250578637-bfeccfc7-821a-49b4-852a-e0f4ddab5224.png)
> > 
> > 
> > Вы поставили пункт в меню проксирование аудио?
> 
> Было бы где ![image](https://user-images.githubusercontent.com/63362730/250579638-a80b6dda-f4ab-4cc9-a0f9-d74d36dcd693.png)

Извините, я забыл сказать что нужно сбросить настройки для её появление.

**Comment by LeonINFIZ** [comment]
Гуд, гуд гуд гуд, всё пашет. Спасибо)

**Comment by ilyhalight** [comment]
Полноценно было добавлено в релиз 1.3.2. Сбрасывать базу данных, теперь, тоже не нужно.
