### ISSUE TITLE
Поддержать ViolentMonkey

### ISSUE THREAD

**Issue by Ashark** [ilyhalight/voice-over-translation#207]
Здравствуйте.
Я использую ViolentMonkey вместо TemperMonkey. Но после установки скрипта, при открытии youtube вылезает сообщение что ViolentMonkey не поддерживается этой версией расширения.
При этом если установить TemperMonkey и установить скрипт туда, при этом временно отключить ViolentMonkey, то кнопка и перевод видео работают.
Можно добавить поддержку ViolentMonkey?

**Comment by ilyhalight** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/b2e42679-4435-42de-834a-a2ed2468a2cf)

**Comment by Ashark** [comment]
А, как-то не догадался что это сокращение означает. Возможно, стоит в readme прописать названия расширений полностью.
Спасибо.
