### ISSUE TITLE
Возможно ли подключить переводчик к плееру MacOs iina ? 

### ISSUE THREAD

**Issue by narimangafurov** [ilyhalight/voice-over-translation#211]
Плохо разбираюсь во всем. Но просто вопрос, возможно ли как то подключить переводчик к плееру MacOs iina либо к какому то другому? Для перевода уже скачанных на компьютер различных видео уроков и тд, может уже поднимался этот вопрос но не нашел

**Comment by ilyhalight** [comment]
Уже скачанных точно нет. Если по веб-ссылке, то может быть еще как-то возможно, но на 100% не уверен в этом.

**Comment by otakukz17** [comment]
залей свои офлайн файлы на ютуб с доступом только себе и смотри на ютубе с переводом как обычно.

**Comment by narimangafurov** [comment]
насчет загрузки на ютуб уже пробовал как раз так, вроде работает но не всегда удобно новые туторы загружать! спасибо за советы друзья!
