### ISSUE TITLE
нет кнопки "перевести видео" FF 115 для android

### ISSUE THREAD

**Issue by Belovmv** [ilyhalight/voice-over-translation#214]
Автору отдельное спасибо за эту разработку! Все супер! Но заметил такой баг, нет кнопки перевода в мобильной версии сайта youtube. Кнопка "перевести видео" появляется только когда на странице включаешь "Вид для ПК". Я использую firefox 115 beta, плагин Violentmonkey. С плагином Tampermonkey ситуация аналогичная.

**Comment by SashaXser** [comment]
Я понял, в чем дело. Скрипт не работает из-за экспериментальной функции, которая определяет язык видео по аудиодорожке. На мобильной версии YouTube такой функции нет, поэтому возникает ошибка, которая блокирует скрипт.

Вот примерное исправление:
````
function getLanguage(player, response, title, description, author) {
  if (!window.location.hostname.includes("m.youtube.com")) {
    // ! Experimental ! get lang from selected audio track if availabled
    const audioTracks = player.getAudioTrack();
    const trackInfo = audioTracks?.getLanguageInfo(); // get selected track info (id === "und" if tracks are not available)
    if (trackInfo?.id !== "und") {
      return trackInfo.id.split(".")[0];
    }

    // TODO: If the audio tracks will work fine, transfer the receipt of captions to the audioTracks variable
    // Check if there is an automatic caption track in the response
    const captionTracks =
      response?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (captionTracks?.length) {
      const autoCaption = captionTracks.find(
        (caption) => caption.kind === "asr"
      );
      if (autoCaption) {
        return autoCaption.languageCode;
      }
    }
  }

**Comment by Belovmv** [comment]
Здорово!  Ну надеюсь скоро внесут исправление )) потому, что я сам не пойму, куда в скрипте вставлять эти исправления.. 

Если подскажете, буду благодарен!

**Comment by AvenCores** [comment]
> Здорово!  Ну надеюсь скоро внесут исправление )) потому, что я сам не пойму, куда в скрипте вставлять эти исправления.. 
> 
> Если подскажете, буду благодарен! 

Заменить с 834 строки до 851 строки на данный код

**Comment by Belovmv** [comment]
О! Заработало! Спасибо всем причастным..

**Comment by Belovmv** [comment]
Ура!!
