### ISSUE TITLE
Зафиксировать громкость...

### ISSUE THREAD

**Issue by KAPTOHKA** [ilyhalight/voice-over-translation#215]
С помощью твикеров ЮТ (например [этот](https://github.com/code-charity/youtube)), можно выставить уровень громкости по умолчанию (например в 5%), а при просмотре с переводом, приходиться каждый раз настраивать (убавлять) уровень громкости оригинала и перевода примерно на 2% и 5% соответственно...

Хотелось бы, чтобы около ползунков громкости оригинала/перевода, были чекбоксы "Запомнить/Зафиксировать громкость", чтобы при просмотре с переводом, громкость каждый раз не настраивать...

Ну и/или чекбокс например "Уменьшить громкость оригинала на 30%" , за исходную громкость брать ту, что настроена в системе (твикере) и ставить её на перевод, а на оригинал минус 30% от исходной... 

Если чтото подобное уже реализовано, то извиняйте, не получилось это настроить...

**Comment by FiLinX** [comment]
> [KAPTOHKA](/KAPTOHKA)

я например тоже пользую некоторые твики к ютубу всякими расширениями и скриптами, включая и тот же уровень громкости при запуске, у меня он там [выставлен на 25% шкалы ютубного плеера]([url](https://i.ibb.co/rcy2t5R/screenshot-2023-07-09-00-18-48-001.png))
но и при переводе VOTом, мне тоже нехватает дефолтного уменьшения громкости оригинального звука до 15%
поэтому я (по подсказке автора [ilyhalight](https://github.com/ilyhalight)), сам в скрипте в строке  `const autoVolume = ` [проставляю уменьшение до 5%](https://i.ibb.co/hZjLXzc/screenshot-2023-07-09-00-30-07-002.png)  
а уровень громкости перевода при запуске - один раз выставил просто на ползунке в панельке, и она не сбивается

**Comment by KAPTOHKA** [comment]
>@FiLinX 

Ну я тоже через `const autoVolume` делал, но это както не правильно, может сделать возможность изменять эту цифру в настройках...

А то, что выставленный уровень громкости перевода запоминается, у меня давно-давно так и было, а потом перестало запоминать, видимо чтото в системе настроено, хотя я её не раз переустанавливал, да и на разных компах также... Покопаюсь еще, может починю...

**Comment by d2m22** [comment]
Есть проблема со звуком перевода, всегда перевод тише оригинала если установлено 15%, приходится уменьшать до 2-3%. Также не запоминает выставленную громкость вручную, приходится в скрипте править вручную до 3% выставляя значение "0.03".

`const autoVolume = 0.03; // 0.0 - 1.0 (0% - 100%) - default volume of the video with the translation`

**Comment by ilyhalight** [comment]
В beta10 добавлен слайдер для установки уровня автоматического уменьшения громкости. Изменять через autoVolume больше не нужно
