### ISSUE TITLE
не выходит кнопка для перевода

### ISSUE THREAD

**Issue by ReaToi** [ilyhalight/voice-over-translation#216]
не выходит кнопка для перевода, хотя я все установил

**Comment by HikkariWest** [comment]
Попробуй аккаунт сменить, возможно появится. Я не понимаю, почему на мейн аккаунте не работает кнопка, а на нерабочем аккаунте все работает. Странно это всё.

**Comment by HikkariWest** [comment]
@ilyhalight Как думаешь, если запускать перевод с помощью браузерной консоли, а не кнопки, то это сработает?

**Comment by ilyhalight** [comment]
> @ilyhalight Как думаешь, если запускать перевод с помощью браузерной консоли, а не кнопки, то это сработает?

По идее, должно работать, если запускать из консоли

**Comment by damaskuss** [comment]
недавно кнопка появилась и все работало, а сегодня кнопка пропала снова...

**Comment by vbelevcev** [comment]
> недавно кнопка появилась и все работало, а сегодня кнопка пропала снова...

You don't happen to have Chrome Canary, do you?

**Comment by vbelevcev** [comment]
у вас случайно не браузер Chrome Canary?

**Comment by damaskuss** [comment]
> у вас случайно не браузер Chrome Canary?

нет обычный хром

**Comment by vbelevcev** [comment]
откатился на 1.3.2 и заработало

**Comment by Katranius** [comment]
У меня тоже кнопка на ютубе вечно пропадает. Зато в яндекс плеере ютуб ролики если смотреть, то всегда есть кнопка!

**Comment by Artseom** [comment]
Обычный хром, 3 аккаунта google, один основной в котором перевод не работает но, если переключаюсь в два других то работает/// не пойму в чем проблема? мне бы на основном чтоб работал, былоб супер...

**Comment by Katranius** [comment]
> Обычный хром, 3 аккаунта google, один основной в котором перевод не работает но, если переключаюсь в два других то работает/// не пойму в чем проблема? мне бы на основном чтоб работал, былоб супер...

Попробуйте почистить куки

**Comment by VitaliyAT** [comment]
> Chrome Canary

у меня сработало... нол думал что не сработает... он похоже где-то запоминает конфигурацию плеера что-ли... можно интересно скриптом чистить?

**Comment by ilyhalight** [comment]
Проблема еще актуальна или могу закрывать?

**Comment by HikkariWest** [comment]
Уже нормально работает.
