### ISSUE TITLE
VOT-Cli

### ISSUE THREAD

**Issue by mner8** [ilyhalight/voice-over-translation#219]
Здравствуйте.
Перевод ролика в браузере осуществляется по субтитрам, а при использовании VOT-Cli по аудио.
Как скачать перевод как в браузере?
Ролик https://www.youtube.com/watch?v=ALJ5EPWAfsc

**Comment by ilyhalight** [comment]
Не понял сути вопроса

**Comment by mner8** [comment]
> Не понял сути вопроса

Если воспроизвести ролик в браузере и получить голосовой перевод с немецкого на русский, он будет осуществлен, основываясь на встроенных субтитрах (такой перевод лучше). Если использовать VOT-Cli и скачать перевод, перевод будет сделан на основе аудиодорожки ролика.
Можно ли скачать с помощью VOT-Cli перевод, который осуществляется для браузера?

**Comment by ilyhalight** [comment]
Пока что нельзя. Может быть потом как-нибудь обновлю vot-cli. Просто проблема в том, что в браузере у тебя автоматически ставиться правильный язык, а в vot-cli перевод всегда идет с английского, отсюда и все косяки

**Comment by ilyhalight** [comment]
В 1.1.1 был добавлен ручной выбор устанавливаемого языка.

Обсуждение vot-cli перенесено в другой [репозиторий](https://github.com/FOSWLY/vot-cli)
