### ISSUE TITLE
Мешает постоянно торчащая иконка

### ISSUE THREAD

**Issue by oxiderast** [ilyhalight/voice-over-translation#22]
https://github.com/ilyhalight/voice-over-translation/issues
Она не убирается сама еще и некорректно отображается
Исправьте пожалуйста🙏🏻

**Comment by oxiderast** [comment]
![image](https://user-images.githubusercontent.com/110498359/187053616-718c79a9-0f05-4aaf-9758-533967fb869d.png)

**Comment by ilyhalight** [comment]
> ![image](https://user-images.githubusercontent.com/110498359/187053616-718c79a9-0f05-4aaf-9758-533967fb869d.png)

Уже исправлено. Скоро залью фикс
