### ISSUE TITLE
неправильная работа (incorrect operation)

### ISSUE THREAD

**Issue by krator3** [ilyhalight/voice-over-translation#220]
Почему-то скрипт не правильно работает на Linux. Я выставляю озвучка видео = 0%, перевод = 100%. Но при этом он сам выставляет озвучку видео на 15%. Ошибка выявлена на firefox for arch linux. Это проявляется как минимум на нескольких последних версиях.

For some reason, the script does not work correctly on Linux. I set the video voiceover = 0%, translation = 100%. But at the same time, he puts the voice acting of the video at 15%. The error was detected on firefox for arch linux. This is evident on at least a few recent versions.

**Comment by ilyhalight** [comment]
> Но при этом он сам выставляет озвучку видео на 15%.

Эта галочка выключена?
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/7b2f6f2b-f564-4bd0-97e9-587d2c6c8e9a)

> Я выставляю озвучка видео = 0%,

Точно уже не помню, но вроде быгромкость озвучки видео не сохраняется при изменение слайдера

**Comment by miketype** [comment]
> 

Проблема в том, что значение изменяется после показа рекламы, например.

**Comment by ilyhalight** [comment]
Обновите скрипт. Должно работать нормально. Если что-то не так переоткройте.
