### ISSUE TITLE
Проблемы со звуком в vk.com после удаления

### ISSUE THREAD

**Issue by mhuruuk** [ilyhalight/voice-over-translation#222]
Хочу удалить скрипт, так как сильно мешает проблема со звуком во ВКонтакте (пропадает звук, необходимо сбрасывать настройки по умолчанию после чего страница перезагружается и он появляется).

Но после удаления, проблема со звуком остается, но исправить её уже не получается, так как отсутствует кнопка перезагрузки.

**Comment by SashaXser** [comment]
> 

Спасибо за ваше сообщение, но оно содержит слишком мало информации, чтобы я мог вам помочь. Пожалуйста, расскажите мне подробнее: когда и как она возникла, какие проблемы вы наблюдаете, какие шаги вы уже предприняли для ее решения. Так я смогу лучше понять ситуацию и дать вам ответ. Пожалуйста, не пишите здесь жалобы или эмоции, а только факты и детали проблемы.

**Comment by FiLinX** [comment]
> 3\. В столбце "Действия" в строке с названием "[VOT] - Закадровый перевод видео" - нажать на кнопку\значок "Удалить"

а после этого действа, удалял ли полностью этот скрипт из темпермонки? ведь он после 3-го пункта лишь стал помеченным на удаление, а полное удаление производится по значку корзины появляющемся после этого в панели вкладок темпермонки за пунктом "настройки"
и лучше после полного удаления, сделать перезапуск темпермонки через Настройки прокрутив там в самый низ
