### ISSUE TITLE
Звук продолжает воспроизводиться при возврате на предыдущую страницу

### ISSUE THREAD

**Issue by SOSKIN123** [ilyhalight/voice-over-translation#223]
При включенном переводе если вернуться назад продолжает воспроизводить звук из видео на YouTube

Как воспроизвести:
1. Открыть любое видео на английском
2. Включить перевод
3. Вернуться на предыдущую страницу
Итог:
Видео закрыто, но звук из него продолжает воспроизводиться

Браузер: FireFox Версия 115.0.2
ОС: MacOS Ventura 13.4.1

UPD: Срабатывает не всегда, кажется если перейти из поиска по видео, перемотать его пару раз и вернуться назад баг воспроизводится чаще

https://github.com/ilyhalight/voice-over-translation/assets/36372497/b0bae76e-59fa-4c67-9b3e-598da5fd481c

**Comment by FiLinX** [comment]
по видео, это больше похоже не на продолжение воспроизведения звука с ролика, а на его повторное перевоспроизведение..  ну, после того как был совершён переход с ролика назад, слышно опять тот же прыгающий звук, который был на ролике при перемотках.

**Comment by SashaXser** [comment]
> При включенном переводе если вернуться назад продолжает воспроизводить звук из видео на YouTube
> 
> Как воспроизвести:
> 
>     1. Открыть любое видео на английском
> 
>     2. Включить перевод
> 
>     3. Вернуться на предыдущую страницу
>        Итог:
>        Видео закрыто, но звук из него продолжает воспроизводиться
> 
> 
> Браузер: FireFox Версия 115.0.2 ОС: MacOS Ventura 13.4.1
> 
> UPD: Срабатывает не всегда, кажется если перейти из поиска по видео, перемотать его пару раз и вернуться назад баг воспроизводится чаще
> screen-recording-2023-07-14-at-183648_3SU1GjU0.mp4

В моем [билде](https://github.com/SashaXser/voice-over-translation/tree/master/dist) это исправлено (Желательно сбросить настройки)

**Comment by idMysteries** [comment]
Последняя версия. Проблема есть. Edge 123, Violentmonkey

**Comment by SashaXser** [comment]
> Последняя версия. Проблема есть. Edge 123, Violentmonkey

Откатись до 1.5.1.2
