### ISSUE TITLE
Переключение языка в дропдауне

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#224]
Когда на YouTube переключаешь язык перевода в дропдауне, после нажатия кнопки перевода, язык в дропдауне сбрасывается:

<img width="298" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/4968313/c3ee1983-c770-4b4c-92f2-000c37ad524b">
 
<img width="252" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/4968313/e3f7cce2-dee7-4a60-b637-662babfc95a1">

**Comment by FiLinX** [comment]
о.. а чё, яндекс умеет китайский?  
недавно вроде японский ролик пробовал - не балакало

**Comment by SashaXser** [comment]
> Когда на YouTube переключаешь язык перевода в дропдауне, после нажатия кнопки перевода, язык в дропдауне сбрасывается:
> <img alt="image" width="298" src="https://user-images.githubusercontent.com/4968313/254059734-c3ee1983-c770-4b4c-92f2-000c37ad524b.png"> <img alt="image" width="252" src="https://user-images.githubusercontent.com/4968313/254063184-e3f7cce2-dee7-4a60-b637-662babfc95a1.png">

Вот корень зла, пока нет идей что с ним делать
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/4ced4054-29f5-4f01-a79f-870254b4c1c3)
Если сделать так, то сбрасываться не будет, а даже сохраняться при смене видео. (до перезагрузки страницы)
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/8d8f8e08-175c-4b1c-93ad-cd1489ba6d8b)

**Comment by Dragoy** [comment]
> > Когда на YouTube переключаешь язык перевода в дропдауне, после нажатия кнопки перевода, язык в дропдауне сбрасывается:
> > <img alt="image" width="298" src="https://user-images.githubusercontent.com/4968313/254059734-c3ee1983-c770-4b4c-92f2-000c37ad524b.png"> <img alt="image" width="252" src="https://user-images.githubusercontent.com/4968313/254063184-e3f7cce2-dee7-4a60-b637-662babfc95a1.png">
> 
> Вот корень зла, пока нет идей что с ним делать ![изображение](https://user-images.githubusercontent.com/24498484/254101421-4ced4054-29f5-4f01-a79f-870254b4c1c3.png) Если сделать так, то сбрасываться не будет, а даже сохраняться при смене видео. (до перезагрузки страницы) ![изображение](https://user-images.githubusercontent.com/24498484/254101840-8d8f8e08-175c-4b1c-93ad-cd1489ba6d8b.png)

как временное решение сойдет, дождемся @ilyhalight с полноценным фиксом :>
