### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by thejohnd0e** [ilyhalight/voice-over-translation#226]
![o](https://github.com/ilyhalight/voice-over-translation/assets/115493464/cbe74f87-876c-473e-b906-faad720dc0de)

На 3х компьютерах одно и тоже.

<img width="1349" alt="Screenshot - 2023-07-21 16 18 32" src="https://github.com/ilyhalight/voice-over-translation/assets/115493464/25ea3489-8c4f-4f26-a819-855e6c7464da">

**Comment by ilyhalight** [comment]
Ответ дали выше

**Comment by thejohnd0e** [comment]
> Ответ дали выше

Спасибо. Моя невнимательность + англ. локаль.
