### ISSUE TITLE
Перевод текста на изображениях

### ISSUE THREAD

**Issue by MetalistPavlenko** [ilyhalight/voice-over-translation#23]
[Увидел вот такую новость](https://vc.ru/tech/228839-yandeks-brauzer-nauchilsya-perevodit-tekst-na-izobrazheniyah), хотелось бы чтобы в этом расширении (скрипте) появилась така возможность, или же сделать отдельное. Будет такая возможность ?

**Comment by ilyhalight** [comment]
> [Увидел вот такую новость](https://vc.ru/tech/228839-yandeks-brauzer-nauchilsya-perevodit-tekst-na-izobrazheniyah), хотелось бы чтобы в этом расширении (скрипте) появилась така возможность, или же сделать отдельное. Будет такая возможность ?

Чисто теоретически, это возможно, ибо сама апишка перевода картинок никак не защищена. Но, так же, идеально, как в Яндекс Браузере, вряд ли получится (в том смысле, что практически не видно замазанного первоначального текста). Если получится нормально реализовать сам рендер картинки, то скорее всего сделаю отдельный скрипт для этого.

Сравнение (не очень объективное, т.к. для теста использовалась только 1 картинка, где во всех случаях было довольно сильно видно замазанный задний фон):
1 - Функция из Яндекс Браузера
2 - Свой рендер
3 - Яндекс Переводчик
![1](https://user-images.githubusercontent.com/62353659/188278289-a7264fd6-51f5-4f3d-8517-654846514e8f.png)
![2](https://user-images.githubusercontent.com/62353659/188278303-ab374ae7-2a80-4d8e-a5f2-083edf631efb.png)
![3](https://user-images.githubusercontent.com/62353659/188278310-576ba611-64e1-4302-ab22-747563f79b16.png)

**Comment by MetalistPavlenko** [comment]
> > [Увидел вот такую новость](https://vc.ru/tech/228839-yandeks-brauzer-nauchilsya-perevodit-tekst-na-izobrazheniyah), хотелось бы чтобы в этом расширении (скрипте) появилась така возможность, или же сделать отдельное. Будет такая возможность ?
> 
> Чисто теоретически, это возможно, ибо сама апишка перевода картинок никак не защищена. Но, так же, идеально, как в Яндекс Браузере, вряд ли получится (в том смысле, что практически не видно замазанного первоначального текста). Если получится нормально реализовать сам рендер картинки, то скорее всего сделаю отдельный скрипт для этого.
> 
> Сравнение (не очень объективное, т.к. для теста использовалась только 1 картинка, где во всех случаях было довольно сильно видно замазанный задний фон): 1 - Функция из Яндекс Браузера 2 - Свой рендер 3 - Яндекс Переводчик 4 - Оригинал ![1](https://user-images.githubusercontent.com/62353659/188278289-a7264fd6-51f5-4f3d-8517-654846514e8f.png) ![2](https://user-images.githubusercontent.com/62353659/188278303-ab374ae7-2a80-4d8e-a5f2-083edf631efb.png) ![3](https://user-images.githubusercontent.com/62353659/188278310-576ba611-64e1-4302-ab22-747563f79b16.png) ![specific-typeface](https://user-images.githubusercontent.com/62353659/188278641-96959778-cc3c-4ec9-86b1-e6ad3cbdf8e6.jpg)

Мне и не нужно чтобы было идеально, главное чтобы переводило. Если сделаете, буду очень благодарен :)

**Comment by SeekerLightOri** [comment]
Есть новости по данной фиче?)

**Comment by ilyhalight** [comment]
> Есть новости по данной фиче?)

Забросил на этапе создания расширения + нету обхода истечения сессии для получения перевода английского текста. Конечно, можно было бы сделать через обычную апишку переводчика, но это уже будет не то... (сессия действует ~7 дн. и после приходится вручную её менять на сервере, что, так же, не очень удобно)
