### ISSUE TITLE
Можно ли добавить поддержку Wistia?

### ISSUE THREAD

**Issue by boxa007** [ilyhalight/voice-over-translation#230]
Добрый день! Подскажите пожалуйста, как можно добавить в плагин поддержку Wistia player?

спасибо

**Comment by ilyhalight** [comment]
Есть какое-нибудь видео с этим плеером, где можно было бы проверить? Кроме https://wistia.com/product/player

**Comment by boxa007** [comment]
вот залил: https://realestateala.com/wistia

**Comment by ilyhalight** [comment]
К сожалению, Яндекс не поддерживает wistia, а так же не имеет "скрытой" поддержки этого сайта. Так что тут остается только стучаться им в поддержку и просить, чтобы они добавили поддержку wistia в свой переводчик, а потом уже поддержка wistia появится и в расширение. Пока как альтернативу могут только посоветовать заливать на youtube/vimeo и уже с них переводить ¯\_(ツ)_/¯
