### ISSUE TITLE
Переводит с английского на английский

### ISSUE THREAD

**Issue by d2m22** [ilyhalight/voice-over-translation#232]
В настройках выставлен перевод с английского на русский, но в 20-30% начинает переводить с английского на английский (закадровый голос повторяет всё на английском). Обновление страницы спасает.

**Comment by SashaXser** [comment]
> В настройках выставлен перевод с английского на русский, но в 20-30% начинает переводить с английского на английский (закадровый голос повторяет всё на английском). Обновление страницы спасает.

Проверь это на [тестовом билде](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

**Comment by SashaXser** [comment]
> ![vot_en-to-en](https://user-images.githubusercontent.com/20663099/256243307-a170bad3-9fb9-4168-a82c-d98a6e58a906.gif)
> 
> Как оно вообще должно работать? Вся эта фишка про "родной" язык отличная придумка для тех, кто сидит не в русскоязычном браузере

Поставьте русский язык в браузере и не будет проблем

**Comment by daregod** [comment]
Больше интересует как "прибить" опцию перевода на русский. Она есть, но не работает.
Менять язык интерфейса в браузере, или добавлять русский язык, чтобы браузер всем об этом сообщал - это шаги понятные, но раньше работало нормально, а теперь сломано.

**Comment by SashaXser** [comment]
> Больше интересует как "прибить" опцию перевода на русский. Она есть, но не работает. Менять язык интерфейса в браузере, или добавлять русский язык, чтобы браузер всем об этом сообщал - это шаги понятные, но раньше работало нормально, а теперь сломано.

#224

**Comment by SashaXser** [comment]
> Больше интересует как "прибить" опцию перевода на русский. Она есть, но не работает. Менять язык интерфейса в браузере, или добавлять русский язык, чтобы браузер всем об этом сообщал - это шаги понятные, но раньше работало нормально, а теперь сломано.

Теперь если вы выбрать опцию “не переводить с моего языка”, вы можете изменить язык в любой момент. Однако, при переходе на другое видео, язык сбросится к языку браузера.
Скачай  [тестовый билд](https://github.com/SashaXser/voice-over-translation/tree/master/dist)
