### ISSUE TITLE
Ошибка "Не удалось запросить перевод видео"

### ISSUE THREAD

**Issue by Nikel2048** [ilyhalight/voice-over-translation#234]
chrome Версия 115.0.5790.110 (Официальная сборка), (64 бит)
![image](https://github.com/ilyhalight/voice-over-translation/assets/71230568/3c469615-2ae5-46d9-bbf1-752adbfe916c)
собственно вопрос, это у меня одного или это у всех?

**Comment by IvanAstran** [comment]
В YouTube такая же проблема.
![chrome_mL04p66YDd](https://github.com/ilyhalight/voice-over-translation/assets/96918464/23d85643-50c3-495e-9feb-dea1230785b1)

**Comment by Bioswamp** [comment]
Подтверждаю Youtube и последний Хром. 
Эта проблема у меня уже с месяц. Решил зайти опять проверить - все так же((
![2023-07-28 19_36_26-(401) 01 Going Over Our Bakes - YouTube](https://github.com/ilyhalight/voice-over-translation/assets/113590288/81a4277e-fbcd-44fc-a47d-2d85fc7f91ce)

**Comment by SashaXser** [comment]
> Подтверждаю Youtube и последний Хром. Эта проблема у меня уже с месяц. Решил зайти опять проверить - все так же(( ![2023-07-28 19_36_26-(401) 01 Going Over Our Bakes - YouTube](https://user-images.githubusercontent.com/113590288/256880295-81a4277e-fbcd-44fc-a47d-2d85fc7f91ce.jpg)

Включите проксирование видео (если у вас Cloudflare версия)
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/daddae8f-88ef-469d-89a9-0ab6c873a1c9)

**Comment by Bioswamp** [comment]
> > Подтверждаю Youtube и последний Хром. Эта проблема у меня уже с месяц. Решил зайти опять проверить - все так же(( ![2023-07-28 19_36_26-(401) 01 Going Over Our Bakes - YouTube](https://user-images.githubusercontent.com/113590288/256880295-81a4277e-fbcd-44fc-a47d-2d85fc7f91ce.jpg)
> 
> Включите проксирование аудио (если у вас Cloudflare версия) ![изображение](https://user-images.githubusercontent.com/24498484/257017815-daddae8f-88ef-469d-89a9-0ab6c873a1c9.png)

У меня нет такого в меню. Хотя переустановил и Tampermonkey и скрипт и ничего. Вот такое у меня в натсройках
![2023-07-30 13_00_17-(416) 01 Going Over Our Bakes - YouTube](https://github.com/ilyhalight/voice-over-translation/assets/113590288/f192f895-4ced-4eae-9be7-d423de0c1462)

**Comment by Bioswamp** [comment]
Так..вопрос снят - нужно было ИМЕННО CLOUDFLARE версию ставить, а я по привычке из мануала на главной ставил, а там ставится обычная версия

**Comment by ilyhalight** [comment]
> > Так..вопрос снято - нужно было ИММЕННО CLOUDFLARE версия ставить, а я по привычке из мануала на главную поставил, а там ставится обычная версия
> 
> Привет , можешь подсказать, где скачать эту версию CLOUDFLARE?

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/63d37948-4939-45ba-8fe6-03c3c621ee62)

**Comment by Harosatchi** [comment]
> Включите проксирование аудио (если у вас Cloudflare версия)

Не помогает(

**Comment by SashaXser** [comment]
> @SashaXser
> 
> > Включите проксирование аудио (если у вас Cloudflare версия)
> 
> Не помогает(

Есть ошибки в консоли? Не пиши пожалуйста что тебе не помогает, это никак не помогает решить твою проблему

**Comment by Harosatchi** [comment]
> @SashaXser Есть ошибки в консоли? Не пиши пожалуйста что тебе не помогает, это никак не помогает решить твою проблему

Понял. Оно?

<img width="1280" alt="Снимок экрана 2023-08-17 в 12 09 23" src="https://github.com/ilyhalight/voice-over-translation/assets/51264528/628ec948-e97e-470f-a9a3-538919090682">

**Comment by SashaXser** [comment]
> > @SashaXser Есть ошибки в консоли? Не пиши пожалуйста что тебе не помогает, это никак не помогает решить твою проблему
> 
> Понял. Оно?
> <img alt="Снимок экрана 2023-08-17 в 12 09 23" width="1280" src="https://user-images.githubusercontent.com/51264528/261259398-628ec948-e97e-470f-a9a3-538919090682.png">

Хм, ошибка в запросе. Скинь видео с которым проблемы.

**Comment by Harosatchi** [comment]
> @SashaXser  Скинь видео с которым проблемы

Абсолютно со всеми, какие бы ни попробовал

**Comment by SashaXser** [comment]
> > @SashaXser  Скинь видео с которым проблемы
> 
> Абсолютно со всеми, какие бы ни попробовал

Вижу, возможно Яндекс что-то сделал, либо он откис 

(error_id:1691227780814523-15282855444347736210) see logs for details

**Comment by MrSoczekXD** [comment]
> > > @SashaXser Скинь видео с которым проблемы
> >
> > Абсолютно со всеми, какие бы ни попробовал
>
> Вижу, возможно Яндекс что-то сделал, либо он откис
>
> (error_id:1691227780814523-15282855444347736210) see logs for details

Нет, ilyhalight использует cloudflare worker из моего pull request'а, а он по другому тело запроса отправляет.

**Comment by ilyhalight** [comment]
> > > > @SashaXser Скинь видео с которым проблемы
> > > 
> > > 
> > > Абсолютно со всеми, какие бы ни попробовал
> > 
> > 
> > Вижу, возможно Яндекс что-то сделал, либо он откис
> > (error_id:1691227780814523-15282855444347736210) see logs for details
> 
> Нет, ilyhalight использует cloudflare worker из моего pull request'а, а он по другому тело запроса отправляет.

Откатил. Перепутал воркеры и не на тот залил
