### ISSUE TITLE
Возможность разведения стереоканалов оригинала и перевода

### ISSUE THREAD

**Issue by Flagrantior** [ilyhalight/voice-over-translation#236]
Считаю, это интересное подспорье в изучении языков.

**Принцип режима:**
Cлайдер, по умолчанию значение на 50%, при движении вправо уменьшаются уровень правого канала оригинала и левого канала перевода, и наоборот.

Можно привести к моно, если нужно избежать ситуации, когда в оригинале голос только в одном канале, но это встречается крайне редко и, думаю, это можно игнорировать.

**Comment by ilyhalight** [comment]
Если такое и будет добавлено, то точно не в ближайшее время
