### ISSUE TITLE
Изменить размер и расположение

### ISSUE THREAD

**Issue by pvarenik** [ilyhalight/voice-over-translation#24]
Есть ли возможность добавить выбор размера и местоположения кнопки? Уж очень она мешает по центру и огромная.

**Comment by ilyhalight** [comment]
Возможность есть - клонировать репозиторий и самостоятельно изменить стили в файлике style.css, а так же изменить ссылки на репозиторий в самом скрипте vot.user.js

В сам скрипт, пока не планирую добавлять такую настройку
