### ISSUE TITLE
Озвучка есть в виде файла, но в файле отсутствует звук

### ISSUE THREAD

**Issue by Awasaky** [ilyhalight/voice-over-translation#242]
https://www.youtube.com/watch?v=txmzVsBniZQ
После нажатия перевода, начинается синхронное воспроизведение звука.
Но оказывается, что звуковая дорожка с сайта - пустая, нет никакой речи.
https://vtrans.s3-private.mds.yandex.net/tts/prod/8e3b7cf484554651ad93a574b2addd6c.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=TUjU1hKqZCA89kq9Wfr3%2F20230804%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230804T070100Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=927928a068ed83f2d5fd2ff17f0d391e11a62f630b450a654d30d35a65543723

**Comment by ilyhalight** [comment]
У меня всё работает

**Comment by Awasaky** [comment]
Вчера у меня не было звука, сейчас перешел - появился. Правда я за это время ничего не менял. Возможно проблемы на стороне яндекса...

**Comment by Awasaky** [comment]
Не воспроизводится
