### ISSUE TITLE
Баг с громкостью видео

### ISSUE THREAD

**Issue by miketype** [ilyhalight/voice-over-translation#249]
Значение громкости видео постоянно сбивается на 100 %.
Через какое-то время или после рекламы.
Tested on Chrome and Firefox.
UPD: в Opera  не сбивается.

Думаю,  что дело не в слайдере..
![Screenshot from 2023-08-11 08-34-10](https://github.com/ilyhalight/voice-over-translation/assets/49117156/3559fabd-d27f-429c-ac5c-0adfd72fd38d)

**Comment by SashaXser** [comment]
> 

На старой версии тоже самое? Если да, то тогда пока не могу точно сказать в чем проблема.

**Comment by miketype** [comment]
Установил 1.0.9.6, подтянул нормальный CSS. 
Да, на старых версиях то же самое.
Может быть, что-то в самом YouTube или Chromium изменилось...

Странно, что в Opera нормальное поведение.

**Comment by FiLinX** [comment]
Возможно для лучшей локализации причины такого поведения, скажу, что у меня когда громкость оригинала сбивалась, то увеличивалась она лишь до 25% шкалы, видимо потому, что именно на этот уровень у меня настроена дефолтная громкость открываемых роликов в расширении [Enhancer for YouTube™]([url](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle))

**Comment by SashaXser** [comment]
Так, я сделал свой минификс, теперь громкость на ютубе будет меняться в плеере Youtube, дабы точно быть уверенным что он не изменится.
[Попробуйте](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

**Comment by miketype** [comment]
> Так, я сделал свой минификс, теперь громкость на ютубе будет меняться в плеере Youtube, дабы точно быть уверенным что он не изменится. [Попробуйте](https://github.com/SashaXser/voice-over-translation/tree/master/dist)

Интересно, что проблема Chrome-specific была.

Потестил расширение. 
Desktop
Сhrome. С данным фиксом - нормально.
Opera. Работает из основного репозитория.
Firefox. Реклама сбивает на  основной версии. С фиксом - нормально.
Edge. Основная ветка - отлично.

Mobile
Kiwi Browser. Основной репозиторий. Отлично.
Firefox Nightly. Основной репозиторий. Отлично.

**Comment by andysu** [comment]
Desktop - Chrome for linux -  115.0.5790.170
фикс не помогает

**Comment by andysu** [comment]
> > Desktop - Chrome for linux - 115.0.5790.170 фикс не помогает
> 
> Вы в плеере выставили громкость? Попробуйте выключить звук в плеере.

Я наверное не обновил скрипт. Сейчас все заработало. Фикс помог. Спасибо.
На всякий случай выключил звук в плеере.

**Comment by miketype** [comment]
> > > Desktop - Chrome for linux - 115.0.5790.170 фикс не помогает
> > 
> > 
> > Вы в плеере выставили громкость? Попробуйте выключить звук в плеере.
> 
> Я наверное не обновил скрипт. Сейчас все заработало. Фикс помог. Спасибо. На всякий случай выключил звук в плеере.

В расширении тоже можно менять звук. Не сбивается.

**Comment by miketype** [comment]
Fixed: #249, #172, #215 (partly or full?), #220

**Comment by miketype** [comment]
Плюс ище с данным фиксом расширение заработало на мобильном Firefox. До этого только на Nightly Edition работало.

P.S. [Firefox поддержит desktop расширения на android](https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/)
