### ISSUE TITLE
Скачать перевод

### ISSUE THREAD

**Issue by vasyahacker** [ilyhalight/voice-over-translation#25]
Здравствуйте!
Подскажите пожалуйста
Можно ли сделать кнопку "скачать" перевод  в аудио файл?
Или хотя бы вывести в консоль ссылку на аудиопоток перевода?

**Comment by ilyhalight** [comment]
Добавил ссылку на перевод в консоль: [скачать ](https://drive.google.com/file/d/1IVeOE7wFsFKABr2IcKpoqkeMIGtQAI1R/view?usp=sharing)

Может быть, позже, сделаю опциональную кнопку для загрузки, чтобы не лезть постоянно в консоль
![изображение](https://user-images.githubusercontent.com/62353659/188520010-60a3ddd9-c343-4a1d-98d7-588d92122385.png)
