### ISSUE TITLE
Добавление поддержки bitchute.com

### ISSUE THREAD

**Issue by avatarDD** [ilyhalight/voice-over-translation#252]
Планируется ли добавление https://www.bitchute.com/ ?

**Comment by SashaXser** [comment]
> Планируется ли добавление https://www.bitchute.com/ ?

А Яндекс его поддерживает? Если нет, то нет.

**Comment by ilyhalight** [comment]
> > Планируется ли добавление https://www.bitchute.com/ ?
> 
> А Яндекс его поддерживает? Если нет, то нет.

На удивление работает, нигде не видел, чтобы о добавление его поддержки писали. 
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/c1a26720-4e4f-4dd7-8141-648620a027d7)
