### ISSUE TITLE
Добавить перевод для dev.epicgames.com/community/learning

### ISSUE THREAD

**Issue by reshetnyakag** [ilyhalight/voice-over-translation#255]
Было бы хорошо если получится добавить перевод для видеороликов с сайта https://dev.epicgames.com/community/learning.
Обучающие статьи от сообщества имеют прикреплённые видео с ютуба (тут всё отлично), но те статьи, которые выкладывают сами авторы движка Unreal Engine почти всегда хранятся на самом сайте EpicGames, например: [Electric Dreams Environment](https://dev.epicgames.com/community/learning/courses/x3L/unreal-engine-electric-dreams-environment-unpacked/RBWm/unreal-engine-building-your-own-environments)

**Comment by ilyhalight** [comment]
Яндекс не поддерживает. Просите добавить поддержку сначало их

**Comment by ilyhalight** [comment]
Добавлено
