### ISSUE TITLE
Возникла ошибка, попробуйте позже

### ISSUE THREAD

**Issue by Lexa070301** [ilyhalight/voice-over-translation#256]
На некоторых видео появляется ошибка "Возникла ошибка, попробуйте позже".

![Screenshot from 2023-08-14 01-33-53](https://github.com/ilyhalight/voice-over-translation/assets/56070799/996b6a49-5bc2-4043-9cbe-71ee709b5f48)

**Comment by SashaXser** [comment]
> На некоторых видео появляется ошибка "Возникла ошибка, попробуйте позже".
> 
> ![Screenshot from 2023-08-14 01-33-53](https://user-images.githubusercontent.com/56070799/260328120-996b6a49-5bc2-4043-9cbe-71ee709b5f48.png)

У тебя Cloudflare версия?

**Comment by Lexa070301** [comment]
Нет

**Comment by SashaXser** [comment]
> Нет

Поставь Cloudflare

**Comment by ilyhalight** [comment]
Новых ответов нету. Буду считать, что решено.
