### ISSUE TITLE
Не запоминает язык, на который переводить

### ISSUE THREAD

**Issue by ilyachch** [ilyhalight/voice-over-translation#258]
Язык системы и браузера - английский. 
Каждый раз, после перезагрузки страницы, язык, на который переводить - выбирается английский.

Было бы намного удобнее, если язык, на который переводить, запоминался бы.

**Comment by miketype** [comment]
Данный [фикс](https://github.com/ilyhalight/voice-over-translation/issues/224#issuecomment-1639080357) может частично решит вашу проблему..

**Comment by SashaXser** [comment]
> Язык системы и браузера - английский. Каждый раз, после перезагрузки страницы, язык, на который переводить - выбирается английский.
> 
> Было бы намного удобнее, если язык, на который переводить, запоминался бы.

Сделал у себя это пожелание, тебе нужно выставить язык и обновить страницу (возможно надо будет потом доделать)
Если интерфейс не появился, просто обновите страницу или смените видео (на крайняк сбросьте настройки)
[Попробуйте](https://github.com/SashaXser/voice-over-translation/tree/master/dist)
