### ISSUE TITLE
[📊] Проголосуйте в опросах о функционале расширения

### ISSUE THREAD

**Issue by ilyhalight** [ilyhalight/voice-over-translation#269]
https://github.com/ilyhalight/voice-over-translation/discussions/268
https://github.com/ilyhalight/voice-over-translation/discussions/265

**Comment by Vitte-Garry** [comment]
После обновления перестал работать перевод!

**Comment by ilyhalight** [comment]
> После обновления перестал работать перевод!

Сделайте отдельную тему с подробным описанием проблемы 
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/97c1887d-4f2c-4aae-ab9c-306172cab90d)
