### ISSUE TITLE
Ошибка "не удалось запросить перевод видео"

### ISSUE THREAD

**Issue by smotim** [ilyhalight/voice-over-translation#27]
![изображение](https://user-images.githubusercontent.com/57951811/188939547-330647c2-a75e-42d1-8a70-57ef0826a188.png)
Сегодня стала появляться такая ошибка. Не известно с чем связано?

**UPD: с 05.10.22 расширение снова работает во многих браузерах. Видимо дальше это Issue про фиксы для Chrome, Edge и Safari**

**Comment by nehalllem** [comment]
После обновления на 1.0.8 перестало работать вообще. До обновления все работало прекрасно. Накатил поверх обновелние - не работает. В фаерфоксе установило вообще начистую - не работает. ОТкатить на прошлые версии не понятно как. Скачать в зип файле релизы конечно можно, но как их подцепить в тамперманкей непонятно.

**Comment by smotim** [comment]
Сейчас увидел, что об ошибке писали уже в другом issue, извините

**Comment by nehalllem** [comment]
> Сейчас увидел, что об ошибке писали уже в другом issue, извините

В каком, подскажите пожалуйста, Там есть решение?

**Comment by smotim** [comment]
> > Сейчас увидел, что об ошибке писали уже в другом issue, извините
> 
> В каком, подскажите пожалуйста, Там есть решение?

https://github.com/ilyhalight/voice-over-translation/issues/1#issuecomment-1232704082

**Comment by smotim** [comment]
![изображение](https://user-images.githubusercontent.com/57951811/188941601-9703852c-dd3b-451e-947f-330a57d224bb.png)
и вот, что в терминале

**Comment by ilyhalight** [comment]
> После обновления на 1.0.8 перестало работать вообще. До обновления все работало прекрасно. Накатил поверх обновелние - не работает. В фаерфоксе установило вообще начистую - не работает. ОТкатить на прошлые версии не понятно как. Скачать в зип файле релизы конечно можно, но как их подцепить в тамперманкей непонятно.

Дело не в обновление расширения. Вероятнее всего, дело в том, что Яндекс сменили секретный ключ для генерации сигнатуры, из-за этого и выбивает 402 ошибку, как и при полном отсутствии сигнатуры. Пофиксить это не смогу, поскольку обход делал не я... Хотя конечно, я могу ошибаться и проблема может быть совершенно не в этом

**Comment by nehalllem** [comment]
> Дело не в обновление расширения. Вероятнее всего, дело в том, что Яндекс сменили секретный ключ для генерации сигнатуры, из-за этого и выбивает 402 ошибку, как и при полном отсутствии сигнатуры. Пофиксить это не смогу, поскольку обход делал не я... Хотя. конечно, я могу ошибаться и проблема может быть совершенно не в этом

получается что сейчас все новые установки этого расширения не будут работать? и лучше не обновлять старые?

**Comment by nehalllem** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/113052680/188981354-0480f09d-3de9-461f-93e8-0e9b89b213a8.png)

**Comment by ilyhalight** [comment]
> получается что сейчас все новые установки этого расширения не будут работать? и лучше не обновлять старые?

Старые версии расширения, так же, перестали работать. Как уже сказал выше, скорее всего, "секретный ключ для генерации сигнатуры от Яндекса" устарел, вследствие чего, запрос на перевод **не может** пройти проверку на серверах Яндекса. Отсюда и ошибка - "Не удалось запросить перевод видео".

**Comment by stasink** [comment]
И что теперь делать?

**Comment by ilyhalight** [comment]
> И что теперь делать? Расходимся по домам?

Получается так, придётся снова ждать, пока кто-нибудь пофиксит и решит заняться расширением. Есть конечно вариант использовать свой веб-сервер, но это практически бессмысленно (если, только, не ставить его на хостинг с виндой)

**Comment by DearFox** [comment]
> > И что теперь делать? Расходимся по домам?
> 
> Получается так, что придется снова ждать, пока кто-нибудь пофиксит и решит заняться расширением. Есть конечно вариант использовать свой веб-сервер, но это практически бессмысленно (если, только, не ставить его на хостинг с виндой)

Типа поднять свой сервер на котором будет крутится яндекс браузер и клиент передает данные о ролике в него, яндекс браузер получает данные и эти данные пересылаются клиенту? Или как?)

**Comment by stasink** [comment]
Недолго музыка играла, недолго фраер танцевал((((

**Comment by ilyhalight** [comment]
> Типа поднять свой сервер на котором будет крутится яндекс браузер и клиент передает данные о ролике в него, яндекс браузер получает данные и эти данные пересылаются клиенту? Или как?)

Да, всё правильно. До версии 1.0.6 так и работало

**Comment by nasOS-official** [comment]
А может эти ключи можно найти в яндекс браузере?

**Comment by MjKey** [comment]
> > И что теперь делать? Расходимся по домам?
> 
> Получается так, придётся снова ждать, пока кто-нибудь пофиксит и решит заняться расширением. Есть конечно вариант использовать свой веб-сервер, но это практически бессмысленно (если, только, не ставить его на хостинг с виндой)

Куда скидывать на лечение скрипта?)
_мб на хост или на мотивацию_

**Comment by VladWinner** [comment]
> в сети сейчас вообще проблемы с доступом к гуглосервисам наблюдаются
Дело не в этом, раз через их браузер работает
> но это лишь хайповые слухи.
Какие слухи, если это правда?

**Comment by AlexR0v** [comment]
в Safari работает как и прежде, дело явно не в яндексе.

**Comment by yingwai** [comment]
Opera тоже откисает

**Comment by CheIIau** [comment]
Да, в Chrome не работает, к сожаленю 🤷

**Comment by Vektor-537** [comment]
> в Safari працює як і раніше, справа явно не в яндексі.

Можливо справа якраз в ньому запит на його сервера повертає код 402, а з таблиці це Payment Required. тобто потрібна оплата. Схоже прикрили лавочку.

**Comment by vruzin** [comment]
куда смотреть где проблема? может я чем помогу...

**Comment by AvenCores** [comment]
Firefox 104.0.2 (Flatpak) идентичная проблема, жду фикс :)

**Comment by ilyhalight** [comment]
> куда смотреть где проблема? может я чем помогу...

Вероятнее всего, дело в смене/устаревание ключа "yandexHmacKey", либо же с более меньшей вероятностью в изменение алгоритма генерации/проверки Vtrans-sig на стороне сервера Яндекса

**Comment by FiLinX** [comment]
> Вероятнее всего, дело в смене/устаревание ключа

а сам HMAC впервые вытащил кто? случаем не mynovelhost? ну, спросить у первовытаскивателя - нет вариантов? )
кстати вот компоненты видео-транслята, которые подтягиваются при установке ябраузера - https://disk.yandex.ru/d/F9kisP90ZuXFuA

**Comment by ilyhalight** [comment]
> > Вероятнее всего, дело в смене/устаревание ключа
> 
> а сам HMAC впервые вытащил кто? случаем не mynovelhost? ну, спросить у первовытаскивателя - нет вариантов? ) 

Да, он самый. Попытаться спросить, конечно, можно было бы, но не его контактов, не какого-либо другого способа связи с ним нету. Да и на гитхаб, судя по активности, он давно не заходил

**Comment by onupirat** [comment]
Так может укажите в описании что уже не работает? А то я только установил, смотрю не работает, начинаю копать.

**Comment by ilyhalight** [comment]
> Так может укажите в описании что уже не работает? А то я только установил, смотрю не работает, начинаю копать.

Указал.

**Comment by FiLinX** [comment]
подождите  -  ведь тут есть вот люди с браузерами сафари в которых скрипт продолжает работать - но есть и коммент от mynovelhost именно про это - Рабочая генерация Vtrans-Signature из ios версии браузера https://github.com/ilyhalight/voice-over-translation/pull/4
в котором есть и скрипт - https://github.com/ilyhalight/voice-over-translation/pull/4/commits/289b98828d48e529c8d83568deb1db67430e9185
вот разве он именно не для получения ключа "yandexHmacKey" ? 
может стоит ребятам на сафари его как-то попробовать?
эх.. жаль я ниччё не понимаю в кодовстве(

**Comment by ilyhalight** [comment]
> вот разве он именно не для получения ключа "yandexHmacKey" ?

Немного не так, он каким-то образом смог получить значения yandexHmacKey с мобильного браузера и уже поверх этого написал функцию, которая превращает yandexHmacKey в Ключ-сигнатуру для допуска к запросам на сервера Яндекса.

> может стоит ребятам на сафари его как-то попробовать?

Странно конечно, если у них действительно работает скрипт. Но если работает, то нужно куда-то. в ту сторону. копать. Я сам бы поставил виртуалку и потестил, но к сожалению. уж очень сильно лагает Макинтош на виртуалке.

**Comment by WildTactic** [comment]
> > > Вероятнее всего, дело в смене/устаревание ключа
> > 
> > 
> > а сам HMAC впервые вытащил кто? случаем не mynovelhost? ну, спросите у первовытаскивателя - нет вариантов? )
> 
> Да, он самый. Попытаться спросить, конечно, можно было бы, но не его конфликтов, не какого-либо другого общения с ним нету. Да и на гитхаб, судя по активности, он давно не заходил

https://cloud.yandex.ru/docs/storage/concepts/pre-signed-urls#canonical-request ->var utf8Encoder

**Comment by mishan-ya** [comment]
Видимо опять слишком поздно пришёл... 
Как пол года назад DBC

**Comment by FiLinX** [comment]
> Видимо опять слишком поздно пришёл...

бывает)   но я всё ещё надеюсь, что кто-нить подможет)
а пока можете как раньше было - юзать перевод с сервером - https://github.com/ilyhalight/voice-over-translation/discussions/3#discussioncomment-3711308

**Comment by ilyhalight** [comment]
> > > > Вероятнее всего, дело в смене/устаревание ключа
> > > 
> > > 
> > > а сам HMAC впервые вытащил кто? случаем не mynovelhost? ну, спросите у первовытаскивателя - нет вариантов? )
> > 
> > Да, он самый. Попытаться спросить, конечно, можно было бы, но не его конфликтов, не какого-либо другого общения с ним нету. Да и на гитхаб, судя по активности, он давно не заходил
> 
> https://cloud.yandex.ru/docs/storage/concepts/pre-signed-urls#canonical-request ->var utf8Encoder

Изучил про эти запросы, но ведь не получится же их сделать без наличия секретной фразы аналогичной той, что используется на серверах Яндекса. А пытаться подобрать/сбрутить ее звучит не реально из-за используемого шифрования sha256.

**Comment by soviet55** [comment]
Ребята, всем привет. У меня скрипт переводчика работает в Safari на Mac OS. Устанавливал я его через расширение Tapermonkey. Поначидался, понаслышался, не хочу ничего трогать, но пока все отлично работает.

**Comment by FiLinX** [comment]
вот ведь а.. 
@soviet55  а когда устанавливал расширение, как давно?

**Comment by soviet55** [comment]
> вот ведь а..
> @soviet55 а когда устанавливал расширение, как давно?

Да, давно. Ну может недели через 2-3, как это дело сделали

**Comment by FiLinX** [comment]
> Да, давно.

Ага, почемуто так и думалось..  Значит всё же как то увязано с куками яндекса

**Comment by mynovelhost** [comment]
Так, только сейчас понадобилось расширение и заметил что не работает. Ключ hmac остался тем же, у себя уже пофиксил, сейчас гляну что изменилось тут, и закину пул реквест с фиксом

**Comment by mynovelhost** [comment]
Закинул пул с фиксом, протестировано на brave 106.0.5249.65.
Обновил юзерагент, добавил Sec-Vtrans-Token
Так же причина 402 - хидеры. !!! Sec-Fetch-Mode трогать нельзя, стандартное значение у GM запроса "cors" но я браузер отправляет запрос с "no-cors", иначе 402

**Comment by FiLinX** [comment]
Вау !!  @mynovelhost  рюмку коньяку за твоё здравие! )
осталось подождать готового файла, чтоб тупо ткнуть было куда и всё заработало) а то сами не сусами, хз чё с этим https://github.com/ilyhalight/voice-over-translation/pull/30/commits/c14bb31aea7608c486f3e9faec43658c47fee48b и с этим https://github.com/ilyhalight/voice-over-translation/pull/30/commits/2244e69c5b9673e15e13c228f67957fb26111fa2 делать..

**Comment by Prost0Lime** [comment]
Попробовал протестировать фикс, по итогу: на brave 106.0.5249.91 - Работает

**Comment by smotim** [comment]
Дополню @Prost0Lime 
**Linux**
1. Brave v1.44.105 (rpm) - работает
2. Firefox 105.0.1 (rpm) - работает
3. Edge 106.0.1370.34 (rpm) - выдает ошибку "Uncaught Не удалось запросить перевод видео"
4. Chrome 106.0.5249.91 (rpm) -  такая же ошибка

Большое спасибо @mynovelhost за фикс, я уж и не надеялся.

Issue можно закрывать, получается?

**Comment by stasink** [comment]
> Issue можно закрывать, получается? Надо заголовок в Readme немного поправить)

Получается что нет.  Chrome и Edge по-прежнему не работают.

**Comment by brightproject** [comment]
Простите, что issue превращаю в чат, но если будет решение - напишите пожалуйста в readme.

**Comment by mynovelhost** [comment]
Глянул и пофиксил хром (105.0.5195.52), все так же дело в хидерах. Хром отправляет дополнительно sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform хидеры. Их быть не должно. Если есть проблемы в других браузерах, скорее всего дело так же в хидерах, и для фикса, нужен лог запроса, со всеми отправлеными хидерами.

В течении 5 минут закину пул реквест с фиксом под хром, возможно пофиксит и другие браузеры

**Comment by ilyhalight** [comment]
> Глянул и пофиксил хром (105.0.5195.52), все так же дело в хидерах. Хром отправляет дополнительно sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform хидеры. Их быть не должно. Если есть проблемы в других браузерах, скорее всего дело так же в хидерах, и для фикса, нужен лог запроса, со всеми отправлеными хидерами.
> 
> В течении 5 минут закину пул реквест с фиксом под хром, возможно пофиксит и другие браузеры

Не знаю, чтобы мы, все, без вас делали =). 
К слову о других браузерах, вроде бы, во всех остальных проблема, так же, была исправлена. Точно работает в
- Opera GX (LVL4 (core: 91.0.4516.36))
- Opera (v91.0.4516.20)
- Cent Browser (v4.3.9.248)
- Cent Browser Beta (v5.0.1002.182) 
- MS Edge (v106.0.1370.34)
- Vivaldi (v5.5.2805.32)

**Comment by FiLinX** [comment]
Уря товарищи! )

**Comment by mynovelhost** [comment]
> Если есть проблемы в других браузерах, скорее всего дело так же в хидерах, и для фикса, нужен лог запроса, со всеми отправлеными хидерами.

Яндекс сейчас более строго проверяет запрос. Лишний/Недостающий хидер -> 402, Неправильное значение хидера -> 402. Так что как и писал:
`Если есть проблемы в других браузерах, скорее всего дело так же в хидерах, и для фикса, нужен лог запроса`
Снять его можно через тот же burp или fiddler (под ним выдаст 403 скорее всего, но это не важно). Без этого адаптировать под браузер невозможно

**Comment by Baltazar500** [comment]
@mynovelhost, можете дать корректный список хедеров (в идеале curl запросом, чтобы меньше заморачиваться) для проверки отработки VOT через AdGuard ? Чую, там та же проблема. Намедни погляжу через burp (собственно я это и так собирался сделать в связи с постами выше, но вы опередели предложив это раньше, чем я успел проверить) , что там с запросами.

**Comment by mynovelhost** [comment]
> @mynovelhost, можете дать корректный список хедеров (в идеале curl запросом, чтобы меньше заморачиваться) для проверки отработки VOT через AdGuard ? Чую, там та же проблема. Намедни погляжу через burp (собственно я это и так собирался сделать в связи с постами выше, но вы опередели предложив это раньше, чем я успел проверить) , что там с запросами.

`POST https://api.browser.yandex.com/video-translation/translate HTTP/1.1`
`Host: api.browser.yandex.com`
`Connection: keep-alive`
`Content-Length: 85`
`Pragma: no-cache`
`Cache-Control: no-cache`
`Accept: application/x-protobuf`
`Vtrans-Signature: <generated signature>`
`Sec-Vtrans-Token: <generated token>`
`Content-Type: application/x-protobuf`
`Sec-Fetch-Site: none`
`Sec-Fetch-Mode: no-cors`
`Sec-Fetch-Dest: empty`
`User-Agent: <yandex useragent>`
`Accept-Encoding: gzip, deflate, br`
`Accept-Language: en`
`Cookie: <cookies>`

Это в яндексе. Из известного 
  1) Brave добавляет `Sec-GPC: 1`, но этот хидер не влияет на 402
  2) sec-ch-ua* и Sec-Fetch-Mode: точно влияют

**Comment by Baltazar500** [comment]
В AdGuard другая петрушка https://github.com/ilyhalight/voice-over-translation/issues/13#issuecomment-1272261400

**Comment by mynovelhost** [comment]
> В AdGuard другая петрушка [#13 (comment)](https://github.com/ilyhalight/voice-over-translation/issues/13#issuecomment-1272261400)

Поставил adguard, там специфично сделан GM_xmlhttpRequest (Запрос отправляется на локальный сервер адгуарда), в итоге пофиксить просто так нельзя.

Для адргуарда (как и для всех браузеров, которые сейчас не работают), сработает прокси.
Пример (скрипт): https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js
Исходник (воркер): https://github.com/mynovelhost/voice-over-translation/blob/master/CloudflareWorker.js

Принцип работы такой: 
  1) Создается cloudflare worker который принимает json {headers: <хидеры>, body: <пост дата>}
  2) Используя полученные хидеры и пост дату делает запрос к яндексу
  3) Добавляет cors хидеры, и возвращает результат

Плюсы:
  1) Использутся обычный fetch -зависимость от GM_xmlhttpRequest
  2) Не важно какие хидеры отправил браузер (т.к воркер отправляет только те, что пришли в json)
Минусы:
  1) На бесплатном тарифе, доступно 100к запросов в день (в принципе, можно сделать штук 10 аккаунтов, и выбирать рандомно воркер, тогда 1кк запросов в день выдержит)
  
Пул реквест создавать не стал, т.к решение добавляет зависимость от воркера, а на большинстве браузеров и так работает

**Comment by Baltazar500** [comment]
>Поставил adguard, там специфично сделан GM_xmlhttpRequest (Запрос отправляется на локальный сервер адгуарда), в итоге пофиксить просто так нельзя.

Вы эту специфику в ветке https://github.com/AdguardTeam/CoreLibs/issues/1665 распишите, чтобы пофиксили, а то воз (всмысле тикет) и останется там где был :/

>Для адргуарда (как и для всех браузеров, которые сейчас не работают), сработает прокси.

Ну т.е. костыли будут только для продвинутых юзеров ? Я в этом деле шарю лишь поверхностно и боюсь не осилю ...

**Comment by mynovelhost** [comment]
> > Поставил adguard, там специфично сделан GM_xmlhttpRequest (Запрос отправляется на локальный сервер адгуарда), в итоге пофиксить просто так нельзя.
> 
> Вы эту специфику в ветке [AdguardTeam/CoreLibs#1665](https://github.com/AdguardTeam/CoreLibs/issues/1665) распишите, чтобы пофиксили, а то воз (всмысле тикет) и останется там где был :/
> 
> > Для адргуарда (как и для всех браузеров, которые сейчас не работают), сработает прокси.
> 
> Ну т.е. костыли будут только для продвинутых юзеров ? Я в этом деле шарю лишь поверхностно и боюсь не осилю ...

По поводу специфики, как я понял, это "не баг, а фича", скорее свего таким образом адгуард режет рекламу, пропуская через себя запросы

А по поводу костылей, сам воркер минут за 5 создается, т.к скрипт готовый в репо есть
Так же, то что я кидал выше - работает
> https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js
В этом скрипте прописан мой воркер (до 100000 запросов в день), если меньше 50-100 человек будут использовать, то должно хватить

**Comment by Firsto** [comment]
> Так же, то что я [кидал выше](adguard:userscript?location=https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js) - работает

Висит такая плашка и всё:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/2667895/195294268-9e481ed9-f971-4399-9809-5a43bfe73e07.png">

**Comment by ilyhalight** [comment]
> > Так же, то что я [кидал выше](adguard:userscript?location=https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js) - работает
> 
> Висит такая плашка и всё:
> <img width="372" alt="image" src="https://user-images.githubusercontent.com/2667895/195294268-9e481ed9-f971-4399-9809-5a43bfe73e07.png">
> 

Скинь видео которое пытаешься перевести. Как буду дома гляну.

**Comment by Baltazar500** [comment]
> гайд как за 100сек сделать воркер и добавить его в скрипт

Создание форка в видяшке - это уже лишнее 😂, но я в итоге сообразил, что к чему (с дашбордом cloudflare правда работал как попугай, даже не вникая в суть, зачем он).  Всё завелось.

>В этом скрипте прописан мой воркер (до 100000 запросов в день), если меньше 50-100 человек будут использовать, то должно хватить

Прописал свой. Дефолтный скоро просядет. 100К запросов мне одному 😂 с головой хватит многократным запасом 😂😂😂.

**Comment by Firsto** [comment]
> > > Так же, то что я кидал выше - работает
> > 
> > 
> > Висит такая плашка и всё:
> > <img alt="image" width="372" src="https://user-images.githubusercontent.com/2667895/195294268-9e481ed9-f971-4399-9809-5a43bfe73e07.png">
> 
> Скинь видео которое пытаешься перевести. Как буду дома гляну.

Всё заработало, просто оказывается надо было подождать минуть пять-десять для некоторых получасовых видео.)

**Comment by ZloyPirozhok** [comment]
> Висит такая плашка и всё: <img alt="image" width="372" src="https://user-images.githubusercontent.com/2667895/195294268-9e481ed9-f971-4399-9809-5a43bfe73e07.png">

В яндекс браузере многие видео переводятся моментально, через скрипт нужно каждый раз ждать, возможно ли сделать что-то подобное?

**Comment by riddle418** [comment]
Что то тикет уже превратился в форум не связанный с темой.

**Comment by ilyhalight** [comment]
> > Висит такая плашка и всё: <img alt="image" width="372" src="https://user-images.githubusercontent.com/2667895/195294268-9e481ed9-f971-4399-9809-5a43bfe73e07.png">
> 
> В яндекс браузере многие видео переводятся моментально, через скрипт нужно каждый раз ждать, возможно ли сделать что-то подобное?

Не всегда приходится ждать, но да, иногда такие видео появляются

**Comment by afrika06** [comment]
В хроме пока не работает, шансы есть?(((

**Comment by ilyhalight** [comment]
> 

Точно последнюю версию расширения используешь? Юзерскрипт-плагин тамперманки?

**Comment by afrika06** [comment]
На момент коммента не работало, сейчас вроде ок)

  
>Вторник, 18 октября 2022, 19:03 +03:00 от Toil ***@***.***>:
> 
> 
>Точно последнюю версию расширения используешь? Юзерскрипт-плагин тамперманки?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you commented. Message ID:  <ilyhalight/voice-over-translation/issues/27/1282635681 @ github . com> 
 
 
--
Артемий Пятёрочкин
Отправлено из Почты  Mail.ru

**Comment by Baltazar500** [comment]
@ilyhalight, а вы worker - костыли от @mynovelhost (без указания собственно адреса воркера) можете запилить в исходном проекте ? Ведь в AdGuard с этими костылями реально всё работает.

@mynovelhost, если @ilyhalight не возьмётся, можете свой форк https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js обновить до 1.0.9.2 ? У меня с JS всё очень поверхностно, а отличий от jhbubyfkmyjuj 1.0.8 многовато и я боюсь не осилю перенос кода.

**Comment by ilyhalight** [comment]
> @mynovelhost, если @ilyhalight не возьмётся, можете свой форк https://github.com/mynovelhost/voice-over-translation/blob/master/vot.user.js обновить до 1.0.9.2 ? У меня с JS всё очень поверхностно, а отличий от jhbubyfkmyjuj 1.0.8 многовато и я боюсь не осилю перенос кода.

Лучше, тогда, 1.0.9.3 подождать, там как раз переводы для остальных сайтов заработают. Примерно, на следующей неделе планирую выпустить.

> @ilyhalight, а вы worker - костыли от @mynovelhost (без указания собственно адреса воркера) можете запилить в исходном проекте ? Ведь в AdGuard с этими костылями реально всё работает.

Как доделаю 1.0.9.3, могу попытаться перенести.

**Comment by Baltazar500** [comment]
Вообщем не шмог :( Опыта в написании js мало.

@mynovelhost, @ilyhalight если будет время и желание адаптируйте под совместную работу с cloudflare worker'ом нынешнюю версию VOT.

**Comment by ilyhalight** [comment]
> Вообщем не шмог :( Опыта в написании js мало.
> 
> @mynovelhost, @ilyhalight если будет время и желание адаптируйте под совместную работу с cloudflare worker'ом нынешнюю версию VOT.

Пробуй - https://letsupload.cc/l0LcGeI5y3/vot-cloudflare.user_js

**Comment by Baltazar500** [comment]
> Пробуй - https://letsupload.cc/l0LcGeI5y3/vot-cloudflare.user_js

Спасибо, работает, правда на youtube -  embed линках я плашку с кнопкой не обнаружил, тоже нюансы работы под Adguard'ом ? Хм ...

>https://letsupload.cc/7020U4I5y1/vot-cloudflare.user_js

Спс за апдейт.

**Comment by Baltazar500** [comment]
>Чуть попозже гляну, не проверял там

На десктопе в хроме под TamperMonkey плашка на месте. Под AdGuard на андроиде с хромом в десктопном режиме плашки на embed - линках нет. На обычных ютуб - линках она есть. Но эти страницы с таким диким лагом в отличии от embed - линков грузятся, что ппц.

**Comment by Firsto** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/2667895/204660196-700dbddd-812e-4258-abff-94ff97c2b4d8.png">
вот так началось :(

**Comment by Baltazar500** [comment]
@Firsto, вы ветку на пару постов выше вашего почитайте. Там рабочий скрипт на базе cloudflare worker'a. Только используйте свой воркер по инструкции ещё чуть выше.

**Comment by ilyhalight** [comment]
> <img alt="image" width="537" src="https://user-images.githubusercontent.com/2667895/204660196-700dbddd-812e-4258-abff-94ff97c2b4d8.png">
> вот так началось :(

Так было сделано специально, чтобы разграничить обычную версию и версию с cloudflare worker`ом. А то, довольно часто задавали вопросы о том, что у них о не работает с Violetmonke / Adguard / Firemonkey, когда они используют обычную версию расширения. Так же, теперь, для 2 версии расширения, так же, выходят обновления совместно с основной версией

**Comment by ATWp** [comment]
Подскажите пожалуйста, что мне нужно сделать? Tampermonkey Обновлена до последней версии!
![image](https://github.com/ilyhalight/voice-over-translation/assets/69421094/7f1e24a8-98c1-43c0-bc7e-d4a125c77dc5)
Логи из консоли

**Comment by ATWp** [comment]
Нашел решение! Вы заходите сюда https://github.com/ilyhalight/voice-over-translation
Нажимаете -> Установить скрипт -> Обновить
Поздравляю, Вы успешны!

**Comment by Tolianbus** [comment]
> Нашел решение! Вы заходите сюда https://github.com/ilyhalight/voice-over-translation Нажимаете -> Установить скрипт -> Обновить Поздравляю, Вы успешны!

dont work

**Comment by binidom** [comment]
I'm the only one who has been having this problem for a few months now, the translator works, then it doesn't work and so every day for a few months now, who has this problem and how to solve it?

**Comment by Captain-HeMo** [comment]
Doesn't work. Doesn't translate. Doesn't respond to pressing! Reinstallation doesn't help.
