### ISSUE TITLE
Нельзя выбрать язык для перевода и язык перевода.

### ISSUE THREAD

**Issue by Dionis94** [ilyhalight/voice-over-translation#270]
В приложении нельзя выбрать язык перевода. Вылазит небольшая полоска и все

![Безымянный](https://github.com/ilyhalight/voice-over-translation/assets/92873544/f25461bd-92cc-4501-a4ee-064ac5cbbced)

Но можно выбрать субтитры

![Безымянный2](https://github.com/ilyhalight/voice-over-translation/assets/92873544/5701e7f6-5db4-4358-8497-ccb6663f18bd)

Браузер Фаерфокс на компьютере
Выключал все расширения не помогает
Создал новый профиль пользователя в Фаерфокс заработало. Но почему в моем родном не работает???
Может из за скрытых настроет в About:Config

**Comment by SashaXser** [comment]
> В приложении нельзя выбрать язык перевода. Вылазит небольшая полоска и все
> 
> ![Безымянный](https://user-images.githubusercontent.com/92873544/261516158-f25461bd-92cc-4501-a4ee-064ac5cbbced.png)
> 
> Но можно выбрать субтитры
> 
> ![Безымянный2](https://user-images.githubusercontent.com/92873544/261516293-5701e7f6-5db4-4358-8497-ccb6663f18bd.png)
> 
> Браузер Фаерфокс на компьютере Выключал все расширения не помогает Создал новый профиль пользователя в Фаерфокс заработало. Но почему в моем родном не работает??? Может из за скрытых настроет в About:Config

Сбрось найстройки

**Comment by Dionis94** [comment]
> Сбрось настройки

Делал так это тоже не помогает и заходил в F12 и удалял VOT и тоже не помогает!!!

**Comment by SashaXser** [comment]
> > Сбрось настройки
> 
> Делал так это тоже не помогает и заходил в F12 и удалял VOT и тоже не помогает!!!

В инкогнито тоже самое? Если да то проверь расширения в браузере

**Comment by Dionis94** [comment]
> В инкогнито тоже самое? Если да, то проверь расширения в браузере

Нашел примерную причину! Это пользовательское оформление фаерфокс через фаил userChrome.css в папке chrome в папке профиля пользователя. Просто ради любопытсва создал новый профиль и скопировал в него старый фаил userChrome.css и меню выбора языка также перестала появляться. Я даже безпонятий как они могут друг с другом конфликтовать пользовательские настройки и расширение для перевода.

**Comment by Dionis94** [comment]
Я даже безпонятий как они могут друг с другом конфликтовать пользовательские настройки и расширение для перевода.

И да раньше на этих же настройках пользователя все хорошо работало но теперь перестало.

**Comment by Dionis94** [comment]
> Я даже безпонятий как они могут друг с другом конфликтовать пользовательские настройки и расширение для перевода.
> 
> И да раньше на этих же настройках пользователя все хорошо работало но теперь перестало.


P.S> И еще меня в интернетах не было с 24 февраля 2023 года и вот появилась такая возможность и обновил приложение для перевода и появилась такая проблема.

**Comment by Dionis94** [comment]
Кто понимает в программировании и интересно мне помочь, я нашел примерно где есть ошибка потому что когда удаляешь этот кусок из файла userChrome.css то в приложении для перевода можно выбрать язык видео и языки перевода.


Вот код


/* Source file https://github.com/MrOtherGuy/firefox-csshacks/tree/master/chrome/dark_additional_windows.css made available under Mozilla Public License v. 2.0
See the above repository for updates as well as full license text. */

/* Dark library, page-info and bookmark-properties */
/* Color scheme matches default dark theme */

/* If you are going to open Library in the (places.xhtml) in a tab then this file should also be imported in userContent.css */

@namespace xul url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

@-moz-document url(chrome://browser/content/places/places.xhtml),
  url(chrome://browser/content/places/bookmarkProperties.xhtml),
  url(chrome://global/content/commonDialog.xhtml),
  url-prefix(chrome://browser/content/preferences/dialogs/),
  url("chrome://mozapps/content/handling/dialog.xhtml"),
  url-prefix(chrome://browser/content/pageinfo/),
  url-prefix(chrome://browser/content/sanitize.xhtml),
  url-prefix("chrome://mozapps/content/downloads"){
  :root{
    background-color: #2b2a33 !important;
    --in-content-box-background: #23222b !important;
  }
  #placesToolbox,
  #placesView,
  #placesToolbar,
  #main-window,
  #topBar,
  dialog,
  tree{
    -moz-appearance: none !important;
    color: rgb(249,249,250) !important;
  }
    
  #placesToolbar,
  tree{
    background: transparent !important;
  }
  
  #imagecontainerbox{ background: url("chrome://global/skin/media/imagedoc-darknoise.png") !important }
  
  search-textbox,
  #searchFilter,
  menulist,
  input,  
  textbox,
  richlistbox,
  treecol,
  treecolpicker,
  button,
  menu,
  #permList{
    -moz-appearance: none !important;
    color: inherit !important;
  }
  
  menulist{ border: 1px solid graytext; padding-inline-end: 4px }
  dropmarker{ filter: invert(1) }
  menulist:hover{ border-color: highlight; background-color: rgba(255,255,255,0.1) }
    
  .menubar-left{ fill: currentColor; -moz-context-properties: fill; }
  #topBar,#searchFilter,search-textbox,input,textbox,richlistbox{ background-color: rgba(0,0,0,0.2) !important; }
  input[mozactionhint="search"],input[readonly],td > input{ background-color: transparent !important; }
    
  treecol:not([hideheader]){ height: 24px; }
  treecol:hover{ filter: brightness(160%) }
  treechildren::-moz-tree-row(multicol, odd), #permList{ background-color: rgba(0,0,0,0.2) !important; }
  
  radiogroup > radio[selected],
  radiogroup > radio:hover,
  #permList > .permission:hover,
  treechildren::-moz-tree-row(hover),
  button:hover{ background-color: rgba(255,255,255,0.1) !important; color: inherit !important;}
  
  treechildren::-moz-tree-row(selected){ background-color: Highlight !important; }
  button{ padding: 3px }
  #placesMenu > menu{ border: none !important; }
    
  search-textbox,input,button{ border: 1px solid graytext; border-radius: 3px }
  search-textbox,input{ padding: 2px }

}

/* modal prompts (alert() & friends) */

xul|vbox.paymentDialogContainerFrame,
xul|vbox.tabmodalprompt-mainContainer{
  background-color: var(--toolbar-bgcolor) !important;
  color: var(--lwt-text-color,-moz-dialogtext) !important;
}



/* Add this to userChrome.css */

@namespace http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul;

/* zDark Context Menus */
.PanelUI-subView .toolbaritem-combined-buttons > .subviewbutton:not(.subviewbutton-iconic) {
background-color:#06c!important;
border:0 solid #ffe1e1!important;
border-radius:6px!important;
padding:0 10px!important
}

panelview {
color:#fff!important
}

#widget-overflow-mainView > .panel-subview-body > toolbarseparator,.PanelUI-subView menuseparator,.PanelUI-subView toolbarseparator,.cui-widget-panelview menuseparator,.cui-widget-panel toolbarseparator {
margin:0
}

:root {
--browser-background:#38383d
}

tabbrowser tabpanels {
background-color:var(--browser-background)!important
}

#context-navigation {
background-color:var(--uc-dark-bkgnd-color)!important
}

#sidebar-box {
background-color:hsl(240,7%,5%)!important
}

toolbarbutton[checked="true"]:not([disabled="true"]) {
color:inherit!important
}

#sidebar-header,.sidebar-splitter {
border-color:hsl(240,3%,20%)!important
}

.sidebar-placesTree {
color:#aaa!important
}

:root {
--uc-dark-bkgnd-color: rgb(49,54,59);
--uc-light-bkgnd-color:#f00;
--uc-active-color:#404040;
--uc-text-color:#c3c6c9;
--uc-border-color:#767676
}

#mainPopupSet menupopup menuitem,#mainPopupSet menupopup menu {
min-height:24px!important
}

.panel-arrowcontent,#placesContext,#alltabs-popup .arrowscrollbox-scrollbox,#contentAreaContextMenu,.textbox-contextmenu,#mainPopupSet menupopup,#bookmarks-menu-button menu menupopup {
border:1px solid var(--uc-border-color)!important;
background:var(--uc-dark-bkgnd-color)!important;
color:var(--uc-text-color)!important
}

#alltabs-popup menuitem,#bookmarks-menu-button menu menupopup .subviewbutton {
color:var(--uc-text-color)!important
}

#mainPopupSet menupopup,#mainPopupSet menupopup menuitem,#mainPopupSet menupopup menu,#alltabs-popup,#bookmarks-menu-button menu menupopup {
-moz-appearance:none!important;
border:none
}

.panel-subviews,#mainPopupSet menupopup,#bookmarks-menu-button menu menupopup > hbox,.search-panel-header.search-panel-current-engine,.search-panel-current-input,panelview,.PanelUI-subView {
background-color:var(--uc-dark-bkgnd-color)!important
}

#BMB_bookmarksPopup {
background-color:unset!important
}

.subviewbutton:hover,#PanelUI-contents toolbarbutton:hover,#mainPopupSet menupopup menuitem:hover,#mainPopupSet menupopup menu:hover,#PanelUI-footer toolbarbutton:not(#PanelUI-quit):hover {
background-color:#06a!important
}

#PanelUI-footer *,panelview toolbarbutton.subviewbutton .toolbarbutton-text,#downloadsFooter,#customizationui-widget-panel label,.autocomplete-richlistitem .ac-title,#widget-overflow-list toolbarbutton,#mainPopupSet menupopup menuitem,#mainPopupSet menupopup menu,#bookmarks-menu-button menu menupopup,#PopupSearchAutoComplete .autocomplete-tree.plain.search-panel-tree,#PanelUI-contents toolbarbutton,#sidebar-switcher-target,#alltabs_containersTab {
color:var(--uc-text-color)!important
}

#alltabs-popup,#alltabs_containersMenuTab {
border:none!important
}

#alltabs_containersMenuTab {
-moz-appearance:none!important;
background-color:transparent!important
}

#placesContext,#contentAreaContextMenu,#contentAreaContextMenu menupopup,#page-action-mainView,.textbox-contextmenu {
-moz-appearance:none!important;
background-color:var(--uc-dark-bkgnd-color)!important;
border:none
}

#placesContext menuitem,#contentAreaContextMenu menuitem,#contentAreaContextMenu menu,.textbox-contextmenu menuitem {
color:var(--uc-text-color)!important;
-moz-appearance:none
}

#placesContext menuitem,#contentAreaContextMenu #context-navigation:not([hidden])~menu,#contentAreaContextMenu #context-navigation:not([hidden])~menuitem {
min-height:24px!important;
height:24px
}

#placesContext menuitem[disabled="true"],#contentAreaContextMenu menuitem[disabled="true"],#mainPopupSet menupopup menuitem[disabled="true"],#BMB_bookmarksPopup menuitem[disabled],.textbox-contextmenu menuitem[disabled] {
color:#888!important
}

#placesContext menuitem:hover,#contentAreaContextMenu menuitem:hover,#contentAreaContextMenu menu:hover,#contentAreaContextMenu menu[open],.textbox-contextmenu menuitem:hover {
background-color:green;
border:none
}

.autocomplete-richlistbox {
background-color:var(--uc-dark-bkgnd-color)!important
}

#PopupAutoCompleteRichResult .ac-title,#PopupAutoCompleteRichResult .search-one-offs,.search-panel-input-value {
color:var(--uc-text-color)!important
}

#PopupSearchAutoComplete {
background-color:var(--uc-light-bkgnd-color)!important;
color:var(--uc-text-color)!important
}

.search-panel-one-offs,.downloadsPanelFooterButton:not(:hover),#overflowMenu-customize-button:not(:hover) {
background-color:red!important
}

menuseparator {
-moz-appearance:none;
padding:0;
border-top:0px solid #333;
border-bottom:0 solid #048
}

menulist > menupopup > menuseparator {
padding:6px 0 5px;
border-top:1px solid red;
border-bottom:none
}

menu,menuitem,menucaption {
-moz-appearance:menuitem;
-moz-box-align:center;
color:#fff!important
}

menuitem[default="true"] {
font-weight:400!important
}

menupopup:not([id="BMB_bookmarksPopup"]),
#BMB_bookmarksPopup menupopup[placespopup=true] > hbox
{
  -moz-appearance: none !important;
  border-radius: 0px !important;
  font-weight: normal !important;
  border: 0px dotted #09f !important;
  border-left: 0 !important;
  border-top: 0px solid #09f !important;
  box-shadow: 0 0px 0 rgba(0,0,0,0) inset,
        0 0 6px hsla(0,0%,0%,0) !important;
  background-color: rgb(49,54,59) !important;
  background-image: linear-gradient(to bottom,
                rgba(30,30,30,0.0),
                rgba(30,30,30,0.0)
                ) !important;
  padding-bottom: 0px !important;
  padding-top: 0px !important;
}

menu, menuitem, .splitmenu-menuitem
{
  -moz-appearance: none !important /* Allow Blue Background for File Menu Items*/; 
  color: rgb(165, 165, 165) !important /* File Menu Item Color */;
}

menu[_moz-menuactive="true"],
menuitem[_moz-menuactive="true"],
.splitmenu-menuitem[_moz-menuactive="true"]
{
  margin-bottom: 0px;
  border-radius: 0;
  background-color: #06a /* Blue Background for File Menu Items */!important;
  color: rgb(225, 225, 225) !important;
  font-size: 12px !important;
}

menu[disabled="true"],
menuitem[disabled="true"],
.splitmenu-menuitem[disabled="true"],
menu[_moz-menuactive="true"][disabled="true"],
menuitem[_moz-menuactive="true"][disabled="true"],
.splitmenu-menuitem[_moz-menuactive="true"][disabled="true"],
toolbarbutton[disabled="true"] 
{
  color: rgb(90, 90, 90) !important; display:none !important /* Hide Grayed Out - Disabled Menu Items */;
}

menupopup menuitem[_moz-menuactive="true"][disabled="true"]
{
  background-color: rgb(100, 100, 100) !important;
}

.chromeclass-menubar
{
  padding-bottom: 0px !important;
  border-bottom: 0px solid transparent !important;
}

menuitem[default="true"]
{
  font-weight: bold !important;
}

menuitem[label="(Empty)"],
menuitem[label="(Empty)"][_moz-menuactive="true"]
{
  -moz-appearance: none !important;
  color: rgb(191, 117, 43) !important;
  background-color: transparent !important;
  min-height: 20px !important;
  max-height: 20px !important;
border:1px solid red !imporant;
}

#clearcache-menuitem
{
  color: red !important;
}

**Comment by miketype** [comment]
Протестировал в Firefox. Все работает.

**Comment by Dionis94** [comment]
> Протестировал в Firefox. Все работает.

Я заново создал новый профиль фаерфокс, заново поставил VOT и тампермонки больше никаких приложений не ставил и скопировал этот код в фаил userChrome.css и запустил фаерфокс и......
Проблема осталась я даже не знаю что может быть.
Ну ладно можно и без этого кода жить.
