### ISSUE TITLE
После обновления 1.4.0.1 всё сломалось

### ISSUE THREAD

**Issue by Harosatchi** [ilyhalight/voice-over-translation#271]
Теперь не нажимается кнопка Перевести видео (где бы ни кликал), срабатывает пауза/плей видео.
Нажимаются только три точки, вот что отображается:

<img width="302" alt="Снимок экрана 2023-08-18 в 09 45 29" src="https://github.com/ilyhalight/voice-over-translation/assets/51264528/76ff17d5-ce44-4070-b6b2-41c6b4b4512b">

Пробовал и версию CF и обычную. Хром.
В консоли ничего не происходит.

**Comment by SashaXser** [comment]
> Теперь не нажимается кнопка Перевести видео (где бы ни кликал), срабатывает пауза/плей видео. Нажимаются только три точки, вот что отображается:
> <img alt="Снимок экрана 2023-08-18 в 09 45 29" width="302" src="https://user-images.githubusercontent.com/51264528/261523554-76ff17d5-ce44-4070-b6b2-41c6b4b4512b.png">
> 
> Пробовал и версию CF и обычную. Хром. В консоли ничего не происходит.

У тебя какая версия Хрома?

**Comment by Harosatchi** [comment]
> @SashaXser  У тебя какая версия Хрома?

Была Версия 115.0.5790.170 (Официальная сборка), (x86_64)
Сейчас обновилась на Версия 116.0.5845.96 (Официальная сборка), (x86_64)
Ничего не изменилось. Мак.

**Comment by SashaXser** [comment]
> > @SashaXser  У тебя какая версия Хрома?
> 
> Была Версия 115.0.5790.170 (Официальная сборка), (x86_64) Сейчас обновилась на Версия 116.0.5845.96 (Официальная сборка), (x86_64) Ничего не изменилось. Мак.

Пробывал нажимать на сброс настроек? Обычно помогает

**Comment by Harosatchi** [comment]
> @SashaXser  Пробывал нажимать на сброс настроек? Обычно помогает

Имеется же в виду "Сбросить настройки" в менюшке настроек скрипта? Сделал два раза, не помогло.

**Comment by SashaXser** [comment]
> > @SashaXser  Пробывал нажимать на сброс настроек? Обычно помогает
> 
> Имеется же в виду "Сбросить настройки" в менюшке настроек скрипта? Сделал два раза, не помогло.

Хм, а в инкогнито тоже самое?

**Comment by Harosatchi** [comment]
> Хм, а в инкогнито тоже самое?

Да

**Comment by SashaXser** [comment]
> > Хм, а в инкогнито тоже самое?
> 
> Да

Хм, тогда значит что-то мешает работает. Если уж в инкогнито не работает. У тебя есть еще скрипты в Tampermonkey? Или расширения для браузера которые могли бы потенциально мешать работе скрипта?

**Comment by Harosatchi** [comment]
> Хм, тогда значит что-то мешает работает. Если уж в инкогнито не работает. У тебя есть еще скрипты в Tampermonkey? Или расширения для браузера которые могли бы потенциально мешать работе скрипта?

Из скриптов или расширений ничего нового не ставил.
Из скриптов - есть еще только SaveFrom.net helper.
Попробовал все расширения отключить и без них проверить.
Нашел виновника - Enhancer for YouTube™ 2.0.119.2 (https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle).
Но до обновления всё было нормально, и сам он обновлялся еще 8.08.

**Comment by FF231** [comment]
Мне помогло и все заработало: Tampermonkey - Закадровый перевод видео - Отредактировать - Разработка - Полный сброс

**Comment by Harosatchi** [comment]
> Нашел виновника - Enhancer for YouTube™ 2.0.119.2 (https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle).
> Но до обновления всё было нормально, и сам он обновлялся еще 8.08.

@SashaXser Подскажите, можно будет наладить совместимость? Очень не хватает этого расширения.

**Comment by SashaXser** [comment]
> Enhancer for YouTube

Хм, попробуй скрипт вставить в настройках Enhancer for YouTube, мб меню появится
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/f0db2f40-b172-47e4-8361-67f593f752c5)

**Comment by SashaXser** [comment]
> > Нашел виновника - Enhancer for YouTube™ 2.0.119.2 (https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle).
> > Но до обновления всё было нормально, и сам он обновлялся еще 8.08.
> 
> @SashaXser Подскажите, можно будет наладить совместимость? Очень не хватает этого расширения.

Хм, попробуй скрипт вставить в настройках Enhancer for YouTube, мб меню появится
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/f0db2f40-b172-47e4-8361-67f593f752c5)

**Comment by FiLinX** [comment]
увы, но 1.4.0.1 и правда слегка поломана)
я вот щас сначало удалил полностью 1.3.6, перезагрузил темпермонку, затем установил 1.4.0.1 и вновь перезагрузил темпермонку
далее, открываю обычное [видео](https://www.youtube.com/watch?v=hrLyzpTV7GU)  -  и так [всё работает](https://i.ibb.co/N9LYwMS/screenshot-2023-08-18-19-40-26-016.png)!
но - открыв это же [видео в эмбед](https://www.youtube.com/embed/hrLyzpTV7GU)  -  увы уже вот как выше описано, кнопка перевести неактивна (плей-стоп отрабатывает), а по троеточию выводит [только это](https://i.ibb.co/7vxy2Gd/screenshot-2023-08-18-19-56-54-017.png)
вин10-64 LTSC  --  хром-утюг-86-32
Enhancer for YouTube™ стоит (но не крайней версии)  -  отключал его, не помогло, эмбеды так же не робит
делал и полный сброс скрипта в темпермонке (по сути лишнее это при установке начисто то) - но увы эмбеды не заработали((
пока что вернусь на 1.3.6)

**Comment by Harosatchi** [comment]
> Хм, попробуй скрипт вставить в настройках Enhancer for YouTube, мб меню появится.

Попробовал, вставил код, сохранил, в тамперманки отключил, но кнопка перевода на видео не появляется.



> Также можешь поменять порядок инжекта скрипта в Tampermonkey

Не помогает

**Comment by SashaXser** [comment]
Получается, недостаточно протестировали ту ветку с субтитрами, и из-за этого многое сломалось. Нужно будет всё исправлять.

**Comment by ilyhalight** [comment]
> но - открыв это же [видео в эмбед](https://www.youtube.com/embed/hrLyzpTV7GU) - увы уже вот как выше описано, кнопка перевести неактивна (плей-стоп отрабатывает), а по троеточию выводит [только это](https://i.ibb.co/7vxy2Gd/screenshot-2023-08-18-19-56-54-017.png)

Меню настроек в эмбедах починил.
С недоступной кнопкой, пока, не удается воспроизвести. Можете попробовать обновится, вдруг, пройдёт с одним из багфиксов

**Comment by ilyhalight** [comment]
> Нашел виновника - Enhancer for YouTube™ 2.0.119.2 (https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle).
Но до обновления всё было нормально, и сам он обновлялся еще 8.08.

Попробуйте обновить расширение до 1.4.0.2. Если это не поможет, то не могли бы вы поделиться настройками Enchancher For YouTube? Ибо на стандартных у меня всё работает.
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/f804edbc-7c65-4166-8601-f022ab724848)

**Comment by FiLinX** [comment]
> вдруг, пройдёт с одним из багфиксов

урряяя!! на 1.4.03 всё работает!  и [в эмбедилках](https://i.ibb.co/sQD5DBR/screenshot-2023-08-19-03-01-42-019.png) тоже)

**Comment by Harosatchi** [comment]
@ilyhalight 
> Попробуйте обновить расширение до 1.4.0.2. Если это не поможет, то не могли бы вы поделиться настройками Enchancher For YouTube? Ибо на стандартных у меня всё работает.

Обновил до 1.4.0.3 - проблема ушла.
Но заметил другую: в Enhancer for YouTube у меня выключено автовоспроизведение видео. Раньше после нажатия Перевести и появления Выключить при запуске видео перевод начинался сразу. Теперь - он сбрасывается и приходится его заново включать, делать лишний клик.
На всякий случай прикладываю настройки энхансера:
`{"version":"2.0.119.2","settings":{"blur":0,"brightness":100,"contrast":100,"grayscale":0,"huerotate":0,"invert":0,"saturate":100,"sepia":0,"applyvideofilters":false,"backgroundcolor":"#000000","backgroundopacity":85,"blackbars":false,"blockads":true,"blockadsexceptforsubs":false,"blockautoplay":true,"blockhfrformats":true,"blockwebmformats":false,"boostvolume":false,"cinemamode":false,"cinemamodewideplayer":true,"controlbar":{"active":false,"autohide":false,"centered":true,"position":"absolute"},"controls":["volume-booster","speed-minus","speed-plus"],"controlsvisible":true,"controlspeed":false,"controlspeedmousebutton":false,"controlvolume":false,"controlvolumemousebutton":false,"convertshorts":true,"customcolors":{"--dimmer-text":"#cccccc","--hover-background":"#232323","--main-background":"#111111","--main-color":"#00adee","--main-text":"#eff0f1","--second-background":"#181818","--shadow":"#000000"},"customcssrules":"","customscript":"","customtheme":false,"darktheme":false,"date":1629883927209,"defaultvolume":false,"disableautoplay":true,"executescript":false,"expanddescription":true,"filter":"none","hidecardsendscreens":false,"hidechat":false,"hidecomments":false,"hiderelated":false,"hideshorts":false,"ignoreplaylists":false,"ignorepopupplayer":true,"localecode":"ru","localedir":"ltr","message":false,"miniplayer":true,"miniplayerposition":"_top-right","miniplayersize":"_400x225","newestcomments":false,"overridespeeds":true,"pauseforegroundtab":true,"pausevideos":true,"popuplayersize":"640x360","qualityembeds":"medium","qualityembedsfullscreen":"hd1080","qualityplaylists":"hd1080","qualityplaylistsfullscreen":"hd1080","qualityvideos":"hd1080","qualityvideosfullscreen":"hd1080","reload":false,"reversemousewheeldirection":false,"selectquality":true,"selectqualityfullscreenoff":false,"selectqualityfullscreenon":false,"speed":1.5,"speedvariation":0.25,"stopvideos":true,"theatermode":false,"theme":"default-dark","themevariant":"youtube-deep-dark.css","update":1665566747111,"volume":15,"volumemultiplier":3,"volumevariation":5,"whitelist":"","wideplayer":false,"wideplayerviewport":false}}`

**Comment by FiLinX** [comment]
А это, не знаю заметил ли кто, я не встречал, но уже минимум с 1.3.6 мне такое попалось и оно продолжает так же быть, хз мож чё значимое..
Вобщем если при запущенном переводе нажать на троеточие и схватить любой из бегунков шкал видео иль перевода, то пока нажата ЛКМ  -  звук и само видео почему-то переходит в режим ускоренного воспроизведения. ))

**Comment by ilyhalight** [comment]
> А это, не знаю заметил ли кто, я не встречал, но уже минимум с 1.3.6 мне такое попалось и оно продолжает так же быть, хз мож чё значимое.. Вобщем если при запущенном переводе нажать на троеточие и схватить любой из бегунков шкал видео иль перевода, то пока нажата ЛКМ - звук и само видео почему-то переходит в режим ускоренного воспроизведения. ))

Это вроде в энчансере какая-то функция, что при зажатии лкм на видео и перетягивание влево/вправо скорость видео будет ускоряться/замедляться. Пару раз с таким сталкивался, а потом оно как-то само по себе пропало и больше не получается так сделать

**Comment by FiLinX** [comment]
ага, там есть регулировка скорости да, и я пользую её наведением на значёк и вращяя колесо мыши.
но там нет режима с ЛКМ, есть лишь с [Ctrl+ПКМ](https://i.ibb.co/tCYZL8S/screenshot-2023-08-19-17-07-00-023.png)
странность короче)

**Comment by miketype** [comment]
> > А это, не знаю заметил ли кто, я не встречал, но уже минимум с 1.3.6 мне такое попалось и оно продолжает так же быть, хз мож чё значимое.. Вобщем если при запущенном переводе нажать на троеточие и схватить любой из бегунков шкал видео иль перевода, то пока нажата ЛКМ - звук и само видео почему-то переходит в режим ускоренного воспроизведения. ))
> 
> Это вроде в энчансере какая-то функция, что при зажатии лкм на видео и перетягивание влево/вправо скорость видео будет ускоряться/замедляться. Пару раз с таким сталкивался, а потом оно как-то само по себе пропало и больше не получается так сделать

Это видимо функция Хрома. Можно и без расширения зажать левую клавишу мышки для быстрой перемотки.
