### ISSUE TITLE
Сброс звука

### ISSUE THREAD

**Issue by la1mon** [ilyhalight/voice-over-translation#276]
В оббщем, после обновления на версию 1.4.0.3 у меня начинает сбрасываться звук в ютубе, я не знаю как это точно обьяснить, попробую скрином.

Каждый раз когда я запускаю видео на ютубе, ползунок звука стоит на максимуме и бьет по ушам, каждый раз приходиться настраивать обратно под себя, после того как видео заканчивается, идет следующее видео и опять ползунок звука на максимуме.
Каждый раз пугаюсь.

До обновления, ползунок звука стоял всегда так как я его и оставлял, без измений.
![Screenshot_22](https://github.com/ilyhalight/voice-over-translation/assets/142688813/42fb023c-0223-4931-9958-6f2c19432211)

Я попробовал выключить скрипт яндекса и включать видео на ютубе, все как раньше, понял что это из за обновления на новую версию. Только вот как это пофиксить я не знаю.

**Comment by ilyhalight** [comment]
Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)

**Comment by SeregaMihalkin** [comment]
> Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)

я походу глупый, но у меня такая же проблема, как мне поставить последнюю 1.4.1-beta6 Pre-release 🗿 Спасибо

**Comment by ilyhalight** [comment]
> > Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)
> 
> я походу глупый, но у меня такая же проблема, как мне поставить последнюю 1.4.1-beta6 Pre-release 🗿 Спасибо

Нужно зайти в releases, там найти 1.4.1-beta6. Открыть Assets и выбрать нужную версию
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/90875f34-8445-4599-8a1d-57fb2c977b47)

**Comment by SeregaMihalkin** [comment]
> > > Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)
> > 
> > 
> > я походу глупый, но у меня такая же проблема, как мне поставить последнюю 1.4.1-beta6 Pre-release 🗿 Спасибо
> 
> Нужно зайти в releases, там найти 1.4.1-beta6. Открыть Assets и выбрать нужную версию ![image](https://user-images.githubusercontent.com/62353659/266795708-90875f34-8445-4599-8a1d-57fb2c977b47.png)

и какую выбрать в итоге? или оба?*

**Comment by ilyhalight** [comment]
> > > > Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)
> > > 
> > > 
> > > я походу глупый, но у меня такая же проблема, как мне поставить последнюю 1.4.1-beta6 Pre-release 🗿 Спасибо
> > 
> > 
> > Нужно зайти в releases, там найти 1.4.1-beta6. Открыть Assets и выбрать нужную версию ![image](https://user-images.githubusercontent.com/62353659/266795708-90875f34-8445-4599-8a1d-57fb2c977b47.png)
> 
> и какую выбрать в итоге? или оба?*

зависит от той, которая у тебя сейчас стоит, если в название есть "VOT Cloudflare", то vot-cloudflare.user.js, если просто "VOT" то vot.user.js
