### ISSUE TITLE
Кнопка перевода не работает в 1.4.0.3

### ISSUE THREAD

**Issue by Patraskon** [ilyhalight/voice-over-translation#277]
Firefox 116.0.3

https://github.com/ilyhalight/voice-over-translation/assets/34421135/93dd577a-4f8a-4752-b76e-2022863b0e68

**Comment by ilyhalight** [comment]
Сбрось настройки расширения. В консоли есть какие-нибудь ошибки?

**Comment by Patraskon** [comment]
Сброс не помогает.

`Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/GenerateIT base.js:7883:77
Загрузка <script> по адресу «https://static.doubleclick.net/instream/ad_status.js» не удалась. watch:1:1
Ошибка при парсинге значения «transform».  Потерянное объявление. watch
Array(10) [ "ru", "en", "zh", "ko", "ar", "fr", "it", "es", "de", "ja" ]
[VOT]-Voice-Over-Translation.user.js:5605:11
Array(10) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
[VOT]-Voice-Over-Translation.user.js:5611:11
Array(10) [ "ru", "en", "zh", "ko", "ar", "fr", "it", "es", "de", "ja" ]
[VOT]-Voice-Over-Translation.user.js:5605:11
Array(10) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…} ]
[VOT]-Voice-Over-Translation.user.js:5611:11
Array(17) [ "bn", "pt", "cs", "hi", "mr", "te", "tr", "ms", "vi", "ta", … ]
[VOT]-Voice-Over-Translation.user.js:5605:11
Array(17) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
[VOT]-Voice-Over-Translation.user.js:5611:11
Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://yt3.ggpht.com/ytc/AOPolaTr99mJmMfd6Ks1aio0sluuDyri2OkF56k9V79ZSg=s48-c-k-c0x00ffffff-no-rj desktop_polymer_enable_wil_icons.js:11667:135
Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://yt3.ggpht.com/eXWcXfFYak0V6Lqb1PupiZn6regtusGHnfQIC3_n3GB5Vdov90gjF6hC1fjOJXhmpBh-fHltAQ=s100-w72-h100-c-k-c0x00ffffff-no-nd-rj desktop_polymer_enable_wil_icons.js:11667:135
Referrer policy: Менее строгая политика origin-when-cross-origin игнорирована для междоменного запроса: https://yt3.ggpht.com/QqoTjrpKRDMfGFPYpgIaTmHkbQ6Lk-brN77OxCYwl0jTtluavivXDdd4lR2wQsr_hcIggw=s136-w136-h136-c-k-c0x00ffffff-no-nd-rj desktop_polymer_enable_wil_icons.js:11667:135
Ошибка при парсинге значения «display».  Потерянное объявление. watch
XHRPOST
https://jnn-pa.googleapis.com/$rpc/google.internal.waa.v1.Waa/GenerateIT
[HTTP/2 200 OK 44ms]
`

**Comment by SashaXser** [comment]
> Firefox 116.0.3
> _2023_08_20_02_08_29_495.mp4

Попробуй создать новый профиль, и проверь работу скрипта. Возможно у тебя есть какой либо скрипт или расширение которое мешает работе.

**Comment by Patraskon** [comment]
Вот с этим расширением почему-то конфликтует из-за этого не работает https://addons.mozilla.org/ru/firefox/addon/youtube-timestamps/

**Comment by ilyhalight** [comment]
> Вот с этим расширением почему-то конфликтует из-за этого не работает https://webextension.org/listing/youtube-tools.html?from=buffer

Странно, у меня работает

**Comment by otero-true** [comment]
Такая же проблема была в версии 1.34.X, я не помню точно. После того как я обновился до 1.4.0.3, проблема осталась.

**Comment by DanzoGit** [comment]
Я перепробовал почти всё, отключил все расширения кроме tampermonkey, сбрасывал настройки скрипта, удалял, ставил заново. Ничего не помогло. Удалил tampermonkey, установил заново вместе с скриптом - заработало.

**Comment by otero-true** [comment]
VPN мне исправил проблему.

**Comment by ipwin-github** [comment]
Возможно что работе скрипта мешает другой скрипт или расширение. У меня тоже кнопка перевода перестала работать еще с версии 1.4.0. Все точно так же как в приведенном видео, нажатие кнопки "Перевести видео" не запускает перевод а только воспроизведение/пауза самого видео. Причиной этого у меня оказался скрипт **YouTube Autoplay Disable** https://greasyfork.org/ru/scripts/448590-youtube-autoplay-disable 
После отключения в настройках этого скрипта функции блокировки автозапуска видео на YouTube (сам скрипт даже отключать не нужно) кнопка перевода начинает работать без вопросов. Интересно что на всех версиях VOT до 1.4.0 оба этих скрипта без проблем уживались друг с другом но после версии 1.4.0 что-то пошло не так и теперь приходится выбирать что-то одно.

**Comment by DanzoGit** [comment]
У меня стоит это расширение - https://chrome.google.com/webstore/detail/disable-autoplay-for-yout/dinkeiniijmpjehejhedbciaedblhnnk
С ним такая же проблема.

**Comment by ilyhalight** [comment]
В релизе 1.4.1 всё так же не появляется кнопка, если включено это расширение?

**Comment by DanzoGit** [comment]
@ilyhalight кнопка появляется, но не реагирует на нажатия. Если попытаться включить видео во время прогрузки страницы, то кнопка работает.

**Comment by ilyhalight** [comment]
> кнопка появляется, но не реагирует на нажатия. Если попытаться включить видео во время прогрузки страницы, то кнопка работает.

Не реагирует, же, только, с дополнительным расширением? Если да, то, тогда, постараюсь попозже разобраться с этим багом, если эта проблема не была исправлена с новым меню в #294

**Comment by DanzoGit** [comment]
@ilyhalight Верно, без расширения, которое отключает автоматическое воспроизведение ютуб роликов, VOT отрабатывает нормально.

**Comment by ipwin-github** [comment]
А у меня в релизе 1.4.1 VOT стал работать с расширением **Disable Autoplay for YouTube™** https://chrome.google.com/webstore/detail/disable-autoplay-for-yout/dinkeiniijmpjehejhedbciaedblhnnk
А вот со скриптом **YouTube Autoplay Disable** https://greasyfork.org/ru/scripts/448590-youtube-autoplay-disable по прежнему не работает. Кнопка перевода с включенным этим скриптом при нажатии только останавливает/воспроизводит видео. Точно так как на видео **Patraskon**

**Comment by Ar1soN** [comment]
Она работает, если после перехода с главной страницы ютуба на видео обновлять полностью страницу. Ctrl + F5

**Comment by ilyhalight** [comment]
> А вот со скриптом **YouTube Autoplay Disable** https://greasyfork.org/ru/scripts/448590-youtube-autoplay-disable по прежнему не работает

Возможно, это было исправлено уже с первыми бетами 1.5.0. Но в 1.5.0 бета 8 у меня не воспроизводится

**Comment by DanzoGit** [comment]
> Возможно, это было исправлено уже с первыми бетами 1.5.0. Но в 1.5.0 бета 8 у меня не воспроизводится

На первый взгляд всё хорошо работает в Chrome.

**Comment by ilmini09** [comment]
Кнопка перевода не работает в https://rt.pornhub.com/

**Comment by ilyhalight** [comment]
> Кнопка перевода не работает в https://rt.pornhub.com/

до последней беты обновитесь

**Comment by ipwin-github** [comment]
> Возможно, это было исправлено уже с первыми бетами 1.5.0. Но в 1.5.0 бета 8 у меня не воспроизводится

Совершено верно, исправлено еще на первой бете 1.5.0. Забыл об этом здесь написать. VOT теперь снова работает с скриптом YouTube Autoplay Disable. И на 1.5.0 бета 8 у меня тоже все работает без проблем.

**Comment by ilyhalight** [comment]
добавлено в стабильную ветку
