### ISSUE TITLE
Мгновенный режим встраивания и 1.4.1-beta

### ISSUE THREAD

**Issue by DanzoGit** [ilyhalight/voice-over-translation#282]
Chrome

Не запускается скрипт, если включить эту настройку в Tampermonkey.

<details>
<summary>screen</summary>

![1](https://github.com/ilyhalight/voice-over-translation/assets/61109303/856ab6cd-ab46-4883-9a47-01df9e9f9f69)
</details>

Необходимо для работы Adguard Extra.

Лог в консоли браузера:
<details>
<summary>screen</summary>

![2](https://github.com/ilyhalight/voice-over-translation/assets/61109303/3d0fada5-e0d5-438b-b038-c35581d1397b)
</details>

Если включить режим встраивания "По умолчанию" и "Перезапустить Tampermonkey", то скрипт отрабатывает нормально.

**Comment by ilyhalight** [comment]
Попробуйте убрать в мете скрипта // @run-at document-start

**Comment by DanzoGit** [comment]
@ilyhalight Не помогло. Ошибки этой в консоли нет, но и интерфейс расширения не появляется.

**Comment by ilyhalight** [comment]
Попробуйте обновиться до 1.4.1-beta7. В ней всё должно нормально работать

**Comment by DanzoGit** [comment]
@ilyhalight Да, на первый взгляд всё отлично. Спасибо 👍💖
