### ISSUE TITLE
Сброс звука видео

### ISSUE THREAD

**Issue by ARTCamelion** [ilyhalight/voice-over-translation#284]
в  Google Chrome с включенным расширением VOT каждое новое открываемое видео воспроизводится со 100% громкостью/
версия 1.4.1-beta

**Comment by ilyhalight** [comment]
Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)

**Comment by ARTCamelion** [comment]
> Исправил. Попробуйте обновиться до [1.4.1-beta2](https://github.com/ilyhalight/voice-over-translation/releases)

Проблема решена. Спасибо!
