### ISSUE TITLE
Пропала кнопка перевода

### ISSUE THREAD

**Issue by Spp595** [ilyhalight/voice-over-translation#285]
firefox, linux, violentmonkey
У меня также имеется chromium браузер и скрипт там тоже запущен через violentmonkey, но там все отлично работает

**Comment by ilyhalight** [comment]
В консоли что-то пишет?

**Comment by Spp595** [comment]
вроде ничего нету

**Comment by ilyhalight** [comment]
Попробуйте убрать в мете скрипта // @run-at document-start

**Comment by Spp595** [comment]
Не помогло

**Comment by Alatau** [comment]
Да, после обновления Chromium до версии 116.0.5845.96 пропала кнопка перевода.

**Comment by Spp595** [comment]
> Да, после обновления Chromium до версии 116.0.5845.96 пропала кнопка перевода.

У меня вроде самая новая версия все нормально работает

**Comment by Spp595** [comment]
Нашел проблему!
У меня почему-то была установлена бета-версия, скачал самую новую версию со странице релиза
Похоже ссылка в инструкции ведет на неправильную версию.

**Comment by Alatau** [comment]
> Нашел проблему! У меня почему-то была установлена бета-версия, скачал самую новую версию со странице релиза Похоже ссылка в инструкции ведет на неправильную версию.

Спасибо! У меня так же проблема решилась вашим путем.

**Comment by ilyhalight** [comment]
> Также заметил что теперь для violentmonkey потребовалось cloudflare версия

Так еще с самого появления cloudflare версии, просто, раньше в описание писались аббревиатуры VM, GM и т.п. 👍 

> У меня почему-то была установлена бета-версия, скачал самую новую версию со странице релиза

Ветка для beta версий появилась позже чем я выложил 1.4.1-beta, поэтому ссылка, сейчас, ведет на бета версию. Как 1.4.1 выйдет, то всё прийдёт в норму.

**Comment by linkinpunk** [comment]
Подтверждаю релизная версия 1.4.0.3 работает. Бета 1.4.1-beta5 в Tampermonkey 4.19.0 на WaterFox G5.1.12 (64 бита) (Windows) нет.

**Comment by ilyhalight** [comment]
> Подтверждаю релизная версия 1.4.0.3 работает. Бета 1.4.1-beta5 в Tampermonkey 4.19.0 на WaterFox G5.1.12 (64 бита) (Windows) нет.

Собственно, как я и предполагал, это из-за добавления `// @run-at document-start`. К релизу, нужно будет исправить

**Comment by ilyhalight** [comment]
В 1.4.1-beta7 должно работать нормально
