### ISSUE TITLE
не удалось перевести видео в твиттере

### ISSUE THREAD

**Issue by Fearless-zww** [ilyhalight/voice-over-translation#289]
![图片](https://github.com/ilyhalight/voice-over-translation/assets/103132906/de8e1247-6912-4088-b252-91cb5735c50b)

Также есть проблема, когда youtube переводит с английского на китайский, китайский - это не мандарин.

Спасибо за ваши усилия, большое спасибо

**Comment by SashaXser** [comment]
>  это не мандарин.
> 


Яндекс не поддерживает мандарин, пока только Китайский (скорее всего упрощенный)
