### ISSUE TITLE
Пропала кнопка скачать аудиофайл

### ISSUE THREAD

**Issue by AlexanderDankin** [ilyhalight/voice-over-translation#290]
Запланировано ли намерено исключить данную возможность? Версия 1.4.1-beta

**Comment by ilyhalight** [comment]
Есть кнопка, никто не собирается ее убирать. Скиньте как у вас выглядит меню
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/4bd2a143-54cc-4832-b700-4577527968bd)

**Comment by AlexanderDankin** [comment]
![Снимок экрана 2023-08-23 в 17 36 31](https://github.com/ilyhalight/voice-over-translation/assets/51136136/2982fde9-7d82-4253-8e5f-a94138b2e67f)

**Comment by ilyhalight** [comment]
> ![Снимок экрана 2023-08-23 в 17 36 31](https://user-images.githubusercontent.com/51136136/262805146-2982fde9-7d82-4253-8e5f-a94138b2e67f.png)

Кхм, странно, а сам перевод видео у вас точно включен? (кнопка будет гореть фиолетовым как на моем скриншоте)

**Comment by Stepman123** [comment]
Уменя такая же версия и меню тоже без этой кнопки. Только что узнал о такой мегаполезной функции, просматривая скришоты в другой теме.
Хотелось бы её вверху иметь, а то у меня меню не полностью помещается пока видео не развернуто. Развернуть сложно из-за тормозов.

**Comment by ilyhalight** [comment]
Будем думать, что проблема решена

**Comment by Stepman123** [comment]
> Будем думать, что проблема решена

В другом вопросе обещали, что с выходом новой версии, кнопка "скачать" будет доступна вверху, но ничего не изменилось. Кнопка в самом низу, скрыта, пока не развернёшь окно плеера.
Может я что не так делаю?

**Comment by ilyhalight** [comment]
> > Будем думать, что проблема решена
> 
> [#268 (reply in thread)](https://github.com/ilyhalight/voice-over-translation/discussions/268#discussioncomment-6836755) В другом вопросе обещали, что с выходом новой версии, кнопка "скачать" будет доступна вверху, но ничего не изменилось. Кнопка в самом низу, скрыта, пока не развернёшь окно плеера. Может я что не так делаю?

меню еще не обновлено

**Comment by hastalamuerte** [comment]
@ilyhalight Спасибо за софт.
Подскажите возможно ли скачивание видео уже с наложенной переведенной звуковой дорожкой (возможно используя сторонний менеджер загрузок YTDLnis или иные) ?

**Comment by ilyhalight** [comment]
> @ilyhalight Спасибо за софт. Подскажите возможно ли скачивание видео уже с наложенной переведенной звуковой дорожкой (возможно используя сторонний менеджер загрузок YTDLnis или иные) ?

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/e39f68b4-46f5-422b-bc90-bf93f2e2cf69)
