### ISSUE TITLE
Нет голоса перевода , Cloudflare version 

### ISSUE THREAD

**Issue by BlackLord-0** [ilyhalight/voice-over-translation#291]
Пробовал ставить разные версии , показывает что перевод идет а голоса перевода нет , в чем может быть причина  ?

**Comment by SashaXser** [comment]
> Пробовал ставить разные версии , показывает что перевод идет а голоса перевода нет , в чем может быть причина ?

Скинь видео, а также покажи что у тебя в консоли

**Comment by BlackLord-0** [comment]
> > Пробовал ставить разные версии , показывает что перевод идет а голоса перевода нет , в чем может быть причина ?
> 
> Скинь видео, а также покажи что у тебя в консоли
![Снимок](https://github.com/ilyhalight/voice-over-translation/assets/141166548/5fb0bd2c-1b4e-4f03-aa6e-737a58e5ac43)

Теперь пишет , что формат аудио не поддерживается

**Comment by BlackLord-0** [comment]
> > > > Пробовал ставить разные версии , показывает что перевод идет а голоса перевода нет , в чем может быть причина ?
> > > 
> > > 
> > > Скинь видео, а также покажи что у тебя в консоли
> > > ![Снимок](https://user-images.githubusercontent.com/141166548/263026784-5fb0bd2c-1b4e-4f03-aa6e-737a58e5ac43.PNG)
> > 
> > 
> > Теперь пишет , что формат аудио не поддерживается
> 
> Формат аудио не поддерживается. Это значит, что сервер Яндекса у вас недоступен. Вы можете скачать скрипт из #288 После этого сбросьте настройки и выберите опцию “Проксирование аудио”. Я думаю, это вам поможет.

Спасибо все заработало , версия 1.3.5 включила перевод и появилось проксирование аудио

**Comment by ilyhalight** [comment]
> Спасибо все заработало , версия 1.3.5 включила перевод и появилось проксирование аудио

Проксирование аудио возвращено в 1.4.1-beta3
