### ISSUE TITLE
.bat file for windows

### ISSUE THREAD

**Issue by 4lev** [ilyhalight/voice-over-translation#293]
```shell
rem @echo off

set original_sound_ratio=0.2
set temp_dir=".\temp"
set temp_video_dir=%temp_dir%\video
set temp_video="%temp_video_dir%\%%(title)s.%%(ext)s"
set temp_audio=%temp_dir%\audio

set video_link=%1



rmdir /s /q %temp_dir%
md %temp_dir%
md %temp_video_dir%
md %temp_audio%

yt-dlp.exe -o %temp_video% %video_link%

echo "Start load translate"
call vot-cli %video_link% --output %temp_audio%

for /f "tokens=*" %%i in ('dir %temp_video_dir% /b') do set video_full_name=%%i
for /f "tokens=*" %%i in ('dir %temp_audio% /b') do set audio_full_name=%%i


ffmpeg.exe -i "%temp_video_dir%\%video_full_name%" -i "%temp_audio%\%audio_full_name%" -c:v copy -filter_complex "[0:a] volume=%original_sound_ratio% [original]; [original][1:a] amix=inputs=2:duration=longest [audio_out]" -map 0:v -map "[audio_out]" -y "%video_full_name%"

rem rmdir /s /q %temp_dir%

```

**Comment by FiLinX** [comment]
я увы совсем не кодун, и не очень понимаю  -  это батник для скачивания ориг видео (с уменьшенной громкостью аудио) + скачивание аудио дорожки перевода, с последующей их склейкой и сохранением в один файл?

**Comment by ilyhalight** [comment]
> я увы совсем не кодун, и не очень понимаю - это батник для скачивания ориг видео (с уменьшенной громкостью аудио) + скачивание аудио дорожки перевода, с последующей их склейкой и сохранением в один файл?

Да

> но разве такое возможно - натравливать vot-cli на в темпе компа локально лежащее видео?

Мысль та же, что и в #153, и в похожем скрипте у другого человека на gitlab. Вводишь ссылку на видео (ютуб, вимео и т.п.), скрипт подгружает видео, запрашивает перевод через vot-cli и через ffmpeg соединяет аудио с оригинальным видео

**Comment by ilyhalight** [comment]
> ```shell
> rem @echo off
> 
> set original_sound_ratio=0.2
> set temp_dir=".\temp"
> set temp_video_dir=%temp_dir%\video
> set temp_video="%temp_video_dir%\%%(title)s.%%(ext)s"
> set temp_audio=%temp_dir%\audio
> 
> set video_link=%1
> 
> 
> 
> rmdir /s /q %temp_dir%
> md %temp_dir%
> md %temp_video_dir%
> md %temp_audio%
> 
> yt-dlp.exe -o %temp_video% %video_link%
> 
> echo "Start load translate"
> call vot-cli %video_link% --output %temp_audio%
> 
> for /f "tokens=*" %%i in ('dir %temp_video_dir% /b') do set video_full_name=%%i
> for /f "tokens=*" %%i in ('dir %temp_audio% /b') do set audio_full_name=%%i
> 
> 
> ffmpeg.exe -i "%temp_video_dir%\%video_full_name%" -i "%temp_audio%\%audio_full_name%" -c:v copy -filter_complex "[0:a] volume=%original_sound_ratio% [original]; [original][1:a] amix=inputs=2:duration=longest [audio_out]" -map 0:v -map "[audio_out]" -y "%video_full_name%"
> 
> rem rmdir /s /q %temp_dir%
> ```

Создайте [Pull Request](https://github.com/ilyhalight/voice-over-translation/pulls), если хотите чтобы ваш батник добавили
