### ISSUE TITLE
Создать PKGBUILD

### ISSUE THREAD

**Issue by gargullia** [ilyhalight/voice-over-translation#303]
Цель иметь бинарник, который можно собирать/запускать в песочнице терминале
Помогите создать PKGBUILD. В мануале https://wiki.archlinux.org/title/Node.js_package_guidelines нет ничего про npm link

Речь про vot-cli

**Comment by ilyhalight** [comment]
pkgbuild поддерживает пакеты устанавливаемые глобально `npm install -g NAME`?

**Comment by ilyhalight** [comment]
Будем думать, что у вас все получилось
