### ISSUE TITLE
запрос

### ISSUE THREAD

**Issue by zlobens** [ilyhalight/voice-over-translation#304]
Возможно ли уменьшить дилей голоса между основный и вторичным?
спасибо за ответ

**Comment by ilyhalight** [comment]
Немного не понял вопроса. Если речь о смене голоса разных людей в самой озвучке, то невозможно т.к. это происходит на стороне серверов яндеса.

**Comment by zlobens** [comment]
я про голос, что поверх накладывается
там есть задержка в ms
тоисть голос оригинальный, он говорит, и поверх начинает накладыватся второй
и вот он задерживается 
можно ли как то сместить так, что бы голос начинал говорить так же, как и оригинальный голос
дилей где то 250-300 ms

**Comment by ilyhalight** [comment]
Только, если пытаться что-то чудить с липсинком, но, скорее всего, идеально дилей, все равно, работать не будет т.к. это побольшей части зависит дорожки от Яндекса.
