### ISSUE TITLE
Как скачивать звуковую дорожку?

### ISSUE THREAD

**Issue by tellts** [ilyhalight/voice-over-translation#305]
Здравствуйте. Есть расширение для браузера Skyload, которое может скачивать звуковую дорожку перевода на русский. А можно ли сделать, чтобы скачивались звуковые дорожки со всего плейлиста? Не подскажите, как доработать скрипт для этого или может быть Вы можете добавить этот функционал в ваше приложение или такой функционал, чтобы скачивалась не только переведенная дорожка, а русифицированное видео целиком (для совместимости просмотра на Андроид устройствах, а не только в VLC плеере на ПК, где можно добавлять эту звуковую дорожку дополнительно)?

**Comment by ilyhalight** [comment]
> русифицированное видео целиком

Через [vot-cli](https://github.com/FOSWLY/vot-cli) и [один из подходящих под вашу систему скриптов](https://github.com/FOSWLY/vot-cli#-%D0%BF%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D1%8B%D0%B5-%D1%81%D1%81%D1%8B%D0%BB%D0%BA%D0%B8) можете скачать сразу русифицированное видео. Загрузка и перевод сразу всего плейлиста не планируется.
