### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by race99** [ilyhalight/voice-over-translation#306]
![image](https://github.com/ilyhalight/voice-over-translation/assets/110671249/da35ecaf-01d3-4fc9-91ad-abb63d977c1d)
Скрипты не работают с ошибкой Bad Request. Google Chrome последней версии.

**Comment by ilyhalight** [comment]
А ты не хочешь обновить расширение до последней стабильной версии? Твоей версии расширения уже больше года.
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/59637486-2c12-4116-a698-b74cda02362f)
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/fa044b3b-9176-4ac4-9e50-b8d1aef4f425)
