### ISSUE TITLE
Расположение кнопки перевода перекрывает стандартные кнопки браузера

### ISSUE THREAD

**Issue by awesomebloging** [ilyhalight/voice-over-translation#307]
Спасибо за расширение.
Но есть один момент: во время нажатия фулл скрин видео, появляются кнопки браузера, которые перекрывают кнопку перевода. 
![img-2023-09-09-22-06-05](https://github.com/ilyhalight/voice-over-translation/assets/80858724/5fcb573e-00d9-4b74-843c-a80ed2f96ac3)
![img-2023-09-09-22-06-10](https://github.com/ilyhalight/voice-over-translation/assets/80858724/3c244900-4bff-4590-9337-dbfdd70b4dc4)

Это так же случается, когда случайно дернешь мышкой. Появляется интерфейс браузера и в этот момент кнопка перевода перекрывается. 

При частом использовании это не приятно. Приходится ждать по 5-10 сек, пока интерфейс браузера пропадет. 

Предлагаю просто сделать кнопку чуть выше или ниже.

**Comment by SashaXser** [comment]
> Спасибо за расширение. Но есть один момент: во время нажатия фулл скрин видео, появляются кнопки браузера, которые перекрывают кнопку перевода. ![img-2023-09-09-22-06-05](https://user-images.githubusercontent.com/80858724/266798570-5fcb573e-00d9-4b74-843c-a80ed2f96ac3.png) ![img-2023-09-09-22-06-10](https://user-images.githubusercontent.com/80858724/266798573-3c244900-4bff-4590-9337-dbfdd70b4dc4.png)
> 
> Это так же случается, когда случайно дернешь мышкой. Появляется интерфейс браузера и в этот момент кнопка перевода перекрывается.
> 
> При частом использовании это не приятно. Приходится ждать по 5-10 сек, пока интерфейс браузера пропадет.
> 
> Предлагаю просто сделать кнопку чуть выше или ниже.

Вы можете изменять расположение кнопки по своему усмотрению. 
Для этого в 130 строке измените значение свойства top: 5rem на top: 8rem. Тогда кнопка опустится ниже.

**Comment by ilyhalight** [comment]
Ответ дали выше. Если делать кнопку ниже/выше, то могут появиться проблемы на других сайтах или при использование в iframe
