### ISSUE TITLE
Translation Missing

### ISSUE THREAD

**Issue by neoOpus** [ilyhalight/voice-over-translation#309]
Please translate this string into the respective languages.

Нейросети не смогли определить речь на видео

**Comment by SashaXser** [comment]
> _No description provided._

Why are you creating an empty issue with no description? How can I help you if you are deaf-mute? Describe your problem.

**Comment by ilyhalight** [comment]
very informative

**Comment by neoOpus** [comment]
I fixed that by editinng but it seems that it didn't correct it

**Comment by neoOpus** [comment]
> > _No description provided._
> 
> Why are you creating an empty issue with no description? How can I help you if you are deaf-mute? Describe your problem.

no need to be mean!

**Comment by SashaXser** [comment]
> > > _No description provided._
> > 
> > 
> > Why are you creating an empty issue with no description? How can I help you if you are deaf-mute? Describe your problem.
> 
> no need to be mean!

I'm not angry, it's just that I was sleepy at the time.

**Comment by SashaXser** [comment]
> Please translate this string into the respective languages.
> 
> Нейросети не смогли определить речь на видео

That means the neural network couldn't detect the voice.

**Comment by ilyhalight** [comment]
These lines are independent of the extension. They are transmitted directly from the server response.

**Comment by neoOpus** [comment]
> These lines are independent of the extension. They are transmitted directly from the server response.

That's what I thought, but can't they be translated using string replacement?

**Comment by neoOpus** [comment]
Anyway, it is not critical and consider this as a low-priority request

**Comment by ilyhalight** [comment]
In the next beta/release, there will be an optional inclusion of the translation of this text using additional queries.

**Comment by ilyhalight** [comment]
added in stable
