### ISSUE TITLE
Перевод для локальных файлов

### ISSUE THREAD

**Issue by stemplock** [ilyhalight/voice-over-translation#310]
Есть ли возможность сделать перевод для локальных файлов на основе этого же скрипта или такое уже есть? Это не проще, чем кодировать логику под множество сервисов?

**Comment by ilyhalight** [comment]
Яндекс не поддерживает перевод локальных файлов. Конечно, у меня есть 1 теория, которую надо будет в будушем проверить, но пока будем считать, что перевод локальных файлов не возможен.

**Comment by ilyhalight** [comment]
> Яндекс не поддерживает перевод локальных файлов. Конечно, у меня есть 1 теория, которую надо будет в будушем проверить, но пока будем считать, что перевод локальных файлов не возможен.

Собственно как и предполагал, для локальных файлов нереализуемо, но для файлов на других сайтах при наличие субтитров можно заставить работать

**Comment by stemplock** [comment]
А вариант поднять свой ютуб с локальным хранилишем тоже не получится? В чем основная проблема?

**Comment by stemplock** [comment]
> > Яндекс не поддерживает перевод локальных файлов. Конечно, у меня есть 1 теория, которую надо будет в будушем проверить, но пока будем считать, что перевод локальных файлов не возможен.
> 
> Собственно как и предполагал, для локальных файлов нереализуемо, но для файлов на других сайтах при наличие субтитров можно заставить работать

А вариант поднять свой ютуб с локальным хранилишем тоже не получится? В чем основная проблема?

**Comment by ilyhalight** [comment]
> > > Яндекс не поддерживает перевод локальных файлов. Конечно, у меня есть 1 теория, которую надо будет в будушем проверить, но пока будем считать, что перевод локальных файлов не возможен.
> > 
> > 
> > Собственно как и предполагал, для локальных файлов нереализуемо, но для файлов на других сайтах при наличие субтитров можно заставить работать
> 
> В чем основная проблема? А вариант поднять свой ютуб с локальным хранилишем тоже не получится? Или просто поднять свой ютуб на хостинге. Так будет работать?

Если у видео есть субтитры в формате vtt и сам mp4/webm файл, то без проблем можно перевести любое видео с любого сайта. А без субтитров, соответственно, ничего работать не будет.

> А вариант поднять свой ютуб с локальным хранилишем тоже не получится? Или просто поднять свой ютуб на хостинге. Так будет работать?

Можно, если вы будете заливать видео вместе с субтитрами. В теории, можно, даже, просто, сделать пустой сайт и бегать переводить чисто по файлам с видео, но опять, таки, рядом должны лежать субтитры

**Comment by Experience1-1** [comment]
Мои предположения, что можно реализовать какую нибудь мини-программу (желательно которая бы не требовала установленного Node.js или каких либо других "dependencies"), суть которой в извлечении аудиодорожки из видео (локально на компьютере) и отправки на какой нибудь сервер, с которого voice-over-translation получает ее и переводит, а затем перевод уже можно скачать как аудиофайл с переводом либо с переводом + оригинальный звук, тут уже зависит от реализации. Не всем удобно выкладывать видео на ютуб просто чтобы его перевести, тем более с видео с доступом по ссылке оно не работает, а значит видео публикуется в открытый доступ, для кого то это важный момент

**Comment by jonson777222** [comment]
ilyhalight , объясните пожалуста, в описании к Vot-cli написано "Установка" , "Установка для разработки". Их нужно обе провести если я хочу просто скачивать переведенное видео ?
И ще вопрос : версия для браузера позволяет скачивать переведенные видео или нет ?
Спасибо.

**Comment by ilyhalight** [comment]
> ilyhalight , объясните пожалуста, в описании к Vot-cli написано "Установка" , "Установка для разработки". Их нужно обе провести если я хочу просто скачивать переведенное видео ? 

Просто "установка"

> И ще вопрос : версия для браузера позволяет скачивать переведенные видео или нет 

Нет. С помощью ее можно скачать только аудио дорожку перевода (без звука видео) и субтитры
