### ISSUE TITLE
Формат аудио не поддерживается (Cloudflare version)

### ISSUE THREAD

**Issue by IvanAstran** [ilyhalight/voice-over-translation#315]
![chrome_HQY6CmdlnE](https://github.com/ilyhalight/voice-over-translation/assets/96918464/3c5c6d9c-9fe1-4cb6-bbaa-9a7a645de06d)
![chrome_thnA3SeLHp](https://github.com/ilyhalight/voice-over-translation/assets/96918464/c570ad52-aaf8-4a14-bd09-5b79f30cdee2)
Chrome.
Версия 117.0.5938.63

**Comment by SashaXser** [comment]
Включите пункт "Проксировать полученное аудио" в меню
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/9250ba86-a87a-458e-9df0-ee83a455ec0b)
