### ISSUE TITLE
Не удалось перевести

### ISSUE THREAD

**Issue by Jeronino** [ilyhalight/voice-over-translation#316]
![Screenshot_2023-09-15-11-55-18-044_com yandex browser-edit](https://github.com/ilyhalight/voice-over-translation/assets/145093140/84ea1829-f273-4d13-898b-ff0415cfaf00)

Хотел перевести видео, чистый английский>русский.
Загрузил видео в ВК так-как тот сайт не поддерживается.
И он не захотел переводить
В чем дело?

**Comment by ilyhalight** [comment]
Проблема на стороне Яндекса
