### ISSUE TITLE
" Не удалось получить данные для перевода " Udemy

### ISSUE THREAD

**Issue by Doromeo** [ilyhalight/voice-over-translation#317]
Как исправить проблему на Udemy? Вводишь токен, не работает.

**Comment by ilyhalight** [comment]
Что в консоли пишет?

**Comment by Doromeo** [comment]
Там где токен? везде true. А что должно быть?

**Comment by Doromeo** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/2f6a6ff7-3525-42cc-b4ec-1ecf0cccb416)

**Comment by Doromeo** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/d3318015-0d5b-47e6-b1a2-4ec2286ea44f)

**Comment by ilyhalight** [comment]
Поставь одну из этих версий (взависимости от той, которая стоит у тебя сейчас) и проверь, на каком моменте возникает ошибка. Скорее всего, не удается получить ссылку на видео или на субтитры
https://drive.google.com/drive/folders/1JNBHzhC5v7_J8eFxrMRkua1XS-U6VZ2d?usp=sharing

**Comment by ilyhalight** [comment]
> Поставь одну из этих версий (взависимости от той, которая стоит у тебя сейчас) и проверь, на каком моменте возникает ошибка. Скорее всего, не удается получить ссылку на видео или на субтитры https://drive.google.com/drive/folders/1JNBHzhC5v7_J8eFxrMRkua1XS-U6VZ2d?usp=sharing

Нижний выделенный блок нужно проверить
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/c078533d-7e9f-4255-972f-010b42f393fa)

**Comment by Doromeo** [comment]
Не а, на любом скрипте отказывается 
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/65a9eba2-ad5b-43b8-a393-846e3208234d)

**Comment by Doromeo** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/e8cc155b-c531-41b5-8e27-bba483c21bd4)

**Comment by ilyhalight** [comment]
> ![image](https://user-images.githubusercontent.com/145155343/268379229-e8cc155b-c531-41b5-8e27-bba483c21bd4.png)

что в Video Data -> translationHelp показывает?

**Comment by Doromeo** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/bbe7a8e9-6107-476b-9d42-10a086ce21c9)

**Comment by ilyhalight** [comment]
> ![image](https://user-images.githubusercontent.com/145155343/268382045-bbe7a8e9-6107-476b-9d42-10a086ce21c9.png)

Не тут, а именно в консоли. Нужно на стрелочку нажать чтобы отобразилось
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/cd33d2a5-374e-4172-b2d6-19eab35ec9a4)

**Comment by Doromeo** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/da46a06e-334d-4775-87f5-0ce1e1b60890)

**Comment by ilyhalight** [comment]
Из того, что вижу, похоже, что апи не возвращает субтитры, не думаю, что проблема на стороне расширения

**Comment by Doromeo** [comment]
ну странно оно работает, у меня и на этих скриптах ютуб не переводит также, а только на 1.5.

**Comment by Doromeo** [comment]
кажется я понял, так как я из Украины, то при включении VPN, на ютубе перевод работает, а на udemy пишет  
![image](https://github.com/ilyhalight/voice-over-translation/assets/145155343/9b5da723-3520-4051-afd0-0fa55d511187)

**Comment by MrWh1tee** [comment]
Тоже не удалось получить данные, для перевода

**Comment by MrWh1tee** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/731e482d-ee8a-43ec-ba95-659dab381043)

**Comment by ilyhalight** [comment]
> ![image](https://user-images.githubusercontent.com/27813446/268592260-731e482d-ee8a-43ec-ba95-659dab381043.png)

Попробуйте сделать, тоже, самое, что советовал человеку выше и посмотреть, что возвращается в "Udemy Data", когда возникает ошибка

**Comment by MrWh1tee** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/6f3fd8e2-6cae-4fb4-82d9-011b1259f733)
всё равно не даёт.


> Поставь одну из этих версий (взависимости от той, которая стоит у тебя сейчас) и проверь, на каком моменте возникает ошибка. Скорее всего, не удается получить ссылку на видео или на субтитры https://drive.google.com/drive/folders/1JNBHzhC5v7_J8eFxrMRkua1XS-U6VZ2d?usp=sharing


Нужно просто скопировать код и вставить? Или как-то по другому это делается

**Comment by MrWh1tee** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/7cfed995-a593-4a70-93ef-3bba0f278971)

**Comment by ilyhalight** [comment]
Возможно, понял в чем проблема. Субтитры ищутся по языку, который выбран как язык перевода и если не удается найти, то происходит ошибка, что не найдены субтитры, хотя, допустим, были еще какие-нибудь субтитры, например на английском. В следующей бете попробую исправить

**Comment by ilyhalight** [comment]
Попробуйте [1.5.0-beta2](https://github.com/ilyhalight/voice-over-translation/releases), там, должно все работать.

**Comment by Walterus** [comment]
Не работает перевод Udemy, ставил версии 1.5.0-beta2 vot-cloudflare.user.js и vot.user.js

по скрипту  vot-cloudflare.user.js, такая ошибка

![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/b2906675-ccda-4606-af16-226651c81e21)

по скрипту vot.user.js

![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/12d29f62-1cd8-4509-859f-b1a669e87e7b)

Снова проблема с получением ссылки для видео, ссылка на субтитры которая на скриншоте рабочая, если по ней перейти открываются субтитры! В чем может быть проблема.

**Comment by ilyhalight** [comment]
> Не работает перевод Udemy, ставил версии 1.5.0-beta2 vot-cloudflare.user.js и vot.user.js
> 
> по скрипту  vot-cloudflare.user.js, такая ошибка
> 
> ![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/b2906675-ccda-4606-af16-226651c81e21)
> 
> по скрипту vot.user.js
> 
> ![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/12d29f62-1cd8-4509-859f-b1a669e87e7b)
> 
> Снова проблема с получением ссылки для видео, ссылка на субтитры которая на скриншоте рабочая, если по ней перейти открываются субтитры! В чем может быть проблема.
> 
> 
> 

Странно, почему-то все равно не получается найти ссылку на видео. Возможно, для платных курсов апи не возвращает ссылку, либо в вашем случае видео имеет какой-то формат отличный от mp4 или webp. Очень помогло бы, если бы вы скинули как выглядит ответ от апи (можете поставить тестовую версию, которую кидал в ветке с проблемой на юдеми. Там в консоли будет lecture data -> media_sources (если найду скрин, то приложу))

**Comment by ilyhalight** [comment]
> ![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/6f3fd8e2-6cae-4fb4-82d9-011b1259f733)


Нужен блок, который выделен (media_sources)

**Comment by uneconomicuse** [comment]
Всем привет!
Тоже столкнулся с тем, что расширение не переводит на Udemy. Может ли это быть связано с DRM у некоторых видео?  https://support.udemy.com/hc/en-us/articles/229231167

**Comment by ilyhalight** [comment]
> Всем привет! Тоже столкнулся с тем, что расширение не переводит на Udemy. Может ли это быть связано с DRM у некоторых видео? https://support.udemy.com/hc/en-us/articles/229231167

Может быть, точную причину пока не удалось найти

**Comment by Walterus** [comment]
> > ![image](https://user-images.githubusercontent.com/27813446/268748231-6f3fd8e2-6cae-4fb4-82d9-011b1259f733.png)
> 
> Нужен блок, который выделен (asset -> media_sources)

не смог найти такой же как ты предоставил на скрине, но вот что нашел
![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/fe40d4af-7c7a-4558-ac2d-4a9e4c640891)

и

![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/457a2f36-5dc7-4988-aa57-7c47867a9673)

Установил так 
![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/6f6b223d-85b4-4409-bbe4-e3e2751e5977)
просто ранее не работал с этим, может что-то сделал не так!

**Comment by ilyhalight** [comment]
> Установил так ![image](https://user-images.githubusercontent.com/22342733/269391344-6f6b223d-85b4-4409-bbe4-e3e2751e5977.png) просто ранее не работал с этим, может что-то сделал не так!

Попробуйте отключить все версии расширения и оставить только [одну из этих версий](https://drive.google.com/drive/folders/1JODMiv25KG0Dfn14hp_lfxddp3g6br24?usp=sharing) (1.5.0-beta2 с включеным дебагом, выбирайте в зависимости от текущей версии расширения (для вас это будет vot.user.js или vot-min.user.js)) и уже на ней протестировать. Если все равно не появятся логи с префиксом [VOT DEBUG], то проверьте настройки уровня логирования в консоли (на скриншоте в самом верху)

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/f2b7ee36-3cc4-4aab-aa35-750d183908f5)



> не смог найти такой же как ты предоставил на скрине, но вот что нашел ![image](https://user-images.githubusercontent.com/22342733/269390720-fe40d4af-7c7a-4558-ac2d-4a9e4c640891.png)
> 
> и
> 
> ![image](https://user-images.githubusercontent.com/22342733/269390820-457a2f36-5dc7-4988-aa57-7c47867a9673.png)
> 

Это скорее, всего, просто, не прогрузились превьюшки или еще какие-то картинки

**Comment by Walterus** [comment]
> одну из этих версий

поставил ту версию по вашей ссылке которую вы указали, удалил предыдущие расширения, у меня вообще перестала появлятся меню на видео, кнопка перевода, ничего нет! На Youtube также!
![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/137695fd-d202-4c8c-bcaf-d9f51926a902)

**Comment by ilyhalight** [comment]
> > одну из этих версий
> 
> поставил ту версию по вашей ссылке которую вы указали, удалил предыдущие расширения, у меня вообще перестала появлятся меню на видео, кнопка перевода, ничего нет! На Youtube также! ![image](https://user-images.githubusercontent.com/22342733/269540173-137695fd-d202-4c8c-bcaf-d9f51926a902.png)

Какая-то странная ошибка... Вы точно все правильно поставили? (скачали файл по ссылке - скопировали содержимое - вставили в полностью пустой скрипт в tampermonkey)

**Comment by Walterus** [comment]
Вроде получилось
![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/d0b09723-874f-4e04-aa2a-a68d058a1ab6)

**Comment by ilyhalight** [comment]
> Вроде получилось ![image](https://user-images.githubusercontent.com/22342733/269597092-d0b09723-874f-4e04-aa2a-a68d058a1ab6.png)

[Добавил тестовую поддержку](https://drive.google.com/drive/folders/1TIpXcYICK6MiPb70pIKsVMki4eW2yPRZ?usp=sharing) этих форматов (попробуйте для теста выбрать 2 разных ролика или 2 разных языка по 1 на каждую из версий), если не заработает, то это уже яндекс их не поддерживает

**Comment by Walterus** [comment]
Не работает
![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/3475b752-06d7-49be-9110-463ddfa255a3)

**Comment by ilyhalight** [comment]
> Не работает
> ![image](https://github.com/ilyhalight/voice-over-translation/assets/22342733/3475b752-06d7-49be-9110-463ddfa255a3)
> 

Не тот не тот?

**Comment by Walterus** [comment]
неа!

**Comment by ilyhalight** [comment]
В кнопке как понимаю тоже надпись не удалось получить данные? Или поменялась на не удалось перевести, видео недоступно для перевода и т.п?

**Comment by Walterus** [comment]
Да, старая надпись, не удалось получить данные....

**Comment by MrWh1tee** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/906a1672-f7dd-4ea6-bf6e-d7d3ef49bd34)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/14bcf1c1-b3e9-4618-81bf-6d81077e06b9)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/6156b0ea-b909-4386-aecb-7277548df984)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/8381b2c3-4bd2-48d3-a040-66b62a692860)


> > Установил так ![image](https://user-images.githubusercontent.com/22342733/269391344-6f6b223d-85b4-4409-bbe4-e3e2751e5977.png) просто ранее не работал с этим, может что-то сделал не так!
> 
> Попробуйте отключить все версии расширения и оставить только [одну из этих версий](https://drive.google.com/drive/folders/1JODMiv25KG0Dfn14hp_lfxddp3g6br24?usp=sharing) (1.5.0-beta2 с включеным дебагом, выбирайте в зависимости от текущей версии расширения (для вас это будет vot.user.js или vot-min.user.js)) и уже на ней попробуйте протестировать. Если все равно не появятся логи с префиксом [VOT DEBUG], то проверьте настройки уровня логирования в консоли (на скриншоте в самом верху)
> 
> ![image](https://user-images.githubusercontent.com/62353659/269405372-f2b7ee36-3cc4-4aab-aa35-750d183908f5.png)
> 
> > не смог найти такой же как ты предоставил на скрине, но вот что нашел ![image](https://user-images.githubusercontent.com/22342733/269390720-fe40d4af-7c7a-4558-ac2d-4a9e4c640891.png)
> > и
> > ![image](https://user-images.githubusercontent.com/22342733/269390820-457a2f36-5dc7-4988-aa57-7c47867a9673.png)
> 
> Это скорее, всего, просто, не прогрузились превьюшки или еще какие-то картинки

пробовал эту версию "не удалось получить данные"

**Comment by ilyhalight** [comment]
> Да, старая надпись, не удалось получить данные....

Понял в чем проблема, в спешке, случайно поставил лишние ковычки и из-за чего не правильно проверялось. Правда, как я и предполагал, яндекс не поддерживает видео в формате m3u8. Насчет mpd не скажу, но он так редко встречается, что я не нашел его за ~20 курсов
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/d3c48eac-8434-4a61-ab0c-21d08daa7ff1)

**Comment by Walterus** [comment]
а где можно скачать, чтобы увидеть что не поддерживает именно, но то есть с доп ковычками? А то пока у меня ошибка прошлая

**Comment by Walterus** [comment]
В формате mpd перевод начинается, но выходит ошибка "Возникла ошибка при переводе, попробуйте позже", значит также не поддерживает!

**Comment by MrWh1tee** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/a9372306-af9b-44f1-b062-29987584fce7)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/46e18014-6ede-4c05-9637-0e3b511abffa)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/a2c6a12a-6fbc-4740-89dc-975e8202333f)
![image](https://github.com/ilyhalight/voice-over-translation/assets/27813446/c189552e-98aa-4028-90e7-a28e6992c9cf)


попробовал m3u8 и mdp с припиской fix - не работает

**Comment by ilyhalight** [comment]
> попробовал m3u8 и mdp с припиской fix - не работает

> Правда, как я и предполагал, яндекс не поддерживает видео в формате m3u8. Насчет mpd не скажу, но он так редко встречается, что я не нашел его за ~20 курсов

Я же выше уже сказал, что оно не будет работать, яндекс не поддерживает видео в m3u8 или mpd

**Comment by anonymousmaharaj** [comment]
Я в итоге не смог запустить с дебагом ни одну из версий, которые на Гугл диске лежат. Даже кнопка не появляется "Перевести видео". ЧЯДНТ?

Бесплатные видео переводятся. У меня 2 платных курса - они нет. Пишет "Не удалось получить данные". Хотелось бы как-то их формат узнать.

**Comment by Hybridd1** [comment]
Такая же проблема. Очень нужно перевести видео, и никак. Стоит последняя бета.
![444](https://github.com/ilyhalight/voice-over-translation/assets/37854601/aea8e5e1-88d7-4e9c-9dc4-ef4388c54e28)
