### ISSUE TITLE
Не переводит Видео Mail.ru

### ISSUE THREAD

**Issue by imudk** [ilyhalight/voice-over-translation#322]
Последние две версии не хотят переводить, что в Chrome, что в Edge.
Пробовал обе версии, обычную и Cloudflare.
![image](https://github.com/ilyhalight/voice-over-translation/assets/58263299/29289c06-7b04-4c02-9552-1abc25d6b388)

**Comment by imudk** [comment]
В консоле все красное, но я не понимаю, что это значит.
![image](https://github.com/ilyhalight/voice-over-translation/assets/58263299/be74f92d-3b42-42fb-852b-7764449f936c)

**Comment by SashaXser** [comment]
> В консоле все красное, но я не понимаю, что это значит. ![image](https://user-images.githubusercontent.com/58263299/268462248-be74f92d-3b42-42fb-852b-7764449f936c.png)

Скачай [это](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/)

**Comment by ilyhalight** [comment]
> > В консоле все красное, но я не понимаю, что это значит. ![image](https://user-images.githubusercontent.com/58263299/268462248-be74f92d-3b42-42fb-852b-7764449f936c.png)
> 
> Проверил, у меня тоже не работает. Возможно поддержку отключи :/

Очень похоже на то. Видео, которое раньше всегда нормально переводилось и на котором все тестил, сейчас, тоже вовзращает такую ошибку. Будем надеяться, что это просто временное отключение поддержки, либо, что просто что-то поменяли

**Comment by imudk** [comment]
> Очень похоже на то. Видео, которое раньше всегда нормально переводилось и на котором все тестил, сейчас, тоже возращает такую ошибку. Будем надеяться, что это просто временное отключение поддержки, либо, что просто что-то поменяли

Надеялся, что это только у меня. Жаль, туда можно было лить и не переживать за копирайты.

**Comment by stemplock** [comment]
Тоже самое. И Рутуб так же не переводит.

**Comment by ilyhalight** [comment]
> Тоже самое. И Рутуб так же не переводит.

На 1.5.0-beta1 работает
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/079f398c-650a-4560-ba8e-c1d1db9c6308)

**Comment by stemplock** [comment]
> > Тоже самое. И Рутуб так же не переводит.
> 
> На 1.5.0-beta1 работает ![image](https://user-images.githubusercontent.com/62353659/268535404-079f398c-650a-4560-ba8e-c1d1db9c6308.png)

Не удалось воспроизвести перевод.  Какая у вас ОС, браузер, версия скрипта? Используете Tampermonkey? Ссылка на видео с общим доступом или ограниченная? Хочется уже рахобраться.)

**Comment by ilyhalight** [comment]
> > > Тоже самое. И Рутуб так же не переводит.
> > 
> > 
> > На 1.5.0-beta1 работает ![image](https://user-images.githubusercontent.com/62353659/268535404-079f398c-650a-4560-ba8e-c1d1db9c6308.png)
> 
> Не удалось воспроизвести перевод. Какая у вас ОС, браузер, версия скрипта? Используете Tampermonkey? Ссылка на видео с общим доступом или ограниченная? Хочется уже разобраться.)

win11, firefox dev. edition 118.0b6 64bit, tampermonkey stable,  vot1.5.0-beta1

Все видео с общим доступом:
Видео 1 - https://rutube.ru/video/436d05cf6edf0a0cadf42fd2360774cc/
Видео 2 - https://rutube.ru/video/241adb788c5ab9cc14b67b06b7af84c6/

**Comment by stemplock** [comment]
> > > > Тоже самое. И Рутуб так же не переводит.
> > > 
> > > 
> > > На 1.5.0-beta1 работает ![image](https://user-images.githubusercontent.com/62353659/268535404-079f398c-650a-4560-ba8e-c1d1db9c6308.png)
> > 
> > 
> > Не удалось воспроизвести перевод. Какая у вас ОС, браузер, версия скрипта? Используете Tampermonkey? Ссылка на видео с общим доступом или ограниченная? Хочется уже разобраться.)
> 
> win11, firefox dev. edition 118.0b6 64bit, tampermonkey stable, vot1.5.0-beta1
> 
> Все видео, на которых я тестил, были с общим доступом: Видео 1 (перевод с русского на русский) - https://rutube.ru/video/436d05cf6edf0a0cadf42fd2360774cc/ Видео 2 (перевод с англ. на русский) - https://rutube.ru/video/241adb788c5ab9cc14b67b06b7af84c6/

Проверил. На рутуб работает только при общем доступе к видео. При доступе по прямой ссылке не работает.

**Comment by ilyhalight** [comment]
> > > > > Тоже самое. И Рутуб так же не переводит.
> > > > 
> > > > 
> > > > На 1.5.0-beta1 работает ![image](https://user-images.githubusercontent.com/62353659/268535404-079f398c-650a-4560-ba8e-c1d1db9c6308.png)
> > > 
> > > 
> > > Не удалось воспроизвести перевод. Какая у вас ОС, браузер, версия скрипта? Используете Tampermonkey? Ссылка на видео с общим доступом или ограниченная? Хочется уже разобраться.)
> > 
> > 
> > win11, firefox dev. edition 118.0b6 64bit, tampermonkey stable, vot1.5.0-beta1
> > Все видео, на которых я тестил, были с общим доступом: Видео 1 (перевод с русского на русский) - https://rutube.ru/video/436d05cf6edf0a0cadf42fd2360774cc/ Видео 2 (перевод с англ. на русский) - https://rutube.ru/video/241adb788c5ab9cc14b67b06b7af84c6/
> 
> Проверил. На рутуб работает только при общем доступе к видео. При доступе по прямой ссылке не работает.

Получается, либо недавно отключили прямые ссылки, либо и раньше не переводило с них

**Comment by ilyhalight** [comment]
Поддержку перевода mail.ru вернули
