### ISSUE TITLE
Кнопки наслаиваются друг на друга (последний edge + voice-over-translation 1.5.0-beta1)

### ISSUE THREAD

**Issue by AvenCores** [ilyhalight/voice-over-translation#323]
![image](https://github.com/ilyhalight/voice-over-translation/assets/64781822/efee9fe3-a162-43f6-8281-a9bca1239aee)

**Comment by OwnerLink** [comment]
Данная кнопка отключается в настройках браузера.

**Comment by ilyhalight** [comment]
Отключите браузерную кнопку "картинка в картинке" и используйте кнопку PiP из расширения
