### ISSUE TITLE
Сколько живет перевод?

### ISSUE THREAD

**Issue by awesomebloging** [ilyhalight/voice-over-translation#325]
Вопрос в том, сколько дней хранится перевод до момента повторной отправки на сервер для перевода? Похоже на что-то около 30 дней. Затем контент переводится заново.
Есть ли способ увеличить этот срок?

**Comment by ilyhalight** [comment]
Ссылка на переведенное аудио - 2 часа
Сам перевод, либо <14 дней, либо в зависимости от того, как часто запрашивают перевод этого видео (точно не могу сказать)


> Есть ли способ увеличить этот срок?

нет
