### ISSUE TITLE
Слайдер меняет громкость английского звука, а не русского (FireFox)

### ISSUE THREAD

**Issue by Shultc** [ilyhalight/voice-over-translation#33]
Слайдер меняет громкость английского видео, а не русского. То есть английский текст всегда на 100%, а русский от 0% до 100%, из-за чего русскую речь практически не слышно.
Проверенно на FireFox 105,0,3 (64-ише)

**Comment by ilyhalight** [comment]
Так и задумано, что слайдер меняет громкость только озвучки. Как мне кажется, так легче настроить необходимую громкость озвучки и самого видео. Чтобы снизить громкость оригинального видео используй слайдер громкости от ютуба
