### ISSUE TITLE
Не переводит в твиттере "no video id found"

### ISSUE THREAD

**Issue by OwnerLink** [ilyhalight/voice-over-translation#331]
![image](https://github.com/ilyhalight/voice-over-translation/assets/76668238/1d3fc076-dedc-4d31-9659-8d969545b6ac)
версия 1,5,0 beta 2 (не cloudflare) но и в релизной то же самое по сути.

**Comment by ilyhalight** [comment]
Можно ссылку на видео? У меня [находит]https://twitter.com/booba/status/1650449856417214464) айдишник, но почему-то яндекс возвращает, что видео не доступно для перевода
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/2f7d447f-45c6-4368-a989-b7ea608e0791)

**Comment by OwnerLink** [comment]
У меня на любом видео так

**Comment by OwnerLink** [comment]
А... Я понял. Видимо какое-то расширение мешает. Просто если в режиме инкогнито оставить только скрипт то все нормально.

Как найду это расширение, сообщу.

**Comment by OwnerLink** [comment]
Как-то так.
![image](https://github.com/ilyhalight/voice-over-translation/assets/76668238/65db4ba6-047b-4c10-8b86-d73e1878401b)

**Comment by OwnerLink** [comment]
Возможно мешает какое-то расширение ибо в режиме инкогнито айди есть. Но факт в том что перевод все еще не доступен.

**Comment by ilyhalight** [comment]
> У меня на любом видео айди не находит. Вот режим инкогнито:
> ![image](https://github.com/ilyhalight/voice-over-translation/assets/76668238/65db4ba6-047b-4c10-8b86-d73e1878401b)
> Возможно мешает одно из расширений айди найти, но перевод что так не доступен что так что эдак.

Возможно, не находит из-за каких-то других расширений. А из-за чего не работает сам перевод хз, может из-за того что Твиттер все больше ограничивает апи и из-за этого у Яндекса что-то сломалось
