### ISSUE TITLE
Не консистентное качество и диалект в переводе для YouTube и TikTok

### ISSUE THREAD

**Issue by miztizm** [ilyhalight/voice-over-translation#337]
При использовании скрипта для перевода видео на TikTok, качество голоса для русского и французского языков оказывается отличным, звучит очень круто. Однако, при переводе видео на YouTube, голос звучит роботизировано и неестественно. Там используется другой tts, не натуральный? 

Кроме того, я столкнулся с проблемой, что французский язык иногда определяется как канадский французский. Как можно настроить скрипт так, чтобы всегда использовался именно французский диалект, а не канадский?

Благодарю

**Comment by SashaXser** [comment]
> При использовании скрипта для перевода видео на TikTok, качество голоса для русского и французского языков оказывается отличным, звучит очень круто. Однако, при переводе видео на YouTube, голос звучит роботизировано и неестественно. Там используется другой tts, не натуральный?
> 
> Кроме того, я столкнулся с проблемой, что французский язык иногда определяется как канадский французский. Как можно настроить скрипт так, чтобы всегда использовался именно французский диалект, а не канадский?
> 
> Благодарю

За эти параметры перевода отвечает сервер Яндекса. Есть идея использовать ISO639-3, вроде как api его понимает, но не все языки из него. TTS и диалект выбирает api самостоятельно, также не исключаю, что сам переводчик был обучен на разных диалектах и получается по разному. Можешь провести эксперимент, залей одно и тоже видео на Ютуб и ТикТок, сравни и отпишись о результатах.
