### ISSUE TITLE
Баг: в хром, отключается перевод после смены разрешения видео.

### ISSUE THREAD

**Issue by LazyOverlordZindarak** [ilyhalight/voice-over-translation#339]
Собственно. Когда работает видео и закадровый перевод, если изменить разрешение картинки, то закадровый перевод отключается и приходится каждый раз включать его при каждом изменении разрешения картинки.

[(48) Rust Crash Course _ Rustlang - YouTube - Google Chrome 2023-09-23 01-00-12.webm](https://github.com/ilyhalight/voice-over-translation/assets/145855248/8812f706-e39b-4b61-9520-2b8ba922cbb5)

**Comment by awesomebloging** [comment]
Есть такой баг.

**Comment by ilyhalight** [comment]
исправлено в 1.5.1.5
