### ISSUE TITLE
Поддержка 9gag, vimeo и т.д

### ISSUE THREAD

**Issue by mynovelhost** [ilyhalight/voice-over-translation#34]
Загрузил дампы из я браузера. Возможно пригодятся для добавления поддержки различных сервисов + иконок/шрифтов/стилей/js для кнопки
[Расшифрованные скрипты из windows версии браузера + ios (ios_button_html.dump, translate_ios_button.js)](https://github.com/ten4dinosaur/YandexDump)

**Comment by Dionis94** [comment]
Здравствуйте. Скажите как добавить код для перевода в ВК. Я очень плохо разбираюсь в компьютерной технике. Помогите пожалуйста!!!

**Comment by Harosatchi** [comment]
Добавьте, пожалуйста, поддержку **Twitter**

**Comment by ilyhalight** [comment]
> Добавьте, пожалуйста, поддержку **Twitter**

Гляну, что там в твиттере, но он, сейчас, не в приоритете

**Comment by TimurKypchak** [comment]
Здравствуйте, подскажите пожалуйста, когда сможете добавить перевод по Юдеми.

**Comment by ilyhalight** [comment]
> Здравствуйте, подскажите пожалуйста, когда сможете добавить перевод по Юдеми.

Точных сроков нету, делаю, когда есть свободное время

**Comment by TimurKypchak** [comment]
Спасибо, за быстрый ответ, сейчас буду качать курс и переводить в яндексе

**Comment by TimurKypchak** [comment]
очень долго и сложно

**Comment by NiCK4048** [comment]
Приветствую, спасибо за такую потрясающую возможность перевода видео в других браузерах.  Хотелось бы видеть новый ресурс banned.video . Если есть возможность добавить, добавьте пожалуйста.

**Comment by ilyhalight** [comment]
> banned.video

Не поддерживается самим переводчиком яндекса

**Comment by Kick4131** [comment]
Возможно ли добавить поддержку видео с cloud.mail.ru по публичной ссылке?

**Comment by sil1vet** [comment]
Привет. А есть возможность добавить перевод видео на мега.nz?

**Comment by ilyhalight** [comment]
> Привет. А есть возможность добавить перевод видео на мега.nz?

нету

**Comment by AbdrAbdr** [comment]
Привет. Есть продвижение по udemy?

**Comment by ilyhalight** [comment]
> Привет. Есть продвижение по udemy?

Буду рад ошибаться, но похоже, что в самом Яндексе перевод Udemy либо:
а) не ушёл дальше тестов и его дальнейшую разработку свернули
б) находится на тех. работах или переработке
в) работает только на каких-то определенных курсах (мало вероятно)
ибо при первой попытке запросить перевод всегда возвращается "Ожидание перевода", а далее идет ошибка "Возникла ошибка, попробуйте позже". 

Насчёт Coursera, то, его отключили (или вообще не подключали):
![изображение](https://user-images.githubusercontent.com/62353659/232309496-fb2ac285-cc81-41f4-8da2-c415004c3136.png)

**Comment by ilyhalight** [comment]
> Загрузил дампы из я браузера. Возможно пригодятся для добавления поддержки различных сервисов + иконок/шрифтов/стилей/js для кнопки
> [Расшифрованные скрипты из windows версии браузера + ios (ios_button_html.dump, translate_ios_button.js)](https://github.com/ten4dinosaur/YandexDump)

Наверное, уже немного поздновато спрашивать, но как можно расшифровать данные скрипты самостоятельно?

**Comment by Privetyanikita** [comment]
добавьте поддержку Udemy

**Comment by dlt5** [comment]
Возможно ли добавить dailymotion?

**Comment by ilyhalight** [comment]
> Возможно ли добавить dailymotion?

Не поддерживается.

**Comment by DragonSigh** [comment]
Добавьте https://www.coursera.org/ в Я.Браузере работает.

**Comment by ilyhalight** [comment]
> Добавьте https://www.coursera.org/ в Я.Браузере работает.

Появится, если разберусь с передачей массивов через protobufjs

**Comment by ilyhalight** [comment]
> > Добавьте https://www.coursera.org/ в Я.Браузере работает.
> 
> Появится, если разберусь с передачей массивов через protobufjs

Появится в следующем релизе 1.4.1 (будет доступно с выходом 1.4.1-beta5)

**Comment by ilyhalight** [comment]
> Привет. Есть продвижение по udemy?

> добавьте поддержку Udemy

Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5

**Comment by Harosatchi** [comment]
loom.com возможно добавить?

**Comment by ilyhalight** [comment]
> loom.com возможно добавить?

Не поддерживается

**Comment by x3d05** [comment]
> > Привет. Есть продвижение по udemy?
> 
> > добавьте поддержку Udemy
> 
> Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5

после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.

![Screen Shot 2023-09-13 at 15 49 09](https://github.com/ilyhalight/voice-over-translation/assets/88771080/f9957895-8492-4bae-bee0-8cf84a5e0f1b)

**Comment by ilyhalight** [comment]
> > > Привет. Есть продвижение по udemy?
> > 
> > 
> > > добавьте поддержку Udemy
> > 
> > 
> > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> 
> после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> 
> P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> 
> ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)

Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса

**Comment by ilyhalight** [comment]
> > > > Привет. Есть продвижение по udemy?
> > > 
> > > 
> > > > добавьте поддержку Udemy
> > > 
> > > 
> > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > 
> > 
> > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> 
> Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса

Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена

**Comment by x3d05** [comment]
> > > > > Привет. Есть продвижение по udemy?
> > > > 
> > > > 
> > > > > добавьте поддержку Udemy
> > > > 
> > > > 
> > > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > > 
> > > 
> > > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> > 
> > 
> > Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса
> 
> Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена

Перепроверил с токеном - не помогло.

Проверил на 6 разных курсах от разных авторов (везде есть субтитры), - не работает нигде :(

<img width="704" alt="Screen Shot 2023-09-13 at 21 05 20" src="https://github.com/ilyhalight/voice-over-translation/assets/88771080/ea380afa-943b-4f01-b145-897c93c0813d">

Ошибки в консоли только такие
<img width="1267" alt="Screen Shot 2023-09-13 at 21 07 24" src="https://github.com/ilyhalight/voice-over-translation/assets/88771080/5e1305c4-05d2-4bf1-b7fc-6bb76c2d0cd0">

Перепроверил в indexedDB токен есть

<img width="192" alt="Screen Shot 2023-09-13 at 21 08 13" src="https://github.com/ilyhalight/voice-over-translation/assets/88771080/9534c362-f05d-4ed1-8666-49eed19f1e50">

**Comment by ilyhalight** [comment]
> > > > > > Привет. Есть продвижение по udemy?
> > > > > 
> > > > > 
> > > > > > добавьте поддержку Udemy
> > > > > 
> > > > > 
> > > > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > > > 
> > > > 
> > > > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > > > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > > > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> > > 
> > > 
> > > Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса
> > 
> > 
> > Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена
> 
> Перепроверил с токеном - не помогло.
> 
> Проверил на 6 разных курсах от разных авторов (везде есть субтитры), - не работает нигде :(
> <img alt="Screen Shot 2023-09-13 at 21 05 20" width="704" src="https://user-images.githubusercontent.com/88771080/267681314-ea380afa-943b-4f01-b145-897c93c0813d.png">
> 
> Ошибки в консоли только такие <img alt="Screen Shot 2023-09-13 at 21 07 24" width="1267" src="https://user-images.githubusercontent.com/88771080/267681648-5e1305c4-05d2-4bf1-b7fc-6bb76c2d0cd0.png">
> 
> Перепроверил в indexedDB токен есть
> <img alt="Screen Shot 2023-09-13 at 21 08 13" width="192" src="https://user-images.githubusercontent.com/88771080/267681908-9534c362-f05d-4ed1-8666-49eed19f1e50.png">

Попробуйте поставить [эту версию](https://drive.google.com/drive/folders/17bOcQ6-Zt843Vzb-LPhcErcaJeRJF_hl?usp=sharing) (выберите один из файлов в зависимости от текущей версии). В ней включены дебаг логи и будет понятно на каком именно моменте что-то идет не так.  Ибо у меня вроде бы всё нормально работает

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/fc59559d-c621-4fdd-84c7-5c5df0173e3f)

**Comment by x3d05** [comment]
> > > > > > > Привет. Есть продвижение по udemy?
> > > > > > 
> > > > > > 
> > > > > > > добавьте поддержку Udemy
> > > > > > 
> > > > > > 
> > > > > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > > > > 
> > > > > 
> > > > > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > > > > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > > > > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> > > > 
> > > > 
> > > > Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса
> > > 
> > > 
> > > Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена
> > 
> > 
> > Перепроверил с токеном - не помогло.
> > Проверил на 6 разных курсах от разных авторов (везде есть субтитры), - не работает нигде :(
> > <img alt="Screen Shot 2023-09-13 at 21 05 20" width="704" src="https://user-images.githubusercontent.com/88771080/267681314-ea380afa-943b-4f01-b145-897c93c0813d.png">
> > Ошибки в консоли только такие <img alt="Screen Shot 2023-09-13 at 21 07 24" width="1267" src="https://user-images.githubusercontent.com/88771080/267681648-5e1305c4-05d2-4bf1-b7fc-6bb76c2d0cd0.png">
> > Перепроверил в indexedDB токен есть
> > <img alt="Screen Shot 2023-09-13 at 21 08 13" width="192" src="https://user-images.githubusercontent.com/88771080/267681908-9534c362-f05d-4ed1-8666-49eed19f1e50.png">
> 
> Попробуйте поставить [эту версию](https://drive.google.com/drive/folders/17bOcQ6-Zt843Vzb-LPhcErcaJeRJF_hl?usp=sharing) (выберите один из файлов в зависимости от текущей версии). В ней включены дебаг логи и будет понятно на каком именно моменте что-то идет не так. Ибо у меня вроде бы всё нормально работает
> 
> ![image](https://user-images.githubusercontent.com/62353659/267685723-fc59559d-c621-4fdd-84c7-5c5df0173e3f.png)

Поставил вашу версию. Ошибки те же.

<img width="1261" alt="Screen Shot 2023-09-13 at 21 34 52" src="https://github.com/ilyhalight/voice-over-translation/assets/88771080/a1f342f7-030c-481c-8a35-fd846c95cce2">

на верхнем скрине вроде все как и у вас. на нижнем ошибка

<img width="1278" alt="Screen Shot 2023-09-13 at 21 35 01" src="https://github.com/ilyhalight/voice-over-translation/assets/88771080/8265af9a-38d9-455a-acf0-a7126547d317">

**Comment by x3d05** [comment]
> > > > > > > > Привет. Есть продвижение по udemy?
> > > > > > > 
> > > > > > > 
> > > > > > > > добавьте поддержку Udemy
> > > > > > > 
> > > > > > > 
> > > > > > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > > > > > 
> > > > > > 
> > > > > > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > > > > > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > > > > > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> > > > > 
> > > > > 
> > > > > Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса
> > > > 
> > > > 
> > > > Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена
> > > 
> > > 
> > > Перепроверил с токеном - не помогло.
> > > Проверил на 6 разных курсах от разных авторов (везде есть субтитры), - не работает нигде :(
> > > <img alt="Screen Shot 2023-09-13 at 21 05 20" width="704" src="https://user-images.githubusercontent.com/88771080/267681314-ea380afa-943b-4f01-b145-897c93c0813d.png">
> > > Ошибки в консоли только такие <img alt="Screen Shot 2023-09-13 at 21 07 24" width="1267" src="https://user-images.githubusercontent.com/88771080/267681648-5e1305c4-05d2-4bf1-b7fc-6bb76c2d0cd0.png">
> > > Перепроверил в indexedDB токен есть
> > > <img alt="Screen Shot 2023-09-13 at 21 08 13" width="192" src="https://user-images.githubusercontent.com/88771080/267681908-9534c362-f05d-4ed1-8666-49eed19f1e50.png">
> > 
> > 
> > Попробуйте поставить [эту версию](https://drive.google.com/drive/folders/17bOcQ6-Zt843Vzb-LPhcErcaJeRJF_hl?usp=sharing) (выберите один из файлов в зависимости от текущей версии). В ней включены дебаг логи и будет понятно на каком именно моменте что-то идет не так. Ибо у меня вроде бы всё нормально работает
> > ![image](https://user-images.githubusercontent.com/62353659/267685723-fc59559d-c621-4fdd-84c7-5c5df0173e3f.png)
> 
> Поставил вашу версию. Ошибки те же.
> <img alt="Screen Shot 2023-09-13 at 21 34 52" width="1261" src="https://user-images.githubusercontent.com/88771080/267690460-a1f342f7-030c-481c-8a35-fd846c95cce2.png">
> 
> на верхнем скрине вроде все как и у вас. на нижнем ошибка
> <img alt="Screen Shot 2023-09-13 at 21 35 01" width="1278" src="https://user-images.githubusercontent.com/88771080/267690564-8265af9a-38d9-455a-acf0-a7126547d317.png">

Заметил, что у меня VideoURL - undefined, а у вас ссылка прямая, почему так может быть?

**Comment by ilyhalight** [comment]
> > > > > > > > > Привет. Есть продвижение по udemy?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > > добавьте поддержку Udemy
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Появится в следующем релизе 1.4.1. Уже доступно для использования в 1.4.1-beta5
> > > > > > > 
> > > > > > > 
> > > > > > > после всех манипуляций с токеном (по вики), не работает udemy, хотя токен в indexedDB есть.
> > > > > > > P.S пробовал - 1.4.1-beta5, 1.4.1-beta6, 1.4.1-beta7
> > > > > > > ![Screen Shot 2023-09-13 at 15 49 09](https://user-images.githubusercontent.com/88771080/267593975-f9957895-8492-4bae-bee0-8cf84a5e0f1b.png)
> > > > > > 
> > > > > > 
> > > > > > Не все курсы поддерживаются. На некоторых курсах нету субтитров и из-за этого перевод не возможен. Откройте консоль и посмотрите есть ли какие-то дополнительные ошибки. Если нету, то скорее всего, это из-за того, что не удалось найти субтитры для курса
> > > > > 
> > > > > 
> > > > > Еще можете попробовать перезаписать токен (ввести тот же токен заново), если поможет, то скорее всего, я допустил какую-то ошибку со временем жизни токена
> > > > 
> > > > 
> > > > Перепроверил с токеном - не помогло.
> > > > Проверил на 6 разных курсах от разных авторов (везде есть субтитры), - не работает нигде :(
> > > > <img alt="Screen Shot 2023-09-13 at 21 05 20" width="704" src="https://user-images.githubusercontent.com/88771080/267681314-ea380afa-943b-4f01-b145-897c93c0813d.png">
> > > > Ошибки в консоли только такие <img alt="Screen Shot 2023-09-13 at 21 07 24" width="1267" src="https://user-images.githubusercontent.com/88771080/267681648-5e1305c4-05d2-4bf1-b7fc-6bb76c2d0cd0.png">
> > > > Перепроверил в indexedDB токен есть
> > > > <img alt="Screen Shot 2023-09-13 at 21 08 13" width="192" src="https://user-images.githubusercontent.com/88771080/267681908-9534c362-f05d-4ed1-8666-49eed19f1e50.png">
> > > 
> > > 
> > > Попробуйте поставить [эту версию](https://drive.google.com/drive/folders/17bOcQ6-Zt843Vzb-LPhcErcaJeRJF_hl?usp=sharing) (выберите один из файлов в зависимости от текущей версии). В ней включены дебаг логи и будет понятно на каком именно моменте что-то идет не так. Ибо у меня вроде бы всё нормально работает
> > > ![image](https://user-images.githubusercontent.com/62353659/267685723-fc59559d-c621-4fdd-84c7-5c5df0173e3f.png)
> > 
> > 
> > Поставил вашу версию. Ошибки те же.
> > <img alt="Screen Shot 2023-09-13 at 21 34 52" width="1261" src="https://user-images.githubusercontent.com/88771080/267690460-a1f342f7-030c-481c-8a35-fd846c95cce2.png">
> > на верхнем скрине вроде все как и у вас. на нижнем ошибка
> > <img alt="Screen Shot 2023-09-13 at 21 35 01" width="1278" src="https://user-images.githubusercontent.com/88771080/267690564-8265af9a-38d9-455a-acf0-a7126547d317.png">
> 
> Заметил, что у меня VideoURL - undefined, а у вас ссылка прямая, почему так может быть?

API Udemy не вернуло ссылку на видео. Можете скинуть ссылку на курс? Проверю потом

**Comment by x3d05** [comment]
https://www.udemy.com/course/learn-the-wave-principle/

я пробовал на разных курсах

**Comment by ilyhalight** [comment]
> https://www.udemy.com/course/learn-the-wave-principle/
> 
> я пробовал на разных курсах

Возможно, исправил. Попробуй эту версию. Еще поправил жизнь токена, как и думал с ней тоже косяк был и он жил 45 минут, а не 30 дней.
https://drive.google.com/drive/folders/1L5B712_aisjwxVcb5lkBH4Y7wQ1k_DbF?usp=sharing

**Comment by x3d05** [comment]
> > https://www.udemy.com/course/learn-the-wave-principle/
> > я пробовал на разных курсах
> 
> Возможно, исправил. Попробуй эту версию. Еще поправил жизнь токена, как и думал с ней тоже косяк был и он жил 45 минут, а не 30 дней. https://drive.google.com/drive/folders/1L5B712_aisjwxVcb5lkBH4Y7wQ1k_DbF?usp=sharing

Да, спасибо! Эта версия помогла! Теперь работает отлично. 

Еще вопрос: плагин поддерживает my.mail.ru? но не работает на cloud.mail.ru верно? Насколько сложно допилить плагин, чтобы из облака плееры тоже поддерживали перевод? Еще раз спасибо!

**Comment by DragonSigh** [comment]
Кнопка на Coursera появилась, но при нажатии по любому видео такое сообщение:

![2023-09-16_14-49-13](https://github.com/ilyhalight/voice-over-translation/assets/1637230/6b811175-d41e-4d53-8b84-29c26700cfe6)

В самом Яндекс Браузере работает.
