### ISSUE TITLE
Поддержка masterclass.com

### ISSUE THREAD

**Issue by bolkonskiy** [ilyhalight/voice-over-translation#345]
Привет!

Спасибо за ваше расширение! Предлагаю добавить поддержку сайта masterclass.com. Оч много полезного обучающего контента :) Думаю, многим будет полезно.

Спасибо!

**Comment by ilyhalight** [comment]
Вероятнее всего, яндекс не поддерживает полностью платные сервисы. Проверить не могу.

**Comment by bolkonskiy** [comment]
А если я предоставлю вам креды на сайт, можно ли  попробовать проверить?

**Comment by ilyhalight** [comment]
Полностью платные сайты, пока не в ходят в планы. Пока закрою
