### ISSUE TITLE
Нету кнопки на определенном видео

### ISSUE THREAD

**Issue by LeonINFIZ** [ilyhalight/voice-over-translation#346]
Почему-то не появляется кнопка именно на этом видео: https://www.youtube.com/watch?v=RPabOxxy8WY.
![image](https://github.com/ilyhalight/voice-over-translation/assets/63362730/bfc2494e-dea4-4ed1-9297-4819ff6727ea)

**Comment by KozinV** [comment]
и тут тоже https://www.youtube.com/watch?v=sQOHhoCSfak

**Comment by ilyhalight** [comment]
В бета версии такой проблемы уже нету

**Comment by KozinV** [comment]
> и тут тоже [youtube.com/watch?v=sQOHhoCSfak](https://www.youtube.com/watch?v=sQOHhoCSfak)
> 
> Firefox 118.0 (64-разрядный)

Firefox обновился на 118.0.1 и всё заработало как было задумано. СПС!
