### ISSUE TITLE
Доступные языки

### ISSUE THREAD

**Issue by andrinko** [ilyhalight/voice-over-translation#347]
Будет ли расширение пакета доступных языков для перевода?

**Comment by SashaXser** [comment]
> Будет ли расширение пакета доступных языков для перевода?

Возможно, какие ещё языки нужны? Язык Кукарача? Старомонгольский? Кадубхаше?

**Comment by LazyOverlordZindarak** [comment]
> > Будет ли расширение пакета доступных языков для перевода?
> 
> Возможно, какие ещё языки нужны? Язык Кукарача? Старомонгольский? Кадубхаше?

Он говорит о языках, доступных для перевода. То есть, о списке слева, а не справа. Я уже впечатлён переводом с 12 языков. И фактически 90% времени я смотрю видео на английском.

Вот топ 10 языков видео на ютубе:

1 - English - 52% - United States, United Kingdom, Canada
2 - Spanish - 11% - Mexico, Spain, Argentina
3 - Portuguese - 8% - Brazil, Portugal, Angola
4 - Russian - 4% - Russia, Ukraine, Kazakhstan
5 - Arabic - 3.5% - Egypt, Saudi Arabia, Algeria
6 - Malay - 3% - Malaysia, Indonesia, Brunei
7 - French - 2.5% - France, Canada (Quebec), Belgium (Wallonia)
8 - German - 2.5% - Germany, Austria, Switzerland
9 - Japanese - 2% - Japan
10 - Chinese - 2% - China, Taiwan, Singapore

Сейчас нет перевода с Португальского (3 место) и Малайского (6).

К сожалению, я не смог найти топ 20 популярных языков видосов ютуба. К примеру, Индонезийский довольно популярен, но я не знаю точную статистику.

Популярность языков по миру:

Арабский – 274 миллионов 
Бенгальский – 265 миллионов 
Русский – 258 миллионов 
Португальский – 234 миллионов 
Индонезийский – 199 миллионов 
Урду – 170 миллионов 
Немецкий – 132 миллионов 
Японский – 128 миллионов 
Суахили – 98 миллионов 
Маратхи – 95 миллионов 
Телугу – 93 миллионов 
Западный панджаби – 93 миллионов У диалект китайского – 82 миллионов Тамильский – 81 миллион Турецкий – 80 миллионов

**Comment by SashaXser** [comment]
> > > Будет ли расширение пакета доступных языков для перевода?
> > 
> > 
> > Возможно, какие ещё языки нужны? Язык Кукарача? Старомонгольский? Кадубхаше?
> 
> Он говорит о языках, доступных для перевода. То есть, о списке слева, а не справа. Я уже впечатлён переводом с 12 языков. И фактически 90% времени я смотрю видео на английском.
> 
> Вот топ 10 языков видео на ютубе:
> 
> 1 - English - 52% - United States, United Kingdom, Canada 2 - Spanish - 11% - Mexico, Spain, Argentina 3 - Portuguese - 8% - Brazil, Portugal, Angola 4 - Russian - 4% - Russia, Ukraine, Kazakhstan 5 - Arabic - 3.5% - Egypt, Saudi Arabia, Algeria 6 - Malay - 3% - Malaysia, Indonesia, Brunei 7 - French - 2.5% - France, Canada (Quebec), Belgium (Wallonia) 8 - German - 2.5% - Germany, Austria, Switzerland 9 - Japanese - 2% - Japan 10 - Chinese - 2% - China, Taiwan, Singapore
> 
> Сейчас нет перевода с Португальского (3 место) и Малайского (6).
> 
> К сожалению, я не смог найти топ 20 популярных языков видосов ютуба. К примеру, Индонезийский и Хинди тоже относительно популярны в видео, но я не знаю точную статистику.
> 
> Популярность языков по миру:
> 
>     * Английский
> 
>     * Китайский
> 
> 
> Хинди
> 
>     * Испанский
> 
>     * Французский
> 
>     * Арабский – 274 миллионов
> 
> 
> Бенгальский – 265 миллионов
> 
>     * Русский – 258 миллионов
> 
> 
> Португальский – 234 миллионов
> 
> Индонезийский – 199 миллионов
> 
> Урду – 170 миллионов
> 
>     * Немецкий – 132 миллионов
> 
>     * Японский – 128 миллионов
> 
> 
> Суахили – 98 миллионов
> 
> Маратхи – 95 миллионов
> 
> Телугу – 93 миллионов
> 
> Западный панджаби – 93 миллионов
> 
> У диалект китайского – 82 миллионов
> 
> Тамильский – 81 миллион
> 
>     * Турецкий – 80 миллионов
> 
> 
> Я думаю, что не удастся сильно расширить список переводимых языков. Мне кажется, что это сильно сложнее, чем "список языков на которые можно переводить".
> 
> Но выглядит очень странно, что упущен перевод с Португальского. Он довольно популярен в мире и он на 3-ем месте по количеству видео на ютубе.

Всё зависит от Яндекса, он даже пока Английски полноценно не вывозит. Слишком сильно страдает перевод из-за кривой реализации системы контекста.

**Comment by LazyOverlordZindarak** [comment]
> Всё зависит от Яндекса, он даже пока Английский полноценно не вывозит. Слишком сильно страдает перевод из-за кривой реализации системы контекста.

Ну, примерно так и предполагал.

> Я думаю, что не удастся сильно расширить список переводимых языков. Мне кажется, что это сильно сложнее, чем "список языков на которые можно переводить".

**Comment by ilyhalight** [comment]
> Популярность языков по миру:
> 
>     * Английский
> 
>     * Китайский
> 
> 
> Хинди
> 
>     * Испанский
> 
>     * Французский
> 
>     * Арабский – 274 миллионов
> 
> 
> Бенгальский – 265 миллионов
> 
>     * Русский – 258 миллионов
> 
> 
> Португальский – 234 миллионов
> 
> Индонезийский – 199 миллионов
> 
> Урду – 170 миллионов
> 
>     * Немецкий – 132 миллионов
> 
>     * Японский – 128 миллионов
> 
> 
> Суахили – 98 миллионов
> 
> Маратхи – 95 миллионов
> 
> Телугу – 93 миллионов
> 
> Западный панджаби – 93 миллионов
> 
> У диалект китайского – 82 миллионов
> 
> Тамильский – 81 миллион
> 
>     * Турецкий – 80 миллионов


Как уже сказали выше, тут всё зависит от Яндекса. Оффициально еще даже 1/3 из тех 12 языков, которые есть сейчас не поддерживаются.

Если интересно, то можете посмотреть [статистику](https://github.com/ilyhalight/voice-over-translation/blob/master/LANG_SUPPORT.md) по протестированным языкам (примерно за начало сентября)
