### ISSUE TITLE
Странное событие с ilyhalight/VOT и нативным аудио переводом самого ЯБраузера

### ISSUE THREAD

**Issue by LazyOverlordZindarak** [ilyhalight/voice-over-translation#348]
Я попробовал посмотреть это видео в хроме с переводом. https://www.youtube.com/watch?v=SkMQStnqCZ0

Расширение VOT не смогло перевести его. К сожалению, я не запомнил что именно оно сказало. Что-то вроде "ошибка перевода". Я открыл то же самое видео в Ябраузере. Аудио переводчик Ябраузера тоже сказал что-то вроде "ошибка перевода". Я перезагружал страницу. А переводчик Ябраузера говорил что-то вроде "видео недоступно для перевода". После этого VOT в хроме, вроде бы, тоже стал говорить "видео недоступно для перевода".

Но я заметил, что в Ябраузере сообщение о недоступности перевода появляется сразу при открытии страницы. А в хроме кнопка сначала белая, и говорит о недоступности перевода видео только если на неё нажать. И я предположил, что возможно проблема в том, что чел в видео говорит слишком быстро.

Поэтому, я попробовал открыть новую страницу в хром. Выставил скорость видео на 0,9. И о чудо. VOT в хроме принял видео на перевод. Когда перевод завершился, всё нормально воспроизводится. И после этого, переведённое видео стало доступно и в Ябраузере.

Теперь вопрос - что это, блин, было? Просто совпадение? Или реально, изменение скорости видео в хроме помогло? Теперь мне очень жаль, что я не записал это странное событие на видео, а мои описания не очень то точны.

**Comment by LazyOverlordZindarak** [comment]
[https://www.youtube.com/watch?v=SkMQStnqCZ0&t=57m54s](url)
О, оно может материться. Забавно)

**Comment by ilyhalight** [comment]
Очень странно, никогда такого не видел, обычно, даже, если речь в видео очень быстрая, то все равно переводит.

Сейчас, тоже, решил попробовал перевести [такое видео](https://www.youtube.com/watch?v=XbGs_qK2PQA&t=2s) с быстрым аудио, и получилось, так, что на английском перевод не работал (возникла ошибка при переводе). После я попробовал перевести с другого языка и видео перевелось. После я снова попробовал перевести это видео с английского и перевод с английского заработал ¯\_(ツ)_/¯

**Comment by ilyhalight** [comment]
> Очень странно, никогда такого не видел, обычно, даже, если речь в видео очень быстрая, то все равно переводит.
> 
> Сейчас, тоже, решил попробовал перевести [такое видео](https://www.youtube.com/watch?v=XbGs_qK2PQA&t=2s) с быстрым аудио, и получилось, так, что на английском перевод не работал (возникла ошибка при переводе). После я попробовал перевести с другого языка и видео перевелось. После я снова попробовал перевести это видео с английского и перевод с английского заработал ¯_(ツ)_/¯

К слову, изменять скорость пробовал, но у меня это не сработало, да и вроде ютуб не сохраняет скорость при передаче ссылки
