### ISSUE TITLE
Не откликается

### ISSUE THREAD

**Issue by Act0r1** [ilyhalight/voice-over-translation#349]
![image](https://github.com/ilyhalight/voice-over-translation/assets/59477383/51c840c2-1c47-46b7-82cd-29354547db23)
Я хочу изменить язык, но ничего не меняется. Также выходит ошибка - VOTLocalizedError: You have disabled the translation of the video in your language

**Comment by SashaXser** [comment]
> ![image](https://user-images.githubusercontent.com/59477383/271932570-51c840c2-1c47-46b7-82cd-29354547db23.png) Я хочу изменить язык, но ничего не меняется. Также выходит ошибка - VOTLocalizedError: You have disabled the translation of the video in your language

Скачай бету и проверь осталась ли проблема или нет

**Comment by ilyhalight** [comment]
> You have disabled the translation of the video in your language

Отключи Do not translate from my language

**Comment by Act0r1** [comment]
> > You have disabled the translation of the video in your language
> 
> Отключи Do not translate from my language

Но я все равно не могу менять язык, то есть там стоит с англ на англ:(

**Comment by SashaXser** [comment]
> > > You have disabled the translation of the video in your language
> > 
> > 
> > Отключи Do not translate from my language
> 
> Но я все равно не могу менять язык, то есть там стоит с англ на англ:(

Ты в меню не можешь нажать на свой язык?
Он справа если что. Меняешь и он сохраняется.

**Comment by ilyhalight** [comment]
Проблема еще актуальна в бета версии?

**Comment by Almaz** [comment]
> > You have disabled the translation of the video in your language
> 
> Отключи Do not translate from my language

Подскажите, пожалуйста, как отключается эта опция?

**Comment by ilyhalight** [comment]
> Подскажите, пожалуйста, как отключается эта опция?

Открываете меню расширения -> Снимаете галочку "Не переводить с родного языка"
![firefox_O9S8w82u5q](https://github.com/user-attachments/assets/b2e0ecb5-f1c0-432f-9237-15a693fa151b)
