### ISSUE TITLE
Нажатие на кнопку обрабатывается несколько раз

### ISSUE THREAD

**Issue by ftoh** [ilyhalight/voice-over-translation#35]
При переходе с одного видео на другое, на кнопку вешается несколько обработчиков. Нажатие приводит сразу к нескольким запросам.
Chrome, Tampermonkey, Версия скрипта: 1.0.8
![image](https://user-images.githubusercontent.com/5018813/195284085-26c59674-08d4-47a0-8f9f-b13a98094b4e.png)

**Comment by mynovelhost** [comment]
Добавлю, если кликнуть на кнопку, и ответ сервера будет 'Перевод займет около минуты', то выполнится этот код

`if (urlOrError === 'Перевод займет около минуты') {`
`        setTimeout(() => {`
`          translateYTFunc(VIDEO_ID);`
`        }, 70000)`
`      }`

Если кликнуть на кнопку еще n раз, то setTimeout выполнится еще n раз. Как результат - n запросов на сервер.
