### ISSUE TITLE
Оффлайн перевод

### ISSUE THREAD

**Issue by baxenko** [ilyhalight/voice-over-translation#350]
Возможно ли сделать так, чтобы можно было переводить оффлайн видео (файл на компьютере) и сохранить его уже с переводом?

или

Когда приоисходит перевод видео на youtube загрузить видео с переведенной аудио дорожкой? 

Спасибо.

**Comment by SashaXser** [comment]
> Возможно ли сделать так, чтобы можно было переводить оффлайн видео (файл на компьютере) и сохранить его уже с переводом?

И как ты себе это представляешь?

**Comment by baxenko** [comment]
Я не разрабочтик, потому спосил о такой возможности. Представить что угодно могу:
1. Плагин к VLC, который наложит перевод и даст сохранить готовое видео
2. Плагин для Chrome который ускорит видео (допустим в x10), а потом сохранит без ускорения x10
3. Плагин для расширения Chrome который умеет загружать видео с YouTube и чтобы можно было прикрутить туда перевод.


А то получается так, что чтобы перевести видео. Нужно:
1. Загрузить его на YouTube
2. Включить перевод
3. Включить OBS (запись экрана)
4. Дождаться пока пройдет видео с переводом (три часа)
5. Остановить запись

**Comment by SashaXser** [comment]
> Я не разрабочтик, потому спосил о такой возможности. Представить что угодно могу:
> 
>     1. Плагин к VLC, который наложит перевод и даст сохранить готовое видео
> 
>     2. Плагин для Chrome который ускорит видео (допустим в x10), а потом сохранит без ускорения x10
> 
>     3. Плагин для расширения Chrome который умеет загружать видео с YouTube и чтобы можно было прикрутить туда перевод.
> 
> 
> А то получается так, что чтобы перевести видео. Нужно:
> 
>     1. Загрузить его на YouTube
> 
>     2. Включить перевод
> 
>     3. Включить OBS (запись экрана)
> 
>     4. Дождаться пока пройдет видео с переводом (три часа)
> 
>     5. Остановить запись

Ну ты всегда можешь залить видео на ютуб, а после скачать переведенную аудиодорожку.
Просто оффлайн пока не получается, нужно загружать его куда-нибудь.

**Comment by baxenko** [comment]
> а после скачать переводную аудиодорожку

Как єто сделать? Потому что когда я загружаюсь видео через сторонее ПО (к примеру Downie) он "не видит" переведенную дорожку. Только те что в оригинале видео на YouTube.

Может есть аналогичное ПО\сервисы которые "под ключ" переводят видео (хотя бы субтитры) Ибо те, что я изучал, типа veed.io, для длинных видео стоят золотых гор.

Спасибо.

**Comment by SashaXser** [comment]
> > а после скачать переводную аудиодорожку
> 
> Как єто сделать? Потому что когда я загружаюсь видео через сторонее ПО (к примеру Downie) он "не видит" переведенную дорожку. Только те что в оригинале видео на YouTube.
> 
> Может есть аналогичное ПО\сервисы которые "под ключ" переводят видео (хотя бы субтитры) Ибо те, что я изучал, типа veed.io, для длинных видео стоят золотых гор.
> 
> Спасибо.

Я вот немного не понимаю, ты устанавливал voice-over-translation в браузере? 
Если не хочешь скачивать аудиодорожку с помощью этого способа, то можно скачать её через [vot-cli](https://github.com/FOSWLY/vot-cli). 
Если не скачивается, то включи VPN.
Насчет локальных файлов уже ответили тут: #310

**Comment by baxenko** [comment]
> Я вот немного не понимаю, ты установил озвучку в браузере?
Да. А где я ее еще могу установить? 

> можно скачать ее через [вот-cli](https://github.com/FOSWLY/vot-cli)
Вот за это спасибо!

**Comment by FiLinX** [comment]
> Я вот немного не понимаю, ты устанавливал voice-over-translation в браузере?

мало вообще кто видит ту кнопку со стрелкой для скачивания аудиодороги перевода)
отсюда и незнание что такой функционал уже есть..
возможно надо как-то её вынести за панель при получении.. чтоб сразу в глаза бросалось)  где нить справа от троеточия иль ещё как..

но самое лучшее - это спрятать под этой кнопкой уже готовый батник в котором прописана команда для yt-dlp на скачивание и аудиодороги перевода и сразу и ролика в 22 формате + склейка их в один файл..
людям надо только предварительно сцылку дать на yt-dlp для его скачки и размещения например в юзер-дате браузера чтоб в батнике для всех единым путём прописано було

блин, не, не пойдёт..  yt-dlp наверняка не поддерживает хосты всех этих курсо-обучалок

**Comment by baxenko** [comment]
> мало вообще кто видит ту кнопку со стрелкой для скачивания аудиодороги перевода - на ней же не подписано ничего)
Боже! Действительно все намного проще, я не замечал эту кнопку загрузки.

Тогда просто загружаю готовый .mp3 с переводом и с помощью стороннего ПО заменяю звуковую дорожку. Спасибо!

**Comment by ilyhalight** [comment]
> > Я вот немного не понимаю, ты устанавливал voice-over-translation в браузере?
> 
> мало вообще кто видит ту кнопку со стрелкой для скачивания аудиодороги перевода - на ней же не подписано ничего) отсюда и незнание что такой функционал уже есть.. возможно надо как-то её вынести за панель при получении.. чтоб сразу в глаза бросалось) где нить справа от троеточия иль ещё как..
> 
> но самое лучшее - это спрятать под этой кнопкой уже готовый батник в котором прописана команда для yt-dlp на скачивание и аудиодороги перевода и сразу и ролика в 22 формате + склейка их в один файл.. людям надо только предварительно сцылку дать на yt-dlp для его скачки и размещения например в юзер-дате браузера чтоб в батнике для всех единым путём прописано було
> 
> блин, не, не пойдёт.. yt-dlp наверняка не поддерживает хосты всех этих курсо-обучалок

Все сайты, которые есть в расширение, кроме coursera, yt-dlp поддерживает. Но мне кажется всё равно что-то универсальное так не сделаешь - кому-то может нужна только аудио дорожка, кому-то другое качество или еще что-то
