### ISSUE TITLE
Можно ли скачать сгенерированные субтитры на локальный компьютер?

### ISSUE THREAD

**Issue by smallwhitedesu** [ilyhalight/voice-over-translation#352]
Эта функция может быть реализована?
Для начинающих изучать русский язык, эта функция довольно полезна. Поэтому хотелось бы узнать.

**Comment by ilyhalight** [comment]
Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню

**Comment by smallwhitedesu** [comment]
> Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню

Загрузка через консоль браузера...? Я не совсем понимаю, как скачивать через консоль... У вас есть подробная инструкция по этому процессу

Если это не доставит вам хлопот, я могу подождать, пока вы добавите кнопку для скачивания субтитров в меню.

**Comment by ilyhalight** [comment]
> > Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню
> 
> Загрузка через консоль браузера...? Я не совсем понимаю, как скачивать через консоль... У вас есть подробная инструкция по этому процессу
> 
> Если это не доставит вам хлопот, я могу подождать, пока вы добавите кнопку для скачивания субтитров в меню.

Чтобы скачать нужно найти вот такую строчку. В ней найти нужный язык (поле `language` - обозначает язык субтитров). Для загрузки нужно перейти по ссылки
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/0f7b724f-beac-4bdc-9e70-573553f7031b)

**Comment by ilyhalight** [comment]
Добавил в бета версию

**Comment by smallwhitedesu** [comment]
> > > Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню
> > 
> > 
> > Загрузка через консоль браузера...? Я не совсем понимаю, как скачивать через консоль... У вас есть подробная инструкция по этому процессу
> > Если это не доставит вам хлопот, я могу подождать, пока вы добавите кнопку для скачивания субтитров в меню.
> 
> Чтобы скачать нужно найти вот такую строчку. В ней найти нужный язык (поле `language` - обозначает язык субтитров). Для загрузки нужно перейти по ссылки ![image](https://user-images.githubusercontent.com/62353659/273305532-0f7b724f-beac-4bdc-9e70-573553f7031b.png)

Новый вопрос.

Похоже, что скачанный файл с субтитрами нельзя использовать напрямую.
Как преобразовать скачанный файл с субтитрами в рабочий формат?

[https://brosubs.s3-private.mds.yandex.net/vtrans/e411ee18-1c54-4f4a-a965-aa78572557d5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=H9BHBAsxYbYIu9W7T8KG%2F20231007%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231007T151624Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=c1f7dd4a2877237980989354d7b6bbd3e520689268c8791e662acc325f088441
](url)
![20231007233905](https://github.com/ilyhalight/voice-over-translation/assets/103359343/aa4f7bd1-f8c1-4226-85d7-4230c8f6c4eb)

**Comment by ilyhalight** [comment]
> > > > Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню
> > > 
> > > 
> > > Загрузка через консоль браузера...? Я не совсем понимаю, как скачивать через консоль... У вас есть подробная инструкция по этому процессу
> > > Если это не доставит вам хлопот, я могу подождать, пока вы добавите кнопку для скачивания субтитров в меню.
> > 
> > 
> > Чтобы скачать нужно найти вот такую строчку. В ней найти нужный язык (поле `language` - обозначает язык субтитров). Для загрузки нужно перейти по ссылки ![image](https://user-images.githubusercontent.com/62353659/273305532-0f7b724f-beac-4bdc-9e70-573553f7031b.png)
> 
> Новый вопрос.
> 
> Похоже, что скачанный файл с субтитрами нельзя использовать напрямую. Как преобразовать скачанный файл с субтитрами в рабочий формат? [1](https://brosubs.s3-private.mds.yandex.net/vtrans/e411ee18-1c54-4f4a-a965-aa78572557d5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=H9BHBAsxYbYIu9W7T8KG%2F20231007%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231007T151624Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=c1f7dd4a2877237980989354d7b6bbd3e520689268c8791e662acc325f088441) ![20231007233905](https://user-images.githubusercontent.com/103359343/273395198-aa4f7bd1-f8c1-4226-85d7-4230c8f6c4eb.png)

Это уже не подскажу, возможно, есть какие-то онлайн инструменты, либо прийдется написать свой конвертер

**Comment by smallwhitedesu** [comment]
> > > > > Пока что можете скачать через консоль браузера. Позже добавлю какую-нибудь кнопку в меню
> > > > 
> > > > 
> > > > Загрузка через консоль браузера...? Я не совсем понимаю, как скачивать через консоль... У вас есть подробная инструкция по этому процессу
> > > > Если это не доставит вам хлопот, я могу подождать, пока вы добавите кнопку для скачивания субтитров в меню.
> > > 
> > > 
> > > Чтобы скачать нужно найти вот такую строчку. В ней найти нужный язык (поле `language` - обозначает язык субтитров). Для загрузки нужно перейти по ссылки ![image](https://user-images.githubusercontent.com/62353659/273305532-0f7b724f-beac-4bdc-9e70-573553f7031b.png)
> > 
> > 
> > Новый вопрос.
> > Похоже, что скачанный файл с субтитрами нельзя использовать напрямую. Как преобразовать скачанный файл с субтитрами в рабочий формат? [1](https://brosubs.s3-private.mds.yandex.net/vtrans/e411ee18-1c54-4f4a-a965-aa78572557d5?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=H9BHBAsxYbYIu9W7T8KG%2F20231007%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231007T151624Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=c1f7dd4a2877237980989354d7b6bbd3e520689268c8791e662acc325f088441) ![20231007233905](https://user-images.githubusercontent.com/103359343/273395198-aa4f7bd1-f8c1-4226-85d7-4230c8f6c4eb.png)
> 
> Это уже не подскажу, возможно, есть какие-то онлайн инструменты, либо прийдется написать свой конвертер

Хорошо  спасибо

**Comment by ilyhalight** [comment]
Добавлено в стабильную версию
