### ISSUE TITLE
Скачивание перевода вместе с оригинальной дорожкой

### ISSUE THREAD

**Issue by awesomebloging** [ilyhalight/voice-over-translation#353]
Перевод видео - это удобно, но _при скачивании аудио_ мы получаем только механический голос и теряем возможность понимать где была ирония, сатира, гротеск итд.

Было бы классно иметь возможность скачивать склеенное аудио вместе с оригинальной дорожкой громкостью в 15%. Думаю многие скачивают аудио и слушают как подкасты. Но сейчас при скачивании нужно либо скачивать и клеть вручную оригинальную дорожку, выставлять громкость итд, что долго. Либо слушать только механический голос, что нормально, но не всегда бывает ясен контекст.

**Comment by ilyhalight** [comment]
[FOSWLY/vot-cli](https://github.com/FOSWLY/vot-cli) вам в помощь. Там сделана загрузка в mp4+audio+перевод, думаю не будет проблем при необходимости разделить, либо переделать скрипт, чтобы он скачивал только audio+перевод
