### ISSUE TITLE
НЕ РАБОТАЕТ ПЕРЕВОД С XVIDEOS ПОМОГИТЕ(((

### ISSUE THREAD

**Issue by Jone655** [ilyhalight/voice-over-translation#356]
Пишет the audio format is not supported, и на телефоне с киви браузера и на пк с гугла

**Comment by SashaXser** [comment]
> Пишет the audio format is not supported, и на телефоне с киви браузера и на пк с гугла

Как же вас развелось, как тараканы, уже нет желания отвечать на такие вопросы. Почему вы не читаете описание? 
Надо поставить барьер для ленивых и тупых, чтобы не писали по 100 раз одно и тоже.

Вот примерное решение проблемы:

Для работы в хромоподобных браузерах может быть необходимо дополнительное [расширение](https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related)

**Comment by ilyhalight** [comment]
Выше ответили на ваш вопрос. Перед тем как задавать вопрос в следующий раз, хотя бы, проверьте нет ли вашего вопроса в [вики](https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-Supported-sites#xvideos)
