### ISSUE TITLE
Включенный перевод в браузере Arc ломает автоматический picture in picture

### ISSUE THREAD

**Issue by doroved** [ilyhalight/voice-over-translation#357]
В браузере Arc при переходе с вкладки ютуба, видео открывается в мини плеере, но если включить перевод, то видео не сворачивается в мини плеер. Сначала подумал, что это баг в Arc, оказалось, что какой-то конфликт создает расширение. 
Демонстрация бага - https://youtu.be/SLVwIOFX14k
Если получится пофиксить, буду благодарен.

**Comment by SashaXser** [comment]
> В браузере Arc при переходе с вкладки ютуба, видео открывается в мини плеере, но если включить перевод, то видео не сворачивается в мини плеер. Сначала подумал, что это баг в Arc, оказалось, что какой-то конфликт создает расширение. Демонстрация бага - https://youtu.be/SLVwIOFX14k Если получится пофиксить, буду благодарен.

Попробуйте использовать бету версию, и отпишитесь об изменениях.

**Comment by SashaXser** [comment]
> > > В браузере Arc при переходе с вкладки ютуба, видео открывается в мини плеере, но если включить перевод, то видео не сворачивается в мини плеер. Сначала подумал, что это баг в Arc, оказалось, что какой-то конфликт создает расширение. Демонстрация бага - https://youtu.be/SLVwIOFX14k Если получится пофиксить, буду благодарен.
> > 
> > 
> > Попробуйте использовать бету версию, отпишитесь об изменениях.
> 
> Поставил **1.5.0-beta3**, к сожалению проблема сохранилась

Проблема актуальна?

**Comment by SashaXser** [comment]
> Не планируется решить проблему?)

На новой бете тоже самое? Чтобы исправить, нужно установить браузер и потратить время. Потом может быть попробую.

**Comment by SashaXser** [comment]
> > > Не планируется решить проблему?)
> > 
> > 
> > На новой бете тоже самое
> 
> Последнюю бетку использую, тоже самое да.
> 
> > Чтобы исправить, нужно установить браузер и потратить время. Потом может быть попробую.
> 
> Ok)

Кстати, обращались ли в службу поддержки браузера для выяснения причины? У меня, к сожалению, нет устройств Apple, разве что можно запустить виртуальную машину с MacOS...

**Comment by SashaXser** [comment]
> > Кстати, обращались ли в службу поддержки браузера для выяснения причины? У меня, к сожалению, нет устройств Apple, разве что можно запустить виртуальную машину с MacOS...
> 
> Да это не в браузере дело, так как без включения перевода, все ок работает) А то что мака нет, хреново, хз через виртуалку как все это будет работать, получится ли отловить проблему.
> 
> Может логирование этого момента сделать, а я логи скину потом

[Включил логирование](https://github.com/SashaXser/voice-over-translation/tree/test/dist), попробуй отловить ошибку.

**Comment by SashaXser** [comment]
> > попробуй отловить ошибку.
> 
> Да что-то хз даже, если руками нажать на эту кнопку, то свернется. <img alt="image" width="313" src="https://private-user-images.githubusercontent.com/30116541/305397728-9c53e362-13d4-4df5-9f86-a10a7204a5d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODMyMzcsIm5iZiI6MTcwODA4MjkzNywicGF0aCI6Ii8zMDExNjU0MS8zMDUzOTc3MjgtOWM1M2UzNjItMTNkNC00ZGY1LTlmODYtYTEwYTcyMDRhNWQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE2VDExMjg1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MGE1ZGIyN2VkZTBkYTQ5MzYzMmEwZTM2ZTM2ZDA2YzllMzhlOGVjZDJlMjAzYmY0MDRkN2UyMDA3NWNjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVbVF_3iftYkDyIPDQIYP4XqUCXT9K8ss1beFbc3YTo">
> 
> Я же правильно понял, как работает скрипт, он синхронизирует время видео с временем озвучки и запускает ее поверх видео?
> 
> Может то что озвучка грузится в блоб из расширения и это мешает браузеру свернуть в мини плеер при переходе на другую вкладку. `blob:chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/79a2de06-ee54-41dc-ab50-6744006c9940`
> 
> Я не углублялся в код скрипта, но если получится блоб озвучки создать на домене ютуба, то можно попробовать.

Не видео, а аудио. При запуске скрипта создается new Audio(), а после получания перевода он подставляет ссылку в этот элемент Audio.

**Comment by ilyhalight** [comment]
Исправлено, но работает, только, если включен "Новый аудиоплеер". Со старым нельзя исправить

**Comment by doroved** [comment]
> Исправлено, но работает, только, если включен "Новый аудиоплеер". Со старым нельзя исправить

Спасибо, заработало, только если галочку снять с `Использовать только для обхода Media CSP`, при этом ничего другое не сломается?
<img width="471" alt="image" src="https://github.com/user-attachments/assets/0684368e-9c1e-47db-8f78-27c84665380d">
И если в двух словах можно объяснить, в чем проблема была? интересно

**Comment by ilyhalight** [comment]
> при этом ничего другое не сломается?

не должно, но аудио будет немного дольше загружаться т.к. чанковая загрузка еще не реализована

> И если в двух словах можно объяснить, в чем проблема была? интересно

как понимаю, связано с тем, что арк переводит видео в pip, только, если оно является последним медиа с которым выполнялось взаимодействие. При включение аудио перевода, таким последним медиа становился `<audio>` и соответственно pip не работал

**Comment by SashaXser** [comment]
> > при этом ничего другое не сломается?
> 
> не должно, но аудио будет немного дольше загружаться т.к. чанковая загрузка еще не реализована
> 
> > И если в двух словах можно объяснить, в чем проблема была? интересно
> 
> как понимаю, связано с тем, что арк переводит видео в pip, только, если оно является последним медиа с которым выполнялось взаимодействие. При включение аудио перевода, таким последним медиа становился `<audio>` и соответственно pip не работал

Индусский код
