### ISSUE TITLE
Udemy: "Не удалось получить данные, необходимые для перевода"

### ISSUE THREAD

**Issue by Cyberive** [ilyhalight/voice-over-translation#358]
Доброго времени 

Прошу помощи. По ситуации следующие: 
<img width="1439" alt="min" src="https://github.com/ilyhalight/voice-over-translation/assets/147221369/376293c0-2b28-41dc-bb2f-f9525f1b432a">
<img width="1440" alt="min1" src="https://github.com/ilyhalight/voice-over-translation/assets/147221369/e6e84ce2-aea9-4fc4-be74-6c0a3185e834">

**Comment by ilyhalight** [comment]
Предполагаю, что у курса нету видео в формате mp4 или webm, либо нету субтитров. Проверьте их наличие по дебаг логам (lecture data -> asset -> media_sources и lecture data -> asset -> captions) как это описано в #317

**Comment by sws33** [comment]
У меня такая же ошибка. MP4 вроде есть - могу скачать видос в формате mp4 через Video DownloadHelper 
В консоли: 

[VOT] VOTLocalizedError: Could not get the data required for the translate
    VOTLocalizedError moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:4372
    translateFunc moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2286
    translateExecutor moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2256
    translateProccessor moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2521
    translateProccessor moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2501
    initWebsite moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2941
    main moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2978
    js moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:2982
    a moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:5368
    js moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:1159
    __webpack_require__ moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:5311
    window["__f__lng7puou.z0k"]/</< moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:5437
    window["__f__lng7puou.z0k"]/< moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:5439
    St https://www.udemy.com/course/sanskrit-pronunciation/learn/lecture/8929318#overview:9
    window["__f__lng7puou.z0k"]/< moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:1
    "__f__lng7puou.z0k" moz-extension://850a6b51-db4d-44e3-ba63-d35262416ae2/userscripts/[VOT]-Voice-Over-Translation.user.js?id=4b302e0b-64db-4a0d-afb3-07f72fae595a:1
    St https://www.udemy.com/course/sanskrit-pronunciation/learn/lecture/8929318#overview:9
    s https://www.udemy.com/course/sanskrit-pronunciation/learn/lecture/8929318#overview:72
    <anonymous> https://www.udemy.com/course/sanskrit-pronunciation/learn/lecture/8929318#overview:75
    g https://www.udemy.com/course/sanskrit-pronunciation/learn/lecture/8929318#overview:69
[VOT]-Voice-Over-Translation.user.js:2523:19

**Comment by ilyhalight** [comment]
> У меня такая же ошибка. MP4 вроде есть - могу скачать видос в формате mp4 через Video DownloadHelper. 

Проверьте что пишет в консоли в "lecture Data" и в "videoURL: XXX, subtitlesURL". DonwloadHelper может как-то иначе работать из-за чего там будет ссылка, а в расширение нет.



> . И
> почему-то на запоминается access-token, когда ввожу его повторно, вижу пустое поле.

Странно, должно запоминаться, возможно, именно из-за этого не работает

**Comment by Cyberive** [comment]
> нету видео в формате mp4

Был прав!

**Comment by sws33** [comment]
Посмотрел свойства скаченного видео  через Avidemux - см. ниже.  Загрузил его на Rutube, попытался перевести через Яндекс-браузер, на что он ругнулся и не смог его даже воспроизвести, написал, что надо обновить кодек. Запустил, как он посоветовал - sudo /opt/yandex/browser/update-ffmpeg и получил ошибку - 
FFMPEG codecs installation failed: there are no download urls for the current browser version: 114.0.5735. Во вкладке about - Yandex Browser говорит, что версия 23.7.1.1215 stable (64-bit). 

Локально, с компьютера видео нормально воспроизводится.  

> lecture Data и в "videoURL: XXX, subtitlesURL"
Странно, ни в консоли, ни в хранилице не нашёл этих вхождений: lecture Data, videoURL:

=====================================================
Видео
=====================================================
Кодек 4СС:			H264
Размер картинки:		1280 x 720
Соотношение сторон:		1:1 (1:1)
Частота кадров:			30,000 кадров/с
Средний битрейт:		2421 кбит/c
Общая длительность:		00:06:25,900
Формат пикселей:		YUV 4:2:0, 8 бит
Цветовой диапазон:		Ограниченный (MPEG)
Первичные цвета:		BT.709
Функция преобразования:		BT.709
Цветовое пространство:		BT.709

=====================================================
Дополнительные данные видеокодека
=====================================================
Размер:				40
Дополнительные данные:		01 4D 40 1F FF E1 00 19 67 4D 40 1F EC A0 28 02 DD 80 88 00 00 03 00 08 00 00 03 01 E0 78 C1 8C B0 01 00 04 68 EB EC B2 

=====================================================
Аудио (1 включённая дорожка)
=====================================================
Кодек:				AAC
Каналы:				Стерео
Битрейт:			16000 Bps / 128 kbps
Частота дискретизации:		44100 Hz
Общая длительность:		00:06:26,028

**Comment by ex1side** [comment]
Здраствуйте, также имеется проблема с udemy, на стабильной версии скрипта, после нажатия на кнопку ничего не просходит(ошибка не появляется), на 1.5.0-бета4 кнопка перевода просто не отображается на udemy

**Comment by ilyhalight** [comment]
> Здраствуйте, также имеется проблема с udemy, на стабильной версии скрипта, после нажатия на кнопку ничего не просходит(ошибка не появляется), на 1.5.0-бета4 кнопка перевода просто не отображается на udemy

что-то пишет в консоли? какой браузер? какой загрузчик?

**Comment by omartulashvili** [comment]
Добрый вечер!
Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"

Лог из консоли:
![image](https://github.com/ilyhalight/voice-over-translation/assets/99362820/40fab6ee-2b7a-4534-8314-1395975fb087)

Браузер: Brave 1.59.120
Tampermonkey

**Comment by ilyhalight** [comment]
> Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> 
> Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> 
> Браузер: Brave 1.59.120 Tampermonkey

Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.

**Comment by omartulashvili** [comment]
> > Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> > Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> > Браузер: Brave 1.59.120 Tampermonkey
> 
> Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.

Скажите, а это не связано вот с этим:
![image](https://github.com/ilyhalight/voice-over-translation/assets/99362820/9465059a-75b8-4b80-8cc0-ecdc04e1c492)

В моем курсе ведь нет субтитров на русском, только Англ. и другие языки :thinking:

**Comment by ilyhalight** [comment]
> > > Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> > > Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> > > Браузер: Brave 1.59.120 Tampermonkey
> > 
> > 
> > Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.
> 
> Скажите, а это не связано вот с этим: ![image](https://user-images.githubusercontent.com/99362820/277880772-9465059a-75b8-4b80-8cc0-ecdc04e1c492.png)
> 
> В моем курсе ведь нет субтитров на русском, только Англ. и другие языки 🤔
> 
> За инфо про бету спасибо, как попробую - дам обр. связь
> 
> UPD: Накатил в Mozilla [бету](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta4) 1.5.0-beta4, перевести не получилось. Лог ошибок: ![image](https://user-images.githubusercontent.com/99362820/277882264-05c03906-b315-45fe-800a-d8db7a4f08dc.png)

А можете немного выше в консоли скинуть как у вас выглядит строчка videoURL: .... subtitlesURL: ....
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/b03b2f4b-9fb8-471f-b556-e9f298eecaad)

**Comment by omartulashvili** [comment]
> > > > Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> > > > Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> > > > Браузер: Brave 1.59.120 Tampermonkey
> > > 
> > > 
> > > Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.
> > 
> > 
> > Скажите, а это не связано вот с этим: ![image](https://user-images.githubusercontent.com/99362820/277880772-9465059a-75b8-4b80-8cc0-ecdc04e1c492.png)
> > В моем курсе ведь нет субтитров на русском, только Англ. и другие языки 🤔
> > За инфо про бету спасибо, как попробую - дам обр. связь
> > UPD: Накатил в Mozilla [бету](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta4) 1.5.0-beta4, перевести не получилось. Лог ошибок: ![image](https://user-images.githubusercontent.com/99362820/277882264-05c03906-b315-45fe-800a-d8db7a4f08dc.png)
> 
> А можете немного выше в консоли скинуть как у вас выглядит строчка videoURL: .... subtitlesURL: .... ![image](https://user-images.githubusercontent.com/62353659/277951359-b03b2f4b-9fb8-471f-b556-e9f298eecaad.png)

Нашел вот такую строчку (это в moziila на установленной бете):
![image](https://github.com/ilyhalight/voice-over-translation/assets/99362820/7270c01d-b71f-4012-9f7a-bdbe61673c0e)

Вы про нее говорите?

**Comment by ilyhalight** [comment]
> > > > > Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> > > > > Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> > > > > Браузер: Brave 1.59.120 Tampermonkey
> > > > 
> > > > 
> > > > Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.
> > > 
> > > 
> > > Скажите, а это не связано вот с этим: ![image](https://user-images.githubusercontent.com/99362820/277880772-9465059a-75b8-4b80-8cc0-ecdc04e1c492.png)
> > > В моем курсе ведь нет субтитров на русском, только Англ. и другие языки 🤔
> > > За инфо про бету спасибо, как попробую - дам обр. связь
> > > UPD: Накатил в Mozilla [бету](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta4) 1.5.0-beta4, перевести не получилось. Лог ошибок: ![image](https://user-images.githubusercontent.com/99362820/277882264-05c03906-b315-45fe-800a-d8db7a4f08dc.png)
> > 
> > 
> > А можете немного выше в консоли скинуть как у вас выглядит строчка videoURL: .... subtitlesURL: .... ![image](https://user-images.githubusercontent.com/62353659/277951359-b03b2f4b-9fb8-471f-b556-e9f298eecaad.png)
> 
> Нашел вот такую строчку (это в moziila на установленной бете): ![image](https://user-images.githubusercontent.com/99362820/278042155-7270c01d-b71f-4012-9f7a-bdbe61673c0e.png)
> 
> Вы про нее говорите?

Да. Как я и предполагал в вашем курсе нет видео в поддерживаемом формате

**Comment by omartulashvili** [comment]
> > > > > > Добрый вечер! Идентичная проблема: при нажатии на кнопку перевода появляется надпись "не удалось получить данные, необходимые для перевода"
> > > > > > Лог из консоли: ![image](https://user-images.githubusercontent.com/99362820/277740853-40fab6ee-2b7a-4534-8314-1395975fb087.png)
> > > > > > Браузер: Brave 1.59.120 Tampermonkey
> > > > > 
> > > > > 
> > > > > Попробуйте последнюю бету скрипта, если там не заработает, то проблема в не поддерживаемом формате.
> > > > 
> > > > 
> > > > Скажите, а это не связано вот с этим: ![image](https://user-images.githubusercontent.com/99362820/277880772-9465059a-75b8-4b80-8cc0-ecdc04e1c492.png)
> > > > В моем курсе ведь нет субтитров на русском, только Англ. и другие языки 🤔
> > > > За инфо про бету спасибо, как попробую - дам обр. связь
> > > > UPD: Накатил в Mozilla [бету](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta4) 1.5.0-beta4, перевести не получилось. Лог ошибок: ![image](https://user-images.githubusercontent.com/99362820/277882264-05c03906-b315-45fe-800a-d8db7a4f08dc.png)
> > > 
> > > 
> > > А можете немного выше в консоли скинуть как у вас выглядит строчка videoURL: .... subtitlesURL: .... ![image](https://user-images.githubusercontent.com/62353659/277951359-b03b2f4b-9fb8-471f-b556-e9f298eecaad.png)
> > 
> > 
> > Нашел вот такую строчку (это в moziila на установленной бете): ![image](https://user-images.githubusercontent.com/99362820/278042155-7270c01d-b71f-4012-9f7a-bdbe61673c0e.png)
> > Вы про нее говорите?
> 
> Да. Как я и предполагал в вашем курсе нет видео в поддерживаемом формате

Во всяком случае - спасибо вам за расширение, а в курсе обойдусь субтитрами :pray:

**Comment by dennmakarov** [comment]
Не переводит ни одного курса с udemy. Везде ошибка
<img width="704" alt="Снимок экрана 2024-05-03 в 13 38 06" src="https://github.com/ilyhalight/voice-over-translation/assets/58773413/e5d6c61a-9222-4631-abbe-129755ecbe8c">

**Comment by ilyhalight** [comment]
> Аналогично, с udemy.com не переводит. Токен обновлял, все делал как в инструкции. результата нет. видео в формате mp4.
> 
> Не удалось получить данные, необходимые для перевода

Вводите токен обернутый в ковычки ("") или без? (нужно вводить без ковычек) 
Субтитры у видео есть? 
Что-то в консоли пишет?

Так же, можете попробовать обновить расширение, только что, залил версию в которой, если не находит субтитры, то используется только прямая ссылка на видео

**Comment by ilyhalight** [comment]
Скорее всего, было исправлено в 1.6.
