### ISSUE TITLE
Поддержка youtube "embed" линков ?

### ISSUE THREAD

**Issue by Baltazar500** [ilyhalight/voice-over-translation#36]
Собственно сабж. На embed линках плашка не появляется. А очень бы хотелось т.к. они в разы легче для мобильного (ведроидного) хрома, работающего в десктопном режиме.

Пример линка : https://www.youtube.com/embed/zqgj390UY6M

**Comment by ilyhalight** [comment]
Уже сделано. Скоро появится

**Comment by Baltazar500** [comment]
Собственно я об этом в другой ветке писал, но продублирую и здесь :

>На десктопе в хроме под TamperMonkey плашка на месте. Под AdGuard на андроиде с хромом в десктопном режиме плашки на embed - линках нет. На обычных ютуб - линках она есть. Но эти страницы с таким диким лагом в отличии от embed - линков грузятся, что ппц.

В связи с этим вопрос, это ремонтабельно или особенности мобильного хрома не обойти ? 

Можно ли как-то запрос на перевод (а впоследствии и его включение) вызвать из букмарклета ? Моб. хром поддерживает скрипто-вкладки, но довольно своеобразно.

**Comment by ilyhalight** [comment]
> Собственно я об этом в другой ветке писал, но продублирую и здесь :
> 
> > На десктопе в хроме под TamperMonkey плашка на месте. Под AdGuard на андроиде с хромом в десктопном режиме плашки на embed - линках нет. На обычных ютуб - линках она есть. Но эти страницы с таким диким лагом в отличии от embed - линков грузятся, что ппц.
> 
> В связи с этим вопрос, это ремонтабельно или особенности мобильного хрома не обойти ?
> 
> Можно ли как-то запрос на перевод (а впоследствии и его включение) вызвать из букмарклета ? Моб. хром поддерживает скрипто-вкладки, но довольно своеобразно.

Всё это надо тестить. А сейчас времени на то, чтобы заниматься расширением не особо много. Если нужно расширение на мобилке, здесь и сейчас, то можешь поставить firefox nightly и [накатить на него тамперманки](https://enux.pl/article/en/2021-03-14/how-use-tampermonkey-firefox-mobile). Там, всё отлично работает в эмбедах. Как будет время, постараюсь разобраться с хромом и адгуардом на мобилках.

![photo_2022-12-11_00-29-26](https://user-images.githubusercontent.com/62353659/206875980-e06acab4-ff36-411a-b88f-0baf03c597a3.jpg)
