### ISSUE TITLE
Кнопка скачивания переведенной дорожки подлезает под элементы управления

### ISSUE THREAD

**Issue by Jawerka** [ilyhalight/voice-over-translation#360]
На скриншоте видно. Ее невозможно нажать пока не развернешь видео на весь экран, возможно ли починить это?
![Снимок экрана 2023-10-04 013739](https://github.com/ilyhalight/voice-over-translation/assets/86230641/d1cd0650-79ac-4ca2-b938-85f9eac7f995)

**Comment by SashaXser** [comment]
> На скриншоте видно. Ее невозможно нажать пока не развернешь видео на весь экран, возможно ли починить это? ![Снимок экрана 2023-10-04 013739](https://user-images.githubusercontent.com/86230641/273465698-d1cd0650-79ac-4ca2-b938-85f9eac7f995.png)

В бете новое меню, попробуй установить бету и отпиши если помогло.

**Comment by Jawerka** [comment]
> > На скриншоте видно. Ее невозможно нажать пока не развернешь видео на весь экран, возможно ли починить это? ![Снимок экрана 2023-10-04 013739](https://user-images.githubusercontent.com/86230641/273465698-d1cd0650-79ac-4ca2-b938-85f9eac7f995.png)
> 
> В бете новое меню, попробуй установить бету и отпиши если помогло.

Да, все отлично в бете.
