### ISSUE TITLE
VOT версии 1.4.1 неработоспособен в AdGuard, а 1.5.0-beta4 плашку вообще не кажет

### ISSUE THREAD

**Issue by Baltazar500** [ilyhalight/voice-over-translation#361]
Собственно сабж.

Понадобился VOT (использую от случая к случаю) и что характерно - старая версия уже не работала и нужно было накатывать новую (пока ручками ибо свой хост и отказ от автопдейта + не очень часто это происходит). Как выяснилось, последняя стабильная версия VOT (1.4.1) практически неработоспособна в AdGuard (под ведром) - кнопка перевода тупо некликабельна, хотя поначалу сообщала сообщает, что "Не удалось загрузить перевод" или "TypeError: Failed to fetch". Последняя ревизия VOT (1.5.0-beta4) плашку вообще не кажет и в принципе неюзабельна в моём случае.

**Comment by SashaXser** [comment]
> Собственно сабж.
> 
> Понадобился VOT (использую от случая к случаю) и что характерно - старая версия уже не работала и нужно было накатывать новую (пока ручками ибо свой хост и отказ от автопдейта + не очень часто это происходит). Как выяснилось, последняя стабильная версия VOT (1.4.1) практически неработоспособна в AdGuard (под ведром) - кнопка перевода тупо некликабельна, хотя поначалу сообщала сообщает, что "Не удалось загрузить перевод" или "TypeError: Failed to fetch". Последняя ревизия VOT (1.5.0-beta4) плашку вообще не кажет и в принципе неюзабельна в моём случае.

Какую версию на скрипта установил? CloudFlare или обычную? Во вторых, где логи? Как тебе помогать по текстовому описанию? Знаешь, я не живу в твоем телефоне и не могу оттуда узнать, что у тебя там конкретно не работает.
Отправь логи для уточнения причины неработоспособности.

**Comment by SashaXser** [comment]
> > Какую версию скрипта установил? CloudFlare или обычную?
> 
> CloudFlare, я другой и не пользовался (ну это если исходить из прошлых issue)
> 
> > Во вторых, где логи?
> 
> Какие конкретно логи ? Скрипт вкорячен в ведроидный AdGuard и там у меня руки связаны. Максимум, что могу - подцепить по usb на десктопе (который не всегда доступен) и посмотреть хромовскую отладку по F12. Что конкретно там смотреть ?

Отладку по F12 подойдет, главное чтобы там логи самого скрипта были. По ним хотя бы можно понять что пошло не так.

**Comment by SashaXser** [comment]
> Здравствуйте. У меня возникли такие же проблемы (я пытался пробовать разные версии):
> 
>     1. Сначало не появлялась кнопка вообще.
> 
>     2. Затем она стала не кликабельна, хотя кнопка настроек кликалась, но не кнопка перевода. Включалось "Воспроизведение/Пауза".
> 
>     3. После получал сообщение о невозможности получить перевод.
>        Получил весь набор, что и у других пользователей. Я вспомнил, что у меня стоят блокировщики сайтов/рекламы. Когда я дал доступ сайту "onrender.com" и др, всё заработало. До этого у меня работало без доступа, поэтому я не сразу понял причину. Так как проблемы точ-в-точь совпадают, то и причина скорее всего таже - нет доступа к необходимым сайтам. Надеюсь это кому-нибудь поможет.

Интересно, а в каком фильтре прописана блокировка сайта?

**Comment by ProNoobGH** [comment]
@SashaXser
Ни в каком. Это была ручная глобальная настройка принимались "1st-party" и в ручную добавлял правила остальных необходимых. Я почитал отзывы и увидел много совпадений, поэтому решил сообщить. Я думаю многие так же могли быть не внимательны, к настройкам и расширениям, которые у них установлены. Конечно ещё может быть блокирование провайдером. В общем, я советовал бы в первую очередь проверить соединение с необходимыми сайтами, тем у кого возникли описанные ошибки.

**Comment by Baltazar500** [comment]
@ProNoobGH, 

>Я вспомнил, что у меня стоят блокировщики сайтов/рекламы.

В моём случае блокировщик рекламы - он же средство использования UserJS, так что мне отключить оный будет проблематично.

>Когда я дал доступ сайту "onrender.com" и др, всё заработало.

Добавил для сайта и конкретного хоста разные вариации правила исключения

```

@@||onrender.com
@@onrender.com
@@||rust-server-531j.onrender.com
@@rust-server-531j.onrender.com

```

но мимо. Проверил содержимое используемых файлов подписок - тоже мимо. Тем не менее, увидев что в коде скрипта шлётся POST, решил его послать ручками и вместо ответа от сервера получил облом

```

curl -v 'https://rust-server-531j.onrender.com/detect' --data 'yandex'
*   Trying 216.24.57.253:443...
* TCP_NODELAY set
* Connected to rust-server-531j.onrender.com (216.24.57.253) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /system/etc/security/cacerts
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS alert, decode error (562):
* error:10000089:SSL routines:OPENSSL_internal:DECODE_ERROR
* Closing connection 0

```

Интересно девки пляшут, подумал я. Памятуя о том, что вы указали выше, что ресурс может находится под блокировками, чекнул оный на предмет блокироаок и получил довольно интересную картину :

<details>

✅ rust-server-531j.onrender.com не заблокирован

🔥 но может быть ограничен по базовому домену:

🔥 но может быть ограничен по IP-адресу:
    216.24.57.253
    216.24.57.3

🚫  /n_4184161   2022-03-25 /d_56e3fqtg4409p
• ст. 15.3, мятеж и фейки
    как ip 216.24.57.253
    как ip 216.24.57.3
    как domain onrender.com

🚫  /n_4500748   2022-06-12 /d_yxbdbn2828qac
• ст. 15.3, мятеж и фейки
    как ip 216.24.57.253
    как ip 216.24.57.3
    как domain onrender.com

🚫  /n_5770000   2023-04-17 /d_84esjrsm7zs32
• ст. 15.3, мятеж и фейки
    как ip 216.24.57.253
    как ip 216.24.57.3

типы блокировки: domain: 🚫

✅ onrender.com не заблокирован

🔥 но может быть ограничен по базовому домену:

🚫  /n_4184161   2022-03-25 /d_56e3fqtg4409p
• ст. 15.3, мятеж и фейки
    как domain onrender.com
    как domain onrender.com

🚫  /n_4500748   2022-06-12 /d_yxbdbn2828qac
• ст. 15.3, мятеж и фейки
    как domain onrender.com
    как domain onrender.com

типы блокировки: domain: 🚫

</details>

ОК. Подумал я. Раз это залетело в базу чекера, то наверно сайт есть и в списках антизапрета, который использует zapret для обхода локкинга. Грепаю список и та-дам - нахожу onrender.com (рукалицо). Далее вырубаю zapret, шлю запрос и успешно получаю ответ (снова рукалицо).

Резюмируя вышесказанное, сайт, который попал в списки антиблокировщиков, но при этом заблокирован не был - успешно "ломался" антиблокировщиком, что как минимум могло мломать логику скрипта.

При всём при этом, все эти телодвижения мне пока не помогли решить проблему. Плашка на 1.5.0-beta4не так и не появилась, а работу 1.4.1 я ещё не перепроверил.

>Отладку по F12 подойдет, главное чтобы там логи самого скрипта были. По ним хотя бы можно понять что пошло не так.

@SashaXser, я совсем не дока в браузерной отладке. Что конкретно там смотреть ? Куда тыкать ? Я максимум туда залезаю код элемента посмотреть, для составления правил AdGuard'a.

**Comment by SashaXser** [comment]
> @ProNoobGH,
> 
> > Я вспомнил, что у меня стоят блокировщики сайтов/рекламы.
> 
> В моём случае блокировщик рекламы - он же средство использования UserJS, так что мне отключить оный будет проблематично.
> 
> > Когда я дал доступ сайту "onrender.com" и др, всё заработало.
> 
> Добавил для сайта и конкретного хоста разные вариации правила исключения
> 
> ```
> 
> @@||onrender.com
> @@onrender.com
> @@||rust-server-531j.onrender.com
> @@rust-server-531j.onrender.com
> ```
> 
> но мимо. Проверил содержимое используемых файлов подписок - тоже мимо. Тем не менее, увидев что в коде скрипта шлётся POST, решил его послать ручками и вместо ответа от сервера получил облом
> 
> ```
> 
> curl -v 'https://rust-server-531j.onrender.com/detect' --data 'yandex'
> *   Trying 216.24.57.253:443...
> * TCP_NODELAY set
> * Connected to rust-server-531j.onrender.com (216.24.57.253) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: none
>   CApath: /system/etc/security/cacerts
> * TLSv1.2 (OUT), TLS handshake, Client hello (1):
> * TLSv1.2 (IN), TLS handshake, Server hello (2):
> * TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.3 (OUT), TLS alert, decode error (562):
> * error:10000089:SSL routines:OPENSSL_internal:DECODE_ERROR
> * Closing connection 0
> ```
> 
> Интересно девки пляшут, подумал я. Памятуя о том, что вы указали выше, что ресурс может находится под блокировками, чекнул оный на предмет блокироаок и получил довольно интересную картину :
> 
> ✅ rust-server-531j.onrender.com не заблокирован
> 
> 🔥 но может быть ограничен по базовому домену:
> 
> 🔥 но может быть ограничен по IP-адресу: 216.24.57.253 216.24.57.3
> 
> 🚫 /n_4184161 2022-03-25 /d_56e3fqtg4409p • ст. 15.3, мятеж и фейки как ip 216.24.57.253 как ip 216.24.57.3 как domain onrender.com
> 
> 🚫 /n_4500748 2022-06-12 /d_yxbdbn2828qac • ст. 15.3, мятеж и фейки как ip 216.24.57.253 как ip 216.24.57.3 как domain onrender.com
> 
> 🚫 /n_5770000 2023-04-17 /d_84esjrsm7zs32 • ст. 15.3, мятеж и фейки как ip 216.24.57.253 как ip 216.24.57.3
> 
> типы блокировки: domain: 🚫
> 
> ✅ onrender.com не заблокирован
> 
> 🔥 но может быть ограничен по базовому домену:
> 
> 🚫 /n_4184161 2022-03-25 /d_56e3fqtg4409p • ст. 15.3, мятеж и фейки как domain onrender.com как domain onrender.com
> 
> 🚫 /n_4500748 2022-06-12 /d_yxbdbn2828qac • ст. 15.3, мятеж и фейки как domain onrender.com как domain onrender.com
> 
> типы блокировки: domain: 🚫
> 
> ОК. Подумал я. Раз это залетело в базу чекера, то наверно сайт есть и в списках антизапрета, который использует zapret для обхода локкинга. Грепаю список и та-дам - нахожу onrender.com (рукалицо). Далее вырубаю zapret, шлю запрос и успешно получаю ответ (снова рукалицо).
> 
> Резюмируя вышесказанное, сайт, который попал в списки антиблокировщиков, но при этом заблокирован не был - успешно "ломался" антиблокировщиком, что как минимум могло сломать логику скрипта.
> 
> При всём при этом, все эти телодвижения мне пока не помогли решить проблему. Плашка на 1.5.0-beta4не так и не появилась, а работу 1.4.1 я ещё не перепроверил.
> 
> @SashaXser,
> 
> > Отладку по F12 подойдет, главное чтобы там логи самого скрипта были. По ним хотя бы можно понять что пошло не так.
> 
> Я совсем не дока в браузерной отладке. Что конкретно там смотреть ? Куда тыкать ? Я максимум туда залезаю код элемента посмотреть (для составления правил AdGuard'a), да сетевые запросы поглядеть.

Этот сайт используется только при отсутствии субтитров у видео. По идее, он не должен использоваться когда субтитры в видео есть. Как я понял, у вас на любом видео ошибка. Пробывали включать проксирование аудио (включается в меню) или включить VPN?

**Comment by Baltazar500** [comment]
Снял логи из консоли и грепнул строки содержащие "VOT Cloudflare" (или всё надо было ?) для версий 1.4.1 и 1.5.0-beta4 с теми же условиями (при недоступности rust-server-531j.onrender.com). На 1.4.1 плашка есть, но кнопка перевода некликабельна, сколько по ней не тапай. На 1.5.0-beta4 плашки нет в принципе и тапать некуда.

[1.4.1.log](https://github.com/ilyhalight/voice-over-translation/files/12899736/1.4.1.log)
[1.5.0-beta4.log](https://github.com/ilyhalight/voice-over-translation/files/12899732/1.5.0-beta4.log)

>Этот сайт используется только при отсутствии субтитров у видео. По идее, он не должен использоваться когда субтитры в видео есть. Как я понял, у вас на любом видео ошибка. 

Я пока конкретное видео проверял. И пару соседних. Возможно они однотипные и поэтому имеют схожий эффект. ХЗ. Вот этот ролик https://www.youtube.com/watch?v=ulurgH9ePoM

>Пробывали включать проксирование аудио (включается в меню) или включить VPN?

Сам adguard пускал вместе с хромом через прокси. Но особой разницы вроде не было. Но могу перепроверить< если надо.

**Comment by SashaXser** [comment]
> Снял логи из консоли и грепнул строки содержащие "VOT Cloudflare" (или всё надо было ?) для версий 1.4.1 и 1.5.0-beta4 с теми же условиями (при недоступности rust-server-531j.onrender.com). На 1.4.1 плашка есть, но кнопка перевода некликабельна, сколько по ней не тапай. На 1.5.0-beta4 плашки нет в принципе и тапать некуда.
> 
> [1.4.1.log](https://github.com/ilyhalight/voice-over-translation/files/12899736/1.4.1.log) [1.5.0-beta4.log](https://github.com/ilyhalight/voice-over-translation/files/12899732/1.5.0-beta4.log)
> 
> > Этот сайт используется только при отсутствии субтитров у видео. По идее, он не должен использоваться когда субтитры в видео есть. Как я понял, у вас на любом видео ошибка.
> 
> Я пока конкретное видео проверял. И пару соседних. Возможно они однотипные и поэтому имеют схожий эффект. ХЗ. Вот этот ролик https://www.youtube.com/watch?v=ulurgH9ePoM
> 
> > Пробывали включать проксирование аудио (включается в меню) или включить VPN?
> 
> Сам adguard пускал вместе с хромом через прокси. Но особой разницы вроде не было. Но могу перепроверить, если надо.



> Снял логи из консоли и грепнул строки содержащие "VOT Cloudflare" (или всё надо было ?) для версий 1.4.1 и 1.5.0-beta4 с теми же условиями (при недоступности rust-server-531j.onrender.com). На 1.4.1 плашка есть, но кнопка перевода некликабельна, сколько по ней не тапай. На 1.5.0-beta4 плашки нет в принципе и тапать некуда.
> 
> [1.4.1.log](https://github.com/ilyhalight/voice-over-translation/files/12899736/1.4.1.log) [1.5.0-beta4.log](https://github.com/ilyhalight/voice-over-translation/files/12899732/1.5.0-beta4.log)
> 
> > Этот сайт используется только при отсутствии субтитров у видео. По идее, он не должен использоваться когда субтитры в видео есть. Как я понял, у вас на любом видео ошибка.
> 
> Я пока конкретное видео проверял. И пару соседних. Возможно они однотипные и поэтому имеют схожий эффект. ХЗ. Вот этот ролик https://www.youtube.com/watch?v=ulurgH9ePoM
> 
> > Пробывали включать проксирование аудио (включается в меню) или включить VPN?
> 
> Сам adguard пускал вместе с хромом через прокси. Но особой разницы вроде не было. Но могу перепроверить, если надо.

А когда разворачиваешь меню в 1.4.1 у тебя есть пункты настроек? Если их нету и кнопка не нажимается, возможно база данных не смогла записаться.

**Comment by denncraft** [comment]
Тоже столкнулся с этой проблемой, но оказалось, что у менчя на разных компах разные расширения установлены. так вот с TamperMonkey скрипт работает, а в Gracemonkey - нет: кнопка не кликабельна, а при вызове меню настроек видны только выбор языков и кнопка сброса.

**Comment by Baltazar500** [comment]
>А когда разворачиваешь меню в 1.4.1 у тебя есть пункты настроек? Если их нету и кнопка не нажимается, возможно база данных не смогла записаться.

Меню есть. Причём язык плашки раз о  раза скачет. Настройки по дефолту, сам ничего не менял
![2023 10 15_01 22 06~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/1a4f8438-4751-4da2-987c-4d0797a1fd54)
![2023 10 15_01 23 05~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/39ae84fe-1981-44c3-957e-556644e7eb20)

Перевести видео/Translate video некликабельна.

**Comment by SashaXser** [comment]
> > А когда разворачиваешь меню в 1.4.1 у тебя есть пункты настроек? Если их нету и кнопка не нажимается, возможно база данных не смогла записаться.
> 
> Меню есть. Причём язык плашки раз от раза скачет. Настройки по дефолту, сам ничего не менял ![2023 10 15_01 22 06~01](https://user-images.githubusercontent.com/12525093/275247462-1a4f8438-4751-4da2-987c-4d0797a1fd54.jpg) ![2023 10 15_01 23 05~01](https://user-images.githubusercontent.com/12525093/275247479-39ae84fe-1981-44c3-957e-556644e7eb20.jpg)
> 
> Перевести видео/Translate video некликабельна.

У тебя базы данных не записалась) Настроек в меню нету, значит и кнопка не будет работать. Попробуй откатиться немного. Начинай смотреть версии от начиная с [1.4.0.3](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.4.0.3) и ниже. Возможно у тебя даже заработает все.

**Comment by Baltazar500** [comment]
>У тебя базы данных не записалась) Настроек в меню нету, значит и кнопка не будет работать. Попробуй откатиться немного. Начинай смотреть версии от начиная с [1.4.0.3](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.4.0.3) и ниже. Возможно у тебя даже заработает все.

Понизил до 1.4.0.3, та же петрушка. понизил до 1.4.0 - всё тоже самое. Решил всё же проверить, что будет, если rust-server-531j.onrender.com не будет ломаться. Собственно вот :

1.4.0, 1.4.3, 1.4.1

![2023 10 15_17 42 20~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/3294d533-097e-42a4-96f8-e5f52d89cea5)

1.5.0-beta4

![2023 10 15_17 51 28~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/ccf2e6a5-b8f9-4b9b-99c5-0022f517ef0f)

Т.е. после появления доступа к rust-server-531j.onrender.com кнопка становится кликабельной и появляются настройки. Правда ролик всё не переводится в обоих случаях, но это уже надо разбирать отдельно. Работу с rust-server-531j.onrender.com вам точно надо пересматривать. Имхо.

![2023 10 15_17 44 46~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/b88275eb-6b5a-40f4-99a9-af7f4bd75998)

![2023 10 15_17 51 02~01](https://github.com/ilyhalight/voice-over-translation/assets/12525093/21aaace4-cb06-4a92-9082-86726f39d7e7)

**Comment by SashaXser** [comment]
> > У тебя базы данных не записалась) Настроек в меню нету, значит и кнопка не будет работать. Попробуй откатиться немного. Начинай смотреть версии от начиная с [1.4.0.3](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.4.0.3) и ниже. Возможно у тебя даже заработает все.
> 
> Понизил до 1.4.0.3, та же петрушка. понизил до 1.4.0 - всё тоже самое. Решил всё же проверить, что будет, если rust-server-531j.onrender.com не будет ломаться. Собственно вот :
> 
> 1.4.0, 1.4.3, 1.4.1
> 
> ![2023 10 15_17 42 20~01](https://user-images.githubusercontent.com/12525093/275312885-3294d533-097e-42a4-96f8-e5f52d89cea5.jpg)
> 
> 1.5.0-beta4
> 
> ![2023 10 15_17 51 28~01](https://user-images.githubusercontent.com/12525093/275313175-ccf2e6a5-b8f9-4b9b-99c5-0022f517ef0f.jpg)
> 
> Т.е. после появления доступа к rust-server-531j.onrender.com кнопка становится кликабельной и появляются настройки. Правда ролик всё не переводится в обоих случаях, но это уже надо разбирать отдельно. Работу с rust-server-531j.onrender.com вам точно надо пересматривать. Имхо.
> 
> ![2023 10 15_17 44 46~01](https://user-images.githubusercontent.com/12525093/275312734-b88275eb-6b5a-40f4-99a9-af7f4bd75998.jpg)
> 
> ![2023 10 15_17 51 02~01](https://user-images.githubusercontent.com/12525093/275313547-21aaace4-cb06-4a92-9082-86726f39d7e7.jpg)

Если хотите, можно сделать прокси сайта. Но если уж у вас и при рабочем сайте не работает перевод. ¯\_(ツ)_/¯
Посмотри во вкладке сеть что не так с хостом для перевода. Может быть он у вас тоже заблокирован?

**Comment by Baltazar500** [comment]
>Посмотри во вкладке сеть что не так с хостом для перевода. Может быть он у вас тоже заблокирован?

Вот что по статусу (воркер свой, потому в линке и "xxx") :

```
Request URL: https://xxx.workers.dev/video-translation/translate
Status Code: 400

```

А ответ вот такой :

```

(error_id:1697364315326424-9377123667595046116) see logs for details

```

Там на стороне cf - воркера ничего подкручивать не надо ? Я по иронии со "встроенным" воркером (который мог работать с уже изменённой серверной частью) работу скрипта не глядел.

**Comment by SashaXser** [comment]
> > Посмотри во вкладке сеть что не так с хостом для перевода. Может быть он у вас тоже заблокирован?
> 
> Вот что по статусу (воркер свой, потому в линке и "xxx") :
> 
> ```
> Request URL: https://xxx.workers.dev/video-translation/translate
> Status Code: 400
> ```
> 
> А ответ вот такой :
> 
> ```
> 
> (error_id:1697364315326424-9377123667595046116) see logs for details
> ```
> 
> Там на стороне cf - воркера ничего подкручивать не надо ? Я по иронии со "встроенным" воркером (который мог работать с уже изменённой серверной частью) работу скрипта не глядел.

Обнови код воркера, я думаю это должно помочь.

**Comment by Baltazar500** [comment]
>Обнови код воркера, я думаю это должно помочь.

Да, дело было в этом.

>Если хотите, можно сделать прокси сайта.

Через воркер ? Даже если не через него, то стоит. Недоступность хоста rust-server-531j.onrender.com ломает работу скрипта.

**Comment by SashaXser** [comment]
> > Обнови код воркера, я думаю это должно помочь.
> 
> Да, дело было в этом.
> 
> > Если хотите, можно сделать прокси сайта.
> 
> Через воркер ? Даже если не через него, то стоит. Недоступность хоста rust-server-531j.onrender.com ломает работу скрипта.

Скрипт ломается только при отсутствии субтитров у видео. Могу сейчас сделать минипатч для того чтобы язык ставился на en если сервер не работает.

**Comment by SashaXser** [comment]
> > Могу сейчас сделать минипатч для того чтобы язык ставился на en если сервер не работает.
> 
> И такой костыль годится. Я его один чёрт добавил в список исключений для антиблокировщика, чтобы не ломался, но он с ием же успехом может быть поломан или вовсе заблокирован у кого-то ещё.

Вообщем, в utils/utils.js меняем функцию detectLang:

```
async function detectLang(cleanText) {
  try {
    const response = await fetch("https://rust-server-531j.onrender.com/detect2", {
      method: "POST",
      body: cleanText,
    });
    return await response.text();
  } catch (error) {
    return "en";
  }
}
```

**Comment by Baltazar500** [comment]
@SashaXser , мне как пользователю менять в vot-cloudflare-min.user.js 

Конкретно 

```
async function detectLang(cleanText) {
  const response = await fetch("https://rust-server-531j.onrender.com/detect", {
    method: "POST",
    body: cleanText,
  });
  return await response.text();
}
```
Правильно понимаю ?

Ещё момент. При внесении критичных изменений на воркере, что нужны для дальнейшей работы скрипта, в самом скрипте нужен чекинг наличия этих изменений на стороне воркера. Чтобы скрипт слал на воркер специфический запрос и ежели его нет - выдавал бы алерт, что нужно обновить код воркера. А то при наличии автоапдейта скрипт может очень "неожиданно" сломаться и причины поломки могут быть далеко неочевидны.

**Comment by ilyhalight** [comment]
добавлено в стабильную ветку
