### ISSUE TITLE
не удалось запросить перевод видео от 09.10.2023

### ISSUE THREAD

**Issue by InoI63** [ilyhalight/voice-over-translation#362]
Всем привет у меня сегодня перестал работать скрипт. Переустанавливал не помогло.
![image](https://github.com/ilyhalight/voice-over-translation/assets/147434707/c8379be5-9826-4643-ab70-b1f5eb77aa7c)

**Comment by SashaXser** [comment]
> Всем привет у меня сегодня перестал работать скрипт. Переустанавливал не помогло. ![image](https://user-images.githubusercontent.com/147434707/273665444-c8379be5-9826-4643-ab70-b1f5eb77aa7c.png)

Информативно, приступаем к решению проблему незамедлительно! 
(Ты можешь нормально описать проблему? Логи там скинуть, описать проблему детально.)

**Comment by InoI63** [comment]
> > Всем привет у меня сегодня перестал работать скрипт. Переустановка не помогла.![изображение](https://user-images.githubusercontent.com/147434707/273665444-c8379be5-9826-4643-ab70-b1f5eb77aa7c.png)
> 
> Информативно, приступаем к решению проблемы! (Ты можешь нормально описать проблему? Логи там скинуть, описать проблему подробно.)

Поставил скрипт вчера до вчерашнего вечера все работало, вчера вечером почему-то перестало.
![46435345](https://github.com/ilyhalight/voice-over-translation/assets/147434707/81cb79eb-e290-4ce6-a1fd-c192b8b5905d)

**Comment by InoI63** [comment]
> > Всем привет у меня сегодня перестал работать скрипт. Переустановка не помогла.![изображение](https://user-images.githubusercontent.com/147434707/273665444-c8379be5-9826-4643-ab70-b1f5eb77aa7c.png)
> 
> Информативно, приступаем к решению проблем! (Ты можешь нормально описать проблему? Логи там скинуть, описать проблему подробно.)

Поставил скрипт работал без проблем до вчерашнего вечера еще с утра работал в консоли вот так.
![33](https://github.com/ilyhalight/voice-over-translation/assets/147434707/9eb609dc-eda9-4334-8db4-f6f97b5eec3f)

**Comment by SashaXser** [comment]
> > > Всем привет у меня сегодня перестал работать скрипт. Переустановка не помогла.![изображение](https://user-images.githubusercontent.com/147434707/273665444-c8379be5-9826-4643-ab70-b1f5eb77aa7c.png)
> > 
> > 
> > Информативно, приступаем к решению проблем! (Ты можешь нормально описать проблему? Логи там скинуть, описать проблему подробно.)
> 
> Поставил скрипт работал без проблем до вчерашнего вечера еще с утра работал в консоли вот так. ![33](https://user-images.githubusercontent.com/147434707/273806445-9eb609dc-eda9-4334-8db4-f6f97b5eec3f.JPG) Использую Chrome. Версия 117.0.5938.150 (Официальная сборка), (64 бит) Поставил этот работает почему-то https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view Но вроде это более ранняя версия или нет?

Вы из Украины? Включите проксирование аудио в настройках.

**Comment by InoI63** [comment]
> > > > Всем привет у меня сегодня перестал работать скрипт. Переустановка не помогла.![изображение](https://user-images.githubusercontent.com/147434707/273665444-c8379be5-9826-4643-ab70-b1f5eb77aa7c.png)
> > > 
> > > 
> > > Информативно, приступаем к решению проблем! (Ты можешь нормально описать проблему? Логи там скинуть, описать проблему подробно.)
> > 
> > 
> > Поставил скрипт работал без проблем до вчерашнего вечера еще с утра работал в консоли вот так. ![33](https://user-images.githubusercontent.com/147434707/273806445-9eb609dc-eda9-4334-8db4-f6f97b5eec3f.JPG) Использую Chrome. Версия 117.0.5938.150 (Официальная сборка), (64 бит) Поставил этот работает почему-то https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view Но вроде это более ранняя версия или нет?
> 
> Вы из Украины? Включите проксирование аудио в настройках. VPN вроде тоже поможет решить эту ошибку.

Не из Украины. Из России.

**Comment by InoI63** [comment]
В общем работает https://drive.google.com/file/d/1KWUutZgy0QEWGG94fCXDWEQTDngZocm9/view
