### ISSUE TITLE
YandexGPT

### ISSUE THREAD

**Issue by FiLinX** [ilyhalight/voice-over-translation#364]
Ребят, вы вот уже собаку съели на хитростях общения с апи яндекса  -  так вот может быть кто из вас создаст новый проэкт тут на эту новую фичу  --  Яндекс-Пересказ? 
А?  )

**Comment by FiLinX** [comment]
цитаты с сайта яндекса:
 -- "можно получить текстовую выжимку из YouTube-роликов, загрузив ссылку на клип на сервис [300.ya.ru](https://300.ya.ru/)."
 -- "Нейросеть YandexGPT можно протестировать в собственном бизнесе — для этого нужно оставить [заявку](https://cloud.yandex.ru/services/yandexgpt) на доступ к API."

**Comment by ilyhalight** [comment]
Если я правильно понял, ты про то, что на скриншотах ниже? Если да, то для этого уже существует расширение

https://github.com/FOSWLY/summarize

![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/46bccdb5-b253-4b1f-be79-0dc8cb310ab8)
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/56bc9935-e9a1-4e36-88eb-4c74d4d1fcc7)
