### ISSUE TITLE
Не работает в Edge

### ISSUE THREAD

**Issue by rms1515** [ilyhalight/voice-over-translation#369]
Microsoft Edge
Version 118.0.2088.46 (Official build) (64-bit)

Кнопка есть. При нажатии переводит. Но после этого снижается звук оригинала, а перевод не звучит.
Пользуюсь через костыль. На кнопке "скачать" говорю "открыть в новой вкладке" и запускаю в ней перевод фоном, тем временем переключаюсь на вкладку с видео и запускаю его..
То есть, перевод есть! Но он почему-то не может сам наложиться на видео.
Пробовал обе версии скрипта.

**Comment by ilyhalight** [comment]
Что-то в консоли пишет?

**Comment by rms1515** [comment]
Извините чайника! Не догадался сразу там посмотреть!
Виновник экстэншн для YouTube - "Magic Actions".
Снёс и всё заработало.
