### ISSUE TITLE
Dropdown menus stopped working on youtube.com with Firefox, but only when the user is logged in

### ISSUE THREAD

**Issue by angrylion7** [ilyhalight/voice-over-translation#371]
The three dropdown menus, that is source language, desired language and subtitle language menus, suddenly stopped working on www.youtube.com with Firefox 118 approximately on October 17th, but only when you're logged in. Nothing happens when I click on the arrow buttons, even though, once the page has finished loading, all 3 fields are filled correctly with expected language name strings. Other supported sites work fine, and so do the same videos on piped.video. The rest of this script's GUI works fine on youtube.com, and previously created voice translations can be enabled.  Nothing suspicious is printed in the browser console when I enable voice translation or before that, and I can't enable subtitles because of these inactive dropdown menus. This might be connected to the new (?) youtube feature where you can enable 2x playback speed by clicking and holding left mouse button on the video area, as this feature only works when you're logged in. Other than logging off of youtube.com, the other workaround I found is installing this in Tampermonkey:
https://greasyfork.org/ru/scripts/473685-youtube-experiment-flags-tamer-basic 
I've checked with vot.user.js from both master and dev branches.
Apparently no problem in Chrome even when logged in and 2x playback speed feature active, so this is Firefox-specific.

**Comment by angrylion7** [comment]
It works if in Firefox Inspector you disable event listeners for both mousedown AND mouseover events for this div:
`<div class="html5-video-container" data-layer="0">`
These are 2 of the 3 new event listeners that are added to this div when the user is logged-in compared to logged-out. Chrome shows the same 5 event listeners when logged in (3 new ones + 2 that also exist when logged-out), but the `<select>` element added by VOT can expand its menu fine in Chrome, as reported before.

**Comment by krasnovpro** [comment]
Guys, please fix this issue.

**Comment by angrylion7** [comment]
Dropdown menus do show up in logged-in Firefox with Chrome's useragent (general.useragent.override in about:config). 

Also, this logged-in-only youtube's mousedown event handler in base.js that I mentioned seems to call event.preventDefault() on that very div very early (because some boolean variable shown as g.Rc is false) with the default useragent string, but so far I couldn't spot it ever calling event.preventDefault() with Chrome's useragent. Intuitively, this should be pertinent to this issue.

**Comment by ilyhalight** [comment]
Попробуйте бету 5
