### ISSUE TITLE
Добавление новых сайтов 

### ISSUE THREAD

**Issue by LSTAlex** [ilyhalight/voice-over-translation#373]
Доброго времени суток.
Есть ли возможность добавить этот скрипт как-то себе в хранилище?
У меня есть Synology, на нём лежат видео. Так же на нём есть плеер для просмотра видео. 
Доступ к этому плееру есть извне с любого браузера.
Пример ссылки доступа http://0.0.0.0:6505/?launchApp=SYNO.SDS.VideoStation.AppInstance&SynoToken=Gv0kXCgFWmNt.#!Home/N4IgNglgRgTghjAniAXCAtgewG4QKYC0ADCADQgDGcALngOaZKogx4V4B21YiA+nABMBeAWRAAHOHTyoAjAF8gA
Примерно так это выглядит:
![image](https://github.com/ilyhalight/voice-over-translation/assets/72004033/dfb856dc-a9d9-41ad-82d1-2ca3da517c2e)
![image](https://github.com/ilyhalight/voice-over-translation/assets/72004033/0376197a-c031-4032-828b-8bc35d6e9293)

Могу ли я сам сделать так, что бы видео переводились из этого плеера?
Я так понимаю нужно просто прописать его в качестве поддерживаемого сайта, но не знаю где и как.

**Comment by ilyhalight** [comment]
> Могу ли я сам сделать так, что бы видео переводились из этого плеера?

Есть у вас есть так же и субтитры для каждого видео, то можете добавить. Иначе перевод всегда будет возвращать ошибку

**Comment by LSTAlex** [comment]
Но эта api вроде как по описанию сама генерирует субтитры и их распознаёт

**Comment by ilyhalight** [comment]
> Но эта api вроде как по описанию сама генерирует субтитры и их распознаёт

Так только для поддерживаемых сайтов, для остальных необходима прямая ссылка на видео + vtt сабы
