### ISSUE TITLE
100% громкости\100% volume

### ISSUE THREAD

**Issue by Floyr** [ilyhalight/voice-over-translation#374]
Здравствуйте, дорогие разработчики! После обновления появилась проблема в Firefox, что не удаётся изменить громкость, скрипт переустанавливал, отключал всё доп. аддоны для проверки на конфликты, но проблема осталась. Можно ли это как-то исправить?
Firefox: version 118.0.2
script: 1.4.1

**Comment by ilyhalight** [comment]
Попробуйте бета версию скрипта, возможно, там проблемы нету

**Comment by Floyr** [comment]
Увы, это не помогло. Откат к старым версиям и новым не дали результата. Возможно, обновления браузера как-то задело скрипт.
Думаю, это всё, что можно сделать, верно?

**Comment by Floyr** [comment]
Также, заметил, что сейчас выдаёт ошибку: "[VOT] Не удалось записать данные в базу данных", при попытке изменить громкость

**Comment by Floyr** [comment]
Это очень странно, но повторная переустановка на версию 1.5 бета - помогла.
