### ISSUE TITLE
[Bug] Не появляется плашка скрипта на некоторых видео

### ISSUE THREAD

**Issue by iG8R** [ilyhalight/voice-over-translation#378]
Собственно, название темы само за себя говорит.
Пример проблемного видео https://www.youtube.com/watch?v=YV1ONa2iaYI
 - Версия скрипта 1.5.0-beta4
 - OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
 - Browser: Firefox 119.0 64bit
 - Browser: Chrome 118.0.5993.90 (Official Build) (64-bit)
 - Browser: Edge 118.0.2088.69 (Official build) (64-bit)

**Comment by SashaXser** [comment]
> Собственно, название темы само за себя говорит. Пример проблемного видео https://www.youtube.com/watch?v=YV1ONa2iaYI
> 
>     * Версия скрипта 1.5.0-beta4
> 
>     * OS: Microsoft Windows [Version 10.0.19045.2673] 64bit
> 
>     * Browser: Firefox 119.0 64bit
> 
>     * Browser: Chrome 118.0.5993.90 (Official Build) (64-bit)
> 
>     * Browser: Edge 118.0.2088.69 (Official build) (64-bit)

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/75f6f09b-02f3-4002-97ef-1c2dc625366e)

**Comment by iG8R** [comment]
Скорее всего, эта такая же ситуация, как и была ранее писана здесь - https://github.com/ilyhalight/voice-over-translation/issues/189

[VOT-popup-bar-doesnt-appear-Video_2023-10-27_121139.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/536889c6-abd1-4618-83ab-a04614019d6a)

**Comment by SashaXser** [comment]
> Скорее всего, эта такая же ситуация, как и была ранее писана здесь - #189
> VOT-popup-bar-doesnt-appear-Video_2023-10-27_121139.webm

Попробуй скачать и установить скрипт из [артефактов](https://github.com/ilyhalight/voice-over-translation/actions/runs/6660539709)
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/065956d8-ec60-436d-ae85-982f7db7b000)

**Comment by iG8R** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/8a2f439f-9807-48a1-a5fa-2c2bcf0ab112)

**Comment by SashaXser** [comment]
> ![image](https://user-images.githubusercontent.com/11407417/278601501-8a2f439f-9807-48a1-a5fa-2c2bcf0ab112.png)

Попробуй сбросить данные о ютубе, или удали базу данных вручную. Обычно должно помочь.

**Comment by iG8R** [comment]
Сбросить данные о ютубе - имеется в виду cookies?

**Comment by SashaXser** [comment]
> Сбросить данные о ютубе - имеется в виду cookies?

Ну да, я просто не помню удаляет ли Chrome при сбросе IDB или нет.

**Comment by iG8R** [comment]
После сброса cookies плашка появилась, но не дает возможности устастановить язык перевода, оба языка установлены на English.

![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/d269fd37-7718-4319-9127-6cf3a6427ed9)

**Comment by SashaXser** [comment]
> После сброса cookies плашка появилась, но не дает возможности установить язык перевода, оба языка установлены на English.
> 
> ![image](https://user-images.githubusercontent.com/11407417/278609329-d269fd37-7718-4319-9127-6cf3a6427ed9.png)

Интересно, у вас что-то конфликтующие?

**Comment by iG8R** [comment]
Попробовал на абсолютно чистом профиле Firefox, только установлен TemperMonkey и в для него только 1 скрипт - VOT.

[VOT-clean-Fierfox-Video_2023-10-27_134603.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/b2fe2673-ef36-465c-afb9-3d4a9289623d)

PS. Edge и Chrome с артефактным скриптом работают нормально.

**Comment by iG8R** [comment]
Сейчас вспомнилось, что пару дней назад всё работало в Firefox нормально, но позавчера обновился на 119.0 версию с 118.0.2.

**Comment by SashaXser** [comment]
> Сейчас вспомнилось, что пару дней назад всё работало в Firefox нормально, но позавчера обновился на 119.0 версию с 118.0.2.

Возможно что-то во время обновления сломалась. Предлагаю попробовать в VioletMonkey, может быть в нем заработает :/

**Comment by iG8R** [comment]
Обычный VOT в VioletMonkey совсем не запустился, а Cloudflare версия также, как и в TemerMonkey не позволяет выбрать язык источника и перевода.
<img src="https://github.com/ilyhalight/voice-over-translation/assets/11407417/023242be-16ab-46cb-bdd8-f44d2e618510" width="550">

**Comment by SrevSA** [comment]
Жаль ответ от Гуру так и не получил. Видео с переводом на Украинский не работает. Постоянно пишет ошибку перевода. Смена нескольких браузеров и версий скрипта не помогла. Может кто то подскажет? Заранее благодарю

**Comment by SashaXser** [comment]
> Жаль ответ от Гуру так и не получил. Видео с переводом на Украинский не работает. Постоянно пишет ошибку перевода. Смена нескольких браузеров и версий скрипта не помогла. Может кто то подскажет? Заранее благодарю

Яндекс что-то тестирует, или отключил на совсем. Спросите лично у Яндекса, не в курсе, что там у них.

**Comment by ilyhalight** [comment]
> Жаль ответ от Гуру так и не получил. Видео с переводом на Украинский не работает. Постоянно пишет ошибку перевода. Смена нескольких браузеров и версий скрипта не помогла. Может кто то подскажет? Заранее благодарю

Пару дней назад перестали работать все доп. языки на которые можно было перевести видео. Причина мне неизвестна, но остается надеяться, что это временно.

> Сейчас вспомнилось, что пару дней назад всё работало в Firefox нормально, но позавчера обновился на 119.0 версию с 118.0.2.

Это независит от версии браузера. Ютуб что-то изменили из-за чего в файрфоксе перестали работать все дропдауны сделанные через тег select, пока, не знаю как это можно было бы пофиксить, кроме того, чтобы сделать кастомный дропдаун
#371

**Comment by SrevSA** [comment]
К сожалению сервера Яндекс бастуют и перевод на украинский не решен. Очень жаль. Решение было идеальным. Я только могу поблагодарить вас за проделанную работу, но увы ,моя проблема не решена. Я о последней 
вашей Бете сейчас.
