### ISSUE TITLE
Не удается перевести видео , попробуйте позже(позже тоже не работает)

### ISSUE THREAD

**Issue by SneNiga** [ilyhalight/voice-over-translation#379]
Такая проблема наверное почти со всеми языками , я рандомно попробовал 2 каких-то , точно пробовал индонезийский и китайский , не работает.
Переводит только на английский язык.
Пробовал с VPN и без него.Даже через другой бразуер , все равно эта ошибка 
"....попробуйте позже" я пробовал на 10-15 видео и позже и не позже , Не пашет((
![Снимок экрана 2023-10-27 в 23 13 59](https://github.com/ilyhalight/voice-over-translation/assets/149182830/1d36321d-ed8c-4f3a-8c0d-e38b31e86149)

**Comment by ilyhalight** [comment]
Сейчас, работает перевод, только, на те языки, которые до разделителя (и то не все). В любом случае, проблема на стороне яндекса.
