### ISSUE TITLE
video is too long

### ISSUE THREAD

**Issue by A1brus** [ilyhalight/voice-over-translation#380]
![Скриншот 28-10-2023 151225](https://github.com/ilyhalight/voice-over-translation/assets/60397054/cc37af37-6bc9-4557-9763-1b57b12d02c4)

так же не работает и изменение языка, например тут youtube.com/watch?v=4kfb5lXmmmo

**Comment by SashaXser** [comment]
> ![Скриншот 28-10-2023 151225](https://user-images.githubusercontent.com/60397054/278806937-cc37af37-6bc9-4557-9763-1b57b12d02c4.jpg)
> 
> так же не работает и изменение языка, например тут youtube.com/watch?v=4kfb5lXmmmo

Не соответствует действительности, видео отлично переводится.

**Comment by ilyhalight** [comment]
У меня все переводит с бета версией скрипта

> так же не работает и изменение языка

Уже известно #371
