### ISSUE TITLE
При смене окна (Alt tab) и возращении обратно не работает продолжение воспроизведения видео через пробел

### ISSUE THREAD

**Issue by Damil61** [ilyhalight/voice-over-translation#382]
При смене окна (Alt tab) и возращении обратно не работает продолжение воспроизведения видео через пробел, начинает работать только если продолжить видео с помощью мыши

**Comment by SashaXser** [comment]
> При смене окна (Alt tab) и возращении обратно не работает продолжение воспроизведения видео через пробел, начинает работать только если продолжить видео с помощью мыши

В каком браузере?

**Comment by Damil61** [comment]
Edge и Chrome

**Comment by vmrfriz** [comment]
Firefox тоже
