### ISSUE TITLE
С 2 ноября перестал работать перевод на любые другие языки кроме русского

### ISSUE THREAD

**Issue by PavelMSW** [ilyhalight/voice-over-translation#386]
Добрый день. 
Версия скрипта 1.4.1
С 2 ноября перестал работать перевод на любые другие языки кроме русского. 
Сообщение об ошибке "Возникла ошибка при переводе, повторите попытки позже". 
Ошибка наблюдается стабильно уже вторые сутки на разных видео, в разных браузерах, на разных компьютерах, любых направлениях языкового перевода кроме как на русский язык.

**Comment by SashaXser** [comment]
> Добрый день. Версия скрипта 1.4.1 С 2 ноября перестал работать перевод на любые другие языки кроме русского. Сообщение об ошибке "Возникла ошибка при переводе, повторите попытки позже". Ошибка наблюдается стабильно уже вторые сутки на разных видео, в разных браузерах, на разных компьютерах, любых направлениях языкового перевода кроме как на русский язык.

Работают вроде Казахский, Немецкий, Английский. Может быть есть ещё, надо обновить список поддерживаемых языков. Казахский точно должен работать. Можете также попробовать бета версию.

**Comment by PavelMSW** [comment]
Благодарю Вас за оперативный ответ, проверил сейчас еще раз

https://www.youtube.com/watch?v=oOELj--RrXA
Тестировал перевод с русского на немецкий

https://www.youtube.com/watch?v=aJX5jg7cW5M
Тестировал перевод с английского на немецкий и испанский

Результат во всех случаях "Возникла ошибка при переводе, повторите попытки позже". Использовал ранее каждый день все работало всегда без проблем. Скрины из браузера Brave на движке хрома, проверял в яндекс браузере те же самые ошибки.

Прикладываю скрины результатов.
![2023-11-03_11-09-48](https://github.com/ilyhalight/voice-over-translation/assets/145162476/0643ff7e-d5c8-4b10-9a52-275b41bb40b5)
![2023-11-03_11-09-02](https://github.com/ilyhalight/voice-over-translation/assets/145162476/2d3df6ec-3a85-4590-be4a-67c62fdbc58e)
![2023-11-03_11-08-23](https://github.com/ilyhalight/voice-over-translation/assets/145162476/4c4f17ef-9b3d-4bd3-9031-cc9d5e829cfb)

Подскажите пожалуйста где я могу скачать beta версию скрипта для Tampermonkey

**Comment by SashaXser** [comment]
> Благодарю Вас за оперативный ответ, проверил сейчас еще раз
> 
> https://www.youtube.com/watch?v=oOELj--RrXA Тестировал перевод с русского на немецкий
> 
> https://www.youtube.com/watch?v=aJX5jg7cW5M Тестировал перевод с английского на немецкий и испанский
> 
> Результат во всех случаях "Возникла ошибка при переводе, повторите попытки позже". Использовал ранее каждый день все работало всегда без проблем. Скрины из браузера Brave на движке хрома, проверял в яндекс браузере те же самые ошибки.
> 
> Прикладываю скрины результатов. ![2023-11-03_11-09-48](https://user-images.githubusercontent.com/145162476/280216979-0643ff7e-d5c8-4b10-9a52-275b41bb40b5.png) ![2023-11-03_11-09-02](https://user-images.githubusercontent.com/145162476/280216986-2d3df6ec-3a85-4590-be4a-67c62fdbc58e.png) ![2023-11-03_11-08-23](https://user-images.githubusercontent.com/145162476/280216988-4c4f17ef-9b3d-4bd3-9031-cc9d5e829cfb.png)
> 
> Подскажите пожалуйста где я могу скачать beta версию скрипта для Tampermonkey

Бету можно скачать в [релизах](https://github.com/ilyhalight/voice-over-translation/releases). Похоже, опять что-то порезали, вчера насколько я помню перевод на Немецкий работал.

**Comment by PavelMSW** [comment]
Благодарю за ответ.
Установил [1.5.0-beta5](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta5) Pre-release.
Протестировал, результат тот же самый "Возникла ошибка при переводе, повторите попытки позже"
Работает перевод только на русский и с русского на английский, все остальные направления теперь выдают ошибку.
Подскажите есть ли возможность это исправить?

**Comment by PavelMSW** [comment]
Печально конечно, это был весьма полезный сервис. Подскажите пожалуйста известны ли Вам какие либо альтернативные сервисы с аналогичным функционалом?

**Comment by ilyhalight** [comment]
Сейчас перевод точно работает только на русский, казахский, английский. Другие языки были отключены Яндексом.

**Comment by ilyhalight** [comment]
> Сейчас перевод точно работает только на русский, казахский, английский. Другие языки были отключены Яндексом.

Как думаете, как будет лучше: удалить их полностью из выборки или просто пометить?

**Comment by PavelMSW** [comment]
> > Сейчас перевод точно работает только на русский, казахский, английский. Другие языки были отключены Яндексом.
> 
> Как думаете, как будет лучше: удалить их полностью из выборки или просто пометить?

Лучше пока просто пометить

**Comment by ilyhalight** [comment]
В бете пометил
