### ISSUE TITLE
Не появляется панель поверх youtube-видео при работе опции предотвращения автоматического проигрывания видео

### ISSUE THREAD

**Issue by iG8R** [ilyhalight/voice-over-translation#387]
Имеется аддон для Firefox `Enhancer for YouTube`, у которого имеется такая функция, как "Prevent videos loaded in background tabs from automatically playing" (при загрузке страницы с видео, не дает этоу видео автоматически начать проигрывание), после включения которой перестает появляться панель VOT даже после начала проигрывания видео.
Можно ли как-то эту проблему решить?

[VOT-Youtube-Stop-Video_2023-11-03_142046_FFB.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/7c4a6ac5-12ff-4dd2-985c-6b76d6effaf2)

**Comment by iG8R** [comment]
Да, я видел это примечание еще со времен, как начал пользоваться VOT, а это была версия 0.95 или что-то вроде того. Но до этого ни разу таких проблеи не возникало, потому и спрашиваю, возможно ли как-то вернуть прежнюю способность VOTa не обращать внимания на такую особенность воспроизведения видео.

**Comment by iG8R** [comment]
И, насколько я понимаю, это примечание относилось к особенности самих браузером и их опции Autoplay -> Allow Audio and Video, а здесь аддон использует саму особенность Youtube.
Опять же, до того, как что-то глюкнуло в Firefox и VOT перестал давать возможность выбора языков перевода из списка, всё работало отлично с этим аддоном.

**Comment by SashaXser** [comment]
> Да, я видел это примечание еще со времен, как начал пользоваться VOT, а это была версия 0.95 или что-то вроде того. Но до этого ни разу таких проблеи не возникало, потому и спрашиваю, возможно ли как-то вернуть прежнюю способность VOTa не обращать внимания на такую особенность воспроизведения видео.

Покажи логи консоли, может быть что-то узнаем.

**Comment by iG8R** [comment]
ОК

**Comment by iG8R** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/881e463a-9348-41a1-92ae-a060aea52128)

**Comment by iG8R** [comment]
Ранее тоже было так, что когда появлялась страница видео в режиме остановки, панели VOT не было видно, но только стоило начать воспроизведение, и он сразу же подгружался и панель появлялась.

**Comment by SashaXser** [comment]
> Ранее тоже было так, что когда появлялась страница видео в режиме остановки, панели VOT не было видно, но только стоило начать воспроизведение, и он сразу же подгружался и панель появлялась.

Попробовал воспроизвести проблему, что-то не получилось. (Тестировал свой скомпилированный [скрипт](https://github.com/SashaXser/voice-over-translation/tree/dev/dist))
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/6fdac979-0685-4177-a01f-7bffa858516e)

**Comment by iG8R** [comment]
В Firefox?

**Comment by SashaXser** [comment]
> В Firefox?

В Firefox этот аддон удалён из магазина. Не могу скачать протестировать :/

**Comment by iG8R** [comment]
Точно, сейчас проверил - нет аддона в магазине... У моего стоит дата последнего обновления 23.08.2023
Есть другой - Tweaks for Youtube https://addons.mozilla.org/en-US/firefox/addon/tweaks-for-youtube/
Почти в самом конце настроек есть такие пункты
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/ae9d38bf-911b-461a-84f3-9580750b04be)

**Comment by iG8R** [comment]
Ха, отключил Enhancer for Youtube и всё заработало. Видимо что-то с аддоном случилось, что его даже удалил из магазина.

**Comment by SashaXser** [comment]
> А вот и не всё так просто. На этом видео панель так и не появляется. https://www.youtube.com/watch?v=MFO7XTwUeSM

Что-то есть в консоли? Желательно лог только ошибок

**Comment by iG8R** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/ac7f1090-f3c6-4209-9bfb-738b0d1bdb55)

**Comment by iG8R** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/807930a4-be72-4e8c-9c51-b2566cca09bb)

**Comment by SashaXser** [comment]
> ![image](https://user-images.githubusercontent.com/11407417/280312665-ac7f1090-f3c6-4209-9bfb-738b0d1bdb55.png)

Не инициализировалась база данных, распространенная проблема. Сбрось IndexedDB, обычно помогает.

**Comment by iG8R** [comment]
Уже постоянно очищаю куки, вот только на одних видео все нормально, а другие - вот с такой проблемой. И это не зависит от того, когда я делал очистку куки - может сразу возникнуть после очищения базы, а может через несколько видео.

**Comment by iG8R** [comment]
Причем, на одном и том же видео - сначала может не появлться панель, после перезагрузки страницы (по F5) - поялвяется, затем вновь после повторного обновления панель не поялвяется. Но есть особо упорные видео, только после 5го-7го перезагрузки страницы VOT успешно показывает панель. На скорость инета и пинг не жалуюсь - 1Гб/с
```
Pinging youtube.com [142.250.203.206] with 32 bytes of data:
Reply from 142.250.203.206: bytes=32 time=14ms TTL=119
Reply from 142.250.203.206: bytes=32 time=14ms TTL=119
Reply from 142.250.203.206: bytes=32 time=14ms TTL=119
Reply from 142.250.203.206: bytes=32 time=14ms TTL=119
```

**Comment by SashaXser** [comment]
> Уже постоянно очищаю куки, вот только на одних видео все нормально, а другие - вот с такой проблемой. И это не зависит от того, когда я делал очистку куки - может сразу возникнуть после очищения базы, а может через несколько видео.

Попробовал переписать логику инициализации, попробую [фикс](https://github.com/SashaXser/voice-over-translation/tree/dev/dist)

**Comment by iG8R** [comment]
Горааааздо лучше стало, из 7 видео, тольо 1 не показало панели с первого раза.

**Comment by SashaXser** [comment]
> Горааааздо лучше стало, из 7 видео, тольо 1 не показало панели с первого раза.

Я могу попытаться его полностью вырезать если возникнут проблемы.

**Comment by iG8R** [comment]
За это время сложилась следующая ситуация - каждые 3-5 видео с первого раза не подгружают панель VOT, приходится от одного до нескольких раз перезагружать видео, чтобы наконец панель появилась.

**Comment by SashaXser** [comment]
> За это время сложилась следующая ситуация - каждые 3-5 видео с первого раза не подгружают панель VOT, приходится от одного до нескольких раз перезагружать видео, чтобы наконец панель появилась.

Вырезал полностью, перекачай скрипт из моего репозитория.

**Comment by iG8R** [comment]
Теперь ситуация такая:
Захожу на главную страницу Youtube и открываю 15 вкладок на новой странице - из этих 15 только 4 показали с первого раза панель VOT. Но если обновить страницы - тот панель появляется. Причем, если не открывать новые вкладки, а прям на главной странице нажать на видео, чтобы он загрузилось в этом же окне, или в новых открытых вкладках нажать на любое другое видео - то они загрузятся уже с панелью без проблем.

Вот лог тех видео, которые с первого раза не подгрузили панель:
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/e9be7f00-d99e-417f-a956-f72e402935d6)

А это лог видео, у которых с первого раза появилась панель:
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/39ab732e-5f58-48d1-aa87-dd20a1fe19eb)

**Comment by FiLinX** [comment]
> Захожу на главную страницу Youtube и открываю 15 вкладок на новой странице - из этих 15 только 4 показали с первого раза панель VOT

https://github.com/ilyhalight/voice-over-translation/discussions/368#discussioncomment-7286501

**Comment by iG8R** [comment]
@FiLinX 
Раньше, до недавних событий с Youtube, когда они там что-то подкрутили и в Firefox перестал работать выбор языков, именно такого поведения не было, когда одни видео подгружают сразу панель VOT, а другие - нет. Если уже не появлялась панель, то всегда, как бы я не обновлял страницы.
Даже по приведенным выше логам видно, как отличается поведение VOT на разных страницах. Причем, даже если неоднократно одну и ту же страницу открывать в новой вкладке (не важно, будет это фоновая загрузка или сразу будет переключение на эту вкладку), несмотря на то, что страница уже находится в cache браузера, все равно панель VOT не появляется.

**Comment by ilyhalight** [comment]
Попробуйте обновиться до 1.5.0 бета 8. В ней, вроде как, пофиксил (по крайней мере, у меня перестало воспроизводиться)

**Comment by iG8R** [comment]
Можно сказать проблема решена, но есть маленький ньюанс.
Раньше панель поялалась даже поверх стоп-картинки видео, сейчас, в некоторых случаях, при загрузке видео, когда еще стоп картинка не подгрузилась, видно, что панель VOT появилась, но при дальнейшей загрузке видео и появлении стоп-картинки, панель исчезает и не позволяет заранее нажать на неё, для начала перевода, только после начала воспроизведения видео это можно сделать.

[VOT-Panel-over-video-Video_2023-11-08_030527.webm](https://github.com/ilyhalight/voice-over-translation/assets/11407417/7bef712d-8729-443c-9931-a44c0301e646)

**Comment by BEELINEUA13** [comment]
> Попробуйте обновиться до 1.5.0 бета 8. В ней, вроде как, пофиксил (по крайней мере, у меня перестало воспроизводиться)

А как установить эту бету?? я вобще новичок в этом

**Comment by iG8R** [comment]
@BEELINEUA13 

![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/8c076b1f-0036-46d9-a30c-bcbeba08c45f)
![image](https://github.com/ilyhalight/voice-over-translation/assets/11407417/dc4eae5b-dca3-4549-b410-a0362803f0d7)

**Comment by BEELINEUA13** [comment]
> @BEELINEUA13
> 
> ![image](https://user-images.githubusercontent.com/11407417/281371875-8c076b1f-0036-46d9-a30c-bcbeba08c45f.png) ![image](https://user-images.githubusercontent.com/11407417/281371928-dc4eae5b-dca3-4549-b410-a0362803f0d7.png)

Спасибо большое

**Comment by ilyhalight** [comment]
добавлено в стабильную ветку
