### ISSUE TITLE
не работает выбор языков на видео в ютуб

### ISSUE THREAD

**Issue by A1brus** [ilyhalight/voice-over-translation#388]
пример: https://www.youtube.com/watch?v=9CAwvKiLICs&t=8s
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/60397054/e1ac98e1-9404-44d9-b277-d29445aad717)
В данной рамке нельзя выбрать возможность изменение языка.
При попытке - открывается видео на весь экран.
последняя версия firefox.
почему в настройках расширения не добавить "ваш язык", переводить на "язык"?
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/60397054/ec02d55b-296a-4f67-826e-817f346ac1b4)

**Comment by ilyhalight** [comment]
Обновитесь до последней беты

> почему в настройках расширения не добавить "ваш язык", переводить на "язык"?

не понял вопроса

**Comment by vmrfriz** [comment]
Установил 1.5.0-beta7 на firefox, проблема решена. [Ссылка на установку](https://github.com/ilyhalight/voice-over-translation/raw/1.5.0-beta7/dist/vot.user.js) для тех, кто не нашёл
