### ISSUE TITLE
Не работает перевод в pornhub

### ISSUE THREAD

**Issue by Alecsyi666** [ilyhalight/voice-over-translation#391]
Всем привет,  не работает перевод в pornhub, неактивна кнопка "перевести" ( нажимаю никак не реагирует ) использую браузер Firefox. Кто нибудь сталкивался с этим?

**Comment by ilyhalight** [comment]
у вас релизная версия или бета? Если релизная, то попробуйте бету

**Comment by Alecsyi666** [comment]
Tampermonkey beta и vot 1.5.0 beta7 попробовал кнопка перевести видео вообще не появляется.

**Comment by joyboyy99** [comment]
Такой же косяк, но кнопку натыкать смог, случайно тыкнул и открылись настройки перевода. По сути кнопка есть, но она невидима

**Comment by ilyhalight** [comment]
В 1.5.0 бета 8 исправил

**Comment by yuzbashyan1994-dev** [comment]
> Всем привет, не работает перевод в pornhub, неактивна кнопка "перевести" ( нажимаю никак не реагирует ) использую браузер Firefox. Кто нибудь сталкивался с этим?

У меня тоже самое вот второй день не работает хотя до этого все работало!

**Comment by umnikivan3-arch** [comment]
Да у меня тоже не работает
