### ISSUE TITLE
Не работает перевод в Udemy 

### ISSUE THREAD

**Issue by Shukhrat-03** [ilyhalight/voice-over-translation#392]
Сделал как указана. Токены тоже поставил.

**Comment by ilyhalight** [comment]
Что пишет?

**Comment by Shukhrat-03** [comment]
не удалось получить данный, необходимые для перевода.

**Comment by Shukhrat-03** [comment]
![Снимок экрана 2023-11-05 212956](https://github.com/ilyhalight/voice-over-translation/assets/126561696/953e2482-7ea9-4a22-ac76-4531b355cac6)

**Comment by ilyhalight** [comment]
Возможно, не удается найти субтитры или видео в нужном формате. Если бы у вас была бета, то в консоли было бы написано что именно не найдено

**Comment by Shukhrat-03** [comment]
Вот бета версия тоже не работает.
![Снимок экрана 2023-11-06 103946](https://github.com/ilyhalight/voice-over-translation/assets/126561696/bb42831f-c3e4-4bc9-a68c-483b1cd32907)
![Снимок экрана 2023-11-06 104010](https://github.com/ilyhalight/voice-over-translation/assets/126561696/78e2fb21-aa60-4a69-909d-65f51092951e)

**Comment by ilyhalight** [comment]
> Вот бета версия тоже не работает. ![Снимок экрана 2023-11-06 103946](https://user-images.githubusercontent.com/126561696/280588913-bb42831f-c3e4-4bc9-a68c-483b1cd32907.png) ![Снимок экрана 2023-11-06 104010](https://user-images.githubusercontent.com/126561696/280588949-78e2fb21-aa60-4a69-909d-65f51092951e.png)

смотрите сообщения в консоли.

**Comment by Shukhrat-03** [comment]
как посмотреть.

**Comment by ilyhalight** [comment]
> как посмотреть?

f12 и там ищете строку вида videoURL: ....., subtitleURL: ....

**Comment by Shukhrat-03** [comment]
> > как посмотреть?
> 
> f12 — консоль и там находится символ вида videoURL: ....., subtitleURL: ....

![image](https://github.com/ilyhalight/voice-over-translation/assets/126561696/a295093d-02af-4588-8a76-89efb55fa399)
![image](https://github.com/ilyhalight/voice-over-translation/assets/126561696/a35ab808-b1ad-4e92-87d1-04afa2cfc1c3)

**Comment by ilyhalight** [comment]
> > > как посмотреть?
> > 
> > 
> > f12 — консоль и там находится символ вида videoURL: ....., subtitleURL: ....
> 
> ![image](https://user-images.githubusercontent.com/126561696/280795595-a295093d-02af-4588-8a76-89efb55fa399.png) ![image](https://user-images.githubusercontent.com/126561696/280795771-a35ab808-b1ad-4e92-87d1-04afa2cfc1c3.png)

Как я и говорил, видео в неподдерживаемом формате. Тут ничего не сделать

**Comment by Shukhrat-03** [comment]
Можно ли скачать видео?

**Comment by ilyhalight** [comment]
> Можно ли скачать видео?

Можно, там, где-то в консоли должна хранится ссылка. Если это не отключено в скомпиленной версии

**Comment by Shukhrat-03** [comment]
Было бы здорово, если бы вы показали на примере, я смог найти.

**Comment by Shukhrat-03** [comment]
https://github.com/ilyhalight/voice-over-translation/issues/392#issuecomment-1795899567

Будет ли решение на будущем?
