### ISSUE TITLE
Не работает перевод в bilibili.com

### ISSUE THREAD

**Issue by whitemankpi** [ilyhalight/voice-over-translation#393]
![зображення](https://github.com/ilyhalight/voice-over-translation/assets/63373322/37f965b1-56ac-40b7-8e70-aaa2714f9909)
Не работает перевод в bilibili.com

**Comment by SashaXser** [comment]
> ![зображення](https://user-images.githubusercontent.com/63373322/280538135-37f965b1-56ac-40b7-8e70-aaa2714f9909.png) Не работает перевод в bilibili.com

Скачайте бету и отпишите о результатах. Если проблема осталась, покажи логи консоли.

**Comment by ilyhalight** [comment]
Нужно больше информации. Попробуйте бету, попробуйте другое видео, попробуйте другую языковую пару (если она отличается от китайский-русский)
