### ISSUE TITLE
[menu] The is chevron trimmed

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#397]
v1.5.0 beta 8

<img width="288" alt="Screen Shot 2023-11-08 at 12 00 19" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/057c75a5-5139-44b8-8ad5-1fb7b9f4738a">

---

<img width="620" alt="Screen Shot 2023-11-08 at 12 12 17" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/0337e25e-2a44-4842-8822-ef77397a4e3c">

**Comment by ilyhalight** [comment]
fixed in beta9
