### ISSUE TITLE
[menu] Preferably, the words should not be reduced in size

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#398]
v1.5.0 beta 8

<img width="316" alt="Screen Shot 2023-11-08 at 12 16 40" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/6e0caaf1-efec-4124-ba3e-e723a09a05cc">

---

<img width="460" alt="Screen Shot 2023-11-08 at 12 17 31" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/3b288696-c856-43bd-b6cd-09176c0f4405">

**Comment by ilyhalight** [comment]
A forced measure. There are long words that just don't fit into a dropdown of this length.

If you disable word trimming using a "...", then part of the word will be completely cut off.
And if you remove the restriction, the menu sizes will "float".
If you just try to reduce the font, you will have to reduce it to 10px

**Comment by Oleg-Chashko** [comment]
Maybe increase the horizontal size by a couple of millimeters?

<img width="282" alt="Screen Shot 2023-11-08 at 13 37 05" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/655dd058-d708-4bbd-9f97-4b44277b4da2">

**Comment by ilyhalight** [comment]
> Maybe increase the horizontal size by a couple of millimeters?
> <img alt="Screen Shot 2023-11-08 at 13 37 05" width="282" src="https://user-images.githubusercontent.com/62497891/281387729-655dd058-d708-4bbd-9f97-4b44277b4da2.png">

I would not particularly like to increase the length of the menu again. Anyway, for some languages and subtitles, three dots will be needed.

I got 2 options without changing the width:
1) All major languages except French and Italian are placed (without visible changes)
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/2ebb21ed-09be-4f3f-9873-35f24e53b9eb)

2) All the main languages are placed (the chevron is slightly reduced)
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/51590b1f-f131-43a0-81f1-90e863624893)

**Comment by Oleg-Chashko** [comment]
👍🏻 🎉

**Comment by ilyhalight** [comment]
fixed in beta9

**Comment by Oleg-Chashko** [comment]
Beta9

<img width="464" alt="Screen Shot 2023-11-17 at 8 34 06" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/4da7dda6-afa8-4757-8757-803588071fd8">

**Comment by ilyhalight** [comment]
> Beta9
> <img alt="Screen Shot 2023-11-17 at 8 34 06" width="464" src="https://user-images.githubusercontent.com/62497891/283703304-4da7dda6-afa8-4757-8757-803588071fd8.png">

the name is too long, if you increase the length, then there will be a different size with the upper dropdown

**Comment by Oleg-Chashko** [comment]
> the name is too long, if you increase the length, then there will be a different size with the upper dropdown

Increase the size in both the top and bottom dropdown menus by ~3mm.  To make everything fit, is that possible?

**Comment by ilyhalight** [comment]
> > the name is too long, if you increase the length, then there will be a different size with the upper dropdown
> 
> Increase the size in both the top and bottom dropdown menus by ~3mm. To make everything fit, is that possible?

in order for everything to fit, including all languages for translation and TTS, you need to increase the size of the menu to at least 375 pixels, which is a lot.
