### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by KobMiles** [ilyhalight/voice-over-translation#399]
Вылазит такая ошибка на любых видео

**Comment by ilyhalight** [comment]
Попробуйте cloudflare версию

**Comment by KobMiles** [comment]
Где в коде можно поменять домен?

**Comment by ilyhalight** [comment]
> Где в коде можно поменять домен?

### Домен воркера
Если в собранном, то через поиск найдите "// CLOUDFLARE CONFIGURATION" и там переменная workerHost будет отвечать за домен. 
Если в сурсах, то /src/config/config-cloudflare.js -> переменная workerHost

### Домен m3u8 воркера
Если в собранном, то через поиск найдите "// CONFIGURATION" и там переменная m3u8ProxyHost будет отвечать за домен. 
Если в сурсах, то /src/config/config.js -> переменная m3u8ProxyHost
