### ISSUE TITLE
Кнопка перевода не работает в https://rt.pornhub.com/

### ISSUE THREAD

**Issue by ilmini09** [ilyhalight/voice-over-translation#402]

**Comment by ilmini09** [comment]
Кнопка перевода не работает в

**Comment by SashaXser** [comment]
> Кнопка перевода не работает в

Скачай бету, и попроси корову больше не кушать твои слова.

**Comment by ilmini09** [comment]
Uploading scrnli_09-11-2023_17-09-25.mp4…

**Comment by ilyhalight** [comment]
Обновитесь до последней беты
