### ISSUE TITLE
Add: language selection option to "do not translate from native language"

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#403]
Add: language selection option to "do not translate from native language". 
Since the browser language is not always the native language for some users.

<img width="460" alt="Screen Shot 2023-11-10 at 15 59 15" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/e8877b96-aa60-4a88-a357-bff8e268c9e5">

**Comment by SashaXser** [comment]
Ну тогда уж сразу по языку меню можно)

**Comment by Oleg-Chashko** [comment]
> Ну тогда уж сразу по языку меню можно)

Yes and no. I don't know which is better. Maybe more choice for the user is better.

**Comment by ilyhalight** [comment]
added in beta9
