### ISSUE TITLE
Формат аудио не поддерживается. EDGE 

### ISSUE THREAD

**Issue by JustUserFromMars** [ilyhalight/voice-over-translation#404]
Формат аудио не поддерживается. В EDGE. Проблема появилась сегодня, ближе к утру кажется. До этого смотрел нормально. 11.10.23. В Файрфоксе нормально работает

**Comment by JustUserFromMars** [comment]
Может проблема в EDGE?

**Comment by ilyhalight** [comment]
Попробуй cloudflare версию

**Comment by JustUserFromMars** [comment]
Заработало☹ ХЗ в чем было дело. О cloudflare ничего не знаю)) Но попробую если вновь че. Спасибо за ответ и ЗА РАСШИРЕНИЕ!👍 Оно Охуенно! Если б еще можно было откатывать, удалять озвучку, дабы перевести по новой. В некоторых есть ляпы с повторениями. Но это наверное к Яндексу?!

**Comment by ilyhalight** [comment]
> Но это наверное к Яндексу?!

`+`
