### ISSUE TITLE
[ bug ] Возникла ошибка при переводе, попробуйте позже

### ISSUE THREAD

**Issue by miztizm** [ilyhalight/voice-over-translation#408]
Сервис Youtube, браузер Chrome, пробовал версию клауд и не кладу.
Выдает такую ошибку и не переводит 

![image](https://github.com/ilyhalight/voice-over-translation/assets/617020/d7ef4ee6-2783-476f-ae20-2d65f1663a2e)

**Comment by SashaXser** [comment]
> Сервис Youtube, браузер Chrome, пробовал версию клауд и не кладу. Выдает такую ошибку и не переводит
> 
> ![image](https://user-images.githubusercontent.com/617020/282422227-d7ef4ee6-2783-476f-ae20-2d65f1663a2e.png)

Яндекс отключил поддержку большинство языков для озвучки. Из тех, на которые точно можно работают остались: Русский, Английский, Казахский. Нечего пока нельзя поделать :/

**Comment by ilyhalight** [comment]
Ответ дали выше
