### ISSUE TITLE
Please add the ability to translate videos

### ISSUE THREAD

**Issue by Artem2030** [ilyhalight/voice-over-translation#409]
Hi.
Please add the ability to translate videos on two porn sites:
https://sxyprn.com/ and https://www.eporner.com/

**Comment by ilyhalight** [comment]
I doubt that Yandex supports them, I will check later

**Comment by ilyhalight** [comment]
> https://sxyprn.com/

Not supported

> https://www.eporner.com/

Supported, will be added in the next beta

**Comment by ilyhalight** [comment]
> Supported, will be added in the next beta

added

**Comment by Artem2030** [comment]
the video translation button did not appear (

**Comment by ilyhalight** [comment]
> the video translation button did not appear (

are you using beta 9?

**Comment by Artem2030** [comment]
https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot-cloudflare.user.js

**Comment by ilyhalight** [comment]
> https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot-cloudflare.user.js

so far, it has only been added to beta 9

**Comment by Artem2030** [comment]
where to get the 9th beta version ?

**Comment by ilyhalight** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/62353659/5810f1dc-aeba-490d-b8f9-e2ec9c0e1f55)

**Comment by Artem2030** [comment]
I downloaded it from here:
https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta9
vot-cloudflare.user.js 
There is still no translation button on the video (
https://i.vgy.me/xlyzvJ.png

**Comment by ilyhalight** [comment]
> I downloaded it from here: https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta9 vot-cloudflare.user.js There is still no translation button on the video ( https://i.vgy.me/xlyzvJ.png

button added only for eporner

**Comment by ilyhalight** [comment]
released
