### ISSUE TITLE
Does not work in pornohub

### ISSUE THREAD

**Issue by Amiantum** [ilyhalight/voice-over-translation#410]
There does not appear a sunbeam, but everything works with YouTube. I watched other solutions, but they do not help
![image](https://github.com/ilyhalight/voice-over-translation/assets/150779505/3dc3b56c-fce4-432f-8583-7568a41be948)

**Comment by SashaXser** [comment]
> There does not appear a sunbeam, but everything works with YouTube. I watched other solutions, but they do not help ![image](https://user-images.githubusercontent.com/150779505/282699059-3dc3b56c-fce4-432f-8583-7568a41be948.png)

Обновитесь до беты. Пойду шаблон сделаю для Issues, постоянно спрашивать все надоедает.

**Comment by Amiantum** [comment]
> > Зайчика не появляется, но с ютубом все работает. Смотрел другие решения, но они не помогают ![образ](https://user-images.githubusercontent.com/150779505/282699059-3dc3b56c-fce4-432f-8583-7568a41be948.png)
> 
> Обновитесь до беты. Пойду шаблон сделаю для Issues, постоянно спрашивать все надоедает.

А как до неё обновиться или где найти?

**Comment by SashaXser** [comment]
> > > Зайчика не появляется, но с ютубом все работает. Смотрел другие решения, но они не помогают ![образ](https://user-images.githubusercontent.com/150779505/282699059-3dc3b56c-fce4-432f-8583-7568a41be948.png)
> > 
> > 
> > Обновитесь до беты. Пойду шаблон сделаю для Issues, постоянно спрашивать все надоедает.
> 
> А как до неё обновиться или где найти?

В [релизах](https://github.com/ilyhalight/voice-over-translation/releases)

**Comment by Amiantum** [comment]
Да, действительно на бете всё работает, а можно ли что-то сделать, чтобы работало и на последней версии?

**Comment by SashaXser** [comment]
> Да, действительно на бете всё работает, а можно ли что-то сделать, чтобы работало и на последней версии?

Ждать обновление

**Comment by Amiantum** [comment]
Хорошо, спасибо за помощь

**Comment by Jone655** [comment]
> > > > Зайчика не появляется, но с ютубом все работает. Смотрел другие решения, но они не помогают ![образ](https://user-images.githubusercontent.com/150779505/282699059-3dc3b56c-fce4-432f-8583-7568a41be948.png)
> > > 
> > > 
> > > Обновитесь до беты. Пойду шаблон сделаю для Issues, постоянно спрашивать все надоедает.
> > 
> > 
> > А как до неё обновиться или где найти?
> 
> В [релизах](https://github.com/ilyhalight/voice-over-translation/releases)

Где конкретно мне взять код беты? Все ссылки на код которые я находил ведут на версию 1.4.1

**Comment by ilyhalight** [comment]
> > > > > Зайчика не появляется, но с ютубом все работает. Смотрел другие решения, но они не помогают ![образ](https://user-images.githubusercontent.com/150779505/282699059-3dc3b56c-fce4-432f-8583-7568a41be948.png)
> > > > 
> > > > 
> > > > Обновитесь до беты. Пойду шаблон сделаю для Issues, постоянно спрашивать все надоедает.
> > > 
> > > 
> > > А как до неё обновиться или где найти?
> > 
> > 
> > В [релизах](https://github.com/ilyhalight/voice-over-translation/releases)
> 
> Где конкретно мне взять код беты? Все ссылки на код которые я находил ведут на версию 1.4.1

в релизах.
