### ISSUE TITLE
Пишет что видео слишком длинное.

### ISSUE THREAD

**Issue by hacker33105** [ilyhalight/voice-over-translation#411]
Как решить эту проблему?
![изображение_2023-11-14_161509046](https://github.com/ilyhalight/voice-over-translation/assets/94451815/cfa17bbe-846c-479b-b271-6d8fec0b29d3)

**Comment by ilyhalight** [comment]
Пока что никак, только, если резать видео на более мелкие части

> Расширение не может переводить видео длиной более 4 часов (ограничение API переводчика)

**Comment by hacker33105** [comment]
@ilyhalight 
Это когда-нибудь будет решено?

**Comment by ilyhalight** [comment]
> @ilyhalight Это когда-нибудь будет решено?

Возможно, в будущем будет сделано. Ориентировочно, в ближайшее месяцы НЕ БУДЕТ
