### ISSUE TITLE
menu issues: The sliders cannot be adjusted smoothly

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#417]
### Operating system / Операционная система

macOS v12.7.1 (21G920)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0-beta9

### Describe the bug / Опишите ошибку программы

The sliders cannot be adjusted smoothly.

### Additional information / Дополнительная информация

https://github.com/ilyhalight/voice-over-translation/assets/62497891/66c87323-650d-4337-92a1-382629aa26a0

**Comment by ilyhalight** [comment]
It seems that this problem has become relevant on all chromium-based browsers.
#394

**Comment by ilyhalight** [comment]
fixed in beta10

**Comment by ilyhalight** [comment]
fixed in stable
