### ISSUE TITLE
Add an option to select other percentages in "Reduce video volume to".

### ISSUE THREAD

**Issue by Oleg-Chashko** [ilyhalight/voice-over-translation#418]
### Describe your feature / Опишите ваше предложение

<img width="473" alt="Reduce video volume to" src="https://github.com/ilyhalight/voice-over-translation/assets/62497891/0d11a9b2-1ee4-4c4f-8adb-1e70bec77720">

**Comment by ilyhalight** [comment]
I've been thinking about it, most likely it will be implemented using a slider

**Comment by ilyhalight** [comment]
Added slider in beta10

**Comment by ilyhalight** [comment]
added in stable
