### ISSUE TITLE
Не работает кнопка установки скрипта для Adguard

### ISSUE THREAD

**Issue by dadazord** [ilyhalight/voice-over-translation#42]
![chrome_MA9vWhwnOf](https://user-images.githubusercontent.com/39309996/197737185-3efeafce-8a68-413c-bfb8-4e6f06c8f413.png)

**Comment by ilyhalight** [comment]
Не знаю с чем может быть связано. У меня в мозилле всё нормально открывается. Вот прямая ссылка: https://github.com/mynovelhost/voice-over-translation/
