### ISSUE TITLE
Потеряна поддержка iOS после 1.5.0-beta4

### ISSUE THREAD

**Issue by BioXeon** [ilyhalight/voice-over-translation#423]
### Operating system / Операционная система

iOS 17.2

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.5.0-beta4 - 1.5.0-beta9

### Describe the bug / Опишите ошибку программы

Не появляется плашка «Перевести видео»

**Comment by ilyhalight** [comment]
Что-то пишет в консоли?

**Comment by BioXeon** [comment]
![Screenshot 2023-11-22 at 11 39 28 AM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/ca33b060-4a74-47da-8146-193a45686bb2)
![Screenshot 2023-11-22 at 11 40 24 AM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/dd9a62ea-65e0-495a-a6cb-396ac78ef580)
![Screenshot 2023-11-22 at 11 40 47 AM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/bb710b49-7308-45bc-a13a-55e4201514d3)

**Comment by BioXeon** [comment]
Ворнинги смотреть\закидывать ?

**Comment by BioXeon** [comment]
В версии 1.5.0-beta3 следующее:
![Screenshot 2023-11-22 at 11 58 04 AM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/f9c53cf8-e2a6-4c8b-8221-efd8a18b55b5)

**Comment by ilyhalight** [comment]
Понял, если получится, то исправлю

**Comment by ilyhalight** [comment]
Попробуй этот скрипт, в теории должно работать https://drive.google.com/drive/folders/1JexKnQSi-0-XUyCtBCGnKFdhTEPWUDEy?usp=sharing

**Comment by BioXeon** [comment]
Спасибо, вечером чекну и дам feedback

**Comment by BioXeon** [comment]
Проблема осталась. Хоть и ошибок меньше.
![Screenshot 2023-11-23 at 7 39 25 PM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/69797f72-0d08-4f22-b5ee-7804ba373fd6)

**Comment by ilyhalight** [comment]
> Проблема осталась. Хоть и ошибок меньше. ![Screenshot 2023-11-23 at 7 39 25 PM](https://user-images.githubusercontent.com/8689565/285269279-69797f72-0d08-4f22-b5ee-7804ba373fd6.png)

у вас расширение через тамперманки стоит или через userscripts?

**Comment by BioXeon** [comment]
Я не пробовал Tampermonkey и по тому, что он платный для iOS & MacOS (разработчик это описал как покрытие издержек за счёт пользователей этих платформ, которые у него есть во время выпуска этого ПО). Вектор мысли мне понятен, попробую и beta версию Usercripts и возьму Tampermonkey

**Comment by ilyhalight** [comment]
> Я не пробовал Tampermonkey и по тому, что он платный для iOS & MacOS (разработчик это описал как покрытие издержек за счёт пользователей этих платформ, которые у него есть во время выпуска этого ПО). Вектор мысли мне понятен, попробую и beta версию Usercripts и возьму Tampermonkey

Вероятнее всего, с тамперманки никаких проблем не будет в сафари, и если вам нужно наиболее универсальное решение, то это.

Просто, я не совсем уверен, есть ли у Userscripts поддержка GM Storage или нет и из-за этого приходится искать проблему методом тыка. Судя по https://github.com/quoid/userscripts/issues/189 нет поддержки только старого синтаксиса "GM_", который я и использую в расширение. Можете попробовать такой вариант, в нем используется новый синтаксис обращений "GM.", который в теории должен поддерживаться UserScripts https://drive.google.com/drive/folders/1JRDDZk_9TG0inHr1Ic-5KUauOyH0VTzG?usp=sharing

**Comment by BioXeon** [comment]
Можно закрывать тикет. Проблема в Userscripts. После установки Tampermonkey я протестировал версию, которая с Google Drive (...-beta9, from 23.11 & 24.11), и она работает.

**Comment by BioXeon** [comment]
Последняя (от 24.11) всё же не работает в Userscripts. Я посмотрел, что там внесены изменения связанные с GM, но не взлетает

**Comment by ilyhalight** [comment]
> Последняя (от 24.11) всё же не работает в Userscripts. Я посмотрел, что там внесены изменения связанные с GM, но не взлетает

там ошибка таже осталась?

**Comment by BioXeon** [comment]
Похоже другая, но фигурирует функция GM.getvalue
![Screenshot 2023-11-25 at 12 55 33 PM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/7223640f-20d3-4304-ad0a-47354dba205d)

**Comment by ilyhalight** [comment]
похоже, даже такой синтаксис не поддерживается :(

**Comment by ilyhalight** [comment]
Возможно, исправил
https://drive.google.com/drive/folders/18OSVwS1nsweXmHbQYz57brfAQikZZ_pZ?usp=sharing

**Comment by BioXeon** [comment]
Так, GM.getvalue ушла, но появились другие. Плашка всё ещё не появляется
![Screenshot 2023-11-26 at 2 33 57 PM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/b48d05c5-cce8-4192-86ce-451fddebbce4)
![Screenshot 2023-11-26 at 2 34 21 PM](https://github.com/ilyhalight/voice-over-translation/assets/8689565/f9ebdd2f-5905-4f53-b7ec-df07eaaf0bce)

**Comment by ilyhalight** [comment]
исправлено в beta10
