### ISSUE TITLE
"возникла ошибка при переводе"

### ISSUE THREAD

**Issue by Vektor-537** [ilyhalight/voice-over-translation#424]
### Operating system / Операционная система

Windows 10 Pro 19041.985

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

"возникла ошибка при переводе" появляється на кожному відео (після переклад займе ... хвилин)
(пробував ці відео
https://www.youtube.com/watch?v=HUHC9tYz8ik
https://www.youtube.com/watch?v=wEu1tgjtosQ&t=1074s
https://www.youtube.com/watch?v=ciapChyIEo0&t=1s
)

**Comment by ilyhalight** [comment]
обновитесь до последней беты

**Comment by Vektor-537** [comment]
ви про цю бету (https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta9)?
там 4 файли, я спробував кожен, всі дають помилку возникла ошибка при переводе, попробуйте позже
консоль видає це (це той файл який важить 676 кб)
[www.youtube.com-1700650102103.log](https://github.com/ilyhalight/voice-over-translation/files/13438278/www.youtube.com-1700650102103.log)
[www.youtube.com-1700650112391.log](https://github.com/ilyhalight/voice-over-translation/files/13438279/www.youtube.com-1700650112391.log)
[www.youtube.com-1700650091450.log](https://github.com/ilyhalight/voice-over-translation/files/13438281/www.youtube.com-1700650091450.log)

**Comment by SashaXser** [comment]
> ви про цю бету (https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta9)? там 4 файли, я спробував кожен, всі дають помилку возникла ошибка при переводе, попробуйте позже консоль видає це (це той файл який важить 676 кб) [www.youtube.com-1700650102103.log](https://github.com/ilyhalight/voice-over-translation/files/13438278/www.youtube.com-1700650102103.log) [www.youtube.com-1700650112391.log](https://github.com/ilyhalight/voice-over-translation/files/13438279/www.youtube.com-1700650112391.log) [www.youtube.com-1700650091450.log](https://github.com/ilyhalight/voice-over-translation/files/13438281/www.youtube.com-1700650091450.log)

Включите это (если у вас язык браузера был бы Украинский, то опция включается автоматически)
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/21423e8b-2290-42f2-a2fa-e0ab8f81177e)

**Comment by Vektor-537** [comment]
те саме 
я спробував зайти через впн winscribe (розширення)- теж не допомогло
при цьому субтитри (від вашого розширення) працюють

**Comment by SashaXser** [comment]
> те саме я спробував зайти через впн winscribe (розширення)- теж не допомогло при цьому субтитри (від вашого розширення) працюють

Дочитал логи, Украинский язык отключили где-то в ноябре. Нечего увы нельзя сделать.
На 04.11.2023 большая часть языков доступных для выбора в качестве озвучки были отключены на стороне Яндекса. Мне неизвестно будут ли они возвращены позднее или нет. Из тех, на которые точно можно выполнить перевод остались: Русский, Английский, Казахский.
