### ISSUE TITLE
В ВК не переводит, пишет не найден ID видео

### ISSUE THREAD

**Issue by Berturg** [ilyhalight/voice-over-translation#425]
### Operating system / Операционная система

Windows 10 

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

![Screenshot_1](https://github.com/ilyhalight/voice-over-translation/assets/36488969/34c89bed-7530-49e9-857f-c0f78810bed9)

**Comment by ilyhalight** [comment]
Видимо, у вас какая-то особенная ссылка на видео. Можете скинуть?

**Comment by lMavorsl** [comment]
Я кстати,тоже вчера хотел запустить какое-то видео и было тоже самое.Если вспомню,что за видео сюда скину.

**Comment by Berturg** [comment]
> Наверное, у вас какая-то особенная ссылка на видео. Можете скинуть?

Я разобрался, в общем видео нужно заливать на личную страницу, а не в паблик или канал.
Переводит только с личной страницы.
