### ISSUE TITLE
Не работает функция Связать громкость перевода и видео

### ISSUE THREAD

**Issue by lMavorsl** [ilyhalight/voice-over-translation#426]
### Operating system / Операционная система

Windows 10 20H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Установил вчера ваш скрипт.Спасибо большое за труд.Повему не работает функция Связать громкость перевода и видео.И при включенной галке и при выключенной в Ютуб никакой реакции нету.Убираю звук полностью в ползунке проигрывателя,а перевод как шел с той же громкостью,так и идет.

**Comment by ilyhalight** [comment]
это привязывается только к громкости внутри расширения

**Comment by lMavorsl** [comment]
Действительно.Не знал,а этот ползунок отключил сразу.Извините за беспокойство тогда.
