### ISSUE TITLE
GM_getValue is not defined

### ISSUE THREAD

**Issue by WildPowerHammer** [ilyhalight/voice-over-translation#428]
### Operating system / Операционная система

Kubuntu 23.10

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

FireMonkey

### Script version / Версия скрипта

1.5.0-beta9

### Describe the bug / Опишите ошибку программы

Скрипт выдает ошибку GM_getValue is not defined:
![image](https://github.com/ilyhalight/voice-over-translation/assets/136165053/e68ab4bf-2ad0-4004-b2ed-d1dc25e1d099)

Проверял в Firefox и Librewolf, если использовать версию скрипта 1.4.1 то возникает проблема как [здесь](https://github.com/ilyhalight/voice-over-translation/issues/388)

### Additional information / Дополнительная информация

На сколько я понял, проблема возникает при попытке определить язык установленный в браузере
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/136165053/912e7d49-fe52-4f9c-864f-af6a91f1554c)

**Comment by WildPowerHammer** [comment]
P.S. Если использовать Tampemonkey, то все начинает работать

**Comment by SashaXser** [comment]
> P.S. Если использовать Tampemonkey, то все начинает работать
 
Может FireMonkey плохо работает с GM_getValue и тд? Точно знаю что Tampermonkey, Violentmonkey и Greasemonkey нормально с ним работают.

**Comment by ilyhalight** [comment]
Возможно, там не поддерживается старый синтаксис с "GM_". Попробуйте скачать отсюда и отпишите https://drive.google.com/drive/folders/1JRDDZk_9TG0inHr1Ic-5KUauOyH0VTzG?usp=sharing

**Comment by WildPowerHammer** [comment]
> Возможно, там не поддерживается старый синтаксис с "GM_". Попробуйте скачать отсюда и отпишите https://drive.google.com/drive/folders/1JRDDZk_9TG0inHr1Ic-5KUauOyH0VTzG?usp=sharing

Ошибка меняется на Uncaught TypeError: GM.getValue is not a function

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/136165053/539586e8-f0d3-4720-864f-2ecf364fa4d4)

**Comment by ilyhalight** [comment]
похоже, даже такой синтаксис не поддерживается

**Comment by WildPowerHammer** [comment]
Я не уверен, что это именно то что вы имели ввиду, но если просто вырезать `// @inject-into page`, то я получаю такой набор ошибок:
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/136165053/64e7becd-d6e5-4dba-8a2f-de564b921527)

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/136165053/08d51781-6a53-4210-90c4-3ad57783fb75)

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/136165053/5dfc5df1-5e04-4eae-9354-d85238819dcf)



Также когда я открыл ролик сразу после удаления строки плашка  с кнопкой перевести действительно высветилась, но не работали кнопки, после обновления страницы плашка не появлялась

**Comment by ilyhalight** [comment]
> Я не уверен, что это именно то что вы имели ввиду, но если просто вырезать `// @inject-into page`, то я получаю такой набор ошибок: ![изображение](https://private-user-images.githubusercontent.com/136165053/285597443-64e7becd-d6e5-4dba-8a2f-de564b921527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQxMTAsIm5iZiI6MTcwMDkyMzgxMCwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NDQzLTY0ZTdiZWNkLWQ2ZTUtNGRiYS04YTJmLWRlNTY0YjkyMTUyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYTBiM2JkZTIwM2Q1MjFjZGE0YTExN2VmNWJjYTkzNmIwMjFlMTUwNDEzZjU5YzlkYWRiODBmZjkyYWMzYTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.li6XEoZU62nkVkvUsn4V9nnvDsxQPawRMeDwX2C6eVo)
> 
> ![изображение](https://private-user-images.githubusercontent.com/136165053/285597452-08d51781-6a53-4210-90c4-3ad57783fb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQxMTAsIm5iZiI6MTcwMDkyMzgxMCwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NDUyLTA4ZDUxNzgxLTZhNTMtNDIxMC05MGM0LTNhZDU3NzgzZmI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NThjMThlNDMzMmU2ZTM1Njk2M2ZjZjgxMGU1YjkxZmE2Nzk5OGFkMWQ3ZDliM2U3ZjNhMTYzMmY0OTYzYzI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eZWUpEWkP_twtSWZA940v9pl_ueSFE1X91I7QM0DGWQ)
> 
> ![изображение](https://private-user-images.githubusercontent.com/136165053/285597500-5dfc5df1-5e04-4eae-9354-d85238819dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQxMTAsIm5iZiI6MTcwMDkyMzgxMCwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NTAwLTVkZmM1ZGYxLTVlMDQtNGVhZS05MzU0LWQ4NTIzODgxOWRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzk0YjYxNmI5ODllMzI0NTgyZDg0MGUyMjM2YTc3OGRiNWY5YzFlMmI1MWVlNWY0ZDA3Y2UxZjQxMDhlNWQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d-vZ1RYLs0N7lOQ6jH2oyNSxxFkuhBG32eF7KItEp8w)
> 
> Также когда я открыл ролик сразу после удаления строки плашка с кнопкой перевести действительно высветилась, но не работали кнопки, после обновления страницы плашка не появлялась
> 
> P.S. - Если попытаться перезапустить скрипт через интерфейс firemonkey, то появляется сообщение о том, чот GM is not defined ![изображение](https://private-user-images.githubusercontent.com/136165053/285597821-61218690-32dd-465e-a6cb-729d7de47d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjQxMTAsIm5iZiI6MTcwMDkyMzgxMCwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3ODIxLTYxMjE4NjkwLTMyZGQtNDY1ZS1hNmNiLTcyOWQ3ZGU0N2Q3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNDUwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTU4OGE4OWUwZjNiN2EwNDQyMDk0M2M2MGE0YTQ2MzE2NzYzMTkwZDA2YWVlZGFlM2Y5YWIwZTc0MzI4MDhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ck4PZ6ltQBV4gyIGFpO-zZdt60HUtw1B1AHNp66YGPM)

Я уже проверил это, да и убирать эту строчку все равно не выход, ибо, даже, если исправить эти все ошибки, то появится другая ошибка с запросами. Поэтому, скорее всего, легче будет просто сделать какой-нибудь универсальный класс для работы с хранилищем в зависимости от поддержки GM Storage. Конечно, из-за этого не будут работать межсайтовые настройки, но мне кажется это лучше, чем, если не будет работать вовсе

**Comment by SashaXser** [comment]
> Я не уверен, что это именно то что вы имели ввиду, но если просто вырезать `// @inject-into page`, то я получаю такой набор ошибок: ![изображение](https://private-user-images.githubusercontent.com/136165053/285597443-64e7becd-d6e5-4dba-8a2f-de564b921527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjU2NzksIm5iZiI6MTcwMDkyNTM3OSwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NDQzLTY0ZTdiZWNkLWQ2ZTUtNGRiYS04YTJmLWRlNTY0YjkyMTUyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNTE2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNjUwN2I0YTgxZjUyNDAwODhhMTBmYTljMmExZTdlMDVmMDQxNDBiOGIyZWQ4MDQyY2U0ODliNjNmMTRjYTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8f6yqhGjQTnXYB2MTzC5Mz8mr9aai3cC8smf0dVK6GI)
> 
> ![изображение](https://private-user-images.githubusercontent.com/136165053/285597452-08d51781-6a53-4210-90c4-3ad57783fb75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjU2NzksIm5iZiI6MTcwMDkyNTM3OSwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NDUyLTA4ZDUxNzgxLTZhNTMtNDIxMC05MGM0LTNhZDU3NzgzZmI3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNTE2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzFhMjhkNzAwYTIwOTcxNDJhYWNhMWQ2NDI3NjI2MDg1NzZhYmUxN2E2OWIyMjg2MjAzNDE2NDU4ZDQ0MTU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Peevk6PnX16k1OHXeBpvLIS6vMS1rBsaYxuYrJEnNt4)
> 
> ![изображение](https://private-user-images.githubusercontent.com/136165053/285597500-5dfc5df1-5e04-4eae-9354-d85238819dcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjU2NzksIm5iZiI6MTcwMDkyNTM3OSwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3NTAwLTVkZmM1ZGYxLTVlMDQtNGVhZS05MzU0LWQ4NTIzODgxOWRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNTE2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTA2MzI3MjRmNDhlNjRmZGIyNGMyY2M0MDZlYWI4ZjAwMjhkZTNkODAwN2FiMjBkMjlhNTVlMmNiYmIwY2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QG8QzwCFhCf-mzOwCUbn1BkP-oDiu24cI--XinqsLTA)
> 
> Также когда я открыл ролик сразу после удаления строки плашка с кнопкой перевести действительно высветилась, но не работали кнопки, после обновления страницы плашка не появлялась
> 
> P.S. - Если попытаться перезапустить скрипт через интерфейс firemonkey, то появляется сообщение о том, чот GM is not defined ![изображение](https://private-user-images.githubusercontent.com/136165053/285597821-61218690-32dd-465e-a6cb-729d7de47d71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5MjU2NzksIm5iZiI6MTcwMDkyNTM3OSwicGF0aCI6Ii8xMzYxNjUwNTMvMjg1NTk3ODIxLTYxMjE4NjkwLTMyZGQtNDY1ZS1hNmNiLTcyOWQ3ZGU0N2Q3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNVQxNTE2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMmRiYzA1M2I5ZjVmOTRhMjMzYzFmOWQ1NGI4OGU4YWJkZmUxYTAyMTFkNjgzZjExNmQ5ZjY2MWNjNTRiNjVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lvfxsnANrEVFhbbapURUjwpRcAzwzggMsE6OROwD4uM)

Попробуй отписать создателям FireMonkey, возможно они починят

**Comment by ilyhalight** [comment]
> Попробуй отписать создателям FireMonkey, возможно они починят

Судя по https://github.com/erosman/support/issues/277 это не баг и так было специально сделано

**Comment by ilyhalight** [comment]
Должно нормально работать
https://drive.google.com/drive/folders/18OSVwS1nsweXmHbQYz57brfAQikZZ_pZ?usp=sharing

**Comment by WildPowerHammer** [comment]
> Должно нормально работать https://drive.google.com/drive/folders/18OSVwS1nsweXmHbQYz57brfAQikZZ_pZ?usp=sharing

Проверил, теперь все отлично работает, безумно вам благодарен!
