### ISSUE TITLE
В Safari не появляется кнопка перевода

### ISSUE THREAD

**Issue by ifRemix** [ilyhalight/voice-over-translation#43]
В Safari вообще не появляется кнопка перевода
voice-over-translation  1.0.9.1 и через Userscripts и через AdGurd.
macOS Ventura 13.0 Safari 16.1
iPadOS 16.1  
https://www.youtube.com/watch?v=RtKb6HO8DJE

**Comment by AlexanderDankin** [comment]
Скрипт в связке с Tampermonkey в Safari 16.0 работает на macOS 12.6

**Comment by AlexanderDankin** [comment]
Только что обновился до версии macOS 12.6.1 + Safari 16.1 - всё по прежнему работает в связке с Tampermonkey...

**Comment by ifRemix** [comment]
Это, конечно, здорово, что в Tampermonkey работает. но мне это не очень интересно. т.к. я совсем не смотрю YouTube на маке. в основном на iPad и немного на iPhone. а Tampermonkey, увы, только на маке есть.
Userscripts же - универсален. и кода раньше скрипт работал, то отлично работал на всех трех девайсах. так что, буду ждать и надеяться, что поправят для использования через Userscripts.

**Comment by AndrewRozhnev** [comment]
macOS 12.6.1
Safari 16.1
voice-over-translation 1.0.9.2
Не появляется кнопка ни через Userscripts, ни посредством AdGuard

**Comment by ifRemix** [comment]
Так что, для Safari планируется исправление? так нигде и не работает  (нет кнопки) - ни на десктопе, ни на планшете.

**Comment by becauseim** [comment]
А как сам скрипт установить в Safari?
Есть ссылка на расширение UserScript, а ссылка на установку скрипта размещена только для Chrome.

**Comment by AlexR0v** [comment]
на сафари кнопка перевода видео появилась, но на любое видео, даже самое короткое, приходит ошибка - не удалось запросить перевод видео(

**Comment by ilyhalight** [comment]
> на сафари кнопка перевода видео появилась, но на любое видео, даже самое короткое, приходит ошибка - не удалось запросить перевод видео(

Попробуй 2-ю версия расширения
![изображение](https://user-images.githubusercontent.com/62353659/217885158-18bcb2c8-d1d3-402f-a30c-ae49203b47d7.png)

**Comment by AlexR0v** [comment]
> > на сафари кнопка перевода видео появилась, но на любое видео, даже самое короткое, приходит ошибка - не удалось запросить перевод видео(
> 
> Попробуй 2-ю версия расширения ![изображение](https://user-images.githubusercontent.com/62353659/217885158-18bcb2c8-d1d3-402f-a30c-ae49203b47d7.png)

помогло! спасибо!

**Comment by BioXeon** [comment]
Доброго времени суток. 
Подскажите, по глупости удалил из Safari (16.4) on MacOS Venture 13.3 -> Хранилище -> Index.DB -> VOT все настройки. 
Теперь появляется только плашка "Перевести видео", но она не работает т.е. не переводится ни одно видео на YouTube. Хотя до этого всё исправно работало, подвило предположение, что очисткой я исправлю проглатывание частей слов или слов полностью при переводе.
Заранее спасибо.
