### ISSUE TITLE
Не открываются меню выбора языка/субтитров

### ISSUE THREAD

**Issue by maximusfox** [ilyhalight/voice-over-translation#431]
### Operating system / Операционная система

Linux Mint

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Менюшки выбора языка с/на который переводить, субтитровая менюшка не открываются, судя по всему исключительно на youtube (проверял на vimeo, там всё работает).
Клик сквозь эти меню прилетает в ютубовый плеер, если дважды кликнуть - плеер открывается на весь экран.

**Comment by SashaXser** [comment]
Обновитесь до беты

**Comment by maximusfox** [comment]
> Обновитесь до беты

Накатил вот это: [линк](https://raw.githubusercontent.com/ilyhalight/voice-over-translation/dev-1.5.0-beta2/dist/vot.user.js) как я понимаю это бета.
И меня там тоже не разворачиваются и клик проходит насквозь даже по ползунку громкости в меню.

**Comment by SashaXser** [comment]
> > Обновитесь до беты
> 
> Накатил вот это: [линк](https://raw.githubusercontent.com/ilyhalight/voice-over-translation/dev-1.5.0-beta2/dist/vot.user.js) как я понимаю это бета. Там тоже не разворачиваются и клик проходит насквозь даже по ползунку громкости в меню.

Скачай [последнюю](https://github.com/ilyhalight/voice-over-translation/releases/download/1.5.0-beta9/vot-min.user.js)

**Comment by ilyhalight** [comment]
#349
