### ISSUE TITLE
Нету плашки с выбором перевода на русский

### ISSUE THREAD

**Issue by quakerr** [ilyhalight/voice-over-translation#434]
### Operating system / Операционная система

windows 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0-beta9

### Describe the bug / Опишите ошибку программы

![2023-11-29_171423](https://github.com/ilyhalight/voice-over-translation/assets/6378839/de0c1800-6636-4c7f-a4fd-55e6625ec0a8)

**Comment by quakerr** [comment]
![2023-11-29_171859](https://github.com/ilyhalight/voice-over-translation/assets/6378839/24022508-a970-4b4f-a403-375c90039141)

**Comment by ilyhalight** [comment]
Уже известно, будет исправлено на релизе/в следующей бете

**Comment by ilyhalight** [comment]
Исправлено в 10 бете
