### ISSUE TITLE
UI Не реагирует на клики

### ISSUE THREAD

**Issue by nixON232** [ilyhalight/voice-over-translation#436]
### Operating system / Операционная система

Win10

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Не реагируют Comboxes /sliders. Чекбоксы работают. из-за этого не могу поменять язык. Проблема только на Youtube
![image](https://github.com/ilyhalight/voice-over-translation/assets/20164412/436ccd15-40c3-4184-8b94-ef1d1ec7ef1b)

 

### Additional information / Дополнительная информация

нашел похожую проблему, но там стоит пофикшено.
https://github.com/ilyhalight/voice-over-translation/issues/349

**Comment by ilyhalight** [comment]
> нашел похожую проблему, но там стоит пофикшено.

Стоит пофикшено, потому, что в бете это уже давным давно исправлено. Используйте beta9

**Comment by cprkv** [comment]
> Используйте beta9
А где скачать эту версию?

**Comment by 0DefAir0** [comment]
> а всё уже нашёл, спасибо

Можете подсказать, где её взять?

**Comment by 0DefAir0** [comment]
> @0DefAir0
> 
> > Можете подсказать, где её взять?
> 
> во вкладке релизы: https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.0-beta9

Спасибо, а как её установить? Что-то совсем не догоняю...

**Comment by 0DefAir0** [comment]
А, понял, спасибо)
