### ISSUE TITLE
Перестал работать перевод на украинский

### ISSUE THREAD

**Issue by DikoHellish** [ilyhalight/voice-over-translation#437]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1/1.5 beta9

### Describe the bug / Опишите ошибку программы

Перестал работать перевод на украинский, это новые ограничения серверов?

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 11
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.4.1/1.5 beta9
> ### Describe the bug / Опишите ошибку программы
> 
> Перестал работать перевод на украинский, это новые ограничения серверов?
> ### Additional information / Дополнительная информация
> 
> _No response_

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/d4574579-a93d-4b37-a8fa-4f09351c56fb)

**Comment by ilyhalight** [comment]
Яндекс отключил его
