### ISSUE TITLE
В видео майл ру не работает перевод  через расширение Tampermonkey скрипты

### ISSUE THREAD

**Issue by Helena1974000** [ilyhalight/voice-over-translation#439]
С Ютуба все переводит хорошо через расширение Tampermonkey скрипты VOT Cloudflare и VOT.
![ььььь](https://github.com/ilyhalight/voice-over-translation/assets/153089425/44a5568f-abeb-4ad2-a5cc-8c24b77634bc)

**Comment by ilyhalight** [comment]
У меня переводит. С какого языка на какой пытаетесь перевести?

**Comment by Helena1974000** [comment]
И бету устанавливала, ничего не получается.

ср, 6 дек. 2023 г., 21:37 Елена Черватюк ***@***.***>:

**Comment by ilyhalight** [comment]
Будем считать, что все работает
