### ISSUE TITLE
Не отображается кнопка превода на Udemy

### ISSUE THREAD

**Issue by ruinmind1282** [ilyhalight/voice-over-translation#443]
### Operating system / Операционная система

macos sonoma

### Browser / Браузер

Firefox

### Script version / Версия скрипта

1.4.1

Не отображается кнопка перевода, на других сайтах все работает отлично, но на udemy ее вообще нету.
<img width="1174" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/150943302/bd2006ce-c967-45f9-8e2d-2db445c6592b">

Подскажите в чем может быть проблема?

**Comment by ilyhalight** [comment]
селекторы обновились, установи 1.5.0beta10
