### ISSUE TITLE
Сломался перевод на Coursera

### ISSUE THREAD

**Issue by igor-sandul** [ilyhalight/voice-over-translation#444]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.10 beta

### Describe the bug / Опишите ошибку программы

Здравствуйте. На 1.5.9 beta появлялась плашка перевода на курсере,  со временем пропал перевод. Обновился на 1.5.10 ничего не поменялось. Ютуб работает перевод как часы. Проверил на установленном браузере Яндекс, там есть перевод. Но есть нюанс, плашка перевести не появляется автоматически. Нужно на каждом ролике жать 3 точки, выбирать язык перевода и включать видео. Думаю  в этом проблема. В хроме и мозилле плашки никакой нет, нет возможности выбирать, включать что-либо. Проверьте пожалуйста.

**Comment by igor-sandul** [comment]
![Screenshot_1](https://github.com/ilyhalight/voice-over-translation/assets/126835820/d873cf2a-4751-4aac-84b0-ed3910378fb5)

**Comment by ilyhalight** [comment]
Если нужен фикс прямо сейчас, то в коде расширения найди `selector: "#video_player",` и замени на `selector: ".vjs-v6",`.

**Comment by igor-sandul** [comment]
![Screenshot_2](https://github.com/ilyhalight/voice-over-translation/assets/126835820/942103bc-b3bb-494a-8080-a07e3e570521)
Стало лучше, спасибо Илья. Правда перевода все равно нет. Может поможет инфа, что когда пишет " Не удалось получить данные для перевода"- это когда я забывал вкл VPN, чтобы достучаться к серверам Яндекс. Т.к. я с Украины, у нас Яндекс в стоп листе. Но на Coursera сейчас такой ответ даже с VPN. С ютубом все норм. Что-то еще нужно подкрутить на Coursera ,видимо

**Comment by ilyhalight** [comment]
Значит в этом курсе видео в формате, который яндекс не поддерживает

**Comment by igor-sandul** [comment]
![2023-12-09_20-10-16](https://github.com/ilyhalight/voice-over-translation/assets/126835820/d027025d-e1a4-4da0-8805-87c9b4dd4c6c)
Вот скрин с яндекс браузера того же курса с тем же аккаунтом курсеры , сделанного на вируалке

**Comment by igor-sandul** [comment]
![2023-12-09_20-28-24](https://github.com/ilyhalight/voice-over-translation/assets/126835820/51ddd4c4-4d3a-4fda-be3f-69eb24f9c523)
Вот другой курс курсера с яндекс браузера. Раньше переводило даже на 1.5.9, потом на 1.5.9 сломалось

**Comment by ten4dinosaur** [comment]
1.4.1 (main) и 1.5.0-beta10 (dev)
no cloudflare + .vjs-v6  (brave v.120 / ip de)

![1.4.1](https://github.com/ilyhalight/voice-over-translation/assets/113720384/b7fd582d-de2f-4528-9b2f-4fe291dc19d5)
![1.5.0-beta10](https://github.com/ilyhalight/voice-over-translation/assets/113720384/bd4c27d3-ac95-470a-b189-a3f6c40bb5b8)

Посмотри логи в консоли и запросов

**Comment by igor-sandul** [comment]
![Screenshot_1](https://github.com/ilyhalight/voice-over-translation/assets/126835820/64be2081-56bd-4dcf-ae24-7b0ec6a80751)
Вот конкретно на хроме. На brave браузере не проверял. Но тут вопрос про хром. Если не хром, тогда проще установить стоковый яндекс.

**Comment by ten4dinosaur** [comment]
Данные нужные для перевода, скрипт собирает при загрузке страницы. На скриншоте этого не видно. Хром 119 так же работает

![image](https://github.com/ilyhalight/voice-over-translation/assets/113720384/1704ef1a-9895-4922-8d6f-abc361f2ae42)

**Comment by ten4dinosaur** [comment]
Апдейт.

Случайно догадался в чем у тебя дело. Ты заменил #video_player на .vjs-v6 только в одном месте. А надо в двух. Возле selector: и в function courseraUtils_getPlayer()

**Comment by ilyhalight** [comment]
> Апдейт.
> 
> Случайно догадался в чем у тебя дело. Ты заменил #video_player на .vjs-v6 только в одном месте. А надо в двух. Возле selector: и в function courseraUtils_getPlayer()

Да, скорее всего из-за этого не работает, забыл что в этой функции он тоже используется

**Comment by igor-sandul** [comment]
![Screenshot_2](https://github.com/ilyhalight/voice-over-translation/assets/126835820/802734e3-fb89-4ebf-ad94-c0e78b18b924)
После долгих мучений вроде получилось

**Comment by igor-sandul** [comment]
Может проблема была еще в том, что у меня было установлено куча скриптов как cloudflare так  и  нет. В общем лес какой-то. Что сделал в итоге: снес расширение tampermonkey, поставил свежее версии 5.0, поставил 1.4.1(main) обновил его же на 1.5.10 beta. Т.е. в списке скриптов и меня сейчас прописан 1 скрипт. Ну и главное- сделал замену "#video_player" на ".vjs-v6" в 2х местах по советам гуру в этом тикете, спасибо за помощь парни. Можно и яндекс юзать, но его сильно допиливать нужно для повседневнрй работы: много popup-в в нем

**Comment by igor-sandul** [comment]
![Screenshot_8](https://github.com/ilyhalight/voice-over-translation/assets/126835820/3ddb9426-581e-49f2-8fc3-79b6892c3d70)
![Screenshot_7](https://github.com/ilyhalight/voice-over-translation/assets/126835820/2fc898c7-d51f-4ecc-b987-8456a64ce757)
![Screenshot_6](https://github.com/ilyhalight/voice-over-translation/assets/126835820/86f470b3-4ffd-4334-8d66-c2b41f156842)
![Screenshot_5](https://github.com/ilyhalight/voice-over-translation/assets/126835820/6cf330e8-67a2-488e-8cbf-8747f69c0ca0)
![Screenshot_4](https://github.com/ilyhalight/voice-over-translation/assets/126835820/3a6c2717-5dd1-4cac-8638-9dd7a7d82474)
![Screenshot_3](https://github.com/ilyhalight/voice-over-translation/assets/126835820/aa23d046-bd63-4f4b-9008-7dfea3387528)
Сейчас нормальные логи в консоли?

**Comment by igor-sandul** [comment]
Еще заметил, что когда была ошибка перевода, то vot-block был ближе к верхней рамки плейера, а когда заработал- стал ближе к центру как-то так

**Comment by ilyhalight** [comment]
Исправлено в стабильной ветке
