### ISSUE TITLE
Не работает defaultAutoVolume

### ISSUE THREAD

**Issue by AvenCores** [ilyhalight/voice-over-translation#445]
### Operating system / Операционная система

win 10 ltsc 2021 (MSDN)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0-beta10

### Describe the bug / Опишите ошибку программы

Строка 561
const defaultAutoVolume = 0.0;

Но видео все также имеет минимальную громкость оригинала в 15%

**Comment by ilyhalight** [comment]
Исправлю, пока можете выбрать нужную "авто громкость" через слайдер

**Comment by ilyhalight** [comment]
Исправлено
