### ISSUE TITLE
Изменение размера субтитров

### ISSUE THREAD

**Issue by Mundi-art** [ilyhalight/voice-over-translation#446]
### Describe your feature / Опишите ваше предложение

В основном пользуюсь для субтитров, на твиче/ютубе и размер субтитров хотелось бы иметь возможность изменять, т.к. стандартный вариант выглядит довольно маленьким (примерно как стандартные субтитры на ютубе на 50% размера) Из-за чего читать не очень комфортно.

**Comment by dlt5** [comment]
А в браузере на андроиде выглядит огромным.

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
