### ISSUE TITLE
не удалось запросить перевод видео

### ISSUE THREAD

**Issue by Helena1974000** [ilyhalight/voice-over-translation#447]
### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

![1](https://github.com/ilyhalight/voice-over-translation/assets/153089425/a4feab0b-bfb9-4c3f-890e-7d9eda51d83e)

### Additional information / Дополнительная информация

Все работало прекрасно до сегодняшнего дня. Браузер Edge

**Comment by StressOzz** [comment]
после обновления Chrome так везде (
даже на последней версии

**Comment by hachikoharuno** [comment]
Подтверждаю наличие проблемы

**Comment by ilyhalight** [comment]
Хром 120 и все работает ¯\_(ツ)_/¯

А какую версию расширения используете? Cloudflare или обычную?

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/0e8ad30e-f8a2-4068-b3f3-eb4919277493)

**Comment by hachikoharuno** [comment]
Да, проверил, обычная работает, но только через tempermonkey, violetmonkey выдает ошибку
А Cloudflare не работает

**Comment by Spp595** [comment]
Браузер iceraven (fork firefox на андроид) тоже не работает, версия cloudflare

**Comment by ilyhalight** [comment]
У cloudflare какие-то проблемы. Если пытаться делать запрос под впном, то все работает. Вероятнее всего, уже скоро все пофиксится

**Comment by Spp595** [comment]
> У cloudflare какие-то проблемы. Если пытаться делать запрос под впном, то все работает. Вероятнее всего, скоро все само пофиксится

И в правду, под впном все отлично)

**Comment by Spp595** [comment]
Проблема все ещё осталось, вы знаете доменное имя которое используется в версии cloudflare? Я бы хотел добавить его с свой список dns vpn

**Comment by ilyhalight** [comment]
> Проблема все ещё осталось, вы знаете доменное имя которое используется в версии cloudflare? Я бы хотел добавить его с свой список dns vpn

По умолчанию используется vot-new.toil-dump.workers.dev для перевода + проксирования аудио (если включено) и m3u8proxy.toil-dump.workers.dev для проксирования стримов.

**Comment by ilyhalight** [comment]
Обновляйтесь и ставьте в настройках адрес воркера `vot.deno.dev`
