### ISSUE TITLE
Как проще и быстрей переводить видео с компьютера?

### ISSUE THREAD

**Issue by ennnnnne1** [ilyhalight/voice-over-translation#448]
### Describe your feature / Опишите ваше предложение

Есть видео, которое расположено на компьютере скаченное с торрента. 
Нужно получить точно такое же, но на русском языке.
Правильно ли я понимаю что самый быстрый способ это 
1) Загрузить видео на ютуб, предварительно нарезав по 4 часа
2) Подождать несколько часов пока ютуб подготовит видео
3) Пройтись плагином
4) Скачать аудиодорожку

Существует ли вариант быстрей?

**Comment by SashaXser** [comment]
> Существует ли вариант быстрей?

Попробуй загрузить на Яндекс Диск

**Comment by FiLinX** [comment]
кстати, чтобы ютуб выдавал линк на загруженное побыстрее для обработки его VOTом, туда можно грузить сильно ужатое видео:
 "Вы можете рассмотреть возможность предоставления видео пониженного качества, если эти видео не будут общедоступны на YouTube и загружаются только для использования в качестве ссылок Content ID. Эти видео могут иметь типичное разрешение «одна четверть», т. е. 320x240. Однако, чтобы обеспечить эффективные ссылки, видео должно быть больше 200 строк."
 это из его справки - Характеристики форматирования видео и аудио - Cправка - YouTube - https://support.google.com/youtube/answer/4603579
 ещё мож это пригодится  -  Рекомендуемые YouTube настройки кодировки загрузки - Cправка - YouTube - https://support.google.com/youtube/answer/1722171

**Comment by inilim** [comment]
Вы через ffmpeg можете заменить изображение видео на заглушку, например черный экран. Такой формат будет весить значительно ниже и обработка сервисами такие как ютуб будет быстрее.
Но с появление перевода в yandex disk, ждать обработки не потребуется. Там видео сразу отдается.
