### ISSUE TITLE
SoundFixer или собственная громкость перевода +NNN%

### ISSUE THREAD

**Issue by EvVlF** [ilyhalight/voice-over-translation#449]
Приветствую.
Есть такое расширение (не знаю на всех ли браузерах, здесь и далее про Firefox) SoundFixer - очень удобно для каждой вкладки крутить свой уровень звука видео/аудио/медиа на 100/200/.../600%. Вопрос, скорее всего, может быть не совсем по адресу, но если с вашей стороны возможно - прокинуть, чтобы была возможность регулирования громкости для подобных (или самого популярного) плагинов или как можно "полюбить" voice-over и soundFixer уже сейчас. Если это скорее для "той" стороны (разрабов плагинов) - подскажите, попробую открыть тикет там. 
Ах да, как вариант, просто добавить подобную функциональность в сам скрипт и менюшку. Спасибо.

**Comment by ilyhalight** [comment]
Потом посмотрю, но если и появится поддержка, то уже после релиза 1.5.0

**Comment by ilyhalight** [comment]
Добавлено
