### ISSUE TITLE
Vivaldi + Violetmonkey

### ISSUE THREAD

**Issue by Sergo1217** [ilyhalight/voice-over-translation#45]
Violetmonkey не определяет скрипт как подходящий для youtube

![2022-10-28_22-46-26](https://user-images.githubusercontent.com/16447886/198720164-629b4e7e-e1dd-4017-a315-346e0993dbe9.png)
![2022-10-28_22-45-43](https://user-images.githubusercontent.com/16447886/198720169-7d2b9786-ebce-4820-bacd-311e61718ba0.png)

**Comment by ilyhalight** [comment]
Не уверен, что получиться исправить. Сделать так, чтобы скрипт определялся правильно и кнопка появлялась - легко, - просто добавить объявление асинхронной автоматически выполняющейся функции перед блоков "ифов". Но, насколько я понял, в Violetmonkey недавно (может быть и давно), вышло обновление из-за которого запросы расширения идут через "свой локальный сервер" (хз как правильно сказать, но теперь они похожи на запросы Adguard Userscripts, которые так же идут через локальный сервер) и к ним добавляется хеадер "vm-verifyfb9t0o84jf7lxafw" со значением "VMxhr0.6191102093253058" . Отсюда вытекает новая ошибка, связанная с 402 статус кодом или же надписью "Не удалось запросить перевод видео". 

Единственный вариант, теперь, для использования с виолетманки - https://github.com/mynovelhost/voice-over-translation/
