### ISSUE TITLE
Hе открываются окна с выбором языка. Firefox. 

### ISSUE THREAD

**Issue by leex-leex** [ilyhalight/voice-over-translation#450]
### Operating system / Операционная система

W10x64

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Здравствуйте.
В FF 120 не работают выпадающие окна с выбором языка для перевода и окно с опциями субтитров.
В Chrome эти окна работают.

### Additional information / Дополнительная информация

![VOT](https://github.com/ilyhalight/voice-over-translation/assets/11260887/858d434f-248a-4eab-99aa-828e32fd1c2f)

**Comment by ilyhalight** [comment]
в бете уже давным давно исправлено #349
