### ISSUE TITLE
Существует ли возможность массового перевода ? 

### ISSUE THREAD

**Issue by ennnnnne1** [ilyhalight/voice-over-translation#451]
### Describe your feature / Опишите ваше предложение

У меня есть список из 40 роликов ютуба, можно ли как-нибудь запустить перевод массового для каждого из роликов? (подгружать список)
Написать бота к браузеру который будет сам переходить по страницам и кликать - самое примитивное, но не удобное решение.

Может существует какой-нибудь в еще вариант?
Возможно есть уже похожая функция в самом плагине в которую нужно просто передавать URL из под node? Но в какую сторону смотреть?

**Comment by ilyhalight** [comment]
https://github.com/FOSWLY/vot-cli
