### ISSUE TITLE
Есть вопрос , возможно можно хакнуть..))

### ISSUE THREAD

**Issue by SneNiga** [ilyhalight/voice-over-translation#452]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Приветствую.Так как перевод сломался и переводит только на пару языков, и ошибка на стороне Яндекса, то может быть есть возможность обмануть их систему?
Я к очень далек от IT и всего подобного, но пришла в голову идея.
Я пытаюсь перевести видео на Индонезийский язык, он начинает переводить, так как на это уходит какое-то время, но он блокирует результат перевода как я понимаю, а ЧТО ЕСЛИ прописать в коде Казахстанский язык , а базу данных для перевода подставить Индонезийскую?
Мое нутро подсказывает что вероятность есть, но небольшая.

**Comment by ilyhalight** [comment]
> а базу данных для перевода подставить Индонезийскую

Это происходит на стороне Яндекса

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> _No response_
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.4.1
> ### Describe the bug / Опишите ошибку программы
> 
> Приветствую.Так как перевод сломался и переводит только на пару языков, и ошибка на стороне Яндекса, то может быть есть возможность обмануть их систему? Я к очень далек от IT и всего подобного, но пришла в голову идея. Я пытаюсь перевести видео на Индонезийский язык, он начинает переводить, так как на это уходит какое-то время, но он блокирует результат перевода как я понимаю, а ЧТО ЕСЛИ прописать в коде Казахстанский язык , а базу данных для перевода подставить Индонезийскую? Мое нутро подсказывает что вероятность есть, но небольшая.
> ### Additional information / Дополнительная информация
> 
> _No response_

Удачи
