### ISSUE TITLE
Udemy отсуствует кнопка для перевода

### ISSUE THREAD

**Issue by dred89** [ilyhalight/voice-over-translation#453]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

version 1.4.1

### Describe the bug / Опишите ошибку программы

Здравствуйте. Для начало хочу поблагодарить за скрипт. 
Проблема заключается в том что на сайте udemy.com отсутствует форма для перевода. Все другие расширение отключены. На ютубе работает

Chrome 120.0.0.0

### Additional information / Дополнительная информация

![Снимок](https://github.com/ilyhalight/voice-over-translation/assets/23725580/4afbb943-73d3-4881-beb6-459bbf8bbd32)

**Comment by SashaXser** [comment]
#443
