### ISSUE TITLE
Выбор языка не кликабелен

### ISSUE THREAD

**Issue by korolipliaja** [ilyhalight/voice-over-translation#454]
### Operating system / Операционная система

Fedora linux

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку программы

Меню выбора языка перевода не кликабельно, что интересно на старом ноутбуке та же проблема, но ещё когда я им пользовался без проблем поменял на русский, и все работало, а сейчас и на ноутбуке тоже не кликабельно, так и осталось на русском

**Comment by ilyhalight** [comment]
Обновляйтесь на 1.5.0-beta10
