### ISSUE TITLE
Вышло обновление protobuf 7.2.5

### ISSUE THREAD

**Issue by korenevskiy** [ilyhalight/voice-over-translation#455]
### Describe your feature / Опишите ваше предложение

для удобства можно использовать ссылку на последнюю версию скрипта
https://cdn.jsdelivr.net/npm/protobufjs/dist/protobuf.min.js

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> для удобства можно использовать ссылку на последнюю версию скрипта https://cdn.jsdelivr.net/npm/protobufjs/dist/protobuf.min.js

Там ничего нового нету...

**Comment by korenevskiy** [comment]
> > ### Describe your feature / Опишите ваше предложение
> > для удобства можно использовать ссылку на последнюю версию скрипта https://cdn.jsdelivr.net/npm/protobufjs/dist/protobuf.min.js
> 
> Там никогда не появляется ничего нового, иногда только исправляют какие-то незаметные ошибки. Предлагаю тебе сделать pull request, чем просить добавить что-то незначительное.

Не могу понять куда PRить, там увидел строку
`// @require https://cdnjs.cloudflare.com/ajax/libs/protobufjs/7.2.3/light/protobuf.min.js`
но не ужели в неё вставлять, но ведь она закоментирована, а других ресурсов с подобным путём я не нашёл

**Comment by ilyhalight** [comment]
> > > ### Describe your feature / Опишите ваше предложение
> > > для удобства можно использовать ссылку на последнюю версию скрипта https://cdn.jsdelivr.net/npm/protobufjs/dist/protobuf.min.js
> > 
> > 
> > Там никогда не появляется ничего нового, иногда только исправляют какие-то незаметные ошибки. Предлагаю тебе сделать pull request, чем просить добавить что-то незначительное.
> 
> Не могу понять куда PRить, там увидел строку `// @require https://cdnjs.cloudflare.com/ajax/libs/protobufjs/7.2.3/light/protobuf.min.js` но не ужели в неё вставлять, но ведь она закоментирована, а других ресурсов с подобным путём я не нашёл

она не закомментирована, это мета информация, которую парсят и грузят расширения-загрузчики.

В "сыром" состояние она хранится в [headers.json](https://github.com/ilyhalight/voice-over-translation/blob/dev/src/headers.json)

**Comment by korenevskiy** [comment]
А для каких целей используют protobuf, дайте короткий комментарий новичку?

**Comment by ilyhalight** [comment]
> А для каких целей используют protobuf, дайте короткий комментарий новичку?

для общения с сервером
