### ISSUE TITLE
Про блокировку worker - версии в РФ

### ISSUE THREAD

**Issue by Baltazar500** [ilyhalight/voice-over-translation#461]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

AdGuard

### Script version / Версия скрипта

1.5.0-beta4

### Describe the bug / Опишите ошибку

>Если вы используете cloudflare версию расширения и имеете российский айпи, то убедитесь, что в настройках у вас стоит домен воркера vot.deno.dev

Если хост для worker'a использовелся свой, то менять надо на "vot.xxx.deno.dev" ? Или как ? deno.dev - это оф.хост CF или какой-то самопал ?

**Comment by ilyhalight** [comment]
> deno.dev - это оф.хост CF или какой-то самопал ?

deno.dev - это сайт от разработчиков Deno (аналог NodeJS), которые, так же, бесплатно дают возможность похостить у себя проекты (правда лимиты чуть меньше чем у CF)

> Если хост для worker'a использовелся свой, то менять надо на "vot.xxx.deno.dev" ? Или как ?

Нужно по [инструкции](https://github.com/FOSWLY/vot-worker/tree/main/deno) задеплоить [воркер](https://github.com/FOSWLY/vot-worker) на дено дев, и там можно будет в настройках проектах посмотреть домен на который нужно поменять (если указано 2 и более домена, то выбирайте тот, у которого название соответствует названию проекта (в моем случае `vot`))
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/6f286e16-4625-44d9-851c-0761ad11e506)

**Comment by Baltazar500** [comment]
>Нужно по [инструкции](https://github.com/FOSWLY/vot-worker/tree/main/deno) задеплоить [воркер](https://github.com/FOSWLY/vot-worker) на deno.dev, и там можно будет в настройках проектах посмотреть домен на который нужно поменять (если указано 2 и более домена, то выбирайте тот, у которого название соответствует названию проекта (в моем случае vot))

Понял. Спасибо. Чуть позже попробую, как дойдут руки. Если возникнут сложности, отпишусь здесь. Пока не сильно критично т.к. worker - версия работает на смарте с ведром из под адгарда, где у меня крутится zapret, который позволяет ей работать без всяких VPN'ов.

Кстати, а чего workers.dev впал в немилость ? Вроде официально он не заблокирован, но есть перекрёстные блокировки по определённым ip-адресам. Дело в этом ?

**Comment by ilyhalight** [comment]
> > Нужно по [инструкции](https://github.com/FOSWLY/vot-worker/tree/main/deno) задеплоить [воркер](https://github.com/FOSWLY/vot-worker) на deno.dev, и там можно будет в настройках проектах посмотреть домен на который нужно поменять (если указано 2 и более домена, то выбирайте тот, у которого название соответствует названию проекта (в моем случае vot))
> 
> Понял. Спасибо. Чуть позже попробую, как дойдут руки. Если возникнут сложности, отпишусь здесь. Пока не сильно критично т.к. worker - версия работает на смарте с ведром из под адгарда, где у меня крутится zapret, который позволяет ей работать без всяких VPN'ов.
> 
> Кстати, а чего workers.dev впал в немилость ? Вроде официально он не заблокирован, но есть перекрёстные блокировки по определённым ip-адресам. Дело в этом ?

¯\_(ツ)_/¯

**Comment by vanbavt08ct** [comment]
> > > Bạn có thể sử dụng [tài khoản của mình trên deno.dev, và bạn có thể sử dụng công cụ này để nâng cao năng ](https://github.com/FOSWLY/vot-worker)[lực](https://github.com/FOSWLY/vot-worker/tree/main/deno) của mình không cần phải làm gì (если указано 2 và более домена, то выбирайте тот, у которого название соответствует названию проекта (в tôi sẽ bỏ phiếu))[](https://github.com/FOSWLY/vot-worker)
> > 
> > 
> > Понял. Chắc chắn rồi. Bạn có thể làm điều đó, vì vậy bạn có thể làm điều đó. Bạn có thể làm được điều đó. Пока не сильно критично т.к. công nhân - версия работает на смарте с ведром из под адгарда, где у меня крутится крутится zpret, который позволяет ей работать б ез всяких VPN'ов.
> > Vì vậy, bạn có muốn làm việc với công nhân.dev không? Bạn không cần phải lo lắng về việc sử dụng địa chỉ IP của mình. Bạn đang làm gì vậy?
> 
> ¯_(ツ)_/¯

Здравствуйте,Добрый день,установки заблокированы на многих языках,можно ли купить у вас услугу перевода?Спасибо,что дочитали.
