### ISSUE TITLE
После обновления выбивает ошибку "аудиоформат не поддерживается"

### ISSUE THREAD

**Issue by Backart** [ilyhalight/voice-over-translation#466]
### Operating system / Операционная система

MacOS

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1

### Describe the bug / Опишите ошибку

После обновления выбивает ошибку "аудиоформат не поддерживается", а также "видео недоступно к переводу", переводил с английского на русский. Проверял на платформе YT.

<img width="1329" alt="Знімок екрана 2023-12-26 о 18 52 41" src="https://github.com/ilyhalight/voice-over-translation/assets/63951244/47695efb-f5d1-423e-acfe-5e3d7099d8a6">
<img width="1198" alt="Знімок екрана 2023-12-26 о 18 53 43" src="https://github.com/ilyhalight/voice-over-translation/assets/63951244/24ce77db-2db9-4264-be19-420eaa7cdb35">
<img width="1258" alt="Знімок екрана 2023-12-26 о 18 55 52" src="https://github.com/ilyhalight/voice-over-translation/assets/63951244/8a9eeaee-27f4-4421-9660-0e0e0cca2ddf">

### Additional information / Дополнительная информация

Предположений нет.

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> MacOS
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.4.1
> ### Describe the bug / Опишите ошибку
> 
> После обновления выбивает ошибку "аудиоформат не поддерживается", а также "видео недоступно к переводу", переводил с английского на русский. Проверял на платформе YT.
> <img alt="Знімок екрана 2023-12-26 о 18 52 41" width="1329" src="https://private-user-images.githubusercontent.com/63951244/292897563-47695efb-f5d1-423e-acfe-5e3d7099d8a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA0MzUsIm5iZiI6MTcwMzYxMDEzNSwicGF0aCI6Ii82Mzk1MTI0NC8yOTI4OTc1NjMtNDc2OTVlZmItZjVkMS00MjNlLWFjZmUtNWUzZDcwOTlkOGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2N2Q3NGQwNmNjMzI3MTJmYTYwZDk2MzY0NmFiZTZlYmE3MmNjNTY1YTc5MmM4ZGQzZjY2MWFjZDFiMWVkMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FA2pEgs2hZaObCtcjRN5jdE3vaytOFRMTcUW-0LjfDI"> <img alt="Знімок екрана 2023-12-26 о 18 53 43" width="1198" src="https://private-user-images.githubusercontent.com/63951244/292897566-24ce77db-2db9-4264-be19-420eaa7cdb35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA0MzUsIm5iZiI6MTcwMzYxMDEzNSwicGF0aCI6Ii82Mzk1MTI0NC8yOTI4OTc1NjYtMjRjZTc3ZGItMmRiOS00MjY0LWJlMTktNDIwZWFhN2NkYjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDg5ZTI4ZjliNzdjOTkyODc3Y2MwMmMzZThmNzdjZTI2MmI3ODk0ZDY0MTU3MmExOTUwZWMwZDVlZjJlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kVIYye3f0t7VJM9uTrUpYvLQIysP5zspZTwclYLAEh4"> <img alt="Знімок екрана 2023-12-26 о 18 55 52" width="1258" src="https://private-user-images.githubusercontent.com/63951244/292897570-8a9eeaee-27f4-4421-9660-0e0e0cca2ddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2MTA0MzUsIm5iZiI6MTcwMzYxMDEzNSwicGF0aCI6Ii82Mzk1MTI0NC8yOTI4OTc1NzAtOGE5ZWVhZWUtMjdmNC00NDIxLTk2NjAtMGUwZTBjY2EyZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDE3MDIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMmUwMDVlNmI3NzIwNjg3NmIzMDA4MmIyYTVmMDZhMzM5ODNkODAwNzZmMjJhYTY4NWUwOWI5ZDNmYzNhZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R-aB7_cXza3C6NeZH34t8Vh9fnyd2x6pGCXtV_DmKEI">
> ### Additional information / Дополнительная информация
> 
> Предположений нет.

В настройках включи "Проксировать полученное аудио"

**Comment by Backart** [comment]
Спасибо, исправил первую ошибку "аудиоформат не поддерживается", не знаете как исправить вторую с "видео недоступно к переводу"?

**Comment by SashaXser** [comment]
> Спасибо, исправил первую ошибку "аудиоформат не поддерживается", не знаете как исправить вторую с "видео недоступно к переводу"?

Вероятно по этой причине, похоже что никак :/
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/8cfcab2b-487a-4fb0-a5c2-14cf156b82db)
