### ISSUE TITLE
Нажатие на ползунок ставит видео на паузу

### ISSUE THREAD

**Issue by lynrayy** [ilyhalight/voice-over-translation#47]
Просьба пофиксить UI штуки такие как: крайне медленное первое появление меню при нажатии на три точки, пауза при нажатии на ползунок
https://youtu.be/KNTrNLovDC4

**Comment by ilyhalight** [comment]
> крайне медленное первое появление меню при нажатии на три точки

Переборщил со значением "анимации". Уменьшу.

> пауза при нажатии на ползунок

Исправлю в 1.0.9.3
