### ISSUE TITLE
Сдвинуть иконку

### ISSUE THREAD

**Issue by NeilRiver** [ilyhalight/voice-over-translation#471]
### Describe your feature / Опишите ваше предложение

![image](https://github.com/ilyhalight/voice-over-translation/assets/41006652/e37eadd7-12d1-463b-a944-2d22d9464d7f)

Не лучшее расположение ... ютуб имеет свои нативные кнопки на той же высоте и на том же положении

**Comment by ilyhalight** [comment]
Это не нативная кнопка ютуба. Положение вы можете поменять через кастомные стили
