### ISSUE TITLE
Возможно ли добавить поддержку https://rumble.com/ ?

### ISSUE THREAD

**Issue by FiLinX** [ilyhalight/voice-over-translation#475]
### Describe your feature / Опишите ваше предложение

Привет всем!
Просматривая недавно почту, обнаружил там уведомление с данного ресурса о их новостях.
Я даже и не помнил, что когда то регистрировался там)
Зашёл, глянул, ну вполне себе нормальная медиа площадка, по типу ютуба..
Ну и естесственно захотелось поддержки перевода через VOT )
Для примера канал Такера Карлсона там  -  https://rumble.com/c/TuckerCarlson

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Привет всем! Просматривая недавно почту, обнаружил там уведомление с данного ресурса о их новостях. Я даже и не помнил, что когда то регистрировался там) Зашёл, глянул, ну вполне себе нормальная медиа площадка, по типу ютуба.. Ну и естесственно захотелось поддержки перевода через VOT ) Для примера канал Такера Карлсона там - https://rumble.com/c/TuckerCarlson

Она уже есть в 1.5

**Comment by FiLinX** [comment]
упс..  сорри за эту иссу(
не в курсах я был, завис на 1.4.1
