### ISSUE TITLE
В Cloudflare версии при перемотке видео звуковая дорожка запускается сначала

### ISSUE THREAD

**Issue by aethercaastle** [ilyhalight/voice-over-translation#477]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

В Cloudflare версии при перемотке видео звуковая дорожка запускается сначала. Баг есть только в cloudflare версии, в обычной у меня всё в порядке.

**Comment by SrevSA** [comment]
Всех с прошедшими. В тех странах, где Яндекс заблокирован эта проблема актуальна. Решается включением VPN.

**Comment by aethercaastle** [comment]
> Всех с прошедшими. В тех странах, где Яндекс заблокирован эта проблема актуальна. Решается включением VPN.

В странах, где Яндекс заблокирован, проблема решается установкой Cloudflare версии, в которой есть баг: при перемотке видео звуковая дорожка запускается сначала. Включение VPN поможет, разве что, пользоваться обычной версией, в которой такого бага нет. Если не ошибаюсь, до версии 1.5 перемотка работала нормально.

**Comment by ilyhalight** [comment]
Не воспроизводится

**Comment by aethercaastle** [comment]
Сменил прокси сервер с vot-worker.onrender.com на vot-new.toil-dump.workers.dev и всё заработало. Спасибо.
