### ISSUE TITLE
Не срабатывает перевод на twitter

### ISSUE THREAD

**Issue by deadcxap** [ilyhalight/voice-over-translation#478]
### Operating system / Операционная система

Windows 10 21H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

не переводится видео: https://twitter.com/BlackJaxVR/status/1742500310407651746
![image](https://github.com/ilyhalight/voice-over-translation/assets/36386824/ec238d86-f84a-4da5-8765-745e8f56ac3a)

Перевод на ютубе - работает корректно при этом.

### Additional information / Дополнительная информация

Логи из консоли разработчика:
```
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:4191 [db] data from db:  ObjectaudioProxy: 0autoSetVolumeYandexStyle: 1autoTranslate: 0autoVolume: 0.4defaultVolume: 100detectService: "yandex"dontTranslateLanguage: "ru"dontTranslateYourLang: 1highlightWords: 0m3u8ProxyHost: "m3u8proxy.toil-dump.workers.dev"proxyWorkerHost: "vot-worker.onrender.com"responseLanguage: "ru"showPiPButton: 0showVideoSlider: 1subtitlesMaxLength: 300syncVolume: 0translateAPIErrors: 1translationService: "yandex"udemyData: {accessToken: '', expires: 0}[[Prototype]]: Object
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2811 [VOT] EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.twimg.com https://recaptcha.net/recaptcha/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://client-api.arkoselabs.com/ https://www.google-analytics.com https://twitter.com https://x.com https://accounts.google.com/gsi/client https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js https://static.ads-twitter.com  'nonce-NmI2OTBlOGMtMWU2Ny00ZWZmLWE3ZTItN2UzYTFiODRlMTQ2'".

    at Proxy.Function (<anonymous>)
    at f (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:2213)
    at w.get (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:44534)
    at u.resolve (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:21728)
    at w.setup (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:48078)
    at w.encode (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:48558)
    at Object.encodeSubtitlesRequest (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2009:39)
    at requestVideoSubtitles (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2799:33)
requestVideoSubtitles @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2811
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:3014 [VOT] Failed get yandex subtitles
(анонимная) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:3014
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:3095 [VOT] subtitles list Array(0)length: 0[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ (e)reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:5326 [VOT] Set translation from en to ru
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8 Uncaught (in promise) EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' https://*.twimg.com https://recaptcha.net/recaptcha/ https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/ https://client-api.arkoselabs.com/ https://www.google-analytics.com https://twitter.com https://x.com https://accounts.google.com/gsi/client https://appleid.cdn-apple.com/appleauth/static/jsapi/appleid/1/en_US/appleid.auth.js https://static.ads-twitter.com  'nonce-NmI2OTBlOGMtMWU2Ny00ZWZmLWE3ZTItN2UzYTFiODRlMTQ2'".

    at Proxy.Function (<anonymous>)
    at f (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:2213)
    at w.get (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:44534)
    at u.resolve (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:21728)
    at w.setup (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:48078)
    at w.decode (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:8:48718)
    at Object.decodeSubtitlesResponse (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2015:40)
    at userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:3020:28
    at requestVideoSubtitles (userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=185fec5e-ef4c-44be-9c06-20dec5f285ce:2813:5)
```

**Comment by ilyhalight** [comment]
Это еще давно так, скорее всего, поддержку твиттера убрали

**Comment by Buumcode** [comment]
Версия 1.5.0.5.

Аудио дорожка перевода скачивается в формате mp3 и там всё переведено. Но на экране пишут: "Формат аудио не поддерживается".

![001_snap_a5546](https://github.com/ilyhalight/voice-over-translation/assets/159101783/3c10f389-7a32-4a47-8d33-2cd45521552f)

**Comment by ilyhalight** [comment]
> Версия 1.5.0.5.
> 
> Аудио дорожка перевода скачивается в формате mp3 и там всё переведено. Но на экране пишут: "Формат аудио не поддерживается".
> 
> ![001_snap_a5546](https://private-user-images.githubusercontent.com/159101783/302517039-3c10f389-7a32-4a47-8d33-2cd45521552f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMDkyNzUsIm5iZiI6MTcwNzIwODk3NSwicGF0aCI6Ii8xNTkxMDE3ODMvMzAyNTE3MDM5LTNjMTBmMzg5LTdhMzItNGE0Ny04ZDMzLTJjZDQ1NTIxNTUyZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwODQyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmNjZTI2YjY1NWU1YzcwOGQyYTMwM2JkOWJiNzA2NGE5MWQxMzA4OTJkZjMzY2QwMzM0ZWNiNTg1NjgwNmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ONLxF4FCYkwmDXr1qEqjoRSAX_nJCSCkO0kB20xFoHw)

Попробуйте включить проксирование аудио в настройках расширения

**Comment by Buumcode** [comment]
> Попробуйте включить проксирование аудио в настройках расширения

Что-то у меня нет такого в настройках.
![02_snap_a5555](https://github.com/ilyhalight/voice-over-translation/assets/159101783/b707e453-ca7c-425e-96fe-c4742c6a21b0)

**Comment by ilyhalight** [comment]
> > Попробуйте включить проксирование аудио в настройках расширения
> 
> Что-то у меня нет такого в настройках. ![02_snap_a5555](https://private-user-images.githubusercontent.com/159101783/302733370-b707e453-ca7c-425e-96fe-c4742c6a21b0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDQwOTMsIm5iZiI6MTcwNzI0Mzc5MywicGF0aCI6Ii8xNTkxMDE3ODMvMzAyNzMzMzcwLWI3MDdlNDUzLWNhN2MtNDI1ZS05NmZlLWM0NzQyYzZhMjFiMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxODIzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjU2ZmQ1NWI5YTVlMjk4MDRmZDRjZDdlNzg2NGRiYzFiMjAwYTkxOTczNWQwY2RjZDMzNWY0OWNhMjhjZTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MME7AnCGSOS-7GfFgRTN5tnk6oBB1_SXfYSepZPxxeY)

Чтобы это было в настройках нужно поставить cloudflare версию

**Comment by Buumcode** [comment]
> Чтобы это было в настройках нужно поставить cloudflare версию

С cloudflare версией теперь как у топикстартера, пишет – "Не удалось запросить перевод видео".

**Comment by Mirazan** [comment]
Здравствуйте. Тоже не работает перевод в Твиттере. Пробовал разные версии и разные браузеры.

**Comment by Buumcode** [comment]
> если не сложно, то подскажите как скачивать переведённую дорожку)

В менюшке расширения есть кнопки на скачивание как аудио-дорожки перевода, так и субтитров.
![03_snap_a5558](https://github.com/ilyhalight/voice-over-translation/assets/159101783/39d0b74e-8f43-4420-8ea5-fd8e73edcafe)

**Comment by ilyhalight** [comment]
> Но на экране пишут: "Формат аудио не поддерживается".

Отключите CSP для твиттера и все будет работать. Особенности платформы.

**Comment by Buumcode** [comment]
> Отключите CSP для твиттера и все будет работать. Особенности платформы.

Ах, вот оно что. Получилось!
Я вроде отключал – но делал это "не так".
На всякий случай поясню здесь, как надо делать.
1) Скачиваем расширение для браузера https://github.com/PhilGrayson/chrome-csp-disable и устанавливаем его.
2) Расширение должно быть в виде кнопочки на панели браузера. Красное = "Включено" (для этой страницы).
3) Идём на сайт, пробуем перевести – пишет "Формат аудио не поддерживается". 
Тогда ВКЛЮЧАЕМ расширение (чтоб стало красненьким) и ПЕРЕГРУЖАЕМ страницу через Ctrl+F5 (это перегрузка с очисткой кеша).
И тогда работает!
