### ISSUE TITLE
почему при выборе языка на который я хочу перевести, у меня стоят крестики напротив всех языков?

### ISSUE THREAD

**Issue by grynvych** [ilyhalight/voice-over-translation#479]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

почему при выборе языка на который я хочу перевести, у меня стоят крестики напротив всех языков?

**Comment by ilyhalight** [comment]
потому что они не работают
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/4974d77b-03e6-43ea-859d-1ca98173f5d3)
