### ISSUE TITLE
Предложение: синхронизация громкости

### ISSUE THREAD

**Issue by lynrayy** [ilyhalight/voice-over-translation#48]
Предлагаю сделать по выбору синхронизацию громкости плеера с громкостью перевода как в я.браузере

То есть есть фиксированное соотношение громкости оригинала к переводу (или выбранное пользователем), а ВСЮ В ЦЕЛОМ громкость можно регулировать через ютуб плеер. 

Как если бы человек крутил громкость на наушниках

**Comment by ilyhalight** [comment]
Идея интересная, но что-то не приходит в голову как это можно было бы правильно реализовать

**Comment by drv42** [comment]
> 

а ты подсмотри как это сделал предыдущий разраб
https://github.com/sodapng/voice-over-translation?ref=tjournal.ru

**Comment by ilyhalight** [comment]
Добавил

**Comment by lynrayy** [comment]
Оо пойду проверю

**Comment by lynrayy** [comment]
Есть недостатки

**Comment by lynrayy** [comment]
Если выставить своё соотношение громкости оригинала и громкости перевода, а затем убавить перевод в ноль, то когда обратно прибавляешь, то громкость перевода становится 1 к 1, из-за чего смотреть невозможно и звук накладывается.
Так же мне кажется нужна кнопка "Сделать соотношение звука как в яндексе", потому что даже я не знаю как в яндексе настроено, а на слух настраивать сложно. Может из коробки в расширении оно и сделано как в яндексе, но кнопки сброса нету

**Comment by lynrayy** [comment]
> а затем убавить перевод в ноль

Или убавить видео в ноль, а потом прибавлять

**Comment by ilyhalight** [comment]
> Если выставить своё соотношение громкости оригинала и громкости перевода, а затем убавить перевод в ноль, то когда обратно прибавляешь, то громкость перевода становится 1 к 1

Немного не понял про это. Пытался сделать так же, как написано, но звук не накладывался. Может какие-нибудь другие расширения стоят?

> "Сделать соотношение звука как в яндексе"

Чуть позже, наверное, переделаю "синхрозизацию громкости", чтобы там было большее (или кастомное) соотношение в пользу перевода, а не 1 к 1 как сейчас

**Comment by lynrayy** [comment]
> Немного не понял про это.

Я про то, что если прибавить перевод (сделать сильно громче оригинала), а потом убавить громкость видоса в ноль и вернуть, то снова станет 1 к 1

**Comment by ilyhalight** [comment]
> > Немного не понял про это.
> 
> Я про то, что если прибавить перевод (сделать сильно громче оригинала), а потом убавить громкость видоса в ноль и вернуть, то снова станет 1 к 1

Теперь, понял.

**Comment by ilyhalight** [comment]
Немного переделал, должно быть лучше. При изменение громкости через ползунок ютуба не стал делать, чтобы можно было отдельно поменять, только, громкость видео без отключения настройки.

**Comment by lynrayy** [comment]
🤦🏻‍♀️
Лично я не пользуюсь только по одной причине - регулировка звука не как в яндексе.
Я просто хочу регулировать звук через плеер ютуба, я это делаю очень часто. Да даже не страшно если соотношение оригинала к переводу будет фиксированным, чем вот так...

Ладно, я снова попробую, но видимо я так никогда не пересяду на хром обратно)
(меня в я.браузере привлекли две вещи - перевод видео, и перевод текста по выделению)
