### ISSUE TITLE
Плавающая кнопка

### ISSUE THREAD

**Issue by dlt5** [ilyhalight/voice-over-translation#483]
### Describe your feature / Опишите ваше предложение

Добавить возможность перетаскивания плавающей кнопки, как у яндекса. Бесит, что нельзя сдвинуть и свернуть в компакт. 
Можно вообще убрать с кнопки «Перевести» и «Отключить», оставив только индикацию цветом. Кто поставил расширение, и так знает, для чего кнопка. Для большей понятности и отличаемости от яндекса я бы изменил цвет с фиолетового на зелёный.

**Comment by ilyhalight** [comment]
> Для большей понятности и отличаемости от яндекса я бы изменил цвет с фиолетового на зелёный.

Это можно сделать через расширения для стилизации, например Stylus, Stylish 

> Добавить возможность перетаскивания плавающей кнопки, как у яндекса. Бесит, что нельзя сдвинуть и свернуть в компакт.

Может быть будет реализовано

**Comment by dlt5** [comment]
Зелёный это предложение по улучшению. И фиолетовый переживу — и уж точно не
буду что-то ставить специально ради этого.

сб, 13 янв. 2024 г., 02:42 Toil ***@***.***>:

**Comment by XJIOP** [comment]
И еще бы опцию, что бы кнопка не отображалась если видео на твоем языке.

**Comment by team-community** [comment]
я понял, что это добавлено? Но как двигать кнопку?

**Comment by ilyhalight** [comment]
> я понял, что это добавлено? Но как двигать кнопку?

необходимо зажать лкм на кнопке и перенести кнопку к левому/правому краю плеера

**Comment by dlt5** [comment]
Спасибо!
