### ISSUE TITLE
ok.ru

### ISSUE THREAD

**Issue by leonyp** [ilyhalight/voice-over-translation#484]
### Describe your feature / Опишите ваше предложение

Is it possible to add https://ok.ru/ ?

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Is it possible to add https://ok.ru/ ?

It won't work, Yandex can't download videos from ok.ru, so there can't be any translation.

**Comment by FiLinX** [comment]
> Yandex can't download videos from ok.ru

странно это как то..  ведь очень схожи с вконтактовыми

**Comment by SashaXser** [comment]
> > Yandex can't download videos from ok.ru
> 
> странно это как то.. ведь очень схожи с вконтактовыми по крайней мере yt-dlp одинаково позволяет смотреть видосы в потплеере\влц что с ok что с vk

Потом ещё раз попробую, но тогда у меня вообще не хотело что-то переводить

**Comment by SashaXser** [comment]
Получилось, сейчас в пулл свой добавлю

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Is it possible to add https://ok.ru/ ?

Added in 1.5.1-beta1

**Comment by SashaXser** [comment]
> Translation on ok.ru no longer works :/

Just checked, everything works

**Comment by leonyp** [comment]
Then what could be the problem with me, I don’t understand. I tried several times, not just today, after the countdown it freezes at 1 minute and does nothing.
