### ISSUE TITLE
Горячие Клавиши активации закадрового перевода

### ISSUE THREAD

**Issue by ShadowMax** [ilyhalight/voice-over-translation#485]
Подскажите, есть ли Горячие Клавиши активации озвучки?
Не смог найти сам, к сожалению.

**Comment by SashaXser** [comment]
> Подскажите, есть ли Горячие Клавиши активации озвучки? Не смог найти сам, к сожалению.

горячих клавиш для кнопки нету

**Comment by ShadowMax** [comment]
> > Подскажите, есть ли Горячие Клавиши активации озвучки? Не смог найти сам, к сожалению.
> 
> горячих клавиш для кнопки нету

Тогда давайте добавим это в таски, пожалуйста.

**Comment by PANAMA8** [comment]
Всем привет! ;) Благодаря VOT и всей команде разработчиков, я зарегался на гитхабе, чтобы создать ветку о нужде в горячих клавишах вкл/выкл перевода, и обнаружил эту тему :)

Смотрю, что вопрос не решен, а очень бы хотелось. 

Поясню: я ежедневно смотрю иностранные гайды по обучению в сфере музыки, и когда показывают музыкальный фрагмент, то соответственно он под воздействием перевода играет тихо, и я вечно держу указатель мыши на кнопке вкл/выкл VOT, чтобы слушать музыкальные части на оригинальной громкости, это изрядно изнуряет меня, мешает обучаться комфортно :) 

Ради такой благой цели как обучение, сделайте пожалуйста хоткейсы, люди добрые, господа разработчики, я буду премного благодарен от всей души.

И задонатить не жалко, если подскажете куда, по возможности конечно. Надеюсь на понимание. С уважением, PANAMA8.

**Comment by ilyhalight** [comment]
Добавлено, обновитесь до последней версии
