### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by zainllw0w** [ilyhalight/voice-over-translation#487]
### Operating system / Операционная система

win 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

Перестало переводить с подписью "Не удалось запросить перевод видео". Как можно исправить?
<img width="362" alt="image" src="https://github.com/ilyhalight/voice-over-translation/assets/77465388/f2dfc373-0677-492d-a5a3-61bc6beacb9e">

### Additional information / Дополнительная информация

Все обновления стоят последние

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> win 11
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.3
> ### Describe the bug / Опишите ошибку
> 
> Перестало переводить с подписью "Не удалось запросить перевод видео". Как можно исправить? <img alt="image" width="362" src="https://private-user-images.githubusercontent.com/77465388/296129764-f2dfc373-0677-492d-a5a3-61bc6beacb9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDI5NjYsIm5iZiI6MTcwNTA0MjY2NiwicGF0aCI6Ii83NzQ2NTM4OC8yOTYxMjk3NjQtZjJkZmMzNzMtMDY3Ny00OTJkLWE1YTMtNjFiYzZiZWFjYjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA2NTc0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3NjE3MTllNGFlMzVhZWVlMmExZjM3NDI5NTc4OTQ1NWQyM2U1NDczZGQ5YTgxZDg2NTQ5ZWU4ODFhN2E2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WHOaE1nILn-LiTn9ueSsf_Tyev_POfAGQZmqDLQKtTU">
> ### Additional information / Дополнительная информация
> 
> Все обновления стоят последние

Включи проксирование аудио в настройках

**Comment by ilyhalight** [comment]
Используйте cloudflare версию + актуальный домен
