### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by EntonyHop** [ilyhalight/voice-over-translation#488]
### Operating system / Операционная система

macOS 10.15.7

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

Other / Другой

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

Оплатил скрипт менеджер Stay от наших китайских товарищей (встроенный тонко настраиваемый блокировщик рекламы, функция черной темы для любой страницы), но вот данный скрипт выдаёт такую ошибку, прокси пробовал разные. В темперМонкей все ок. Есть идеи как поправить ситуацию?

**Comment by EntonyHop** [comment]
установил cloud flare версию все заработало

**Comment by ilyhalight** [comment]
Закрываю, если работает cloudflare версия. Такое бывает с некоторыми расширениями
