### ISSUE TITLE
[Coursera] Не удается перевести видео, попробуйте позже

### ISSUE THREAD

**Issue by ex1side** [ilyhalight/voice-over-translation#489]
### Operating system / Операционная система

Windows 11 23H2

### Browser / Браузер

Firefox 121.0.1

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3 Cloudflare

### Describe the bug / Опишите ошибку

При попытке перевести видео курса возникает ошибка (Не удается перевести видео, попробуйте позже), пробовал также на видео которые раньше точно работали, но там тоже самое. Другие сервисы по типу ютуба работают
Скриншот консоли:
![зображення](https://github.com/ilyhalight/voice-over-translation/assets/78278069/337ed2b2-bddc-4c43-a062-3fb7571934ac)

**Comment by ilyhalight** [comment]
Проблема на стороне Яндекса
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/53b0d3a6-2d97-4bd6-890c-8d2b84c7abc9)

**Comment by ex1side** [comment]
Благодарю за ответ
