### ISSUE TITLE
БАГ не жмётся кнопка

### ISSUE THREAD

**Issue by lynrayy** [ilyhalight/voice-over-translation#49]
Кнопка "перевести видео" не нажимается (не реагирует)
https://youtu.be/1uum5_OKufQ

**Comment by ilyhalight** [comment]
Можно поподробнее? Какой браузер используется, какие другие расширение для ютуба используются?

**Comment by lynrayy** [comment]
Хром, очевидно
Другие расширения не должны влиять, но стоит YouTube Redux, RYD (дизлайки), после F5 кнопка заработала. Но неприятно всё равно, хочется как в яндексе что бы работало

**Comment by lynrayy** [comment]
Ещё SponsorBlock

**Comment by ilyhalight** [comment]
> Хром, очевидно Другие расширения не должны влиять, но стоит YouTube Redux, RYD (дизлайки), после F5 кнопка заработала. Но неприятно всё равно, хочется как в яндексе что бы работало

Потестирую, если получится воспроизвести, то исправлю
