### ISSUE TITLE
BIbibili wont translate (also the same in the Cloudflare version)

### ISSUE THREAD

**Issue by whitemankpi** [ilyhalight/voice-over-translation#491]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.4

### Describe the bug / Опишите ошибку

1.5.0.4 won't translate Bilibili.cn  service (no matter on which language EN or RU) 
The same problem on the Cloudflare version
![image](https://github.com/ilyhalight/voice-over-translation/assets/63373322/7c1bf703-15f9-4643-a43c-d448bf177ef6)

![image](https://github.com/ilyhalight/voice-over-translation/assets/63373322/878058ee-fc15-47fa-8925-b2a46a7a6853)

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 10 22H2
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.4
> ### Describe the bug / Опишите ошибку
> 
> 1.5.0.4 won't translate Bilibili.cn service (no matter on which language EN or RU) The same problem on the Cloudflare version ![image](https://private-user-images.githubusercontent.com/63373322/296450143-7c1bf703-15f9-4643-a43c-d448bf177ef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNDg2MjYsIm5iZiI6MTcwNTE0ODMyNiwicGF0aCI6Ii82MzM3MzMyMi8yOTY0NTAxNDMtN2MxYmY3MDMtMTVmOS00NjQzLWE0M2MtZDQ0OGJmMTc3ZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDEyMTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5NzVkOGE3Mzk5YzFlYzcxOWVjNWM4OTYxNTUwYmU4OTg5NTdiZmQ4MzE2NTgwMjNlYzk0M2YwNzE1OTJlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B7e4CW6MILxU1pY8ZhbJ4P6Jzj3pmknciWXzfNIENBc)
> 
> ![image](https://private-user-images.githubusercontent.com/63373322/296450241-878058ee-fc15-47fa-8925-b2a46a7a6853.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNDg2MjYsIm5iZiI6MTcwNTE0ODMyNiwicGF0aCI6Ii82MzM3MzMyMi8yOTY0NTAyNDEtODc4MDU4ZWUtZmMxNS00N2ZhLTg5MjUtYjJhNDZhN2E2ODUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEzVDEyMTg0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxNzgwNDM1OGUyNGMzNmRhM2JiYTM1NGM3ZGJhYjQwM2NiYjBjNjIyZTZkMzEzODkxNGRlNzdmZmViNzQxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H9aQAHwpUTiHneQ1kBL4kCBUQUrlpqVsUqfYOijHBek)
> ### Additional information / Дополнительная информация
> 
> _No response_

Show me the console log

**Comment by whitemankpi** [comment]
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] The translation will take about a minute
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857
38Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure element '<URL>'. This request was automatically upgraded to HTTPS, For more information see <URL>
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5620 [VOT] Video Data:  Object
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:4052 [VOT] Translation response:  VideoTranslationResponse
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] The translation will take about a minute
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5620 [VOT] Video Data:  Object
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:4052 [VOT] Translation response:  VideoTranslationResponse
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] Не удается перевести видео, попробуйте позже
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5620 [VOT] Video Data:  Object
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:4052 [VOT] Translation response:  VideoTranslationResponse
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] Не удается перевести видео, попробуйте позже
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857
biliMirror.umd.mini.js:1 bili-mirror: handleUnhandleRejection-Error parsing failed: DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at Ct (https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:41641)
    at Object.<anonymous> (https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:44919)
    at https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:1716
    at Object.next (https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:1821)
    at https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:737
    at new Promise (<anonymous>)
    at n (https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:482)
    at Object.handleUnhandleRejection (https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:44254)
    at https://s1.hdslb.com/bfs/seed/jinkela/short/b-mirror/biliMirror.umd.mini.js:1:49388
    at ft (https://s1.hdslb.com/bfs/static/pcdn-seeder/reward-seeder-1.2.0.min.js:2:354960)
(anonymous) @ biliMirror.umd.mini.js:1

![image](https://github.com/ilyhalight/voice-over-translation/assets/63373322/ee4a4b94-02c1-4716-ae05-373c9f76dda2)

**Comment by whitemankpi** [comment]
userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] Не удается перевести видео, попробуйте позже
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857
await in (anonymous) (async)
(anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:4056
onload @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:1303
Rt @ VM1130:9
(anonymous) @ VM1130:36
Rt @ VM1130:9
r @ VM1130:24
(anonymous) @ VM1130:25
(anonymous) @ VM1130:76
m @ VM1130:76
Lt @ VM1128 content.js:8
m @ VM1128 content.js:65
s @ VM1128 content.js:66
setTimeout (async)
setTimeout @ VM1128 content.js:48
processMessage @ VM1128 content.js:51
(anonymous) @ VM1128 content.js:73
g @ VM1128 content.js:66
Rt @ VM1130:9
p @ VM1130:76
u @ VM1130:78
(anonymous) @ VM1130:78
eo @ VM1130:17
send @ VM1130:78
No @ VM1130:25
qo @ VM1130:25
i @ VM1130:36
(anonymous) @ VM1130:45
await in (anonymous) (async)
(anonymous) @ VM1130:46
q @ VM1130:43
(anonymous) @ VM1130:44
(anonymous) @ VM1130:20
Rt @ VM1130:9
t @ VM1130:9
message @ VM1130:20
message @ VM1130:21
(anonymous) @ VM1130:81
m @ VM1130:77
Lt @ VM1128 content.js:8
m @ VM1128 content.js:65
u @ VM1128 content.js:67
(anonymous) @ VM1128 content.js:67
Sn @ VM1128 content.js:15
send @ VM1128 content.js:67
m @ VM1128 content.js:16
g @ VM1128 content.js:16
(anonymous) @ VM1128 content.js:45
s @ VM1128 content.js:43
s @ VM1128 content.js:43
await in s (async)
(anonymous) @ VM1128 content.js:43
BV1i8411w724/?spm_id_from=autoNext&vd_source=4aca9e844f56379f3299dc1af20ca037:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV1i8411w724/?spm_id_from=autoNext&vd_source=4aca9e844f56379f3299dc1af20ca037' was loaded over HTTPS, but requested an insecure element 'http://i0.hdslb.com/bfs/b/7e947f8e64c7802a16de7ebec8a8e290160ec668.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by SashaXser** [comment]
> userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 [VOT] Не удается перевести видео, попробуйте позже (anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:5857 await in (anonymous) (async) (anonymous) @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:4056 onload @ userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=34c285b3-2130-4755-b274-4a8d3a1945ae:1303 Rt @ VM1130:9 (anonymous) @ VM1130:36 Rt @ VM1130:9 r @ VM1130:24 (anonymous) @ VM1130:25 (anonymous) @ VM1130:76 m @ VM1130:76 Lt @ VM1128 content.js:8 m @ VM1128 content.js:65 s @ VM1128 content.js:66 setTimeout (async) setTimeout @ VM1128 content.js:48 processMessage @ VM1128 content.js:51 (anonymous) @ VM1128 content.js:73 g @ VM1128 content.js:66 Rt @ VM1130:9 p @ VM1130:76 u @ VM1130:78 (anonymous) @ VM1130:78 eo @ VM1130:17 send @ VM1130:78 No @ VM1130:25 qo @ VM1130:25 i @ VM1130:36 (anonymous) @ VM1130:45 await in (anonymous) (async) (anonymous) @ VM1130:46 q @ VM1130:43 (anonymous) @ VM1130:44 (anonymous) @ VM1130:20 Rt @ VM1130:9 t @ VM1130:9 message @ VM1130:20 message @ VM1130:21 (anonymous) @ VM1130:81 m @ VM1130:77 Lt @ VM1128 content.js:8 m @ VM1128 content.js:65 u @ VM1128 content.js:67 (anonymous) @ VM1128 content.js:67 Sn @ VM1128 content.js:15 send @ VM1128 content.js:67 m @ VM1128 content.js:16 g @ VM1128 content.js:16 (anonymous) @ VM1128 content.js:45 s @ VM1128 content.js:43 s @ VM1128 content.js:43 await in s (async) (anonymous) @ VM1128 content.js:43 BV1i8411w724/?spm_id_from=autoNext&vd_source=4aca9e844f56379f3299dc1af20ca037:1 Mixed Content: The page at 'https://www.bilibili.com/video/BV1i8411w724/?spm_id_from=autoNext&vd_source=4aca9e844f56379f3299dc1af20ca037' was loaded over HTTPS, but requested an insecure element 'http://i0.hdslb.com/bfs/b/7e947f8e64c7802a16de7ebec8a8e290160ec668.png'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

Is the problem only with this video?

**Comment by SashaXser** [comment]
Что-то видео у того чела вообще не переводятся. Проблема на стороне Яндекса...

**Comment by whitemankpi** [comment]
> Is the problem only with this video?

problem with any video

**Comment by ilyhalight** [comment]
Уже работает. Были какие-то проблемы на стороне Яндекса
