### ISSUE TITLE
Перевод начинается не там, где нужно

### ISSUE THREAD

**Issue by Dimko4ka** [ilyhalight/voice-over-translation#492]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.4

### Describe the bug / Опишите ошибку

Доброго времини суток. У меня почему-то перевод начинается не там где нужно. А если я жму на паузу, к примеру в середине видео, то перевод начинается с начала. Версия VOT у меня Cloudflare.

https://github.com/ilyhalight/voice-over-translation/assets/126572811/15213524-3a10-44fc-b981-63625d4945fd

**Comment by ilyhalight** [comment]
Смените домен worker прокси-сервера на vot-new.toil-dump.workers.dev. Похоже render.com не поддерживает постоянных соединений из-за чего не получается поставить нужное время аудио дорожки (если верить https://stackoverflow.com/questions/37044064/html-audio-cant-set-currenttime)

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/ef1eb2dd-0772-431a-8c19-d23c086a2951)

**Comment by Dimko4ka** [comment]
> vot-new.toil-dump.workers.dev

Спасибо, сработало! Все работает правильно!

**Comment by ilyhalight** [comment]
[Исправлено](https://github.com/FOSWLY/vot-worker/pull/1)
