### ISSUE TITLE
Перевод на Coursera

### ISSUE THREAD

**Issue by igor-sandul** [ilyhalight/voice-over-translation#493]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.3

### Describe the bug / Опишите ошибку

Заводил уже баг-репорт на отсутсnвие перевода на Coursera. Вопрос решился путем замены на ".vjs-v6" в 2х местах. Это было в декабре на версии 1.4.1 и 1.5.10 бета. Сейчас стоит 1.5.0.3 и там уже это исправлено, но перевода нет, причем где точно был перевод раньше. Т.е. видео в mp4 и субтитры русские точно есть. Сейчас же перевода на всем изучаемом курсе нет, пишет не удается перевести видео, попробуйте попозже. При этом есть сообщение подождите минуту. Проверил на яндекс браузере. Перевод есть. Только автоматом не определяет английский, нужно выбрать английский вручную в настройках и передвинуть ползунок вкл. перевод, появляется кнопка перевода и сам перевод. Самое интересное тот ролик, который перевел в Яндексе, потом переводит и в Хроме, но только его, на всех других ошибка.

### Additional information / Дополнительная информация

![2024-01-17_00-37-06](https://github.com/ilyhalight/voice-over-translation/assets/126835820/359a3922-2830-4c18-bf6b-70bd55490c3c)
Ролик в Яндекс браузере
![Screenshot_1](https://github.com/ilyhalight/voice-over-translation/assets/126835820/3ab87304-528d-4a8f-b5e8-8472114210ef)
Тот же ролик в хроме, после перевода в Яндексе
![Screenshot_2](https://github.com/ilyhalight/voice-over-translation/assets/126835820/0a7839c2-eb99-43d4-adaa-4072f5d56137)
Следующий ролик в Хроме

**Comment by igor-sandul** [comment]
Перепутал подписи под двумя последними скринами, думаю понятно

**Comment by igor-sandul** [comment]
![Screenshot_3](https://github.com/ilyhalight/voice-over-translation/assets/126835820/68766ff8-7620-457b-8096-e33e69364277)
ролик в хроме ,где есть перевод

**Comment by igor-sandul** [comment]
![Screenshot_5](https://github.com/ilyhalight/voice-over-translation/assets/126835820/951524e2-4c7c-4de8-8d52-291c0a3bdb75)
![Screenshot_4](https://github.com/ilyhalight/voice-over-translation/assets/126835820/58ea6e4f-5556-49b3-bb7a-102a338ffb03)
ролик в хроме,где нет перевода до нажатия кнопки перевод и после

**Comment by ilyhalight** [comment]
У меня как и в #489 даже в яндексе не переводит

**Comment by igor-sandul** [comment]
Яндекс переводит, правда, с vpn . Иногда нужно в настройках скрипта принудительно указать английский. Но вот есть нюанс, что перевод появляется в хроме, если предварительно перевести в яндексе. Имеется ввиду один и тот же ролик. Может в этом фича и сюда нужно копать. Я ничего не требую, просто надеюсь моя инфа интересна разработчику. Но полагаю, что в приоритете ютуб у разработчика...

**Comment by ilyhalight** [comment]
Исправлено в 1.5.0.5
