### ISSUE TITLE
Кнопка на Айпаде

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#497]
### Operating system / Операционная система

iPad

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

Version: cloudflare 1.5.0.5

### Describe the bug / Опишите ошибку

Слишком сильно растянута кнопка 
![IMG_0223](https://github.com/ilyhalight/voice-over-translation/assets/4968313/cc2aa681-4b2a-4668-bff0-87d4f45e1bb4)

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> iPad
> ### Browser / Браузер
> 
> Safari
> ### Userscript manager / Скриптовый движок
> 
> UserScripts
> ### Script version / Версия скрипта
> 
> Version: cloudflare 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> Слишком сильно растянута кнопка ![IMG_0223](https://private-user-images.githubusercontent.com/4968313/298561340-cc2aa681-4b2a-4668-bff0-87d4f45e1bb4.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5Mzg0ODksIm5iZiI6MTcwNTkzODE4OSwicGF0aCI6Ii80OTY4MzEzLzI5ODU2MTM0MC1jYzJhYTY4MS00YjJhLTQ2NjgtYmZmMC04N2Q0ZjQ1ZTFiYjQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE1NDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYTdmM2I3MGNhNzQ3NTJhMGFiN2Q0MmQ2NzM3MDUxYmQxNWVkZDZiNzEzNzY2OGE5MjM1YjQxNGU1YjllY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0JFbqKA6Bb26MSOtXzxQXSh1IIcaqgF4z6q1QRyeMrw)
> ### Additional information / Дополнительная информация
> 
> _No response_

Мне кажется, это локальная проблема. В 1.4.1 нет такой проблемы?

**Comment by Dragoy** [comment]
нет, там все четко было. 
Так же на айпаде много разных косяков, с тем что оно не сразу начинает воспроизведение, звук перевода или видео в настройках не регулируются. Я бы как-то мог помочь с дебагом?

**Comment by SashaXser** [comment]
> нет, там все четко было. Так же на айпаде много разных косяков, с тем что оно не сразу начинает воспроизведение, звук перевода или видео в настройках не регулируются. Я бы как-то мог помочь с дебагом?

А ошибки есть в консоли?

**Comment by Dragoy** [comment]
> А ошибки есть в консоли?
Если нужно попробую глянуть

**Comment by SashaXser** [comment]
> > А ошибки есть в консоли?
> > Если нужно попробую глянуть

Картинка не загрузилась

**Comment by ilyhalight** [comment]
Исправлено
