### ISSUE TITLE
Работа расширения.

### ISSUE THREAD

**Issue by vruzin** [ilyhalight/voice-over-translation#5]
у меня ошибка: https://bit.ly/3yrbzHW

1. Не понятно зачем вебсервер.
2. Надо инструкцию по запуску, иначе только программисты могут запустить, и то с проблемами.
3. как бы избавится от вебсервера? (или заменить чем-то легким, чтоб дилетант мог запустить)

Я не разбирался досконально как работает и зачем запускать в фоне еще и яндекс браузер... всё же как оно работает?

**Comment by DmitriyPekar** [comment]
![image](https://user-images.githubusercontent.com/14822106/176379662-36016f7c-11f2-4c76-8766-7cbfd9f914ff.png)

с новой версией, тебе не нужен веб сервер, а нужен Tampermonkey/Greasemonkey и установить скрипт. И будет всё работать

**Comment by vruzin** [comment]
Странно, неделю назад у меня не работало, а сейчас работает!!! СУПЕР!!! Спасибо громадное!!!
