### ISSUE TITLE
Перевод трансляций YouTube

### ISSUE THREAD

**Issue by MjKey** [ilyhalight/voice-over-translation#50]
В Яндекс браузере, уже есть перевод трансляций с задержкой, есть возможность реализовать в скрипте это?

**Comment by ilyhalight** [comment]
Скажу так, пока что, не планируется. Нужно доделать до конца, то, что есть сейчас.

Да и сами обновления переводчика в Яндексе у меня ещё не появились. У меня, там, до сих пор доступен. только. перевод видео на ютубе (+ перевод трансляций для канала наса и ещё каких-то каналов, которые я не думаю, что будут кому-то интересны)

Если кому-то нужен дамп запросов перевода трансляций для каналов наса и пр. (ну вроде правильно сдампил):
https://letsupload.cc/g3Yb70Hayb/Documents_zip
