### ISSUE TITLE
Перевод хранится меньше часа (возможно баг Яндекса)

### ISSUE THREAD

**Issue by oxalates** [ilyhalight/voice-over-translation#500]
### Operating system / Операционная система

Win 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.0.1

### Describe the bug / Опишите ошибку

Раньше перевод хранился около двух недель. Если есть плейлист, то можно было прокликать видео, чтобы они поставились на перевод (чтобы не ждать по 5-10 мин).

Теперь же, я несколько раз прокликиваю видео из плейлиста чтобы начался перевод. И некоторые видео хранят перевод буквально пару минут. Это не связано с популярностью видео. Это не связано с тем, что скрипт не успел запуститься.
Это либо ошибка Яндекса (может понизили срок хранения видео, но почему тогда рандом такой?), либо что-то с расширением.

### Additional information / Дополнительная информация

Речь о Ютюбе.

**Comment by chrom007** [comment]
У меня даже сегодня было такое что в одном браузере мне писало "Перевод может занять несколько минут", а в тоже время в другом браузере перевод включался моментально...

**Comment by FiLinX** [comment]
на самом деле Яндекс же переезжал недавно, переносил многие свои центры с Нидерландов
и вот видимо сейчас происходит веерный выбор подключения к какому из датацентров обратиться
например сейчас почти у 90% свежих роликов на топовых каналах, которые яндекс раньше сам держал в приоритете (то есть выдавал перевод сразу, из кеша своего)  -  сейчас приходится ожидать перевода
