### ISSUE TITLE
Перевод не синхронизируется с временем видео

### ISSUE THREAD

**Issue by chrom007** [ilyhalight/voice-over-translation#501]
### Operating system / Операционная система

Windows 10 22H2 (latest)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5 (latest)

### Describe the bug / Опишите ошибку

При включение функции `Проксировать полученное аудио` звук перевода начинает воспроизводиться **заново** при **каждой перемотке** или возобновлению видео. Как только данная функция выключается то перевод ведёт себя нормально и полностью синхронизируется с видео

### Additional information / Дополнительная информация

https://github.com/ilyhalight/voice-over-translation/assets/12010456/edcffd58-3adb-434f-9abd-03f12ae194ed

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 10 22H2 (latest)
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5 (latest)
> ### Describe the bug / Опишите ошибку
> 
> При включение функции `Проксировать полученное аудио` звук перевода начинает воспроизводиться **заново** при **каждой перемотке** или возобновлению видео. Как только данная функция выключается то перевод ведёт себя нормально и полностью синхронизируется с видео
> ### Additional information / Дополнительная информация
> 2024-01-28.07-00-25.mp4

Это происходит в любом браузере?

**Comment by chrom007** [comment]
@SashaXser не проверял 🤔

**Comment by SashaXser** [comment]
> @SashaXser не проверял 🤔

В #492 вроде такая же проблема, возможно тебе поможет смена воркера на vot-new.toil-dump.workers.dev

Также, возможно эта проблема исправлена в моей версии [скрипта](https://github.com/SashaXser/voice-over-translation/tree/dev/dist)

**Comment by chrom007** [comment]
@SashaXser Да, первый вариант действительно помог, это было довольно таки не очевидно 😅 
Возможно стоит отказаться от использования render.com или не делать его значением по умолчанию 🤔 

Ваша версия скрипта к сожалению не пофиксила данную проблему, всётаки это действительно проблема в хосте

**Comment by SashaXser** [comment]
> @SashaXser Да, первый вариант действительно помог, это было довольно таки не очевидно 😅 Возможно стоит отказаться от использования render.com или не делать его значением по умолчанию 🤔
> 
> Ваша версия скрипта к сожалению не пофиксила данную проблему, всётаки это действительно проблема в хосте

Не знаю, в Firefox я никак не смог воспроизвести проблему. Render не имеет лимитов на количество запросов, поэтому он сейчас и используется. У вас нету Firefox, чтобы проверить есть в нём такая же проблема? Возможно, это проблема только в хромоподобных браузерах.

**Comment by chrom007** [comment]
@SashaXser Да, скорее всего так и есть. 

Я открыл в инкогнито одно и тоже видео, с одинаковыми настройками расширения в двух разных браузерах. В итоге в Chrome я столкнулся с той же проблемой синхронизации, а в Firefox всё работает отлично даже с render... Это очень странно как по мне 😄

**Comment by chrom007** [comment]
Также я протестировал в **Edge** и в нём также озвучка не синхронизируется
Наверное и вправду какая-то проблема связанна с Chromium движком 😞

На всякий случай уточню что тестировал я **Cloudflare версию** расширения

**Comment by SashaXser** [comment]
> Ещё я протестировал в **Edge** и в нём также озвучка не синхронизируется а начинается заново Наверное и вправду какая-то проблема связанна с Chromium движком и хостом Render 😞
> 
> На всякий случай уточню что тестировал я **Cloudflare версию** расширения

Разорался, Илья накосячит с заголовками ответов. 
Хром не может проматывать аудио, если не знает сколько байт содержит аудио. 
То есть если нету заголовка "Content-Length", мотать он не будет. 😐

Можешь протестить этот воркер: vottest.onrender.com

**Comment by ilyhalight** [comment]
[Исправлено](https://github.com/FOSWLY/vot-worker/pull/1)
