### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by aratori1** [ilyhalight/voice-over-translation#503]
### Operating system / Операционная система

Windows 11 Pro 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

Cloudflare 1.5.0.5

### Describe the bug / Опишите ошибку

Не удалось запросить перевод видео
![chrome_8flm2MfRj2](https://github.com/ilyhalight/voice-over-translation/assets/96918464/092e7ada-9308-4d0e-be40-36810ee53e8b)

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 11 Pro 23H2
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> Cloudflare 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> Не удалось запросить перевод видео ![chrome_8flm2MfRj2](https://private-user-images.githubusercontent.com/96918464/300911750-092e7ada-9308-4d0e-be40-36810ee53e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDIzMTcsIm5iZiI6MTcwNjY0MjAxNywicGF0aCI6Ii85NjkxODQ2NC8zMDA5MTE3NTAtMDkyZTdhZGEtOTMwOC00ZDBlLWJlNDAtMzY4MTBlZTUzZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2M3ZWU3MzE4YmMwM2M1ZWJhNGRkNDY2ZTI3NjNhOWRjNzQwNWNhYzc0YjUxMWE2Nzk5NmQxMzIyNTFhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0y1MvRZRTp5OFWAqaIDtKlvEYPrc5kdiOFGtHEBoUg)
> ### Additional information / Дополнительная информация
> 
> _No response_

Починилось?

**Comment by aratori1** [comment]
> > ### Operating system / Операционная система
> > Windows 11 Pro 23H2
> > ### Browser / Браузер
> > Chrome
> > ### Userscript manager / Скриптовый движок
> > Tampermonkey
> > ### Script version / Версия скрипта
> > Cloudflare 1.5.0.5
> > ### Describe the bug / Опишите ошибку
> > Не удалось запросить перевод видео ![chrome_8flm2MfRj2](https://private-user-images.githubusercontent.com/96918464/300911750-092e7ada-9308-4d0e-be40-36810ee53e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDIzMTcsIm5iZiI6MTcwNjY0MjAxNywicGF0aCI6Ii85NjkxODQ2NC8zMDA5MTE3NTAtMDkyZTdhZGEtOTMwOC00ZDBlLWJlNDAtMzY4MTBlZTUzZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2M3ZWU3MzE4YmMwM2M1ZWJhNGRkNDY2ZTI3NjNhOWRjNzQwNWNhYzc0YjUxMWE2Nzk5NmQxMzIyNTFhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0y1MvRZRTp5OFWAqaIDtKlvEYPrc5kdiOFGtHEBoUg)
> > ### Additional information / Дополнительная информация
> > _No response_
> 
> Починилось?

Да, но ошибки в консоли все так же есть.

**Comment by SashaXser** [comment]
> > > ### Operating system / Операционная система
> > > Windows 11 Pro 23H2
> > > ### Browser / Браузер
> > > Chrome
> > > ### Userscript manager / Скриптовый движок
> > > Tampermonkey
> > > ### Script version / Версия скрипта
> > > Cloudflare 1.5.0.5
> > > ### Describe the bug / Опишите ошибку
> > > Не удалось запросить перевод видео ![chrome_8flm2MfRj2](https://private-user-images.githubusercontent.com/96918464/300911750-092e7ada-9308-4d0e-be40-36810ee53e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDIzMTcsIm5iZiI6MTcwNjY0MjAxNywicGF0aCI6Ii85NjkxODQ2NC8zMDA5MTE3NTAtMDkyZTdhZGEtOTMwOC00ZDBlLWJlNDAtMzY4MTBlZTUzZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2M3ZWU3MzE4YmMwM2M1ZWJhNGRkNDY2ZTI3NjNhOWRjNzQwNWNhYzc0YjUxMWE2Nzk5NmQxMzIyNTFhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0y1MvRZRTp5OFWAqaIDtKlvEYPrc5kdiOFGtHEBoUg)
> > > ### Additional information / Дополнительная информация
> > > _No response_
> > 
> > 
> > Починилось?
> 
> Да, но ошибки в консоли все так же есть.

Какие?

**Comment by aratori1** [comment]
> > > > ### Operating system / Операционная система
> > > > Windows 11 Pro 23H2
> > > > ### Browser / Браузер
> > > > Chrome
> > > > ### Userscript manager / Скриптовый движок
> > > > Tampermonkey
> > > > ### Script version / Версия скрипта
> > > > Cloudflare 1.5.0.5
> > > > ### Describe the bug / Опишите ошибку
> > > > Не удалось запросить перевод видео ![chrome_8flm2MfRj2](https://private-user-images.githubusercontent.com/96918464/300911750-092e7ada-9308-4d0e-be40-36810ee53e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NDIzMTcsIm5iZiI6MTcwNjY0MjAxNywicGF0aCI6Ii85NjkxODQ2NC8zMDA5MTE3NTAtMDkyZTdhZGEtOTMwOC00ZDBlLWJlNDAtMzY4MTBlZTUzZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDE5MTMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwN2M3ZWU3MzE4YmMwM2M1ZWJhNGRkNDY2ZTI3NjNhOWRjNzQwNWNhYzc0YjUxMWE2Nzk5NmQxMzIyNTFhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C0y1MvRZRTp5OFWAqaIDtKlvEYPrc5kdiOFGtHEBoUg)
> > > > ### Additional information / Дополнительная информация
> > > > _No response_
> > > 
> > > 
> > > Починилось?
> > 
> > 
> > Да, но ошибки в консоли все так же есть.
> 
> Какие?

Только что понял, что те ошибки не относятся к VOT. 
Проблема решена.
