### ISSUE TITLE
Перевод видео для dev.epicgames.com

### ISSUE THREAD

**Issue by MjKey** [ilyhalight/voice-over-translation#505]
На сайте размещены обучающие ролики, было бы круто иметь перевод для них.

Примеры ссылок с видео:
https://dev.epicgames.com/community/learning/courses/3ke/your-first-hour-in-unreal-engine-5-2/4Ovq/unreal-engine-creating-your-first-project
https://dev.epicgames.com/community/learning/tutorials/e2V/your-first-game-in-unreal-engine-5
https://dev.epicgames.com/community/learning/tutorials/lMr9/unreal-engine-begin-play-programming

Знаю что такое предложение поступало в 23 году, может изменилось что-нибудь?

**Comment by SashaXser** [comment]
> На сайте размещены обучающие ролики, было бы круто иметь перевод для них.
> 
> Примеры ссылок с видео: https://dev.epicgames.com/community/learning/courses/3ke/your-first-hour-in-unreal-engine-5-2/4Ovq/unreal-engine-creating-your-first-project https://dev.epicgames.com/community/learning/tutorials/e2V/your-first-game-in-unreal-engine-5 https://dev.epicgames.com/community/learning/tutorials/lMr9/unreal-engine-begin-play-programming
> 
> Знаю что такое предложение поступало в 23 году, может изменилось что-нибудь?

Технически это возможно, но там используется не обычный mp4, а DASH-MPD. Его нужно будет как-то скормить Яндексу.

**Comment by ilyhalight** [comment]
Добавлено в последней версии скрипта
