### ISSUE TITLE
Останавливается звук при переключении на другую вкладку

### ISSUE THREAD

**Issue by serggermob** [ilyhalight/voice-over-translation#510]
### Operating system / Операционная система

window 7

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.4.1-beta

### Describe the bug / Опишите ошибку

Останавливается звук при переключении на другую вкладку.
Не работает переключение видео в отдельное окно, поверх остальных. «Картинка в картинке»

### Additional information / Дополнительная информация

Попробовал вкл.выкл флаг - Calculate window occlusion on Windows безрезультатно

**Comment by SashaXser** [comment]
На бете 1.5.1 такая же проблема?

**Comment by serggermob** [comment]
Работает, спасибо большое! В отдельном окне тоже открывается, но только при помощи дополнительного расширения. Спасибо за программу!
