### ISSUE TITLE
Формат субтитров?

### ISSUE THREAD

**Issue by Buumcode** [ilyhalight/voice-over-translation#514]
### Describe your feature / Опишите ваше предложение

Кто-нибудь понимает, что за субтитры такие скачивает это расширение? Ни один плейер их не принимает.

Вот что скачивается:
{"containsTokens": false, "subtitles": [{"text": "Лукас, как давно вы не приходили.", "startMs": 3190.0, "durationMs": 2740.0, "speakerId": "0"}, {"text": "да, по правде говоря, да, доктор, я был.", "startMs": 6230.0, "durationMs": 2130.0, "speakerId": "1"}, {"text": "по правде говоря, чтобы сказать вам правду, я был в отпуске со своей женой.", "startMs": 8360.0, "durationMs": 4350.0, "speakerId": "1"}]}

А вот как выглядят реальные субтитры формата ASS:
[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:18.72,0:00:21.35,Default,,0,0,0,,очень негативно регулируемый побочный эффект,
Dialogue: 0,0:00:21.35,0:00:23.10,Default,,0,0,0,,а не то, что ваше тело
Dialogue: 0,0:00:23.10,0:00:26.22,Default,,0,0,0,,ищет как  прямая цель, хм,
Dialogue: 0,0:00:26.22,0:00:28.43,Default,,0,0,0,,реакция на это видео была в основном
Dialogue: 0,0:00:28.43,0:00:30.08,Default,,0,0,0,,положительной, но было несколько человек,
Dialogue: 0,0:00:30.08,0:00:32.88,Default,,0,0,0,,которые, казалось, были расстроены, думая, что я
Dialogue: 0,0:00:32.88,0:00:35.82,Default,,0,0,0,,подразумеваю, что если чья-то цель

То есть по идее те скачиваемые субтитры ещё и надо конвертировать? Или что?

**Comment by kscaner** [comment]
Скрипт не хочет конвертировать json в srt - ругается на строчку 9.
Не смог ничего работающего найти, кроме одной платной программы.
Нельзя ли добавить конвертер в VOT, чтобы сразу в srt субтитры можно было скачать?

**Comment by Buumcode** [comment]
> Скрипт не хочет конвертировать json в srt - ругается на строчку 9.

Странно. У меня скрипт прекрасно работает и всё конвертируется. А что за "строчка 9"?

**Comment by kscaner** [comment]
> > Скрипт не хочет конвертировать json в srt - ругается на строчку 9.
> 
> Странно. У меня скрипт прекрасно работает и всё конвертируется. А что за "строчка 9"?

Ну а у меня нет. И как его можно запускать в Windows, где не установлен python?

Вот строчка 9
`        srt_content += f"{index}\n"`

**Comment by Buumcode** [comment]
> И как его можно запускать в Windows, где не установлен python?

Конечно же, для работы скрипта нужно установить Python. Например, для своей Windows 7 я устанавливал [v3.8.10](https://www.python.org/downloads/release/python-3810/). Далее скачал скрипт, запускаю его – всё прекрасно работает.

**Comment by kscaner** [comment]
> Конечно же, для работы скрипта нужно установить Python. Например, для своей Windows 7 я устанавливал [v3.8.10](https://www.python.org/downloads/release/python-3810/). Далее скачал скрипт, запускаю его – всё прекрасно работает.

Я запускал на Server 2008R2 где был установлен Python 3.5 - и там получал выше указанную ошибку.

**Comment by SashaXser** [comment]
> > Конечно же, для работы скрипта нужно установить Python. Например, для своей Windows 7 я устанавливал [v3.8.10](https://www.python.org/downloads/release/python-3810/). Далее скачал скрипт, запускаю его – всё прекрасно работает.
> 
> Я запускал на Server 2008R2 где был установлен Python 3.5 - и там получал выше указанную ошибку.

Попробуй через [программу](https://github.com/SashaXser/json-to-srt/)

**Comment by kscaner** [comment]
> > > Конечно же, для работы скрипта нужно установить Python. Например, для своей Windows 7 я устанавливал [v3.8.10](https://www.python.org/downloads/release/python-3810/). Далее скачал скрипт, запускаю его – всё прекрасно работает.
> > 
> > 
> > Я запускал на Server 2008R2 где был установлен Python 3.5 - и там получал выше указанную ошибку.
> 
> Попробуй через [программу](https://github.com/SashaXser/json-to-srt/)

Попробовал оба варианта на всякий пожарный на Windows 11 x64 в командной строке получаю ошибку

**Comment by SashaXser** [comment]
> `start_ms`

У тебя точно всё хорошо с файлом? Отправь файл который ты кидал в программу

**Comment by kscaner** [comment]
Вот этот файл, только выцепил из VOT через MS Edge.

[db7a6f62-9412-473d-aa1c-5c1da928b212.json](https://github.com/ilyhalight/voice-over-translation/files/15455920/db7a6f62-9412-473d-aa1c-5c1da928b212.json)

**Comment by SashaXser** [comment]
> Вот этот файл, только выцепил из VOT через MS Edge.
> 
> [db7a6f62-9412-473d-aa1c-5c1da928b212.json](https://github.com/ilyhalight/voice-over-translation/files/15455920/db7a6f62-9412-473d-aa1c-5c1da928b212.json)

Теперь должно работать, перекачай релиз

**Comment by kscaner** [comment]
> > Вот этот файл, только выцепил из VOT через MS Edge.
> > [db7a6f62-9412-473d-aa1c-5c1da928b212.json](https://github.com/ilyhalight/voice-over-translation/files/15455920/db7a6f62-9412-473d-aa1c-5c1da928b212.json)
> 
> Теперь должно работать, перекачай релиз

Супер, работает. Большое спасибо!
