### ISSUE TITLE
Перевод drive.google.com

### ISSUE THREAD

**Issue by selincodes** [ilyhalight/voice-over-translation#515]
### Describe your feature / Опишите ваше предложение

Возможно ли сделать перевод видео в гугл диске? Там плеер как на ютубе.

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Возможно ли сделать перевод видео в гугл диске? Там плеер как на ютубе.

Уже пробывал, нечего не получилось. Заливай на Яндекс Диск или другие сайты.

**Comment by ilyhalight** [comment]
Добавил в [1.5.1-beta4](https://github.com/ilyhalight/voice-over-translation/releases). Поддерживаются только публичные ссылки, например: `https://drive.google.com/file/d/FILE_ID`
