### ISSUE TITLE
Добавить main.noodlemagazine.com

### ISSUE THREAD

**Issue by 7edrose** [ilyhalight/voice-over-translation#516]
Есть возможность добавить https://main.noodlemagazine.com/ ?

**Comment by ilyhalight** [comment]
Поддержка и раньше была из-за того что там используется плеер Vimeo, но из-за отсутствия поддержки перевода корп. видео (параметр app_id не учитывался) всегда возвращалась ошибка. Теперь, работает как надо, но нужно отключить CSP для `player.vimeo.com` из-за особенностей плеера.

Исправлено в [1.5.1-beta4](https://github.com/ilyhalight/voice-over-translation/releases). Не забудьте про CSP.
