### ISSUE TITLE
Перевод с twitch

### ISSUE THREAD

**Issue by MastaDan9** [ilyhalight/voice-over-translation#519]
### Operating system / Операционная система

Не указано

### Browser / Браузер

Не указано

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Здравствуйте. У меня не появляется кнопка перевода когда смотрю трансляции или видео на твитч. Проверил с ютубом, кнопка есть.

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Здравствуйте. У меня не появляется кнопка перевода когда смотрю трансляции или видео на твитч. Проверил с ютубом, кнопка есть.

Зайди на страницу видео/клипа и обнови странцу, кнопка должна появится

**Comment by MastaDan9** [comment]
> > ### Describe your feature / Опишите ваше предложение
> > Здравствуйте. У меня не появляется кнопка перевода когда смотрю трансляции или видео на твитч. Проверил с ютубом, кнопка есть.
> 
> Зайди на страницу видео/клипа и обнови странцу, кнопка должна появится

Пробовал несколько раз, ставил на разные браузеры, кнопки так и не появилось

**Comment by MastaDan9** [comment]
![image](https://github.com/ilyhalight/voice-over-translation/assets/7467926/a46b25a7-50ee-4b1d-8436-a02e7ea7e7a4)

**Comment by SashaXser** [comment]
> ![image](https://private-user-images.githubusercontent.com/7467926/304393184-a46b25a7-50ee-4b1d-8436-a02e7ea7e7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjQzNDMsIm5iZiI6MTcwNzgyNDA0MywicGF0aCI6Ii83NDY3OTI2LzMwNDM5MzE4NC1hNDZiMjVhNy01MGVlLTRiMWQtODQzNi1hMDJlN2VhN2U3YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTEzNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0NDlhZjM1OTdhNjFmMGQwMmU3MzEwNWVjOGYyYzQ5ZmQ2MGYwMmE0NDA2YmUxOTE1MGUyOTBlNzBlOGY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sk7DZ5-rBrvcZyFPVi0rLh9yHv_8RXHjybq5EAY9Lec)

У вас какая версия? Почему вы указали это как предложение функции а не проблема?

**Comment by MastaDan9** [comment]
> > ![image](https://private-user-images.githubusercontent.com/7467926/304393184-a46b25a7-50ee-4b1d-8436-a02e7ea7e7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjQzNDMsIm5iZiI6MTcwNzgyNDA0MywicGF0aCI6Ii83NDY3OTI2LzMwNDM5MzE4NC1hNDZiMjVhNy01MGVlLTRiMWQtODQzNi1hMDJlN2VhN2U3YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTEzNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0NDlhZjM1OTdhNjFmMGQwMmU3MzEwNWVjOGYyYzQ5ZmQ2MGYwMmE0NDA2YmUxOTE1MGUyOTBlNzBlOGY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sk7DZ5-rBrvcZyFPVi0rLh9yHv_8RXHjybq5EAY9Lec)
> 
> У вас какая версия? Почему вы указали это как предложение функции а не проблема?

Простите, выбрал не тот раздел. 
Версия 1.5.0.5
Попробовал на втором ПК, появилась кнопка перевода на видео твича, но 5ч видео не смог перевести, выдал ошибку "Слишком длинное видео", прямые трансляции не переводит?
На первом ПК как будто блокируются скрипты, хм

**Comment by SashaXser** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/7467926/304393184-a46b25a7-50ee-4b1d-8436-a02e7ea7e7a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjQzNDMsIm5iZiI6MTcwNzgyNDA0MywicGF0aCI6Ii83NDY3OTI2LzMwNDM5MzE4NC1hNDZiMjVhNy01MGVlLTRiMWQtODQzNi1hMDJlN2VhN2U3YTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMTEzNDAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDk0NDlhZjM1OTdhNjFmMGQwMmU3MzEwNWVjOGYyYzQ5ZmQ2MGYwMmE0NDA2YmUxOTE1MGUyOTBlNzBlOGY3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Sk7DZ5-rBrvcZyFPVi0rLh9yHv_8RXHjybq5EAY9Lec)
> > 
> > 
> > У вас какая версия? Почему вы указали это как предложение функции а не проблема?
> 
> Простите, выбрал не тот раздел. Версия 1.5.0.5 Попробовал на втором ПК, появилась кнопка перевода на видео твича, но 5ч видео не смог перевести, выдал ошибку "Слишком длинное видео", прямые трансляции не переводит? На первом ПК как будто блокируются скрипты, хм

Попробуйте скачать [1.5.1-beta4](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.1-beta4)
