### ISSUE TITLE
VOT версии 1.0.9.2 (вероятно и 1.0.9 и 1.0.9.1) совсем перестал работать в AdGuard

### ISSUE THREAD

**Issue by Baltazar500** [ilyhalight/voice-over-translation#52]
Собственно сабж.

VOT версии 1.0.9.2 (вероятно и 1.0.9 и 1.0.9.1) перестал работать в AdGuard от слова совсем. Плашка при воспроизведении ютуб - роликов теперь вообще не кажется. Хотел попробовать переделать скрипт ревизии 1.0.9.2 по лекалам @mynovelhost https://github.com/ilyhalight/voice-over-translation/issues/27#issuecomment-1295853780 под cloudflare worker, но обнаружил, что тот даже плашку теперь не кажет. Сломалась ли она в 1.0.9 или 1.0.9.1 я не проверял.

**Comment by ilyhalight** [comment]
В не выпущенной версии уже исправлено. В 1.0.9.2 и версиях ниже не было асинхронной обертки.

Как-то так должно выглядеть (весь код нужно обернуть в само выполняющуюся async function:
![изображение](https://user-images.githubusercontent.com/62353659/202741796-52573aed-9a5a-4db4-b66a-2bd441dca666.png)
