### ISSUE TITLE
Отключается звук оригинала на Youtube

### ISSUE THREAD

**Issue by d2m22** [ilyhalight/voice-over-translation#521]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Отключается звук оригинала видео, значок громкости перечеркнут. В настройках установлено "Уменьшить громкость видео до" = 0.15%.

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 11
> ### Browser / Браузер
> 
> Firefox
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> Отключается звук оригинала видео, значок громкости перечеркнут. В настройках установлено "Уменьшить громкость видео до" = 0.15%.
> ### Additional information / Дополнительная информация
> 
> _No response_

Попробуйте скачать [1.5.1-beta4](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.1-beta4)

**Comment by d2m22** [comment]
> Попробуйте скачать [1.5.1-beta4](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.1-beta4)
В версии 1.5.1-beta4 проблем с отключением оригинала звука не замечено.
