### ISSUE TITLE
Перевод с newgrounds.com

### ISSUE THREAD

**Issue by MjKey** [ilyhalight/voice-over-translation#522]
### Describe your feature / Опишите ваше предложение

Ссылки в видео выглядят так:
https://www.newgrounds.com/portal/view/{ID}
Сам плеер: #ng-global-video-player

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Ссылки в видео выглядят так: [https://www.newgrounds.com/portal/view/{ID}](https://www.newgrounds.com/portal/view/%7BID%7D) Сам плеер: #ng-global-video-player

[Реализовал](https://github.com/SashaXser/voice-over-translation/tree/dev/dist), пожалуйста, не присылайте кривые селекторы, так как они не будут работать, если плеер находится в полноэкранном режиме.

**Comment by ilyhalight** [comment]
Добавлено в 1.5.1-beta5
