### ISSUE TITLE
[VOT] Failed get yandex subtitles

### ISSUE THREAD

**Issue by SergeyLuashkov** [ilyhalight/voice-over-translation#527]
### Operating system / Операционная система

Linux

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Сообщение на кнопке:
`Не удалось запросить перевод видео`
Сообщение в консоли: 
`[VOT] Failed get yandex subtitles`
Я пробовал загружать видео и со встроенными субтитрами mkv и mp4, и в одной папке что бы srt лежали, что я делаю не так?
Или проблема не в субтитрах?

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Linux
> ### Browser / Браузер
> 
> Firefox
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> Сообщение на кнопке: `Не удалось запросить перевод видео` Сообщение в консоли: `[VOT] Failed get yandex subtitles` Я пробовал загружать видео и со встроенными субтитрами mkv и mp4, и в одной папке что бы srt лежали, что я делаю не так? Или проблема не в субтитрах?
> ### Additional information / Дополнительная информация
> 
> _No response_

Ничего не понял, опишите подробнее пожалуйста

**Comment by SergeyLuashkov** [comment]
В Yandex Disk на firefox на linux не работает вообщем, хотя все настройки сделал, как в wiki, в chromium все работало

**Comment by SashaXser** [comment]
> В Yandex Disk на firefox на linux не работает вообщем, хотя все настройки сделал, как в wiki, в chromium все работало

Возможно это CORS, можете скинуть логи консоли?

**Comment by SergeyLuashkov** [comment]
`
Content-Security-Policy: Игнорирую «'unsafe-inline'» внутри script-src: указан nonce-source или hash-source n4qXsUiKQWkvJA
InstallTrigger is deprecated and will be removed in the future. constants.js:50:15
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:1019:347
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66
injected: keepAlive: got message 
Object { messageId: "lsqragcx.03", ack: true, method: "keepAlive" }
content.js:8:1240
Ignoring unsupported entryTypes: element. public.ru.958a3df8727f84718309.js:93:126796
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. player.js:2:139943
InstallTrigger is deprecated and will be removed in the future. constants.js:50:15
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66
injected: keepAlive: got message 
Object { messageId: "lsqm2gvh.45", ack: true, method: "keepAlive" }
content.js:8:1240
Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:673:347
Loading failed for the <script> with source “https://yastatic.net/yandex-video-player-iframe-api-bundles/hlsjs/0.12.2-1761-1846-1976_tmp-2080-2095-2146-2171-2-2172-2232_tmp-2427-2498/hls.min.js”. n4qXsUiKQWkvJA:1:1
Ignoring unsupported entryTypes: layout-shift. player.v2.modern.js:2:636956
Ignoring unsupported entryTypes: layout-shift. public.ru.958a3df8727f84718309.js:93:121759
[db] data from db:  
Object { autoTranslate: 0, dontTranslateLanguage: "ru", dontTranslateYourLang: 1, autoSetVolumeYandexStyle: 1, autoVolume: 0, showVideoSlider: 1, syncVolume: 0, subtitlesMaxLength: 300, highlightWords: 0, responseLanguage: "ru", … }
[VOT]-Voice-Over-Translation.user.js:4252:13
[VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto().
    getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661
[VOT]-Voice-Over-Translation.user.js:2822:13
[VOT] Failed get yandex subtitles [VOT]-Voice-Over-Translation.user.js:3025:21
[VOT] Subtitles response:  
Object { subtitles: [] }
[VOT]-Voice-Over-Translation.user.js:3032:19
[VOT] subtitles list 
Array []
[VOT]-Voice-Over-Translation.user.js:3106:11
[VOT] Set translation from auto to ru [VOT]-Voice-Over-Translation.user.js:5384:13
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. player.v2.modern.js:2:654019
[VOT] Video Data:  
Object { translationHelp: null, isStream: false, duration: 343, videoId: "n4qXsUiKQWkvJA", detectedLanguage: "auto", responseLanguage: "ru" }
[VOT]-Voice-Over-Translation.user.js:5627:13
[VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto().
    getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661
[VOT]-Voice-Over-Translation.user.js:2709:13
[VOT] Не удалось запросить перевод видео [VOT]-Voice-Over-Translation.user.js:5863:19
    translateFunc moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:5863
    translateVideo moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:4049
    requestVideoTranslation moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2711
injected: keepAlive: got message 
Object { messageId: "lsqi5xro.6hi", ack: true, method: "keepAlive" }
content.js:8:1240
injected: keepAlive: got message 
Object { messageId: "lsqjikmu.zbc", ack: true, method: "keepAlive" }
content.js:8:1240

`

**Comment by SashaXser** [comment]
> Content-Security-Policy: Игнорирую «'unsafe-inline'» внутри script-src: указан nonce-source или hash-source n4qXsUiKQWkvJA InstallTrigger is deprecated and will be removed in the future. constants.js:50:15 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:1019:347 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66 injected: keepAlive: got message Object { messageId: "lsqragcx.03", ack: true, method: "keepAlive" } content.js:8:1240 Ignoring unsupported entryTypes: element. public.ru.958a3df8727f84718309.js:93:126796 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “”. player.js:2:139943 InstallTrigger is deprecated and will be removed in the future. constants.js:50:15 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66 injected: keepAlive: got message Object { messageId: "lsqm2gvh.45", ack: true, method: "keepAlive" } content.js:8:1240 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:673:347 Loading failed for the <script> with source “[https://yastatic.net/yandex-video-player-iframe-api-bundles/hlsjs/0.12.2-1761-1846-1976_tmp-2080-2095-2146-2171-2-2172-2232_tmp-2427-2498/hls.min.js”](https://yastatic.net/yandex-video-player-iframe-api-bundles/hlsjs/0.12.2-1761-1846-1976_tmp-2080-2095-2146-2171-2-2172-2232_tmp-2427-2498/hls.min.js%E2%80%9D). n4qXsUiKQWkvJA:1:1 Ignoring unsupported entryTypes: layout-shift. player.v2.modern.js:2:636956 Ignoring unsupported entryTypes: layout-shift. public.ru.958a3df8727f84718309.js:93:121759 [db] data from db: Object { autoTranslate: 0, dontTranslateLanguage: "ru", dontTranslateYourLang: 1, autoSetVolumeYandexStyle: 1, autoVolume: 0, showVideoSlider: 1, syncVolume: 0, subtitlesMaxLength: 300, highlightWords: 0, responseLanguage: "ru", … } [VOT]-Voice-Over-Translation.user.js:4252:13 [VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto(). getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661 [VOT]-Voice-Over-Translation.user.js:2822:13 [VOT] Failed get yandex subtitles [VOT]-Voice-Over-Translation.user.js:3025:21 [VOT] Subtitles response: Object { subtitles: [] } [VOT]-Voice-Over-Translation.user.js:3032:19 [VOT] subtitles list Array [] [VOT]-Voice-Over-Translation.user.js:3106:11 [VOT] Set translation from auto to ru [VOT]-Voice-Over-Translation.user.js:5384:13 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. player.v2.modern.js:2:654019 [VOT] Video Data: Object { translationHelp: null, isStream: false, duration: 343, videoId: "n4qXsUiKQWkvJA", detectedLanguage: "auto", responseLanguage: "ru" } [VOT]-Voice-Over-Translation.user.js:5627:13 [VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto(). getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661 [VOT]-Voice-Over-Translation.user.js:2709:13 [VOT] Не удалось запросить перевод видео [VOT]-Voice-Over-Translation.user.js:5863:19 translateFunc moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:5863 translateVideo moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:4049 requestVideoTranslation moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2711 injected: keepAlive: got message Object { messageId: "lsqi5xro.6hi", ack: true, method: "keepAlive" } content.js:8:1240 injected: keepAlive: got message Object { messageId: "lsqjikmu.zbc", ack: true, method: "keepAlive" } content.js:8:1240



> Content-Security-Policy: Игнорирую «'unsafe-inline'» внутри script-src: указан nonce-source или hash-source n4qXsUiKQWkvJA InstallTrigger is deprecated and will be removed in the future. constants.js:50:15 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:1019:347 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66 injected: keepAlive: got message Object { messageId: "lsqragcx.03", ack: true, method: "keepAlive" } content.js:8:1240 Ignoring unsupported entryTypes: element. public.ru.958a3df8727f84718309.js:93:126796 This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “”. player.js:2:139943 InstallTrigger is deprecated and will be removed in the future. constants.js:50:15 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content.js:60:457 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). 2 content-script.js:40:66 injected: keepAlive: got message Object { messageId: "lsqm2gvh.45", ack: true, method: "keepAlive" } content.js:8:1240 Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса inline («script-src»). sandbox eval code:673:347 Loading failed for the <script> with source “[https://yastatic.net/yandex-video-player-iframe-api-bundles/hlsjs/0.12.2-1761-1846-1976_tmp-2080-2095-2146-2171-2-2172-2232_tmp-2427-2498/hls.min.js”](https://yastatic.net/yandex-video-player-iframe-api-bundles/hlsjs/0.12.2-1761-1846-1976_tmp-2080-2095-2146-2171-2-2172-2232_tmp-2427-2498/hls.min.js%E2%80%9D). n4qXsUiKQWkvJA:1:1 Ignoring unsupported entryTypes: layout-shift. player.v2.modern.js:2:636956 Ignoring unsupported entryTypes: layout-shift. public.ru.958a3df8727f84718309.js:93:121759 [db] data from db: Object { autoTranslate: 0, dontTranslateLanguage: "ru", dontTranslateYourLang: 1, autoSetVolumeYandexStyle: 1, autoVolume: 0, showVideoSlider: 1, syncVolume: 0, subtitlesMaxLength: 300, highlightWords: 0, responseLanguage: "ru", … } [VOT]-Voice-Over-Translation.user.js:4252:13 [VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto(). getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661 [VOT]-Voice-Over-Translation.user.js:2822:13 [VOT] Failed get yandex subtitles [VOT]-Voice-Over-Translation.user.js:3025:21 [VOT] Subtitles response: Object { subtitles: [] } [VOT]-Voice-Over-Translation.user.js:3032:19 [VOT] subtitles list Array [] [VOT]-Voice-Over-Translation.user.js:3106:11 [VOT] Set translation from auto to ru [VOT]-Voice-Over-Translation.user.js:5384:13 WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER. player.v2.modern.js:2:654019 [VOT] Video Data: Object { translationHelp: null, isStream: false, duration: 343, videoId: "n4qXsUiKQWkvJA", detectedLanguage: "auto", responseLanguage: "ru" } [VOT]-Voice-Over-Translation.user.js:5627:13 [VOT] Error: Accessing TypedArray data over Xrays is slow, and forbidden in order to encourage performant code. To copy TypedArrays across origin boundaries, consider using Components.utils.cloneInto(). getSignature moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2661 [VOT]-Voice-Over-Translation.user.js:2709:13 [VOT] Не удалось запросить перевод видео [VOT]-Voice-Over-Translation.user.js:5863:19 translateFunc moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:5863 translateVideo moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:4049 requestVideoTranslation moz-extension://e5302d99-a895-4757-8b5e-9aae35d18932/userscripts/[VOT]-Voice-Over-Translation.user.js?id=e0940099-d481-47c2-9f0a-9452c5b73cac:2711 injected: keepAlive: got message Object { messageId: "lsqi5xro.6hi", ack: true, method: "keepAlive" } content.js:8:1240 injected: keepAlive: got message Object { messageId: "lsqjikmu.zbc", ack: true, method: "keepAlive" } content.js:8:1240

Нашел решение, задай Добавить TM в политику безопасности CSP: Да в настройках TamperMonkey и обязательно нажми Сохранить.

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/142c5bfd-d890-4300-881e-7361739f733d)

**Comment by andreyplus** [comment]
Этого параметра нет в FireMonkey (https://addons.mozilla.org/en-US/firefox/addon/firemonkey/)
