### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by 1grek** [ilyhalight/voice-over-translation#529]
### Operating system / Операционная система

MacOS

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

4.4.5 (82)

### Describe the bug / Опишите ошибку

Запускаю видео, например на youtube, появляется стандартная плашка - "перевести видео", при нажатии на нее - меняется на "Не удалось запросить перевод видео"
Не работает именно с сафари на макос и юзерскриптс.
На гугл хром развернул - все четко работает. Но очень бы хотелось именно сафари подружить с этой фичей.
Хэлп.

**Comment by SashaXser** [comment]
#525
