### ISSUE TITLE
so many languages are locked

### ISSUE THREAD

**Issue by vanbavt08ct** [ilyhalight/voice-over-translation#530]
### Describe your feature / Опишите ваше предложение

![image](https://github.com/ilyhalight/voice-over-translation/assets/112487927/366a7fa0-6a1f-4a00-97b3-017ba4579242)
so many languages are locked how can i reinstall it, how much does it cost to buy it, please guide me to pay

**Comment by ilyhalight** [comment]
API limits

![Screenshot_2024-02-22-09-53-04-17_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/ilyhalight/voice-over-translation/assets/62353659/a2e58d53-3747-4128-926c-ff98a781fc9e)

**Comment by vanbavt08ct** [comment]
Dear friend
I have API of open chat ai, can I replace it? Can you guide me and I will pay your fee, Please help

**Comment by vanbavt08ct** [comment]
I am willing to buy Yandex API, please help, thank you

**Comment by rochocki7** [comment]
Hi There, I would love to translate English and Russian sermons into Polish. Is there any other browser than Yandex where it can be done.
Because it translates well into Russian from English and Russian into English.
Would be very appreciated and help many people spread The GOOD NEWS about GOD.

**Comment by ilyhalight** [comment]
> Is there any other browser than Yandex where it can be done.

unfortunately not, you can try through eleven labs, but it will be paid
