### ISSUE TITLE
Stops working with OrangeMonkey on Chrome

### ISSUE THREAD

**Issue by yuhrim** [ilyhalight/voice-over-translation#532]
### Operating system / Операционная система

Windows 10 LTSC

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

OrangeMonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Most likely a problem with my crooked hands. Give me a nudge on where to dig. I use CentBrowser (Chromium 102.0.5005.167). The script works until the first restart of the browser. Then the button does not appear. Only reinstallation helps.

**Comment by ilyhalight** [comment]
Perhaps this is a problem in orangemonkey itself, because after restarting, imported scripts stop working via require
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/97762349-ee00-4551-bc90-7a89341ea50d)

**Comment by yuhrim** [comment]
No, it's not about OrangeMonkey. Other scripts are working properly.

**Comment by ilyhalight** [comment]
Check in 1.6.0, if anything, rediscover it. It works for me in this version
