### ISSUE TITLE
❗ PLS give feature to switch woomans or mans voices by my will ❗

### ISSUE THREAD

**Issue by Polydick** [ilyhalight/voice-over-translation#533]
### Describe your feature / Опишите ваше предложение

Now it deafult if original voice mans thats tranlation in mans voice and if speaks woomen translation is woomans. Give to switch it.

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Now it deafult if original voice mans thats tranlation in mans voice and if speaks woomen translation is woomans. Give to switch it.

This is not provided, they are selected automatically by Yandex. If you want it to be implemented, write to Yandex feedback.

**Comment by Polydick** [comment]
> > ### Опишите вашу функцию / Опишите ваше предложение
> > Теперь это очень важно, если оригинальный голос mans, то есть перевод mans, а если говорит woomen, перевод - woomans. Дайте переключить его.
> 
> Это не предусмотрено, они подбираются автоматически Яндексом. Если хотите, чтобы она была реализована, напишите в Яндекс отзыв.

Возможно использовать другой сервис или преключить голос?

**Comment by SashaXser** [comment]
> > > ### Опишите вашу функцию / Опишите ваше предложение
> > > Теперь это очень важно, если оригинальный голос mans, то есть перевод mans, а если говорит woomen, перевод - woomans. Дайте переключить его.
> > 
> > 
> > Это не предусмотрено, они подбираются автоматически Яндексом. Если хотите, чтобы она была реализована, напишите в Яндекс отзыв.
> 
> Возможно использовать другой сервис или преключить голос?

Я же сказал что голос не переключается, они автоматически выбираются. Какой другой сервис?

**Comment by SashaXser** [comment]
> > > > > ### Опишите вашу функцию / Опишите ваше предложение
> > > > > Теперь это очень важно, если оригинальный голос mans, то есть перевод mans, а если говорит woomen, перевод - woomans. Дайте переключить его.
> > > > 
> > > > 
> > > > Это не предусмотрено, они подбираются автоматически Яндексом. Если хотите, чтобы она была реализована, напишите в Яндекс отзыв.
> > > 
> > > 
> > > Возможно использовать другой сервис или преключить голос?
> > 
> > 
> > Я же сказал что голос не переключается, они автоматически выбираются. Какой другой сервис?
> 
> предоставить варианты перевода от других сервисов озвучки

Какой например?

**Comment by Polydick** [comment]
> > > > > > ### Опишите вашу функцию / Опишите ваше предложение
> > > > > > Теперь это очень важно, если оригинальный голос mans, то есть перевод mans, а если говорит woomen, перевод - woomans. Дайте переключить его.
> > > > > 
> > > > > 
> > > > > Это не предусмотрено, они подбираются автоматически Яндексом. Если хотите, чтобы она была реализована, напишите в Яндекс отзыв.
> > > > 
> > > > 
> > > > Возможно использовать другой сервис или преключить голос?
> > > 
> > > 
> > > Я же сказал что голос не переключается, они автоматически выбираются. Какой другой сервис?
> > 
> > 
> > предоставить варианты перевода от других сервисов озвучки
> 
> Какой например?

я думают вы лучше знаете начиная с гугла

**Comment by FiLinX** [comment]
в традузир переводчике имеется выбор озвучки текста между Гугл и Бинг TTS движками
 https://github.com/FilipePS/Traduzir-paginas-web/

**Comment by Polydick** [comment]
> в традузир переводчике имеется выбор озвучки текста между Гугл и Бинг TTS движками сколько там голосов не ведаю, ни разу не запускал озвучку) https://github.com/FilipePS/Traduzir-paginas-web/

хуйня какаято

**Comment by ilyhalight** [comment]
> сколько там голосов не ведаю, ни разу не запускал озвучку)

вроде два, обычная говорилка из гугла и бинга без доп. голосов
