### ISSUE TITLE
Не працює закадровий переклад відео

### ISSUE THREAD

**Issue by Roman19801** [ilyhalight/voice-over-translation#534]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Не працює закадровий переклад відео.В чому проблема,в Tempermonkey чи в скріпті для перекладу?
![не удалось](https://github.com/ilyhalight/voice-over-translation/assets/161028267/e75dbd63-51ef-4d74-9ff4-a3c34b7f7645)

**Comment by Roman19801** [comment]
![скрін](https://github.com/ilyhalight/voice-over-translation/assets/161028267/602cbf65-0510-4050-858c-b192d71853f0)
Додаю скрін

**Comment by SashaXser** [comment]
#525

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> _No response_
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> Не працює закадровий переклад відео.В чому проблема,в Tempermonkey чи в скріпті для перекладу? ![не удалось](https://private-user-images.githubusercontent.com/161028267/307306501-e75dbd63-51ef-4d74-9ff4-a3c34b7f7645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg3MDYsIm5iZiI6MTcwODY4ODQwNiwicGF0aCI6Ii8xNjEwMjgyNjcvMzA3MzA2NTAxLWU3NWRiZDYzLTUxZWYtNGQ3NC05ZmY0LWEzYzM0YjdmNzY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxMTQwMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjkwNmJmZDgwMGVlYmJiMDM1MWU5MjhhNzM5MGE5MzhmNjU3NjRkZTRiMmYyM2Q2YWJlMTg1YmQ2ZDYwM2ZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yn6I_BMOFnUOzbAEpkU4OyFccGef2GIS0VrLkNH0hz4)
> ### Additional information / Дополнительная информация
> 
> _No response_

#525

**Comment by Roman19801** [comment]
Проблеми почалися після оновлення Хром.Допомогло скинути Хром до заводських.

**Comment by Roman19801** [comment]
Знову не працює(((

**Comment by ilyhalight** [comment]
Вы попробовали поставить cloudflare версию скрипта, а так же включить проксирование аудио в настройках скрипта, как вам посоветовали выше?

Пожалуйста не создавайте дубликаты активных веток, все сообщения видим и по возможности на них отвечаем

**Comment by Roman19801** [comment]
> Ви пробували поставити скрипт версії cloudflare, а також включити проксування аудіо в налаштуваннях скрипта, як ви посоветовали вище?
> 
> Будь ласка, не створюйте публікації активних веток, всі повідомлення видимі і за можливості на них відповід

Так пробував

**Comment by Roman19801** [comment]
![1111](https://github.com/ilyhalight/voice-over-translation/assets/161028267/5ed14667-3e5f-4329-b75c-1bb2f7e336f9)
начало появлятся это уведомление постоянно на значке Tempermonkey . Пробовал стваить Violentmonkey.
![violent](https://github.com/ilyhalight/voice-over-translation/assets/161028267/b7d89743-1e6b-4eec-9bc9-81bf106bf1a6)
Пробовал бета скрипт и предидущий.
Так же иногда не показівает что работает скрипт
![22222](https://github.com/ilyhalight/voice-over-translation/assets/161028267/4936bea1-f0fd-4ea3-82f8-ee1a4783bc48)

**Comment by Roman19801** [comment]
Интересно,но в Опере работает скрипт

**Comment by SashaXser** [comment]
> Интересно,но в Опере работает скрипт

У вас какая версия Хрома?

**Comment by Roman19801** [comment]
> > Интересно,но в Опере работает скрипт
> 
> У вас какая версия Хрома?

122.0.6261.70   64-разрядная

**Comment by Roman19801** [comment]
Заработало снова в Хроме.Видимо проблема в Яндексе все таки

**Comment by SashaXser** [comment]
> Заработало снова в Хроме.Видимо проблема в Яндексе все таки

Само собой починилось? Проблем с 122 версией не увидел.

**Comment by Roman19801** [comment]
> > Заработало снова в Хроме.Видимо проблема в Яндексе все таки
> 
> Само собой починилось? Проблем с 122 версией не увидел.
Да,просто начало работать.

**Comment by Firsto** [comment]
Сегодня опять перестало работать. "Не удалось запросить перевод видео"

**Comment by ilyhalight** [comment]
> Сегодня опять перестало работать. "Не удалось запросить перевод видео"

https://github.com/ilyhalight/voice-over-translation/discussions/526#discussioncomment-8581553
