### ISSUE TITLE
Make the slider in the video player dependent of not only the volume of the source

### ISSUE THREAD

**Issue by stfy14** [ilyhalight/voice-over-translation#535]
### Describe your feature / Опишите ваше предложение

Было бы круто сделать слайдер в видеоплеере зависимым не только от громкости исходного видео
Понижение громкости происходит только на громкость оригинала, громкость перевода остается неизменной.

Это так же происходит и при связанной громкости оригинала c переводом.

Для примерного понимания, что я имею ввиду, можете попробовать оригинальное расширение "YaTranslate" и в его настройках включить перевод видео и попробовать его. В нем использование слайдера уменьшает громкость оригинала с переводом, при этом сохраняется соотношение громкости оригинал/перевод

**Comment by ilyhalight** [comment]
В настройках есть опция для этого. Не помню работает ли она с слайдером встроенным в ютуб или нет, но через само меню точно работает

**Comment by ilyhalight** [comment]
Надо будет добавить, чтобы работало при включённой связке громкости

**Comment by ilyhalight** [comment]
Будет добавлено в 1.5.2
