### ISSUE TITLE
The audio format is not supported

### ISSUE THREAD

**Issue by KobMiles** [ilyhalight/voice-over-translation#536]
### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

![image](https://github.com/ilyhalight/voice-over-translation/assets/148866440/b3fa8bea-9c9d-413d-9bd5-fe125f9e0a0f)
Пишет это при попытке перевода видео. Использую браузер Brave, скачал и настроил cloudflare версию скрипта.

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> _No response_
> ### Browser / Браузер
> 
> Other / Другой
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> ![image](https://private-user-images.githubusercontent.com/148866440/307395268-b3fa8bea-9c9d-413d-9bd5-fe125f9e0a0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTI5MTksIm5iZiI6MTcwODcxMjYxOSwicGF0aCI6Ii8xNDg4NjY0NDAvMzA3Mzk1MjY4LWIzZmE4YmVhLTljOWQtNDEzZC05YmQ1LWZlMTI1ZjllMGEwZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxODIzMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjhhYjc3NjdlNzE2YzVkNGYzZjhhZWJhNzFlNjI2NTY4OGM4MjViYTc4ZDcxMmNhYTUxZmZkNDlmYmQyNTZjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EqTB5AHiY1cmSrRLOHEoQRzTqJxC92oPNUYPse6WRxc) Пишет это при попытке перевода видео. Использую браузер Brave, скачал и настроил cloudflare версию скрипта.
> ### Additional information / Дополнительная информация
> 
> _No response_

Какой сайт?

**Comment by KobMiles** [comment]
Активировал этот параметр в настройках и все заработало.
![image](https://github.com/ilyhalight/voice-over-translation/assets/148866440/4f46d694-c06b-4dbb-a91d-bc09b6699bce)

**Comment by SashaXser** [comment]
> Активировал этот параметр в настройках и все заработало. ![image](https://private-user-images.githubusercontent.com/148866440/307397028-4f46d694-c06b-4dbb-a91d-bc09b6699bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MTQyMjAsIm5iZiI6MTcwODcxMzkyMCwicGF0aCI6Ii8xNDg4NjY0NDAvMzA3Mzk3MDI4LTRmNDZkNjk0LWMwNmItNGRiYi1hOTFkLWJjMDliNjY5OWJjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QxODQ1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjZlYjhkY2EyYTk2NTVkODA3MGQ5MmM0MDc3MjQ0ZTZlMGE4MTQwMzkwMTIxMWFiZDlhNzVhZWVmYjYzNzEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Aaqo3Eeszia_DlHejKcHRKPJYsHG8imLGCMTsGc2-K4)

Рад что вы смогли решить проблему
