### ISSUE TITLE
Возможность показа субтиров, переведенных самим ютубом

### ISSUE THREAD

**Issue by cobra838** [ilyhalight/voice-over-translation#537]
### Describe your feature / Опишите ваше предложение

Возможность показа субтиров, переведенных самим ютубом.
Например, если в yt-dlp ввести такую команду
yt-dlp I7dJKf16rPo --list-subs
покажется
ru-en - это перевод на русский английских субтитров, добавленных самим автором видео
ru - перевод на русский английских субтитров, которые ютуб обозначает "Английский (создано автоматически)"
Хотелось бы видеть, чтобы ваш скрипт показывал субтитры из первого пункта: ru-en, потому что перевод в них зачастую лучше, чем у яндекса, который разобрал речь в ролике сам.
Не знаю, возможно ли такое реализовать (или все скачивается с серверов яндекса или я даже не знаю...), но если возможно, то было бы очень полезной фичей, потому что то, как ютуб выводит свои субтитры, просто... неудобно, реализация показа из этого скрипта гораздо лучше.

**Comment by ilyhalight** [comment]
Те субтитры что имеют переписку "(youtube)" разве не то что вы просите добавить?

**Comment by cobra838** [comment]
Да, но если не ошибаюсь, они только того языка, на котором само видео.
Допустим, вот есть такое-то английское видео, в котором автор добавил свои субтитры (то есть не созданные самим ютубом автоматически через их распозновалки, а самим автором канала), ну и в скрипте в субтитрах и отображается «Английский youtube». Но ютуб же ещё и переводит эти субтитры на другие языки (можно открыть в ютубе настройки - субтитры - выбрать оригинальный субтитр - перевести - выбрать русский). Заранее переводит, при загрузке видео автором, не в момент просмотра. Вот мне бы и хотелось бы, чтобы скрипт мог бы отображать такие переведенные самим ютубом субтитры. Пока что скрипт может отображать только русские субтитры, переведённые Яндексом, и распознавание речи у них, конечно, лучше, чем у ютуба, но текстовый результат будет не лучше, чем текст, который делал автор канала в своих субтитрах.

**Comment by ilyhalight** [comment]
Добавил
