### ISSUE TITLE
Не вдалося запросити переклад відео

### ISSUE THREAD

**Issue by Roman19801** [ilyhalight/voice-over-translation#538]
### Operating system / Операционная система

10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

	1.5.0.5

### Describe the bug / Опишите ошибку

Не вдалося запросити переклад відео   Перепробував всі версії скріпта

**Comment by ilyhalight** [comment]
Дубликат #534

Пожалуйста не создавайте дубликаты активных веток, все сообщения видим и по возможности на них отвечаем
