### ISSUE TITLE
disk.yandex.ru и yadi.sk

### ISSUE THREAD

**Issue by maxlan47** [ilyhalight/voice-over-translation#539]
### Describe your feature / Опишите ваше предложение

Друзья, 
https://disk.yandex.ru/i/Jb1vd*  - работает с CLI а
https://yadi.sk/i/Jb1vd* - нет

Первая ссылка из браузерной версии яндекс диска а вторая из приложения под linux.
Ошибка "URL: https://yadi.sk/i/Jb1vd* is unknown service"
думаю это не сложно исправить) Благодарю вас за ваши труды.

**Comment by ilyhalight** [comment]
По cli версии пишите недочёты в репозиторий с cli версией (FOSWLY/vot-cli). Будет исправлено

**Comment by ilyhalight** [comment]
Исправил в vot-cli 1.3.1
