### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by SkyHunter1** [ilyhalight/voice-over-translation#54]
Всем привет, с скриптом версии 1.0.9.3 в данном сетапе (windows - firefox 107.0 - violentmonkey) на всех видео, которые я пытался открыть, пишет "Не удалось запросить перевод видео"
К слову, скрипт версии 1.0.9.2 вообще не работал, ничего не появлялось просто

**Comment by ilyhalight** [comment]
#45
