### ISSUE TITLE
видео с любым языком - не удалось запросить перевод видео

### ISSUE THREAD

**Issue by KrevetkaOo** [ilyhalight/voice-over-translation#540]
### Operating system / Операционная система

Winows 11 23H2/22631.3227

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

видео с любым языком - не удалось запросить перевод видео
тест: [youtube](https://youtu.be/Zy7uXy5ojVM)

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Winows 11 23H2/22631.3227
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> видео с любым языком - не удалось запросить перевод видео тест: [youtube](https://youtu.be/Zy7uXy5ojVM)
> ### Additional information / Дополнительная информация
> 
> _No response_

Поменяйте в настройках расширения домен на один из доступных.

vot.deno.dev
vot-new.toil-dump.workers.dev

**Comment by AlexR0v** [comment]
где это менять нужно? @SashaXser можете, пожалуйста, более подробно описать?

**Comment by KrevetkaOo** [comment]
> где это менять нужно?

![image](https://github.com/ilyhalight/voice-over-translation/assets/15080586/e53bcb37-8334-4a69-bf8c-a36464ad9dfa)

**Comment by AlexR0v** [comment]
@KrevetkaOo спасибо! 
Может кому-то поможет - эти настройки находятся на самой кнопке перевода там где три точки.

**Comment by gluck-59** [comment]
Теперь осталось найти "саму кнопку перевода " :)

<img width="1154" alt="Снимок экрана 10 01 2025 в 15 25 51" src="https://github.com/user-attachments/assets/c3ac6be1-d209-4948-a212-8f4cc1f15f29" />
