### ISSUE TITLE
Перестал работать перевод

### ISSUE THREAD

**Issue by Aitix** [ilyhalight/voice-over-translation#541]
### Operating system / Операционная система

Windows 11 Домашняя Версия 23H2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

Edge Версия 122.0.2365.52. Ничего не менял, раньше работало, сейчас пишет "Не удалось запросить перевод для видео". Использую Cloudflare version. Читая другие проблемы попробовал поставить галочку "Проксировать полученное аудио" - не помогло :C

**Comment by SashaXser** [comment]
#540

**Comment by Aitix** [comment]
> #540

Cпасибо большое, сильно помог мне сегодня :)

**Comment by bashtan123** [comment]
Перестал работать "undefined" "не удалось запросить перевод"
После обновления Chrome Версия 122.0.6261.70 (Официальная сборка), (64 бит)
Использую Cloudflare version. Проксировать полученное аудио.

**Comment by binidom** [comment]
Тоже перестал работать, обновлений не каких не делал, уже два дня не работает

**Comment by Aitix** [comment]
Попробуйте решение выше, мне помогло.

**Comment by customstone** [comment]
> Попробуйте решение выше, мне помогло.

если там имеется ввиду заменить домены в меню расширения на самом видео, то не помогает. 
не работает уже три дня с ошибкой, обозначенной выше

**Comment by EugenyBY** [comment]
сегодня после обновы хрома перестал работать перевод. win11. хром Version 121.0.6167.189 (Official Build) (64-bit)

**Comment by tvRussianBear** [comment]
В Google Chrome Версия 122.0.6261.70 (Официальная сборка) перевод больше не пашет. Версия скрипта 1.5.0.5

**Comment by ilyhalight** [comment]
> сегодня после обновы хрома перестал работать перевод. win11. хром Version 121.0.6167.189 (Official Build) (64-bit)

Пишет не удалось запросить перевод или именно не появляется кнопка?

**Comment by ilyhalight** [comment]
> Пишет не удалось запросить перевод

Если пишет не удалось запросить перевод, то попробуйте в настройках расширения изменить адрес worker прокси-сервера на `vot.toil.cc` (без пробелов и лишних символов), а так же не забудьте галочку "Проксировать полученное аудио"
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/9dc2a989-707f-42a4-801d-7635e85d2bca)

**Comment by customstone** [comment]
> Если пишет не удалось запросить перевод, то попробуйте в настройках расширения изменить адрес worker прокси-сервера на `vot.toil.cc` (без пробелов и лишних символов), а так же не забудьте галочку "Проксировать полученное аудио" 
вроде заработало, спасибо

**Comment by tvRussianBear** [comment]
> > Если пишет «не удалось запросить перевод», то в расширении расширения необходимо изменить адрес рабочего прокси-сервера на `vot.toil.cc`(без пробелов и лишних символов), а также не забудьте галочку «Проксировать полученное аудио»
> 
> вроде заработало, спасибо

Это помогло спасибо

**Comment by Akex24** [comment]
> > Пишет не удалось запросить перевод
> 
> Если пишет не удалось запросить перевод, то попробуйте в настройках расширения изменить адрес worker прокси-сервера на `vot.toil.cc` (без пробелов и лишних символов), а так же не забудьте галочку "Проксировать полученное аудио" ![изображение](https://private-user-images.githubusercontent.com/62353659/308150507-9dc2a989-707f-42a4-801d-7635e85d2bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDk1MjYsIm5iZiI6MTcwOTA0OTIyNiwicGF0aCI6Ii82MjM1MzY1OS8zMDgxNTA1MDctOWRjMmE5ODktNzA3Zi00MmE0LTgwMWQtNzYzNWU4NWQyYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE1NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTIxMmE4NjNmNmE3ZTg1YjUyMjU2NDUxYzVlYjIzOTc1ZTZmMjU0YzZkNTI3YmQyYzljMjQzZDk1NDVkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1iNkVTKg7b1fyO6c41Kj107cKF9WNy-Kx-x0_IkdAI)

У меня нет worker. Браузер фаерфокс. Браузер обновлен до последней версии. Скрипты все обновлены. Но перевод не работает. 
![22222222222222222](https://github.com/ilyhalight/voice-over-translation/assets/161492838/0a24a87c-6811-4e1e-9efc-f1dddce2273a)

**Comment by SashaXser** [comment]
> > > Пишет не удалось запросить перевод
> > 
> > 
> > Если пишет не удалось запросить перевод, то попробуйте в настройках расширения изменить адрес worker прокси-сервера на `vot.toil.cc` (без пробелов и лишних символов), а так же не забудьте галочку "Проксировать полученное аудио" ![изображение](https://private-user-images.githubusercontent.com/62353659/308150507-9dc2a989-707f-42a4-801d-7635e85d2bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDk1MjYsIm5iZiI6MTcwOTA0OTIyNiwicGF0aCI6Ii82MjM1MzY1OS8zMDgxNTA1MDctOWRjMmE5ODktNzA3Zi00MmE0LTgwMWQtNzYzNWU4NWQyYmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDE1NTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZTIxMmE4NjNmNmE3ZTg1YjUyMjU2NDUxYzVlYjIzOTc1ZTZmMjU0YzZkNTI3YmQyYzljMjQzZDk1NDVkMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1iNkVTKg7b1fyO6c41Kj107cKF9WNy-Kx-x0_IkdAI)
> 
> У меня нет worker. Браузер фаерфокс. Браузер обновлен до последней версии. Скрипты все обновлены. Но перевод не работает. ![22222222222222222](https://private-user-images.githubusercontent.com/161492838/308245181-0a24a87c-6811-4e1e-9efc-f1dddce2273a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTA0NDUsIm5iZiI6MTcwOTA1MDE0NSwicGF0aCI6Ii8xNjE0OTI4MzgvMzA4MjQ1MTgxLTBhMjRhODdjLTY4MTEtNGUxZS05ZWZjLWYxZGRkY2UyMjczYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjRlNTUzNmEzNjE4MTdmZWE5MThjMmExMjc4MWZhYTY4YWI5NzkwMTZiNTViYWVjYzFmYjNkNjEzOGMwYmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Dr8OZNFZTVitBGXQX40UNMc7Xj1ggb0tMJf3LuylOg)

#525

**Comment by Firsto** [comment]
> > Пишет не удалось запросить перевод
> 
> Если пишет не удалось запросить перевод, то попробуйте в настройках расширения изменить адрес worker прокси-сервера на `vot.toil.cc` (без пробелов и лишних символов), а так же не забудьте галочку "Проксировать полученное аудио" 

Заработало, благодарствую!

**Comment by vocalir145** [comment]
Та же проблема, пробовал менять адрес прокси на
vot.toil.cc
vot.deno.dev
vot-worker.onrender.com
vot-new.toil-dump.workers.dev
И всё равно "Не удалось запросить перевод видео"

**Comment by SashaXser** [comment]
> Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"

Покажи логи консоли

**Comment by vocalir145** [comment]
> > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> 
> Покажи логи консоли
![2024-03](https://github.com/ilyhalight/voice-over-translation/assets/131145311/87ed78c5-f8a5-41ca-aa20-8c84ce517026)

**Comment by SashaXser** [comment]
> > > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> > 
> > 
> > Покажи логи консоли
> > ![2024-03](https://private-user-images.githubusercontent.com/131145311/309409451-87ed78c5-f8a5-41ca-aa20-8c84ce517026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzM4OTgsIm5iZiI6MTcwOTMzMzU5OCwicGF0aCI6Ii8xMzExNDUzMTEvMzA5NDA5NDUxLTg3ZWQ3OGM1LWY4YTUtNDFjYS1hYTIwLThjODRjZTUxNzAyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMjUzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmQyMGU0MTY1YjMxZTA4MWFmYzI2MTkxNTUxYTA3MzY1MmI5ZjM0ZDc4YWEyOTI1YjY3ZDdhYzZkNTY5ZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MDewzIsTdW73nD0iZyHHry9K0ZMlymfE6RZTT2ZaO08)

Ошибка CSP, отключи его.

Для работы необходимо изменить опцию "Добавить TM в политику безопасности CSP" на "Да" (Tampermonkey -> Настройки -> Режим конфигурации: "Опытный" -> Добавить TM в политику безопасности CSP: "Да")

Обязательно нажми сохранить.

**Comment by vocalir145** [comment]
> > > > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> > > 
> > > 
> > > Покажи логи консоли
> > > ![2024-03](https://private-user-images.githubusercontent.com/131145311/309409451-87ed78c5-f8a5-41ca-aa20-8c84ce517026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzM4OTgsIm5iZiI6MTcwOTMzMzU5OCwicGF0aCI6Ii8xMzExNDUzMTEvMzA5NDA5NDUxLTg3ZWQ3OGM1LWY4YTUtNDFjYS1hYTIwLThjODRjZTUxNzAyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMjUzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmQyMGU0MTY1YjMxZTA4MWFmYzI2MTkxNTUxYTA3MzY1MmI5ZjM0ZDc4YWEyOTI1YjY3ZDdhYzZkNTY5ZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MDewzIsTdW73nD0iZyHHry9K0ZMlymfE6RZTT2ZaO08)
> 
> Ошибка CSP, отключи его.
> 
> Для работы необходимо изменить опцию "Добавить TM в политику безопасности CSP" на "Да" (Tampermonkey -> Настройки -> Режим конфигурации: "Опытный" -> Добавить TM в политику безопасности CSP: "Да")
> 
> Обязательно нажми сохранить, если не помогло, попробуй выбрать "Удалить полностью".

Всё равно не работает
Отключаю CSP через расширение Disable Content-Security-Policy, которое советовали ранее, может с ним что-то не то?
![image](https://github.com/ilyhalight/voice-over-translation/assets/131145311/c4874f5c-b7d7-4556-9e38-03fe83350095)
![image](https://github.com/ilyhalight/voice-over-translation/assets/131145311/5a1968fb-fd72-4cf4-8cc8-d5b69970785d)

**Comment by SashaXser** [comment]
> > > > > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> > > > 
> > > > 
> > > > Покажи логи консоли
> > > > ![2024-03](https://private-user-images.githubusercontent.com/131145311/309409451-87ed78c5-f8a5-41ca-aa20-8c84ce517026.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzM4OTgsIm5iZiI6MTcwOTMzMzU5OCwicGF0aCI6Ii8xMzExNDUzMTEvMzA5NDA5NDUxLTg3ZWQ3OGM1LWY4YTUtNDFjYS1hYTIwLThjODRjZTUxNzAyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMjUzMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZmQyMGU0MTY1YjMxZTA4MWFmYzI2MTkxNTUxYTA3MzY1MmI5ZjM0ZDc4YWEyOTI1YjY3ZDdhYzZkNTY5ZTkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MDewzIsTdW73nD0iZyHHry9K0ZMlymfE6RZTT2ZaO08)
> > 
> > 
> > Ошибка CSP, отключи его.
> > Для работы необходимо изменить опцию "Добавить TM в политику безопасности CSP" на "Да" (Tampermonkey -> Настройки -> Режим конфигурации: "Опытный" -> Добавить TM в политику безопасности CSP: "Да")
> > Обязательно нажми сохранить, если не помогло, попробуй выбрать "Удалить полностью".
> 
> Всё равно не работает Отключаю CSP через расширение Disable Content-Security-Policy, которое советовали ранее, может с ним что-то не то? ![image](https://private-user-images.githubusercontent.com/131145311/309412933-c4874f5c-b7d7-4556-9e38-03fe83350095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzU4MjgsIm5iZiI6MTcwOTMzNTUyOCwicGF0aCI6Ii8xMzExNDUzMTEvMzA5NDEyOTMzLWM0ODc0ZjVjLWI3ZDctNDU1Ni05ZTM4LTAzZmU4MzM1MDA5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMzI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODk4MzQyNzY1OWVmOGE5YmJlOGZkMzAyNjJiMmEzMjE5YmUxZDVmYzIwNjdkZjM3OTUwNzM2NDRhMzVjNDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oQ5Hp_Z4-XyReibqwmlAtL-kFnk9Y0qDxCFFf-GB_JI) ![image](https://private-user-images.githubusercontent.com/131145311/309413201-5a1968fb-fd72-4cf4-8cc8-d5b69970785d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMzU4MjgsIm5iZiI6MTcwOTMzNTUyOCwicGF0aCI6Ii8xMzExNDUzMTEvMzA5NDEzMjAxLTVhMTk2OGZiLWZkNzItNGNmNC04Y2M4LWQ1YjY5OTcwNzg1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMVQyMzI1MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzI2OGUxZDZkNjgwMjM2MTk5ZDcwNTQxZGE1MmNkNjMzNTAyYjZiYzg2NGRhYTllMjMzNWM2NDY4OGM2MDIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V53bSoubLooyBfNhMQfaanj65Or5xlXs-R6GJi09HQ8)

Может быть не работает, в Twitter очень строгий CSP, обычно помогает только полное отключение CSP через Tampermonkey. В будущем, возможно не нужно будет отключать CSP.
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/1ed9ad79-4ef5-46f2-84ed-150513420814)

**Comment by 8311380** [comment]
> Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"

запускать нужно через VPN

**Comment by SashaXser** [comment]
> > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> 
> запускать нужно через VPN

Необязательно, для этого сделана Cloudflare версия с просирование аудио. Для тех кому нужно обойти блокировку Яндекса.

**Comment by vocalir145** [comment]
Пробовал полное удаление, не помогло
Желаю скорейшей разработки✊😼

**Comment by zuluss** [comment]
> > > Та же проблема, пробовал менять адрес прокси на vot.toil.cc vot.deno.dev vot-worker.onrender.com vot-new.toil-dump.workers.dev И всё равно "Не удалось запросить перевод видео"
> > 
> > 
> > запускать нужно через VPN
> 
> Необязательно, для этого сделана Cloudflare версия с проксированием аудио. Для тех кому нужно обойти блокировку Яндекса.

а где скачать Cloudflare версию?
