### ISSUE TITLE
the translation does not work on the bitchute website.

### ISSUE THREAD

**Issue by Ariy13** [ilyhalight/voice-over-translation#542]
### Operating system / Операционная система

windows 10 h2

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.0.1

### Describe the bug / Опишите ошибку

the translation does not work on the bitchute website. The "translate" button has disappeared. Azura Yandex browser and Mozilla are the latest versions. Before that, everything worked in both browsers a couple of weeks ago

**Comment by ilyhalight** [comment]
Исправлено в 1.5.1
