### ISSUE TITLE
[Youtube Embed] ID not found / ID не найден

### ISSUE THREAD

**Issue by ftoh** [ilyhalight/voice-over-translation#544]
### Operating system / Операционная система

Windows 10 21H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

На некоторых встроенных youtube-видео не определяется id, потому что они открываются через YouTube Iframe API.
Например, https://300.ya.ru/v_uixQyQEK?t=206

Пофиксить можно так
```js
const url = getPlayer().getVideoUrl()
new URL(url).searchParams.get('v')
```

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 10 21H2
> ### Browser / Браузер
> 
> Chrome
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.0.5
> ### Describe the bug / Опишите ошибку
> 
> На некоторых встроенных youtube-видео не определяется id, потому что они открываются через YouTube Iframe API. Например, https://300.ya.ru/v_uixQyQEK?t=206
> 
> Пофиксить можно так
> 
> ```js
> const url = getPlayer().getVideoUrl()
> new URL(url).searchParams.get('v')
> ```
> 
> ### Additional information / Дополнительная информация
> 
> _No response_

Сделай Pull Request с исправлением, так будет проще
