### ISSUE TITLE
Привязать окно перевода к нижнему инфобару

### ISSUE THREAD

**Issue by Alpak0n3** [ilyhalight/voice-over-translation#546]
Можно ли привязать окно "перевести видео" к нижнему инфобару, что-бы они появлялись и скрывались одновременно? Или уменьшить отображение до 1-й секунды вместо 3-х. Мне кажется так будет лучше.

**Comment by ilyhalight** [comment]
> уменьшить отображение  до 1-й секунды вместо 3-х

думаю так будет лучше

**Comment by ilyhalight** [comment]
в 1.5.1 уменьшил до секунды

**Comment by Alpak0n3** [comment]
> в 1.5.1 уменьшил до секунды

Да, так стало лучше.
