### ISSUE TITLE
Кнопка не кликабельна

### ISSUE THREAD

**Issue by Patraskon** [ilyhalight/voice-over-translation#55]
Firefox 107

Скрипт работает только в приватном режиме

https://user-images.githubusercontent.com/34421135/203061717-aa4f2d46-c47d-44a4-aea2-ea02a64ef56f.mp4

**Comment by ilyhalight** [comment]
А можешь скинуть, что в консоли пишет при клике? Тоже на файрфоксе сижу, но такой ошибки нету

**Comment by Patraskon** [comment]
При клике нечего. Но ошибок много 
[console-export-2022-11-21_18-11-33.txt](https://github.com/ilyhalight/voice-over-translation/files/10057687/console-export-2022-11-21_18-11-33.txt)

**Comment by ilyhalight** [comment]
Попробуй в консоли браузера прописать: `indexedDB.deleteDatabase('VOT');` и 1-2 раза перезагрузить страницу. Это должно помочь, ибо ругается на отсутствие ключа "settings" в IndexedDB расширения (Uncaught DOMException: IDBDatabase.transaction: 'settings' is not a known object store name voice-over-translation.user.js:525)

Если не помогло, скинь

**Comment by Patraskon** [comment]
Помогло. Мне каждый раз надо это делать или оно запоминается ?

**Comment by ilyhalight** [comment]
> Помогло. Мне каждый раз надо это делать или оно запоминается ?

Нужно сделать единожды. Скорее всего, при каком-то запуске расширения возникла ошибка и часть базы данных слетела. Из-за этого часть кода выдавала ошибку и клик не засчитывался.

**Comment by Patraskon** [comment]
Чёт она кликабельна через раз ток становится. 3 точки работают. Приходится авто перевод врубать чтоб по сто раз страницу не перезагружать
