### ISSUE TITLE
Перестала появляться кнопка, если отключено автовоспроизведение при помощи Enhancer for YouTube

### ISSUE THREAD

**Issue by PalmtopTiger** [ilyhalight/voice-over-translation#551]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.1

### Describe the bug / Опишите ошибку

Здравствуйте.
После обновления до версии 1.5.1 перестала появляться кнопка перевода, если в расширении [Enhancer for YouTube](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) включены опции:

- Предотвращать автовоспроизведение в фоновых вкладках
- Предотвращать автовоспроизведение в активной вкладке
- Не подгружать видео, если оно остановлено

Понимаю, что просьба несколько неуместная, но расширение довольно популярное и раньше всё работало.
С уважением.

### Additional information / Дополнительная информация

Браузер: Vivaldi

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 10 22H2
> ### Browser / Браузер
> 
> Other / Другой
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.1
> ### Describe the bug / Опишите ошибку
> 
> Здравствуйте. После обновления до версии 1.5.1 перестала появляться кнопка перевода, если в расширении [Enhancer for YouTube](https://chromewebstore.google.com/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle) включены опции:
> 
>     * Предотвращать автовоспроизведение в фоновых вкладках
> 
>     * Предотвращать автовоспроизведение в активной вкладке
> 
>     * Не подгружать видео, если оно остановлено
> 
> 
> Понимаю, что просьба несколько неуместная, но расширение довольно популярное и раньше всё работало. С уважением.
> ### Additional information / Дополнительная информация
> 
> Браузер: Vivaldi

Покажи логи консоли

**Comment by PalmtopTiger** [comment]
[Если не работает.txt](https://github.com/ilyhalight/voice-over-translation/files/14590491/default.txt)
[Если работает.txt](https://github.com/ilyhalight/voice-over-translation/files/14590492/default.txt)
Судя по логам, скрипт не отрабатывает, если не находит работающий плеер.
В голову пришла мысль и я её проверил: если быстро запустить видео кликом после обновления страницы, то кнопка появится. Видимо, скрипт проверят по таймауту наличие плеера и, если не нашёл, отключается.

**Comment by SashaXser** [comment]
Напоминает #387, но у меня лично не воспроизводится. 
Раньше исправлялось вот так, но это костыльно. 

```js

  // the "delayed video upload" fix for YouTube (#387)
  if (!(description && title)) {
    return "en";
  }

```

**Comment by PalmtopTiger** [comment]
В текущей версии этих строк нет. Если их добавить, начинает работать.

**Comment by SashaXser** [comment]
> В текущей версии этих строк нет. Если их добавить, начинает работать.
> 
> > Напоминает #387, но у меня лично не воспроизводится.
> 
> С работающим Enhancer for YouTube не воспроизводится? Попробуй мой конфиг. Не забудь свой сохранить, если пользуешься расширением. [enhancer_config.json](https://github.com/ilyhalight/voice-over-translation/files/14590954/enhancer_config.json)

Попробывал, ошибка не воспроизводится. Кнопка появляется.

**Comment by SashaXser** [comment]
@PalmtopTiger Попробуй скачать [скрипт](https://github.com/SashaXser/voice-over-translation/tree/test/dist), вроде исправил.

**Comment by PalmtopTiger** [comment]
Работает. Большое спасибо!
