### ISSUE TITLE
ЯндексДиск не переводит

### ISSUE THREAD

**Issue by andrei-zhdanov** [ilyhalight/voice-over-translation#554]
Здравствуйте. не переводит на яндекс диске. кнопка перевода появляется, но язык почему то определяется как русский. меняю руками на английский, нажимаю "перевести" и в итоге ошибка "Не удалось запросить перевод"

**Comment by andrei-zhdanov** [comment]
Здравствуйте. не переводит на яндекс диске. кнопка перевода появляется, но язык почему то определяется как русский. меняю руками на английский, нажимаю "перевести" и в итоге ошибка "Не удалось запросить перевод"

**Comment by SashaXser** [comment]
> Здравствуйте. не переводит на яндекс диске. кнопка перевода появляется, но язык почему то определяется как русский. меняю руками на английский, нажимаю "перевести" и в итоге ошибка "Не удалось запросить перевод"

#513

**Comment by andrei-zhdanov** [comment]
благодарю)
