### ISSUE TITLE
Перевод видео для https://cdn/

### ISSUE THREAD

**Issue by dtfyu3** [ilyhalight/voice-over-translation#557]
### Describe your feature / Опишите ваше предложение

Возможно ли сделать перевод видео, имеющего ссылку например
https://cdn.cs50.net/2023/fall/lectures/0/lecture0-b-1080p-hdr.mp4
Не является ли данный "плеер" стандартным для браузера, что значит поддержку не только лишь https://cdn/... ?

**Comment by ilyhalight** [comment]
Добавил, в целом это само напрашивалось.

> Не является ли данный "плеер" стандартным для браузера, что значит поддержку не только лишь https://cdn/... ?

Элемент `video` немного по другому работает, поэтому это будет работать, только, на прямых ссылках типа `*://*.*/*.mp4*`, а на сайтах кнопки не будет.
