### ISSUE TITLE
Баг. Не появляется кнопка с переводом на twitch

### ISSUE THREAD

**Issue by vts3rss** [ilyhalight/voice-over-translation#56]
Например для этого видео
https://www.twitch.tv/videos/1654334498

**Comment by ilyhalight** [comment]
Исправил. Убрал не нужную проверку на дополнительный класс видео контейнера. Обнови скрипт.

**Comment by vts3rss** [comment]
Работает! Спасибо!
Небольшой вопрос. Официальный Яндекс Браузер не переводит twitch и перевод на twitch возможен только через скрипт вроде Вашего?

**Comment by ilyhalight** [comment]
> Официальный Яндекс Браузер не переводит twitch и перевод на twitch возможен только через скрипт вроде Вашего?

Официально Яндекс Браузер переводит twitch и ещё некоторые сайты помимо ютуба. Только, как я понял не у всех пользователей есть доступ к этому функционалу (может быть, Яндекс открывают доступ к этому функционалу какими-то "пачками"... честно не знаю)
![изображение](https://user-images.githubusercontent.com/62353659/203540077-4dee5946-b655-42ad-9dbf-ae3ff1ede83f.png)

**Comment by vts3rss** [comment]
> > Официальный Яндекс Браузер не переводит twitch и перевод на twitch возможен только через скрипт вроде Вашего?
> 
> Официально Яндекс Браузер переводит twitch и ещё некоторые сайты помимо ютуба. Только, как я понял не у всех пользователей есть доступ к этому функционалу (может быть, Яндекс открывают доступ к этому функционалу какими-то "пачками"... честно не знаю) ![изображение](https://user-images.githubusercontent.com/62353659/203540077-4dee5946-b655-42ad-9dbf-ae3ff1ede83f.png)

Понял, еще раз спасибо

**Comment by vts3rss** [comment]
Обнаружил, что Яндекс Браузер переводит twitch, если открыть мобильную версию сайта. 
Например для такой ссылки будет перевод https://m.twitch.tv/videos/1654334498
А для такой нет https://www.twitch.tv/videos/1654334498
Хотя это одно и то же видео.
Может информация будет кому-нибудь полезна.
