### ISSUE TITLE
Проблема с показом субтитров в ok.ru

### ISSUE THREAD

**Issue by cobra838** [ilyhalight/voice-over-translation#561]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.1.1 (в хроме)
+
1.5.1.3 (в edge)

### Describe the bug / Опишите ошибку

Проблема с показом субтитров в одноклассниках
Пробовал с двумя браузерами, chrome и edge, проблема не уходит

### Additional information / Дополнительная информация

![image](https://github.com/ilyhalight/voice-over-translation/assets/73720906/e88e948d-fcba-4bea-a7a8-2f471bf7ee1b)

**Comment by ilyhalight** [comment]
Исправлено в 1.5.2
