### ISSUE TITLE
Возможность использовать субтитры, вместо прослушивания перевода

### ISSUE THREAD

**Issue by VladBladick** [ilyhalight/voice-over-translation#563]
### Describe your feature / Опишите ваше предложение

На многих сайтах недоступны субтитры, а есть возможность только прослушивать аудио перевод. Может зависит от плеера, но хотелось бы увидеть возможность включения субтитров, особенно на ресурсе bilibili.

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> На многих сайтах недоступны субтитры, а есть возможность только прослушивать аудио перевод. Может зависит от плеера, но хотелось бы увидеть возможность включения субтитров, особенно на ресурсе bilibili.

Отправьте это предложение в Яндекс, так как субтитры генерируются их системой и не зависят от скрипта.

**Comment by ilyhalight** [comment]
> > ### Describe your feature / Опишите ваше предложение
> > На многих сайтах недоступны субтитры, а есть возможность только прослушивать аудио перевод. Может зависит от плеера, но хотелось бы увидеть возможность включения субтитров, особенно на ресурсе bilibili.
> 
> Отправьте это предложение в Яндекс, так как субтитры генерируются их системой и не зависят от скрипта.

Вряд ли сделают, у них же есть встроенная нейронка и смысла делать тоже самое, но на сервере я думаю нет
