### ISSUE TITLE
Reddit support

### ISSUE THREAD

**Issue by ghost** [ilyhalight/voice-over-translation#564]
### Describe your feature / Опишите ваше предложение

Еще не увидел функции, которая предлагает перевод видео на Reddit. Было бы очень полезно
Также интересно - кому нужен перевод на XVideos?))

**Comment by ilyhalight** [comment]
> Еще не увидел функции, которая предлагает перевод видео на Reddit. Было бы очень полезно

Приведи пример ссылки на такое видео. Все видео какие я нашел используют плеер ютуба

**Comment by ekibastus** [comment]
> Приведи пример ссылки на такое видео. Все видео какие я нашел используют плеер ютуба
https://reddit.com/r/Unexpected/comments/1bkqj2u/rookie_ninja_warrior_rises_to_the_top/
https://reddit.com/r/Unexpected/comments/1bl8t8x/educational_in_more_ways_than_one/
https://reddit.com/r/interestingasfuck/comments/1bl0t6m/boycotts_are_for_the_poor/
https://reddit.com/r/Unexpected/comments/1bl3pnf/now_i_can_be_convinced/
https://reddit.com/r/JeffArcuri/comments/1bl31ph/the_sweatshirt/
etc.

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
