### ISSUE TITLE
Bash script

### ISSUE THREAD

**Issue by Acenotass** [ilyhalight/voice-over-translation#566]
### Describe your feature / Опишите ваше предложение

Накидал скриптик на bash для облегчения рутинных операций
Критика и фидбеки приветствуются
https://github.com/s-n-alexeyev/yvt/

**Comment by FiLinX** [comment]
крутяк!  давно пора было)
но вопросец - 
`Сохраняет ауиодорожки оригинала и переведенной дорожки.
Встраивает субтитры, по умолчанию на английском языке.`
- реально ли НЕ выполнять это?

**Comment by FiLinX** [comment]
ой, это какой то Bash    ыы..  я про это только слышал где-то от кого-то, но не прикасался ничем ни разу)
вот .bat и .ps1  пользую..  а тут даже и не в курсе куда и чего его как))

хотелось просто по подобию как с теми же .bat и .ps1  -  кликом по ним отрабатывало ютубный линк из буфера)
причём любой линк, и полный ватч и эмбед и юту.бе
единственно что уровень громкости оригинала нужно установить на 0.2-0.3

**Comment by s-n-alexeyev** [comment]
> ой, это какой то Bash ыы..

Bash это инструмент командной строки Linux


> хотелось просто по подобию как с теми же .bat и .ps1 - кликом по ним чтоб отрабатывало ютубный линк из 
буфера)

то что делает скрипт - использует команды и утилиты Linux, также обращается к аппаратной части, поэтому напрямую, в лоб перенести скрипт будет весьма непросто, к тому же я не знаком с powershell от Windows
вот есть несложный скрипт для Windows, который делает нечто подобное
https://github.com/FOSWLY/vot-cli/tree/main/scripts

>причём любой линк, и полный ватч и эмбед и юту.бе

не совсем понял что имелось в виду

> единственно что уровень громкости оригинала нужно установить на 0.2-0.3

по умолчанию громкость и так выставлена на 0.3

**Comment by Buumcode** [comment]
> > причём любой линк, и полный ватч и эмбед и юту.бе 
> не совсем понял что имелось в виду
Это он имеет ввиду, что на Ютубе ссылки бывают разных видов, и в скрипте должна быть предусмотрена их конвертация.
Например, три формата ссылки на одно и то же видео:
`https://www.youtube.com/shorts/y2dwyTBxRlo
https://www.youtube.com/watch?v=y2dwyTBxRlo
https://youtu.be/y2dwyTBxRlo`

**Comment by s-n-alexeyev** [comment]
> > причём любой линк, и полный ватч и эмбед и юту.бе
> 
> > > не совсем понял что имелось в виду
> 
> Это он имеет ввиду, что на Ютубе ссылки бывают разных видов, и в скрипте должна быть предусмотрена их конвертация. Например, три формата ссылки на одно и то же видео: https://www.youtube.com/shorts/y2dwyTBxRlo https://www.youtube.com/watch?v=y2dwyTBxRlo https://youtu.be/y2dwyTBxRlo

Все поддерживаемые линки можно посмотреть https://github.com/FOSWLY/vot-cli , на базе чего и строится скрипт .
