### ISSUE TITLE
download a video or audio track with translation

### ISSUE THREAD

**Issue by Ayuemin** [ilyhalight/voice-over-translation#569]
Доброго времени суток!!! Спасибо за Ваш труд! Очень нужно иметь возможность скачать переведённое видео или хотя бы аудиодорожку. Есть ли возможность это реализовать? Может какие-то временные файлы с переведённым видео можно извлекать или другой способ?

**Comment by Ayuemin** [comment]
> Доброго времени суток!!! Спасибо за Ваш труд! Очень нужно иметь возможность скачать переведённое видео или хотя бы аудиодорожку. Есть ли возможность это реализовать? Может какие-то временные файлы с переведённым видео можно извлекать или другой способ?

**Comment by ilyhalight** [comment]
Аудиодорожку можно скачать прямиком из меню
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/e0de6229-3244-47ed-b126-bee5cd9fabd1)

Для загрузки аудио+видео используйте [VOT-CLI](https://github.com/FOSWLY/vot-cli) + соответствующий скрипт для вашей ОС

**Comment by Ayuemin** [comment]
Спасибо, за ответ!
