### ISSUE TITLE
cli версия

### ISSUE THREAD

**Issue by Spp595** [ilyhalight/voice-over-translation#57]
Будет ли cli версия для скачивания перевода (аудио) через консоль в линукс?
Буду очень рад если такая функция появиться

**Comment by ilyhalight** [comment]
Правильно понял, что ты имеется ввиду сделать какую-нибудь доп. программку, которая например по команде "vot ссылка_на_видео" будет скачивать аудио перевода?

**Comment by Spp595** [comment]
Да, все верно.

**Comment by ilyhalight** [comment]
Попробую сделать

**Comment by ilyhalight** [comment]
Если всё получится, то здесь отпишу

**Comment by Spp595** [comment]
ок, спасибо

**Comment by ilyhalight** [comment]
https://github.com/ilyhalight/voice-over-translation/tree/master/vot-cli

**Comment by Spp595** [comment]
Большое спасибо)
Я хотел смотреть видео с переводом на телефоне но через браузер это неудобно.
Позже напишу скриптик который автоматом скачивает и перевод и видео и совмещает дорожки
