### ISSUE TITLE
Проблемы с CORS

### ISSUE THREAD

**Issue by CzarOfScripts** [ilyhalight/voice-over-translation#570]
### Operating system / Операционная система

Windows 11 23H2 (22631.3296)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.0.5

### Describe the bug / Опишите ошибку

После обновления браузера (до 123.0.6312.86), не работает перевод на том же ютубе.

### Additional information / Дополнительная информация

> Access to fetch at 'https://vot-worker.onrender.com/video-translation/translate' from origin 'https://www.youtube.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by sasholy** [comment]
> ### Operating system / Операционная система
> Windows 11 23H2 (22631.3296)
> 
> ### Browser / Браузер
> Chrome
> 
> ### Userscript manager / Скриптовый движок
> Tampermonkey
> 
> ### Script version / Версия скрипта
> 1.5.0.5
> 
> ### Describe the bug / Опишите ошибку
> После обновления браузера (до 123.0.6312.86), не работает перевод на том же ютубе.
> 
> ### Additional information / Дополнительная информация
> > Access to fetch at 'https://vot-worker.onrender.com/video-translation/translate' from origin 'https://www.youtube.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

настройки VOT - сбросил настройки и заработало.

**Comment by CzarOfScripts** [comment]
@sasholy, не сработало.

**Comment by SashaXser** [comment]
> @sasholy, не сработало.

Поменяй прокси сервер в настройках скрипта на [vot.toil.cc](https://vot.toil.cc/health)
