### ISSUE TITLE
Can't find variable: GM_addStyle

### ISSUE THREAD

**Issue by Kerber0ss** [ilyhalight/voice-over-translation#571]
### Operating system / Операционная система

Sonoma 14.4

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.5.1.3

### Describe the bug / Опишите ошибку

In Safari 17.4 get error Can't find variable: GM_addStyle and script not working (
Try cloudflare, cloudflare-min, user version, same errors.

![image](https://github.com/ilyhalight/voice-over-translation/assets/9537017/140213b9-fed9-4362-a5aa-a7427e4d9e74)

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Sonoma 14.4
> ### Browser / Браузер
> 
> Safari
> ### Userscript manager / Скриптовый движок
> 
> UserScripts
> ### Script version / Версия скрипта
> 
> 1.5.1.3
> ### Describe the bug / Опишите ошибку
> 
> In Safari 17.4 get error Can't find variable: GM_addStyle and script not working ( Try cloudflare, cloudflare-min, user version, same errors.
> 
> ![image](https://private-user-images.githubusercontent.com/9537017/317191858-140213b9-fed9-4362-a5aa-a7427e4d9e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDQ5OTUsIm5iZiI6MTcxMTU0NDY5NSwicGF0aCI6Ii85NTM3MDE3LzMxNzE5MTg1OC0xNDAyMTNiOS1mZWQ5LTQzNjItYTVhYS1hNzQyN2U0ZDllNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTMwNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNjZDc3NzE5ZjBiMDNkYWM2YzYxMTA0YTIxYzQ1MGViYjFkNWJjMzQ3ZDNmYmFhYzBmZmRiNjE0MmZkMWEyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N3YbuvneJnTEP9FhMzjoJ98-y9Q84j1zd6doDm-bMrQ)
> ### Additional information / Дополнительная информация
> 
> _No response_

Delete the following line: // @grant GM_addStyle

**Comment by Kerber0ss** [comment]
> > ### Operating system / Операционная система
> > Sonoma 14.4
> > ### Browser / Браузер
> > Safari
> > ### Userscript manager / Скриптовый движок
> > UserScripts
> > ### Script version / Версия скрипта
> > 1.5.1.3
> > ### Describe the bug / Опишите ошибку
> > In Safari 17.4 get error Can't find variable: GM_addStyle and script not working ( Try cloudflare, cloudflare-min, user version, same errors.
> > ![image](https://private-user-images.githubusercontent.com/9537017/317191858-140213b9-fed9-4362-a5aa-a7427e4d9e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDQ5OTUsIm5iZiI6MTcxMTU0NDY5NSwicGF0aCI6Ii85NTM3MDE3LzMxNzE5MTg1OC0xNDAyMTNiOS1mZWQ5LTQzNjItYTVhYS1hNzQyN2U0ZDllNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMTMwNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDNjZDc3NzE5ZjBiMDNkYWM2YzYxMTA0YTIxYzQ1MGViYjFkNWJjMzQ3ZDNmYmFhYzBmZmRiNjE0MmZkMWEyMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N3YbuvneJnTEP9FhMzjoJ98-y9Q84j1zd6doDm-bMrQ)
> > ### Additional information / Дополнительная информация
> > _No response_
> 
> Delete the following line: // @grant GM_addStyle

now working.
![image](https://github.com/ilyhalight/voice-over-translation/assets/9537017/18e4cd58-f1a4-4b2c-8742-3dc55a504272)

**Comment by ifRemix** [comment]
Operating system / Операционная система
Sonoma 14.4.1

Browser / Браузер
Safari   14.4.1

Userscript manager / Скриптовый движок
UserScripts

Script version / Версия скрипта
 1.5.1.3
vot-cloudflare.user.js

Describe the bug / Опишите ошибку
Просто пропала кнопка перевода.

<img width="1434" alt="SCR-20240330-oycd" src="https://github.com/ilyhalight/voice-over-translation/assets/97290980/3f0e8d5b-139c-4db9-ab8b-4f35707225bb">
<img width="1432" alt="SCR-20240330-oyry" src="https://github.com/ilyhalight/voice-over-translation/assets/97290980/f8ec53b0-f1ec-4950-8539-7cb26e0af928">

**Comment by SashaXser** [comment]
> Operating system / Операционная система Sonoma 14.4.1
> 
> Browser / Браузер Safari 14.4.1
> 
> Userscript manager / Скриптовый движок UserScripts
> 
> Script version / Версия скрипта 1.5.1.3 vot-cloudflare.user.js
> 
> Describe the bug / Опишите ошибку Просто пропала кнопка перевода.
> <img alt="SCR-20240330-oycd" width="1434" src="https://private-user-images.githubusercontent.com/97290980/318198930-3f0e8d5b-139c-4db9-ab8b-4f35707225bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDk0ODMsIm5iZiI6MTcxMTgwOTE4MywicGF0aCI6Ii85NzI5MDk4MC8zMTgxOTg5MzAtM2YwZThkNWItMTM5Yy00ZGI5LWFiOGItNGYzNTcwNzIyNWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDlhMmE1YTMzMmI2ZDM5NzJlZDc3MWFkMGNkYzllZmQzNTFjZWYyNGQxMTAwMGNmYzUxZWFiM2JkZTdhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7dsAtcfdS8pzmfTNKtEQ68mj4QdWQkoBFUEFXMgt5Vg"> <img alt="SCR-20240330-oyry" width="1432" src="https://private-user-images.githubusercontent.com/97290980/318198933-f8ec53b0-f1ec-4950-8539-7cb26e0af928.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4MDk0ODMsIm5iZiI6MTcxMTgwOTE4MywicGF0aCI6Ii85NzI5MDk4MC8zMTgxOTg5MzMtZjhlYzUzYjAtZjFlYy00OTUwLTg1MzktN2NiMjZlMGFmOTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDE0MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmYwNWI3YjNiYTg0YjZmOTMyN2JlN2U3Y2FkYzNiNDU0NDcxMmRjYjExOTYzZjE4YWUxZWEyNzM3MWRmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s099u2WPnNagBqxfQULhIgVJUH7Fuj4rQsg-VKFZOU8">

Удали строку ``` // @grant GM_addStyle```

**Comment by ilyhalight** [comment]
Попробуйте установить последнюю версию(не из релизов, а через ссылку на главной), должно быть исправлено
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/f17cb827-1b7e-43b4-b3eb-abbb22dc5afa)

**Comment by Kerber0ss** [comment]
> Попробуйте установить последнюю версию (не из релизов, а через ссылку на главной), должно быть исправлено ![изображение](https://private-user-images.githubusercontent.com/62353659/318232118-f17cb827-1b7e-43b4-b3eb-abbb22dc5afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4Njk3MjYsIm5iZiI6MTcxMTg2OTQyNiwicGF0aCI6Ii82MjM1MzY1OS8zMTgyMzIxMTgtZjE3Y2I4MjctMWI3ZS00M2I0LWIzZWItYWJiYjIyZGM1YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDA3MTcwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MjliYjdkNjFlN2IxODNlODFhMDljZGNmYmRmYjhiN2U0NDA5MDNiMjczOGFiOTY2NGM1Mjk2NjEzM2JkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qrc9Vhft2perlRsERZkC1pdJfDmZIv9Everp4v6doI8)

yes, working!!! thank you.

**Comment by ifRemix** [comment]
> Попробуйте установить последнюю версию (не из релизов, а через ссылку на главной), должно быть исправлено ![изображение](https://private-user-images.githubusercontent.com/62353659/318232118-f17cb827-1b7e-43b4-b3eb-abbb22dc5afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4ODA0NjAsIm5iZiI6MTcxMTg4MDE2MCwicGF0aCI6Ii82MjM1MzY1OS8zMTgyMzIxMTgtZjE3Y2I4MjctMWI3ZS00M2I0LWIzZWItYWJiYjIyZGM1YWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDEwMTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZDdlZTg0NDcyZTFhYzdlMzEwODg1MmFjZmRlNDA2OTgzNWI0ZThjMzI0YTJiYzU3NTI2MWY3OTkxYzBkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMp_kYpEXj5i4hYIADQ3TDYiloKK1UFnR9INK3WuRhk)


Отлично! этот вариант сработал. просто удаление  строки  `// @grant GM_addStyle` почему-то не работало7 
Спасибо!
