### ISSUE TITLE
Не работает твич прямого эфира голосовой перевод 

### ISSUE THREAD

**Issue by Healf94** [ilyhalight/voice-over-translation#577]
### Operating system / Операционная система

Windows 10 android

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.1.4 vot

### Describe the bug / Опишите ошибку

Нету значка перевода на твич в прямом эфире , устанавливал на ПК , попробовал оперу файр Фокс гугл хром не работает , заходил даже через m.twitch тоже самое , в клипах значок перевода есть , установил на андроид файрфокс ночь  и поставил этот скрипт через tampermonkey , тоже самое , версия скрипта последняя

### Additional information / Дополнительная информация

(

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 10 android
> ### Browser / Браузер
> 
> Firefox
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.1.4 vot
> ### Describe the bug / Опишите ошибку
> 
> Нету значка перевода на твич в прямом эфире , устанавливал на ПК , попробовал оперу файр Фокс гугл хром не работает , заходил даже через m.twitch тоже самое , в клипах значок перевода есть , установил на андроид файрфокс ночь и поставил этот скрипт через tampermonkey , тоже самое , версия скрипта последняя
> ### Additional information / Дополнительная информация
> 
> (

Поддерживаются только клипы и видео. Перед размещением сообщения в данном разделе внимательно ознакомьтесь с Вики-страницей, посвященной поддержке сайтов.

Доступные (под)домены:

    [www.twitch.tv](https://www.twitch.tv/)
    [m.twitch.tv](https://m.twitch.tv/)
    [player.twitch.tv](https://player.twitch.tv/)
    [clips.twitch.tv](https://clips.twitch.tv/)

Доступные пути:

    /videos
    /embed
    /NICKNAME/clip
    /?video=VIDEO_ID (используется только для player.twitch.tv)

**Comment by Healf94** [comment]
Благодарен вам за ответ, теперь буду внимально читать возможности . И ещё вопросик , планируется ли в будущем сделать перевод трансляции?

**Comment by Healf94** [comment]
Ого, спасибо вам за ваши труды, жду обновления!!!
