### ISSUE TITLE
Пропала кнопка перевода в видео на Google Drive.

### ISSUE THREAD

**Issue by Post1rony** [ilyhalight/voice-over-translation#578]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.1.4

### Describe the bug / Опишите ошибку

В версии 1.5.1.4 перестала появляться кнопка в видео на Google Drive, в 1.5.1.3 кнопка появлялась, видео переводилось.

**Comment by SashaXser** [comment]
Попробуй [фикс](https://github.com/SashaXser/voice-over-translation/tree/test/dist), должно исправить проблему

**Comment by Post1rony** [comment]
Спасибо, пофиксилось.

**Comment by imudk** [comment]
Спасибо, но, что на фиксе, что на обновлении 1.5.1.5 перестало переводиться, появляется сообщение "I can't translate the video, try again later". Хотя еще час назад все было хорошо. Доступ к файлам открыт.

**Comment by Post1rony** [comment]
У меня все работает, что 1.5.1.4 с фиксом, что 1.5.1.5. Кстати еще одна проблема с гугл диском в том, что переводит видео намного дольше чем все остальное, по ощущениям раз в 10 дольше.

**Comment by imudk** [comment]
> Спасибо, но, что на фиксе, что на обновлении 1.5.1.5 перестало переводиться, появляется сообщение "I can't translate the video, try again later". Хотя еще час назад все было хорошо. Доступ к файлам открыт.

Частично проблему я решил. Оказалось, что у Google Drive есть лимит на воспроизведения и поэтому запросы не отправлялись, так как Яндекс не могу скачать аудио из-за недоступности видео. Но, мне пока не удалось перевести видео длинней 50 минут. Если видео 2 часа я получаю такую же ошибку, но при этом это не связано с доступностью видео, так как оно доступно. У кого-то переводились видео по 2 часа?

**Comment by Post1rony** [comment]
> > Спасибо, но, что на фиксе, что на обновлении 1.5.1.5 перестало переводиться, появляется сообщение "I can't translate the video, try again later". Хотя еще час назад все было хорошо. Доступ к файлам открыт.
> 
> Частично проблему я решил. Оказалось, что у Google Drive есть лимит на воспроизведения и поэтому запросы не отправлялись, так как Яндекс не могу скачать аудио из-за недоступности видео. Но, мне пока не удалось перевести видео длинней 50 минут. Если видео 2 часа я получаю такую же ошибку, но при этом это не связано с доступностью видео, так как оно доступно. У кого-то переводились видео по 2 часа?

Действительно не переводит, попробовал 3-часовой, долго стоит, но в итоге пишет 'не удалось'.
