### ISSUE TITLE
Поддержка developer.apple.com/videos

### ISSUE THREAD

**Issue by Ramiz69** [ilyhalight/voice-over-translation#579]
### Describe your feature / Опишите ваше предложение

Хотелось бы увидеть поддержку перевода [сессий WWDC](https://developer.apple.com/videos/all-videos/)

**Comment by ilyhalight** [comment]
Позже будет добавлен наряду с Patreon и Reddit. Возможно, в апреле-мае, может быть позже. Точных сроков не могу дать

**Comment by Gerodot** [comment]
Очень надеюсь что до WWDC появится. Спасибо.

**Comment by Gerodot** [comment]
10 числа начинается WWDC и было бы не плохо что бы появилась поддержка, будут выходить новые видео и переводы были бы очень к месту.

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
