### ISSUE TITLE
Поддержка www.artstation.com

### ISSUE THREAD

**Issue by SeekerLightOri** [ilyhalight/voice-over-translation#58]
Привет очень хотелось бы увидеть поддержку https://www.artstation.com/learning
На этом сайте очень много полезного контента для 2D и 3D направлений, которых нет на том же ютуб, если это конечно возможно 
Это достаточно популярная площадка среди художников, думаю многим это поможет в изучении своего дела

**Comment by ilyhalight** [comment]
Привет, к сожалению на данный момент это не возможно. Яндекс Переводчик не поддерживает данный сайт.

Поддерживаемые сайты:
        "^www.coursera.org$"
        "^(www.|m.)facebook.com$"
        "^9gag.com$"
        "^www.tiktok.com$"
        "^(www.|m.)?twitch.tv$"
        "^(mobile.)?twitter.com$"
        "^(player.)?vimeo.com$"
        "^(m.)?vk.com$"
        "^www.udemy.com$"
        "^(www.|m.)?youtube(-nocookie)?.com$"
        "^(www.|rt.)?pornhub.com$":
        "^www.xvideos.com$"
