### ISSUE TITLE
Не работает перевод на Safari (macOS Ventura)

### ISSUE THREAD

**Issue by Gerodot** [ilyhalight/voice-over-translation#583]
### Operating system / Операционная система

macOS Ventura 13.6.6 (22G630)

### Browser / Браузер

Safari 17.4.1 (18618.1.15.111.8, 18618)

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.5.1.5

### Describe the bug / Опишите ошибку

При попытке запросить перевод, отображается ошибка "Не удалось запросить перевод видео", лог на скрине. Пытался текстом приложить но не получилось. 
<img width="1058" alt="Снимок экрана 2024-04-06 в 15 28 03" src="https://github.com/ilyhalight/voice-over-translation/assets/1532819/610d0896-f048-4db0-b965-c31f5b255fad">

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> macOS Ventura 13.6.6 (22G630)
> ### Browser / Браузер
> 
> Safari 17.4.1 (18618.1.15.111.8, 18618)
> ### Userscript manager / Скриптовый движок
> 
> UserScripts
> ### Script version / Версия скрипта
> 
> 1.5.1.5
> ### Describe the bug / Опишите ошибку
> 
> При попытке запросить перевод, отображается ошибка "Не удалось запросить перевод видео", лог на скрине. Пытался текстом приложить но не получилось. <img alt="Снимок экрана 2024-04-06 в 15 28 03" width="1058" src="https://private-user-images.githubusercontent.com/1532819/320204249-610d0896-f048-4db0-b965-c31f5b255fad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0MDc1MzEsIm5iZiI6MTcxMjQwNzIzMSwicGF0aCI6Ii8xNTMyODE5LzMyMDIwNDI0OS02MTBkMDg5Ni1mMDQ4LTRkYjAtYjk2NS1jMzFmNWIyNTVmYWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMTI0MDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmNjMDM5Y2E5YzBkZTMzYzgxYWJhMDEzZjNkY2UxMmJjZGM2YTY4NTVjODg0M2NjNzVlY2UxMWRmZDI5ZTQ4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5gICuJRl156VzcggdpNQqArWy9q1e2eECCdWJv-mBS0">
> ### Additional information / Дополнительная информация
> 
> _No response_

На каком сайте перевод?

**Comment by Gerodot** [comment]
Странная ситуация. Сначала отвалилась Cloudfire версия, с той же ошибкой, после чего долго метался и пытался обновиться и пробовал в том числе и указанную мой тут. Сейчас заработала VOT Cloudfire
