### ISSUE TITLE
Не устанавливается на macos Safari

### ISSUE THREAD

**Issue by varo1n** [ilyhalight/voice-over-translation#587]
### Operating system / Операционная система

macos Sonoma

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

no

### Describe the bug / Опишите ошибку

Илья приветствую. Нашел недавно твой чудо скрипт, установил по инструкции на ютубе, все работало отлично. Но на следующий день кнопка перевода в ютубе просто перестала появляться. Удалил скрипт и пробовал установить заново, но движок больше не хочет перехватывать твой скрипт с гитхаба, пишет проверка и ничего не меняется. Подскажи, пожалуйста, что где надо почистить, чтоб все заработало? Заранее спасибо ))
<img width="873" alt="Снимок экрана 2024-04-17 в 21 48 15" src="https://github.com/ilyhalight/voice-over-translation/assets/165905131/8d9df6e9-cc90-4be8-9dc8-8d9e4fd3e62a">

**Comment by ilyhalight** [comment]
Не подскажу, сам только пару раз пользовался userscripts и с такой проблемой не сталкивался. Как вариант попробуйте полностью переустановить расширение userscripts

**Comment by varo1n** [comment]
Спасибо. Помогла переустановка userscripts. vot.user установился, но работать почему-то отказался, пишет нет доступа к переводу, cloudflare установилась и работает без проблем. Спасибо вам за ваш труд ))
