### ISSUE TITLE
ДОбавить в мобильный браузер Cromite

### ISSUE THREAD

**Issue by SergeyDjam** [ilyhalight/voice-over-translation#591]
### Describe your feature / Опишите ваше предложение

В браузере встроенный функционал UserScript, однако на сайтах с видео VOT никак не отрабатывает. 
По возможности адаптировать скрипт.

**Comment by ilyhalight** [comment]
Не будет реализовано. У мобильной версии Cromite нет ни remote debug, ни devtools, а логи через adb не содержат никакой информации об ошибках внутри скрипта + судя по https://github.com/uazo/cromite/issues/589#issuecomment-1844982169 поддержки grant тоже нет (хоть это и не так критично)
