### ISSUE TITLE
Кнопка перевода под заблокированным слоем встроенного плеера.

### ISSUE THREAD

**Issue by bogisis** [ilyhalight/voice-over-translation#596]
### Operating system / Операционная система

MacOS 14.3

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Greasemonkey

### Script version / Версия скрипта

1.5.2.2

### Describe the bug / Опишите ошибку

В случае со встроенными плеерами (youtube в моем случае), где заблокированы элементы управления и щелчок правой кнопкой мыши, кнопка перевода видео оказывается как будто бы под прозрачным слоем блокирующем нажатие на нее в том числе. 
Можно ли как-либо иначе вызывать перевод видео, горячие клавиши? 
Или может можно добавить в настройки опцию автоматического активирования перевода?

**Comment by ilyhalight** [comment]
> Или может можно добавить в настройки опцию автоматического активирования перевода?

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/62353659/91542ca8-c339-4400-bce0-b7c59b11b61a)
?

**Comment by ilyhalight** [comment]
Переоткройте, если проблема все еще существует
