### ISSUE TITLE
Добавить функцию Краткий пересказ видео от YandexGPT

### ISSUE THREAD

**Issue by denbog1** [ilyhalight/voice-over-translation#597]
### Describe your feature / Опишите ваше предложение

Не знаю, насколько это сложно добавить, но было-бы очень удобно пользоваться функцией Краткий пересказ видео от YandexGPT
![image](https://github.com/ilyhalight/voice-over-translation/assets/168200378/9045ce2f-0024-4253-9594-3f5a9130b7c6)

**Comment by ilyhalight** [comment]
Если нужен пересказ используйте https://github.com/FOSWLY/summarize. В этом расширение не будет пересказа.
