### ISSUE TITLE
Скачивание аудиодорожки с наложенным переводом

### ISSUE THREAD

**Issue by dlt5** [ilyhalight/voice-over-translation#599]
### Describe your feature / Опишите ваше предложение

Снова поднимаю вопрос реализации этой хотелки.
Сейчас для получения видео с переводом нужно скачать видео, скачать звук, скачать перевод, объединить аудиодорожки в редакторе, затем заменить оригинальную дорожку новой.
Может, есть способ реализовать объединение дорожек? Громкость при наложении соответственно та, что выставлена.

**Comment by Buumcode** [comment]
> объединить аудиодорожки в редакторе, затем заменить оригинальную дорожку новой.
На всякий случай поясню, что для личного употребления можно использовать BSPlayer – он позволяет запускать сразу две аудиодорожки (однако, громкость каждой дорожки по отдельности регулировать не даёт, только вместе). Правый клик > Аудио > Аудио потоки. Там можно выбрать всё сразу, или можно что-то одно. Также можно подгрузить отдельную звуковую дорожку через "Загрузить внешний аудиофайл".
Другой способ – проигрывать через программу VideoMeld. Там есть встроенный плеер – и можно выставить громкость каждой аудиодорожки отдельно. Программка маленькая, весит всего 10 Мб.

**Comment by Buumcode** [comment]
> а это на андроиде или пк?

Это Windows.

**Comment by ilyhalight** [comment]
https://github.com/FOSWLY/vot-cli + один из скриптов под вашу ОС. При желание скрипт можно переделать, чтобы вместо сохраненения объединенного видео + аудио с переводом сохраняло только аудио с переводом

**Comment by FiLinX** [comment]
> Может, есть способ реализовать объединение дорожек? Громкость при наложении соответственно та, что выставлена.

да, можешь через VOT-Cli это организовать, требует установки Node.js и скрипта translate.ps1 - 

ещё можно с помощью yt-dlp плагина - https://github.com/gnfalex/YT_yt_dlp_plugin

или вот таким батником к ffmpeg, при условии одинаковых имён у лежащих рядом файлов оригинала видео и дорожки аудио-перевода, и скопированного имени в буфер памяти:
`@echo off
set vol=0.25
for /f "delims=" %%i in ('
mshta "javascript:var x=clipboardData.getData('text');if(x) new ActiveXObject('Scripting.FileSystemObject').GetStandardStream(1).Write(x);close();"
') do set ClipboardData=%%i
ffmpeg -hide_banner -i "%ClipboardData%.mp4" -i "%ClipboardData%.mp3" -c:v copy -b:a 128k -filter_complex "[0:a]volume=%vol%[original];[original][1:a]amix=inputs=2:duration=longest[audio_out]" -map 0:v -map "[audio_out]" -y "%ClipboardData%_RUS.mp4"
pause`

**Comment by dlt5** [comment]
@FiLinX, спасибо большое! Хотел попробовать и отписаться, но всё никак не доеду до компа.
