### ISSUE TITLE
БАГ с ускоренным видео

### ISSUE THREAD

**Issue by vruzin** [ilyhalight/voice-over-translation#6]
В момент, когда видео уже запущено, плагинами изменяю скорость воспроизведения. Но перевод не ускоряется. Если поставить видео на паузу и снова запустить, то и перевод тоже ускоряется. Так что я думаю тут надо сделать функцию обновления параметров воспроизведения (возможно по таймеру).

**Comment by ilyhalight** [comment]
Довольно странно... Сейчас попробовал ускорить видео с помощью стандартного изменения скорости от ютуба, а так же с помощью расширения [Enhancer for YouTube](https://addons.mozilla.org/ru/firefox/addon/enhancer-for-youtube/), и всё работает нормально: перевод ускоряется и соответствует оригинальному звуку.

Какие плагины используешь для изменения скорости воспроизведения?
