### ISSUE TITLE
Добавление поддержки сайта

### ISSUE THREAD

**Issue by Svuux** [ilyhalight/voice-over-translation#600]
### Describe your feature / Опишите ваше предложение

Хотелось бы увидеть возможную поддержку перевода сайта https://animego.org

**Comment by ilyhalight** [comment]
В целом можно добавить поддержку и сейчас, но на длинных видео будет слишком долгое ожидание перевода (20+ минут), либо вовсе будут ошибки, из-за того, что их плеер kodik режет скорость на загрузку видео. Нашел одно решение, благодаря которому можно будет довольно сильно уменьшить время ожидания перевода, но сам механизм еще не доделан, поэтому точных сроков не скажу. Но точно не раньше чем #579 и #564

**Comment by Svuux** [comment]
Шикарно буду ждать :)

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
