### ISSUE TITLE
Перевод картинок

### ISSUE THREAD

**Issue by Jemon1024** [ilyhalight/voice-over-translation#601]
### Describe your feature / Опишите ваше предложение

 У меня вот возник вопрос! а есть ли возможность сделать по той же схеме перевод картинок? просто частенько читаю, и не всегда есть желание переводить с оригинального языка самому во время чтения...

**Comment by Svuux** [comment]
https://www.deepl.com/ru/translator
В помощь приложение Deepl Можешь горячими клавишами переводить любое изображение на экране
![Uploading изображение_2024-04-30_090203830.png…]()

**Comment by Svuux** [comment]
![изображение_2024-04-30_090243605](https://github.com/ilyhalight/voice-over-translation/assets/135654927/4b210bd7-2757-4a8a-87d4-e2392c935f37)

**Comment by Jemon1024** [comment]
> ![изображение_2024-04-30_090243605](https://private-user-images.githubusercontent.com/135654927/326687821-4b210bd7-2757-4a8a-87d4-e2392c935f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjIxMDMsIm5iZiI6MTcxNDQ2MTgwMywicGF0aCI6Ii8xMzU2NTQ5MjcvMzI2Njg3ODIxLTRiMjEwYmQ3LTI3NTctNGE4YS04N2Q0LWUyMzkyYzkzNWYzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQzMFQwNzIzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmY5Zjc5ODkxNWQ3YmUwMjU2OGMwYTM5YzMxYjNiYWRmZTAzNWM2NmM2Yjk5MjRlMDE0NTQ5YmMzZDIzYjQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.exhaGAWGFRMcwgJuPkkCNEmPn_kLkDRilMuNBYtodQY)

я конечно все понимаю, есть там такая функция. но вот к примеру я читаю мангу на японском, и мне кадый раз этой фигней заниматься это кукухой поехать можно!

**Comment by CzarOfScripts** [comment]
Скорее всего оффтоп:

> https://www.deepl.com/ru/translator В помощь приложение Deepl Можешь горячими клавишами переводить любое изображение на экране

В windows 11 вы можете сделать скриншот через ножницы (win+shift+s) и там есть такая иконка:
![image](https://github.com/ilyhalight/voice-over-translation/assets/78804737/51c31529-4468-42d0-9a05-8baa94321e07)

Текст оно определяет намного лучше, чем DeepL.

**Comment by Jemon1024** [comment]
> Скорее всего оффтоп:
> 
> > https://www.deepl.com/ru/translator В помощь приложению Deepl Можешь горячими клавишами перевести любое изображение на экран
> 
> В Windows 11 вы можете сделать скриншот через ножницы (win+shift+s), и там есть такая иконка: ![изображение](https://private-user-images.githubusercontent.com/78804737/326915767-51c31529-4468-42d0-9a05-8baa94321e07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0OTgxMzgsIm5iZiI6MTcxNDQ5NzgzOCwicGF0aCI6Ii83ODgwNDczNy8zMjY5MTU3NjctNTFjMzE1MjktNDQ2OC00MmQwLTlhMDUtOGJhYTk0MzIxZTA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE3MjM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYWQ4NjBkM2NmMDZlMjE3NGUzYjY5N2EwOGU2OWM2ZTU1NzRhNGVkYzhmYmJlYmJhZWNkNDczODJkNzliNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Omzd_5sMCelFIMoCMjVdMLN309yR3duLJ5ima9uP6cQ)
> 
> Текст он сформулирован намного лучше, чем DeepL.

а я повторю, когда читаешь что то вот такой фигней заниматься в принципе не хочется! это как шуруп молотком забивать, можно конечно но зачем если можно взять отвертку что лежит там же где и остальные штуки для этого преднозначенные)

**Comment by ilyhalight** [comment]
Пока не планируется

**Comment by ilyhalight** [comment]
сделано https://github.com/ilyhalight/voice-over-translation/issues/1502
