### ISSUE TITLE
Нет кнопки перевести

### ISSUE THREAD

**Issue by MelvinSGjr** [ilyhalight/voice-over-translation#613]
### Operating system / Операционная система

Windows 11 Pro 23H2; Linux Mint LMDE 6 (faye) x86_64 Debian; PeppermintOS i686 Debian

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

latest

### Describe the bug / Опишите ошибку

нет кнопки перевода после обновления

всегда использую Tampermonkey BETA в Brave браузере, FireFox и Chromium

такие пролемы на этих системах возникали:

Windows 11 Pro 23H2
Linux Mint LMDE 6 (faye) x86_64 Debian
PeppermintOS i686 Debian

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> Windows 11 Pro 23H2; Linux Mint LMDE 6 (faye) x86_64 Debian; PeppermintOS i686 Debian
> ### Browser / Браузер
> 
> Other / Другой
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> latest
> ### Describe the bug / Опишите ошибку
> 
> нет кнопки перевода после обновления
> 
> всегда использую Tampermonkey BETA в Brave браузере, FireFox и Chromium
> 
> такие пролемы на этих системах возникали:
> 
> Windows 11 Pro 23H2 Linux Mint LMDE 6 (faye) x86_64 Debian PeppermintOS i686 Debian
> ### Additional information / Дополнительная информация
> 
> _No response_

Логи консоли?

**Comment by SashaXser** [comment]
#620

**Comment by ilyhalight** [comment]
Переоткройте, если проблема не была решена
