### ISSUE TITLE
Изменение переводчика

### ISSUE THREAD

**Issue by JohnConnor123** [ilyhalight/voice-over-translation#617]
### Describe your feature / Опишите ваше предложение

Насколько возможно добавить возможность замены Яндекс переводчика на гугл переводчик? Гугл часто переводит получше и попонятнее, где яндекс откровенно лажает. Возможно это регулирует параметр "Сервис определения", но там нет google, только какой-то rust server
![image](https://github.com/ilyhalight/voice-over-translation/assets/106041597/37608c1c-444b-44f3-bd0f-3386f90b7718)

**Comment by SashaXser** [comment]
Сервис определения языка анализирует текст, чтобы определить язык видео. Переводчик текста используется только для перевода сообщений от Яндекса. По вопросам качества перевода и связанным с этим проблемам, пожалуйста, обращайтесь в службу поддержки Яндекс Браузера. Мы не являемся сотрудниками Яндекс.

**Comment by JohnConnor123** [comment]
Про то, что вы не являетесь сотрудником Яндекс понятно. Вопрос в том, можно ли подменить перевод Яндекса переводом Гугла

**Comment by SashaXser** [comment]
> Про то, что вы не являетесь сотрудником Яндекс понятно. Вопрос в том, можно ли подменить перевод Яндекса переводом Гугла

К сожалению, в настоящее время нет возможности подменить перевод Яндекса переводом Google.
