### ISSUE TITLE
Доработка парсера ответа

### ISSUE THREAD

**Issue by UnDetected** [ilyhalight/voice-over-translation#62]
```
var protoResponse = new protobuf.Type("VideoTranslationResponse")
	.add(new protobuf.Field("url",		1,	"string"))
	.add(new protobuf.Field("duration",	2,	"double"))
	.add(new protobuf.Field("status",	4,	"int32"))
	.add(new protobuf.Field("code",	7,	"string"))
	.add(new protobuf.Field("message",	9,	"string"));
```

duration - время перевода в секундах
code - нарастающее число, возможно порядковый номер перевода. пользы нет.
message - текстовое описание ошибки, если она возникла (status == 0)

Дорабатывать и кидать пулл реквесты некогда (сорян), пилю либу под php, так что то, что выше - результат изысканий =)

**Comment by mynovelhost** [comment]
> ```
> var protoResponse = new protobuf.Type("VideoTranslationResponse")
> 	.add(new protobuf.Field("url",		1,	"string"))
> 	.add(new protobuf.Field("duration",	2,	"double"))
> 	.add(new protobuf.Field("status",	4,	"int32"))
> 	.add(new protobuf.Field("code",	7,	"string"))
> 	.add(new protobuf.Field("message",	9,	"string"));
> ```
> 
> duration - время перевода в секундах code - нарастающее число, возможно порядковый номер перевода. пользы нет. message - текстовое описание ошибки, если она возникла (status == 0)
> 
> Дорабатывать и кидать пулл реквесты некогда (сорян), пилю либу под php, так что то, что выше - результат изысканий =)

Данные в запросе анализировал? Или есть какой то билд ябраузера с доп информацией :) ?

**Comment by UnDetected** [comment]
> 

Реверсил. За Я.Браузер вообще не брался ни разу, у меня к нему стойкое отвращение.

**Comment by mynovelhost** [comment]
> > 
> 
> Реверсил. За Я.Браузер вообще не брался ни разу, у меня к нему стойкое отвращение.

Жаль, я надеялся что билд с символами слили. Ну а по поводу отвращения, думаю те кому ябраузер нравится в этот репозиторий и не полузут
