### ISSUE TITLE
Не работает. Нет кнопки перевести

### ISSUE THREAD

**Issue by Mihail990** [ilyhalight/voice-over-translation#620]
### Operating system / Операционная система

Windows 11 Pro 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.2.2

### Describe the bug / Опишите ошибку

После последних обновлений win 11, а так же хром - пропала кнопка. Тамперманки, скрипт переустанавливался - результата никакого.

**Comment by SashaXser** [comment]
Есть ошибки в консоли?

**Comment by Mihail990** [comment]
> Есть ошибки в консоли?

<img width="560" alt="Screenshot_2" src="https://github.com/ilyhalight/voice-over-translation/assets/123508916/36980b0c-4a72-4cbc-9333-7c18fb9900f2">
Где еще посмотреть?

**Comment by SashaXser** [comment]
У вас точно установлен скрипт? Попробуйте удалить и [перекачать](https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot.user.js)

**Comment by Mihail990** [comment]
Я прежде чем писать, уже переустанавливал... Но ок, еще раз. В консоли все равно ругается на 778 строку (инициализация)
<img width="528" alt="Screenshot_1" src="https://github.com/ilyhalight/voice-over-translation/assets/123508916/0ef851b9-5ac4-40a2-9fb9-332f9fa7db58">
<img width="459" alt="Screenshot_2" src="https://github.com/ilyhalight/voice-over-translation/assets/123508916/536eaf5b-2da6-4ae7-9a5b-feb3d82c5a44">
<img width="759" alt="Screenshot_3" src="https://github.com/ilyhalight/voice-over-translation/assets/123508916/06a8b184-faf1-4a3a-a203-5934b96a0acb">
Это 100% после обновления и скорей всего только хрома. До несколько дней в нем висело предложение "перезапустить и обновить", и все работало.

**Comment by Mihail990** [comment]
> Интересно, в Chrome 125 проблем не обнаружено... решение формы #604

Спасибо за помощь и подсказку. Пароль не нужно отключать, после обновления винды слетела авторизация учетной записи майкрософт. Вновь залогинился, все заработало.
