### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by vocalir145** [ilyhalight/voice-over-translation#624]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.2.2

### Describe the bug / Опишите ошибку

![image](https://github.com/ilyhalight/voice-over-translation/assets/131145311/f5dd573c-281e-4c05-975d-bfef4c9c8b98)
![image](https://github.com/ilyhalight/voice-over-translation/assets/131145311/b3f84e64-9f15-4e5c-ba53-c1d08c911717)

**Comment by GallenteProt** [comment]
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/160413161/e7a8ebe6-1ff6-4dc1-910c-02194510c071)

**Comment by Arseniy56439** [comment]
Такая же проблема в chrome

**Comment by GennPen** [comment]
Edge 125 - тоже перестало работать

**Comment by FiLinX** [comment]
а у кого нибудь яндекс браузер стоит?  там сейчас как?
а то может это у яндекса какой то из датацентров с гипофизом нейронки повредился..

**Comment by Big92B** [comment]
Brave\ не работает.
Яндекс\ работает

**Comment by FiLinX** [comment]
а вы прокси в VOTе пробовали менять?  
я не могу, у меня старая версия VOT, ещё без выборов этих проксей)

**Comment by Big92B** [comment]
> ## хм.. спросил щас на форуме руборда по яндекс браузеру:
> работает ли сейчас у вас перевод видео на ютубе?
> > Нет. Не работает. Ни в Яндексе ни в Cent. 22.05.24 21:12

у меня работало час назад. Сейчас попробовал, Youtube вообще перестал включаться через Yandex

**Comment by FiLinX** [comment]
так что с проксями в VOTе?  они к куда?  вот мож эта прокся и легла щас

**Comment by grxxnd00r** [comment]
ось - Windows 7
брузер - Firefox ESR 115.11 x32
до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".

почините пажалуйста :(

**Comment by ipwin-github** [comment]
Изначально был какой-то сбой на стороне Яндекса потому что в Yandex браузере перевод тоже не работал. При включении перевода появлялось сообщение "Очень много запросов на перевод попробуйте позже". Сейчас перевод в Yandex браузере заработал и на данный момент работает. А вот в Cent (и в других браузерах скорее всего тоже) перевод по прежнему не работает. VOT пишет "Не удалось запросить перевод видео".

**Comment by Alkohole** [comment]
> так что с проксями в VOTе? они к куда? вот мож эта прокся и легла щас

Ну, от смены прокси ситуация не меняется

**Comment by neyguvj** [comment]
> в ориг браузере не работает, думаю это общая проблема: 
а какая версия браузера?

**Comment by ipwin-github** [comment]
[Dragoy](https://github.com/Dragoy) Именно сейчас не работает? Потому что у меня такое же сообщение было где-то час назад но сейчас в Yandex браузере перевод работает. Проверил на многих видео и на всех без исключения перевод работает. Версия браузера 24.1.3.809 (64-bit).

**Comment by Dragoy** [comment]
@ipwin-github в самом яндекс браузере заработало, но расширение пока в ауте

**Comment by sl4rk** [comment]
+ Не работает

**Comment by petrusinov** [comment]
У меня и на Яндекс Браузере пишет ошибку

**Comment by abtalg** [comment]
В Tampermonkey не запускается	скрипт [VOT] - Закадровый перевод видео. Скрипт не запущен.
Tampermonkey не имеет доступа к странице.

**Comment by Lordbl4** [comment]
такая же проблема

![6aroafQ 1](https://github.com/ilyhalight/voice-over-translation/assets/5826558/fd25bd84-efa2-4f32-8d7a-630752124cb6)

**Comment by aibymind** [comment]
В яндекс-браузере работает сейчас, а в опере, со скриптом [VOT] - не работает.

**Comment by Log0user** [comment]
Тоже самое.
Google Chrome - Версия 125.0.6422.77
![image](https://github.com/ilyhalight/voice-over-translation/assets/120344565/079970e7-77de-4f6b-b056-bbede3c632b6)
![image](https://github.com/ilyhalight/voice-over-translation/assets/120344565/4b1d87f4-1ba1-4de3-b52c-ee97f5764d66)
Браузер перезагружал, обновлял, расширение перевключал и с впн/без пробовал. Не помогло

**Comment by MixxxGit** [comment]
Подтверждаю! Вчера работало а сегодня снова: "Не удалось запросить перевод видео"
У меня не пашет ни через Adguard ни через Tampermonkey.
Хотя в яндекс-браузере все работает.

**Comment by alexandr19972011** [comment]
Win10, Firefox 126.0, TM 5.1.1, VOT 1.5.2.2 - "Не удалось запросить перевод видео"
![изображение](https://github.com/ilyhalight/voice-over-translation/assets/170599257/d3164a4a-14d5-472a-adc5-02cb92ad93c0)

**Comment by Arseniy56439** [comment]
Всё ещё не работает

**Comment by Valeron-bit** [comment]
Класс.

1. **Unchecked runtime.lastError: The message port closed before a response was received.**
   - **Описание:** Сообщение порта закрыто до получения ответа. Обычно это связано с расширениями браузера или внутренними коммуникациями в браузере.
   - **Решение:** В большинстве случаев это предупреждение можно игнорировать, так как оно не оказывает существенного влияния на функциональность.

2. **LegacycyDataMixin will be applied to all legacy elements.**
   - **Описание:** Будет применен `LegacycyDataMixin` ко всем устаревшим элементам. Используйте настройку `_legacyUndefinedCheck: true` для включения этого поведения.
   - **Решение:** Если вы разрабатываете собственный скрипт, проверьте использование устаревших элементов и при необходимости примените рекомендуемую настройку.

3. **Third-party cookie will be blocked. Learn more in the Issues tab.**
   - **Описание:** Браузер блокирует сторонние куки. Это связано с настройками безопасности и конфиденциальности браузера.
   - **Решение:** Если это поведение нежелательно, настройте политику куки в браузере или серверные заголовки.

4. **Access to XMLHttpRequest at 'https://ad.doubleclick.net/ad...' from origin 'https://www.youtube.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**
   - **Описание:** Запрос XMLHttpRequest был заблокирован политикой CORS, так как отсутствует заголовок `Access-Control-Allow-Origin`.
   - **Решение:** Добавьте соответствующий заголовок на сервере или настройте запросы таким образом, чтобы они соответствовали политике CORS.

5. **Failed to load resource: net::ERR_FAILED**
   - **Описание:** Не удалось загрузить ресурс, ошибка сети.
   - **Решение:** Проверьте доступность ресурса и правильность URL.

6. **Failed to get yandex subtitles**
   - **Описание:** Не удалось получить субтитры с Яндекса.
   - **Решение:** Проверьте корректность запросов к API Яндекса и убедитесь, что доступ к API не заблокирован.

7. **Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.**
   - **Описание:** Неправильно распознан заголовок Permissions-Policy с фичей `ch-ua-form-factor`.
   - **Решение:** Проверьте правильность написания и использования заголовков Permissions-Policy.

8. **This document requires 'TrustedScript' assignment.**
   - **Описание:** Документ требует назначения `TrustedScript`.
   - **Решение:** Убедитесь, что скрипты, которые вы используете, доверенные и назначены правильно.

9. **Failed to load resource: the server responded with a status of 404 (Not Found)**
   - **Описание:** Сервер ответил статусом 404, ресурс не найден.
   - **Решение:** Проверьте URL ресурса и убедитесь, что он существует.

10. **requestStorageAccessFor: Permission denied.**
    - **Описание:** Запрос доступа к хранилищу отклонен.
    - **Решение:** Настройте разрешения на доступ к хранилищу, если это необходимо.

В общем, для решения этих проблем вам нужно будет:
- Проверить конфигурацию серверных заголовков, особенно для CORS.
- Убедиться, что все ресурсы доступны и корректно загружены.
- Настроить права доступа и политики безопасности в соответствии с требованиями вашего приложения.

**Comment by isqad** [comment]
Ну все, учим все английский.

**Comment by thedanill** [comment]
Проблема в том, что серверу не нравится хедер vtrans-signature, т.е подпись запроса. Вероятно, изменился либо алгоритм, либо секретный ключ. Рискну предположить, что изменения произошли ещё несколько версий Браузера назад, но до вчерашнего вечера принимались обе версии подписи. 

Посмотрю, что можно сделать.

**Comment by Sotth** [comment]
Версия [VOT] - Закадровый перевод видео Версия 1.5.2.2 перевод на YouTube не работает, сообщает "Не удалось запросить перевод видео". Браузер Vivaldi
Как решить эту проблему?

**Comment by kscaner** [comment]
В самом Яндекс Браузере выходит сообщение "слишком много запросов на перевод". Пробовал на ютубе и вк. Может это у Яндекса с движком перевода проблемы?

**Comment by thedanill** [comment]
> Проблема в том, что серверу не нравится хедер vtrans-signature, т.е подпись запроса. Вероятно, изменился либо алгоритм, либо секретный ключ. Рискну предположить, что изменения произошли ещё несколько версий Браузера назад, но до вчерашнего вечера принимались обе версии подписи.
> 
> Посмотрю, что можно сделать.

Новый hmac key — bt8xH3VOlb4mqf0nqAibnDOoiPlXsisf, сейчас создам pull request. Судя по всему, параллельно планируется изменить protobuf-схему, в версиях для некоторых платформ это уже произошло. Сейчас нет времени анализировать, мб гляну на той неделе.

**Comment by SashaXser** [comment]
Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)

**Comment by GallenteProt** [comment]
> Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)

Работает, спасибо!

**Comment by grxxnd00r** [comment]
> ось - Windows 7 брузер - Firefox ESR 115.11 x32 до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".
> 
> почините пажалуйста :(



> Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)

РАБОТАЕТ!!!

**Comment by ALLIGATOR88** [comment]
> > ось - Windows 7 брузер - Firefox ESR 115.11 x32 до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".
> > почините пажалуйста :(
> 
> > Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)
> 
> РАБОТАЕТ!!!

Объясните непрограммистам - как это установить? Надо скачать эти файлы, и куда то поместить?

**Comment by grxxnd00r** [comment]
> > > ось - Windows 7 брузер - Firefox ESR 115.11 x32 до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".
> > > почините пажалуйста :(
> > 
> > 
> > > Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)
> > 
> > 
> > РАБОТАЕТ!!!
> 
> Объясните непрограммистам - как это установить? Надо скачать эти файлы, и куда то поместить?

Ну я и сам не программист.
файл "vot.user.js" кнопочка "Copy raw file".
затем заходим в темпрманку и удаляем скрипт, который не работает.
потом нажимаем на поюсик (типа создать новый скрипт и туда контрл в и окей.
у меня всё заработало.

**Comment by thedanill** [comment]
> Объясните непрограммистам - как это установить? Надо скачать эти файлы, и куда то поместить?

Если возникают такие вопросы, то проще всего будет подождать несколько часов до обновления скрипта, всё произойдёт автоматически.

**Comment by grxxnd00r** [comment]
> > > > ось - Windows 7 брузер - Firefox ESR 115.11 x32 до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".
> > > > почините пажалуйста :(
> > > 
> > > 
> > > > Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)
> > > 
> > > 
> > > РАБОТАЕТ!!!
> > 
> > 
> > Объясните непрограммистам - как это установить? Надо скачать эти файлы, и куда то поместить?
> 
> Ну я и сам не программист. файл "vot.user.js" кнопочка "Copy raw file". затем заходим в темпрманку и удаляем скрипт, который не работает. потом нажимаем на плюсик (типа создать новый скрипт) и туда контрл в и окей. у меня всё заработало.

ну или можно просто нажать "Raw" и он сам встанет в темпрманку.

**Comment by ALLIGATOR88** [comment]
> > > > ось - Windows 7 брузер - Firefox ESR 115.11 x32 до недавнего времени перевод работал без проблем, теперь не работает "Не удалось запросить перевод видео".
> > > > почините пажалуйста :(
> > > 
> > > 
> > > > Вот версия с новым ключем, [пробуйте](https://github.com/SashaXser/voice-over-translation/tree/test/dist)
> > > 
> > > 
> > > РАБОТАЕТ!!!
> > 
> > 
> > Объясните непрограммистам - как это установить? Надо скачать эти файлы, и куда то поместить?
> 
> Ну я и сам не программист. файл "vot.user.js" кнопочка "Copy raw file". затем заходим в темпрманку и удаляем скрипт, который не работает. потом нажимаем на плюсик (типа создать новый скрипт) и туда контрл в и окей. у меня всё заработало.

Получилось! Спасибо добрый человек! )

**Comment by FiLinX** [comment]
> Новый hmac key

Спасибо!  заменил ключ - и всё вновь работает!!
но непойму, в исправно работавшей у меня до вчера версии vot.user_1.4.1.js в одном из браузеров  -  я не нахожу строки с hmac key  -  странно.. как же оно тогда работало?  и как сейчас его вылечить?

**Comment by SashaXser** [comment]
Вышел [1.5.3](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.3)

**Comment by FiLinX** [comment]
> Объясните непрограммистам - как это установить?

да ненадо даже ничего вновь переустанавливать!  
просто в темпермонке кликаете по имевшемуся у вас VOT - откроется редактор скрипта
теперь в поиск по Ctrl+F  вбиваете     hmac key
и заменяете устаревший ключ, на этот:
Новый hmac key — bt8xH3VOlb4mqf0nqAibnDOoiPlXsisf
https://i.imgur.com/5p8nXbb.jpeg
всё - в меню Файл на Сохранить

**Comment by FiLinX** [comment]
> Вышел [1.5.3](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.3)

упс))

**Comment by whisperofrunesfromteenager** [comment]
> > Объясните непрограммистам - как это установить?
> 
> да ненадо даже ничего вновь переустанавливать! просто в темпермонке кликаете по имевшемуся у вас VOT - откроется редактор скрипта теперь в поиск по Ctrl+F вбиваете hmac и заменяете устаревший ключ, на этот: Новый hmac key — bt8xH3VOlb4mqf0nqAibnDOoiPlXsisf https://i.imgur.com/5p8nXbb.jpeg всё - в меню Файл на Сохранить

Спасибо, помогло

**Comment by Sotth** [comment]
Версия 1.5.3 РАБОТАЕТ

**Comment by ATWp** [comment]
Чтобы установить, можно сделать проще
1. перейти на страницу этого расширения https://github.com/ilyhalight/voice-over-translation
2. пролистать вниз до слов: [«Установите Скрипт»](https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot.user.js) ...
3. просто сделайте тык по "установите скрипт!"

**Comment by GOVNO3000** [comment]
в Хроме не работает

**Comment by Petro123677** [comment]
в мене з vpn работаєт
