### ISSUE TITLE
Нет кнопки для перевода видео для "Прямых веб-ссылок на .mp4"

### ISSUE THREAD

**Issue by maximkuprikov** [ilyhalight/voice-over-translation#630]
### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3

### Describe the bug / Опишите ошибку

Возможно я что-то не так понял. Хотел перевести видео с локального диска по прямой ссылке на mp4. А там нет кнопки. Да и темпермонкей не реагирует на эту страницу. И есть ли такая возможность в принципе?Если она есть, то я не нашёл как такое сделать. Если есть такая возможность, то можно разместить в "Supported sites" инструкцию. А пока пришлось загрузить на яндекс и смотреть Ядиска. В любом случае спасибо вам и за такую возможность!

**Comment by ilyhalight** [comment]
Локальные файлы нельзя перевести. Перевод доступен только для прямых веб-ссылок (которые начинаются на http), например https://s3.toil.cc/vot/video.mp4
