### ISSUE TITLE
Не удалось запросить перевод видео

### ISSUE THREAD

**Issue by vladozer** [ilyhalight/voice-over-translation#631]
### Operating system / Операционная система

Ubuntu Linux

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.2.2

### Describe the bug / Опишите ошибку

При попытке перевести видео, моментально пишет, что не удалось запросить перевод видео.

**Comment by ilyhalight** [comment]
Обновитесь до 1.5.3
