### ISSUE TITLE
Увеличение громкости или турбо режим.

### ISSUE THREAD

**Issue by JackieWaltRyan** [ilyhalight/voice-over-translation#64]
Прошу сделать возможность увеличивать максимальную громкость перевода выше 100%. Или дополнительно/на крайний случай турбо режим, как в том же Enhancer for YouTube например. Желательно до 1000%.

Потому что как я довольно часто замечаю, аудио дорожка русского перевода, иногда намного тише оригинальной на инглише... На скриншоте Enhancer for YouTube, где 10 как раз 1000%.

![Screenshot-174](https://user-images.githubusercontent.com/79658863/205749565-176f2b93-4380-42b9-b32e-4e5de355be33.png)

**Comment by ilyhalight** [comment]
Добавлю

**Comment by ilyhalight** [comment]
> Добавлю

Сейчас не очень много времени что-то добавлять и тестировать, поэтому откладывается на неопределенный срок

**Comment by 25hz** [comment]
а зачем,если на ютубе можно убавить инглишь и все

**Comment by narimangafurov** [comment]
Обновился. Все супер! спасибо!

**Comment by ilyhalight** [comment]
И
