### ISSUE TITLE
Перевод использует "минуты" вместо "минут" для множественного числа

### ISSUE THREAD

**Issue by Blueberryy** [ilyhalight/voice-over-translation#643]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

![image](https://github.com/ilyhalight/voice-over-translation/assets/36592509/798d98fe-0f11-40af-8b1c-3f074646539a)

Я вроде уже кидал PR где сократил перевод до просто "мин.", но он куда-то делся.

**Comment by ilyhalight** [comment]
Теперь, должно писать правильно

**Comment by SashaXser** [comment]
> Теперь, должно писать правильно

![изображение](https://github.com/ilyhalight/voice-over-translation/assets/24498484/9c3ab53f-0603-42b9-a840-84cd317173f2)

**Comment by ilyhalight** [comment]
> > Теперь, должно писать правильно
> 
> ![изображение](https://private-user-images.githubusercontent.com/24498484/335563307-9c3ab53f-0603-42b9-a840-84cd317173f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxOTI3OTEsIm5iZiI6MTcxNzE5MjQ5MSwicGF0aCI6Ii8yNDQ5ODQ4NC8zMzU1NjMzMDctOWMzYWI1M2YtMDYwMy00MmI5LWE4NDAtODRjZDMxNzE3M2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDIxNTQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNmNiNGIxN2ExZjcxNmM5NzQ5YTVlYjgxNmFlOTI4YWRhNjQxOTUzZGY4MTc1YjJmYjNiZWVhMDcxZDRhNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IX5W7VoRRRrmhCFV_UXm6FJ-oaZAN5pBx-AULPnUko8)

`+`
