### ISSUE TITLE
Failed to request video translation

### ISSUE THREAD

**Issue by devenrgy** [ilyhalight/voice-over-translation#646]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

При запросе на перевод видео, появляется ошибка Failed to request video translation. Расширение переустанавливал, не помогает. Ошибка последние дня 2. 
https://i.imgur.com/syi71Tm.png
https://i.imgur.com/1QkTLMW.png
https://i.imgur.com/KDXw9FC.png
https://i.imgur.com/KWoQwkH.png

**Comment by ilyhalight** [comment]
Возможно, у вас недоступны сервера яндекса. Попробуйте cloudflare версию

**Comment by devenrgy** [comment]
> Возможно, у вас недоступны сервера яндекса. Попробуйте cloudflare версию

C cloudflare заработало. 🙄
Странно конечно, но ладно, буду пользоваться ей теперь... Спасибо за ответ.

**Comment by ErmeevEgor** [comment]
Такая же проблема, а как установить cloudflare версию?
