### ISSUE TITLE
neural networks cloud not detect speech video

### ISSUE THREAD

**Issue by typekol** [ilyhalight/voice-over-translation#647]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.2.2

### Describe the bug / Опишите ошибку

https://www.youtube.com/watch?v=2xJzF4GeDs4&list=PL5qQm8_EmcZPIuy-i6yDbjV3ErWtysIbP&
Не воркает - neural networks cloud not detect speech video
![Screenshot_54](https://github.com/ilyhalight/voice-over-translation/assets/157954524/2f650ba5-3762-46e5-8461-a6a4ba52d86f)

**Comment by ilyhalight** [comment]
Обновитесь до 1.5.3.1

**Comment by typekol** [comment]
Ничего не изменилось все так-же

**Comment by SashaXser** [comment]
> Ничего не изменилось все так-же

Поменяй язык видео на "Авто".

**Comment by ilyhalight** [comment]
> Обновитесь до 1.5.3.1

Перепутал ошибки, выше дали правильный ответ
