### ISSUE TITLE
translation itself is missing (форматаудио не поддерживается)

### ISSUE THREAD

**Issue by Blackdragon3035** [ilyhalight/voice-over-translation#649]
### Operating system / Операционная система

win 24h2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

translates and makes the background sound quieter, but the translation itself is missing.  (переводит и делает фоновый звук тише, однако отсутствует сам перевод......иногда пишет формат аудио не поддерживается) sometimes it says audio format is not supported

**Comment by ilyhalight** [comment]
Попробуйте cloudflare версию с проксированием аудио

**Comment by Blackdragon3035** [comment]
Спасибо, помогло именно проксирование.

**Comment by Blackdragon3035** [comment]
> Спробуйте версію cloudflare з проксуванням аудіо


Спасибо, помогло именно проксирование.
