### ISSUE TITLE
Субтитры

### ISSUE THREAD

**Issue by jestxfot** [ilyhalight/voice-over-translation#65]
Добавьте поддержку субтитров

**Comment by djekstar** [comment]
Поддерживаю, иметь возможность генерить сабы помимо закадрового голосового перевода тоже было бы очень круто. Вроде как в бразуере Яндекса с этой функцией есть такая возможность ? Почему скрип дает только возможность пользоваться закадровым переводом ?

**Comment by jestxfot** [comment]
В том то и дело что генерация субтитров уже готова и существует, её просто почему-то забыли добавить

**Comment by ilyhalight** [comment]
https://github.com/ilyhalight/voice-over-translation/issues/1#issuecomment-1185044543
