### ISSUE TITLE
support kick

### ISSUE THREAD

**Issue by MaximKiselev** [ilyhalight/voice-over-translation#655]
### Describe your feature / Опишите ваше предложение

hi, please add support kick.com. its similar like twitch

**Comment by ilyhalight** [comment]
This isn't possible yet

**Comment by MaximKiselev** [comment]
I meant adding archive, not streaming

**Comment by ilyhalight** [comment]
> I meant adding archive, not streaming

this too, kick uses m3u8, which isn't being translated yet

**Comment by SashaXser** [comment]
@ilyhalight Можно закрывать?
