### ISSUE TITLE
Скорость видео

### ISSUE THREAD

**Issue by Doloni1** [ilyhalight/voice-over-translation#656]
### Describe your feature / Опишите ваше предложение

Добавьте при возможности функцию в настройки которая при активации перевода будет автоматически ускорять видео на 1,25х или 1,5х, примерно как это сделано с громкостью. А то надоело видео с переводом ускорять вручную а без перевода замедлять вручную...

**Comment by ilyhalight** [comment]
Не думаю что будет добавлено
