### ISSUE TITLE
Определение языка у видео, на сайте bilibili.com

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#659]
### Describe your feature / Опишите ваше предложение

Для примера, если открыть видео на английском, по умолчанию для сайта будет выбираться перевод для китайского:
https://www.bilibili.com/video/BV1v142117Y9/?p=2&spm_id_from=pageDriver&vd_source=31ca8612fe0b126579a245dddfcf3735

Я для этого каждый раз лезу в код скрипта что бы сменить язык по умолчанию для сайта на английский. 

Предлагаю в настройки добавить дропдаун где для всех по умолчанию используется автоматический подбор языка (Авто), либо выбрать любой другой язык который будет переопределен жестко для всех сайтов. Что бы просто не лезть каждый раз в скрипт и не редачить его.

**Comment by SashaXser** [comment]
> ### Describe your feature / Опишите ваше предложение
> 
> Для примера, если открыть видео на английском, по умолчанию для сайта будет выбираться перевод для китайского: https://www.bilibili.com/video/BV1v142117Y9/?p=2&spm_id_from=pageDriver&vd_source=31ca8612fe0b126579a245dddfcf3735
> 
> Я для этого каждый раз лезу в код скрипта что бы сменить язык по умолчанию для сайта на английский.
> 
> Предлагаю в настройки добавить дропдаун где для всех по умолчанию используется автоматический подбор языка (Авто), либо выбрать любой другой язык который будет переопределен жестко для всех сайтов. Что бы просто не лезть каждый раз в скрипт и не редачить его.

Не волнуйтесь о выборе языка. Яндекс теперь автоматически определяет язык видео, поэтому вам не нужно его указывать. Посмотрите субтитры, Яндекс уже определил, что видео на английском языке.

**Comment by ilyhalight** [comment]
> (А да, похоже Яндекс блокирует все языки кроме "Авто")

Странно, что выключили именно any => ru, на некоторых видео zh => en/kk все еще работает

**Comment by ilyhalight** [comment]
> Что означает скрипт просто никак не детектит язык на bilibili

так и есть

**Comment by Dragoy** [comment]
> > Что означает скрипт просто никак не детектит язык на bilibili
> 
> так и есть

как на счет временного решения, добавить выпадашку с языком по умолчанию?

**Comment by ilyhalight** [comment]
> > > Что означает скрипт просто никак не детектит язык на bilibili
> > 
> > 
> > так и есть
> 
> как на счет временного решения, добавить выпадашку с языком по умолчанию?

мне кажется нет особого смысла, на большинстве сайтов и так стоит auto как язык, которого хватает. Сейчас сделал так же и для bilibili

**Comment by Dragoy** [comment]
> Сейчас сделал так же и для bilibili
а как тогда быть? вручную в коде zn менять на en для bilibili?

**Comment by ilyhalight** [comment]
> > Сейчас сделал так же и для bilibili
> 
> а как тогда быть? вручную в коде zn менять на en для bilibili?

уже поменял на auto, нужно просто обновиться через кнопку на главной репозитория

**Comment by SashaXser** [comment]
> > > Сейчас сделал так же и для bilibili
> > 
> > 
> > а как тогда быть? вручную в коде zn менять на en для bilibili?
> 
> уже поменял на auto, нужно просто обновиться через кнопку на главной репозитория

Кстати, похоже bilibili пропадает при полном экране, откати изменение селектора для bilibili в sites.js, также можешь разкоментить old

``
      selector: ".bpx-player-video-wrap",
``

**Comment by Dragoy** [comment]
> уже поменял на auto, нужно просто обновиться через кнопку на главной репозитория

спасибо, сейчас проверю

**Comment by Dragoy** [comment]
Все отлично работает!
![image](https://github.com/ilyhalight/voice-over-translation/assets/4968313/c22e843e-dc44-4eba-b9f6-6d50c4a5c9e6)

> на bilibili пропадает кнопка при полном экране

у меня так же +++

**Comment by SashaXser** [comment]
> Все отлично работает! ![image](https://private-user-images.githubusercontent.com/4968313/338348729-c22e843e-dc44-4eba-b9f6-6d50c4a5c9e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTQzNTgsIm5iZiI6MTcxODA1NDA1OCwicGF0aCI6Ii80OTY4MzEzLzMzODM0ODcyOS1jMjJlODQzZS1kYzQ0LTRlYmEtYjlmNi02ZDUwYzRhNWM5ZTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMjExNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MThlZDNmM2M4NWY2NDFlNGZjNWUxMjNhY2FhYmU2YTg1MzMxOTVjNDc5ZGM0ZmIzZDY0OTIzYTU4ZTZlM2FkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GFtn7BL0N4BjoChtIP-XnRLr5dKskccmuW56-3tMAA8)
> 
> > на bilibili пропадает кнопка при полном экране
> 
> у меня так же +++

Да, но там баг есть если починить, видео начнут дублироваться...

**Comment by Dragoy** [comment]
все же столкнулся с такой проблемой когда оно не хочет переводить с Авто:
![image](https://github.com/ilyhalight/voice-over-translation/assets/4968313/e35fdab7-a93e-413b-9fee-4717f2e788a2)

а когда переключаешь на энглиш все начинает работать:
![image](https://github.com/ilyhalight/voice-over-translation/assets/4968313/47c32761-170b-4375-b4dd-6fbd2e2bfb0b)
