### ISSUE TITLE
Предложение: возможность скачивать видео с переводом

### ISSUE THREAD

**Issue by belya544** [ilyhalight/voice-over-translation#66]
Было бы круто добавить возможность скачивания видео с переводом, у Яндекса такой функции нет, а она очень полезная.

**Comment by ilyhalight** [comment]
Вы можете скачать аудио файл перевода с помощью специальной кнопки внутри меню расширения. После вам останется только объединить его с видео в любом видеоредакторе. Именно функции скачать видео уже объединенное с аудио не будет.
