### ISSUE TITLE
Ошибка не удалось запросить перевод видео

### ISSUE THREAD

**Issue by Polydick** [ilyhalight/voice-over-translation#660]
### Operating system / Операционная система

Windows 10 Pro 22H2

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

![Untitlsddsdsdsdsed](https://github.com/ilyhalight/voice-over-translation/assets/160669917/8c20f93d-c688-46f0-94b3-39a040c0eab0)

### Additional information / Дополнительная информация

Произошло это после перехода с браузера waterfox на оперу. Возможно что-то не так настроено хотя что может пойти не так если я скачал аддон для оперы tampermonkey и ваш скрипт?

**Comment by SashaXser** [comment]
Что в консоли?

**Comment by ilyhalight** [comment]
Попробуйте установить cloudflare версию, либо предоставьте логи консоли

**Comment by Buumcode** [comment]
Может, проблема с испанским языком? У меня 1.5.3.1 – английский переводит без проблем.

**Comment by sskorohod** [comment]
Та же проблема после обновления хрома

**Comment by FiLinX** [comment]
в последних версиях хромых, да, темпормонка не работает, даже с режимом разраба..
крайняя версия монки для MV2 - [это 5.1.1](https://www.tampermonkey.net/)
но у человека вроде не в этом суть, у него панелька ВОТа наличествует, а на новых хромых её и небыло бы даже

**Comment by ilyhalight** [comment]
> в последних версиях хромых, да, темпормонка не работает, даже с режимом разраба.. крайняя версия монки для MV2 - [это 5.1.1](https://www.tampermonkey.net/) но у человека вроде не в этом суть, у него панелька ВОТа наличествует, а на новых хромых её и небыло бы даже

Вроде уже исправили работу ТМв3, по крайней мере на 126 хроме все работает

**Comment by Polydick** [comment]
> Та же проблема после обновления хрома

да у меня ещё остальные расширения работают некорректно

**Comment by Polydick** [comment]
> У меня тоже v1.5.3.1. Только что зашёл на этот канал в ютубе – переводит без проблем. Windows 7, браузер Opera. "хотя что может пойти не так если я скачал аддон для оперы tampermonkey и ваш скрипт?" -- Там в новой версии Tampermonkey требуют включить в браузере Режим Разработчика. Может, в этом дело? Хотя у вас, судя по картинке – скрипт активирован. Вы уверены, что его версия 1.5.3.1? А то у меня стояла старая 1.5.0.5 – и было как у вас на картинке. Обновился вручную – стало получать перевод корректно.

![Untitl333333ed](https://github.com/ilyhalight/voice-over-translation/assets/160669917/30110832-1b14-4b45-85e3-9a4c1bce8c8c)
![Untцццццццццццццццццitled](https://github.com/ilyhalight/voice-over-translation/assets/160669917/ee0a8879-b9f2-4080-b059-172ca6500d95)

**Comment by Polydick** [comment]
> Что в консоли?

![image](https://github.com/ilyhalight/voice-over-translation/assets/160669917/a3e74bf1-02a7-4a7b-9119-cf51fdc7dc10)

**Comment by Polydick** [comment]
> Попробуйте установить cloudflare версию, либо предоставьте логи консоли

так я переустановил помогло. Спасибо
