### ISSUE TITLE
Почему-то не работает скрипт

### ISSUE THREAD

**Issue by stylex122** [ilyhalight/voice-over-translation#661]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Установил темперманки, установил в него скрипт, захожу в ютуб и ни кнопок ничего нет. Как будто ничего и не устанавливал. До этого на браузере вивальди всё было в порядке, правда переводило не всегда, ну в общем работало. А тут просто ничего, пробовал переустанавливать скрипт, ничего не поменялось. Попробую перезайти в браузер, но вряд ли что-то поменяется.

**Comment by Buumcode** [comment]
А скрипт детектит возможность перевода? Красненький квадратик в панели появляется?
У меня тоже версия v1.5.3.1 – Windows 7, браузер Opera – только что проверил, всё работает.
![VOT_snap_a5613](https://github.com/ilyhalight/voice-over-translation/assets/159101783/315a3ee9-d2b5-4df6-8afe-fd952b43d66c)

**Comment by stylex122** [comment]
Нет такого как на скрине, просто иконка чёрная. Да, похоже в этом режиме разработчика дело. Как я понял это в хроме в меню расширений включается, включил и всё вроде заработало. И под иконкой счётчик этот тоже появился.

**Comment by stylex122** [comment]
Закрываю тему
