### ISSUE TITLE
Не отображаться кнопка перевода

### ISSUE THREAD

**Issue by Wolfish991** [ilyhalight/voice-over-translation#662]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

![Screenshot 2024-06-11 150259](https://github.com/ilyhalight/voice-over-translation/assets/172391224/659b37bd-01de-465c-b93a-3962d8ca8118)

**Comment by Buumcode** [comment]
Вам же Тамперманки пишет, что теперь для работы скрипта нужно включить DEVELOPER MODE. Вы это сделали?

**Comment by Wolfish991** [comment]
Спасибо, заработало. Я где то упустил этот момент.

**Comment by avigdorsky** [comment]
Круто все работало но сегодня - отвалилось. Будем разбираться

**Comment by arhiopteryx** [comment]
https://github.com/ilyhalight/voice-over-translation/issues/662#issuecomment-2160768958

**Comment by Lyverance** [comment]
Все равно не работает. вот [пруф](https://vk.com/video319109326_456239511)

**Comment by Ersulan** [comment]
день добрый на браузере "Firefox Developer Edition" не удается включить панель (его просто нет)
