### ISSUE TITLE
убрать из словаря all right, озвучку имён и звуков кроме голоса

### ISSUE THREAD

**Issue by qweshka** [ilyhalight/voice-over-translation#663]
### Describe your feature / Опишите ваше предложение

всё НЕ в порядке)
возможно ли как-то исключить allright и ok из транслейтора?-постоянное "всё в порядке" сводит с ума.
так же бот перед каждой фразой называет имя говорящего
кроме этого озвучивает происходящее на экране не связанное с речью, например- какой жанр музыки заиграл в этот момент, если в видео ударяется металлический предмет, бот это анонсит как: "звон алюминия" и тп по типу "закрылась дверь" если в видео кто-то хлопнул дверью.
зы:спасибо!

**Comment by ilyhalight** [comment]
Пишите яндексу, проблема на их стороне. Мы на озвучку никак повлиять не можем
