### ISSUE TITLE
Brave Not Work (Brave браузер не работает перевод)

### ISSUE THREAD

**Issue by dfdfjk34125** [ilyhalight/voice-over-translation#664]
### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

ex. 1.4.1

### Describe the bug / Опишите ошибку

Я не знаю ошибка или не ошибка но. Я пользуюсь brave Браузером. И перевода видео нету (I am Idk eror this or no but. I am user brave browser and this not work)

### Additional information / Дополнительная информация

Перевода видео не появляется (Video transletor doesn't doesn't appear)
<img width="766" alt="Screenshot_82" src="https://github.com/ilyhalight/voice-over-translation/assets/172494789/6761fef7-0dd9-46f4-8dc7-f58096be5087">

**Comment by ilyhalight** [comment]
https://github.com/ilyhalight/voice-over-translation/issues/662#issuecomment-2160768958
