### ISSUE TITLE
Добавить ОГРОМНЫЙ КРАСНЫЙ ТЕКСТ в README

### ISSUE THREAD

**Issue by SashaXser** [ilyhalight/voice-over-translation#665]
### Describe your feature / Опишите ваше предложение

Я замечаю множество Issues, создаваемых без предварительного изучения FAQ или поиска решения в уже существующих Issues. Предлагаю обновить раздел посвященный решению наиболее распространенных ошибок. Также можно добавить красный текст, который будет привлекать внимание, чтобы пользователи обращались к разделу с решением проблем в README.

**Comment by ilyhalight** [comment]
Обновил и немного актуализировал FAQ, в README добавил информацию о необходимости проверить FAQ и уже существующие Issues.

Есть какие-либо предложения, что еще добавить FAQ?

**Comment by SashaXser** [comment]
> Обновил и немного актуализировал FAQ, в README добавил информацию о необходимости проверить FAQ и уже существующие Issues.
> 
> Есть какие-либо предложения, что еще добавить FAQ?

Буду пока наблюдать за ситуацией, возможно, в будущем предложу новые идеи. Кажется, что список сайтов в Supported sites можно расширить.

**Comment by ilyhalight** [comment]
> > Обновил и немного актуализировал FAQ, в README добавил информацию о необходимости проверить FAQ и уже существующие Issues.
> > 
> > Есть какие-либо предложения, что еще добавить FAQ?
> 
> Буду пока наблюдать за ситуацией, возможно, в будущем предложу новые идеи. Кажется, что список сайтов в Supported sites можно расширить.
> 

нужно будет его тоже обновить

**Comment by ilyhalight** [comment]
> > > Обновил и немного актуализировал FAQ, в README добавил информацию о необходимости проверить FAQ и уже существующие Issues.
> > > Есть какие-либо предложения, что еще добавить FAQ?
> > 
> > 
> > Буду пока наблюдать за ситуацией, возможно, в будущем предложу новые идеи. Кажется, что список сайтов в Supported sites можно расширить.
> 
> нужно будет его тоже обновить

обновил
