### ISSUE TITLE
Как перевести видео которое не в онлайне, а сохранено на компьютере?

### ISSUE THREAD

**Issue by InfernalWolf666** [ilyhalight/voice-over-translation#667]
### Describe your feature / Опишите ваше предложение

Бывает так что имеется видео скачанное на компьютер, как попросить этот скрипт перевести звуковую дорожку?

Допустим даже, если просто я вырежу звуковую дорожку в видеоредакторе, что бы эта нейронная сеть её перевела, и я бы опять в редакторе её обьеденил/заменил .

Если нельзя то посоветуйте аналоги пожалуйста

**Comment by Buumcode** [comment]
Можно заливать на сайты и переводить: ютуб, Vkontakte, яндекс-диск. Для перевода нужно делать видео открытым для доступа по ссылке. Пример с Яндекс-диском: [тыц](https://github.com/ilyhalight/voice-over-translation/issues/513?notification_referrer_id=NT_kwDOCXuzV7Q5MzYwNjM2MTQ4OjE1OTEwMTc4Mw#issuecomment-2017789463)
