### ISSUE TITLE
Пропала кнопка в Твиттере

### ISSUE THREAD

**Issue by vocalir145** [ilyhalight/voice-over-translation#669]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

![image](https://github.com/ilyhalight/voice-over-translation/assets/131145311/4d3459fc-4013-4b9a-b732-07d9f8059c25)

**Comment by ilyhalight** [comment]
Убедитесь, что вы открываете видео как пост (в адресной строке будет https://twitter.com/nickname/status/...), если все равно не показывается, то дайте ссылку, где не работает

**Comment by ilyhalight** [comment]
Переоткройте, если проблема не решена
