### ISSUE TITLE
Feature: Добавить перевод для аудио

### ISSUE THREAD

**Issue by vts3rss** [ilyhalight/voice-over-translation#67]
Добрый день. Есть ли возможность добавить синхронный перевод для аудио? Например для Google Podcast. https://podcasts.google.com/feed/aHR0cHM6Ly9hbmNob3IuZm0vcy83MmVhMmU0Yy9wb2RjYXN0L3Jzcw?sa=X&ved=0CAkQlvsGahcKEwjIo6Cbx_v7AhUAAAAAHQAAAAAQAQ&hl=ru-KZ
Спасибо

**Comment by ilyhalight** [comment]
К сожалению Яндекс не поддерживает гугл подкасты

**Comment by ilyhalight** [comment]
Все доступные сайты (для части из которых уже сделан перевод) можно глянуть тут: #34

**Comment by vts3rss** [comment]
Понял, спасибо
