### ISSUE TITLE
The function does not work: do not translate from the selected language

### ISSUE THREAD

**Issue by lfazliev** [ilyhalight/voice-over-translation#673]
### Operating system / Операционная система

IOS 17.5.1

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.5.3.1 cloudflare

### Describe the bug / Опишите ошибку

Translates the video into the native language when the do not translate from the selected language feature is enabled.

**Comment by ilyhalight** [comment]
Думаю можно посчитать за баг, не помню зачем изначально была сделана проверка на соответствие обоих языков, возможно, изначально планировался какой-то другой функционал
