### ISSUE TITLE
Перевод Картинок

### ISSUE THREAD

**Issue by InfernalWolf666** [ilyhalight/voice-over-translation#678]
### Describe your feature / Опишите ваше предложение

Привет, ребят, я пользовался яндекс браузером и обнаружил что он помимо видео ещё и картинки переводит.
Если такая возможность и эту функцию добавить, на удивление она оказалась полезной когда я посещал например реддит.

Лучей добра

**Comment by ilyhalight** [comment]
https://github.com/FOSWLY/translate-backend/issues/2 + https://github.com/ilyhalight/voice-over-translation/issues/23#issuecomment-1236149903

**Comment by InfernalWolf666** [comment]
> [FOSWLY/translate-backend#2](https://github.com/FOSWLY/translate-backend/issues/2) + [#23 (комментарий)](https://github.com/ilyhalight/voice-over-translation/issues/23#issuecomment-1236149903)

понял, спасибо, геморойно значит

**Comment by ilyhalight** [comment]
сделано #1502
