### ISSUE TITLE
vot-cli: опция output описана некорректно?

### ISSUE THREAD

**Issue by Musickiller** [ilyhalight/voice-over-translation#68]
Добрый день!

В `vot-cli --help` написано, что
```
--output — Download video to directory
```
, хотя на самом деле, скачивается только аудио. Это ошибка в описании или в работе программы?

Конечно было бы комфортно, если бы можно было просто скачать видео сразу с переводом =))

**Comment by Musickiller** [comment]
Say hello to my little fish script, который скачивает видео, скачивает перевод и переводит. Протестил на ютубе для одного видео (не будет пока работать с плейлистами)

https://gitlab.com/musickiller/fishy-voice-over/-/blob/main/translate.fish

**Comment by ilyhalight** [comment]
> Это ошибка в описании или в работе программы?

Ошибка в описание. Исправил.

**Comment by ilyhalight** [comment]
> Say hello to my little fish script, который скачивает видео, скачивает перевод и переводит. Протестил на ютубе для одного видео (не будет пока работать с плейлистами)
> 
> https://gitlab.com/musickiller/fishy-voice-over/-/blob/main/translate.fish
> 
> см. строки для ffmpeg, вся магия там =)

Добавил ссылку в описание ,может быть кому-нибудь пригодится
