### ISSUE TITLE
Xvideos теперь xv-ru

### ISSUE THREAD

**Issue by Etheresk** [ilyhalight/voice-over-translation#682]
### Describe your feature / Опишите ваше предложение

Xvideos теперь переадресует на xv-ru, если выбран язык интерфейса "Русский" (зачем-то)

![image](https://github.com/ilyhalight/voice-over-translation/assets/73643707/f21d0cea-695c-437e-84bf-e62218b3cdd1)
![image](https://github.com/ilyhalight/voice-over-translation/assets/73643707/861ba651-0ed0-4d10-a272-7e8865c12971)

Неплохо было бы добавить поддержку и этого домена

**Comment by ilyhalight** [comment]
Добавил
