### ISSUE TITLE
Формат аудио не поддерживается

### ISSUE THREAD

**Issue by Valeron-bit** [ilyhalight/voice-over-translation#683]
### Operating system / Операционная система

Windows 11 Pro 22H2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3

### Describe the bug / Опишите ошибку

Не переводит видео с английского, пишет, что не поддерживается формат аудио (видео - https://youtu.be/YRWgY4kxSWo?si=xMxhLskR9NJ-XLbd)
![image](https://github.com/ilyhalight/voice-over-translation/assets/70327872/d7123d9f-f11d-4021-a3db-9bfb18a65f35)

**Comment by ilyhalight** [comment]
Переведите с другого языка, например авто. У Яндекса в последнее время что-то часто всплывают проблемы с отвалом ссылки на перевод
