### ISSUE TITLE
Нет поддержки перевода YouTube Shorts

### ISSUE THREAD

**Issue by OR1GG1N2** [ilyhalight/voice-over-translation#69]

**Comment by ilyhalight** [comment]
Пока не планируется. Если нужно посмотреть перевод того или иного шортса нужно поменять ссылку на https://youtube.com/watch?v=АЙДИ_ВИДЕО

Пример:
Шортс - https://www.youtube.com/shorts/zDiJpqVbszk
Отдельное видео - https://www.youtube.com/watch?v=zDiJpqVbszk

**Comment by FiLinX** [comment]
@OR1GG1N2  я открываю все шортсы в эмбедах, и на них перевод уже работает!
YouTube Embedded · RU  -  http://forum.ru-board.com/topic.cgi?forum=2&topic=4971&start=180#5
