### ISSUE TITLE
Как мне быть?

### ISSUE THREAD

**Issue by Ruslanvvv2** [ilyhalight/voice-over-translation#691]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

![Screenshot 2024-07-07 212001](https://github.com/ilyhalight/voice-over-translation/assets/174959080/543d4157-3e4e-4acc-89d4-c0661804cd3e)

### Additional information / Дополнительная информация

Не работает переводчик, то есть вообще не включается.

Предлагает включить мне режим разработчики, пожалуйста, помогите мне с проблемой.

Спасибо за ответ!

The translator does not work, that is, it does not turn on at all.

It offers me to enable developer mode, please help me with the problem.

Thanks for the answer!

**Comment by ilyhalight** [comment]
https://www.tampermonkey.net/faq.php#Q209
