### ISSUE TITLE
Не показывается окно перевода 

### ISSUE THREAD

**Issue by g4p3bgh098i34hg9** [ilyhalight/voice-over-translation#692]
### Operating system / Операционная система

ubuntu 24.04

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Окна перевода нету, из-за чего пользоваться скриптом невозможно. Пробовал на другом браузере Vivaldi но все точно также нету окна. Расширений других нету только Tampermonkey. 

### Additional information / Дополнительная информация

![image](https://github.com/ilyhalight/voice-over-translation/assets/175003047/6a86c61b-754f-471f-b1a3-2306f798762e)

![image](https://github.com/ilyhalight/voice-over-translation/assets/175003047/a27af2a5-225f-4766-91a0-a8a292e5b3e0)

**Comment by ilyhalight** [comment]
Режим разработчика включен? https://www.tampermonkey.net/faq.php#Q209

**Comment by g4p3bgh098i34hg9** [comment]
Включен не был. После включение скрипт заработал. Спасибо!
