### ISSUE TITLE
Не работает с vimeo.com и player.vimeo.com

### ISSUE THREAD

**Issue by alexxety** [ilyhalight/voice-over-translation#695]
### Operating system / Операционная система

Mac OS Sonoma 14.5 (23F79)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

С ютубом все хорошо

Не работает с vimeo.com и player.vimeo.com
пробовал в mazila и chrome 
<img width="407" alt="Снимок экрана 2024-07-10 в 13 46 38" src="https://github.com/ilyhalight/voice-over-translation/assets/154386455/b019711b-1521-4279-af61-50934fcda80a">
<img width="529" alt="Снимок экрана 2024-07-10 в 15 02 51" src="https://github.com/ilyhalight/voice-over-translation/assets/154386455/6df9f439-0606-4a72-a8eb-a701b0e1feac">

Удалены политики 
<img width="831" alt="Снимок экрана 2024-07-10 в 15 58 13" src="https://github.com/ilyhalight/voice-over-translation/assets/154386455/9a97381d-f5cb-44d3-8a99-1fb2466fbe7b">

Подключаюсь с США, так же пробовал так же через vpn 

пробую на обоих версиях с клоудом и без 
<img width="497" alt="Снимок экрана 2024-07-10 в 16 01 23" src="https://github.com/ilyhalight/voice-over-translation/assets/154386455/93cfd8ba-5569-411b-b264-5ab66ea4af05">

<img width="772" alt="Снимок экрана 2024-07-10 в 16 01 43" src="https://github.com/ilyhalight/voice-over-translation/assets/154386455/ddddb6de-d79f-4def-990f-698b41de636a">

**Comment by ilyhalight** [comment]
Ошибка на стороне Яндекса

**Comment by alexxety** [comment]
Когда решиться ?

> Ошибка на стороне Яндекса

**Comment by ilyhalight** [comment]
> Когда решиться ?
> 
> > Ошибка на стороне Яндекса

Не могу сказать точных сроков
