### ISSUE TITLE
Не удается запросить перевод на Invidious

### ISSUE THREAD

**Issue by Vladik01-11** [ilyhalight/voice-over-translation#696]
### Operating system / Операционная система

Windows 10 21H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Любое видео на платформе, основанной на Invidious, отказывается переводится, ссылаясь на "Не удалось запросить перевод видео"

### Additional information / Дополнительная информация

Большинство текущих ссылок на Invidious сейчас стала не актуальными, может стоит обновить их?

**Comment by ilyhalight** [comment]
Что пишет в консоли? Вероятнее всего, поможет полное удаление cors (например, через настройки Tampermonkey) т.к. на invidious они слишком жесткие для работы расширения

**Comment by ilyhalight** [comment]
> После добавления TM в политику безопасности CSP требует дополнительного расширения
> 
> ```
> [VOT] Video Data:  
> Object { translationHelp: null, isStream: false, duration: 343, videoId: "2d6oPq73svY", detectedLanguage: "auto", responseLanguage: "ru" }
> [VOT]-Voice-Over-Translation.user.js:6195:13
> [VOT] Translation response:  
> Object { url: "https://vtrans.s3-private.mds.yandex.net/tts/prod/f8060cb5c64c452f9c4152ccd49b22d3.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=WjGREUc47LBUFZn6pllC%2F20240711%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240711T125330Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=708dba3bc408b92af594dc1e6911615dded9ab62a346d7b56bcfda111597333d", duration: 575.390476, status: 1, translationId: "279685957", language: "en" }
> [VOT]-Voice-Over-Translation.user.js:4417:15
> [VOT] DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable. [VOT]-Voice-Over-Translation.user.js:6033:19
> Content-Security-Policy: Параметры страницы заблокировали загрузку ресурса (media-src) на https://vtrans.s3-private.mds.yandex.net/tts/prod/f8060cb5c64c452f9c4152ccd49b22d3.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=WjGREUc47LBUFZn6pllC%2F20240711%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240711T125330Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=708dba3bc408b92af594dc1e6911615dded9ab62a346d7b56bcfda111597333d, поскольку это нарушает следующую директиву: «media-src 'self' blob: https://*.googlevideo.com:443 https://*.youtube.com:443» watch
> Uncaught (in promise) VOTLocalizedError: An additional extension is needed to support this site
>     VOTLocalizedError moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:2442
>     lipSync moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:6048
>     promise callback*lipSync moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:6032
>     updateTranslation moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:6179
>     translateFunc moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:6401
>     translateVideo moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:4430
>     onload moz-extension://e6f36775-d9ab-4ebe-911f-afe340627cac/userscripts/[VOT]-Voice-Over-Translation.user.js?id=b387b2ff-fbf2-4920-9a4b-421aac959da4:694
>     wt https://invidious.flokinet.to/watch?v=2d6oPq73svY:9
>     i https://invidious.flokinet.to/watch?v=2d6oPq73svY:37
>     wt https://invidious.flokinet.to/watch?v=2d6oPq73svY:9
>     r https://invidious.flokinet.to/watch?v=2d6oPq73svY:24
>     ko https://invidious.flokinet.to/watch?v=2d6oPq73svY:25
>     v https://invidious.flokinet.to/watch?v=2d6oPq73svY:78
>     v https://invidious.flokinet.to/watch?v=2d6oPq73svY:78
>     wt https://invidious.flokinet.to/watch?v=2d6oPq73svY:9
>     f https://invidious.flokinet.to/watch?v=2d6oPq73svY:77
>     l https://invidious.flokinet.to/watch?v=2d6oPq73svY:79
>     send https://invidious.flokinet.to/watch?v=2d6oPq73svY:80
>     Wn https://invidious.flokinet.to/watch?v=2d6oPq73svY:17
>     send https://invidious.flokinet.to/watch?v=2d6oPq73svY:79
>     ko https://invidious.flokinet.to/watch?v=2d6oPq73svY:25
>     Ao https://invidious.flokinet.to/watch?v=2d6oPq73svY:25
>     i https://invidious.flokinet.to/watch?v=2d6oPq73svY:37
>     f https://invidious.flokinet.to/watch?v=2d6oPq73svY:46
>     f https://invidious.flokinet.to/watch?v=2d6oPq73svY:47
>     q https://invidious.flokinet.to/watch?v=2d6oPq73svY:45
>     f https://invidious.flokinet.to/watch?v=2d6oPq73svY:45
>     message https://invidious.flokinet.to/watch?v=2d6oPq73svY:20
>     wt https://invidious.flokinet.to/watch?v=2d6oPq73svY:9
>     t https://invidious.flokinet.to/watch?v=2d6oPq73svY:9
>     message https://invidious.flokinet.to/watch?v=2d6oPq73svY:20
>     message https://invidious.flokinet.to/watch?v=2d6oPq73svY:21
>     <anonymous> https://invidious.flokinet.to/watch?v=2d6oPq73svY:83
>     v https://invidious.flokinet.to/watch?v=2d6oPq73svY:78
> watch:2442:5
> ```

для invidious нужно ставить "удалить полностью", либо использовать сторонние расширения, которые удаляют для нужного сайта
