### ISSUE TITLE
Вместо .srt скачивается json.

### ISSUE THREAD

**Issue by subof** [ilyhalight/voice-over-translation#699]
### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3

### Describe the bug / Опишите ошибку

Пофиксите пожалуйста скачивание субтитров перевода Yandex, чтобы скачивался файл .srt формате.
Сейчас скачивается файл json без расширения.

**Comment by SashaXser** [comment]
> ### Operating system / Операционная система
> 
> _No response_
> ### Browser / Браузер
> 
> Firefox
> ### Userscript manager / Скриптовый движок
> 
> Tampermonkey
> ### Script version / Версия скрипта
> 
> 1.5.3
> ### Describe the bug / Опишите ошибку
> 
> Пофиксите пожалуйста скачивание субтитров перевода Yandex, чтобы скачивался файл .srt формате. Сейчас скачивается файл json без расширения.
> ### Additional information / Дополнительная информация
> 
> _No response_

Обновите/переустановите скрипт
