### ISSUE TITLE
Добавьте поддержку ВК

### ISSUE THREAD

**Issue by Patraskon** [ilyhalight/voice-over-translation#7]

**Comment by ilyhalight** [comment]
С радостью бы добавил, но такой возможности нету в самом Яндекс Браузере ¯\_(ツ)_/¯

**Comment by Patraskon** [comment]
> возможности нету

Есть.
![zxcxzcxzcxc](https://user-images.githubusercontent.com/34421135/178164031-3b7f2816-ea43-4047-a1b4-8c8cc622cb4b.png)

И не только в ВК
![zxczxcczxxczss](https://user-images.githubusercontent.com/34421135/178164047-87689250-cb25-40ad-9a95-f4d86d1e4a94.png)

**Comment by ilyhalight** [comment]
> > возможности нету
> 
> Есть. ![zxcxzcxzcxc](https://user-images.githubusercontent.com/34421135/178164031-3b7f2816-ea43-4047-a1b4-8c8cc622cb4b.png)
> 
> И не только в ВК ![zxczxcczxxczss](https://user-images.githubusercontent.com/34421135/178164047-87689250-cb25-40ad-9a95-f4d86d1e4a94.png)

Можно ссылку на видео? Только, что перепроверил на последней версии Яндекс Браузера и не было кнопки перевода 
![изображение](https://user-images.githubusercontent.com/62353659/178164289-87764daa-46d0-437c-b4e9-ab7613c9a82d.png)

**Comment by Patraskon** [comment]
https://vk.com/video-76524643_456239811

**Comment by ilyhalight** [comment]
> https://vk.com/video-76524643_456239811

Похоже, проблема у меня с Яндекс браузером. Сейчас, попробую с нуля поставить, если получится заставить работать переводчик, то постараюсь добавить в течение недели

**Comment by Patraskon** [comment]
У меня бета версия если что

**Comment by AlexanderDankin** [comment]
Добрый день! Могли бы вы реализовать поддержку переводчика в Safari?

**Comment by ilyhalight** [comment]
Как будет время, гляну на счет Adguard и violetmonkey

**Comment by ilyhalight** [comment]
> Как будет время, гляну на счет Adguard и violetmonkey

Проверил Violetmonkey, там расширение работает из коробки - без необходимости в каких-либо изменениях. AdGuard не могу сейчас проверить, ибо сейчас сижу на линуксе, а AdGuard с юзер-скриптами поддерживает только Mac, Windows и Android (на последнем не получилось запустить, мб чуть позже накачу виртуалку и там попробую)

**Comment by AlexanderDankin** [comment]
Как раз интересует адоптация под Mac. Через AdGuard отображается интерфейс переводчика в Safari, но не работает. 
Установил в Safari расширение Tampermonkey, добавил скрипт, но работает кривовато интерфейс + некорректно работает перевод (разгоняется и зацикливается на одном предложении и всё время его повторяет без остановки)

**Comment by ilyhalight** [comment]
> Как раз интересует адоптация под Mac. Через AdGuard отображается интерфейс переводчика в Safari, но не работает. Установил в Safari расширение Tampermonkey, добавил скрипт, но работает кривовато интерфейс + некорректно работает перевод (разгоняется и зацикливается на одном предложении и всё время его повторяет без остановки)

Понял, Постараюсь исправить

**Comment by ilyhalight** [comment]
> > Как раз интересует адоптация под Mac. Через AdGuard отображается интерфейс переводчика в Safari, но не работает. Установил в Safari расширение Tampermonkey, добавил скрипт, но работает кривовато интерфейс + некорректно работает перевод (разгоняется и зацикливается на одном предложении и всё время его повторяет без остановки)
> 
> Понял. Постараюсь исправить и адаптировать под AdGuard и Safari

Нашёл более лёгкое решение для Safari — https://apps.apple.com/app/userscripts/id1463298887 
Вроде бы, работает как надо :)
P.S.: Используй новую версию расширения 1.0.7
![изображение](https://user-images.githubusercontent.com/62353659/183268622-8d08ee64-d708-4b08-8966-461c358919ee.png)

**Comment by AlexanderDankin** [comment]
Да, всё отлично работает! Спасибо большое!!!

**Comment by AlexanderDankin** [comment]
Выявилось ряд проблем при применении переводчика в Safari. Зайдя на ютьюб и открыв первый ролик, всё нормально работает. Но стоит начать смотреть второй, ну или максимум третий ролик, как начинаются проблемы в виде отсутствия перевода. Интерфейс отображается со следующим содержанием:"перевод займёт минуту", но так и не переводит, либо "невозможно перевести видео. Зайдите позже, нейронная сеть скоро научится" 
Приходится закрывать браузер и открывать его снова. Иногда достаточно обновить страницу. Но это не всегда помогает, чаще приходиться закрывать и открывать браузер. 
Если включить "автоперевод", то перевод в большинстве случаев не работает.
Ещё возникает проблема с отображением интерфейса. Перевод работает, но интерфейс отображает строку: "ошибка загрузки или воспроизведения аудио". В данном случае невозможно отключить/приостановить перевод...

**Comment by ilyhalight** [comment]
> Перевод работает, но интерфейс отображает строку: "ошибка загрузки или воспроизведения аудио".

Исправлю, у меня не совсем правильно сделана проверка и из-за этого иногда выскакивает эта ошибка. 

> :"перевод займёт минуту"

Плагин не посылает автоматический запрос спустя 1-2 минуты, если получает ответ "перевод займёт около минуты". Поэтому необходимо спустя некоторое время нажать ещё раз вручную, чтобы перевод появился.

> "невозможно перевести видео. Зайдите позже, нейронная сеть скоро научится"

Такой ответ плагин получает с сервера и сделать с этим ничего нельзя, но лично я с таким сталкивался всего пару раз (возможно, я просто слишком редко смотрю иностранные видео)

**Comment by DmitriyPekar** [comment]
> > "невозможно перевести видео. Зайдите позже, нейронная сеть скоро научится"
> 
> Такой ответ плагин получает с сервера и сделать с этим ничего нельзя, но лично я с таким сталкивался всего пару раз (возможно, я просто слишком редко смотрю иностранные видео)

такое ещё происходит когда пробуешь перевести +18 видео, где есть подтверждение возрасту(например Dead Island 2 трейлер).
