### ISSUE TITLE
Иногда в Google Chrome запускаются сразу все вкладки с видео на youtube

### ISSUE THREAD

**Issue by dandoner** [ilyhalight/voice-over-translation#70]
Пока не знаю как решить кроме как запретить воспроизводить звук сайту..

**Comment by FiLinX** [comment]
Очень похоже, что в браузере применяется очистка кукисов и стораджей, плюс одно из других расширений добавляет что-то своё новое в ютуб-кукисы - и вот тогда и происходит перезапуск всех вкладок с ютубинами..

**Comment by ilyhalight** [comment]
Не сталкивался с таким. Поэтому чем-либо помочь вряд ли с могу.
