### ISSUE TITLE
Плашка "Перевести видео" не исчезает в некоторых случаях и мешает смотреть видео

### ISSUE THREAD

**Issue by gugglegum** [ilyhalight/voice-over-translation#700]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Обычно плашка "Перевести видео" появляется при открытии видео и исчезает через пару секунд отсутствия движения мышью. Однако, в самом начале с момента установки этого скрипта в Tampermonkey я сталкивался с тем, что эта плашка не исчезала на русскоязычных видео на YouTube. Потом правда это как-то само исправилось. Но сейчас я заметил, что плашка вообще не исчезает на видео на pornhub'е. Как возможное решение я бы предложил добавить крестик или пункт меню "закрыть" или "спрятать".

**Comment by Xruss** [comment]
Есть предложения для улучшения.
Сделать возможность с помощью мишки передвигать плашку "Перевести видео" в любое место браузера (окна видео).

**Comment by ilyhalight** [comment]
> Сделать возможность с помощью мышки передвигать плашку "Перевести видео" в любое место браузера (окна видео).

Сейчас можно передвигать кнопку в левую/правую часть экрана, в любое место не планируется

**Comment by gugglegum** [comment]
> Сейчас можно передвигать кнопку в левую/правую часть экрана, в любое место не планируется

Передвигание плашки ведет себя как-то странно. Мне удалось перетянуть её вправо в уменьшенный вариант. Но теперь не получается вернуть её обратно или переместить влево. При перетаскивании влево плашка появляется посередине сверху, но при отпускании ЛКМ плашка возвращается вправо.

Но что на счёт основной проблемы с неисчезновением плашки при отсутствии движения мыши? Или хотя бы можно отключить этот функционал на pornhub'е? Нафиг он там вообще?

**Comment by ilyhalight** [comment]
>  заметил, что плашка вообще не исчезает на видео на pornhub'е. 

Исправил, обновитесь

**Comment by gugglegum** [comment]
@ilyhalight Вау, круто! Стало исчезать как надо. И за одно перетаскивание плашки влево-вправо стало лучше работать. Спасибо!
