### ISSUE TITLE
Не появляется на x.com (Twitter)

### ISSUE THREAD

**Issue by stepahin** [ilyhalight/voice-over-translation#701]
### Operating system / Операционная система

macOS

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Не появляется кнопка на видео на x.com возможно как раз из-за переезда на новый домен недавно. На ютубе у меня работает всё отлично.

Пробовал в общих настройках:
Modify existing content security policy (CSP) headers: Yes и Remove entirely (никакой другой настройки про CSP не нашел)

В настройках скрипта:
Добавалял в User includes: *://*.x.com/*

Ничего не дало результат. Ютуб так же работает ок. На x.com не появляется кнопка ни в ленте ни на странице твита с видео ни в фулскрине. Что еще попробовать?

**Comment by FiLinX** [comment]
Подтверждаю, да, панелька не выводится, ни в лентах, ни в сингл, ни в фуллсайз
причём это уже давно..
а вот раньше, когда ещё выводилась - был глюк - панелька не исчезала сама с окна плеера)

**Comment by ilyhalight** [comment]
x.com еще не добавлен в расширение, в след. версии добавлю

**Comment by ilyhalight** [comment]
Добавлено в 1.6.0
