### ISSUE TITLE
Как заставить работать скрипт в расширении User JavaScript and CSS?

### ISSUE THREAD

**Issue by Smorvel** [ilyhalight/voice-over-translation#703]
### Describe your feature / Опишите ваше предложение

Я не люблю TemperMonkey и тому подобные расширения, и использую вот это https://chromewebstore.google.com/detail/nbhcbdghjpllgmfilhnhkllmkecfmpld

Подскажите кто нибудь, как в этом расширении завтавить работать скрипт? Я попробовал вставить cloudflare версию, но кнопка перевода не появилась...

**Comment by ilyhalight** [comment]
Добавил гайд в [FAQ](https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ#%D0%BA%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81-user-js-and-css)

**Comment by Smorvel** [comment]
@ilyhalight Только сегодня смог проверить, скрипт не работает через расширение. Сделал все точно как в FAQ, даже в разных браузерах попробовал. но кнопка перевести так и не появилась

**Comment by ilyhalight** [comment]
> @ilyhalight Только сегодня смог проверить, скрипт не работает через расширение. Сделал все точно как в FAQ, даже в разных браузерах попробовал. но кнопка перевести так и не появилась

Возможно, что-то забыли сделать или где-то ошиблись. Так же, проверьте, что используете версию vot 1.6.0. Если все равно не будет появляться, скиньте логи консоли

**Comment by Smorvel** [comment]
@ilyhalight Использую именно 1.6.0 версию скрипта. Все 4 модуля добавил и включил (дважды добавил, так как проверял в разных браузерах)
Что именно из консоли нужно присылать не знаю, так что вот скрин целиком:
![image](https://github.com/user-attachments/assets/70b78c30-5210-44b9-8cf7-cf7181cb7329)

**Comment by ilyhalight** [comment]
> @ilyhalight Использую именно 1.6.0 версию скрипта. Все 4 модуля добавил и включил (дважды добавил, так как проверял в разных браузерах) Что именно из консоли нужно присылать не знаю, так что вот скрин целиком: ![image](https://private-user-images.githubusercontent.com/19754243/356761500-70b78c30-5210-44b9-8cf7-cf7181cb7329.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDAzNDAsIm5iZiI6MTcyMzI0MDA0MCwicGF0aCI6Ii8xOTc1NDI0My8zNTY3NjE1MDAtNzBiNzhjMzAtNTIxMC00NGI5LThjZjctY2Y3MTgxY2I3MzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDIxNDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjk2OGI1ZjAzZDM3MWY3ZDkxYWZiYzk1ZmEyY2JkZWIyNDRhMmFhMDk5NGM1MTQyZWNmYzBmYzc0YmFiYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dPTSR4hkItPyyT3AJHI2TFQnvsxEPS1ROLntjVy5fEs)

этот модуль не добавлен из-за этого не грузится

```
https://gist.githubusercontent.com/ilyhalight/6eb5bb4dffc7ca9e3c57d6933e2452f3/raw/7ab38af2228d0bed13912e503bc8a9ee4b11828d/gm-addstyle-polyfill.js
```

**Comment by Smorvel** [comment]
@ilyhalight но он добавлен. Удалил и повторно добавил, и активировал на странице скрипта, но результата нет.
![image](https://github.com/user-attachments/assets/36f1d9f6-0bea-402e-8e5b-1d2013ef6bc3)

**Comment by Smorvel** [comment]
Вот полный бэкап настроек расширения с модулями и скриптом
[user-js-css-v11-240810.json](https://github.com/user-attachments/files/16567243/user-js-css-v11-240810.json)

**Comment by ilyhalight** [comment]
> Вот полный бэкап настроек расширения с модулями и скриптом
> 
> [user-js-css-v11-240810.json](https://github.com/user-attachments/files/16567261/user-js-css-v11-240810.json)

Очень странно. у меня все работает с вашими настройками

**Comment by Smorvel** [comment]
@ilyhalight банально конечно, но может у вас скрипт подгружает какое-то другое расширение?) Типа дополняет и загружунный скрипт в страницу уже подхватывает недостающие модули или что там нужно 👀

**Comment by ilyhalight** [comment]
> @ilyhalight банально конечно, но может у вас скрипт подгружает какое-то другое расширение?) Типа дополняет и загружунный скрипт в страницу уже подхватывает недостающие модули или что там нужно 👀

Все другие загрузчики выключаю во время тестов, да и в самом меню пишет, что он загружен именно через этот загрузчик (через полифил). Попробуйте сделать "Сброс данных" в расширение и загрузить заново json конфиг, может быть поможет

**Comment by Smorvel** [comment]
Проверил только что в "виртуальном" браузере (в облаке), и действительно там появилась кнопка. Но у меня ни в какую не хочет, ни через один из браузеров. Сейчас буду пытаться разобраться почему так. Когда разберусь отпишусь.

**Comment by Smorvel** [comment]
В общем браузер для тестов у меня был Edge в нем кнопка не отображалсь потому что там куки были отключены для ютуба. После включения все заработало.
А вот мой основной бразер Cent, и в нем никак не получается заставить работать скрипт. Возможно дело в устаревшем хромиуме, не знаю.. но тут даже расширение у меня уставнолено версии 2.1.1, тем не менее я проверил на последней версии расширения (просто убрав из манифеста требования к хромиуму 120+), и почему-то скрипт всеравно не работает. Видимо это не исправить пока браузер не обновят.

В любом случае пасибо за помощь, за детальнейший FAQ, я вообще не ожидал такого 😇
