### ISSUE TITLE
Поддержка blender.org

### ISSUE THREAD

**Issue by CoringPlay** [ilyhalight/voice-over-translation#704]
### Describe your feature / Опишите ваше предложение

Домен с обучающими видео video.blender.org
Данный сайт работает на PeerTube v5.0.0
Проэкт по изучению Blender от Blender Foundation

**Comment by SashaXser** [comment]
@ilyhalight Разве так должно быть?
![изображение](https://github.com/user-attachments/assets/e0e3c806-07f5-482c-be72-95ddd13e9818)

**Comment by ilyhalight** [comment]
> @ilyhalight Разве так должно быть? ![изображение](https://private-user-images.githubusercontent.com/24498484/355621603-e0e3c806-07f5-482c-be72-95ddd13e9818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5ODY2NDUsIm5iZiI6MTcyMjk4NjM0NSwicGF0aCI6Ii8yNDQ5ODQ4NC8zNTU2MjE2MDMtZTBlM2M4MDYtMDdmNS00ODJjLWJlNzItOTVkZGQxM2U5ODE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDIzMTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMWJhZjFmOGE3ZGIyNGY2OGY1Y2JhOWZmNzljNGU5YjZhYjllNzU0NjExYTNmYjIwMjFjZmUxMTY1M2Q1ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pf8KcfmRaOdFE_F-KQ-XEFC1G7vayIdBRW53ILenAAE)

не должно
