### ISSUE TITLE
Поддержка сайтов для взрослых

### ISSUE THREAD

**Issue by 11class09** [ilyhalight/voice-over-translation#705]
### Describe your feature / Опишите ваше предложение

Было бы здорово если бы добавили поддержку porntn.com и incestflix.com

**Comment by FiLinX** [comment]
до сих пор не понимаю - что там переводить то вообще имеется, в порнухах то? )
ладно ещё всякие хентай сериалы, там хоть какой то текст есть.. а тут то что?

**Comment by pinkigerls** [comment]
Привет, FiLinX!

Слушай, ты прав, порнуха — это, конечно, не Шекспир, но иногда там действительно бывают диалоги, по сюжету которых можно понять, что происходит. Да и не забывай, что на Pornhub иногда выкладывают всякие трэшовые ролики с закадровым голосом или сюжетом, который можно обсудить. Это не всегда чистая порнография, иногда там есть интересные моменты, которые можно перевести или обыграть. 

Так что, да, не всегда там текст на уровне «Как дела?», но иногда и разговорчики, и сюжеты, хоть и хреновые, но есть! Так что поддержка таких сайтов — это не лишнее, особенно если кто-то хочет подойти к этому с юмором или креативом. 

Короче, если поднимется вопрос о поддержке, то не стоит так уж ужесточать — иногда в этом есть смысл!

**Comment by ilyhalight** [comment]
> если бы добавили поддержку porntn.com

.com и .net это один и тот же сайт или просто похожие? Еще неделю назад сделал логику для .com, но сейчас сайт что-то не работает

**Comment by ilyhalight** [comment]
> incestflix.com

сайты без поддержки https не добавляются в расширение

**Comment by 11class09** [comment]
> .com и .net это один и тот же сайт или просто похожие?

Просто похожие, но не один и тот же. 
С .com иногда бывает такое что он не доступен. Но в этот раз он что-то долго лежит.


> > incestflix.com
> 
> сайты без поддержки https не добавляются в расширение

incestflix.to или incestflix.net  Те же самые сайты только есть https. Вообще у него много доменов. На каких-то есть https на каких-то нет.

**Comment by ilyhalight** [comment]
> incestflix.com

Добавлено в 1.7.1
