### ISSUE TITLE
Формат аудио не поддерживается

### ISSUE THREAD

**Issue by sl4rk** [ilyhalight/voice-over-translation#712]
### Operating system / Операционная система

Windows 11 23h2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

При попытке перевести вот это видео
https://www.youtube.com/watch?v=NMfjnZ66cxA 
появляется сообщение "формат аудио не поддерживается"
![Screenshot 2024-07-27 032115](https://github.com/user-attachments/assets/ec55767d-95ca-4e99-b40e-0d4f2e4fad52)

**Comment by ilyhalight** [comment]
Скорее всего опять яндекс шалит как в #683, проверь с авто на нужный язык нормально переводит

**Comment by sl4rk** [comment]
> Скорее всего опять яндекс шалит как в #683, проверь с авто на нужный язык нормально переводит?
