### ISSUE TITLE
Некорректное отображение окна

### ISSUE THREAD

**Issue by witalihirsch** [ilyhalight/voice-over-translation#713]
### Operating system / Операционная система

MacOS Sequoia

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Некорректно отображается окно в Safari
![image 1](https://github.com/user-attachments/assets/c89b11c7-26cb-4560-b21f-2da910ccd0cb)

**Comment by witalihirsch** [comment]
Такая проблема на ютюбе, в остальных поддерживаемых плеерах все в порядке

**Comment by ilyhalight** [comment]
> Такая проблема на ютюбе, в остальных поддерживаемых плеерах все в порядке

Попробуй кнопку перетянуть в правую/левую часть плеера и потом вернуть назад

**Comment by witalihirsch** [comment]
О, рил сработало, спасибо
