### ISSUE TITLE
Не работает перевод в видео с рабочего стола ПК, открытом через браузер

### ISSUE THREAD

**Issue by ReleaseN** [ilyhalight/voice-over-translation#715]
### Operating system / Операционная система

Windows 11 Pro 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Доброго времени суток! Не могу понять то, почему не переводит видео, которое находится на рабочем столе моей операционной системы и которое открыто при помощи браузера. В поле "@includes" мной был добавлен путь, но видео не переводится. Неудобно загружать скачанные видео на Ютуб в приватный плейлист (да и есть ограничения на суточную загрузку), чтобы перевести ролики и хотелось бы, чтобы можно было переводить их без этого, просто открыв видео в браузере.

![attachment](https://github.com/user-attachments/assets/9c9f2f86-3429-4754-bd58-490ab8a13112)

**Что пробовал:** перезагружать скрипт, перезагружать браузер, заново открывать видео, открывать видео разной продолжительности (2 часа и 10 минут)

**Что ожидаю:** перевод видео напрямую с компьютера в браузере после соответствующего правила в настройках скрипта

P. S: в моём браузере на базе Chromium (Cent Browser) путь до файла начинается с "file:///" (3 слэша).

**Comment by Buumcode** [comment]
> перевод видео напрямую с компьютера в браузере

Перевод напрямую невозможен. Яндекс переводит только те видео, которые находятся в расшаренном (публичном) доступе – такая политика.

Загружайте видео на сайты (Ютуб, Вконтакте, Яндекс-диск и т.п.), делайте их доступными по ссылке – и тогда переводит. 
Вот тема, где описано как переводить в Яндекс-диске:
https://github.com/ilyhalight/voice-over-translation/issues/513?notification_referrer_id=NT_kwDOCXuzV7Q5MzYwNjM2MTQ4OjE1OTEwMTc4Mw#issuecomment-2196427888
