### ISSUE TITLE
Перестало отображаться меню перевода в YouTube

### ISSUE THREAD

**Issue by walged** [ilyhalight/voice-over-translation#716]
### Operating system / Операционная система

Windows 10 20H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

До сегодняшнего дня все работало, в очередной раз пошел шерстить англ. уроки и заметил, что кнопки перевода в YouTube отсутствует, решил проверить другие сайта, в том же Вконтакте все работает, проблема только в YouTube
Скрин с ютуба
![image](https://github.com/user-attachments/assets/debd3236-e985-4a67-b6e3-938508e20bcc)
Скрин с Вк
![image](https://github.com/user-attachments/assets/eaf56885-da5c-46d8-8206-9293b860be15)

**Comment by ilyhalight** [comment]
Что в консоли?

**Comment by walged** [comment]
![image](https://github.com/user-attachments/assets/cf147e61-c0d3-4325-9017-286f492405da)

**Comment by walged** [comment]
![image](https://github.com/user-attachments/assets/08ff4082-f7f1-491c-941c-4182792e92c0)

**Comment by oxalates** [comment]
Та же проблема  в хроме 
![img-2024-07-31-20-56-30](https://github.com/user-attachments/assets/b882d50e-686d-4f8f-9437-561553222348)

**Comment by oxalates** [comment]
В Брейве тоже сломалось: failed to request video translation

**Comment by ilyhalight** [comment]
> ![image](https://private-user-images.githubusercontent.com/110821987/353928713-cf147e61-c0d3-4325-9017-286f492405da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDgwNDUsIm5iZiI6MTcyMjQ0Nzc0NSwicGF0aCI6Ii8xMTA4MjE5ODcvMzUzOTI4NzEzLWNmMTQ3ZTYxLWMwZDMtNDMyNS05MDE3LTI4NmY0OTI0MDVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNzQyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAxMGZlZmRkMTI2Njk1ZTc4NTE4ZGU4NWU3MjA1YzRjMWRhNzhlZDM4Y2FhYmU4NGIzNmU0NTEyMjU1OGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRyNOQZmEzCALeN7UTIsP6eVaBU1m13cZdgF1L5WBic)

Попробуйте эту версию https://kmi.aeza.net/Oe98gmKX69?hl (для установки скопируйте все с сайта и замените в ТМ)

**Comment by oxalates** [comment]
> > ![image](https://private-user-images.githubusercontent.com/110821987/353928713-cf147e61-c0d3-4325-9017-286f492405da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDgwNDUsIm5iZiI6MTcyMjQ0Nzc0NSwicGF0aCI6Ii8xMTA4MjE5ODcvMzUzOTI4NzEzLWNmMTQ3ZTYxLWMwZDMtNDMyNS05MDE3LTI4NmY0OTI0MDVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNzQyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAxMGZlZmRkMTI2Njk1ZTc4NTE4ZGU4NWU3MjA1YzRjMWRhNzhlZDM4Y2FhYmU4NGIzNmU0NTEyMjU1OGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRyNOQZmEzCALeN7UTIsP6eVaBU1m13cZdgF1L5WBic)
> 
> Попробуйте эту версию https://kmi.aeza.net/Oe98gmKX69?hl (для установки скопируйте все с сайта и замените в ТМ)

также не отображается кнопка в ютюбе

**Comment by ilyhalight** [comment]
> > > В Брейве тоже сломалось: failed to request video translation
> > 
> > 
> > Точно используете актуальную версию скрипта?
> 
> в брейве старая - 1.5.0.5 в хроме - 1.5.3.1

в брейве не работает из-за старой версии

**Comment by walged** [comment]
> > ![image](https://private-user-images.githubusercontent.com/110821987/353928713-cf147e61-c0d3-4325-9017-286f492405da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDgwNDUsIm5iZiI6MTcyMjQ0Nzc0NSwicGF0aCI6Ii8xMTA4MjE5ODcvMzUzOTI4NzEzLWNmMTQ3ZTYxLWMwZDMtNDMyNS05MDE3LTI4NmY0OTI0MDVkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQxNzQyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTAxMGZlZmRkMTI2Njk1ZTc4NTE4ZGU4NWU3MjA1YzRjMWRhNzhlZDM4Y2FhYmU4NGIzNmU0NTEyMjU1OGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DRyNOQZmEzCALeN7UTIsP6eVaBU1m13cZdgF1L5WBic)
> 
> Попробуйте эту версию https://kmi.aeza.net/Oe98gmKX69?hl (для установки скопируйте все с сайта и замените в ТМ)

Попробовал, перезапускал браузер, те же ошибки 
![image](https://github.com/user-attachments/assets/6084a6b9-e6aa-4105-98fe-379f7ca99699)
![image](https://github.com/user-attachments/assets/73ba1c44-868e-4985-a99e-70efe53f9136)

**Comment by oxalates** [comment]
В брейве заработала 1.5.3.1

**Comment by ilyhalight** [comment]
Получилось повторить. Если работа расширения нужна прямо сейчас, то отключите CSP и все заработает. либо подождите фикса

Как это можно сделать ниже (отключает для всех сайтов, если нужно отключить только для ютуба, то используйте доп. расширения):
![изображение](https://github.com/user-attachments/assets/d162439d-c3b3-42c1-96d2-3000122dcf93)
![изображение](https://github.com/user-attachments/assets/243b28b4-5218-4132-804d-4ef6610b589b)

**Comment by walged** [comment]
> Получилось повторить. Если работа расширения нужна прямо сейчас, то отключите CSP и все заработает. либо подождите фикса
> 
> Как это можно сделать показал ниже (отключает для всех сайтов, если нужно отключить только для ютуба, то используйте доп. расширения): ![изображение](https://private-user-images.githubusercontent.com/62353659/353954244-d162439d-c3b3-42c1-96d2-3000122dcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTI0MzQsIm5iZiI6MTcyMjQ1MjEzNCwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQyNDQtZDE2MjQzOWQtYzNiMy00MmMxLTk2ZDItMzAwMDEyMmRjZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxM2NmMTIxYzQxNTFhNzg4OGRmZGJjYzI0MDJlY2Y1MjllNzkxZWE4MGZkYTY5ZGVkMjQ5MzY3ZWY4NmQxMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHj4AxT-D0RXYe_KrNFGmOACK4jU2L4b3uX3T6KQ_M8) ![изображение](https://private-user-images.githubusercontent.com/62353659/353954304-243b28b4-5218-4132-804d-4ef6610b589b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTI0MzQsIm5iZiI6MTcyMjQ1MjEzNCwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQzMDQtMjQzYjI4YjQtNTIxOC00MTMyLTgwNGQtNGVmNjYxMGI1ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE4NTUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2MDNiMTZjZjU5NzU4YjA2ZTE5NzZlOTE5NTk4ZTZkYTA1YjRlNTgxNTBiMDMxYTAyMDliMWYwMjM1NDdlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._tF_PAMUxKavrS9JpNdegvc2v-Nc0VWn8vcdVdamIjg)

Получилось, кнопка перевода отобразилась, спасибо!
![image](https://github.com/user-attachments/assets/203b28d9-18c6-48ed-a619-250197161b12)

**Comment by Olas-GE** [comment]
> Получилось повторить. Если работа расширения нужна прямо сейчас, то отключите CSP и все заработает. либо подождите фикса
> 
> Как это можно сделать показал ниже (отключает для всех сайтов, если нужно отключить только для ютуба, то используйте доп. расширения): ![изображение](https://private-user-images.githubusercontent.com/62353659/353954244-d162439d-c3b3-42c1-96d2-3000122dcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTcyNzQsIm5iZiI6MTcyMjQ1Njk3NCwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQyNDQtZDE2MjQzOWQtYzNiMy00MmMxLTk2ZDItMzAwMDEyMmRjZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYzNlNzBmYzYwZjk2N2M0MGY0YTg3YzczNGViNTc3MTZmYzhlZmE5YzI5NGU4NmE5ZjcwNzkyZGFlODQ1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fPMSanXAjag5YVEZecEOY1AYV48dDHSSkcoudGT_MHo) ![изображение](https://private-user-images.githubusercontent.com/62353659/353954304-243b28b4-5218-4132-804d-4ef6610b589b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTcyNzQsIm5iZiI6MTcyMjQ1Njk3NCwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQzMDQtMjQzYjI4YjQtNTIxOC00MTMyLTgwNGQtNGVmNjYxMGI1ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwMTYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwZWZhNzg3MmNmZWE2NDI4YTg0Nzc2NmIzNTU2MThlMDk0YmQ2NzlhNjJhOWJhMTVkMzEyYjYzMmIwNTE1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcvAdw45o5R1q1yRTvvae73BzC8ZBkIkWnfoqNmfgwE)

Заработало на Edge. Спасибо!

**Comment by VitalySonko** [comment]
Заработало, но потом снова перестало (((.

**Comment by Djalil1976** [comment]
> Получилось повторить. Если работа расширения нужна прямо сейчас, то отключите CSP и все заработает. либо подождите фикса
> 
> Как это можно сделать показал ниже (отключает для всех сайтов, если нужно отключить только для ютуба, то используйте доп. расширения): ![изображение](https://private-user-images.githubusercontent.com/62353659/353954244-d162439d-c3b3-42c1-96d2-3000122dcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDQ3NTksIm5iZiI6MTcyMjUwNDQ1OSwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQyNDQtZDE2MjQzOWQtYzNiMy00MmMxLTk2ZDItMzAwMDEyMmRjZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZjgxYTRmMDZkNGI2ZTk5MjExYTllZWI1MmIwYWIzNWNlM2YyNmI5OWY3MDlkNjg3NWUyN2VhZmYzMjI2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vgdn2CMpOUzwYnyGFXw2EenEVOr9bk0JisUnNaQM1e8) ![изображение](https://private-user-images.githubusercontent.com/62353659/353954304-243b28b4-5218-4132-804d-4ef6610b589b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MDQ3NTksIm5iZiI6MTcyMjUwNDQ1OSwicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQzMDQtMjQzYjI4YjQtNTIxOC00MTMyLTgwNGQtNGVmNjYxMGI1ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA5MjczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2Q5ZDBlNGU4MWRlYzlmMDNjZjVhNDY3ODJiMGE2NTE4NzdkNTIxYmEyYjQyMDcwZjdjNzA3YWViMjFjODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TORy9WooMpZ0mPWl2drXv2HrfLrhWWbJQMWtK6uEJSg)

Это способ помог, на YouTube перевод работает

**Comment by ilyhalight** [comment]
Вариант без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js

**Comment by brz95** [comment]
@ilyhalight 
спасибо, спас
будем благодарны если расскажешь как без vpn убрать замедление YouTube

**Comment by ilyhalight** [comment]
> @ilyhalight спасибо, спас будем благодарны если расскажешь как без vpn убрать замедление YouTube

можно попробовать использовать какой-нибудь https://github.com/ValdikSS/GoodbyeDPI

**Comment by brz95** [comment]
@ilyhalight у меня Мак, он для Windows, через VPN не хотелось бы, так как VPN тоже замедляет скорость

**Comment by hrihoriart** [comment]
Да только сегодня вот заметил что перестал отображаться на ютубе значок перевода

**Comment by VitalySonko** [comment]
> Исправления без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js

И как воспользоваться этим исправлением?

**Comment by ilyhalight** [comment]
> > Исправления без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js
> 
> И как воспользоваться этим исправлением?

перейти по ссылке -> raw -> перезаписать

**Comment by VitalySonko** [comment]
> > > Исправления без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js
> > 
> > 
> > И как воспользоваться этим исправлением?
> 
> перейти по ссылке -> raw -> перезаписать

спасибо

**Comment by eviltracker** [comment]
Cloudflare-version 1.5.3.1 для AdGuard так же не работает, кнопки нет.

**Comment by ilyhalight** [comment]
> Cloudflare-version 1.5.3.1 для AdGuard так же не работает, кнопки нет.

Попробуйте версию предложенную выше

> https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js

**Comment by icorneli** [comment]
![image](https://github.com/user-attachments/assets/3d43139f-6664-4110-acbe-d5e409ef8de9)
в Brave не работает меню.

**Comment by icorneli** [comment]
1.6.0-beta.1 поставил, заработало, спасибо

**Comment by SergGrey** [comment]
> Фикс без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js

Не работает в Incognition
![image](https://github.com/user-attachments/assets/5316ce98-5608-4121-973d-8b15f334186e)

**Comment by ilyhalight** [comment]
> > Фикс без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js
> 
> Не работает в Incognition ![image](https://private-user-images.githubusercontent.com/30808171/354932969-5316ce98-5608-4121-973d-8b15f334186e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQ3NzYsIm5iZiI6MTcyMjg1NDQ3NiwicGF0aCI6Ii8zMDgwODE3MS8zNTQ5MzI5NjktNTMxNmNlOTgtNTYwOC00MTIxLTk3M2QtOGIxNWYzMzQxODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEwNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZTE4NDRlNjdhYzgxZWQ5ZjBhMzAwN2U5YmYzYWI5ZWQ2MjkzMTU2NWYyNmNhYmYyYmE0MWVmNTAyZDIzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iw7HkUKRRDTZwjc3jxAtZ27LTOB8jj_4R57XT4609M)

Проверьте что tampermonkey работает и скрипт активен. Проверил в 125 и все работает

**Comment by SergGrey** [comment]
> > > Фикс без отключения CSP - https://github.com/ilyhalight/voice-over-translation/blob/votjs-integration/dist/vot.user.js
> > 
> > 
> > Не работает в Incognition ![image](https://private-user-images.githubusercontent.com/30808171/354932969-5316ce98-5608-4121-973d-8b15f334186e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NTQ3NzYsIm5iZiI6MTcyMjg1NDQ3NiwicGF0aCI6Ii8zMDgwODE3MS8zNTQ5MzI5NjktNTMxNmNlOTgtNTYwOC00MTIxLTk3M2QtOGIxNWYzMzQxODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDEwNDExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmZTE4NDRlNjdhYzgxZWQ5ZjBhMzAwN2U5YmYzYWI5ZWQ2MjkzMTU2NWYyNmNhYmYyYmE0MWVmNTAyZDIzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4iw7HkUKRRDTZwjc3jxAtZ27LTOB8jj_4R57XT4609M)
> 
> Проверьте что tampermonkey работает и скрипт активен. Проверил в 125 и все работает

Установка Tampermonkey MV2 помогла, извините за лишнее беспокойство. В обычном Tampermonkey режим разработчика включал, так что не знаю в чём была проблема

**Comment by darg1n3c** [comment]
> Получилось повторить. Если работа расширения нужна прямо сейчас, то отключите CSP и все заработает. либо подождите фикса
> 
> Как это можно сделать показал ниже (отключает для всех сайтов, если нужно отключить только для ютуба, то используйте доп. расширения): ![изображение](https://private-user-images.githubusercontent.com/62353659/353954244-d162439d-c3b3-42c1-96d2-3000122dcf93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTQ0ODcsIm5iZiI6MTcyMjk1NDE4NywicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQyNDQtZDE2MjQzOWQtYzNiMy00MmMxLTk2ZDItMzAwMDEyMmRjZjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwY2FmYmVjYzc1MTRhNjc5NzY5OWQ0YTc3ODJlMTJmZDUxMTYxMzJjYzY4ZDM5ZWNlNzNjYzgxYmU3NmUxYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BD6LOgQs2O_A1T_zpa19KPeIBWzAuD55FJ7r7qJPKAY) ![изображение](https://private-user-images.githubusercontent.com/62353659/353954304-243b28b4-5218-4132-804d-4ef6610b589b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTQ0ODcsIm5iZiI6MTcyMjk1NDE4NywicGF0aCI6Ii82MjM1MzY1OS8zNTM5NTQzMDQtMjQzYjI4YjQtNTIxOC00MTMyLTgwNGQtNGVmNjYxMGI1ODliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE0MjMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzE5OGExNWFjMzNmOTUyOGM3YWMwMmU3YjU5NTBiYzlmMjk0MDMyMDZiNTRlMWY0NjUwM2NmYjU5YjliNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qvl2vZVO-vXIIbHkLrgMoT0vl9ttKGJHYlXlPI_8zQY)
где я могу изменить это, у меня тоже не работает

**Comment by ilyhalight** [comment]
Обновитесь до 1.6.0
