### ISSUE TITLE
Не появляется меню в ютубе на браузере Opera GX 

### ISSUE THREAD

**Issue by AlterRainytu** [ilyhalight/voice-over-translation#717]
### Operating system / Операционная система

Win 10 20H2

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

у меня не появлятся меню в самом ютубе но на удивление оно появляется в других местах:

https://github.com/user-attachments/assets/b9678072-17df-4727-b672-8eb85b266de8

### Additional information / Дополнительная информация

Как минимум заметил перевод на самом www.tampermonkey.net в самом же ютубе он не появлся вообще

**Comment by ilyhalight** [comment]
Дубликат #716
