### ISSUE TITLE
Перестал работать перевод загруженного видео на Яндекс.Диск, Мой Мир Видео (Mail.ru), Google Drive, VK > Мои Видео

### ISSUE THREAD

**Issue by rollingcookies** [ilyhalight/voice-over-translation#718]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Opera GX 109.0.5097.108

### Userscript manager / Скриптовый движок

Tampermonkey 5.1.6194

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

В сервисах (Я.Диск, Мой Мир Видео, Google Drive, VK > Мои Видео) перестал работать перевод, на кнопке скрипта переводчика красный текст: 

Возникла ошибка при переводе, попробуйте позже / Не удалось запросить перевод видео. / Доступ к видео ограничен

Попробовал версии скрипта:
1) https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot.user.js
2) https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/dist/vot-cloudflare.user.js
3) Из [комментария](https://github.com/ilyhalight/voice-over-translation/issues/716#issuecomment-2261143785) к проблеме https://kmi.aeza.net/Oe98gmKX69?hl

+ CSP в Tampermonkey включил, режим девелопера включил, AdBlocker отключил

Может есть другой видеохостинг, куда можно загрузить свое видео и перевод будет работать?

![Скриншот 01-08-2024 13 53 53](https://github.com/user-attachments/assets/571797ff-3084-42f6-bb40-9e42ae37d919)
![Скриншот 01-08-2024 13 53 32](https://github.com/user-attachments/assets/d0216f8b-b4a6-41c6-b750-a4c49614fcd3)

**Comment by ilyhalight** [comment]
Яндекс возвращает ошибку, от нас не зависит

**Comment by ilyhalight** [comment]
С ходу не назову такие видеохостинги, как вариант еще подойдут файловые хостинги, которые отдают прямую ссылку на файл, например catbox.moe (это не лучший вариант, ибо у них довольно плохо грузятся видео и нужно полностью отключать/удалять CSP).

> Ссылка где именно должна быть прямая - в строке браузера при открытии файла, но обычно же открывается веб-страница, в которой встроен видеоплеер и тогда работает кнопка скрипта перевода, но в адресной строке вряд ли будет прямая ссылка на видео? Или в этой странице встроенный видеоплеер должен обращаться к видео по прямой ссылке "http://.../*.mp4" ?

Либо в строке браузера - тогда кнопка сразу будет, либо другой вариант - нужно будет поискать прямую ссылку через девтулзы на странице с плеером и если она там есть, то открыть ее в отдельном окне, после чего в открытом окне будет кнопка перевода.

**Comment by ilyhalight** [comment]
> В сервисах (Я.Диск, Мой Мир Видео, Google Drive, VK > Мои Видео) перестал работать перевод, на кнопке скрипта переводчика красный текст:

Вы одно и тоже видео пытались переводить или разные? Такая ошибка "Возникла ошибка при переводе, попробуйте позже " так же может появляться, если не удается перевести конкретное видео, а не для всего сервиса. Проверил на яндекс диске, у меня там все нормально переводит

**Comment by rollingcookies** [comment]
> С ходу не назову такие видеохостинги, как вариант еще подойдут файловые хостинги, которые отдают прямую ссылку на файл, например catbox.moe (это не лучший вариант, ибо у них довольно плохо грузятся видео и нужно полностью отключать/удалять CSP).
> 
> 
> Либо в строке браузера - тогда кнопка сразу будет, либо другой вариант - нужно будет поискать прямую ссылку через девтулзы на странице с плеером и если она там есть, то открыть ее в отдельном окне, после чего в открытом окне будет кнопка перевода.

Видимо это работает только в Chrome, т.к. в Opera GX при попадании в адресную строку прямой ссылки на файл - файл начинается скачиваться сразу.

**Comment by rollingcookies** [comment]
> > В сервисах (Я.Диск, Мой Мир Видео, Google Drive, VK > Мои Видео) перестал работать перевод, на кнопке скрипта переводчика красный текст:
> 
> Вы одно и тоже видео пытались переводить или разные? Такая ошибка "Возникла ошибка при переводе, попробуйте позже " так же может появляться, если не удается перевести конкретное видео, а не для всего сервиса. Проверил на яндекс диске, у меня там все нормально переводит.

Да, сейчас попробовал другое видео и все хорошо переводится! Спасибоо! Попытался разобраться, в чем дело с тем видео, которое не переводилось. открыв его в MKVToolNix GUI, обнаружил, что видео содержало помимо дорожек видео и аудио, еще отдельную дорожку "Глобальные теги" (не знаю, что это значит, видимо какая-то meta-информация), удалил эту дорожку и заново перепаковал видео в формат .mkv. Загрузил его на Я.Диск и ... Все заработало, теперь и оно стало переводиться! 🙂

**Comment by MrDixioner** [comment]
> Попытался разобраться, в чем дело с тем видео, которое не переводилось. открыв его в MKVToolNix GUI, обнаружил, что видео содержало помимо дорожек видео и аудио, еще отдельную дорожку "Глобальные теги" (не знаю, что это значит, видимо какая-то meta-информация), удалил эту дорожку и заново перепаковал видео в формат .mkv. Загрузил его на Я.Диск и ... Все заработало, теперь и оно стало переводиться!

Мне не помогло. Тоже в видео были глобальные теги, перепаковал видео без них. Открываю через Яндекс.браузер. Ни на ютубе, ни в ВК, ни в самом яндексе видео не переводится, пишет "Ошибка: Видео не доступно для перевода". Бред какой то. А через скрипт в хроме пишет, что "Ошибка перевода, попробуйте позже". И так до бесконечности.

**Comment by rollingcookies** [comment]
> Мне не помогло. Тоже в видео были глобальные теги, перепаковал видео без них. Открываю через Яндекс.браузер. Ни на ютубе, ни в ВК, ни в самом яндексе видео не переводится, пишет "Ошибка: Видео не доступно для перевода". Бред какой то. А через скрипт в хроме пишет, что "Ошибка перевода, попробуйте позже". И так до бесконечности.

Да, через какое-то время этот способ перестал работать и у меня. Пока не нашел идеального решения для удобного перевода локальных видео. Надеюсь пофиксят этот баг и перевод с ЯндексДиска заработает.
