### ISSUE TITLE
Перевод с learning.sap.com

### ISSUE THREAD

**Issue by Aleksey-Ivanov** [ilyhalight/voice-over-translation#719]
### Describe your feature / Опишите ваше предложение

Можно ли сделать закадровый перевод с этого ресурса learning.sap.com?
Или есть возможность подсказать как это можно сделать, может как-то через настройки?

Спасибо за то, что уже сделали. Очень крутой плагин, спасибо уже за проделанную работу!

**Comment by ilyhalight** [comment]
Добавлено
