### ISSUE TITLE
chrome не работает

### ISSUE THREAD

**Issue by littledoggi** [ilyhalight/voice-over-translation#721]
### Operating system / Операционная система

windows 10 

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Полностью перестал работать на браузере Chrome, проверил на новом чистом профиле.

**Comment by ilyhalight** [comment]
эта версия работает?

https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js

**Comment by h2p** [comment]
> эта версия работает?
> 
> https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js

This version works, thanks
