### ISSUE TITLE
Переводит ЮТ только в инкогнито

### ISSUE THREAD

**Issue by Fan4eGGG** [ilyhalight/voice-over-translation#723]
### Operating system / Операционная система

win 10 22h2

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

не работает только в ЮТ перевод - не появляется кнопка, но если открыть ют в инкогнито - то кнопка появляется. расширения все отключал, менеджер менял и на легаси и с магаза хром качал и с оперы, ставил cloudflare версию - не появляется. опера не обновлялась, просто за сутки пропала возможность перевода.

**Comment by MixxxGit** [comment]
Подтверждаю! У меня перестал работать инжект через ADguard, кнопка перевести просто не появляется. Если выйти из акка то всё окей.

**Comment by VadimLL** [comment]
Да, сегодня вдруг перестал (1.5.3.1) работать в моей опере (Opera One версия: 112.0.5197.39) - просто не показываю кнопку на которую нужно нажать чтобы перевести.

Открытие видео в приватном окне (или что [Fan4eGGG] имеет ввиду под инкогнито?) не помогает - также нет кнопки.

**Comment by ZigorewsLike** [comment]
Также не появляется кнопка. Браузер выдаёт ошибку 
`userscript.html?name=%255BVOT%255D-Voice-Over-Translation.user.js&id=8876640a-dc82-4991-b25d-14e42978b729:8 This document requires 'TrustedScript' assignment.`

Возможно связанно с безопасностью использования `eval`, как подсказывает сам браузер:
![image](https://github.com/user-attachments/assets/8b0eb7f0-6bb5-4c41-8c20-e948f7224785)

**Comment by ANIMka** [comment]
Аналогично. Работает, только если разлогиниться.
Cent Browser 5.1.1130.129 x64 (Chromium 118.0.5993.159)

**Comment by SashaXser** [comment]
[Переустановите (кликабельно)](https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js)

**Comment by Fan4eGGG** [comment]
> [Переустановите (кликабельно)](https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js)

починилось, пасиба.

**Comment by VadimLL** [comment]
"Ура, заработало!" )
