### ISSUE TITLE
не отображается кнопка

### ISSUE THREAD

**Issue by harmoff** [ilyhalight/voice-over-translation#724]
### Operating system / Операционная система

Windows 10 2H20

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

не отображается кнопка переводчика

### Additional information / Дополнительная информация

скриншоты ошибок: https://i.imgur.com/v3LUp0f.jpeg

**Comment by SashaXser** [comment]
[Переустановите (кликабельно)](https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js)

**Comment by avigdorsky** [comment]
Такая же проблема была.

**Comment by nuarejazz** [comment]
Такая же проблема.

**Comment by harmoff** [comment]
> [Переустановите (кликабельно)](https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js)
что делать с этим файлом вообще

**Comment by vadimkiryanov** [comment]
> [Переустановите (кликабельно)](https://github.com/ilyhalight/voice-over-translation/raw/votjs-integration/dist/vot.user.js)

Спасибо, это помогло
