### ISSUE TITLE
Не найден идентификатор (ID) видео

### ISSUE THREAD

**Issue by harmoff** [ilyhalight/voice-over-translation#725]
### Operating system / Операционная система

Windows 10 2H20

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

не работает перевод, не находит id
дословный текст ошибки в названии топика

### Additional information / Дополнительная информация

скриншот прикрепляю: https://i.imgur.com/Q9EVAO0.jpeg

**Comment by ilyhalight** [comment]
по скриншоту похоже на то, что просто не прогрузился скрипт. В консоли что-то есть?

**Comment by ilyhalight** [comment]
Проверьте в 1.6.0, если что переоткройте
