### ISSUE TITLE
Исчезло окно перевода

### ISSUE THREAD

**Issue by Polydick** [ilyhalight/voice-over-translation#729]
### Operating system / Операционная система

Windows 10 Pro 22H2

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Раньше окно перевода было однако уже я его не вижу даже после перезапуска браузера

### Additional information / Дополнительная информация

![изображение_2024-08-07_012321240](https://github.com/user-attachments/assets/7f7b7eea-2f54-4dec-a78e-7e88ee533202)

**Comment by ilyhalight** [comment]
Обновитесь до 1.6.0

**Comment by Polydick** [comment]
оно не обновляется автоматически

**Comment by ilyhalight** [comment]
> оно не обновляется автоматически

старый скрипт нужно удалить и поставить новую версию т.к. у вас cloudflare версия, которая была объединена в этом обновление с основной версией скрипта

![изображение](https://github.com/user-attachments/assets/db3a236c-8796-443f-b0a6-32e1e5695617)
