### ISSUE TITLE
Не всплывает кнопка "перевести" только на ютубе. Раньше все работало.

### ISSUE THREAD

**Issue by okgo2012** [ilyhalight/voice-over-translation#730]
### Operating system / Операционная система

MacOs 14.6

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

В браузерах хром, опера перестало всплывать окно скрипта, с кнопкой перевода. Именно на Ютубе. На рутубе, в вк кнпока всплывает и скрипт всё переводит. Попробовал отключить все другие расширения, которые стоят в браузере - не помогло. В яндекс браузере кнопка на юутбе всплывает и работает. Раньше скрипт работал отлично, пользовался постоянно, автору респект

**Comment by Trapezze** [comment]
Подтверждаю. На винде 10 Edge так же - исчезла кнопка перевода

**Comment by SiTiROS** [comment]
да на хроме тоже перестало, вот сегодня только! что делать? как быть?

**Comment by SiTiROS** [comment]
надо обновиться - после обновления проблема исправлена, спасибо!

**Comment by Trapezze** [comment]
да мною уже было обновлено всё. Не помогло


> надо обновиться - после обновления проблема исправлена, спасибо!

**Comment by ilyhalight** [comment]
Обновитесь до 1.6.0, если уже стоит эта версия скиньте логи консоли

**Comment by okgo2012** [comment]
> Обновитесь до 1.6.0, если уже стоит эта версия скиньте логи консоли

Не подскажешь, как это сделать?

**Comment by okgo2012** [comment]
Спасибо, обновился. Странно, пришлось удалить сперва, чтобы он установил новую версию в Tampermonkey
