### ISSUE TITLE
Не появляется кнопка "Перевести" на Reddit.

### ISSUE THREAD

**Issue by Post1rony** [ilyhalight/voice-over-translation#732]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.0

### Describe the bug / Опишите ошибку

Не появляется кнопка "Перевести" ни на https://www.reddit.com/, ни на https://new.reddit.com/, ни на https://old.reddit.com/.

**Comment by ilyhalight** [comment]
Временно перенес функционал на old.reddit.com, обновитесь

**Comment by Post1rony** [comment]
> Временно перенес функционал на old.reddit.com, обновитесь

На old.reddit.com кнопка появилась, но после нажатия через какое-то время пишет "Возникла ошибка при переводе, попробуйте позже".

**Comment by ilyhalight** [comment]
> но после нажатия через какое-то время пишет "Возникла ошибка при переводе, попробуйте позже".

Еще раз обновитесь, исправил ошибку

**Comment by Post1rony** [comment]
> Еще раз обновитесь, исправил ошибку

Теперь вроде как переводит, появляется синяя надпись "отключить", звук оригинала приглушается, но самого голоса перевода нет. Тишина, только приглушенная оригинальная дорожка.

**Comment by ARBURIUS** [comment]
@Post1rony зайди chrome://flags напиши в поиске csp. И в строке Isolated sandboxed iframes выбери из выпадающего списка Disabled. Должно запахать

**Comment by Post1rony** [comment]
> зайди chrome://flags напиши в поиске csp. И в строке Isolated sandboxed iframes выбери из выпадающего списка Disabled. Должно запахать после перезапуска.

Появился звук, и после того как вернул это обратно звук не пропал, хотя до этого на 3 видео проверял, звука не было.
