### ISSUE TITLE
Не работает перевод в Arc Browser (Windows 10)

### ISSUE THREAD

**Issue by GoGagoo** [ilyhalight/voice-over-translation#734]
### Operating system / Операционная система

Windows 10, 22H2

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6

### Describe the bug / Опишите ошибку

WOT не работает на Arc Browser, в частности, на Youtube. Хотя этот браузер на базе Chromium.
![photo_2024-08-08_10-32-42](https://github.com/user-attachments/assets/aa6d7cee-f167-4de1-90f4-2b41d5ab6125)

**Comment by nimbus2332** [comment]
Плюсую, не появляется кнопка, у меня Edge. версия 1.5.3.1

**Comment by gaxeliy** [comment]
Перестала появляться кнопка перевода. Linux Fedora, Google Chrome.
Видимо, общая проблема.

**Comment by ilyhalight** [comment]
До 1.6.0 обновитесь
