### ISSUE TITLE
Не появляется кнопка перевода видео на Гугл диске.

### ISSUE THREAD

**Issue by Post1rony** [ilyhalight/voice-over-translation#737]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.0

### Describe the bug / Опишите ошибку

После обновления на 1.6.0 не появляется кнопка перевода на Гугл диске, на 1.5.3.1 тоже уже не появляется.

**Comment by ilyhalight** [comment]
Исправил
