### ISSUE TITLE
Не работают субтитры

### ISSUE THREAD

**Issue by DarkKalkor** [ilyhalight/voice-over-translation#739]
### Operating system / Операционная система

Windows 11 Pro 23H2 Сборка OC: 22631.3958 Взаимодействие: Windows Feature Experience Pack 1000.22700.1026.0

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

Последняя самая

### Describe the bug / Опишите ошибку

Видео переводиться, а вот субтитры не появляются. У меня раньше не работал перевод ваш как субтитры так и голос без впн, теперь все работает кроме субтитров. На любом видео не показывает субтитры. https://ru.files.fm/u/p43bekurk7 (видео с доверенного источника) и второе: https://ru.files.fm/u/zyeebcvzxf 

### Additional information / Дополнительная информация

Я с Украины, поэтому наверное и не работают субтитры. хз

**Comment by SashaXser** [comment]
> Я с Украины, поэтому наверное и не работают субтитры. хз

Да, ваш провайдер блокирует доступ к brosubs.s3-private.mds.yandex.net, так как ресурс размещён на российском IP-адресе. @ilyhalight добавь проксирование субтитров.

**Comment by ilyhalight** [comment]
> > Я с Украины, поэтому наверное и не работают субтитры. хз
> 
> Да, ваш провайдер блокирует доступ к brosubs.s3-private.mds.yandex.net, так как ресурс размещён на российском IP-адресе. @ilyhalight добавь проксирование субтитров.

Добавил

**Comment by DarkKalkor** [comment]
> > > Я с Украины, поэтому наверное и не работают субтитры. хз
> > 
> > 
> > Да, ваш провайдер блокирует доступ к brosubs.s3-private.mds.yandex.net, так как ресурс размещён на российском IP-адресе. @ilyhalight добавь проксирование субтитров.
> 
> Добавил

Досих пор не работают субтитры  @ilyhalight Только что переустанавливал скрипт через гит хаб, в итоге ничего не изменилось(если что стрими переводились до етого только с впн, поэтому субтитры должни работать) Видео: https://ru.files.fm/u/gn7sh9h59s

**Comment by ilyhalight** [comment]
> > > > Я с Украины, поэтому наверное и не работают субтитры. хз
> > > 
> > > 
> > > Да, ваш провайдер блокирует доступ к brosubs.s3-private.mds.yandex.net, так как ресурс размещён на российском IP-адресе. @ilyhalight добавь проксирование субтитров.
> > 
> > 
> > Добавил
> 
> Досих пор не работают субтитры @ilyhalight Только что переустанавливал скрипт через гит хаб, в итоге ничего не изменилось(если что стрими переводились до етого только с впн, поэтому субтитры должни работать) Видео: https://ru.files.fm/u/gn7sh9h59s

В консоли что-то пишет после первой активации субтитров?

**Comment by DarkKalkor** [comment]
> > > > > Я с Украины, поэтому наверное и не работают субтитры. хз
> > > > 
> > > > 
> > > > Да, ваш провайдер блокирует доступ к brosubs.s3-private.mds.yandex.net, так как ресурс размещён на российском IP-адресе. @ilyhalight добавь проксирование субтитров.
> > > 
> > > 
> > > Добавил
> > 
> > 
> > Досих пор не работают субтитры @ilyhalight Только что переустанавливал скрипт через гит хаб, в итоге ничего не изменилось(если что стрими переводились до етого только с впн, поэтому субтитры должни работать) Видео: https://ru.files.fm/u/gn7sh9h59s
> 
> В консоли что-то пишет после первой активации субтитров?

Заработало, как то запоздало. Все гуд
