### ISSUE TITLE
Перевод скачанных фильмов и сериалов?

### ISSUE THREAD

**Issue by Atashka56** [ilyhalight/voice-over-translation#74]
Здравствуйте. Скажите пожалуйста, возможно ли как нибудь сделать или куда нибудь загрузить скаченный видео файл на английском языке и чтоб потом его перевёл и озвучил Яндекс нейросеть? Возможно ли таким способом озвучивать фильмы и сериалы на английском языке? На Ютуб не вариант, так как он сразу удаляет из-за авторских прав.

**Comment by mynovelhost** [comment]
vimeo, 9gag, vk, xvideos, pornhub
