### ISSUE TITLE
Нету кнопки меню на YouTube

### ISSUE THREAD

**Issue by Demosand** [ilyhalight/voice-over-translation#742]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

На ютубе пропала кнопка меню скрипта, не понял почему пропала. На всех остальных сайтах есть функция перевода с меню и так далее.  Но на ютубе кнопки нету. Что делать? Переустановка не помогла
![image](https://github.com/user-attachments/assets/b3dd3fe8-0a56-4b49-8398-e66c72cc3baf)
![image](https://github.com/user-attachments/assets/d1746692-b2e2-4fc6-931d-eeee40c41052)
Не знаю что именно связано в консоли с скриптом по этому прикрепил всю консоль

**Comment by brat4ikk** [comment]
нет кнопки перевода

**Comment by ilyhalight** [comment]
Обновитесь до 1.6.0

**Comment by brat4ikk** [comment]
1.6.0 уже стоит

**Comment by ilyhalight** [comment]
> 1.6.0 уже стоит

попробуй как тут сделать #741
