### ISSUE TITLE
Добавьте сайт livepush.io (или любой другой плеер HLS и MP4)

### ISSUE THREAD

**Issue by Smorvel** [ilyhalight/voice-over-translation#743]
Добавьте поддержку https://livepush.io/hls-player/index.html чтобы можно было самому вставить любое m3u8 или mp4 видео и получить перевод.

Кстати я попробовал включить перевод прямо открыв mp4 и оно почему-то не сработало..
![image](https://github.com/user-attachments/assets/38356913-72ee-4031-b903-1bcd5874d076)

**Comment by ilyhalight** [comment]
> Кстати я попробовал включить перевод прямо открыв mp4 и оно почему-то не сработало..

Как ссылка выглядит? Если это локальный файл, то естественно, он не будет переводиться

> чтобы можно было самому вставить любое m3u8 

Перевода любых m3u8 не будет

**Comment by Smorvel** [comment]
Файл не локальный, для теста вытащил mp4 отсюда и попытался перевести на английский https://filmix.fm/films/drama/173011-hozyayka-gory-2024.html

Почему любых m3u8 не будет? от чего зависит?
например я хочу этот перевести он идет 40 минут https://universal-vod.daserste.de/i/int/2024/04/16/4e3e7e2b-491b-4219-ad97-469b3773245c/,JOB_461373_sendeton_640x360-50p-1200kbit,JOB_461373_sendeton_480x270-50p-700kbit,JOB_461373_sendeton_960x540-50p-1600kbit,JOB_461373_sendeton_1280x720-50p-3200kbit,JOB_461373_sendeton_1920x1080-50p-5000kbit,.mp4.csmil/master.m3u8
как это сделать?

**Comment by ilyhalight** [comment]
> Файл не локальный, для теста вытащил mp4 отсюда и попытался перевести на английский https://filmix.fm/films/drama/173011-hozyayka-gory-2024.html

скорее всего, или у них на сдне заблокированы айпи яндекса, либо наоборот (либо вовсе все рф айпи заблокированы)

> Почему любых m3u8 не будет? от чего зависит?

1) если разрешить любые m3u8 - то это будет занимать слишком много места
2) непонятно как нормально проверять бесконечный ли это m3u8 + проверять длину видео до начала конвертации

**Comment by ilyhalight** [comment]
> Хм, понятно. Ну тогда видимо тему можно закрывать.. А я могу как-то сам, без скрипта, на прямую скормить яндексу нужный мне mp4 и m3u8 и получить перевод?

перевести mp4 можно через [vot-cli](https://github.com/FOSWLY/vot-cli), либо можно использовать библиотеку [vot.js](https://github.com/FOSWLY/vot.js), чтобы самому сделать нужную обертку над апи яндекса
m3u8 нужно конвертировать в mp4, залить куда-нибудь и дальше действия, такие же, как для обычного mp4

**Comment by DearFox** [comment]
> скорее всего, или у них на сдне заблокированы айпи яндекса, либо наоборот (либо вовсе все рф айпи заблокированы)

Загрузил видос на свой собственный сайт, который за клаудфлеером. Яндекс всё равно не хочет переводить видос по прямой ссылке типа: `https://example.com/video.mp4`
Есть какие-то доп требования?

**Comment by DearFox** [comment]
> > скорее всего, или у них на сдне заблокированы айпи яндекса, либо наоборот (либо вовсе все рф айпи заблокированы)
> 
> Загрузил видос на свой собственный сайт, который за клаудфлеером. Яндекс всё равно не хочет переводить видос по прямой ссылке типа: `https://example.com/video.mp4` Есть какие-то доп требования?

Ладно, хаха, на самом деле у меня видео называлось `SPAI_M01L01T01 - The Pipeline [1078360924].mp4` и я просто заметил, что в консоли при попытке перевести видео - ссылка на видео обрезается до `SPAI_M01L01T01 - The Pipeline` а остальная часть ссылки остаётся просто текстом. Я просто переименовал файл убрав все пробелы и спец символы и это сработало.
