### ISSUE TITLE
Озвучка начинаетца сначала при остановке, перемотке, или других действиях с видео и не соответсвует видео ряду 

### ISSUE THREAD

**Issue by TrimKaslana** [ilyhalight/voice-over-translation#744]
### Operating system / Операционная система

10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6

### Describe the bug / Опишите ошибку

При просмотре видео в один момент я вышел из хрома и когда зашол повторна продолжел воспроизведение на моменте где я закончил но заместь нужного аудио ряда я услышал начало видео и так при перемотке остановке и повторному воспроизведению и так со всеми видео которые переводятца вашым дополнением. Помогите решыть мою проблему

### Additional information / Дополнительная информация

когда я начал пользоватца етим преводом каждый раз при переводе видо мне преходилось ждать пару менут но после 3, 1 часового ролика я перестал видеть прозьбу подождать, но я не уверен што в етом и есть проблема

**Comment by ilyhalight** [comment]
исправил, перезагрузи страницу

**Comment by TrimKaslana** [comment]
спасибо все работает. И благодарю вас за столь прекрасную функцыю вы спасли мое лето:3
