### ISSUE TITLE
Не появляется кнопка "Перевести  на ютубе

### ISSUE THREAD

**Issue by brat4ikk** [ilyhalight/voice-over-translation#749]
### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

161

### Describe the bug / Опишите ошибку

Не появляется кнопка "Перевести  на ютубе

### Additional information / Дополнительная информация

Yandex

**Comment by Ars-Mond** [comment]
Добрый день.
Тоже пропала кнопка перевода на YouTube.
Tampermonkey. Версия скрипта: 1.6.1. Браузер: Firefox.

**Comment by ilyhalight** [comment]
Есть какие-то ошибки в консоли?

**Comment by Ars-Mond** [comment]
![image](https://github.com/user-attachments/assets/58275d17-75d6-4541-8cb9-bc34a8c11863)

**Comment by Ars-Mond** [comment]
![image](https://github.com/user-attachments/assets/e0c04e8d-9cef-49cd-8b0e-17d781601089)

**Comment by ilyhalight** [comment]
> ![image](https://private-user-images.githubusercontent.com/39434601/357211663-e0c04e8d-9cef-49cd-8b0e-17d781601089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTk2OTUsIm5iZiI6MTcyMzQ5OTM5NSwicGF0aCI6Ii8zOTQzNDYwMS8zNTcyMTE2NjMtZTBjMDRlOGQtOWNlZi00OWNkLThiMGUtMTdkNzgxNjAxMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZGNmZGRjNjA3MjI2YWQ2ODEyMzA1NWUxNjE5NzMwMjYxZTNmZjE5NjY2MjU4OTMzN2U2NWQyODVlZmQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmfKY6M8S8Nn-ejodcprVTkepYxR1s8tPiUdKi2Vn5k)

Проверьте, что в флагах браузера у вас включен `dom.webaudio.enabled` (стоит значение **true**). Найти флаги можно в about:config

**Comment by AlexDon228** [comment]
Доброго времени суток.
Прошивка Hyper OS, 14 android.
Браузер Kiwi.
В расширениях режим разработчика включен.

1. Установил расширение Tampermonkey v5.2.3.
Установил скрипт v1.6.1.
В YouTube да и на других сайтах кнопка перевода не появляется.

2. Установил расширение Tampermonkey Legacy v5.1.1.
Установил скрипт v1.6.1.
Все отлично работает.

Можно ли как-то починить скрипт в расширении Tampermonkey v5.2.3.

**Comment by Ars-Mond** [comment]
> > ![image](https://private-user-images.githubusercontent.com/39434601/357211663-e0c04e8d-9cef-49cd-8b0e-17d781601089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTk2OTUsIm5iZiI6MTcyMzQ5OTM5NSwicGF0aCI6Ii8zOTQzNDYwMS8zNTcyMTE2NjMtZTBjMDRlOGQtOWNlZi00OWNkLThiMGUtMTdkNzgxNjAxMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZGNmZGRjNjA3MjI2YWQ2ODEyMzA1NWUxNjE5NzMwMjYxZTNmZjE5NjY2MjU4OTMzN2U2NWQyODVlZmQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmfKY6M8S8Nn-ejodcprVTkepYxR1s8tPiUdKi2Vn5k)
> 
> Проверьте, что в флагах браузера у вас включен `dom.webaudio.enabled` (стоит значение **true**). Найти флаги можно в about:config

Добрый день,
Почему тогда раньше работало?

**Comment by ilyhalight** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/39434601/357211663-e0c04e8d-9cef-49cd-8b0e-17d781601089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTk2OTUsIm5iZiI6MTcyMzQ5OTM5NSwicGF0aCI6Ii8zOTQzNDYwMS8zNTcyMTE2NjMtZTBjMDRlOGQtOWNlZi00OWNkLThiMGUtMTdkNzgxNjAxMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZGNmZGRjNjA3MjI2YWQ2ODEyMzA1NWUxNjE5NzMwMjYxZTNmZjE5NjY2MjU4OTMzN2U2NWQyODVlZmQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmfKY6M8S8Nn-ejodcprVTkepYxR1s8tPiUdKi2Vn5k)
> > 
> > 
> > Проверьте, что в флагах браузера у вас включен `dom.webaudio.enabled` (стоит значение **true**). Найти флаги можно в about:config
> 
> Добрый день, Почему тогда раньше работало?

Возможно, использовали старую версию расширения. До 1.6.0 webaudio не использовался расширением

**Comment by ilyhalight** [comment]
> Доброго времени суток. Прошивка Hyper OS, 14 android. Браузер Kiwi. В расширениях режим разработчика включен.
> 
>     1. Установил расширение Tampermonkey v5.2.3.
>        Установил скрипт v1.6.1.
>        В YouTube да и на других сайтах кнопка перевода не появляется.
> 
>     2. Установил расширение Tampermonkey Legacy v5.1.1.
>        Установил скрипт v1.6.1.
>        Все отлично работает.
> 
> 
> Можно ли как-то починить скрипт в расширении Tampermonkey v5.2.3.

Попереключайте режим разработчика, тамперманки иногда не хочет обнаруживать режим разработчика с первого раза

**Comment by Ars-Mond** [comment]
Полсле проверке выяснил что работает у меня идеально на версии: [1.5.3.1](https://github.com/ilyhalight/voice-over-translation/releases/tag/1.5.3.1).
Я опасаюсь что api yandex может изменится. И я не смогу перейти на другую версию скрита при обновлении, так как браузером управляет организация. Мне крайне повезло что здесь стоит Tampermonkey для скриптов организации.

**Comment by ilyhalight** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/39434601/357211663-e0c04e8d-9cef-49cd-8b0e-17d781601089.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0OTk2OTUsIm5iZiI6MTcyMzQ5OTM5NSwicGF0aCI6Ii8zOTQzNDYwMS8zNTcyMTE2NjMtZTBjMDRlOGQtOWNlZi00OWNkLThiMGUtMTdkNzgxNjAxMDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDIxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3ZGNmZGRjNjA3MjI2YWQ2ODEyMzA1NWUxNjE5NzMwMjYxZTNmZjE5NjY2MjU4OTMzN2U2NWQyODVlZmQ3MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QmfKY6M8S8Nn-ejodcprVTkepYxR1s8tPiUdKi2Vn5k)
> > > > 
> > > > 
> > > > Проверьте, что в флагах браузера у вас включен `dom.webaudio.enabled` (стоит значение **true**). Найти флаги можно в about:config
> > > 
> > > 
> > > Добрый день, Почему тогда раньше работало?
> > 
> > 
> > Возможно, использовали старую версию расширения. До 1.6.0 webaudio не использовался расширением
> 
> ~Можно ли отключить или модифицировать скрипт так что бы от не использовал webaudio?~
> 
> P.s. Не могу изменить конфиг так, как регулируется настройками user.js и после перезапуска слетают конфиги. Тут стоит что-то наподобие: [Narsil](https://git.nixnet.services/Narsil)/[desktop_user.js](https://git.nixnet.services/Narsil/desktop_user.js).

Исправил, теперь, должно работать.

**Comment by ilyhalight** [comment]
Если у ТСа, все еще, есть какие-то проблемы с появлением, то переоткройте тему и приложите логи
