### ISSUE TITLE
Нету кнопки меню на YouTube

### ISSUE THREAD

**Issue by Ars-Mond** [ilyhalight/voice-over-translation#750]
### Operating system / Операционная система

Windows 11 22H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Нету кнопки на YouTube. Переустановил скрипт заного, не помогло, всё равно кнопка не появляется.

**Comment by ilyhalight** [comment]
Лучше предоставьте логи консоли, а не создавайте дубликаты

**Comment by Ars-Mond** [comment]
![image](https://github.com/user-attachments/assets/04708bdc-a7ee-426e-9bd0-b9b52c7f9bc0)
