### ISSUE TITLE
The audio format is not supported, or you need to open the audio in a new tab

### ISSUE THREAD

**Issue by utilop** [ilyhalight/voice-over-translation#751]
### Operating system / Операционная система

Windows 11 23H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3.1

### Describe the bug / Опишите ошибку

Mainly on this site xv-ru.com, because this is the only site of this type available to me (without VPN))) But it also takes a long time to load.
 In short, to hear the translation, you need to open it in a new tab. In the other case, there seems to be a translation, and the main sound is muffled, but the translation is not audible. You have to open the audio page and sync 😭
Rarely writes the audio format is not supported as a screenshot, but the translation on the tab is available. It is very rare that there is an empty path. All this could be specific to the operation of the site in my country (I already said that the page often takes a long time to load) or an error?
 The browser does not matter, I use both edge and firefox. 
 
![изображение](https://github.com/user-attachments/assets/fe97eb41-4a22-489a-9c22-5544f4291425)

### Additional information / Дополнительная информация

 By the way, I was never able to translate on sites where access is via VPN

**Comment by ilyhalight** [comment]
try using 1.6.1 version

**Comment by utilop** [comment]
@ilyhalight Everything is the same

**Comment by ilyhalight** [comment]
> @ilyhalight Everything is the same

Follow these [instructions](https://github.com/ilyhalight/voice-over-translation/wiki/%5BEN%5D-FAQ#when-activating-the-translation-it-says-the-audio-format-is-not-supported-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%B0%D1%83%D0%B4%D0%B8%D0%BE-%D0%BD%D0%B5-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F), but select "Delete completely" instead of "Yes"

**Comment by utilop** [comment]
@ilyhalight Ok, thanks. Just wanted to report a bug.
