### ISSUE TITLE
Не поддерживается перевод Twitch

### ISSUE THREAD

**Issue by G1ZMO** [ilyhalight/voice-over-translation#752]
### Operating system / Операционная система

Windows 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Нет окна перевода прямых трансляций, или записей VOD. 
Вроде бы в описании указано, что поддерживается twitch, но по факту нет.

**Comment by ilyhalight** [comment]
![firefox_r6ZjLSccGZ](https://github.com/user-attachments/assets/77c798ad-1e2b-485c-b7c9-2541f6ed1adc)
