### ISSUE TITLE
Выбор голоса озвучки

### ISSUE THREAD

**Issue by oxalates** [ilyhalight/voice-over-translation#758]
### Describe your feature / Опишите ваше предложение

Вопрос: можно ли реализовать выбор голоса озвучки? Я заметил, что на youtube голос один, а при открвании того же видео на vk, то голос другой. Я думаю, что это связано с тем, что в вк отсутствуют субтитры. И если на ютюбе видео без субтитров, то голос тоже меняется.

**Comment by ilyhalight** [comment]
Не получится, вся логика, связанная с озвучкой происходит на серверах яндекса и как-то вручную на это повлиять нельзя
