### ISSUE TITLE
Опять не работает переводчик.

### ISSUE THREAD

**Issue by DarkKalkor** [ilyhalight/voice-over-translation#766]
### Operating system / Операционная система

Windows 11 23H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

Самая последняя

### Describe the bug / Опишите ошибку

перевод не работает, кстати я заметил что если я ставлю украинский перевод(меню яндекса) то появляеться какой то новый пункт там есть выбор deepl или yandex, я проверял два типа и никакой не работает. И на русском языке меню тоже пробовал не работает.

### Additional information / Дополнительная информация

Видео: https://ru.files.fm/u/mgc7mk83rz

**Comment by solumthenight** [comment]
Хром, ютуб - работает, яндекс диск - значок синий, но перевода нет, гугл драйв - пишет попробуйте позже

**Comment by DarkKalkor** [comment]
> Что-то пишет в консоли после активации перевода?

Каким то чудом все заработало сегодня XD

**Comment by ilyhalight** [comment]
> Хром, ютуб - работает, яндекс диск - значок синий, но перевода нет, гугл драйв - пишет попробуйте позже

для яндекс диска нужно удалять csp через тамперманки/любое другое расширение, которое позволяет это сделать

**Comment by solumthenight** [comment]
> > Хром, ютуб - работает, яндекс диск - значок синий, но перевода нет, гугл драйв - пишет попробуйте позже
> 
> для яндекс диска нужно удалять csp через тамперманки/любое другое расширение, которое позволяет это сделать

Сработало для яндекса, но после сбрасывания настроек и повторной установки скрипта, яндекс заработал и без танцев с бубнами, но плюс ещё изменилась иконка, раньше она  была столбиком в правой части, а теперь строкой посередине сверху... Гугл драйв как не работал, так и не работает. ![chrome_wztLfvbBiR](https://github.com/user-attachments/assets/945356b6-9dd1-4ba9-b5fd-4df9697513be)

**Comment by ilyhalight** [comment]
> плюс ещё изменилась иконка, раньше она была столбиком в правой части, а теперь строкой посередине сверху...

Вы ее сами перенесли в правую часть плеера. После переустановки расширения настройки сбросились и она стала по умолчанию - по центру

> ... Гугл драйв как не работал, так и не работает.

Значит, у Яндекса, сейчас, какие-то проблемы с загрузкой из этого сервиса

**Comment by ilyhalight** [comment]
пока закрою, переоткройте, если повторится снова и вы сможете предоставить логи консоли
