### ISSUE TITLE
Yandex Disk

### ISSUE THREAD

**Issue by solumthenight** [ilyhalight/voice-over-translation#769]
### Describe your feature / Опишите ваше предложение

Большая просьба - добавить вариант со ссылками /d/,  Яндекс автоматически выставляет либо  /d/ ,  либо  /i/ - приходится заново генерировать ссылку, плюс сделайте, пожалуйста, возможность работать через папку, делать на каждое видео отдельную ссылку не очень удобно. Папки тоже работают через /d/.

**Comment by ilyhalight** [comment]
#735
