### ISSUE TITLE
Failed to request create session

### ISSUE THREAD

**Issue by PPVLV** [ilyhalight/voice-over-translation#772]
### Operating system / Операционная система

Windows 7 Ultimate x64

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

![Снимок](https://github.com/user-attachments/assets/bf2f2abf-a566-4199-943d-a5829f2ef3d6)
Что-то перестало работать на Youtube, выдаёт вот такую ошибку.

**Comment by PPVLV** [comment]
Снёс **1.6.1** и установил **1.5.3.1** и всё заработало! **Больше не буду обновляться вообще!** )) (пока не сломается)

**Comment by Myrakami** [comment]
Скорей всего связано со сбоем у российских провайдеров, телега также не работала.

**Comment by sergreukorolenko** [comment]
win 11 23H2 можно как-то исправить ?

**Comment by OIvanK** [comment]
> Скорей всего связано со сбоем у российских провайдеров, телега также не работала.

В Вк версия 1.6.1 не работает, а 1.5.3.1 работает

**Comment by Myrakami** [comment]
> > Скорей всего связано со сбоем у российских провайдеров, телега также не работала.
> 
> Я прямо сейчас это проверял. С телеграмом 10-15мин назад не было никаких проблем, а с переводом было. Как только переусановил старую версию, заработало СРАЗУ, значит дело таки не совсем в этом.

На последней версии уже тоже работает на ютубе.

**Comment by Gothicmp4** [comment]
Просто обновите на последнюю версию, желательно удалить всё и скачать заново

**Comment by Ardor98** [comment]
Помог прокси vot-worker.kload.workers.dev

*Режим проксирование у меня стоит - "Проксировать все"
*Сервис перевода текста - "Яндекс Браузер"
*Сервис определения языка - "Яндекс Браузер"
(Возможно эти три настройки тоже влияют)
