### ISSUE TITLE
Ошибка: Доступ к видео ограничен

### ISSUE THREAD

**Issue by souljahwitchfaith** [ilyhalight/voice-over-translation#773]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Попытался скачать и обрезать видео с ютуба, чтобы избежать лимита времени закадрового перевода. Использовал 2 платформы для загрузки видео Ютуб и Гугл Диск. В двух платформах видео были в открытом доступе, но все равно переводчик отказался работать. Куда я могу залить видео чтобы оно воспроизводилось с переводчиком?

**Comment by ilyhalight** [comment]
Значит как-то не так залили.

Можете попробовать vimeo, mail.ru, vk, ok, rutube

**Comment by Aewcom** [comment]
Проблема все еще актуальна.
Загрузил видео на ютуб. Сделал доступ по ссылке. Нажимаю перевод- выдает эту ошибку. Немного подождал (1-2 часа) и перевод начал работать для всех остальных загруженных видео, а то на которое нажал изначально- ошибка сохранилась.
Для чистоты эксперемента- запустил это видео в другом браузере и оно переводиться (а в изначально сохраняется ошибка). 
Я без понятия в чем может быть проблема. Такое чувство, что он подгружает информацию из кэша.

**Comment by Aewcom** [comment]
Проблема все еще актуальна.
Загрузил видео на ютуб. Сделал доступ по ссылке. Нажимаю перевод- выдает эту ошибку. Немного подождал (1-2 часа) и перевод начал работать для всех остальных загруженных видео, а то на которое нажал изначально- ошибка сохранилась.
Для чистоты эксперемента- запустил это видео в другом браузере и оно переводиться (а в изначально сохраняется ошибка).
Я без понятия в чем может быть проблема. Такое чувство, что он подгружает информацию из кэша.
