### ISSUE TITLE
Запуск из букмарклета?

### ISSUE THREAD

**Issue by iamgitcat** [ilyhalight/voice-over-translation#774]
### Describe your feature / Опишите ваше предложение

Букмарклет (закладка) может запускать скрипт с сервера, но с vot.user.js не получилось. А может у вас вдруг могли бы быть идеи как можно было бы подправить скрипт для такого сценария запуска или может вы уже рассматривали подобное и так не получится.

`javascript:(function(){var script=document.createElement('script');script.src='https://your-server.com/your-larger-script.js';document.body.appendChild(script);})();`

**Comment by ilyhalight** [comment]
Логика примерно та же, что и [с установкой скрипта в User JS and CSS](https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ#%D0%BA%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81-user-js-and-css). Только тут необходимо загрузить сам скрипт на какой-либо сервер (github, gists, pastebin и т.п. не подойдет).

В итоге получится примерно такой код:
```js
javascript:(function() {
  const toScript = link => {
    const script = document.createElement('script');
    script.src = link;
    script.defer = true;
    return script;
  };

  const scripts = [
    "https://cdn.jsdelivr.net/npm/protobufjs/dist/light/protobuf.min.js",
    "https://cdn.jsdelivr.net/npm/hls.js/dist/hls.light.min.js",
    "https://s3.toil.cc/gm-less.js",
  ].map(link => toScript(link));
  document.body.append(...scripts);

  setTimeout(() => {
    document.body.appendChild(toScript("https://s3.toil.cc/vot.user.js"));
  }, 300)
})();
```

Автообновлений нет, гарантий работоспособности на всех сайтах тоже
