### ISSUE TITLE
не работает перевод в firefox уже около недели, linux - windows

### ISSUE THREAD

**Issue by koloved** [ilyhalight/voice-over-translation#775]
### Operating system / Операционная система

windows 11-linux

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

https://i.imgur.com/Fv5utCS.jpeg

**Comment by oxalates** [comment]
У меня работает в версии ФФ 129. А в Хроме отвалилось. Версии 1.6.1 и там и там.

**Comment by ilyhalight** [comment]
Уберите эту галочку в настройках, либо поставьте там язык с которого не нужно переводить
![firefox_Kpkdgj6H8A](https://github.com/user-attachments/assets/2d3ff586-ad37-46c9-b5d9-54e4a9a4072b)

**Comment by ilyhalight** [comment]
> У меня работает в версии ФФ 129. А в Хроме отвалилось. Версии 1.6.1 и там и там.

Создавайте issues, расписывайте проблему с предоставлением логов
