### ISSUE TITLE
видео длиной в 4 часа и больше не переводятца

### ISSUE THREAD

**Issue by TrimKaslana** [ilyhalight/voice-over-translation#776]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6

### Describe the bug / Опишите ошибку

Здраствуйте я познакомился с вашым дополнением не давно когда  мне потребовался перевод одного очень долгого прохождения видео длиной в 1, 2, 3 и 3.3 часа переводилось нормально но когда я попытался воспользавотца дополнением, в 4 часовом ролине мне выдало ошыбку сказал што видео ролик слишком длиный што мне делать и являетца вобше ето ошыбкой?
![тикет](https://github.com/user-attachments/assets/565b4c6f-d0f2-4673-ba07-a9b59a395d52)

**Comment by ilyhalight** [comment]
![firefox_wC7QRHzjdk](https://github.com/user-attachments/assets/dfe5fd6f-1a35-495b-bce5-3d55afa765ff)

Единственное решение - самому разрезать видео на несколько частей, которые будут меньше 4 часов и залить на любой из доступных сайтов
