### ISSUE TITLE
Поддержка Odysee.com

### ISSUE THREAD

**Issue by CoringPlay** [ilyhalight/voice-over-translation#778]
### Describe your feature / Опишите ваше предложение

Домен с видео odysee.com

Пример ссылки на видео
https://odysee.com/@NICKNAME:n/NAME-VIDEO:n

В место маленькой 'n' может быть любое значение, но оно присваивается в видео и каналу.
Наглядный пример ссылки на видео
https://odysee.com/@GardenZooTV:9/секреты-выращивания:3

**Comment by ilyhalight** [comment]
Уже поддерживается
