### ISSUE TITLE
Отсутствует кнопка перевода для Coursera

### ISSUE THREAD

**Issue by json-statham** [ilyhalight/voice-over-translation#779]
### Operating system / Операционная система

Windows 11 Pro 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

С момента предпоследнего/последного обновления скрипта, кнопка перевода не осуществляла голосовой перевод 
"Не удается перевести видео, попробуйте позже". Если переводить через субтитры, то все было ок. 
Было решено переустановить Tampermonkey, как итог - кнопка вовсе пропала. С ютубом, например, таких проблем не наблюдается все работает корректно

**Comment by json-statham** [comment]
![Screenshot 2024-08-24 122119](https://github.com/user-attachments/assets/131ecf09-88b6-4191-8d36-350ac067635b)

**Comment by ilyhalight** [comment]
Исправлено, обновитесь до новой версии

**Comment by json-statham** [comment]
Работает, покорнейше благодарю! 

> Исправлено, обновитесь
