### ISSUE TITLE
Тишина вместо перевода

### ISSUE THREAD

**Issue by iKinst** [ilyhalight/voice-over-translation#783]
### Operating system / Операционная система

Mac OS Sonoma

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1 и предыдущие

### Describe the bug / Опишите ошибку

В Сафари ( в остальных браузерах не пробовал) периодически вместо переведенной дорожки просто тишина. Оригинальная дорожка делается тише, как и задумано, но русской речи просто нет. Переустанавливал расширение, удалял скрипт, загружал по новой – все тщетно. Кто-нибудь встречал подобную проблему?

### Additional information / Дополнительная информация

Не знаю связано ли это или нет, с недавнего времени использую скрытие пакетов DPI через программу AdGuard.

**Comment by ilyhalight** [comment]
В консоли есть какие-то ошибки?

**Comment by Post1rony** [comment]
На Хроме с Tampermonkey на 1.6.1 тоже часто такое в последнее время у меня.

**Comment by ilyhalight** [comment]
Исправил
