### ISSUE TITLE
Ошибка перевода на Coursera

### ISSUE THREAD

**Issue by remrtehno** [ilyhalight/voice-over-translation#787]
### Operating system / Операционная система

windows 11 23H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

![image](https://github.com/user-attachments/assets/f1d381e6-ef34-4c8b-b5c6-2affa99fecff)
![image](https://github.com/user-attachments/assets/5663d752-659c-45f9-a9ef-463ee40a2b2d)
![image](https://github.com/user-attachments/assets/b0e5342c-4e1d-4e9d-9851-ed74ad1e6907)

Работало с теми же настройками, через минут 20 перестало.
Может заработать позже а может и нет.
Сброс настроек не помогает, перезрузка страницы не помогает, также не помогает менять Proxy оба адреса.

**Comment by ilyhalight** [comment]
> Может заработать позже а может и нет.

Ошибка на стороне Яндекса
