### ISSUE TITLE
Возможность скачивать файлы с оригинальным именем видео

### ISSUE THREAD

**Issue by oxalates** [ilyhalight/voice-over-translation#791]
### Describe your feature / Опишите ваше предложение

Если вы часто скачиваете много аудио, например много подкстов, то они сохраняются как `c7084901938d43c4846be646c343d440.mp3`

Если вы захотите потом найти оригинал, то это будет проблематично, если у вас название файла `c7084901938d43c4846be646c343d440.mp3`

Было бы удобно иметь человеко-понятные имена файлов, например, как оригинальное видео.

**Comment by ilyhalight** [comment]
Добавил, но пока будет работать не на всех сайтах
