### ISSUE TITLE
Неполностью совершает перевод, пропускает огромные участки видео

### ISSUE THREAD

**Issue by art1coder** [ilyhalight/voice-over-translation#792]
### Operating system / Операционная система

Цштвщцы 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.1.1 \ 1.6.1

### Describe the bug / Опишите ошибку

если видео длинной 1 час 55 минут, первый час звук отсутствует, дальше появляется периодически,
перезагрузки страницы и повторный перевод ситцацию не меняют.
звук оригинала(английский) впорядке

### Additional information / Дополнительная информация

https://youtu.be/ctGiEA4Mkuw?si=3XWx_boMxx_4pRM_

**Comment by ilyhalight** [comment]
Проблема на стороне Яндекса, если хотите, чтобы это исправили, то лучше передайте ссылку на видео им.

Перед переводом переключите язык видео на "авто", чтобы пропуски звука пропали
