### ISSUE TITLE
Возникла ошибка при переводе, попробуйте позже

### ISSUE THREAD

**Issue by Prottok** [ilyhalight/voice-over-translation#793]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Перестал переводить любое видео. Пишет: Возникла ошибка при переводе, попробуйте позже.

**Comment by ilyhalight** [comment]
только что проверил, все работает
![firefox_4obeYFNPTi](https://github.com/user-attachments/assets/46d31fe8-0ea5-4057-9fb0-9c34e942e675)
