### ISSUE TITLE
Перестал работать в AdGuard

### ISSUE THREAD

**Issue by askold2** [ilyhalight/voice-over-translation#794]
### Operating system / Операционная система

Windows 10 LTSC 21H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

AdGuard

### Script version / Версия скрипта

1.6.1, 1.5.3.1

### Describe the bug / Опишите ошибку

У меня стояла версия 1.5.3.1 и некоторое время назад работала, а сегодня, при попытке запустить перевод чего угодно стала выдавать "Не удалось запросить перевод видео". Вероятно дело в обновлении AdGuard. Тогда я установил свежую версию 1.6.1, она без ошибок установилась в AdGuard, присутствует там в списке пользовательских скриптов, но не работает совсем, даже панель для запуска перевода не выдает.

**Comment by askold2** [comment]
Извиняюсь, похоже с 1.6.1 проблема была в прокси, хоть я и не понимаю какая тут связь, но без прокси оно заработало.

**Comment by mrTerryBogard** [comment]
Доброго времени суток!

Где скачать для Adguard? Только что был на главной странице и не вижу кнопки...
