### ISSUE TITLE
Использовать перевод youtube вместо piped/invidious

### ISSUE THREAD

**Issue by omniroot** [ilyhalight/voice-over-translation#795]
### Describe your feature / Опишите ваше предложение

Проблема в том, что при использовании piped/invidious видео отправляется на перевод, даже если оно уже переведено на youtube (что логично, домен то другой), но в этом нет смысла, ведь у нас уже есть перевод.
Предлагаю перед отправкой запросов заменять piped.video/invidious инстансы на youtube.com.
Если видео ещё не перевели, переводить нужно также используя youtube.com

**Comment by ilyhalight** [comment]
Сейчас так и работает
![firefox_kmJq4NXMQk](https://github.com/user-attachments/assets/ecc9c37f-eabb-4f19-8ccb-32a91cb9ca9b)

**Comment by omniroot** [comment]
Если самому выставить язык видео на английский, то всё работает правильно. На авто отправляет на перевод. 
https://nowtransfer.de/c8357c328fe2

**Comment by ilyhalight** [comment]
> Если самому выставить язык видео на английский, то всё работает правильно. На авто отправляет на перевод. https://nowtransfer.de/c8357c328fe2

С авто почти всегда необходимо немного подождать перевод, на ютубе в том числе, т.к. пользователей, кто переводит с авто на русский меньше чем например с английского на русский. Нужно будет убрать выставление языка "авто" по умолчанию у invidious и piped

**Comment by ilyhalight** [comment]
> Нужно будет убрать выставление языка "авто" по умолчанию у invidious и piped

убрал пару дней назад, обновитесь
