### ISSUE TITLE
Rumble не работает

### ISSUE THREAD

**Issue by legastok** [ilyhalight/voice-over-translation#796]
### Describe your feature / Опишите ваше предложение

Здравствуйте, Rumble перестал работать перевод
Также хотелось бы https://odysee.com/ перевод

**Comment by ilyhalight** [comment]
> Также хотелось бы https://odysee.com/ перевод

Уже есть

> Здравствуйте, Rumble перестал работать перевод

В последней версии работает

**Comment by oxalates** [comment]
> Rumble

У меня в 1.6.1 и последнем хроме ни в Rumble, ни в odysee кнопки перевода нет.
На остальных сайтах работает.
![img-2024-09-08-10-27-14](https://github.com/user-attachments/assets/b65efd42-6516-446e-aa0f-9ef064fbfe79)
![img-2024-09-08-10-28-26](https://github.com/user-attachments/assets/f1634632-d4f0-42c0-af2e-6cc9919b0ffb)

**Comment by ilyhalight** [comment]
> > Rumble
> 
> У меня в 1.6.1 и последнем хроме ни в Rumble, ни в odysee кнопки перевода нет. На остальных сайтах работает. ![img-2024-09-08-10-27-14](https://private-user-images.githubusercontent.com/143810604/365421311-b65efd42-6516-446e-aa0f-9ef064fbfe79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTI4NzksIm5iZiI6MTcyNTc5MjU3OSwicGF0aCI6Ii8xNDM4MTA2MDQvMzY1NDIxMzExLWI2NWVmZDQyLTY1MTYtNDQ2ZS1hYTBmLTllZjA2NGZiZmU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMDQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDBhMDM4NGEwZWJmMDMzM2IzZWQ1NWMxZjgxYjFiN2VkMGIzMzgzNzIwMGNjMmFiNTc5Y2RlZDUzY2UwNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N1H7YH4hfOedBMnq79KcHo4Mk41iybO1JShNGUjVm_k) ![img-2024-09-08-10-28-26](https://private-user-images.githubusercontent.com/143810604/365421313-f1634632-d4f0-42c0-af2e-6cc9919b0ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTI4NzksIm5iZiI6MTcyNTc5MjU3OSwicGF0aCI6Ii8xNDM4MTA2MDQvMzY1NDIxMzEzLWYxNjM0NjMyLWQ0ZjAtNDJjMC1hZjJlLTZjYzk5MTliMGZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMDQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDI2ZWY2MjBjM2UzZTc0N2MxNjIzNWZhMmYwMzVhYTVkM2Q2YTRmYjE3NDk3ZGNmN2UzOGU3ODdiYmY4NGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e9Qfg-mPEftBFJn2jreIHGAH2W3lRioqodiTckyeaFI)

Обновите расширение через кнопку на главной странице репозитория (через которую устанавливали)

**Comment by ilyhalight** [comment]
> > > > Rumble
> > > 
> > > 
> > > У меня в 1.6.1 и последнем хроме ни в Rumble, ни в odysee кнопки перевода нет. На остальных сайтах работает. ![img-2024-09-08-10-27-14](https://private-user-images.githubusercontent.com/143810604/365421311-b65efd42-6516-446e-aa0f-9ef064fbfe79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTI4NzksIm5iZiI6MTcyNTc5MjU3OSwicGF0aCI6Ii8xNDM4MTA2MDQvMzY1NDIxMzExLWI2NWVmZDQyLTY1MTYtNDQ2ZS1hYTBmLTllZjA2NGZiZmU3OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMDQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDBhMDM4NGEwZWJmMDMzM2IzZWQ1NWMxZjgxYjFiN2VkMGIzMzgzNzIwMGNjMmFiNTc5Y2RlZDUzY2UwNzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N1H7YH4hfOedBMnq79KcHo4Mk41iybO1JShNGUjVm_k) ![img-2024-09-08-10-28-26](https://private-user-images.githubusercontent.com/143810604/365421313-f1634632-d4f0-42c0-af2e-6cc9919b0ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTI4NzksIm5iZiI6MTcyNTc5MjU3OSwicGF0aCI6Ii8xNDM4MTA2MDQvMzY1NDIxMzEzLWYxNjM0NjMyLWQ0ZjAtNDJjMC1hZjJlLTZjYzk5MTliMGZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMDQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDI2ZWY2MjBjM2UzZTc0N2MxNjIzNWZhMmYwMzVhYTVkM2Q2YTRmYjE3NDk3ZGNmN2UzOGU3ODdiYmY4NGY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e9Qfg-mPEftBFJn2jreIHGAH2W3lRioqodiTckyeaFI)
> > 
> > 
> > Обновите расширение через кнопку на главной странице репозитория (через которую устанавливали)
> 
> У меня 1.6.1 ![img-2024-09-08-15-47-51](https://private-user-images.githubusercontent.com/143810604/365438919-f5da6b1b-a040-4339-a7f5-a0a8f1063610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDM2ODcsIm5iZiI6MTcyNTgwMzM4NywicGF0aCI6Ii8xNDM4MTA2MDQvMzY1NDM4OTE5LWY1ZGE2YjFiLWEwNDAtNDMzOS1hN2Y1LWEwYThmMTA2MzYxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMzQ5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmM4NGFmN2U3ZjM1ZTI2ZDU3Y2UyN2MwNDQxOTk5N2NmZjM5YmMzMDA1OWM0NGMwMTE0NDE1MjdiY2FkNTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KhdKop-xPDqr2Hqge8eGVjRVH2VjfZrEwQT6r1dqOck)

![firefox_0DxzJ3cQro](https://github.com/user-attachments/assets/aa1ae186-344a-49ab-a14f-0ee1423e57eb)
