### ISSUE TITLE
Не работает перевод в ютубе

### ISSUE THREAD

**Issue by Calvin-rgb** [ilyhalight/voice-over-translation#799]
### Operating system / Операционная система

Win 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Версия Хрома: 128
Пытался даже переустановить расширение и скрипт, перезагружал много раз - итог: кнопка перевода не появляется

**Comment by ilyhalight** [comment]
Что в консоли? Режим разработчика включен?

**Comment by arhiopteryx** [comment]
https://github.com/ilyhalight/voice-over-translation/issues/662#issuecomment-2160768958

**Comment by Calvin-rgb** [comment]
Заработал, спасибо за инструкцию!
