### ISSUE TITLE
Автоматическое включение перевода без нажатия на кнопку?

### ISSUE THREAD

**Issue by OwnerLink** [ilyhalight/voice-over-translation#8]
Здравствуйте! Возможно ли сделать перевод автоматическим без нажатия на кнопку? Или может в самом скрипте есть такая функция и ее нужно просто активировать?

**Comment by ilyhalight** [comment]
Такой возможности сейчас нету. Постараюсь добавить в течение недели

**Comment by ilyhalight** [comment]
Добавил в v1.0.6. Обнови расширение

**Comment by OwnerLink** [comment]
> Добавил в v1.0.6. Обнови раБольшое спасибо :D
