### ISSUE TITLE
Сколько живет кэш обращения к переводу?

### ISSUE THREAD

**Issue by oxalates** [ilyhalight/voice-over-translation#800]
### Describe your feature / Опишите ваше предложение

Имеется ввиду не сам перевод, а обращение к файлу перевода. Например, видео было с доступом по ссылке и Яндекс пишет: "Ошибка: Видео не доступно для перевода" или "не удалось запросить доступ к видео". Так же бывает "возникла ошибка при переводе, попробуйте позже".

И если видео теперь в открытом доступе, то Яндекс какое-то время по прежнему считает, что "Видео не доступно". Так вот, сколько времени живет этот кэш обращения Яндекса к видео? Можно ли это время как-то сократить или настроить?
Иногда нужно ждать, пока Яндекс сбросит этот кэш и заново начнет запрашивать видео, чтобы его перевести (по ощущениям, это минут 15-20)

Иногда, если видео застревает в статусе: "возникла ошибка при переводе, попробуйте позже", можно ожидать 3 раза и более по 15-20 минут, если перевод вернется с этой ошибкой, пока сервера не поймут, что видео доступно и его можно перевести.

**Comment by ilyhalight** [comment]
> Так вот, сколько времени живет этот кэш обращения Яндекса к видео

Точно не известно, вероятно, для ютуба время кэша будет меньше, чем для других сайтов

> Можно ли это время как-то сократить или настроить

Раньше была настройка, которая позволяла игнорировать кэш, но видимо она больше не работает. Максимум, можно запросить перевод с другого языка с которого еще не переводили
