### ISSUE TITLE
При просмотре youtube shorts, при перелистывании на новое видео продолжается озвучка предыдущего.

### ISSUE THREAD

**Issue by DygDyg** [ilyhalight/voice-over-translation#802]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

При просмотре youtube shorts, при перелистывании на новое видео продолжается озвучка предыдущего.
Включён автоперевод видео, при попадании в шортсах английского видео он его переводит и при переходе на следующее он включает повторно перевод аудиодорожки предыдущего. 

https://github.com/user-attachments/assets/82907784-1806-443e-b49d-cae09e45c8a1

Причём ведёт себя нестабильно, то пропадает после 1 видео, то может повторяться пока не нажмешь на кнопку с отключением перевода.

**Comment by ilyhalight** [comment]
Исправил, обновитесь
