### ISSUE TITLE
ошыбка переноса по сылке до скрипта

### ISSUE THREAD

**Issue by TrimKaslana** [ilyhalight/voice-over-translation#805]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

когда я захотел установить ваше прекрасное дополнение на ноутбук я попытался скачать скрипт но меня просто не перенесло по сылке в чом проблема

### Additional information / Дополнительная информация

я уже пойлзовался вашым дополнением на пк и мнея не переносит на сайт со скриптом

**Comment by ilyhalight** [comment]
попробуйте что-то из описанного тут #804

не знаю из-за чего происходит ошибка
