### ISSUE TITLE
Добавить сайт

### ISSUE THREAD

**Issue by Kzander3000** [ilyhalight/voice-over-translation#806]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.2.3.

### Describe the bug / Опишите ошибку

Добрый день.
Научите, пожалуйста, добавлять сайты самостоятельно в настройках. Я вроде использовал настройки включения Пользовательские @matches и скрипт в панели управления показывает, что включен на сайте, но видео все равно не переводит.

Меня интересуют сайты:

1. https://learning.sap.com/
К примеру видео: https://learning.sap.com/learning-journeys/discovering-sap-activate-implementation-tools-and-methodology/describing-sap-activate
3. https://learninghub.sap.com/

**Comment by ilyhalight** [comment]
> https://learning.sap.com/

Уже поддерживается, но пока только курсы

**Comment by ilyhalight** [comment]
> Научите, пожалуйста, добавлять сайты самостоятельно в настройках. Я вроде использовал настройки включения Пользовательские @matches и скрипт в панели управления показывает, что включен на сайте, но видео все равно не переводит.

нужно не только добавить в список, но и прописать логику работы для нужного сайта по аналогии с уже существующей

**Comment by Kzander3000** [comment]
> > https://learning.sap.com/
> 
> Уже мероприятия, но пока только курсы
> 
> > * https://learninghub.sap.com/
> 
> Это тот же сайт, который ведет на Learning.sap.com или на нем тоже могут быть какие-то видео?

Добрый день.
К сожалению для сайта https://learning.sap.com/ все равно не работает перевод, не появляется окно с переводом. Я пробовал добавить сайт и прописать логику в редактор:
```
{
    host: VideoService.sapLearning,
    url: "stub",
    match: /^learning\.sap\.com$/,
    selector: ".playkit-engine", - тут разные классы перечислял, в которых сидит само видео <video>...</video>
    needExtraData: true,
},
```
Но результата нет, возможно нужно еще что-то прописывать?
У вас код прописан следующий:
```
    {
        host: VideoService.sap,
        url: "https://learning.sap.com/courses/",
        match: /^learning.sap.com$/,
        selector: ".playkit-container",
        eventSelector: ".playkit-player",
        needExtraData: true,
    },
```
Тоже пробовал его менять, играться с классами. Не помогло((


Что касается https://learninghub.sap.com/, вы правы, там где есть видео, то страницы ссылаются на https://learning.sap.com/ соответсвенно полагаю нужно решить вопрос с этим сайтом.

**Comment by ilyhalight** [comment]
> К сожалению для сайта https://learning.sap.com/ все равно не работает перевод, не появляется окно с переводом. Я пробовал добавить сайт и прописать логику в редактор:

Пока работает, только, если ссылка начинается на /courses, позже добавлю и learning-journeys

пример https://learning.sap.com/courses/opportunities-and-success-for-partners-in-sap-s-industry-cloud

**Comment by Kzander3000** [comment]
> пример https://learning.sap.com/courses/opportunities-and-success-for-partners-in-sap-s-industry-cloud

Курсы работают, спасибо большое.
Дайте знать, пожалуйста, когда можно будет проверить learning-journeys.

**Comment by ilyhalight** [comment]
> > пример https://learning.sap.com/courses/opportunities-and-success-for-partners-in-sap-s-industry-cloud
> 
> В курсах вижу перевод в субтитрах, саму кнопку перевода, но закадрового перевода у меня нет.

нужно csp удалять через tampermonkey, чтобы аудио работало

**Comment by Kzander3000** [comment]
Что такое csp? Не совсем понимаю, что мне нужно сделать.
Я попробовал вообще удалить скрипт и заново установить, не помогло.

У меня могут быть глупые вопросы, просто я не разбираюсь в этом((

**Comment by ilyhalight** [comment]
> Что такое csp? Не совсем понимаю, что мне нужно сделать. Я попробовал вообще удалить скрипт и заново установить, не помогло.
> 
> У меня могут быть глупые вопросы, просто я не разбираюсь в этом((

[Инструкция](https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ#%D0%BF%D1%80%D0%B8-%D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4%D0%B0-%D0%BF%D0%B8%D1%88%D0%B5%D1%82-%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%B0%D1%83%D0%B4%D0%B8%D0%BE-%D0%BD%D0%B5-%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F-the-audio-format-is-not-supported). Только за место "Да", нужно выбрать "Удалить"

**Comment by Kzander3000** [comment]
Добрый день.
Не помогло. Я выполнил шаги согласно инструкции:
![2024-09-16_163503](https://github.com/user-attachments/assets/efc0f594-2953-4991-b6a9-0c436ec7a2fc)
Все равно нет закадрового голоса. Есть кнопка сама и работают субтитры, как на скрине ниже.
![Без имени](https://github.com/user-attachments/assets/394537ab-c1ca-4918-b415-73a8fdef60f6)

**Comment by ilyhalight** [comment]
> позже добавлю и learning-journeys

Добавил, обновите расширение

**Comment by Kzander3000** [comment]
Спасибо.
Но пока не появилось.

Правильно понимаю, что достаточно нажать кнопку Обновить тут:
![2024-09-16_174602](https://github.com/user-attachments/assets/beeec41b-777c-4cb3-9e52-bd8b32ecf89f)

Я попробовал еще нажать на время обновления (3d) в панели управления скрипта:
![2024-09-16_174652](https://github.com/user-attachments/assets/c3554005-3fc8-4a45-a98a-3be2d7e28243)

**Comment by ilyhalight** [comment]
> Правильно понимаю, что достаточно нажать кнопку Обновить тут:

нужно нажимать "установить расширение" на странице скрипта на гитхабе и там уже предложит обновить
