### ISSUE TITLE
Ошибки в работе скрипта при переводе видео с Apple Developer

### ISSUE THREAD

**Issue by Gerodot** [ilyhalight/voice-over-translation#808]
### Operating system / Операционная система

macOS Ventura 13.6.9 (22G830)

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

При выполнении скрипта возникают ошибки (см скрин). На других сайтах такой проблемы нет. Ошибка не зависит от браузера, проверено на Chrome и Safari
Громкость ролика штатно снижается до 15%, UI не показывает сообщений об ошибке. Загрузка перевода в виде файла работает штатно.  
![Снимок экрана 2024-09-15 в 10 59 39](https://github.com/user-attachments/assets/83e3fb9a-fd85-47a3-a138-87d28efd305d)
![Снимок экрана 2024-09-15 в 11 03 50](https://github.com/user-attachments/assets/9d072b84-a9f0-40b1-9f19-97841528a870)

**Comment by ilyhalight** [comment]
Попробуйте обновиться до последний версии через кнопку на главной репозитория, и убедитесь, что в настройках расширения включена функция "Обход Media CSP"

**Comment by ilyhalight** [comment]
Переоткройте, если не помогло

**Comment by Gerodot** [comment]
Обновил. Галка стоит. 
На Safari перевод начинается с самого начала вне зависимости от положения плейхеда. На Chrome перевода нет.
