### ISSUE TITLE
Ручное корректирование субтитров до их отправки на озвучку

### ISSUE THREAD

**Issue by eyewee** [ilyhalight/voice-over-translation#809]
### Describe your feature / Опишите ваше предложение

Здравствуйте, можно ли добавить опцию скачать SRT файл, затем вручную откорректировать его, и лишь затем отдать расширению на озвучку? Таким образом озвучка будет более качественной..

**Comment by ilyhalight** [comment]
Нет. Субтитры играют роль, только. если есть видео с прямой ссылкой на .mp4, а сайтов работающих по такой логике довольно мало, и сомневаюсь, что они пользуются сильной популярностью

**Comment by eyewee** [comment]
Хорошо, а можно ли тогда скачать видео с ютуб, залить в драйв, и от туда ведь уже будет прямая сыылка на mp4? Есть ли возможность в таком случае как-то вручную отредактировать текст перед озвучкой?

**Comment by ilyhalight** [comment]
> и от туда ведь уже будет прямая сыылка на mp4

Не будет прямой ссылки, в гугл драйв переводится через обычную ссылку через которую делятся файлом. Прямая ссылка на mp4, есть только у coursera, coursehunter, udemy, linkedin, odysee, sap learning, либо на каких-либо сайтах/s3, которые ведут именно на файл, а не на плеер.

Coursera и udemy и так озвучиваются по субтитрам, если они есть. Для linkedin и sap learning, тоже, будет добавлена озвучка по существующим субтитрам с сайта. А делать отдельный функционал и организовывать какое-то временное хранилище для загруженных субтитров для 2.5 не самых популярных сайтов, честно говоря, не вижу смысла.

**Comment by eyewee** [comment]
Понятно, я имею ввиду не озвучка и имеющихся субтитров а озвучка с генерированных яндексом. В расширении видел пункт "translate errors from API" и можно выбрать яндекс или дипл, я бы хотел чтобы подобным образом была функция ручной коррекции, если таковое возможно. Т.е. добавить, опционально, промежуточных этап, между процессом генерации субтитров ( и их перевода) и озвучки. И чтобы именно процесс перевода можно было вручную довести до ума. Ведь расширение уже имеет опцию скачивания переведенных субтитров, если бы можно было их скачать а затем, изменив, локально применить к видео, использовать user modified версию, которая хранится на кэше браузера локально, было бы прекрасно.
