### ISSUE TITLE
Не появляется иконка перевода на rumble.com 

### ISSUE THREAD

**Issue by Paul1804** [ilyhalight/voice-over-translation#810]
### Operating system / Операционная система

Debian 6.7.12-1~bpo12+1 (2024-05-06) x86_64 GNU/Linux

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

Не вижу иконки перевода при просмотре видео на rumble.com Длина видео 1:42 часа. Ну и соответственно ничего и не переводит

**Comment by ilyhalight** [comment]
обновитесь через кнопку на главной

**Comment by Paul1804** [comment]
> обновитесь через кнопку на главной

обновить страницу, вы имели ввиду ?

**Comment by ilyhalight** [comment]
> > обновитесь через кнопку на главной
> 
> обновить страницу, вы имели ввиду ?

Нет, именно скрипт

**Comment by Paul1804** [comment]
![изображение](https://github.com/user-attachments/assets/5377813f-20cd-4849-a207-98566c8cf3cc)
там явно нет -Обновить.( просто включить и выключить его ?

**Comment by Paul1804** [comment]
![изображение](https://github.com/user-attachments/assets/287242aa-6cd5-4647-bc93-36c13cccb47b)
вот от сюда ?

**Comment by Paul1804** [comment]
...да, иконка появилась. Спасибо !

**Comment by Paul1804** [comment]
если видео на rumble будет 6:30 то перевод пойдет ?

**Comment by ilyhalight** [comment]
> если видео на rumble будет 6:30 то перевод пойдет ?

до 4 часов поддерживается
