### ISSUE TITLE
если видео на rumble будет 6:30 то перевод пойдет ?

### ISSUE THREAD

**Issue by Paul1804** [ilyhalight/voice-over-translation#811]
### Describe your feature / Опишите ваше предложение

если видео на rumble будет 6:30 то перевод пойдет ?

**Comment by ilyhalight** [comment]
должен быть

**Comment by Paul1804** [comment]
нет не идет. При наведении на иконку перевода всплывает окно "Видео слишком длинное". Как это преодолеть ? Вот это видео очень хочется с переводом увидеть  https://rumble.com/v2dg19g-march-16-2023.html?playlist_id=watch-history

**Comment by ilyhalight** [comment]
Аа... вы имели ввиду 6 часов 30 минут, такие видео, к сожалению, только разрезать на несколько частей, которые будут меньше 4 часов, перезаливать куда-нибудь и уже их смотреть с переводом

**Comment by Paul1804** [comment]
ну а куда перезалить то ? Что бы по простому.. У меня канала то нет.(

**Comment by ilyhalight** [comment]
> ну а куда перезалить то ? Что бы по простому.. У меня канала то нет.(

любой поддерживаемый веб-сайт, кроме google drive т.к. там почему-то видео больше 50 минут не стабильно переводятся

Из самых простых вариантов Яндекс диск, Mail.ru Видео, VK видео, YouTube (не в закрытый доступ), Vimeo

**Comment by Paul1804** [comment]
разрезал на части по 2:11 часа, загрузил на яндекс диск, запустил, видео пошло на английском... однако иконка перевода не появляется на экране. Что предпринять ?

**Comment by ilyhalight** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/40546987/368670593-16d5ce76-b58a-4c59-bd4a-98b3c96c4444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2ODcwNzMsIm5iZiI6MTcyNjY4Njc3MywicGF0aCI6Ii80MDU0Njk4Ny8zNjg2NzA1OTMtMTZkNWNlNzYtYjU4YS00YzU5LWJkNGEtOThiM2M5NmM0NDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDE5MTI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZDU3YzcxMWZhOTBmZjMzYjdiZjhjMTExZDc3MmE3M2E1MTg2NjFmNmRiNmRlMDI1NWQ1NWM5N2RhNDA0ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bAGjntMUTVtk3LFfKLH8JzZeP-M5aVEptTnNKemq6TA) разрезал на части по 2:11 часа, загрузил на яндекс диск, запустил, видео пошло на английском... однако иконка перевода не появляется на экране. Что предпринять ? Может быть, как вариант, разрезать на куски продолжительностью до 2-х часов ?

Вам нужно открыть доступ по ссылке к каждому видео и по нему уже переводить. Расширение не поддерживает ссылки на яндекс диске, которые начинаются с /d/

**Comment by Paul1804** [comment]
Да, все получилось! Огромное спасибо за помошь!  ...и  за то что Вы сделали такую программу. Это огромное облегчение конечно, иметь возможность смотреть те видео которые хочется, с переводом.

**Comment by Paul1804** [comment]
Подскажите, а можно ли переведенное видео таким образом скачать на компьютер с переводом?

**Comment by ilyhalight** [comment]
> Подскажите, а можно ли переведенное видео таким образом скачать на компьютер с переводом?

через [vot-cli](https://github.com/FOSWLY/vot-cli) + один из скриптов для вашей ос можно автоматически скачать видео+перевод. Либо скачайте перевод через расширение и видео через любой другой способ и соедините в редакторе

**Comment by Paul1804** [comment]
Спаибо, я все понял. Все работает. А вы не планируете добавить этот функционал в расширение ? что бы скачивать видео и перевод одновременно и паковать в формат , к примеру mp4 .

**Comment by ilyhalight** [comment]
> Спаибо, я все понял. Все работает. А вы не планируете добавить этот функционал в расширение ? что бы скачивать видео и перевод одновременно и паковать в формат , к примеру mp4 .

Нет, слишком избыточно
