### ISSUE TITLE
"Не переводить с родного языка" для 2-х и более языков

### ISSUE THREAD

**Issue by iG8R** [ilyhalight/voice-over-translation#818]
### Describe your feature / Опишите ваше предложение

Привествую.
Возможно ли выбрать 2 и более языка в параметре "Не переводить с родного языка", например, Русский, Украинский и Английский? Т.к. сейчас крайне затруднительно пользоваться включенным параметром "Переводить при открытии", т.к. большинство просматриваемых видео все таки на этих языках и в переводе для меня не нуждаются, например, видео на украинском начинают переводиться на русский и потому постоянно приходится отвлекаться на отключение перевода.

**Comment by ilyhalight** [comment]
Возможно, добавлю, но не в ближайшее время

**Comment by iG8R** [comment]
Спасибо большое.
