### ISSUE TITLE
Доработки: запоминание настроек и возвращение громкости на 100% в случае отключения перевода

### ISSUE THREAD

**Issue by MettriQ** [ilyhalight/voice-over-translation#82]
Сейчас оригинал и перевод имеют одинаковую громкость, поэтому приходится при каждом новом переводе видео постоянно убавлять громкость оригинала до 20%, эти настройки не запоминаются. 
Также, если я внезапно захочу с перевода переключиться обратно на оригинал, чтобы послушать отдельную часть видео в оригинале, громкость оригинала так и останется на 20% и её приходится каждый раз снова выставлять на 100%.
Предлагаю следующее: 
1. Добавить галочку "применять настройки для каждого видео", чтобы выставленная громкость, например 20% оригинал и 100% перевод, применялась для каждого видео;
2.  Отключать применённые настройки и возвращать громкость на 100% в случае, если я выключаю перевод. Для этой опции тоже можно добавить галочку.

**Comment by narimangafurov** [comment]
поддерживаю! было бы отлично!

**Comment by FiLinX** [comment]
а что делать для таких как я?  
во первых, у меня в микшере самой системы стоит предел на 50% громкости, а браузеру ещё до 25% граница снижена
во вторых, ютубным расширением применяется установка на 25% громкости при запуске роликов
в третьих, бегунок уровня громкости самого перевода в этом скрипте запомнен на половине его шкалы
   и всё равно, чтобы комфортно воспринималось, приходится убавлять громкость оригинала до 3-5%
ютубным расширением делать установку на такой уровень - не катит, я смотрю не более четверти роликов на иноземном, остальные по русски..
   
   самое идеальное было бы, это если б при включении перевода  -  производилось бы автоматическое выставление громкости оригинала в одну-десятую часть от величины выставленного уровня перевода соответственно, а при отключении перевода возвращало бы уровень оригинала в дефолт..
вобщем, как у яндыха самого)

**Comment by ilyhalight** [comment]
> и ещё важное - очень не хотелось бы ещё каких либо кешей, что либо логирующих в браузере надолго

По сути, сейчас, ничего такого и нету, кроме базы данных, которая хранит настройки расширения. В будущем, добавлять, такое, так же не планируется (да, и хранить, то собственно нечего, всё получается с серверов яндекса или уже встроено напрямую в расширение)

**Comment by ilyhalight** [comment]
> 2\. Отключать применённые настройки и возвращать громкость на 100% в случае, если я выключаю перевод. Для этой опции тоже можно добавить галочку.

Добавил в 1.0.9.7. Без галочки, если многим будет ее не хватать, то добавлю.


> 1. Добавить галочку "применять настройки для каждого видео", чтобы выставленная громкость, например 20% оригинал и 100% перевод, применялась для каждого видео;

Добавлю чуть позже, что-то забыл про это, когда обнову пушил.

**Comment by ilyhalight** [comment]
> самое идеальное было бы, это если б при включении перевода - производилось бы автоматическое выставление громкости оригинала в одну-десятую часть от величины выставленного уровня перевода соответственно, а при отключении перевода возвращало бы уровень оригинала в дефолт (а не в 100%)..
> вобщем, как у яндыха самого)

С небольшими изменениями, но добавлено
