### ISSUE TITLE
Просмотр и перевод локальных видео

### ISSUE THREAD

**Issue by Macleopard** [ilyhalight/voice-over-translation#821]
### Describe your feature / Опишите ваше предложение

Здравствуйте, не могу перевести видео, которое находится на локальном файле. Пробовал через протокол file://, пробовал через html-страницу, которая ведет на этот файл. Добавлял в скрипт *://*.localhost/* file://*/*.mp4*, также безуспешно

**Comment by SashaXser** [comment]
Прочитайте [FAQ](https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ), уже надоели с этим вопросом. 
Вы вообще читаете что-то кроме кода на Python?
![изображение](https://github.com/user-attachments/assets/f6f5709c-4a34-4ead-b62e-22613fdb4755)

**Comment by Macleopard** [comment]
Простите, не увидел, хотя заходил на FAQ
