### ISSUE TITLE
Не переводит видео в vimeo player

### ISSUE THREAD

**Issue by ihxnnxs** [ilyhalight/voice-over-translation#828]
### Operating system / Операционная система

Windows 11 23H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

## **Приветствую разработчиков и контрибутеров voice-over-translation👋** 

У меня возникла проблема с переводом видео в vimeo player на сайте laracasts.com.
Дело в том что при попытке перевода любого видео, он пытается перевести и в определенный момент выбрасывает ошибку:

![изображение](https://github.com/user-attachments/assets/8459dd82-7ddd-4682-a1ae-0be3aedfeb4e)

Перевод стоит от Яндекса.

Вот мои настройки:

![изображение](https://github.com/user-attachments/assets/e24318dd-4602-4049-a4b3-60f1fb09c758)

P.s. если нужна доп. информация, то пишите я почти всегда онлайн :)

**Comment by ilyhalight** [comment]
> Дело в том что при попытке перевода любого видео, он пытается перевести и в определенный момент выбрасывает ошибку:

Для встроенного плеера vimeo это нормально, т.к. для правильной загрузки он требует указания referer заголовка (без него, будет показываться, что видео не существует), о котором Яндекс ничего не знает. Возможно, получится исправить

**Comment by ihxnnxs** [comment]
Если получиться исправить, будет вообще кайф)

**Comment by ilyhalight** [comment]
Теперь, должно работать 
![firefox_MLTNKZozeM](https://github.com/user-attachments/assets/5ec4032a-648d-46ed-a1a1-62d48fd4c8a7)

**Comment by ihxnnxs** [comment]
Спасибо огромное, у вас есть donation alerts?

**Comment by ilyhalight** [comment]
> у вас есть donation alerts?

нет

**Comment by Awake-108** [comment]
У меня такая же проблема в Vimeo, не переводит.
Что значит "для правильной загрузки он требует указания referer заголовка" и как это исправить?
"Обновитесь до самой последней версии через кнопку установить скрипт на главной", - установили только вчера и обновления вроде как не требуются, если нажимать Tampermonkey > утилиты > проверить обновления скриптов.
Помогите, пожалуйста!!!

**Comment by ilyhalight** [comment]
> установили только вчера и обновления вроде как не требуются, если нажимать Tampermonkey > утилиты > проверить обновления скриптов

Он и не должен предлагать т.к. это обновление еще в бете, ждите релиза или установите вручную со [страницы релизов](https://github.com/ilyhalight/voice-over-translation/releases)

**Comment by Awake-108** [comment]
Когда пытались наладить работу в vimeo, нажали "добавить vimeo в исключения" и теперь в Tampermonkey "скрипт не запущен". Как убрать vimeo из исключений, чтобы в vimeo сверху появлялось "перевести"?

**Comment by ilyhalight** [comment]
> Когда пытались наладить работу в vimeo, нажали "добавить vimeo в исключения" и теперь в Tampermonkey "скрипт не запущен". Как убрать vimeo из исключений, чтобы в vimeo сверху появлялось "перевести"?

в настройках скрипта в тампермонкей поищите

**Comment by ilyhalight** [comment]
> Теперь, должно работать. Обновитесь до самой последней версии через кнопку установить скрипт на главной репозитория ![firefox_MLTNKZozeM](https://private-user-images.githubusercontent.com/62353659/370924300-5ec4032a-648d-46ed-a1a1-62d48fd4c8a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NjE5MzYsIm5iZiI6MTczMDc2MTYzNiwicGF0aCI6Ii82MjM1MzY1OS8zNzA5MjQzMDAtNWVjNDAzMmEtNjQ4ZC00NmVkLWExYTEtNjJkNDhmZDRjOGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDIzMDcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYmYzZjA2MTQ1YWU5MThkMjE1ZGIzZTc5ZDMxOTVmZGFhNDcyMjBiMWQ0MzBiOWQwMTNlZTk2Nzg0MTg2NjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jFpOj7ZvulfYAXrEzx7aUZ5DCIsPgtBO3_mHbOz3o5M)

Добавлено в 1.7.1
