### ISSUE TITLE
failed to create request session

### ISSUE THREAD

**Issue by dr9amre** [ilyhalight/voice-over-translation#829]
### Operating system / Операционная система

windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

just don't translate video
![Безымянный](https://github.com/user-attachments/assets/a9179643-29ae-4e05-b12b-774d47a4e8fd)

**Comment by ilyhalight** [comment]
Try upgrade to 1.7.0. If this didn't help, provide all logs from console (error + log + info levels), including the line "[db] data from db:  "
