### ISSUE TITLE
Не переводит либо озвучивает без перевода

### ISSUE THREAD

**Issue by Ttmw911** [ilyhalight/voice-over-translation#830]
### Operating system / Операционная система

Win 10

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

https://www.youtube.com/watch?v=yQIBS5xwvVQ
https://www.youtube.com/watch?v=vrt3lL5gEb0

Не переводит видео. Либо вообще нет перевода либо выборочно озвучивает английские слова.

**Comment by SashaXser** [comment]
Попробуй обратиться в службу поддержки Яндекс Браузера и уточни у них.

**Comment by Ttmw911** [comment]
@SashaXser Правильно понимаю что именно сам перевод это полностью работа Яндекса? Т.е. такие косяки перевода к данному расширению не имеют отношения?
