### ISSUE TITLE
не работает на youtube в мобильной версии Safari IOS 18.0 

### ISSUE THREAD

**Issue by osmaav** [ilyhalight/voice-over-translation#833]
### Operating system / Операционная система

IOS 18.0

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.6.1

### Describe the bug / Опишите ошибку

звук перевода с английского на русский не воспроизводится на сайте m.youtube.com при этом если сам файл аудио скачать, то он воспроизводится, субтитры так же работают

**Comment by ilyhalight** [comment]
Попробуйте обновиться

**Comment by osmaav** [comment]
благодарю! версия 1.7.0 прекрасно работает
