### ISSUE TITLE
YouTube Не переводит спонсорские видео

### ISSUE THREAD

**Issue by Kzander3000** [ilyhalight/voice-over-translation#839]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.2.3.

### Describe the bug / Опишите ошибку

Я оформил спонсорство на ютуб и как оказалось, что ролики скрипт не может перести, так как ограничен доступ. Как исправить?
![image](https://github.com/user-attachments/assets/0466cf28-2b68-4c38-b085-c11f2ee6eb54)

[https://www.youtube.com/watch?v=0uEF6NSeBDY&list=PL8CXU2O8dFHYVnmbYhUvwBcum1Wzv0eYb&index=6](url)

**Comment by FiLinX** [comment]
> Как исправить?

а исправить то что??   купить яндексу спонсорство на этот канал? ))
ну, как яндекс доступ то к такому видео получит то?
если уж очень надо именно это видео перевести  -  то сами скачайте, и загрузив его например на яндекс-гугле диск, и получив там ссылку на паблик, перейдите по ней  -  вот тогда уже и посмотрите в переводе)
ну то есть у яндекса должен быть свободный доступ к видео!
а вот чем и как вам скачать с ютуба, такое видео с ограничениями, это уже вопрос за рамками данного топика)

**Comment by Kzander3000** [comment]
Предполагал, что если я получу доступ к видео, следовательно страница открыта: видео запускается, можно услышать звук и есть субтитры, то и скрипт получает автоматически такой доступ - ведь страница открыта. Тут что-то не логично.

Что самое интересно, что скрипт считывает субтитры и показывает перевод, а голос нет. Субтитры обрабатываются по-другому?
![image](https://github.com/user-attachments/assets/357b810a-0111-4764-b3b8-30be0a760489)
На скрине выделил зеленым субтитры скрипта и внизу можно увидеть субтитры самого видео-автора.

**Comment by ilyhalight** [comment]
Как уже сказали выше, переводчик Яндекса банально не может скачать видео т.к. он работает используя публичные ссылки. А если попытаться загрузить видео без авторизации, то будет примерно такой текст

![WindowsTerminal_9SfLbimeIp](https://github.com/user-attachments/assets/97fcb4c1-83ee-4369-9287-ac50489e04da)

Поэтому перевод такого видео не возможен, если вручную его не загрузить куда-нибудь. Субтитры на скриншоте видимо автосгенерированные ютубом (при выборе в меню у них есть домен в название - www.youtube.com) т.к. Яндекс ничего не возвращает в ответе
![WindowsTerminal_mK1BsVqAlY](https://github.com/user-attachments/assets/537ec23a-8f5a-4462-8b3e-cb056fb8e8d4)
