### ISSUE TITLE
Не работает в m.youtube.com

### ISSUE THREAD

**Issue by Michael1297** [ilyhalight/voice-over-translation#84]
Не появляется кнопка перевода в m.youtube.com

**Comment by miketype** [comment]
> Не появляется кнопка перевода в m.youtube.com
(Как временное решение)

В 1.0.9.5 работает.

Нужно установить старую версию:
https://github.com/ilyhalight/voice-over-translation/raw/1.0.9.5/vot.user.js

**Comment by miketype** [comment]
Сейчас кнопки вообще нет.
(в мобильной версии)

Раньше (до версии 1.0.9.6) она иногда пропадала. При этом перевод работал безупречно. (если установить автоперевод)

**Comment by ilyhalight** [comment]
Исправил появление кнопки.

 На счёт того нормально ли всё работает или нет - ничего не могу сказать. Поскольку на телефоне звука перевода не было, но расположение кнопки было нормальное, а на пк звук перевода есть, но кнопка находится по центру страницы.

**Comment by Michael1297** [comment]
Благодарю. Через AdGuard у меня работает нормально.
