### ISSUE TITLE
youtube Не переводит хотя скрипт работает 

### ISSUE THREAD

**Issue by souie-bit** [ilyhalight/voice-over-translation#840]
### Operating system / Операционная система

win 11 23h2 22631.4169

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

Баг появился с обновлением 1.7.0
С 10-й попытки запускай перевод(каждый раз по-разному)(но если скрипт запустил озвучку баг пропадает). Но при этом через скрипт спокойно скачивается дорожка озвучки.
Не багается скрипт когда на видео не было перевода. 
Может есть вариант откатиться до предыдущей версии?
Прошу не бить если есть уже тикет на это тему!(я искал вроде нет)
А ещё проблема в горячих клавишах. После включения скрипта они перестают работать банально play\pause.
Есть вариант пофиксить ?

**Comment by souie-bit** [comment]
https://youtu.be/vSb8DxxtEDw
Тут повезло, помогло перезагрузка страницы. Но обычно минуты 2 тратишь, чтоб начать просмотр

**Comment by ilyhalight** [comment]
Что в консоли, когда не получается запустить перевод

**Comment by ilyhalight** [comment]
> А ещё проблема в горячих клавишах. После включения скрипта они перестают работать банально play\pause.

У меня все работает

**Comment by souie-bit** [comment]
https://kappa.lol/S9Was

**Comment by Kokos21s** [comment]
Тоже не переводит видео после обновы

**Comment by souie-bit** [comment]
> У меня все работает
Ты говоришь про кнопки которые Windows или гр.кнопки на сайте ?

**Comment by souie-bit** [comment]
> Что в консоли, когда не получается запустить перевод

https://kappa.lol/S9Was

**Comment by souie-bit** [comment]
> Тоже не переводит видео после обновы

Случайно нашёл способ. Нужно выставить громкость перевода на 100% пока не начнёт говорить .
Мне по крайне мере помогает этот способ.

**Comment by ilyhalight** [comment]
Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, возможно пофиксит

**Comment by souie-bit** [comment]
> Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, возможно, пофиксит проблему с срабатыванием перевода не с первого раза. Горячие клавиши должны работать в этой версии, если вы про те же, что и в #192, #841

https://youtu.be/sGIhQvtRXmE
перевод не стартует сразу. А горячие клавиши работают windows ура.

**Comment by souie-bit** [comment]
> Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, возможно, пофиксит проблему с срабатыванием перевода не с первого раза. Горячие клавиши должны работать в этой версии, если вы про те же, что и в #192, #841

а так же https://youtu.be/nLymfAyo7Sw
меняет голос если x больше чем 1.0

**Comment by ilyhalight** [comment]
> Дубль звука https://youtu.be/4H-8ZvISwa8

Просто появилось после начала перевода или нужно сделать что-то конкретное для появления?

**Comment by souie-bit** [comment]
> Просто появилось после начала перевода или нужно сделать что-то конкретное для появления?

https://youtu.be/BuK88nsVBq4 
просто включаешь и выключаешь перевод

**Comment by progzone122** [comment]
У меня начинает работать перевод только когда звук видео 100%

**Comment by souie-bit** [comment]
@ilyhalight Можно ли как то выключить новые голоса ? Или это новый апдейт от яндекса ? https://youtu.be/PeO3LYvkusI 
Это насколько плохо. Постоянно меняется голоса у одного говорящего это АД.

**Comment by ilyhalight** [comment]
> @ilyhalight Можно ли как то выключить новые голоса ? Или это новый апдейт от яндекса ? https://youtu.be/PeO3LYvkusI Это насколько плохо. Постоянно меняется голоса у одного говорящего это АД.

полагаю, что нельзя самому на это повлиять. Максимум можно яндексу зарепортить, что на каком-то конкретном видео вот такие артефакты, может быть и починят

**Comment by ilyhalight** [comment]
> У меня начинает работать перевод только когда звук видео 100%

> Тут повезло, помогло перезагрузка страницы. Но обычно минуты 2 тратишь, чтоб начать просмотр

С последней бетой такая проблема еще появляется или уже нет?

**Comment by progzone122** [comment]
> > У меня начинает работать перевод только когда звук видео 100%
> 
> > Тут повезло, помогло перезагрузка страницы. Но обычно минуты 2 тратишь, чтоб начать просмотр
> 
> С последней бетой такая проблема еще появляется или уже нет?

Вроде стало лучше

**Comment by ilyhalight** [comment]
Пока будем считать, что исправлено, если что переоткройте
