### ISSUE TITLE
Пауза и воспроизведение мультимедийными кнопками

### ISSUE THREAD

**Issue by nifush** [ilyhalight/voice-over-translation#841]
Operating system / Операционная система
Windows 10 21H2

Browser / Браузер
Chrome

Userscript manager / Скриптовый движок
Tampermonkey

Script version / Версия скрипта
1.6.1

Describe the bug / Опишите ошибку
Не работает пауза и воспроизведение видео мультимедийными кнопками (на мыши так и на клавиатуре) при включенном переводе на youtube, если не включать перевод то пауза и воспроизведение работает, есть ли какое нибудь решение? Очень не удобно когда смотришь туториал и приходится ставить на паузу переводя мышь на само видео и кликать по нему.

**Comment by FiLinX** [comment]
тут скорее виновен сам Хром
когда последним запущенным на воспроизведение медиа контентом - является аудио поток (яндекс перевод), вот тут и проблема в Хроме
https://i.imgur.com/LW3Trab.jpeg

**Comment by souie-bit** [comment]
> как альтернативу медиа-клавишам, для плей-паузы можно использовать английскую клавишу K Keyboard shortcuts for YouTube™ - https://www.mrfdev.com/youtube-keyboard-shortcuts
Да только они работают когда окно хрома активен(А если допустим в другом окне это не работает)хотя у меня было всего один раз когда горячие кнопки play\pause работали со скриптом

**Comment by nifush** [comment]
> тут скорее виновен сам Хром когда последним запущенным на воспроизведение медиа контентом - является аудио поток (яндекс перевод), вот тут и проблема в Хроме https://i.imgur.com/LW3Trab.jpeg
> 
> как альтернативу медиа-клавишам, для плей-паузы можно использовать английскую клавишу K Keyboard shortcuts for YouTube™ - https://www.mrfdev.com/youtube-keyboard-shortcuts

Сам то хром воспроизводит и паузит видео мультимедийными кнопками даже если окно хрома не активна, но если включить перевод видео то он перестает реагировать на паузу/воспроизведение.

**Comment by ilyhalight** [comment]
Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, должно работать

**Comment by ilyhalight** [comment]
> Попробуйте с [этой](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) версией, должно работать

Исправлено, но работает, только, если включен "Новый аудиоплеер". Со старым нельзя исправить
