### ISSUE TITLE
Не переводит больше стримы на ютубе(долгие)

### ISSUE THREAD

**Issue by darkkalcor** [ilyhalight/voice-over-translation#847]
### Operating system / Операционная система

Windows 11 23H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

![Снимок экрана 2024-10-05 222517](https://github.com/user-attachments/assets/919cc0fc-f120-4b64-bec7-ab4d52f0876c)

### Additional information / Дополнительная информация

![Снимок экрана 2024-10-05 223648](https://github.com/user-attachments/assets/56fc9198-697f-4848-a443-3de9eeb6c2ef)

**Comment by ilyhalight** [comment]
Завершенные стримы = длинные видео, а их никогда не переводило. Перевод стримов есть только в лайве и то довольно кривой

**Comment by darkkalcor** [comment]
Я помню я стримы спокойно переводил, а сейчас что уже невозможно? Жаль.
