### ISSUE TITLE
Не работает в twitch

### ISSUE THREAD

**Issue by braintm** [ilyhalight/voice-over-translation#85]
Нет кнопки на твиче. Браузер firefox на винде

**Comment by ilyhalight** [comment]
На твиче перевод есть только в клипах (видео). Перевод самих трансляций не доступен.
Пример ссылки: https://www.twitch.tv/videos/ID
![изображение](https://user-images.githubusercontent.com/62353659/216665112-e91eca34-780a-468e-b3c5-ca695564e3fc.png)
