### ISSUE TITLE
Озвучивание текста без видео

### ISSUE THREAD

**Issue by redflasher** [ilyhalight/voice-over-translation#851]
### Describe your feature / Опишите ваше предложение

Была бы очень полезна функциональность для перевода текста в аудио, типа как тут: https://alkohole.github.io/machine-reading-text/
но с возможностью сохранения в аудио-файл на свой комп.
Готов поддержать донатом.

**Comment by ilyhalight** [comment]
Эту апишку нормально не получится использовать как tts. В любом случае минимально нужно будет видео + какие-никакие субтитры. Лучше используйте для tts специальные сервисы, вроде, того, что вы привели в примере
