### ISSUE TITLE
Изменяется интонация перевода при ускоренном просмотре

### ISSUE THREAD

**Issue by trydex** [ilyhalight/voice-over-translation#853]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1-beta1

### Describe the bug / Опишите ошибку

Несколько дней назад заметил, что при просмотре какого угодно перевода на скорости повышается и интонация перевода, появляется голос бурундука из мультика. При переводе через Яндекс.Браузер и просмотре на скорости 2х голос остается как на 1х. Баг?

**Comment by ilyhalight** [comment]
#849
