### ISSUE TITLE
failed to create request session

### ISSUE THREAD

**Issue by recoonn** [ilyhalight/voice-over-translation#856]
### Operating system / Операционная система

Windows 11 Pro 21H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1-beta1

### Describe the bug / Опишите ошибку

К сожалению перестал работать скрипт после обновления. 
Работаю через VPN Avast
до версии 1.7 все работало отлично, обновился до беты тоже самое
firefox 131.0.2 

Спасибо за Ваш труд.
![2024-10-11_22-45](https://github.com/user-attachments/assets/3f69ab35-8788-4740-b890-641e0f620a09)
![2024-10-11_22-47](https://github.com/user-attachments/assets/3819c29f-5c0d-4914-96fc-81fcdb304c64)

**Comment by ilyhalight** [comment]
У вас по какой-то причине домен воркера сменился на почту, либо вы сами случайно его сменили. Зайдите в меню расширения и установите адрес worker прокси-сервера равный `vot-worker.toil.cc`, как на скриншоте

![firefox_XZ3IprveMA](https://github.com/user-attachments/assets/b20227f5-e183-46f2-92b3-f9bed3e297e7)

**Comment by recoonn** [comment]
да огромное спасибо, действительно моя почта, только я ее не указывал там )) спасибо огромное
