### ISSUE TITLE
Safari 18 нет звука

### ISSUE THREAD

**Issue by Kerber0ss** [ilyhalight/voice-over-translation#857]
### Operating system / Операционная система

Macos 15.0.1

### Browser / Браузер

Safari

### Userscript manager / Скриптовый движок

UserScripts

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

Нет звука в видео при активации скрипта в youtube, vimeo. Настройки те-же что и в chrome, скрипт тоже. В chrome работает, в safari нет.
![image](https://github.com/user-attachments/assets/71ec77de-1f87-48be-a3fa-f83b21841e65)

**Comment by ilyhalight** [comment]
Проверьте бета версию, там, скорее всего, будет работать
