### ISSUE TITLE
Запоминал значение Громкость оригинала

### ISSUE THREAD

**Issue by AvenCores** [ilyhalight/voice-over-translation#86]
Хочу чтобы Слайдер громкости оригинала запоминал, то что я его ставлю на 0
Т.к я устал уже при каждом просмотре раз за разом перемещать слайдер с 15% до 0%

**Comment by miketype** [comment]
В начале кода в данной константе установите 0.
const defaultVideoVolume = 0.15; // 0.0 - 1.0 (0% - 100%) - default volume of the video with the translation (uses with option "autoSetVolumeYandexStyle")
