### ISSUE TITLE
расположение кнопки

### ISSUE THREAD

**Issue by Zutrex2597** [ilyhalight/voice-over-translation#864]
### Describe your feature / Опишите ваше предложение

кнопка перевести видео находиться поверх субтитров. Если есть возможность поменять расположение кнопки перевода видео или самих субтитров?

**Comment by Zutrex2597** [comment]
![{5A814CB7-2482-4DD0-AB38-5F73FD95CE4C}](https://github.com/user-attachments/assets/77085069-9cb0-486a-b2bf-e16ba852af51)

**Comment by SashaXser** [comment]
> ![{5A814CB7-2482-4DD0-AB38-5F73FD95CE4C}](https://private-user-images.githubusercontent.com/66751219/377239062-77085069-9cb0-486a-b2bf-e16ba852af51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMTY2MjksIm5iZiI6MTcyOTExNjMyOSwicGF0aCI6Ii82Njc1MTIxOS8zNzcyMzkwNjItNzcwODUwNjktOWNiMC00ODZhLWIyYmYtZTE2YmE4NTJhZjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDIyMDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZGQ5NGNlMzYwOGMxNTBiMGIyYzBkY2Q2ZjM0MzEyNGMxYTE1OGU2Y2I3YTI5MGY1ZjkwMmRhMDA5MWU2NDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nyxqHLWuEaWqP7iV4aN_30ziAulKFEB8rTSu5HuEy_Q)

Зажми кнопку и перемещай её в разные стороны.

**Comment by ilyhalight** [comment]
Зажмите ЛКМ на блоке с субтитрами и сможете перемещать блок в нужное место в пределах видео. Кнопку перевода, так же, можно перемещать, но она имеет только 3 фиксированных положения - в левой части, по центру и в правой части видео
