### ISSUE TITLE
Translation download button is not active as of today across several browesers

### ISSUE THREAD

**Issue by tornado197** [ilyhalight/voice-over-translation#868]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

v5.3.1.5

### Describe the bug / Опишите ошибку

Cant dowload translation on Youtube as of 21.10.24

### Additional information / Дополнительная информация

Tried on Yandex and Youtube.

**Comment by ilyhalight** [comment]
is it working, are there any errors in the console?

**Comment by Skatilsya** [comment]
Аддон не переводит недавние видео. Для старых (которые уже кто-то переводил ранее) -- аудио подгружается.

Ошибка в консоли:
[VOT] Failed to get yandex subtitles

**Comment by ilyhalight** [comment]
> [VOT] Failed to get yandex subtitles

это ошибка связана с тем, что субтитры не найдены или еще не сгенерировались. Она никак не относится к тому, что вы описали, но какие-то проблемы с переводом "новых" видео действительно есть

**Comment by ilyhalight** [comment]
> Аддон не переводит недавние видео

Исправлено в 1.7.1
