### ISSUE TITLE
Перевод минутных видео стал занимать очень много времени примерно неделю назад

### ISSUE THREAD

**Issue by Ilya0khiriv** [ilyhalight/voice-over-translation#871]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

Перевод минутных видео стал занимать очень много времени примерно неделю назад

Короктие видео на ютубе, включая шортсы, переводятся иногда по 20 минут

**Comment by ilyhalight** [comment]
[1#issuecomment-2436545027](https://github.com/ilyhalight/voice-over-translation/issues/1#issuecomment-2436545027)
