### ISSUE TITLE
Возможно, ли добавить Douyin.com?

### ISSUE THREAD

**Issue by MaksProger** [ilyhalight/voice-over-translation#876]
### Describe your feature / Опишите ваше предложение

Douyin так-то родственник TikTok, даже селектор CSS .xgplayer video выдает. Практически временные ссылки на видео чем то похожи. Например:
v16-webapp-prime.tiktok.com/video/....
v3-web-prime.douyinvod.com/video/....
Но все же они как земля и небо. Douyin более прокачен.  Поэтому стало интересно. Все таки часто я его открываю.

**Comment by ilyhalight** [comment]
Попробуйте эту версию. Не тестировал, но, вроде, должно работать

https://drive.google.com/file/d/185Zq6STP_AeLJH3UvU87mmLQi2WJ1YKO/view?usp=sharing

**Comment by MaksProger** [comment]
Нет кнопки, проверял и в ленте, на поисковой странице и отдельно ссылкой на конкретное видео. Если честно я уже пробовал такой фокус изменения в скрипте, tiktok на douyin, до написания темы.  Правда, только в браузере firefox 115.16.1esr (64-разрядный), на win 7, Tampermonkey BETA v5.3.6216 
Если заглянуть в консоль, инжектированный скрипт, выбивает ошибку. 
**Uncaught (in promise) VideoDataError: Entered unsupported link: "douyin"**
Я не думаю, что другой браузер или ОС исправит эту ошибку. 
Единственное что напрягает это  ссылки на видео, которые ведут на 
v3-dy-o.zjcdn.com или v3-web-prime.douyinvod.com т.е. на совсем другие домены, в отличие от тикток. 
По-хорошему мне нужно разобраться, как всё это работает. Конечно, чтобы разобраться на это нужно время и желание. Но машинный перевод с китайского, не соответствует действительности.  Желание здесь и пропадает. Тема скорее из любопытства. Просто douyin это не совсем tiktok.

**Comment by ilyhalight** [comment]
> **Uncaught (in promise) VideoDataError: Entered unsupported link: "douyin"**

Сейчас, перепроверил, оказалось, что у doyuin немного не так формируются пути на видео, как у тиктока (не указывается юзернейм в ссылке), отсюда и ошибка. Но все равно, Яндекс не умеет (либо работает криво с китайскими видео, ибо те же видео с doyuin залитые с прямыми ссылками выдают ошибки с неудачным переводом) в перевод ссылок на douyin, как в тиктоке, так, что, так просто, это бы не сработало.

**Comment by ilyhalight** [comment]
Пока закрою как нереализуемо, т.к. сомневаюсь, что в ближайшее время получится с этим что-то сделать

**Comment by MaksProger** [comment]
`не указывается юзернейм в ссылке` 
~~Я не понимаю.~~ Я не знаю, какие запросы должен делать скрипт.  И что, скармливается Яндекс переводчику. Я не интересовался этой темой. Поэтому ваше сообщение, не особо понятно для меня. Сам я раньше никогда не касался направления клиент - серверных приложений. Для меня это ново. После долгих раздумий, над вашим сообщением. Я все же решил написать сообщение. 
_К тому же я ошибочно сделал  вывод про плеер. Если в TikTok отчетливо видно, что страница использует npm-xgplayer, и для xgplayer спокойно можно посмотреть события, свойственные ему. У того же, например, bilibili, по событиям можно утверждать, что плеер скорее xgplayer. Но douyin, если открывать видео по ссылке, и заглянуть в ресурсы, название скриптов штук 9 с названием player-0 и т.д по порядку. Если даже на это не обращать внимание, то и событий (play, pause…) попросту нет. А на главной странице, событий через, чур, много. Не совсем стандартно._
![douyinlenta](https://github.com/user-attachments/assets/645dccd6-ef4f-45da-b3be-196f790cfd9c)
_И даже если скрипт расширение функционала плеера, скаченный с сайта «Жирная вилка» «HTML5视频播放工具» на главной странице douyin, еще условно работает, который понятное дело работает и на bilibili тоже, то по ссылке на видео, он превращает  страницу в белый фон, и в верхнем левом углу вечно надпись «Please wait…». Но это не столь важно, скрип может быть устаревшим. К тому же, скорее плеер будет влиять на воспроизведение дорожки (соответствие вашего скрипта). А дорожку еще надо получить. Но факт в том, что в пределах сайта не только шаблон прыгает. 
Конечно, я понимаю, если было бы так просто, эта тема и не создавалась. Можно было вписывать, например, douyin в bilibili. Но. Например, у били bvid в запросе, у доинг vid и другие есть различия. Та же маска для поиска ресурсов… Понятное дело результат будет, ожидаемо не рабочим. Если функция заточена именно под один шаблон._ 
![doubili](https://github.com/user-attachments/assets/f4cd7b62-2643-49cb-b99a-5ca675e1499c)
Конечно, я немного ознакомился со скриптом. Но на стороне клиента сделать что-то -  это одно.  А здесь совсем другое.  Даже что в переменных находиться, для чего они, как должен быть построен запрос, без понятия. И что должно находиться в нем. И также. Просто если Яндексу скармливается сслыка на страницу, первое сслылка шара с этого сайта, имеет вид  v.douyin.com/********/ и при переходе по ней становиться www.douyin.com/video/*, но обе ссылки рабочие, проверено через онлайн загрузчики.  Но опять же не все онлайн загрузчики могут работать с сайтом, хоть, и заявлена поддержка, скорее из-за частых изменений на сайте, что не всем быстро удается адаптироваться. Но по такому, если предположить худший вариант, Яндекс  сам производит манипуляции с сайтом и не умеет работать с таким сайтом, на ум приходит только одно. Я не разбирался в документации по доинг https://developer.open-douyin.com/docs-page в тех же API JS, например, в нюансах сознание worker. Но для меня, как вариант, проще промежуточный сервер, который условно буферизовал бы видео, чтобы привести к виду более понятному для скрипта. Грубо говоря, сайт конвертер, тупо гнать трафик, как бы через прокси. Но как я понимаю, пока это не требуется. 
`Яндекс не умеет (либо работает криво с китайскими видео… те же видео с doyuin залитые с прямыми ссылками выдают ошибки…)`
Сложное предложение, трудно перевариваемое. С одной стороны можно расценить, как не соответствует кодек для декодирования, у самого сервера Яндекса (Но MPEG AAC Audio (mp4a), так же на том же youtube используется, единственное, что компрессия и версия может повлиять), а с другой, что само аудио не усваивается. Да я понимаю, разные диалекты в каждой части Китая и дикция, плюс еще выражение каких-нибудь чувств. Но если диктор быстро и хорошо произносит речь, то и перевод получается, даже очень идеальным для переводчика. Проверял на обзоре одного фильма на били. За исключением, все же звуков в нашем языке больше, и аудиодорожка  идет в очень ускоренном произношении, чтобы не отстать от видео. И переводчик в переводе матом ругается, если переводит ссоры. К тому же, бывает, вроде девушка, а в переводе мужская озвучка. Задумываешься, как он догадался. Но это мелочи. По идее на том же douyin, такие обзоры он должен переводить.

**Comment by ilyhalight** [comment]
> Но по такому, если предположить худший вариант, Яндекс сам производит манипуляции с сайтом и не умеет работать с таким сайтом

Вероятно, Яндекс под капотом использует загрузку видео через yt-dlp. Это нам на руку т.к. позволяет переводить множество веб-сайтов без лишних конвертаций и т.п. Однако, проблема в том, что Яндекс не слишком часто его обновляет, либо использует свой форк более старых версий yt-dlp. Из-за этого иногда встречаются сайты, которые должны поддерживаться yt-dlp, но перевести видео на которых не удается. Один из таких сайтов Douyin.

> Сложное предложение, трудно перевариваемое

Если более простым языком.
Для перевода TikTok указывается обычная ссылка на видео. Например, https://www.tiktok.com/@USERNAME/video/VIDEO_ID. Дополнительные манипуляции с ссылкой никакие не проводятся. Яндекс сам скачивает видео и переводит его. Все работает.

Подобная ссылка для перевода Douyin не работает.
Перевод по ссылке на видео с CDN douyin (*.zjcdn.com,*.douyinvod.com) тоже не работает

> Перевод по ссылке на видео с CDN douyin (*.zjcdn.com,*.douyinvod.com) тоже не работает

Пока отвечал, кажется, случайно нашел причину из-за чего не работает перевод по ссылке на CDN douyin. Скорее всего, вина в каких-то спец символах внутри параметров ссылки. Если переделаю медиа прокси, то должно все-таки, получится добавить перевод. Пускай issue повисит, пока не проверю эту теорию

**Comment by MaksProger** [comment]
> Перевод по ссылке на видео с CDN douyin (_.zjcdn.com,_.douyinvod.com) тоже не работает.

А временные ссылки, например с Tiktok работают?  У меня, по крайней мере, нет.  Я до этого не писал, так как думаю, проверял уже. Да и конкретной информации у самого не было.

Эксперименты показали, временная сслылка остается рабочей в случае:
Tiktok – если удалить дополнительные параметры в ссылке (после знака вопроса), до expire, дальше ничего изменять нельзя, даже в значения, будет выдавать страницу, доступ запрещен.

> перевод по ссылке на CDN douyin. Скорее всего, вина в каких-то спец символах внутри параметров ссылки.

Douyin – можно всё удалить после знака, вместе с вопросом, оставив только ссылку, ссылка будет рабочей. 

Но как я понял из мануала по скрипту, Яндекс переводит все прямые ссылки, а значит, файервулы серверов не дают доступа на файлы по временным ссылкам.

_Я вспоминаю времена, когда интернет был не стабилен. К тому же когда появились файлообменники, в бесплатном аккаунте, скорость не позволяла скачать быстро. Качалось не один час, а при разрыве связи, приходилось закачку ставить по новой и не один раз. Рулили менеджеры закачек, так как можно было докачивать, но с динамическим IP, ссылка становилась не доступной, после нового подключения, приходилось заново перехватывать временную ссылку из браузера и изменять её на не докаченном файле. Т.е. была фильтрация по IP. 
Второе. User-Agent должен быть, такой же, как и у браузера, по которому выдается временная ссылка. Иначе скачивался файл, типа, доступ запрещен, если бы он открывался в браузере._ 

TikTok ссылки при открытии в другом браузере, доступ запрещен, в третьем также, даже при смене UserAgent , правда через дополнение, полностью вручную скопировав, на браузер в котором ссылка была получена.  Но там дополнительные параметры в ссылке, как token, не знаю, как работает, но понятное дело, другой браузер уже скорее и не откроет. К тому же сайт ни разу не открывался в этих браузерах, не пользуюсь этим ресурсом. 

Douyin временная ссылка с удаленными параметрами, да и целая, при смене IP, остается рабочей, даже проверено по WEB прокси. Но замечено, что не везде открывается. В другом браузере работает. Даже в IE древнем, VLC открывает. Но это естественно, так как у них есть дополнительные программы, например, загрузчик видео, понятное дело нажатие на сайте скачать, скачивание перейдет в программу, которая скорее и наложит водяные знаки. В принципе еще установлено и приложение для виндовс, но не пользуюсь, такая же веб версия, висит просто в фоне.  Поэтому все же прыжки из одного в другое, точно агент строго фиксироваться не будет. Да и при постоянном движении, например, со смартфона ip также может прыгать, подключаясь от точки к точки. Все таки там Китай. 

Единственное, что в голову приходит, посмотреть на поведение Яндекс переводчика, залив на сервер видео и скормив ему, и посмотреть параметры клиента, какой видео скачает, попробовать подстроиться под него. Получить временную ссылку с такими параметрами и скормить ему. По логике он должен иметь ~~поведение~~ параметры Яндекс браузера. Но Яндекс браузер мне запомнился, как шпион, который User-Agent тырил у браузера по умолчанию, со всеми данными. Сейчас не знаю.
Есть подозрение, но это не точно, если запрос к ресурсам делает уникальный клиент, например выдающий сервер, файервул может блокировать, как защиту от парсинга, в крайнем случае, даже может быть заблокирован ip. Выводы делать рано, так как не все проверено. Но по хорошему, по правилам, Яндекс сам должен получать временную ссылку.

**Comment by hugepower** [comment]
Видео по ссылке https://www.douyin.com/video/7414024495712718095 имеет постоянную ссылку для воспроизведения, которая выглядит следующим образом:

https://www.douyin.com/aweme/v1/play/?video_id=v0200fg10000crhueh7og65qq74l3r10&line=0

Эта ссылка ведет непосредственно к видео, и она будет работать стабильно, даже если исходная страница с видео изменится.

**Comment by MaksProger** [comment]
> https://www.douyin.com/aweme/v1/play/?video_id

Web API?

`https://www.douyin.com/aweme/v1/play/?{ video_id }`

example: 

https://v.douyin.com/irwRJJ2e/
https://www.douyin.com/aweme/v1/play/?video_id=v0300fg10000cr3i457og65vli2216a0

**Comment by ilyhalight** [comment]
> А временные ссылки, например с Tiktok работают?  У меня, по крайней мере, нет.  Я до этого не писал, так как думаю, проверял уже. Да и конкретной информации у самого не было.

Не проверял. Ибо, пока работает по обычной ссылке не было смысла тестировать с такими ссылками.

> Единственное, что в голову приходит, посмотреть на поведение Яндекс переводчика, залив на сервер видео и скормив ему, и посмотреть параметры клиента, какой видео скачает, попробовать подстроиться под него. Получить временную ссылку с такими параметрами и скормить ему. По логике он должен иметь ~~поведение~~ параметры Яндекс браузера. 

Сейчас, так и сделано. В самом Яндекс браузер список поддерживаемых сайтов очень скуден, поэтому в большинстве случаев, приходится додумывать самому как это могло бы работать. 

> https://www.douyin.com/aweme/v1/play/?video_id=v0200fg10000crhueh7og65qq74l3r10&line=0
>> Web API?

с проксированием такой ссылки, вроде бы, последний раз и тестировал. Она как раз и редиректит на один из их cdn (на какой точно - не помню)

**Comment by MaksProger** [comment]
> что с /aweme/... ссылкой или со ссылкой сразу на cdn - не хотел переводить

А здесь нет такого, при обращении Яндекс переводчика к сайту ресурсов, он тащит за собой кучу информации, типа я Яндекс? 
Потому что если, даже в теме пример ссылки с aweme, кликнуть на пример, и даже правой кнопкой открыть в новом окне выдаст ошибку 403. 
Только, открытие в новом приватном окне, или скопировав, вставив в адресную строку, тогда сервер дает доступ к ресурсам.

**Comment by ilyhalight** [comment]
> > что с /aweme/... ссылкой или со ссылкой сразу на cdn - не хотел переводить
> 
> А здесь нет такого, при обращении Яндекс переводчика к сайту ресурсов, он тащит за собой кучу информации, типа я Яндекс?

вроде нет

> Потому что если, даже в теме пример ссылки с aweme, кликнуть на пример, и даже правой кнопкой открыть в новом окне выдаст ошибку 403. Только, открытие в новом приватном окне, или скопировав, вставив в адресную строку, тогда сервер дает доступ к ресурсам.

видимо, у них в aweme сделана проверка на referer. Если он не пустой или не равен домену douyin, то возвращает ошибку

**Comment by ilyhalight** [comment]
> Если переделаю медиа прокси, то должно все-таки, получится добавить перевод

Действительно помогло

**Comment by MaksProger** [comment]
Спасибо огромное за проделанную работу. Не против, если я упомяну о расширении, где-нибудь в дзене в статье или оставлю ссылку на страницу проекта? 
**Да. Сейчас скрипт работает, _только по ссылкам на видео._ Работает нормально, плеер перевода четко слушается команд. На данный момент, если уж в остальных разделах сайта выдает ошибку, наверное скрипт проще отключить в остальных разделах.** 
Да, почему скрипт не работает на других страницах. Может только у меня, но пока не знаю. Логично, конечно, за это время, сайт douyin изменился. И даже как было вчера, уже сегодня немного по-другому. Он постоянно в движении.  Даже, заметил, логика плеера на главной странице, запрос видео, совсем не та как раньше. Если честно перевод в ленте может и не нужен. Просто мало, где бы там требовался, все равно прямые трансляции, которые попадаются в ленте, он не сумеет переводить, там другая логика. А на видеоролик всегда можно отрыть ссылку шару. Даже мысль была у меня раньше, предложить отключить скрипт на главной странице. 
Но позавчера, искал видео по самоделкам, конечно, видео приходилось открывать по шаре, чтобы услышать перевод. А ссылки шаре у них копируются, как и в обычном тик токе с заголовком, т.е. ссылку нужно еще обработать, что немного не удобно, если приходится открывать не одно видео, штуки 3-4 подряд.  Для себя я конечно могу накидать скрипт, доп кнопку в плеер на страницу, которая бы открывала видео из плеера в новой вкладке. Но это пока просто в мыслях.
Если честно, за все время было замечено, страница по шаре ссылке, остается практически не изменой, остальное всё движется. Скорее это не просто так, а для тех же поисковых систем, страницы на конкретные видео не затрагиваются. Потому что я пользовался китайским графом, где мне по кадру, он выдал ссылки и на douyin на конкретное видео.  Можно утверждать, что эти страницы индексируются поисковиками. И не трогаются разработчиками. Поэтому, можно попробовать и такую логику, подготовить ссылку скрипту VOT, если он выдает ошибку по videodata в других разделах сайта (я сам не разбирался, почему, времени пока нет). Может, будет проще получать её параллельно пользовательским скриптом по шаре. Т.е. как бы скрипт сделать неактивным, пока не будет действие пользователя в плеере. Т.е. отдавать ссылку скрипту, когда это действительно нужно. Потому что на сайте есть сейчас разделы, где есть всплывающий плеер, это и в поиске и на странице пользователя. Просто, я считаю, более надежное, что при следующем изменении на этих страницах, скрипт все равно сможет получить ссылку.

**Comment by ilyhalight** [comment]
> Не против, если я упомяну о расширении, где-нибудь в дзене в статье или оставлю ссылку на страницу проекта?

Не против

> Да, почему скрипт не работает на других страницах. Может только у меня, но пока не знаю

Сейчас, в скрипте получение айдишника видео на Douyin сделано по содержимому пути внутри ссылки, если в ссылке есть `/video/VIDEO_ID`, то часть `VIDEO_ID` и считается айдишником, соответственно, там скрипт запускается, в противном случае не активируется. Вечером сделаю, чтобы работал и в других местах, где есть плеер

**Comment by MaksProger** [comment]
Доброго времени. В последнее время появилась проблема c 抖音. Если перевести видео в ленте и далее листать, перевод начинает проигрываться на некоторых других видео, даже если они не совпадают по длине. Пролистывая назад вперед, оно как будто привязывается по какому то идентификатору, а не в хаотичном порядке в виде глюка. Причем не как не привязан к кнопке VOT, если на этом видео нажать перевод, то уже вместе с этим переводом проигрывается та звуковая дорожка. Я конечно не как не разбирался что не так. Но я точно скажу это не связано с  VOT, такое поведение началось еще в старой версии, в которой было все нормально. У меня браузер старый и обновления сломаны, он не как не обновляется в этой ОС. 
Версия:1.10.5
Загрузчик:Tampermonkey v5.4.6228Браузер:Firefox 115.0 (Windows NT 6.1)
Единственное, могло, что-то измениться на сайте, что привело к этой проблеме. Либо может, что-то у меня сломалось, например сам Tampermonkey. Пока на других устройствах не проверял.  В последнее время мало пользуюсь интернетом. Но это было замечено, где то месяца 2 назад. Когда у старой версии VOT появились незначительные глюки на этом сайте. Что указывает на какие то изменения в скриптах.

**Comment by MaksProger** [comment]
Привет. В мобильной версии firefox nightly 143.0a1 android 15 тоже самое. Почему nightly, так как в мобильной обычной версии нельзя сменить DoH, а без смены на европейский, этот сайт не открывается нормально. 
Поведение, если перевести видео в ленте и дальше листать, то строго через пару видео, на 3 видео запускается перевод, листаешь дальше также через два запускается этот же перевод. Пробовал разные инжекторы, но от них ничего не зависит. 
Если в смартфоне включить версию для ПК, то в версии для ПК стало все совсем печально. Он вообще стал выбивать ошибку, что не удалось перевести видео или как в мобильном вообще высвечивает непонятную ошибку.  Поведение на ПК в старом браузере, который я указывал выше тоже самое. Хоть и не осуществляется поддержка по старым браузерам, но как я уже упоминал, это не относиться к версии браузера. Мне удобней указать, что то из них.  
Итак, на ПК в версию скрипта 1.10.5 я немного добавил консольного вывода

<img width="1267" height="658" alt="Image" src="https://github.com/user-attachments/assets/bd288b9c-bd07-412d-9430-ac442e35b442" />

Но не чего особенного не заметил, ссылка нормальная 

<img width="1227" height="507" alt="Image" src="https://github.com/user-attachments/assets/38dd5165-e242-4371-9ef6-360de89f811f" />

Но вот она ошибка 

<img width="1245" height="237" alt="Image" src="https://github.com/user-attachments/assets/69139b0e-1b1f-42a5-b69c-c3ce48806fee" />

Далее перевод в адаптивный режим, устройство выбрано галакси 10+
Данные вроде такие же 

<img width="1237" height="501" alt="Image" src="https://github.com/user-attachments/assets/4c035103-fcfa-480c-b886-f88c7600046c" />

Здесь мы получаем перевод, т.е. не каких ошибок 

<img width="1215" height="303" alt="Image" src="https://github.com/user-attachments/assets/fb23dde0-4b8f-416d-8f21-53814c807591" />

И тот же перевод уже запускается здесь, сам по себе

<img width="1239" height="441" alt="Image" src="https://github.com/user-attachments/assets/d98ea83f-137f-4cf0-9d9d-595b8d046104" />

Как я понимаю, мои догадки, ошибка не в переводе, ссылка и перевод как бы работает без проблем, а все возникает при получении перевода. Так как на сайте скорее изменились скрипты и перевод нормально встроется не может?

**Comment by MaksProger** [comment]
Доброго времени. По хорошему нужно бы исправить.  
Забудь про недоступность перевода, это скорее с яндекс что-то. 
А вот проблема с мобильной версией наверное связана с какими нибудь изменениями на сайте. Итак обобщаю.

Описание проблемы:
В мобильной версии Douyin (как в настоящем мобильном браузере, так и в режиме эмуляции на ПК "UserAgent") возникает проблема с автоматическим воспроизведением кешированных аудио переводов. После прокрутки ленты на 3 видео вперед или назад, ранее переведенные аудио дорожка начинает воспроизводиться автоматически на текущем активном видео.

Ключевые наблюдения:
    Проблема проявляется с четкой периодичностью (каждые 3 видео: 1-3-6-9...)
    Связана с моментом удаления DOM-контейнеров видео в мобильной версии
    В десктопной версии сейчас проблемы нет
    Аудио плеер не привязан к жизненному циклу видео-контейнера
    При удалении контейнера аудио продолжает работать и потом "прикрепляется" к другому видео

Диагностика:
При мониторинге обнаружено, что:
    Видео контейнеры в мобильной версии удаляются при прокрутке
    Аудио элементы создаются, но не уничтожаются при удалении родительского контейнера
    MutationObserver фиксирует удаление контейнеров, но VOT не реагирует на это

Временное решение:
Я добавил код, который принудительно останавливает все аудио элементы при удалении любого видео контейнера:

``` 
// Специальный фикс для мобильной версии Douyin
console.log('=== MOBILE DOUYIN FIX ===');

// Определяем, что мы в мобильной версии
const isMobileVersion = window.innerWidth <= 768 || 
                       navigator.userAgent.includes('Mobile') ||
                       document.querySelector('.xgplayer-mobile');

if (isMobileVersion) {
    console.log('📱 Mobile version detected, applying special fix');
    
    // Глобальный реестр активных аудиоплееров
    window.votAudioPlayers = new Map();
    
    // Перехватываем создание аудио элементов в VOT
    const originalAudio = window.Audio;
    window.Audio = function(src) {
        const audio = new originalAudio(src);
        
        // Регистрируем аудио элемент
        const audioId = Date.now() + Math.random();
        window.votAudioPlayers.set(audioId, {
            element: audio,
            src: src,
            createdAt: Date.now(),
            videoId: getCurrentVideoId()
        });
        
        console.log('🎵 Registered VOT audio player:', audioId);
        
        // Добавляем метод для удаления
        audio._votId = audioId;
        audio.removeVOT = function() {
            if (window.votAudioPlayers.has(audioId)) {
                this.pause();
                this.src = '';
                window.votAudioPlayers.delete(audioId);
                console.log('🗑️ Removed VOT audio player:', audioId);
            }
        };
        
        return audio;
    };
    
    // Функция для получения ID текущего видео
    function getCurrentVideoId() {
        const video = document.querySelector('video');
        const container = video?.closest('.xg-video-container');
        return container?.getAttribute('data-xgplayerid') || 'unknown';
    }
    
    // Улучшенный мониторинг удаления видео контейнеров
    const mobileObserver = new MutationObserver((mutations) => {
        mutations.forEach((mutation) => {
            mutation.removedNodes.forEach((node) => {
                if (node.nodeType === 1 && 
                    (node.classList?.contains('xg-video-container') || 
                     node.querySelector?.('.xg-video-container'))) {
                    
                    console.log('📱 Mobile: Video container removed, cleaning up audio');
                    
                    // Останавливаем ВСЕ аудиоплееры VOT при удалении любого контейнера
                    stopAllVOTAudio();
                }
            });
        });
    });
    
    mobileObserver.observe(document.body, {
        childList: true,
        subtree: true
    });
    
    // Функция остановки всех аудиоплееров VOT
    function stopAllVOTAudio() {
        console.log('🛑 Stopping ALL VOT audio players');
        
        window.votAudioPlayers.forEach((player, id) => {
            try {
                player.element.pause();
                player.element.currentTime = 0;
                player.element.src = '';
                console.log('✅ Stopped VOT audio:', id);
            } catch (e) {
                console.log('❌ Error stopping audio:', id, e);
            }
        });
        
        // Также очищаем все стандартные audio элементы
        document.querySelectorAll('audio').forEach(audio => {
            if (!audio._votId) { // Если это не зарегистрированный VOT аудио
                try {
                    audio.pause();
                    audio.currentTime = 0;
                } catch (e) {
                    // Игнорируем ошибки
                }
            }
        });
    }
    
    // Дополнительная защита: останавливаем аудио при скролле
    let scrollTimer;
    window.addEventListener('scroll', () => {
        clearTimeout(scrollTimer);
        scrollTimer = setTimeout(() => {
            // После завершения скролла проверяем, не нужно ли остановить аудио
            const currentVideo = document.querySelector('video');
            if (!currentVideo || currentVideo.paused) {
                stopAllVOTAudio();
            }
        }, 500);
    });
    
    // Восстанавливаем аудио только для текущего видео при взаимодействии
    document.addEventListener('click', (e) => {
        if (e.target.textContent.includes('перевод') || 
            e.target.textContent.includes('translate')) {
            // При ручном запуске перевода сначала очищаем все старые аудио
            stopAllVOTAudio();
        }
    });
} 
```
