### ISSUE TITLE
Пропала кнопка в YouTube "Перевести видео"

### ISSUE THREAD

**Issue by RomzdikHub** [ilyhalight/voice-over-translation#878]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

Пропала кнопка в YouTube "Перевести видео", что делать?

**Comment by meganekka87** [comment]
тож перестала недавно кнопка появлятся. был 1.7, поставил 1.7.1beta4 - ниче не поменялось

Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at proxy.js:39:59
    at Array.forEach (<anonymous>)
    at overrideProperty (proxy.js:37:36)
    at proxy.js:365:17
    at Array.forEach (<anonymous>)
    at injectProxy (proxy.js:364:36)
    at injectProxyAndCleanup (proxy.js:492:9)
    at HTMLDocument.dataReceiver (proxy.js:516:9)

LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.

desktop_polymer.js:7301 Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by konservat0r** [comment]
аналогично, нет кнопки перевода. 
![Screenshot_9](https://github.com/user-attachments/assets/ba7ee2a1-6a1c-4caa-aea6-4c8c5e6ed00a)

**Comment by vbsmalta** [comment]
Такая же фигня, Пропала кнопка в YouTube "Перевести видео" win 11 chrоme Версия 130.0.6723.70

**Comment by Roman19801** [comment]
не появилась?

**Comment by Roman19801** [comment]
> > Такая же фигня, Пропала кнопка в YouTube "Перевести видео" win 11 chrоme Версия 130.0.6723.70
> 
> Точно такой же конфиг и все работает, попробуйте обновиться до последней версии расширения или до беты. Возможно, ютуб что-то выборочно тестирует и из-за этого сломалось, либо конфликтует с каким-то из других установленных расширений `¯\_(ツ)_/¯`

Что обновить нужно?)

**Comment by ilyhalight** [comment]
> > > Такая же фигня, Пропала кнопка в YouTube "Перевести видео" win 11 chrоme Версия 130.0.6723.70
> > 
> > 
> > Точно такой же конфиг и все работает, попробуйте обновиться до последней версии расширения или до беты. Возможно, ютуб что-то выборочно тестирует и из-за этого сломалось, либо конфликтует с каким-то из других установленных расширений `¯\_(ツ)_/¯`
> 
> Что обновить нужно?)

[расширение](https://github.com/ilyhalight/voice-over-translation/releases)

**Comment by Roman19801** [comment]
> > > > Такая женька, Пропала кнопка в YouTube "Перевести відео" win 11 chrome Версія 130.0.6723.70
> > > 
> > > 
> > > Точно такий же конфіг і все працює, спробуйте оновити до останньої версії розширення або додати. Можливо, що-то вибірково тестується і із-за цього сломалось, або конфліктує з яким-то з інших встановлених розширень`¯\_(ツ)_/¯`
> > 
> > 
> > Що потрібно відновити?)
> 
> [розширення](https://github.com/ilyhalight/voice-over-translation/releases)

![image_2024-10-31_21-25-16](https://github.com/user-attachments/assets/2f2dbc81-9987-4d35-83b0-da7c123cdf1c)
А какой скрипт использовать?

**Comment by ilyhalight** [comment]
> > > > > Такая женька, Пропала кнопка в YouTube "Перевести відео" win 11 chrome Версія 130.0.6723.70
> > > > 
> > > > 
> > > > Точно такий же конфіг і все працює, спробуйте оновити до останньої версії розширення або додати. Можливо, що-то вибірково тестується і із-за цього сломалось, або конфліктує з яким-то з інших встановлених розширень`¯\_(ツ)_/¯`
> > > 
> > > 
> > > Що потрібно відновити?)
> > 
> > 
> > [розширення](https://github.com/ilyhalight/voice-over-translation/releases)
> 
> ![image_2024-10-31_21-25-16](https://private-user-images.githubusercontent.com/161028267/382089152-2f2dbc81-9987-4d35-83b0-da7c123cdf1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MDQ1MTIsIm5iZiI6MTczMDQwNDIxMiwicGF0aCI6Ii8xNjEwMjgyNjcvMzgyMDg5MTUyLTJmMmRiYzgxLTk5ODctNGQzNS04M2IwLWRhN2MxMjNjZGYxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMVQxOTUwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmU4ODc1YWY3OWZhY2FkMGJmNjllMTNhMGFhZjE1MmE1NDExNGY1Zjk4ZjVjYTdmNGMxY2NjZGNlODM2MDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nhxeMZNlZWMg1-ZtZ76S2mYab5xfjyFJsw1yxMD7nPI) А какой скрипт использовать?

второй

**Comment by vbsmalta** [comment]
обновился до 1.7.1-beta4 - Не помогло. Кнопка "Перевести видео" так и не появилась

**Comment by Roman19801** [comment]
Тоже не помогло

**Comment by Volan16** [comment]
Может у вы не включили режим разработчика? 
https://github.com/ilyhalight/voice-over-translation/issues/662#issuecomment-2160768958

**Comment by vbsmalta** [comment]
> Может у вас выключен режим разработчика?

Вот Спасибо тебе Добрый человек!   Точно! Теперь заработало!

**Comment by lllqtop** [comment]
если кому не помогает, причиной наверно является конфликт с другими расширениями, скорее всего блокировщик рекламы, в нем вам надо добавить tapmonkey в список безопасных хостов (по-моему так называется) ну или просто перезапустите блокировщик рекламы и др расширения
