### ISSUE TITLE
Linkedin learning

### ISSUE THREAD

**Issue by FRM513** [ilyhalight/voice-over-translation#882]
### Describe your feature / Опишите ваше предложение

Подскажите, пожалуйста,   поддерживается ли перевод видео курсов? У меня не получается проверить, хотя в списке сайтов линкедин указан.
 Если не поддерживается - добавьте, пожалуйста.

**Comment by MaksProger** [comment]
Должен работать. 

![Linkedin](https://github.com/user-attachments/assets/5d30a38f-530b-470e-9a61-faa512c99802)

**Comment by FRM513** [comment]
У меня работает расширение, но при воспроизведении видео нет иконки включить отключить. Это только на этом сайте не работает 
![image](https://github.com/user-attachments/assets/53267e66-ee9c-41d5-b04c-c64688ddf6d4)

**Comment by MaksProger** [comment]
Мало информации. Попробуйте firefox. У меня firefox 115.16.1esr, Tampermonkey v5.3.6216 beta. Скрипт сейчас из темы douyin. Но сайт также есть в официальном скрипте. 
Проверьте адресную строку сайта. Попробуйте не входить в аккаунт. Должно быть также как у меня. Присмотритесь к антивирусному ПО или плагинам, не блокируют ли они скрипты. 
![agile](https://github.com/user-attachments/assets/1d20bcec-8227-46ac-9c52-09cefc2eaeb2)

**Comment by FRM513** [comment]
Спасибо за помощь!
Попробовал как вы рекомендовали, получилось с Firefox.
Протестировал Chrome  и Edge. тоже заработало.
Причина  была в том, что не нужно входить в аккаунт, тогда работает исправно.

Подскажите пожалуйста, планируется ли обойти данное ограничение, так как под аккаунтом удобно смотреть курсы, потому что ведется прогресс обучения. Спасибо

**Comment by ilyhalight** [comment]
> Спасибо за помощь! Попробовал как вы рекомендовали, получилось с Firefox. Протестировал Chrome и Edge. тоже заработало. Причина была в том, что не нужно входить в аккаунт, тогда работает исправно.
> 
> Подскажите пожалуйста, планируется ли обойти данное ограничение, так как под аккаунтом удобно смотреть курсы, потому что ведется прогресс обучения. Спасибо

Выглядит так, как-будто с входом в аккаунт меняется плеер, нужно будет глянуть

**Comment by FRM513** [comment]
Буду ждать апдейта. Надеюсь, у вас получится это  пофиксить. Очень было бы полезно и я бы вас отблагодарил.
Спасибо)
