### ISSUE TITLE
Перестали работать горячее клавиши мультимедии Windows на 1.7.1-beta3 и 1.7.1-beta4

### ISSUE THREAD

**Issue by souie-bit** [ilyhalight/voice-over-translation#884]
### Operating system / Операционная система

win 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1-beta3

### Describe the bug / Опишите ошибку

На 1.7.1-beta1 они работали отлично, а 1.7.1-beta3 и 1.7.1-beta4 перестали работать.

**Comment by A007jb** [comment]
сегодня у меня такая ошибка вылазит, что делать?
![image](https://github.com/user-attachments/assets/956a2041-2e7c-488a-82ca-47eeb3caf65c)

**Comment by AAntaresAA** [comment]
> сегодня у меня такая ошибка вылазит, что делать? ![image](https://private-user-images.githubusercontent.com/187110671/382472970-956a2041-2e7c-488a-82ca-47eeb3caf65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTQwMzIsIm5iZiI6MTczMDU1MzczMiwicGF0aCI6Ii8xODcxMTA2NzEvMzgyNDcyOTcwLTk1NmEyMDQxLTJlN2MtNDg4YS04MmNhLTQ3ZWViM2NhZjY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMzIyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2IyM2M3NGZkZWNlMmRmNWJlZWVjZTE5MGZmMGRlYjVkMDUwMjMyNTQ1ODk4NGQwMzRkMGM0NGZmODExYTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X592oSzD9Q32CO1kkWc99chkBknTUFFG0LtOVAlXamw)
у меня тоже самое, перевод не работает

**Comment by Mihail990** [comment]
> сегодня у меня такая ошибка вылазит, что делать? ![image](https://private-user-images.githubusercontent.com/187110671/382472970-956a2041-2e7c-488a-82ca-47eeb3caf65c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NTQwMTgsIm5iZiI6MTczMDU1MzcxOCwicGF0aCI6Ii8xODcxMTA2NzEvMzgyNDcyOTcwLTk1NmEyMDQxLTJlN2MtNDg4YS04MmNhLTQ3ZWViM2NhZjY1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMlQxMzIxNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWZmOWY5MDk1YjU4MjcxMmY3NGUwYTUwMGNmNTZlMmNkMTY2NjllNTU4ODlkNDFjZjkwMDdhOWQ1MTkwNGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5lXVPDoxM6cSQROPM3lUEyV-TnVbdBnphCWnH2MNDrs)

тоже самое

**Comment by souie-bit** [comment]
@AAntaresAA @A007jb обновите скрипт https://github.com/ilyhalight/voice-over-translation/discussions/880

**Comment by AAntaresAA** [comment]
> @AAntaresAA @A007jb обновите скрипт #875

не требуется, последняя версия

**Comment by Mihail990** [comment]
<img width="465" alt="Screenshot_22" src="https://github.com/user-attachments/assets/a035080b-6015-48ba-a230-e8dfdb74930c">
на 1.7.1 бета 4 тоже самое

**Comment by souie-bit** [comment]
@Mihail990 моя ссылка ведёт на 1.7.1-beta3 она работает.

**Comment by Mihail990** [comment]
> @Mihail990моя ссылка ведет на 1.7.1-beta3 она работает.

На третьей тоже самое..
<img width="491" alt="Screenshot_24" src="https://github.com/user-attachments/assets/adcb9c86-2de0-4885-8ffd-b832338ae39c">
<img width="524" alt="Screenshot_25" src="https://github.com/user-attachments/assets/13151555-9f72-492f-ad3d-8f9079d9daf7">

**Comment by souie-bit** [comment]
@Mihail990 открываешь видео. Нажимаешь перевод не переводится F5 и работает.

**Comment by Mihail990** [comment]
> @Mihail990открываешь видео. Нажимаешь перевод, не переводится F5 и работает.

Просто переустановил Tampermonkey, заработала 4 бета

**Comment by ilyhalight** [comment]
> На 1.7.1-beta1 они работали отлично, а 1.7.1-beta3 и 1.7.1-beta4 перестали работать.

актируйте в меню расширения новый плеер и будут работать, так же убедитесь, что не стоит галочка "Использовать только для обхода Media CSP".

**Comment by FiLinX** [comment]
> актируйте в меню расширения новый плеер и будут работать, так же убедитесь, что не стоит галочка "Использовать только для обхода Media CSP".

да, при этих настройках медиаклавиши работают, но у меня при них наблюдается глюк звука - https://files.catbox.moe/rusc4f.mp4
при включении же "Использовать только для обхода Media CSP", или вообще отключении нового плеера  -  звук становится нормален, но медиаклавиши уже не работают..
1.7.1-beta4, Ирон хромиум 118, и темпермонка 5.1.1

**Comment by ilyhalight** [comment]
> > актируйте в меню расширения новый плеер и будут работать, так же убедитесь, что не стоит галочка "Использовать только для обхода Media CSP".
> 
> да, при этих настройках медиаклавиши работают, но у меня при них наблюдается глюк звука - https://fex.net/s/3m0dt2c при включении же "Использовать только для обхода Media CSP", или вообще отключении нового плеера - звук становится нормален, но медиаклавиши уже не работают.. 1.7.1-beta4, Ирон хромиум 118, и темпермонка 5.1.1

Возможно, как-то связано с браузером. Не встречал в других браузерах подобного 🤔
