### ISSUE TITLE
Перевод без звука диктора.

### ISSUE THREAD

**Issue by MARAN1GHTON** [ilyhalight/voice-over-translation#887]
### Operating system / Операционная система

Windows 10 22h2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1 beta 4

### Describe the bug / Опишите ошибку

При включении видео может выдать ошибку, о проблеме запроса на перевод, но при повторном нажатии на кнопку перевода видео прога переводит и кнопка перекрашивается в синий, а в опциях можно включить русские субтитры. Однако  диктор молчит и сколько бы громокости не ставь - будет тишина.

### Additional information / Дополнительная информация

Было проверено в хроме, опере и фоксе. Также сначала стояла 1.7.1. версия расширения, после встречи с проблемой обновил до последней безрезультатно. Стоит упомянуть, что проблема не у всех видео, некоторые лагают и после некоторого времени голос диктора может заработать, а в некоторых так и не удаётся получить запрос на перевод. Видео с которым проблемы: https://www.youtube.com/watch?v=AfOMAkzD0dU

**Comment by MARAN1GHTON** [comment]
Все советы не помогли, оба прокси в хранилище поставил на 0 в обоих случаях, но звука также нет. У друга на маке при этом всё работает из коробки, при чём любое видео (даже до 3ёх часов он мог хавать и не жаловаться). Я было подумал что дело с впн, хотя такого раньше не было, да и сейчас включая и выключая результат один и тот же.

**Comment by wingstrong** [comment]
У меня то же самое. Либо нет голоса, сколько ни жди (хоть для 1-минутного видео) либо Не удалось перевести, либо Failed to create session, а перевод да еще и с голосом включается в 1 видео из 10

**Comment by ilyhalight** [comment]
Переустановите скрипт через кнопку на главной репозитория. Должно заработать
