### ISSUE TITLE
не работает перевод

### ISSUE THREAD

**Issue by Kzander3000** [ilyhalight/voice-over-translation#889]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.2.3.

### Describe the bug / Опишите ошибку

Перестал работать перевод.
Я читал, что можно установить старую версию. Установил в пятницу 1.7.1 beta 4 и перевод работал, но сегодня перестал и он работать. Пробовал установить значения 0 в хранилище, не помогло. Что нужно сделать?
![image](https://github.com/user-attachments/assets/930b09f0-4b3c-442b-8d12-dc5c6465ad1a)

**Comment by mad24md** [comment]
Мне помогло вот [это](https://github.com/ilyhalight/voice-over-translation/issues/885#issuecomment-2452997914)

**Comment by zacisco** [comment]
на chrome-based браузере тоже перестало работать
на огнелисе помогло переустановить скрипт из совета выше
а на вивальди нет
![image](https://github.com/user-attachments/assets/66fcd36a-1a92-4b89-aba6-7e849d0f2266)
получаю такую ошибку (Failed to request create session)
