### ISSUE TITLE
Перевод начинается заново при перемотке видео

### ISSUE THREAD

**Issue by hrihoriart** [ilyhalight/voice-over-translation#890]
### Operating system / Операционная система

Windows 11 Home 23H2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.0

### Describe the bug / Опишите ошибку

При любой перемотке видео, перевод сбрасывается в начало. Необходима какая-то принудительная синхронизация

**Comment by ilyhalight** [comment]
Попробуйте обновиться до последней беты, должно помочь

**Comment by hrihoriart** [comment]
> Попробуйте обновиться до последней беты, должно помочь

уже испробовал разные бетки вплоть до 4й и не спасло. Устанавливал и перезагружал браузер и тестил, всё так же

**Comment by ilyhalight** [comment]
проверьте сейчас

**Comment by hrihoriart** [comment]
> проверьте сейчас

снова поставил бетку 4 и пока хорошо всё
