### ISSUE TITLE
При открытии нового видео перевод не производится 

### ISSUE THREAD

**Issue by A007jb** [ilyhalight/voice-over-translation#894]
### Operating system / Операционная система

Windows 11 24h2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1

### Describe the bug / Опишите ошибку

При открытии нового видео перевод не производится, а только после обновления страницы перевод воспроизводится

**Comment by ilyhalight** [comment]
> Аналогично с 1.7.1 перевод не работает, откат на 1.7.0 помог (на данный момент времени).

скорее помог не откат, а то, что из-за отката убралась настройка проксирования запроса #885

**Comment by ilyhalight** [comment]
> При открытии нового видео перевод не производится, а только после обновления страницы перевод воспроизводится

предоставьте логи консоли

**Comment by katzsmile** [comment]
Проблема решается просто. Нужно зайти в настройки скрипта, далее в Хранилище, и удалить все параметры оставив только пустые { } и сохранить, затем просто настроить скрипт заново и все работает. Проверено на 1.7.0 и 1.7.1

**Comment by masterwishx** [comment]
> Проблема решается просто. Нужно зайти в настройки скрипта, далее в Хранилище, и удалить все параметры оставив только пустые { } и сохранить, затем просто настроить скрипт заново и все работает. Проверено на 1.7.0 и 1.7.1

Sorry not working for me ...

**Comment by ilyhalight** [comment]
Переустановите скрипт через кнопку на главной репозитория. Должно заработать

**Comment by masterwishx** [comment]
> Переустановите скрипт через кнопку на главной репозитория. Должно заработать

Working fine now , 
Very strange ,  but after disabled and enabled Adguard the script is working now v1.7.1
