### ISSUE TITLE
Расширение загружает другую звуковую дорожку нежели чем Яндекс Браузер

### ISSUE THREAD

**Issue by MixxxGit** [ilyhalight/voice-over-translation#897]
### Operating system / Операционная система

Win10 x64 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

AdGuard

### Script version / Версия скрипта

1.7.1

### Describe the bug / Опишите ошибку

Это не баг а больше смахивает на фичу, но все равно остаются вопросы.
Только что заметил что для некоторых особо популярных  видосов с большим количеством просмотров загружается высококласcная аудиодорожка с хорошим переводом и где голоса роботов очень сильно похожи на голоса спикеров.
Например 
https://www.youtube.com/watch?v=fRyyTAs1XY8
https://www.youtube.com/watch?v=7qZl_5xHoBw
https://www.youtube.com/watch?v=hBMoPUAeLnY
Что бы не быть голословным даю ссылку на хорошую дорожку с последнего ролика
https://drive.google.com/file/d/16Er1bRhmebh6Ih_PLNoPwzxRGvyAIG8y/view?usp=sharing

Но в яндекс браузере через его стандартный интерфейс активации перевода видео загружается обычная дорожка со стандартными голосами. Почему такая разница?
Складывается ощущение что у команды яндекса есть более качественная модель для перевода видео но они её применяют выборочно  (видимо она кушает больше ресурсов) и не сразу а только для популярных видео но это не объясняет почему из яндекс браузера грузится обычная  звуковая дорожка.

**Comment by ilyhalight** [comment]
Вероятно, нашел настройку, что отвечает за такое поведение. Интересно, что раньше в яндекс браузере она тоже была включенной, но в последней версии ее там выключили, видимо, из-за ошибок, когда в одном диалоге голос одного и того же человека постоянно менялся (вроде, это даже где-то тут в issues репортили, но не найду что-то)

**Comment by pinkigerls** [comment]
https://www.youtube.com/watch?v=BF8KNzj2w40

если что, сегодня нашел вот такое вот видео, которое имеет меньше, чем 1.2 млн просмотров. всего лишь 284000. я думаю, здесь исключение сделали только ради того, что это очень популярная новостная газета.

**Comment by mrkhachaturov** [comment]
https://www.youtube.com/watch?v=7Jon_cAK_to&t=303s

Всего 179 000 просмотров и перевод с новым голосом
