### ISSUE TITLE
qutebrowser

### ISSUE THREAD

**Issue by GutsyHeart** [ilyhalight/voice-over-translation#9]
Можно ли как то заставить работать в qutebrowser?
Пишет "Не удалось запросить перевод видео"

**Comment by ilyhalight** [comment]
Как будет время постараюсь добавить поддержку этого браузера

**Comment by ilyhalight** [comment]
К сожалению, заставить работать расширение мне не удается из-за ошибки с CORS + неудачных подключений к YandexAPI (насколько я понимаю - это из-за ограничений описанных в [faq#18.1](https://www.qutebrowser.org/doc/faq.html), хотя может быть - это я что-то не донастроил в qutebrowser)
