### ISSUE TITLE
Формат аудио не поддерживается

### ISSUE THREAD

**Issue by flowing-abyss** [ilyhalight/voice-over-translation#90]
Не озвучивает видео ни в Firefox (v109.0.1), ни в Chromium (v110.0.5481.77). Подскажите, пожалуйста, как понять в чём именно заключается проблема?
![image](https://user-images.githubusercontent.com/98622217/218109842-bc1586eb-ca55-4b9e-a8ac-fb64bb06f85e.png)

**Comment by flowing-abyss** [comment]
Выдало две ошибки.
Первая:

DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable. Voice Over Translations.user.js:1192:21
    lipSync moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1192
    (Асинхронный: promise callback)
    lipSync moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1191
    translateFunc moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1084
    dispatch moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    handle moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    (Асинхронный: EventListener.handleEvent)
    add moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    Ee moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    each moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    each moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    Ee moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    on moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    translateFunc moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1080
    translateVideo moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:368
    onload moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:345
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    i https://www.youtube.com/watch?v=Cfr4YNbKrB8:34
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    r https://www.youtube.com/watch?v=Cfr4YNbKrB8:22
    Fo https://www.youtube.com/watch?v=Cfr4YNbKrB8:23
    g https://www.youtube.com/watch?v=Cfr4YNbKrB8:67
    g https://www.youtube.com/watch?v=Cfr4YNbKrB8:67
    (Асинхронный: Async)
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    p https://www.youtube.com/watch?v=Cfr4YNbKrB8:67

Вторая ошибка:

Uncaught (in promise) VOT: Формат аудио не поддерживается Voice Over Translations.user.js:1202:17
    lipSync moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1202
    (Асинхронный: promise callback)
    lipSync moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1191
    translateFunc moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1084
    dispatch moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    handle moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    (Асинхронный: EventListener.handleEvent)
    add moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    Ee moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    each moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    each moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    Ee moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    on moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:3
    translateFunc moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:1080
    translateVideo moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:368
    onload moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/userscripts/Voice Over Translations.user.js?id=d80acced-b8c8-4203-9405-d26467cd8d93:345
    call self-hosted:1356
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    i https://www.youtube.com/watch?v=Cfr4YNbKrB8:34
    call self-hosted:1356
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    r https://www.youtube.com/watch?v=Cfr4YNbKrB8:22
    Fo https://www.youtube.com/watch?v=Cfr4YNbKrB8:23
    g https://www.youtube.com/watch?v=Cfr4YNbKrB8:67
    g https://www.youtube.com/watch?v=Cfr4YNbKrB8:67
    call self-hosted:1356
    Mt moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:8
    m moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:55
    a moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:56
    (Асинхронный: setTimeout handler)
    setTimeout self-hosted:1356
    setTimeout moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:34
    processMessage moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:37
    <анонимный> moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:65
    g moz-extension://b50ef8b5-123e-4b64-b732-21404c9fdea2/content.js:56
    call self-hosted:1356
    St https://www.youtube.com/watch?v=Cfr4YNbKrB8:9
    p https://www.youtube.com/watch?v=Cfr4YNbKrB8:67

Тоже самое, но скриншотом.
![image](https://user-images.githubusercontent.com/98622217/218236716-314f11b4-ea2e-4411-a577-33ce4178fe2d.png)

**Comment by Spp595** [comment]
Такая же проблема

**Comment by ilyhalight** [comment]
> DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable. Voice Over Translations.user.js:1192:21

Можно увидеть ответ, который приходит с сервера? Судя по этой ошибке, проблема в не верной ссылке на аудио файл.
![изображение](https://user-images.githubusercontent.com/62353659/218254108-6ec7743c-9194-4fa8-b403-c2169193f6cb.png)

**Comment by flowing-abyss** [comment]
Вот такой вывод. Видео тоже самое.

VOT Response:  
Object { url: "https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49…0b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013", duration: 584, status: 1, code: "89191919" }
​
code: "89191919"
​
duration: 584
​
status: 1
​
url: "https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49…0b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013"
​
<prototype>: Object { constructor: VideoTranslationResponse(p), duration: 0, status: 0, … }
Voice Over Translations.user.js:360:15

Тоже самое на скрине:
![image](https://user-images.githubusercontent.com/98622217/218254479-5908831b-547f-4fee-8a64-a7149adae071.png)

**Comment by ilyhalight** [comment]
> Вот такой вывод. Видео тоже самое.
> 
> VOT Response: Object { url: "[https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49…0b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013](https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49%E2%80%A60b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013)", duration: 584, status: 1, code: "89191919" } ​ code: "89191919" ​ duration: 584 ​ status: 1 ​ url: "[https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49…0b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013](https://vtrans.s3-private.mds.yandex.net/tts/prod/ebf7eefb49%E2%80%A60b033f863aa647524c8d16825191b7ddfdb2a5520975ea49da6f17fc7013)" ​ : Object { constructor: VideoTranslationResponse(p), duration: 0, status: 0, … } Voice Over Translations.user.js:360:15
> 
> Тоже самое на скрине: ![image](https://user-images.githubusercontent.com/98622217/218254479-5908831b-547f-4fee-8a64-a7149adae071.png)
> 
> Я перешёл по ссылке и там заиграл перевод в плеере. Т.е. ссылка получается рабочая и в ней воспроизводится звук. ![image](https://user-images.githubusercontent.com/98622217/218254672-76e54747-4e96-442a-b0c4-8a530e8914af.png)

В таком случае, не знаю, что можно было бы попробовать сделать и куда копать. Не сталкивался с таким ранее.

**Comment by flowing-abyss** [comment]
А при каком условии вообще выдается исключение "Формат аудио не поддерживается"? Я не шибко программист, поэтому не могу понять по скрипту в каком случае он у вас эту ошибку выдает. Иначе говоря, что эта ошибка означает: нет нужного кодека, браузер не поддерживает, данные по звуку не доходят, может просто какой-то библиотеки в системе не хватает или что-то другое?

**Comment by ilyhalight** [comment]
> А при каком условии вообще выдается исключение "Формат аудио не поддерживается"? Я не шибко программист, поэтому не могу понять по скрипту в каком случае он у вас эту ошибку выдает. Иначе говоря, что эта ошибка означает: нет нужного кодека, браузер не поддерживает, данные по звуку не доходят, может просто какой-то библиотеки в системе не хватает или что-то другое?

В твоем случае, возвращается ошибка "NotSupportedError", что судя по [документации](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#exceptions) означает, что:
![изображение](https://user-images.githubusercontent.com/62353659/218258501-553c82fe-6580-4a3b-aa89-b596ad0146ce.png)
(к сожалению, более конкретное значение ошибки не получится получить)

Это исключение выдается в функции lipSync (при значение переменной mode = 'play').
Если конкретно, то в этом фрагменте кода:
```
        //...
        var audioPromise = audio.play();
        if (audioPromise !== undefined) {
          audioPromise.catch(e => {
            console.error(e)
            if (e.name === "NotAllowedError") {
              transformBtn('error', 'Предоставьте разрешение на автовоспроизведение')
              throw "VOT: Предоставьте разрешение на автовоспроизведение"
            } else if (e.name === "NotSupportedError") {
              if (sitesChromiumBlocked.includes(window.location.hostname)) {
                transformBtn('error', 'Для поддержки этого сайта необходимо дополнительное расширение')
                throw "VOT: Для поддержки этого сайта необходимо дополнительное расширение"
              } else {
                transformBtn('error', 'Формат аудио не поддерживается')
                throw "VOT: Формат аудио не поддерживается"
              }
            }
          })
        }
        //...
```

По итогу, эта ошибка выдается, если объекту [аудио](https://developer.mozilla.org/ru/docs/Web/API/HTMLAudioElement/Audio) не удалось [запустить проигрывание звука](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play) и вернулся [объект с ошибкой](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play#exceptions).

Пример объекта с ошибкой, где `name` - имя ошибки, `message` - сообщение ошибки (из-за чего произошла ошибка, оно же и передается в лог ошибки):
![изображение](https://user-images.githubusercontent.com/62353659/218258598-f01292dd-e144-485d-8bb9-7896b95bdabf.png)

Для того, чтобы получить объект с ошибкой нужно добавить `console.log(audioPromise);`, чтобы получилось примерно так:
```
       //...
        var audioPromise = audio.play();
        if (audioPromise !== undefined) {
          console.log(audioPromise)
          audioPromise.catch(e => {
       //...
```

**Comment by flowing-abyss** [comment]
Я понял в чём проблема. Сайт vtrans.s3-private.mds.yandex.net как-то тречит обращения к нему. У меня стоит Privacy Badger и он этот трекер блочит. Если разрешить обращение по этому домену, то перевод начинает озвучиваться как надо.

**Comment by 0x262D** [comment]
Если начали трекать - быть беде.
Наверное готовяться как-то хитро нас всех побанить :crying_cat_face:

**Comment by Spp595** [comment]
> Я понял в чём проблема. Сайт vtrans.s3-private.mds.yandex.net как-то тречит обращения к нему. У меня стоит Privacy Badger и он этот трекер блочит. Если разрешить обращение по этому домену, то перевод начинает озвучиваться как надо.

тоже самое, недавно его поставил

**Comment by VitaliyAT** [comment]
Банерорезки его (получаемый звуковой файл перевода) лочат, например, я отключил Гостери, перегрузил страницу, заказал перевод по новой, тот мгновенно пришёл и заиграл.
