### ISSUE TITLE
не включается перевод на втором видео

### ISSUE THREAD

**Issue by ilyachch** [ilyhalight/voice-over-translation#902]
### Operating system / Операционная система

Arch Linux

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1

### Describe the bug / Опишите ошибку

После обновления на версию 1.7.1 появилась такая проблема:
1. заходим на видео 1, включаем перевод
3. перевод работает
4. переходим на любое другое видео (видео 2) (без перезагрузки страницы), включаем перевод
5. собственная громкость видео снижается, перевода нет
6. переходим обратно на видео 1 (без перезагрузки страницы), включаем перевод
7. собственная громкость видео снижается, перевода нет
8. на видео 1 или видео 2 обновляем страницу, включаем перевод
9. перевод работает

если выключить или выключить "новый аудиоплеер" - перевод заработает без перезагрузки страницы (только на текущем видео, для последующих начинается то же самое - без перезагрузки не работает)

сам "новый аудиоплеер" не влияет - с включенным и выключенным поведение одинаковое

в консоли ошибок нет. запрос отрабатывает - 200

**Comment by ilya-corneli** [comment]
У меня так же не работает ютуб, идет перевод, но не голоса перевода

**Comment by ilyhalight** [comment]
Переустановите скрипт через кнопку на главной репозитория. Должно заработать

**Comment by ilyachch** [comment]
> Переустановите скрипт через кнопку на главной репозитория. Должно заработать

да, помогло
