### ISSUE TITLE
Долгий перевод

### ISSUE THREAD

**Issue by nazarhktwitch** [ilyhalight/voice-over-translation#905]
### Operating system / Операционная система

Windwos 10 22H2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1

### Describe the bug / Опишите ошибку

Переводит видео 25 минутное около 5 минут, а в яндексе за 3 секунды

### Additional information / Дополнительная информация

Это не обязательно, но можно ли ускорить?

**Comment by ilyhalight** [comment]
Отключите эту функцию, должно помочь
![firefox_0PsuoZF7TF](https://github.com/user-attachments/assets/43aaaf9e-964d-445f-a50a-7bd5cb3f6796)

**Comment by nazarhktwitch** [comment]
В настройках такого не могу найти

**Comment by ilyhalight** [comment]
> В настройках такого не могу найти

Через кнопку на главной репозитория обновите/переустановите расширение и после этого появится

**Comment by nazarhktwitch** [comment]
Не знаю, переустановил расширение кнопка не появилась

**Comment by ilyhalight** [comment]
> Не знаю, переустановил расширение кнопка не появилась

видимо плохо искали

![firefox_5zQWcczmoN](https://github.com/user-attachments/assets/4f39d0dc-aa62-4422-9bcb-fa63dce098b4)

**Comment by nazarhktwitch** [comment]
Нет такого вообще
![image](https://github.com/user-attachments/assets/d13fb28a-63b0-4870-af33-ccad8e08d47f)

**Comment by ilyhalight** [comment]
> Нет такого вообще ![image](https://private-user-images.githubusercontent.com/170885099/384695180-d13fb28a-63b0-4870-af33-ccad8e08d47f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDgwMDgsIm5iZiI6MTczMTI0NzcwOCwicGF0aCI6Ii8xNzA4ODUwOTkvMzg0Njk1MTgwLWQxM2ZiMjhhLTYzYjAtNDg3MC1hZjMzLWNjYWQ4ZTA4ZDQ3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNDA4MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTQ3Y2ZlNDcwZjgzOTQ5NTA1YWQ4ZGEyMDVjOWU2ZTQ0YWNkNWYyNjJiNmM5OTkyODg2MDFiZmZjMzk3OGNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NGXpmCmxyu1Ck_LoeK97fqh2rr-Pa6XsOWM9igS3kao)

до 1.7.2 обновитесь, там не может не быть

**Comment by nazarhktwitch** [comment]
Обновил, появилось
