### ISSUE TITLE
Перевод с русского на русский

### ISSUE THREAD

**Issue by kasatka60** [ilyhalight/voice-over-translation#906]
### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

Любая версия

### Describe the bug / Опишите ошибку

На рутубе переводит с русского на русский, хотя правильно определяет язык видео и при этом в настройках поставлена галочка: не переводить с русского. На ютубе таких проблем нету.

### Additional information / Дополнительная информация

Данный баг воспроизводится на трех компах с ОС Win11 22H2. Браузер EDGE.

**Comment by ilyhalight** [comment]
Эта настройка работает только для youtube, ok, vk. Не помню, зачем так было сделано, но думаю можно попробовать убрать
