### ISSUE TITLE
Проблемы с отображением кнопки и субтитров на сайте

### ISSUE THREAD

**Issue by 11class09** [ilyhalight/voice-over-translation#909]
### Operating system / Операционная система

Windows 7

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.1

### Describe the bug / Опишите ошибку

Incestflix.net
Кнопка за пределами плеера
![1](https://github.com/user-attachments/assets/fd0f0331-5999-46d7-a3d5-cfba3ae3b486)
В полноэкранном режиме ни кнопки ни субтитров не отображается. После выхода из полноэкранного режима субтитры оказываются наверху также за пределами плеера.
![2](https://github.com/user-attachments/assets/b65cac6e-6e31-47c7-a134-d8c0056656c6)

**Comment by ilyhalight** [comment]
С их стандартным браузерным плеером лучшего не сделать. Максимум можно было бы сделать, чтобы без фуллскрина кнопки и субтитры были в пределах плеера, но дополнительный адаптив для непопулярных сайтов не вижу смысла делать
