### ISSUE TITLE
 An error occurred during the translation, please try again later

### ISSUE THREAD

**Issue by AllisonAinsworth** [ilyhalight/voice-over-translation#919]
### Operating system / Операционная система

22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

На youtube не переводится видео, висит сообщение The translation will take about a minute и ничего не происходит в течение длительного времени. После появляется сообщение An error occurred during the translation, please try again later. Вне зависимости от количества попыток результат не меняется.

**Comment by ilyhalight** [comment]
> После появляется сообщение An error occurred during the translation, please try again later

Не удалось воспроизвести ошибку, но да, долгое ожидание есть. Видимо, Яндекс опять что-то поменял в способе, который использовал для перевода без отправки аудио, либо полностью перешел на клиентскую загрузку аудио для ютуба. Нужно разбираться

**Comment by DearFox** [comment]
> то необходимо ждать минут 10 завершения перевода

Думаю в таком случае нужно что-то придумать и просто писать в место этого:
![изображение](https://github.com/user-attachments/assets/7eef14a3-58e5-4eba-a61a-fd761f48920c)

что-то типа: "перевод может занять порядка 10 минут" или типа того.

**Comment by DearFox** [comment]
> но что делать с теми у кого мобильный/медленный интернет не понятно

Добавить настройку для переключения как вариант.

**Comment by ilyhalight** [comment]
> Попозже сделаю изменение текста на что-то вроде "перевод немного задерживается", если сервер несколько раз вернул одинаковое время в ответе. Дабы текст не вводил в заблуждение.

Добавил в дев ветке

> В целом, примерно так и оказалось. Либо не отправляешь аудио и очень долго ждешь, и возможно получаешь ошибку, либо нужно загружать аудио с ютуба и отправлять его вместе с запросом. В ближайшее время попробую реализовать загрузку и отправку аудио, но что делать с теми у кого мобильный/медленный интернет не понятно

Сейчас, нормализовалась работа и без необходимости загрузки аудио, пока немного отложу
