### ISSUE TITLE
Настройка задержки аудио перевода

### ISSUE THREAD

**Issue by palkindenis85** [ilyhalight/voice-over-translation#92]
Скажите как настроить задержу воспроизведение аудио перевода
То есть чтобы сначала шло оригинальное аудио а через 2 сек перевод,
ето годится для изучение языка

**Comment by ilyhalight** [comment]
Сделал такую версию. Выключи автообновление для скрипта, иначе при обновление до следующей версии у тебя пропадает задержка в 2 секунды.

https://drive.google.com/file/d/1s-WPIjwnuJvXMeOhoSyzyW6vcqeAr1zR/view?usp=share_link
