### ISSUE TITLE
Не работает перевод

### ISSUE THREAD

**Issue by NewDarkys** [ilyhalight/voice-over-translation#920]
### Operating system / Операционная система

Windows 10 22H2  

### Browser / Браузер

Other / Другой

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Не появляется кнопка перевода на всех видео ютуба!

### Additional information / Дополнительная информация

Браузер Brave

**Comment by ilyhalight** [comment]
проблема на вашей стороне
![brave_KE7HLlKgT1](https://github.com/user-attachments/assets/dda4410d-6afd-42c6-af91-25e23bfcf28c)
