### ISSUE TITLE
The button in the Edge browser has disappeared / пропала кнопка в браузере Edge

### ISSUE THREAD

**Issue by Pirchesko** [ilyhalight/voice-over-translation#921]
### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Я использую редко закадровый перевод. Но сегодня я случайно заметил, что он пропал из моего бразуера Edge. Переустановка скрипта не помогла. В браузере Firefox кнопка на месте. 
Я считаю, что кнопка могла пропасть из-за обновления браузера Edge. Я прикрепил скриншот, где видно, что появились какие-то другие копки от браузера. Как можно вернуть кнопку "перевести видео"?
![{1EC09CCF-FAD0-4CB9-9CDF-B0C408B84466}](https://github.com/user-attachments/assets/e9b1829d-dfe4-48be-a0f0-525c541c5b64)

**Comment by ilyhalight** [comment]
проверьте, что включен режим разработчика в браузере и что расширение активно в tampermonkey

**Comment by sergeos** [comment]
У меня тоже не отображалось в едже, пришлось включить режим разработчика (developer mode) и переустановить скрипт, после этого заработало. 2-минутное видео перевелось не сразу, а через минут 5-6 после активации перевода.
Мой конфиг:
![image](https://github.com/user-attachments/assets/3ef17e59-740b-4dc5-98ee-1d4ffcb78e78)

**Comment by Pirchesko** [comment]
Я попытался посмотреть что там в консоли, но там что-то слишком много всяких разных ошибок и я не понимаю что с ними делать и есть ли среди этих ошибок какая-то ошибка касаемая закадрового перевода или tampermonkey
![{37C1E414-7531-4CA9-82B2-F8808351AEDC}](https://github.com/user-attachments/assets/ec70f5bf-7af7-447f-9f61-08f51b9762a1)
Если говорить о режиме разработчика в браузере, то я не понял о чем вы. Я попробовал поиском посмотреть что у меня есть из настроек, но похоже что нет так называемого "режима разработчика" или т.п. Или я вас в ээтом плане не правильно понял. Подскажите где конкретно надо включить "developer mode" 
![{DB7804D0-F93A-4FBA-9D4C-F5D4257F6680}](https://github.com/user-attachments/assets/282af074-39d5-4d21-9bbd-46be40569bc8)

**Comment by ilyhalight** [comment]
> Я попытался посмотреть что там в консоли, но там что-то слишком много всяких разных ошибок и я не понимаю что с ними делать и есть ли среди этих ошибок какая-то ошибка касаемая закадрового перевода или tampermonkey ![{37C1E414-7531-4CA9-82B2-F8808351AEDC}](https://private-user-images.githubusercontent.com/55009114/386985889-ec70f5bf-7af7-447f-9f61-08f51b9762a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzQxMTAsIm5iZiI6MTczMTg3MzgxMCwicGF0aCI6Ii81NTAwOTExNC8zODY5ODU4ODktZWM3MGY1YmYtN2FmNy00NDdmLTlmNjEtMDhmNTFiOTc2MmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIwMDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NWUyM2RjMjcwOTM5N2Q4NjcyYzJhNTAzZjc5ODY4NDFiYmI3MzE3YzkzMmRjZmQ5ZmVmYjE0ZDU1YjdhZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eiMK4ovsfAj9UaMkLYyl-HNCGKSdqPEl7PFJBVg5_RQ) Если говорить о режиме разработчика в браузере, то я не понял о чем вы. Я попробовал поиском посмотреть что у меня есть из настроек, но похоже что нет так называемого "режима разработчика" или т.п. Или я вас в ээтом плане не правильно понял. Подскажите где конкретно надо включить "developer mode" ![{DB7804D0-F93A-4FBA-9D4C-F5D4257F6680}](https://private-user-images.githubusercontent.com/55009114/386986041-282af074-39d5-4d21-9bbd-46be40569bc8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4NzQxMTAsIm5iZiI6MTczMTg3MzgxMCwicGF0aCI6Ii81NTAwOTExNC8zODY5ODYwNDEtMjgyYWYwNzQtMzlkNS00ZDIxLTliYmQtNDZiZTQwNTY5YmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDIwMDMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NGYyNzI4Y2Q0YjQ5MDNiODFjNmRkYTEyODk3ZWQyMTVjM2MyNzMwOTUzMzk3ODIyYTE4ZDk0NjI0MWE5YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EEiz4rS_-lViMh7jJK6lt6L0oEDCV9Xe2kHdosNTbJ4)

Во вкладке расширения (edge://extensions/) --> сверху переключатель режим разработчика

**Comment by Pirchesko** [comment]
Вая, всё заработало, спасибо!
![{7E6199E1-4E16-4B59-9CBE-BAC9D08A08B7}](https://github.com/user-attachments/assets/7430a046-54cc-4560-895f-e6187b501e81)

**Comment by rexen-pro** [comment]
Да работает, работает. По крайней мере у меня в Edge. Всё как расписано - включен режим разраба в расширениях (не путать с ДевТулзами по Ф12). У кого не работает - пробуйте отключать другие расширения или скрипты в том же ТамперМанки. Хотя вот в ФаерФоксе кнопка у меня тольком не работает - её загораживает слой видео, никакие попытки что-то обновлять или отключать не помогли.

**Comment by ilyhalight** [comment]
> её загораживает слой видео

Возможно, какое-то из других расширений конфликтует. Либо ютуб что-то тестирует в плеере на ограниченном числе пользователей.

Ибо у меня все нормально работает в фф
