### ISSUE TITLE
Don`t work with vkvideo

### ISSUE THREAD

**Issue by neeromeero** [ilyhalight/voice-over-translation#931]
### Operating system / Операционная система

Linux

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

После перехода вквидео на домен vkvideo.ru перестал работать перевод

**Comment by FiLinX** [comment]
пока переходный период  -  можно и ручками в адресной строке заменять vkvideo.ru  на  vk.com

**Comment by ipwin-github** [comment]
**FiLinX**
Замена в адресной строке на старый домен не поможет, потому что сам перевод в браузере не воспроизводится. То есть скрипт переводит и показывает что видео переведено но воспроизведения перевода нет. При этом звуковая дорожка с переводом скачивается.

**Comment by ipwin-github** [comment]
**ilyhalight**
Действительно проблема оказалась на моей стороне. Проверил на браузере с чистым профилем и там перевод воспроизводится на старом домене. Видимо в моем основном браузере появился конфликт с каким-то скриптом или расширением который и проявляется в отсутствии воспроизведения перевода на vk.

**Comment by Metal-01-1** [comment]
Здравствуйте.
Получается, что пока через вк перевод работает только в формате субтитров?
Озвучивания голосом у меня нет. Проверял на разных браузерах, везде только субтитры.

**Comment by ilyhalight** [comment]
> Здравствуйте. Получается, что пока через вк перевод работает только в формате субтитров? Озвучивания голосом у меня нет. Проверял на разных браузерах, везде только субтитры.

в последней бете все работает

**Comment by Flashwalker** [comment]
Эй, когда уже будет то?

**Comment by Flashwalker** [comment]
> в последней dev версии все работает

 а где она?

**Comment by ilyhalight** [comment]
> > в последней dev версии все работает
> 
> а где она?

обновитесь до последней стабильной версии, там уже есть

**Comment by Flashwalker** [comment]
Короче оно так и не работает ни на vk.com ни на vkvideo.ru
https://vk.com/video433975587_456239545
Ошибка перевода
