### ISSUE TITLE
Supported languages

### ISSUE THREAD

**Issue by peppofort** [ilyhalight/voice-over-translation#933]
### Describe your feature / Опишите ваше предложение

Hi, I can only translate to Russian, English and Kazakh. Is Italian supported?

**Comment by ilyhalight** [comment]
Italian is supported only as the language from which the translation is performed

**Comment by peppofort** [comment]
so will the target languages ​​remain the same or will others be implemented in the future?

**Comment by ilyhalight** [comment]
> so will the target languages ​​remain the same or will others be implemented in the future?

idk, it mostly depends on Yandex
