### ISSUE TITLE
Translation of VK video does not work / Не работает перевод ВК видео

### ISSUE THREAD

**Issue by Hitosha** [ilyhalight/voice-over-translation#936]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Translation of VK videos does not work. I think that the addresses for the videos in VK have changed. The code says (VK.ru) and (VK.com). And in the address bar (vkvideo.ru). / Не работает перевод VK видео. Я так думаю, что поменялись адреса на видео в ВК. В коде указано (VK.ru) и (VK.com). А в адресной строке (vkvideo.ru).

**Comment by Kitatadoshi** [comment]
becouse now use vkplay.com instead of vk.com

**Comment by ilyhalight** [comment]
уже репортили #931
