### ISSUE TITLE
На сайте Одноклассники не работает.

### ISSUE THREAD

**Issue by HollowG** [ilyhalight/voice-over-translation#937]
### Operating system / Операционная система

Window 10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Violentmonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

На сайте OK расширение будто не работает, нет ни плашки ни чего либо, но при этом месяца 2 назад было. 
С ВК или YB, таких проблем не наблюдается.

**Comment by ilyhalight** [comment]
Уже репортили #900
