### ISSUE TITLE
Нету кнопки на экране ютуба

### ISSUE THREAD

**Issue by Mark07w** [ilyhalight/voice-over-translation#938]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Нужна помощь. Я скачал скрипт, выключил и включил браузер, включил в расширениях режим разработчика, включил скрипт, и после этих действий все равно не вижу кнопки для перевода на экране ютуба..

**Comment by ilyhalight** [comment]
В Tampermonkey скрипт показывается как активный? Есть какие-то ошибки в консоли?

**Comment by Mark07w** [comment]
Нажал кнопку, переустановить скрипт и все заработало!))
