### ISSUE TITLE
Не запускается скрипт

### ISSUE THREAD

**Issue by Trapezze** [ilyhalight/voice-over-translation#942]
### Operating system / Операционная система

Windows 11

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

5.3.2

### Describe the bug / Опишите ошибку

[Видео с демонстрацией.zip](https://github.com/user-attachments/files/18034569/default.zip)

### Additional information / Дополнительная информация

В настройках панели управления скрипта, скрипт отказывается запускаться.

**Comment by ilyhalight** [comment]
Переключатель в положение включено у вас уже стоит, галочка там нужна только для массовых действий со скриптами. То, что на гитхабе он не показывается - особенность самого Tampermonkey, он показывает скрипты, только, на сайтах, которые прописаны в самом скрипте (например, ютуб, вк, вимео и т.д.)
