### ISSUE TITLE
Перестал работать перевод на dev.epicgames.com

### ISSUE THREAD

**Issue by ver-tag** [ilyhalight/voice-over-translation#944]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Больше не появляется выпадающее меню для перевода в плеере. Пару дней назад всё работало.

**Comment by ilyhalight** [comment]
немного логику плеера изменили, буду пытаться исправлять
