### ISSUE TITLE
Ошибка при переводе видео на Яндексе и Vimeo

### ISSUE THREAD

**Issue by sailars** [ilyhalight/voice-over-translation#945]
### Operating system / Операционная система

Windows 10 Pro 22H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Вначале хотел бы еще раз поблагодарить вас за эту чудную возможность переводить видео вне Яндекс Браузера. Пользуюсь вашим скриптом почти с самого его появления. Очень выручает и дает много возможностей... Но столкнулся с ошибками:
Заявлена поддержка Vimeo, но мне очень трудно добиться результата перевода видео. Загружаю видео в свою библиотеку, получаю _публичную_ ссылку на видео, открываю, пишет: "Ошибка: видео слишком длинное". Видео составляет около 23 минут.
Ссылка на видео: https://vimeo.com/1037018244
![изображение](https://github.com/user-attachments/assets/dcee6b6b-df23-4d4c-af89-a6f1ed220151)

То же самое с Яндекс Диском: https://disk.yandex.ru/i/pM07k0QEme42UQ
Но ошибка там страшнее: 
![изображение](https://github.com/user-attachments/assets/acbe0a78-3003-4099-afac-de771d7fde02)

Firefox 111.0

Что это может быть и что делать?

**Comment by FiLinX** [comment]
у меня ваша яндексовая ссылка отрабатывает - перевод звучит
а вот на вимео да, ругается на "слишком длинное" )
ни проксирование, ни использование нового аудиоплеера -  не включено у меня если что

**Comment by ilyhalight** [comment]
> То же самое с Яндекс Диском: https://disk.yandex.ru/i/pM07k0QEme42UQ

установите "Добавлять TM в политику безопасности CSP" в настройках Tampermonkey на значение автоматически (если уже стоит "автоматически", то на "да")

https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ



> "Ошибка: видео слишком длинное". Видео составляет около 23 минут.
> Ссылка на видео: https://vimeo.com/1037018244

Это вернул сам сервер яндекса по непонятно какой причине. Поставьте язык оригинала на "Авто" и выдаст нормальный перевод.

**Comment by sailars** [comment]
> > То же самое с Яндекс Диском: https://disk.yandex.ru/i/pM07k0QEme42UQ
> 
> установите "Добавлять TM в политику безопасности CSP" в настройках Tampermonkey на значение автоматически (если уже стоит "автоматически", то на "да")
> 
> https://github.com/ilyhalight/voice-over-translation/wiki/%5BRU%5D-FAQ
> 
> > "Ошибка: видео слишком длинное". Видео составляет около 23 минут.
> > Ссылка на видео: https://vimeo.com/1037018244
> 
> Это вернул сам сервер яндекса по непонятно какой причине. Поставьте язык оригинала на "Авто" и выдаст нормальный перевод.

Спасибо, оба варианта в принципе помогли.
На Вимео ошибка исчезла, перевод пошел, но только первые секунд 20. Дальше не генерит, хотя показывает, что работает. Скорее всего, здесь уже глюки Яндекса-шмандекса.
=============
Для тех, кто столкнулся с этой же ошибкой на Яндексе, вам нужно перейти в панель управления Tampermonkey - вкладка Настройки, выбрать режим конфигурации "опытный", затем внизу напротив настройки "Добавить TM в политику безопасности CSP" выбрать "Да". И не забудьте нажать "Сохранить" в разделе Безопасность, иначе значение сбросится. Перезапускам браузер, страницу с кешем и готово.

Для Вимео: открыть страницу с видео, запустить, но не нажимать "Перевести". Нажать на три точки, выбрать "Авто", затем можно переводить.
