### ISSUE TITLE
перестал работать перевод на vk video

### ISSUE THREAD

**Issue by toto555666** [ilyhalight/voice-over-translation#947]
### Operating system / Операционная система

Виндовс 10
### Browser / Браузер

Опера, Опера GX, Гугл Хром, Яндекс Браузер

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Здравствуйте. Уже где-то дней 10 не работает (не появляется кнопка) vk video. Не работает ни в браузере Опера, ни в Опера GX, ни в Гугл Хром, ни в Яндекс Браузер. При всем этом во всех этих браузерах на ютубе кнопка перевода есть и работает. 
Пожалуйста, исправьте эту проблему. Спасибо за прекрасный скрипт.

**Comment by ilyhalight** [comment]
уже исправлено в дев версии, ожидайте релиза #931
