### ISSUE TITLE
Регулятор (ограничитель) количества показа слов в одном субтитре за раз

### ISSUE THREAD

**Issue by toto555666** [ilyhalight/voice-over-translation#948]
### Describe your feature / Опишите ваше предложение

Длина субтитров - очень даже нужная функция. Возможно кому-то и нужна побольше, но оптимально - это несколько вариантов длины на выбор. Порой скачиваешь сабы и каждый саб вменяемый по длине, но попадаются такие, что величиной в пол страницы. Это не очень удобно, если важно наблюдать за видео - сабы его закрывают. Если есть такая возможность, то сделайте несколько вариантов на выбор - например, "не больше 20 слов за раз", "не больше 40 слов за раз" и т.д. А в идеале конечно лучше ползунок с нарастающим выбором количества показа слов за раз.

Еще раз благодарю за прекрасный скрипт.

**Comment by ilyhalight** [comment]
> Если есть такая возможность, то сделайте несколько вариантов на выбор - например, "не больше 20 слов за раз", "не больше 40 слов за раз" и т.д. А в идеале конечно лучше ползунок с нарастающим выбором количества показа слов за раз.

Такое уже есть, но измеряется не в словах, а в символах. Меню -> оформление субтитров -> Максимальная длина субтитров

![firefox_zzsnMu1air](https://github.com/user-attachments/assets/b7d2b8db-eb2d-4cd8-b118-554a9cff4fee)
