### ISSUE TITLE
не удалось запросить перевод видео

### ISSUE THREAD

**Issue by rich15304560** [ilyhalight/voice-over-translation#95]
собственно проблема в заглавии. в той рамочке на ютубе когда наводишь на окно с видео пишет в серой рамочке данную фразу...перевести - не переводит...правда иногда толи отглючивает  толи хз что, но начинает переводить, браузер - хром.

**Comment by moskal87** [comment]
https://prnt.sc/QrWjEJJ2Z_u8 такое пишет, надеюсь я правильно понял.

**Comment by ilyhalight** [comment]
> https://prnt.sc/QrWjEJJ2Z_u8 такое пишет, надеюсь я правильно понял.

Тебе нужно использовать специальную версию для UserScripts - https://raw.githubusercontent.com/ilyhalight/voice-over-translation/master/vot-cloudflare.user.js

**Comment by moskal87** [comment]
а расширения, Tampermonkey использовать?

**Comment by ilyhalight** [comment]
> а расширения, Tampermonkey использовать?

А, сейчас, какое испольуется?

**Comment by moskal87** [comment]
> > а расширения, Tampermonkey использовать?
> 
> А, сейчас, какое испольуется?

оно и использовалось

**Comment by moskal87** [comment]
теперь, на ютубе пишет https://prnt.sc/k0UrRtLbbr2E сама консоль https://prnt.sc/K2RhqzaABPBe

**Comment by ilyhalight** [comment]
> теперь, на ютубе пишет https://prnt.sc/k0UrRtLbbr2E сама консоль https://prnt.sc/K2RhqzaABPBe

Не используете никакой блокировщик трафика или что-либо блокирующее рекламу/отслеживание и т.п.? Похожая проблема возникала как раз из-за этого #90

**Comment by moskal87** [comment]
выключил ad block не помогло. Проще будет яндекс поставить для перевода) Спасибо, за помощь!
