### ISSUE TITLE
Исчезла кнопка перевода

### ISSUE THREAD

**Issue by reykerGG** [ilyhalight/voice-over-translation#950]
### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

![Снимок экрана 2024-12-10 140801](https://github.com/user-attachments/assets/b58eb683-aad8-4f8a-abd0-e9ac3f5bc195) Когда-то работал щяс кнопка исчезла после обновление браузера

**Comment by FiLinX** [comment]
для начала, отключи и удали Tampermonkey 
затем проверь, стоит ли на странице расширений галочка "Режим разработчика", если нет то включи
потом уже установи вновь Tampermonkey и скрипт VOT

**Comment by reykerGG** [comment]
спасибо за помощь, нужно было включить режим разработчика.
