### ISSUE TITLE
Не подгружается кнопка перевода если в ok.ru вставлено VK видео (возможно для всех видео с ok.ru).

### ISSUE THREAD

**Issue by kscaner** [ilyhalight/voice-over-translation#951]
### Operating system / Операционная система

Windows 11 24H2

### Browser / Браузер

Edge

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Вот пример видео
https://ok.ru/video/7450706184910
кнопка для перевода не подгружается, хотя ссылка ведет на okcdn.ru, и только по лого вверху слева видно, что оно с VK Видео. Хотя, возможно, теперь все видео ok.ru перенесли в VK видео.

**Comment by kscaner** [comment]
Извиняюсь похоже уже есть [issue](https://github.com/ilyhalight/voice-over-translation/issues/900)

**Comment by ilyhalight** [comment]
Уже репортили. В дев ветке исправлено

**Comment by kscaner** [comment]
> Уже репортили. В дев ветке исправлено

А эту версb. как-то можно установить, или надо ждать бету/релиз?
