### ISSUE TITLE
Субтитры не работают

### ISSUE THREAD

**Issue by Alessa19** [ilyhalight/voice-over-translation#953]
### Operating system / Операционная система

Windows 11 21H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Я пытаюсь скачать русские субтитры, которые генерирует Яндекс, для видео на YouTube. Язык видео — русский. Я не понимаю, почему для некоторых видео субтитры доступны, а для других — нет (вместо этого доступны только авто-субтитры YouTube). Для видео на YouTube, где субтитры Яндекса недоступны, VOT всё равно работает.

Например, для этого видео https://www.youtube.com/watch?v=JbQ-om9Z4Rc субтитры, которые генерирует Яндекс, не отображаются и их нельзя скачать. Однако VOT работает для этого видео.
![Screenshot 2024-12-11 225939](https://github.com/user-attachments/assets/46624a66-8922-4079-9c7b-e19d51c50924)

**Comment by ilyhalight** [comment]
Яндекс не сразу генерирует субтитры для видео. Обычно это происходит при запросе перевода, **но иногда Яндекс даже после успешного перевода не хочет отдавать субтитры для ролика**. Такое же поведение и в их браузере.  Возможно, это ошибка у них на бекенде, а может быть это такая фича. 

От расширения это в любом случае не зависит
