### ISSUE TITLE
Пропала кнопка перевода видео (пока заметил это только на Ютубе)

### ISSUE THREAD

**Issue by Lumluk** [ilyhalight/voice-over-translation#956]
### Operating system / Операционная система

10

### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.7.2

### Describe the bug / Опишите ошибку

Просто не появляется кнопка перевода

**Comment by ilyhalight** [comment]
Попробуйте выполнить действия описанные в #950 и #921

**Comment by Lumluk** [comment]
@ilyhalight  благодарю, очень помогли
