### ISSUE TITLE
перестал работать на ютуб

### ISSUE THREAD

**Issue by oldgentleman83** [ilyhalight/voice-over-translation#958]
### Browser / Браузер

Opera

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1,7,2

### Describe the bug / Опишите ошибку

не работает на ютуб. 

### Additional information / Дополнительная информация

регион испания

**Comment by ilyhalight** [comment]
#956, если не поможет, то переоткройте и дайте больше информации
