### ISSUE TITLE
нету кнопки с преводом

### ISSUE THREAD

**Issue by gigandbro** [ilyhalight/voice-over-translation#959]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

	1.7.2

### Describe the bug / Опишите ошибку

![image](https://github.com/user-attachments/assets/dd5b3ba7-0fea-4ff3-ac92-da85d296d856)

**Comment by ilyhalight** [comment]
#956, если не поможет, то переоткройте и дайте больше информации
