### ISSUE TITLE
Не включается звук перевода

### ISSUE THREAD

**Issue by Patraskon** [ilyhalight/voice-over-translation#96]
Браузер Firefox 110.1. В Microsoft Edge всё работает

https://user-images.githubusercontent.com/34421135/222123267-1b461262-6c15-45be-992b-63ff6884b768.mp4

**Comment by ilyhalight** [comment]
Из-за юзер агента при воспроизведение аудио, иногда барахлит, потом самособой проходит. Посмотрю, что можно сделать, но ничего не обещаю
