### ISSUE TITLE
Добавьте хинди пожалуйста

### ISSUE THREAD

**Issue by TTTSHOK** [ilyhalight/voice-over-translation#963]
### Describe your feature / Опишите ваше предложение

Мне не редко приходится смотреть видео на английском языке с туториалами, но попадаюсь на индусов, которые в заголовке пишут на английском, а видео на хинди. Можете ли вы добавить этот язык? (и украинский тоже)

**Comment by ilyhalight** [comment]
Это у ребят из Яндекса просите
