### ISSUE TITLE
Можно ли встроить скрипт на свой сайт?

### ISSUE THREAD

**Issue by sws33** [ilyhalight/voice-over-translation#97]
Можно ли встроить скрипт на свой сайт, чтобы youtube-видео на сайте включились сразу с переводом?

**Comment by ilyhalight** [comment]
Без костылей не получится т.к. ютуб видео встраивается на сайт через iframe. К нему ты доступ не получишь. Единственный вариант - делать какую-то дополнительную кнопку для включения/отключения перевода, но из-за этого не будет нормальной синхронизации, а соответственно и смысла в этом тоже пропадает
