### ISSUE TITLE
vkvideo

### ISSUE THREAD

**Issue by Ilja317** [ilyhalight/voice-over-translation#971]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8

### Describe the bug / Опишите ошибку

Guys thank you! For added vkvideo but playlist in it don`t work

**Comment by ilyhalight** [comment]
show link to the playlist

**Comment by Ilja317** [comment]
https://vkvideo.ru/playlist/825926180_46/video825926180_456244294

**Comment by Ilja317** [comment]
To be honest, I don’t understand why this playlist doesn’t work because I checked it on other playlists and it works there. Maybe VK now has 2 types of path patterns and this one doesn’t match the regular expression, or it’s just me, but I checked it in 2 different browsers

**Comment by ilyhalight** [comment]
> this one doesn’t match the regular expression

yes, small mistake. I forgot to make "-" (video-XXXX_XXX) optional for playlist regex

**Comment by Ilja317** [comment]
thank you for answered my message so quickly
