### ISSUE TITLE
BILI BILI not correct

### ISSUE THREAD

**Issue by Tony773737382992** [ilyhalight/voice-over-translation#977]
### Operating system / Операционная система

windows 11

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.5.3

### Describe the bug / Опишите ошибку

![Screenshot 2024-12-21 165801](https://github.com/user-attachments/assets/e79643dd-5fea-4685-bed4-7825ba322b61)

### Additional information / Дополнительная информация

Bili Bili not support from Playlists
Support only First Video, Second and next video not support this script

**Comment by ilyhalight** [comment]
Update extension to latest version. The latest version already support translation from playlists

**Comment by Tony773737382992** [comment]
> Update extension to latest version (e.g. 1.8.1). The latest version already support translation from playlists

![Uploading Screenshot 2024-12-21 184123.png…]()
