### ISSUE TITLE
Скрипт отключается при повторном воспроизведении youtube-видео

### ISSUE THREAD

**Issue by sws33** [ilyhalight/voice-over-translation#98]
При первом воспроизведении youtube-видео ставлю галочку "Повтор" в свойствах видео (клик Правок кнопкой мышки), когда начинается повторное воспроизведение, перевод отключается. Кнопка "включить перевод" сохраняет прежнее состояние от первого воспроизведения и предлагает отключить перевод. Попытка включить перевод, кликая по кнопке не приводит к результату. Помогает только перезагрузка страницы.

**Comment by ilyhalight** [comment]
В хроме всё работает и перевод, так же, начинается заново, вместе, с видео.

В файрфоксе перевод не начинается, но кнопка работает, что позволяет самому перезапустить перевод видео.
