### ISSUE TITLE
Работает везде, кроме ТВИТТЕРА

### ISSUE THREAD

**Issue by SeaShark41** [ilyhalight/voice-over-translation#981]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1

### Describe the bug / Опишите ошибку

Здравствуйте, помогите плиз! 
Только сегодня установила, ради ТВИТТЕРА
Посмотрела ровно одно видео, кайф, шикардос, кнопка "перевести" была! Всё работало.
А потом что-то пропала кнопонька, и её нет ни в Хроме, ни в Эдже, ни в Яндекс браузере
РЕЖИМ РАЗРАБОТЧИКА ВЕЗДЕ ВКЛЮЧЁН, голова сломана, подскажите, то ли я дурак, то ли переводчик помер

**Comment by ilyhalight** [comment]
В ленте кнопка не работает. Чтобы была кнопка перевода нужно открыть пост (нажать по нему). Пример того, как выглядит открытый пост:
https://x.com/morganmillipede/status/1796782136608825616

**Comment by SeaShark41** [comment]
Спасибо!!
Самостоятельно и эмпирически пришла к тому же!
Супер))

**Comment by ilyhalight** [comment]
Добавил поддержку ленты
