### ISSUE TITLE
Видео слишком длинное/VOTLocalizedError: Video is too long

### ISSUE THREAD

**Issue by patsevanton** [ilyhalight/voice-over-translation#986]
### Operating system / Операционная система

Ubuntu 23.10

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1

### Describe the bug / Опишите ошибку

VOTLocalizedError: Video is too long

**Comment by patsevanton** [comment]
![image](https://github.com/user-attachments/assets/f4a4ed7c-bb0c-41cb-b1bd-8bdb23807f6b)

**Comment by ilyhalight** [comment]
В [последней дев версии](https://github.com/ilyhalight/voice-over-translation/raw/refs/heads/dev/dist/vot.user.js) уже исправлено
