### ISSUE TITLE
Не поддерживается перевод www.twitch.tv

### ISSUE THREAD

**Issue by Kurururugi** [ilyhalight/voice-over-translation#987]
### Operating system / Операционная система

Windows 10 Pro 22H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1 5d

### Describe the bug / Опишите ошибку

При просмотре записей на www.twitch.tv, длительность которых менее 4 часов, не появляется плашка "Перевести видео". При просмотре этого же видео на m.twitch.tv плашка есть.
![tw_1](https://github.com/user-attachments/assets/3db9bf3d-d3a0-4b1f-b922-9d908dc4cebe)
![tw_2](https://github.com/user-attachments/assets/19774099-1322-4b03-b2c9-d403d5abf35d)

**Comment by ilyhalight** [comment]
> При просмотре записей на [www.twitch.tv](http://www.twitch.tv), длительность которых менее 4 часов, не появляется плашка "Перевести видео". При просмотре этого же видео на m.twitch.tv плашка есть.

У меня работает, проверьте наличие ошибок в консоли

![firefox_srZrnLgcPO](https://github.com/user-attachments/assets/44edd695-d6fc-4486-ba15-2610cd386439)

**Comment by Kurururugi** [comment]
Действительно, на www.twich.tv плашку блокировал Adblock, а на m.twich.tv этого не делал...
