### ISSUE TITLE
Стримы не переводятся

### ISSUE THREAD

**Issue by Dragoy** [ilyhalight/voice-over-translation#988]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1

### Describe the bug / Опишите ошибку

Смотрю стрим: https://www.youtube.com/watch?v=j79G5Be8Q4Y
Когда нажимаю кнопку перевода, основной звук уменьшается а перевода просто не слышно либо его вовсе нет.
Проверил в яндексбраузере все отлично переводит.

**Comment by ilyhalight** [comment]
В дев ветке уже исправлено

**Comment by ilyhalight** [comment]
Исправлено в 1.8.2
