### ISSUE TITLE
Проблема с переводом видео, на которые авторы наложили возрастное ограничение...

### ISSUE THREAD

**Issue by iFreddyKi** [ilyhalight/voice-over-translation#989]
### Operating system / Операционная система

Windows 10 22H2

### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1

### Describe the bug / Опишите ошибку

Столкнулся с проблемой, которая описана в заголовке, пробовал менять прокси и пользоваться впн, не помогает.

![image](https://github.com/user-attachments/assets/019f4f06-5a8a-4a1f-adb6-493a750bced1)

**Comment by ilyhalight** [comment]
Не фиксится, ограничение со стороны апи
