### ISSUE TITLE
Не отображается иконка переводчика в Ютуб. Дальнейшее использование расширения невозможна

### ISSUE THREAD

**Issue by irmich5546** [ilyhalight/voice-over-translation#990]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.1

### Describe the bug / Опишите ошибку

При установке скрипта в Tampermonkey расширение не показывается в окне видео Ютуба, как не пробуй перезапускать и переустанавливать скрипт, я так и не увидел иконку переводчика

**Comment by irmich5546** [comment]
> ### Operating system / Операционная система
> Windows 10 22H2
> 
> ### Browser / Браузер
> Chrome
> 
> ### Userscript manager / Скриптовый движок
> Tampermonkey
> 
> ### Script version / Версия скрипта
> 1.8.1
> 
> ### Describe the bug / Опишите ошибку
> При установке скрипта в Tampermonkey расширение не показывается в окне видео Ютуба, как не пробуй перезапускать и переустанавливать скрипт, я так и не увидел иконку переводчика
> 
> ### Additional information / Дополнительная информация
> _No response_

**Comment by Mihail-Veresk** [comment]
Исчезла и не отображается иконка Чндекс переводчика с "ютуба" арезапуск отключение скрипта не к чему не приводит

**Comment by ilyhalight** [comment]
Вероятно, у вас не включен режим разработчика необходимый для работы Tampermonkey

**Comment by irmich5546** [comment]
> Вероятно, у вас не включен режим разработчика необходимый для работы Tampermonkey

хде?

**Comment by ilyhalight** [comment]
> > Вероятно, у вас не включен режим разработчика необходимый для работы Tampermonkey
> 
> хде?

https://www.tampermonkey.net/faq.php#Q209
