### ISSUE TITLE
С последнием обновление пропала функция перевода

### ISSUE THREAD

**Issue by gene4000** [ilyhalight/voice-over-translation#995]
### Operating system / Операционная система

windows 7

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.2

### Describe the bug / Опишите ошибку

Сегодня обновился скрипт, и сразу же перестал работать - не отображается кнопка перевода. Я обновил Tempermonkey (теперь версия 5.3.3) в браузере Firefox 115.18.0esr последней версии.  Никакого режима разработчка в Firefox нет. А если и был, то я его сегодня не отключал.

**Comment by gene4000** [comment]
Из другой версии браузера вернул версию 1.8.1 - сразу заработало

**Comment by ilyhalight** [comment]
> Сегодня обновился скрипт, и сразу же перестал работать - не отображается кнопка перевода

что в консоли

**Comment by gene4000** [comment]
> > Сегодня обновился скрипт, и сразу же перестал работать - не отображается кнопка перевода
> 
> что в консоли

вот такая ошибка выдается после попытки запустить видео:
[VOT] Failed to get Yandex subtitles [[VOT]-Voice-Over-Translation.user.js:6898:17](moz-extension://2e945fe5-38ef-4260-96f4-426d244112ae/userscripts/%5BVOT%5D-Voice-Over-Translation.user.js?id=edc4758a-abbe-404b-bd91-5c2ec8cc099c)

**Comment by ilyhalight** [comment]
Это ошибка получения субтитров, когда их нету, это нормально. Других ошибок от расширения нет?

**Comment by gene4000** [comment]
> Это ошибка получения субтитров, когда их нету, это нормально. Других ошибок от расширения нет?

Только такая ошибка от этого скрипта.

**Comment by ilyhalight** [comment]
> > Это ошибка получения субтитров, когда их нету, это нормально. Других ошибок от расширения нет?
> 
> Только такая ошибка от этого скрипта.

В таком случае помочь как-либо не могу, скачал эту же версию браузера и у меня в ней все работает

**Comment by kasatka60** [comment]
Смотрю в книгу(консоль) вижу фигу.

**Comment by ilyhalight** [comment]
> Смотрю в книгу(консоль) вижу фигу.

Если в консоли вообще нету никаких сообщений от скрипта, значит у вас выключен режим разработчика в браузера (либо Tampermonkey забагался и думает, что он выключен). 
Описание как включить есть тут #921, если не помогло переустановите Tampermonkey и юзерскрипт

**Comment by kasatka60** [comment]
Переустановка Tampermonkey помогла. Хотя до этого переустановка самого скрипта перевода - не помогала. Режим разработчика давно включен.
Только теперь кнопка перевода сверху по центру. Раньше она была у левого края и компактная: без фраз "перевести видео"/"отключить перевод" и т.д.

**Comment by ilyhalight** [comment]
> У меня нету юзерскрипта.

я про само расширение voice-over-translation

**Comment by Fludogenerator** [comment]
Windows 10 21H2
Firefox 134.0b10
Tampermonkey 5.3.3

(!) Uncaught (in promise) TypeError: this.data.dontTranslateLanguage.map is not a function
...
...
...

**Comment by ben73** [comment]
У меня тоже перестало работать с последним обновлением. Кнопка перевода не отображается / хоткей не работает. 

Google Chrome 131.0.6778.205 / Mac OS 14.6.1

В консоли такое:
<img width="1271" alt="Снимок экрана 2024-12-28 в 12 35 07" src="https://github.com/user-attachments/assets/5dd07509-f897-4cff-8d73-184f7175809c" />
