### ISSUE TITLE
Нельзя изменить громкость перевода и оригинала через менюшку скрипта

### ISSUE THREAD

**Issue by DmitriyPekar** [ilyhalight/voice-over-translation#996]
### Operating system / Операционная система

Windows 10 21H2

### Browser / Браузер

Firefox

### Userscript manager / Скриптовый движок

Violentmonkey

### Script version / Версия скрипта

1.8.2

### Describe the bug / Опишите ошибку

![librewolf_xuXhHGik6u](https://github.com/user-attachments/assets/5f1d5d80-bbb8-4c3d-ac57-e353f29e3aad)

**Comment by Dionis94** [comment]
Тоже такая же проблема!!!
