### ISSUE TITLE
после обновления на 1,8,2 перестало работать. Помог только откат на 1.8.1

### ISSUE THREAD

**Issue by EDWARDKING68** [ilyhalight/voice-over-translation#997]
### Browser / Браузер

Chrome

### Userscript manager / Скриптовый движок

Tampermonkey

### Script version / Версия скрипта

1.8.2

### Describe the bug / Опишите ошибку

после обновления на 1,8,2 перестало работать. Помог только откат на 1.8.1

**Comment by sergeyklay** [comment]
Попробуйте удалить расширение и скрипт и переустановить все заново. У меня была такая же проблема. Полная переустановка помогла.

**Comment by EDWARDKING68** [comment]
Спасибо, обновился на 1.8.3, всё работает!
